### PR TITLE
fix: Devcontainer resets /etc/hosts (#11439)

### LINKED ISSUE #11439: The container created by Devcontainer keeps resetting /etc/hosts
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

# What happened
Whenever I reboot my computer, /etc/hosts entries added by Devcontainer are gone

```bash
devcontainer up --workspace-folder .
devcontainer exec --workspace-folder . /bin/bash
cat /etc/hosts

#127.0.0.1	localhost
#::1	localhost ip6-localhost ip6-loopback
#fe00::0	ip6-localnet
#ff00::0	ip6-mcastprefix
#ff02::1	ip6-allnodes
#ff02::2	ip6-allrouters
#172.17.0.1	host.docker.internal
#172.17.0.2	be7abe611b1c
#127.0.0.1 dex
#127.0.0.1 minio
#127.0.0.1 postgres
#127.0.0.1 mysql
#127.0.0.1 azurite

reboot
devcontainer up --workspace-folder .
devcontainer exec --workspace-folder . /bin/bash
cat /etc/hosts

#127.0.0.1	localhost
#::1	localhost ip6-localhost ip6-loopback
#fe00::0	ip6-localnet
#ff00::0	ip6-mcastprefix
#ff02::1	ip6-allnodes
#ff02::2	ip6-allrouters
#172.17.0.1	host.docker.internal
#172.17.0.2	be7abe611b1c
```
# What I expect
/etc/hosts should be preserved

# Why it happens
That's Because Devcontainer's container is running with bridge networking 
https://stackoverflow.com/questions/27521678/etc-hosts-file-of-a-docker-container-gets-overwritten

# How to fix It
~~https://code.visualstudio.com/remote/advancedcontainers/start-processes~~
~~Add postStartCommand field that adds /etc/hosts entries to devcontainer.json~~
Add --add-host options as runArgs in devcontainer.json

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
none
```

### Logs from the workflow controller

```text
none
```

### Logs from in your workflow's wait container

```text
none
```

### PR DESCRIPTION
**Pull request by binkoni**
Fixes #11439 

### Motivation

A container created by Devcontainer keeps resetting /etc/hosts whenever I reboot or restart the container.

### Modifications

.devcontainer/devcontainer.json
.devcontainer/pre-build.sh
~~.devcontainer/post-start.sh~~

### Verification

To ensure this issue is fixed, I manually tested by running devcontainer commands that after I made this change.
I also tested with VsCode devcontainer extension.

### CODE REVIEW

File: .devcontainer/post-start.sh [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#!/usr/bin/env sh
+set -eux
+
+# Add hosts
+sudo bash -c 'echo "127.0.0.1 dex" >> /etc/hosts'
+sudo bash -c 'echo "127.0.0.1 minio" >> /etc/hosts'
+sudo bash -c 'echo "127.0.0.1 postgres" >> /etc/hosts'
+sudo bash -c 'echo "127.0.0.1 mysql" >> /etc/hosts'
+sudo bash -c 'echo "127.0.0.1 azurite" >> /etc/hosts'
```
Comment (agilgur5) [inline .devcontainer/post-start.sh:9]: what if these entries already exist in `/etc/hosts`? these may end up getting listed twice as a result. that won't break anything, but may want to check the file first

Comment (binkoni) [reply .devcontainer/post-start.sh]: Thanks for the review! I think it's impossible for the entries to already exist. Because when the container restarts it wipes the entries added by the script. But when we suppose that the entries already exist for some reason, that will add duplicate entries.
So I changed the code to make it more reliable by adding --add-host options as runArgs in devcontainer.json instead of using postStartCommand

Comment (agilgur5) [reply .devcontainer/post-start.sh]: Oh good idea on `--add-host`!

If someone configured different networking or used a different client, there could be some overlap. But in general, just better to be safer if we can make the code purely additive without much effort

**Review by agilgur5 — APPROVED** [review]
Good change! Thanks for the contribution!

**Review by terrytangyuan — APPROVED** [review]
