### PR TITLE
fix(ui): retain query parameters when closing workflow side panel. Fixes #15795

### LINKED ISSUE #15795: UI: closing the "submit-new-workflow" sidepanel on the workflows list page removes parameters from the URL
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

While reviewing #15217 I saw that opening and closing the sidepanel removes all the filter parameters from the URL. Unexpected behaviour and is a small quality of life fix. The issue is because of:
https://github.com/argoproj/argo-workflows/blob/5456d80f25c2437c4d717e6e5f266e26ab496449/ui/src/workflows/components/workflows-list/workflows-list.tsx#L365-L368

The whole side panel implementation on the workflows list page is a bit weird compared to the workflow template list. It can be tidied up to match.

### Version(s)

latest main (5456d80f25c2437c4d717e6e5f266e26ab496449)

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
* Add some filter parameters (phase)
* Click "submit new workflow"
* Close the side panel
* Observe the URL removing the filter parameters
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by elliotgunton**
Fixes #15795

### Motivation

As part of various improvements (#15217, #15796) to the URL parameters experience, this fixes the bug where the query parameters are wiped out when closing the side panel (to submit a new workflow).

### Modifications

* Update the side panel handling code to match the workflow template page
* Retain query parameters `onClose` (by just updating the `sidePanel` variable)

### Verification

Showing parameters are retained:

https://github.com/user-attachments/assets/21dc7785-6e70-45de-bc27-27a680f504fa

Also showing that opening the side panel, closing it (by clicking off) and then using the back button of the browser reopens it:

https://github.com/user-attachments/assets/386a20d2-1443-416f-8fec-68ed6c0b39fb

### CODE REVIEW

File: ui/src/workflows/components/workflows-list/workflows-list.tsx [hunk 1]
```diff
@@ -60,6 +60,7 @@ export function WorkflowsList({match, location, history}: RouteComponentProps<an
 
     const isFirstRender = useRef(true);
     const [namespace, setNamespace] = useState(nsUtils.getNamespace(match.params.namespace) || '');
+    const [sidePanel, setSidePanel] = useState(queryParams.get('sidePanel') || '');
```
Comment (MasonM) [inline ui/src/workflows/components/workflows-list/workflows-list.tsx:65]: Moving `sidePanel` to the React state is a good idea, but this breaks the back button, since it won't re-opened the side panel after it's been closed. Steps to reproduce:
1. Visit http://localhost:8080/workflows
2. Click "Submit New Workflow"
3. Click "Close"
4. Click the back button in your browser
5. Notice the sidepanel isn't re-opened. Compare that behavior to the workflow templates page (http://localhost:8080/workflow-templates)

I believe the fix will involve `useQueryParams()`, e.g. https://github.com/argoproj/argo-workflows/blob/dbeccfc06a295b2f186510af9fed14e40f19a9d9/ui/src/workflow-templates/workflow-template-list.tsx#L59-L64

Comment (elliotgunton) [reply ui/src/workflows/components/workflows-list/workflows-list.tsx:65]: I've added a fix based on your suggestion ~but getting the issue that the back button now needs to be clicked twice to reopen the sidepanel. Looking into whether it's related to #15796 (i.e. if it can be fixed by rebasing on that)~

Comment (elliotgunton) [reply ui/src/workflows/components/workflows-list/workflows-list.tsx:65]: Fixed by normalising the `p.get('sidePanel')`

```ts
    useEffect(
        useQueryParams(history, p => {
            setSidePanel(p.get('sidePanel') || '');
        }),
        [history]
    );
```


https://github.com/user-attachments/assets/386a20d2-1443-416f-8fec-68ed6c0b39fb

File: ui/src/workflows/components/workflows-list/workflows-list.tsx [hunk 2]
```diff
@@ -157,7 +169,7 @@ export function WorkflowsList({match, location, history}: RouteComponentProps<an
             historyUrl('workflows' + (nsUtils.getManagedNamespace() ? '' : '/{namespace}'), {namespace, extraSearchParams: params})
         );
         isFirstRender.current = false;
-    }, [namespace, phases.toString(), labels.toString(), pagination.limit, pagination.offset, nameValue, nameFilter, createdAfter, finishedBefore]); // referential equality, so use values, not refs
+    }, [namespace, phases.toString(), labels.toString(), pagination.limit, pagination.offset, nameValue, nameFilter, createdAfter, finishedBefore, sidePanel]); // referential equality, so use values, not refs
```
Comment (MasonM) [inline ui/src/workflows/components/workflows-list/workflows-list.tsx]: I accidentally inserted some whitespace when I was resolving the merge conflict: 
```suggestion
    }, [namespace, phases.toString(), labels.toString(), pagination.limit, pagination.offset, nameValue, nameFilter, createdAfter, finishedBefore, sidePanel]); // referential equality, so use values, not refs
```

File: ui/src/workflows/components/workflows-list/workflows-list.tsx [hunk 3]
```diff
@@ -135,7 +141,13 @@ export function WorkflowsList({match, location, history}: RouteComponentProps<an
         }
         storage.setItem('options', options, {} as WorkflowListRenderOptions);
 
-        const params = new URLSearchParams(history.location.search);
+        const params = new URLSearchParams();
```
Comment (MasonM) [inline ui/src/workflows/components/workflows-list/workflows-list.tsx:144]: It looks like the functionality added in https://github.com/argoproj/argo-workflows/pull/13922 to allow pre-filling workflows parameters in the URL is broken, and I suspect it's because of the removal of `history.location.search` in this line. Steps to reproduce:
1. Visit http://localhost:8080/workflows?namespace=argo&limit=50&sidePanel=submit-new-workflow&template=delightful-python&parameters%5Bmessage%5D=test-hello, replacing `delightful-python` with a valid workflow template name
2. Notice the side panel opens, but doesn't auto-fill the workflow template and `message` parameter. On the `main` branch, you should see this: 

Image

Comment (MasonM) [reply ui/src/workflows/components/workflows-list/workflows-list.tsx:144]: I entered https://github.com/argoproj/argo-workflows/pull/15820 to add some unit tests for this component, including a test for this bug. Please add a test for the changes here once that's merged.

Comment (elliotgunton) [reply ui/src/workflows/components/workflows-list/workflows-list.tsx:144]: Noted, will take a look!

Comment (elliotgunton) [reply ui/src/workflows/components/workflows-list/workflows-list.tsx:144]: Fixed and test added! That pre-filling code looks a bit strange to me, and it doesn't update the URL when you select the template. Could be a good target for a refactor/tidy up.
