### PR TITLE
fix(executor): Fix emissary kill. Fixes #6030

### LINKED ISSUE #6030: pns executor w/ security context not working with vault injector
I'm using vault injector with pns executor. It works fine until I add security context to not run as root. Vault sidecar container not getting killed. Details below.

```
apiVersion: v1
data:
  containerRuntimeExecutor: pns
  workflowDefaults: |
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 8737
```

```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-clone
spec:
  ...
  templates:
    - name: git-clone
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: "{{inputs.parameters.repo}}"
              revision: "{{inputs.parameters.revision}}"
              usernameSecret:
                name: github-creds
                key: username
              passwordSecret:
                name: github-creds
                key: password
      metadata:
        annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/role: "xxxx
          vault.hashicorp.com/auth-path: "xxx"
          vault.hashicorp.com/secret-volume-path: "/tmp/vault"
          vault.hashicorp.com/agent-inject-secret-npmrc: "xxx"
          vault.hashicorp.com/agent-inject-template-npmrc: |
            {{- with secret "xxx" -}}
              {{ .Data.data.npmrc }}
            {{- end }}
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |-
                cp /tmp/vault/secrets/npmrc ./.npmrc

        volumeMounts:
          - name: tmp
            mountPath: /tmp
        workingDir: /src
      volumes:
        - name: tmp
          emptyDir: {}
      outputs:
        artifacts:
          - name: src
            path: /src
            globalName: src
```

```
time="2021-05-26T23:08:58.651Z" level=info msg="Starting Workflow Executor" executorType=pns version=v3.1.0-rc8
time="2021-05-26T23:08:58.655Z" level=info msg="Creating PNS executor (namespace: argo, pod: ci-4fqjw-539851645, pid: 66)"
time="2021-05-26T23:08:58.655Z" level=info msg="Creating a K8sAPI executor"
time="2021-05-26T23:08:58.655Z" level=info msg="Executor (version: v3.1.0-rc8, build_date: 2021-05-25T15:15:42Z) initialized (pod: argo/ci-4fqjw-539851645) with template:\n{\"name\":\"git-clone\",\"inputs\":{\"parameters\":[{\"name\":\"repo\",\"value\":\"https://github.com/Forbes-Media/dp-seal.git\"},{\"name\":\"revision\",\"value\":\"main\"},{\"name\":\"generate-artifactory-credentials\",\"value\":\"false\"}],\"artifacts\":[{\"name\":\"argo-source\",\"path\":\"/src\",\"git\":{\"repo\":\"https://github.com/Forbes-Media/dp-seal.git\",\"revision\":\"main\",\"usernameSecret\":{\"name\":\"github-creds\",\"key\":\"username\"},\"passwordSecret\":{\"name\":\"github-creds\",\"key\":\"password\"}}}]},\"outputs\":{\"artifacts\":[{\"name\":\"src\",\"path\":\"/src\",\"globalName\":\"src\"},{\"name\":\"git-labels\",\"path\":\"/tmp/git-labels\",\"globalName\":\"git-labels\"}]},\"metadata\":{\"annotations\":{\"vault.hashicorp.com/agent-inject\":\"true\",\"vault.hashicorp.com/agent-inject-secret-npmrc\":\"kv/data/operations/argo/jfrog\",\"vault.hashicorp.com/agent-inject-template-npmrc\":\"{{- with secret \\\"kv/data/operations/argo/jfrog\\\" -}}\\n  {{ .Data.data.npmrc }}\\n{{- end }}\\n\",\"vault.hashicorp.com/auth-path\":\"/auth/development-playground\",\"vault.hashicorp.com/role\":\"operations-read-only\",\"vault.hashicorp.com/secret-volume-path\":\"/tmp/vault\"}},\"container\":{\"name\":\"\",\"image\":\"forbes-docker.jfrog.io/alpine/git:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"if [[ \\\"false\\\" == \\\"true\\\" ]]; then\\n  cp /tmp/vault/secrets/npmrc ./.npmrc\\nfi\\n# spaces bad for clobber-args\\n# GIT_AUTHOR_NAME=$(git log -1 --pretty=format:'%an')\\nGIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')\\n# GIT_COMMIT_MESSAGE=$(git log -1 --pretty=%B | head -1)\\nGIT_COMMIT_HASH=$(git log -1 --format=\\\"%H\\\")\\nOUTPUT=/tmp/git-labels\\necho \\\"GIT_REPO=\\\\\\\"https://github.com/Forbes-Media/dp-seal.git\\\\\\\"\\\" | tee -a ${OUTPUT}\\necho \\\"GIT_REVISION=\\\\\\\"main\\\\\\\"\\\" | tee -a ${OUTPUT}\\n# echo \\\"GIT_AUTHOR_NAME=\\\\\\\"${GIT_AUTHOR_NAME}\\\\\\\"\\\" | tee -a ${OUTPUT}\\necho \\\"GIT_AUTHOR_EMAIL=\\\\\\\"${GIT_AUTHOR_EMAIL}\\\\\\\"\\\" | tee -a ${OUTPUT}\\n# echo \\\"GIT_COMMIT_MESSAGE=\\\\\\\"${GIT_COMMIT_MESSAGE}\\\\\\\"\\\" | tee -a ${OUTPUT}\\necho \\\"GIT_COMMIT_HASH=\\\\\\\"${GIT_COMMIT_HASH}\\\\\\\"\\\" | tee -a ${OUTPUT}\"],\"workingDir\":\"/src\",\"resources\":{},\"volumeMounts\":[{\"name\":\"tmp\",\"mountPath\":\"/tmp\"}]},\"volumes\":[{\"name\":\"tmp\",\"emptyDir\":{}}],\"archiveLocation\":{\"gcs\":{\"bucket\":\"argo-artifact-repository\",\"key\":\"ci-4fqjw/ci-4fqjw-539851645\"}}}"
time="2021-05-26T23:08:58.655Z" level=info msg="Starting annotations monitor"
time="2021-05-26T23:08:58.655Z" level=info msg="Starting deadline monitor"
time="2021-05-26T23:08:59.717Z" level=warning msg="failed to secure root file handle for 82" error="open /proc/82/root: permission denied"
time="2021-05-26T23:08:59.768Z" level=warning msg="failed to secure root file handle for 82" error="open /proc/82/root: permission denied"
time="2021-05-26T23:08:59.921Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/root: permission denied"
time="2021-05-26T23:08:59.971Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/root: permission denied"
time="2021-05-26T23:09:00.022Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.022Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.073Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.073Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.124Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.124Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.174Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.174Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.225Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.225Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.276Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.276Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.326Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.326Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.377Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.377Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.428Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.428Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.478Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.478Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.529Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.529Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.580Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.580Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.631Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.631Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.681Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.681Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.732Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.732Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.782Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.783Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.833Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.833Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.884Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.884Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.935Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.935Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:00.985Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:00.985Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.037Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.037Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.088Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.088Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.138Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.139Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.189Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.189Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.240Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.240Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.291Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.291Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.341Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.341Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.392Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.392Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.443Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.443Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.494Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.494Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.544Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.544Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.595Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.595Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.646Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.646Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.696Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.696Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.747Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.747Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.798Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.798Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.848Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.848Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.899Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.899Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:01.950Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:01.950Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.001Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.001Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.052Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.052Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.102Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.102Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.153Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.153Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.204Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.204Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.254Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.254Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.305Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.305Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.356Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.356Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.406Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.406Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.457Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.457Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.508Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.508Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.559Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.559Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.609Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.609Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.660Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.660Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.711Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.711Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.762Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.762Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.812Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.812Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.863Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.863Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.913Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.914Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:02.964Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:02.964Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.015Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.015Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.065Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.065Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.116Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.116Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.167Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.167Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.217Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.217Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.268Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.268Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.319Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.319Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.369Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.370Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.420Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.420Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.471Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.471Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.521Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.521Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.572Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.572Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.623Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.623Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.664Z" level=info msg="Watch pods 200"
time="2021-05-26T23:09:03.674Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.674Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.676Z" level=info msg="Main container completed"
time="2021-05-26T23:09:03.677Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-05-26T23:09:03.677Z" level=info msg="No output parameters"
time="2021-05-26T23:09:03.677Z" level=info msg="Saving output artifacts"
time="2021-05-26T23:09:03.677Z" level=info msg="Staging artifact: src"
time="2021-05-26T23:09:03.677Z" level=info msg="Staging /src from mirrored volume mount /mainctrfs/src"
time="2021-05-26T23:09:03.677Z" level=info msg="Taring /mainctrfs/src"
time="2021-05-26T23:09:03.725Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.725Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.776Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.776Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.826Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.826Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.877Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.877Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.928Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.928Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:03.979Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:03.979Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.030Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.030Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.080Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.081Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.131Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.131Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.182Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.182Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.233Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.233Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.284Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.284Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.335Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.335Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.385Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.386Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.436Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.436Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.487Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.487Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.538Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.538Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.589Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.589Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.639Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.639Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.642Z" level=info msg="archived 82 files/dirs in /mainctrfs/src"
time="2021-05-26T23:09:04.642Z" level=info msg="Successfully staged /src from mirrored volume mount /mainctrfs/src"
time="2021-05-26T23:09:04.642Z" level=info msg="GCS Save path: /tmp/argo/outputs/artifacts/src.tgz, key: ci-4fqjw/ci-4fqjw-539851645/src.tgz"
time="2021-05-26T23:09:04.690Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.690Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.741Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.741Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.793Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.793Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.843Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.843Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.894Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.894Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.945Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.945Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:04.995Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:04.995Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.046Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.046Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.097Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.097Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.148Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.148Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.198Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.198Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.249Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.249Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.300Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.300Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.351Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.351Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.401Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.401Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.452Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.452Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.503Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.503Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.554Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.554Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.574Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/src.tgz
time="2021-05-26T23:09:05.574Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/src.tgz"
time="2021-05-26T23:09:05.574Z" level=info msg="Staging artifact: git-labels"
time="2021-05-26T23:09:05.574Z" level=info msg="Staging /tmp/git-labels from mirrored volume mount /mainctrfs/tmp/git-labels"
time="2021-05-26T23:09:05.574Z" level=info msg="Taring /mainctrfs/tmp/git-labels"
time="2021-05-26T23:09:05.576Z" level=info msg="Successfully staged /tmp/git-labels from mirrored volume mount /mainctrfs/tmp/git-labels"
time="2021-05-26T23:09:05.576Z" level=info msg="GCS Save path: /tmp/argo/outputs/artifacts/git-labels.tgz, key: ci-4fqjw/ci-4fqjw-539851645/git-labels.tgz"
time="2021-05-26T23:09:05.604Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.604Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.655Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.655Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.706Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.706Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.729Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/git-labels.tgz
time="2021-05-26T23:09:05.729Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/git-labels.tgz"
time="2021-05-26T23:09:05.729Z" level=info msg="Annotating pod with output"
time="2021-05-26T23:09:05.757Z" level=info msg="secured root for pid 97 root: vault (\"/proc/97/root\")"
time="2021-05-26T23:09:05.757Z" level=warning msg="failed to secure root file handle for 97" error="open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.767Z" level=info msg="Patch pods 200"
time="2021-05-26T23:09:05.769Z" level=error msg="executor error: failed to get container name for process 97: open /proc/97/environ: permission denied"
time="2021-05-26T23:09:05.769Z" level=info msg="Alloc=22385 TotalAlloc=60246 Sys=73297 NumGC=8 Goroutines=13"
```

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>
Fixes #6030

### CODE REVIEW

File: workflow/signal/signal.go [hunk 1]
```diff
@@ -1,17 +1,35 @@
...
 	log "github.com/sirupsen/logrus"
 	"k8s.io/client-go/rest"
 
 	"github.com/argoproj/argo-workflows/v3/workflow/common"
 )
 
-func SignalContainer(restConfig *rest.Config, namespace string, pod string, container string, s syscall.Signal) error {
-	return ExecPodContainerAndGetOutput(restConfig, namespace, pod, container, "/bin/sh", "-c", fmt.Sprintf("kill -s%d -- -1", s))
+func SignalContainer(restConfig *rest.Config, pod *corev1.Pod, container string, s syscall.Signal) error {
+	command := []string{"/bin/sh", "-c", "kill -%d 1"}
```
Comment (alexec) [inline workflow/signal/signal.go:18]: this line changes the default kill cmd

File: workflow/signal/signal.go [hunk 2]
```diff
@@ -20,6 +38,13 @@ func ExecPodContainerAndGetOutput(restConfig *rest.Config, namespace string, pod
 		return err
 	}
 	stdout, stderr, err := common.GetExecutorOutput(x)
-	log.WithFields(log.Fields{"stdout": stdout, "stderr": stderr}).WithError(err).Debug()
+	log.
```
Comment (alexec) [inline workflow/signal/signal.go:41]: extra logging

**Comment by alexec** [comment]
@whynowy please review?

**Comment by whynowy** [comment]
Does it fix the issue #6030? It looks like the user says it's still not working.

**Comment by alexec** [comment]
@rwong2888 is using an RC with does not have this fix on it.

**Review by whynowy — APPROVED** [review]
