### PR TITLE
fix(executor): allow emptyRepo artifact input. Fixes #5857

### LINKED ISSUE #5857: Unable to clone empty repository
## Summary 

When cloning empty repo via input artifacts there's an error:

`executor error: remote repository is empty`

It should be possible to clone empty repositories. This comes up especially if a workflow is used to create new repositories through eg. Bitbucket API, and then committing to those.

### PR DESCRIPTION
**Pull request by tczhao**
Fixes #5857

Tips:

* Maybe add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).
* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.
* If changes were requested, and you've made them, then dismis the review to get it looked at again.
* You can ask for help!

### CODE REVIEW

File: workflow/artifacts/git/git_test.go [hunk 1]
```diff
@@ -13,24 +13,29 @@ import (
...
-	err := driver.Load(&wfv1.Artifact{
-		ArtifactLocation: wfv1.ArtifactLocation{
-			Git: &wfv1.GitArtifact{
-				Repo:     "https://github.com/argoproj/argoproj.git",
-				Fetch:    []string{"+refs/heads/*:refs/remotes/origin/*"},
-				Revision: "HEAD",
-				Depth:    &d,
+	for _, url := range []string{
+		"https://github.com/argoproj/argo-workflows.git",
+		"https://github.com/tczhao/empty-repo.git",
```
Comment (tczhao) [inline workflow/artifacts/git/git_test.go:18]: maybe we need a argoproj empty repo?

Comment (alexec) [reply workflow/artifacts/git/git_test.go:18]: https://github.com/argoproj/empty

Comment (tczhao) [reply workflow/artifacts/git/git_test.go]: since its a private repo

added to
- TestGitArtifactDriverLoad_SSL
- TestGitArtifactDriverLoad_HTTPS

skip
- TestGitArtifactDriver_Load

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Thank you!
