### PR TITLE
fix(containerSet): mark container deleted when pod deleted. Fixes: #12210

### LINKED ISSUE #12210: ContainerSet does not stop container task when Pod is removed
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I experience stuck workflows when using containerSet and pod gets deleted while workflow is running. This workflow is in running state and never finishes it also not possible to stop the workflow.

To reproduce run workflow example and delete the pod running the workflow.

### Version

v.3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: lovely-rhino
spec:
  templates:
    - name: init
      dag:
        tasks:
          - name: A
            template: run
            arguments: {}
    - name: run
      containerSet:
        containers:
          - name: main
            image: alpine:latest
            command:
              - /bin/sh
            args:
              - '-c'
              - sleep 9000
            resources: {}
  entrypoint: init
  arguments: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
time="2023-11-16T00:24:51.907Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:51.955Z" level=info msg="Updated phase  -> Running" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:51.955Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:51.955Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:51.955Z" level=info msg="DAG node lovely-rhino-6452p initialized Running" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:51.955Z" level=warning msg="was unable to obtain the node for lovely-rhino-6452p-4192128298, taskName A"
time="2023-11-16T00:24:51.955Z" level=warning msg="was unable to obtain the node for lovely-rhino-6452p-4192128298, taskName A"
time="2023-11-16T00:24:51.955Z" level=info msg="All of node lovely-rhino-6452p.A dependencies [] completed" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:51.955Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:51.955Z" level=info msg="Pod node lovely-rhino-6452p-4192128298 initialized Pending" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:52.002Z" level=info msg="Created pod: lovely-rhino-6452p.A (lovely-rhino-6452p-run-4192128298)" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:52.003Z" level=info msg="Container node lovely-rhino-6452p-1411179001 initialized Pending" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:52.003Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:52.003Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:24:52.019Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=594776568 workflow=lovely-rhino-6452p
time="2023-11-16T00:25:02.005Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:25:02.005Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lovely-rhino-6452p
time="2023-11-16T00:25:02.005Z" level=info msg="node lovely-rhino-6452p-1411179001 phase Pending -> Running" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:25:02.005Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Running new.progress=0/1 nodeID=lovely-rhino-6452p-4192128298 old.message= old.phase=Pending old.progress=0/1 workflow=lovely-rhino-6452p
time="2023-11-16T00:25:02.005Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:25:02.005Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:25:02.024Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=594776713 workflow=lovely-rhino-6452p
time="2023-11-16T00:25:12.025Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:25:12.025Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lovely-rhino-6452p
time="2023-11-16T00:25:12.025Z" level=info msg="node unchanged" namespace=argo-workflows nodeID=lovely-rhino-6452p-4192128298 workflow=lovely-rhino-6452p
time="2023-11-16T00:25:12.025Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:25:12.025Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.316Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.317Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.317Z" level=info msg="Workflow pod is missing" namespace=argo-workflows nodeName=lovely-rhino-6452p.A nodePhase=Running recentlyStarted=false workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.317Z" level=info msg="node lovely-rhino-6452p-4192128298 phase Running -> Error" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.317Z" level=info msg="node lovely-rhino-6452p-4192128298 message: pod deleted" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.317Z" level=info msg="node lovely-rhino-6452p-4192128298 finished: 2023-11-16 00:26:14.317181368 +0000 UTC" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.317Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.317Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:14.337Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=594777738 workflow=lovely-rhino-6452p
time="2023-11-16T00:26:24.338Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:24.338Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lovely-rhino-6452p
time="2023-11-16T00:26:24.339Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lovely-rhino-6452p
time="2023-11-16T00:26:24.339Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lovely-rhino-6452p
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by shuangkun**
Fixes #12210 

### Motivation

Avoid incorrect judgment that dag running causes workflow hang. The fundamental reason is that when the pod is cleaned up, the container is not still displayed as running, which causes the dag to be judged as running in assessDAGPhase.

### Modifications

Set container node error instead of  running when pod was deleted.

### Verification

test local and e2e.

Before, pod delete but container running:
```yaml
    lovely-rhino-544408588:
      boundaryID: lovely-rhino
      children:
      - lovely-rhino-3630214831
      - lovely-rhino-1026744615
      displayName: A
      finishedAt: "2024-03-07T07:07:07Z"
      hostNodeName: kind-control-plane
      id: lovely-rhino-544408588
      message: pod deleted
      name: lovely-rhino.A
      outputs:
        artifacts:
        - name: main-logs
          s3:
            key: lovely-rhino/lovely-rhino-run-544408588/main.log
        - name: main2-logs
          s3:
            key: lovely-rhino/lovely-rhino-run-544408588/main2.log
      phase: Error
      progress: 0/1
      startedAt: "2024-03-07T07:06:34Z"
      templateName: run
      templateScope: local/lovely-rhino
      type: Pod
    lovely-rhino-1026744615:
      boundaryID: lovely-rhino-544408588
      displayName: main2
      finishedAt: null
      id: lovely-rhino-1026744615
      name: lovely-rhino.A.main2
      phase: Running
      progress: 0/1
      startedAt: "2024-03-07T07:06:34Z"
      templateName: run
      templateScope: local/lovely-rhino
      type: Container
    lovely-rhino-3630214831:
      boundaryID: lovely-rhino-544408588
      displayName: main
      finishedAt: null
      id: lovely-rhino-3630214831
      name: lovely-rhino.A.main
      phase: Running
      progress: 0/1
      startedAt: "2024-03-07T07:06:34Z"
      templateName: run
      templateScope: local/lovely-rhino
      type: Container
  phase: Running
```
After fix:
```yaml
      lovely-rhino-544408588:
        boundaryID: lovely-rhino
        children:
        - lovely-rhino-3630214831
        - lovely-rhino-1026744615
        displayName: A
        finishedAt: "2024-03-07T07:25:56Z"
        hostNodeName: kind-control-plane
        id: lovely-rhino-544408588
        message: pod deleted
        name: lovely-rhino.A
        outputs:
          artifacts:
          - name: main-logs
            s3:
              key: lovely-rhino/lovely-rhino-run-544408588/main.log
          - name: main2-logs
            s3:
              key: lovely-rhino/lovely-rhino-run-544408588/main2.log
        phase: Error
        progress: 0/1
        startedAt: "2024-03-07T07:25:32Z"
        templateName: run
        templateScope: local/lovely-rhino
        type: Pod
      lovely-rhino-1026744615:
        boundaryID: lovely-rhino-544408588
        displayName: main2
        finishedAt: "2024-03-07T07:25:56Z"
        id: lovely-rhino-1026744615
        message: container deleted
        name: lovely-rhino.A.main2
        phase: Error
        progress: 0/1
        startedAt: "2024-03-07T07:25:33Z"
        templateName: run
        templateScope: local/lovely-rhino
        type: Container
      lovely-rhino-3630214831:
        boundaryID: lovely-rhino-544408588
        displayName: main
        finishedAt: "2024-03-07T07:25:56Z"
        id: lovely-rhino-3630214831
        message: container deleted
        name: lovely-rhino.A.main
        phase: Error
        progress: 0/1
        startedAt: "2024-03-07T07:25:33Z"
        templateName: run
        templateScope: local/lovely-rhino
        type: Container
    phase: Error
```

### CODE REVIEW

File: workflow/controller/operator_test.go [hunk 1]
```diff
@@ -10335,3 +10335,91 @@ func TestWorkflowNeedReconcile(t *testing.T) {
...
+	woc = newWorkflowOperationCtx(woc.wf, controller)
+	woc.operate(ctx)
+	for _, node := range woc.wf.Status.Nodes {
+		if node.Type == wfv1.NodeTypePod {
+			assert.Equal(t, wfv1.NodeRunning, node.Phase)
+		}
+	}
+
+	// delete pod
+	time.Sleep(10 * time.Second)
```
Comment (tczhao) [inline workflow/controller/operator_test.go:10406]: use
`_ = os.Setenv("RECENTLY_STARTED_POD_DURATION", "0")`
and 
set graceperiod to 0 on `metav1.DeleteOptions{` in `deletePods` function

so that we can get rid of time.sleep here

**Review by tczhao — CHANGES_REQUESTED** [review]

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -1223,6 +1223,17 @@ func (woc *wfOperationCtx) podReconciliation(ctx context.Context) (error, bool)
...
 			woc.markNodePhase(node.Name, wfv1.NodeError, "pod deleted")
+			// Set pod's child(container) error if pod deleted
+			for _, childNodeID := range node.Children {
+				childNode, err := woc.wf.Status.Nodes.Get(childNodeID)
+				if err != nil {
+					woc.log.Errorf("was unable to obtain node for %s", childNodeID)
+					continue
+				}
+				if childNode.Type == wfv1.NodeTypeContainer {
+					woc.markNodePhase(childNode.Name, wfv1.NodeError, "container deleted")
```
[the remark this answers is not in the document]
Comment (shuangkun) [reply workflow/controller/operator.go]: OK, I change it.

File: workflow/controller/operator_test.go (hunk 1 above)
Comment (shuangkun) [reply workflow/controller/operator_test.go]: Yeah,  I add it. Thanks!

**Review by tczhao — APPROVED** [review]

**Comment by agilgur5** [comment]
> containerset does not stop container when pod removed.

> The fundamental reason is that when the pod is cleaned up, the container is not still displayed as running, which causes the dag to be judged as running in assessDAGPhase.

> Set container node error instead of running when pod was deleted.

To make sure I understand this correctly -- the Pod and container were correctly stopped, but the container's `status` node was incorrectly marked?

If so, we should retitle this -- the container was stopped and is not running, it's just incorrectly marked as running.

File: workflow/controller/operator_test.go (hunk 1 above)
Comment (agilgur5) [reply workflow/controller/operator_test.go]: > use
> `_ = os.Setenv("RECENTLY_STARTED_POD_DURATION", "0")`

This sets it for the whole process though, no? not just this single test?

File: workflow/controller/operator_test.go [hunk 3]
```diff
@@ -10803,3 +10803,91 @@ status:
...
+            resources: {}
+  entrypoint: init
+  arguments: {}
+  ttlStrategy:
+    secondsAfterCompletion: 300
+  podGC:
+    strategy: OnPodCompletion`
+
+// TestContainerSetDoesNotStopContainerWhenPodRemoved test whether a workflow has ContainerSet error when pod removed.
+func TestContainerSetDoesNotStopContainerWhenPodRemoved(t *testing.T) {
```
Comment (agilgur5) [inline workflow/controller/operator_test.go:10847]:
```suggestion
// TestContainerSetStopContainerWhenPodRemoved tests that a workflow has ContainerSet error when pod deleted.
func TestContainerSetDeleteContainerWhenPodDeleted(t *testing.T) {
```

the test checks that it _is_ stopped, or, rather deleted, more specifically

File: workflow/controller/operator.go [hunk 4]
```diff
@@ -1224,6 +1224,17 @@ func (woc *wfOperationCtx) podReconciliation(ctx context.Context) (error, bool)
 				woc.updated = true
 			}
 			woc.markNodePhase(node.Name, wfv1.NodeError, "pod deleted")
```
Comment (agilgur5) [inline workflow/controller/operator.go:1226]: this should probably also use `markNodeError` while we're making this modification
```suggestion
			woc.markNodeError(node.Name, errors.New("pod deleted"))
```

File: workflow/controller/operator_test.go (hunk 1 above)
Comment (shuangkun) [reply workflow/controller/operator_test.go]: Sigle and i remove it after test.

Comment (agilgur5) [reply workflow/controller/operator_test.go]: That's not quite sufficient. Env vars are set for an entire process -- meaning it affects any tests that are ran in parallel and use the same env var. But I wasn't sure if Go had any special handling for this given that I've seen this in other tests. According to Go's own docs (for the [`t.Setenv` function](https://pkg.go.dev/testing#B.Setenv)), it does not have any special handling and this would indeed affect any parallel tests.

While this is done in other tests in this codebase ([50 occurrences](https://github.com/search?q=repo%3Aargoproj%2Fargo-workflows%20os.setenv&type=code)) which probably need a larger refactoring, this env var is a bit more global in its effects.

This is one of those reasons why config shouldn't be set purely in global-scoped env vars, as it can lead to races like this, particularly with test code that relies on globals.

Comment (shuangkun) [reply workflow/controller/operator_test.go:10874]: removed it, and i test sleep 5s is not enough. need 10s

Comment (agilgur5) [reply workflow/controller/operator_test.go:10874]: hmm, not needing to `sleep` in the tests is good to have though... @tczhao what do you think? 

perhaps we leave one in and then refactor in a separate PR to avoid globals?

Comment (tczhao) [reply workflow/controller/operator_test.go:10874]: > removed it, and i test sleep 5s is not enough. need 10s

The 10s is due to `RECENTLY_STARTED_POD_DURATION` defaults to 10s,
`podReconciliation` will not update the wf status until `RECENTLY_STARTED_POD_DURATION` elapsed
https://github.com/argoproj/argo-workflows/blob/v3.5.5/workflow/controller/operator.go#L1209

---

> perhaps we leave one in and then refactor in a separate PR to avoid globals?

Sounds good to me

Comment (agilgur5) [reply workflow/controller/operator_test.go:10874]: Let's make sure to add a `// TODO:` comment here to modify this in the future. Can reference this thread in the comment: https://github.com/argoproj/argo-workflows/pull/12756#discussion_r1530245007.
This would be a really easy follow-up to miss (and may not  happen soon), so being explicit is good (and `TODO`s can be searched for in the codebase easily)

File: workflow/controller/operator_test.go [hunk 5]
```diff
@@ -10870,6 +10870,7 @@ func TestContainerSetDeleteContainerWhenPodDeleted(t *testing.T) {
 		}
 	}
 
+	// TODO: Enable use local variables in the test to avoid long wait. See https://github.com/argoproj/argo-workflows/pull/12756#discussion_r1530245007
```
Comment (agilgur5) [inline workflow/controller/operator_test.go:10873]:
```suggestion
	// TODO: Refactor to use local-scoped env vars in test to avoid long wait. See https://github.com/argoproj/argo-workflows/pull/12756#discussion_r1530245007
```

Small clarification

**Review by agilgur5 — APPROVED** [review]
Thanks for tracking this down, fixing it, and adding a regression test!

**Comment by shuangkun** [comment]
> Thanks for tracking this down, fixing it, and adding a regression test!

Thany you and @tczhao ,  thank you for your suggestions！

**Comment by agilgur5** [comment]
Backported cleanly to `release-3.5` as faaddf3ac
