### PR TITLE
fix: Capture exit code of signaled containers. Fixes #9415

### LINKED ISSUE #9415: Argo-Exec V3.3.9 is recognising a failure exit code as exitCode 0
## Checklist

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Dotnet console app running in Argo, Exception occurs and container terminates. Argo recognises this as Success in version 3.3.9. In previous versions v3.3.7 and v3.3.8 Argo correctly recognises this as a failure. Note that if I run the container locally I receive a non-zero exit code typically, 137 or 139.

What version are you running?
V3.3.9. Tested also in V3.3.7 and V3.3.8 in which the behaviour is as expected.

### V3.3.9
Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dotnet-exception-test
spec:
  entrypoint: dotnet-exception-test
  templates:
  - name: dotnet-exception-test
    container:
      image: hrusby/dotnet-immediate-exception:1.0.0
      command: ["dotnet", "Immediate-Exception.dll"]
```

For reference, the only code being executed in the image is:
```cs
using System;

namespace ImmediateException
{
    class Program
    {
        static void Main(string[] args)
        {
            throw new Exception("Some Error");
        }
    }
}
```

#### Logs from the workflow controller:
```bash
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
time="2022-08-23T12:22:07.164Z" level=info msg="Processing workflow" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:07.173Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:07.174Z" level=info msg="Pod node dotnet-exception-test-4w468 initialized Pending" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:07.183Z" level=info msg="Created pod: dotnet-exception-test-4w468 (dotnet-exception-test-4w468)" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:07.183Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:07.183Z" level=info msg=reconcileAgentPod namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:07.192Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=31982786 workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.185Z" level=info msg="Processing workflow" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.185Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.185Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.185Z" level=info msg="node changed" new.message= new.phase=Succeeded new.progress=0/1 nodeID=dotnet-exception-test-4w468 old.message= old.phase=Pending old.progress=0/1
time="2022-08-23T12:22:17.186Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg=reconcileAgentPod namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="Running OnExit handler: exit-handler" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="Steps node dotnet-exception-test-4w468-3028619305 initialized Running" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="StepGroup node dotnet-exception-test-4w468-1819341757 initialized Running" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="Skipping dotnet-exception-test-4w468.onExit[0].send-alert: when 'Succeeded != Succeeded' evaluated false" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="Skipped node dotnet-exception-test-4w468-1750326720 initialized Skipped (message: when 'Succeeded != Succeeded' evaluated false)" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="Step group node dotnet-exception-test-4w468-1819341757 successful" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="node dotnet-exception-test-4w468-1819341757 phase Running -> Succeeded" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="node dotnet-exception-test-4w468-1819341757 finished: 2022-08-23 12:22:17.18690107 +0000 UTC" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="Outbound nodes of dotnet-exception-test-4w468-1750326720 is [dotnet-exception-test-4w468-1750326720]" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="Outbound nodes of dotnet-exception-test-4w468-3028619305 is [dotnet-exception-test-4w468-1750326720]" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="node dotnet-exception-test-4w468-3028619305 phase Running -> Succeeded" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="node dotnet-exception-test-4w468-3028619305 finished: 2022-08-23 12:22:17.186974874 +0000 UTC" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.186Z" level=info msg="Checking daemoned children of dotnet-exception-test-4w468-3028619305" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.187Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.187Z" level=info msg="Marking workflow completed" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.187Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.187Z" level=info msg="Checking daemoned children of " namespace=argo workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.192Z" level=info msg="cleaning up pod" action=deletePod key=argo/dotnet-exception-test-4w468-1340600742-agent/deletePod
time="2022-08-23T12:22:17.201Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=31982838 workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.211Z" level=info msg="archiving workflow" namespace=argo uid=332c11cf-743c-432b-8ff2-13e079aa3a29 workflow=dotnet-exception-test-4w468
time="2022-08-23T12:22:17.216Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/dotnet-exception-test-4w468/labelPodCompleted
time="2022-08-23T12:22:17.255Z" level=info msg="Queueing Succeeded workflow argo/dotnet-exception-test-4w468 for delete in 164h30m0s due to TTL"

#### The workflow's pods that are problematic:
```sh
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/default-container: main
      workflows.argoproj.io/node-id: dotnet-exception-test-4w468
      workflows.argoproj.io/node-name: dotnet-exception-test-4w468
      workflows.argoproj.io/outputs: '{"artifacts":[{"name":"main-logs","s3":{"key":"dotnet-exception-test-4w468/dotnet-exception-test-4w468/main.log"}}]}'
    creationTimestamp: "2022-08-23T12:22:07Z"
    labels:
      workflows.argoproj.io/completed: "true"
      workflows.argoproj.io/workflow: dotnet-exception-test-4w468
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/default-container: {}
            f:workflows.argoproj.io/node-id: {}
            f:workflows.argoproj.io/node-name: {}
          f:labels:
            .: {}
            f:workflows.argoproj.io/completed: {}
            f:workflows.argoproj.io/workflow: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"332c11cf-743c-432b-8ff2-13e079aa3a29"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          f:containers:
            k:{"name":"main"}:
              .: {}
              f:command: {}
              f:env:
                .: {}
                k:{"name":"ARGO_CONTAINER_NAME"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_DEADLINE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_INCLUDE_SCRIPT_OUTPUT"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_NODE_ID"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_PROGRESS_FILE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_PROGRESS_FILE_TICK_DURATION"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_PROGRESS_PATCH_TICK_DURATION"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_TEMPLATE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/var/run/argo"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
            k:{"name":"wait"}:
              .: {}
              f:command: {}
              f:env:
                .: {}
                k:{"name":"ARGO_CONTAINER_NAME"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_CONTAINER_RUNTIME_EXECUTOR"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_DEADLINE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_INCLUDE_SCRIPT_OUTPUT"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_NODE_ID"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_POD_NAME"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:fieldRef:
                      .: {}
                      f:apiVersion: {}
                      f:fieldPath: {}
                k:{"name":"ARGO_POD_UID"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:fieldRef:
                      .: {}
                      f:apiVersion: {}
                      f:fieldPath: {}
                k:{"name":"ARGO_PROGRESS_FILE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_PROGRESS_FILE_TICK_DURATION"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_PROGRESS_PATCH_TICK_DURATION"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_TEMPLATE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_WORKFLOW_NAME"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"GODEBUG"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/argo/secret/argo-minio"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/var/run/argo"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:initContainers:
            .: {}
            k:{"name":"init"}:
              .: {}
              f:command: {}
              f:env:
                .: {}
                k:{"name":"ARGO_CONTAINER_NAME"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_CONTAINER_RUNTIME_EXECUTOR"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_DEADLINE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_INCLUDE_SCRIPT_OUTPUT"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_NODE_ID"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_POD_NAME"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:fieldRef:
                      .: {}
                      f:apiVersion: {}
                      f:fieldPath: {}
                k:{"name":"ARGO_POD_UID"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:fieldRef:
                      .: {}
                      f:apiVersion: {}
                      f:fieldPath: {}
                k:{"name":"ARGO_PROGRESS_FILE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_PROGRESS_FILE_TICK_DURATION"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_PROGRESS_PATCH_TICK_DURATION"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_TEMPLATE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ARGO_WORKFLOW_NAME"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"GODEBUG"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/argo/secret/argo-minio"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/var/run/argo"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
          f:volumes:
            .: {}
            k:{"name":"argo-minio"}:
              .: {}
              f:name: {}
              f:secret:
                .: {}
                f:defaultMode: {}
                f:items: {}
                f:secretName: {}
            k:{"name":"var-run-argo"}:
              .: {}
              f:emptyDir: {}
              f:name: {}
      manager: workflow-controller
      operation: Update
      time: "2022-08-23T12:22:07Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:workflows.argoproj.io/outputs: {}
      manager: argoexec
      operation: Update
      time: "2022-08-23T12:22:14Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:initContainerStatuses: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.244.2.81"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-08-23T12:22:14Z"
    name: dotnet-exception-test-4w468
    namespace: argo
    ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Workflow
      name: dotnet-exception-test-4w468
      uid: 332c11cf-743c-432b-8ff2-13e079aa3a29
    resourceVersion: "31982844"
    uid: 04dc4a95-a7e1-401c-bfdb-e1819c517118
  spec:
    containers:
    - command:
      - argoexec
      - wait
      - --loglevel
      - info
      env:
      - name: ARGO_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: ARGO_POD_UID
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.uid
      - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
        value: emissary
      - name: GODEBUG
        value: x509ignoreCN=0
      - name: ARGO_WORKFLOW_NAME
        value: dotnet-exception-test-4w468
      - name: ARGO_CONTAINER_NAME
        value: wait
      - name: ARGO_TEMPLATE
        value: '{"name":"dotnet-exception-test","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"imageRepo/docker/immediate-dotnet-exception:1.0.0","command":["dotnet","ImmediateException.dll"],"resources":{}},"archiveLocation":{"archiveLogs":true,"s3":{"endpoint":"argo-minio.argo:9000","bucket":"argo-artifacts","insecure":true,"accessKeySecret":{"name":"argo-minio","key":"accesskey"},"secretKeySecret":{"name":"argo-minio","key":"secretkey"},"key":"dotnet-exception-test-4w468/dotnet-exception-test-4w468"}}}'
      - name: ARGO_NODE_ID
        value: dotnet-exception-test-4w468
      - name: ARGO_INCLUDE_SCRIPT_OUTPUT
        value: "false"
      - name: ARGO_DEADLINE
        value: "0001-01-01T00:00:00Z"
      - name: ARGO_PROGRESS_FILE
        value: /var/run/argo/progress
      - name: ARGO_PROGRESS_PATCH_TICK_DURATION
        value: 1m0s
      - name: ARGO_PROGRESS_FILE_TICK_DURATION
        value: 3s
      image: quay.io/argoproj/argoexec:v3.3.9
      imagePullPolicy: IfNotPresent
      name: wait
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /argo/secret/argo-minio
        name: argo-minio
        readOnly: true
      - mountPath: /var/run/argo
        name: var-run-argo
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-zh9vs
        readOnly: true
    - command:
      - /var/run/argo/argoexec
      - emissary
      - --
      - dotnet
      - ImmediateException.dll
      env:
      - name: ARGO_CONTAINER_NAME
        value: main
      - name: ARGO_TEMPLATE
        value: '{"name":"dotnet-exception-test","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"imageRepo/docker/immediate-dotnet-exception:1.0.0","command":["dotnet","ImmediateException.dll"],"resources":{}},"archiveLocation":{"archiveLogs":true,"s3":{"endpoint":"argo-minio.argo:9000","bucket":"argo-artifacts","insecure":true,"accessKeySecret":{"name":"argo-minio","key":"accesskey"},"secretKeySecret":{"name":"argo-minio","key":"secretkey"},"key":"dotnet-exception-test-4w468/dotnet-exception-test-4w468"}}}'
      - name: ARGO_NODE_ID
        value: dotnet-exception-test-4w468
      - name: ARGO_INCLUDE_SCRIPT_OUTPUT
        value: "false"
      - name: ARGO_DEADLINE
        value: "0001-01-01T00:00:00Z"
      - name: ARGO_PROGRESS_FILE
        value: /var/run/argo/progress
      - name: ARGO_PROGRESS_PATCH_TICK_DURATION
        value: 1m0s
      - name: ARGO_PROGRESS_FILE_TICK_DURATION
        value: 3s
      image: imageRepo/docker/immediate-dotnet-exception:1.0.0
      imagePullPolicy: IfNotPresent
      name: main
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/argo
        name: var-run-argo
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-zh9vs
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    initContainers:
    - command:
      - argoexec
      - init
      - --loglevel
      - info
      env:
      - name: ARGO_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: ARGO_POD_UID
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.uid
      - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
        value: emissary
      - name: GODEBUG
        value: x509ignoreCN=0
      - name: ARGO_WORKFLOW_NAME
        value: dotnet-exception-test-4w468
      - name: ARGO_CONTAINER_NAME
        value: init
      - name: ARGO_TEMPLATE
        value: '{"name":"dotnet-exception-test","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"imageRepo/docker/immediate-dotnet-exception:1.0.0","command":["dotnet","ImmediateException.dll"],"resources":{}},"archiveLocation":{"archiveLogs":true,"s3":{"endpoint":"argo-minio.argo:9000","bucket":"argo-artifacts","insecure":true,"accessKeySecret":{"name":"argo-minio","key":"accesskey"},"secretKeySecret":{"name":"argo-minio","key":"secretkey"},"key":"dotnet-exception-test-4w468/dotnet-exception-test-4w468"}}}'
      - name: ARGO_NODE_ID
        value: dotnet-exception-test-4w468
      - name: ARGO_INCLUDE_SCRIPT_OUTPUT
        value: "false"
      - name: ARGO_DEADLINE
        value: "0001-01-01T00:00:00Z"
      - name: ARGO_PROGRESS_FILE
        value: /var/run/argo/progress
      - name: ARGO_PROGRESS_PATCH_TICK_DURATION
        value: 1m0s
      - name: ARGO_PROGRESS_FILE_TICK_DURATION
        value: 3s
      image: quay.io/argoproj/argoexec:v3.3.9
      imagePullPolicy: IfNotPresent
      name: init
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /argo/secret/argo-minio
        name: argo-minio
        readOnly: true
      - mountPath: /var/run/argo
        name: var-run-argo
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-zh9vs
        readOnly: true
    nodeName: lon2kubdev06
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - emptyDir: {}
      name: var-run-argo
    - name: argo-minio
      secret:
        defaultMode: 420
        items:
        - key: accesskey
          path: accesskey
        - key: secretkey
          path: secretkey
        secretName: argo-minio
    - name: default-token-zh9vs
      secret:
        defaultMode: 420
        secretName: default-token-zh9vs
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-08-23T12:22:12Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-08-23T12:22:14Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-08-23T12:22:14Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-08-23T12:22:07Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://a7440827ca1a61326aef63bd39a81c2a8a70b479309b09a9215183a2819b80a2
      image: imageRepo/docker/immediate-dotnet-exception:1.0.0
      imageID: docker-pullable://imageRepo/docker/immediate-dotnet-exception@sha256:44984dec2ab9ccf373e0a3dcbdfae0668641760351450860329c53ced12c31b5
      lastState: {}
      name: main
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: docker://a7440827ca1a61326aef63bd39a81c2a8a70b479309b09a9215183a2819b80a2
          exitCode: 0
          finishedAt: "2022-08-23T12:22:13Z"
          reason: Completed
          startedAt: "2022-08-23T12:22:12Z"
    - containerID: docker://e3954ba9be0218d7df6c08635647865ca3e6ba9ee0b42d3d751ad93bd9e69bc9
      image: quay.io/argoproj/argoexec:v3.3.9
      imageID: docker-pullable://quay.io/argoproj/argoexec@sha256:e633c7097757d9947ff79d3051eeaeb760e7e5d66b5d4d314078117d6cb18ebb
      lastState: {}
      name: wait
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: docker://e3954ba9be0218d7df6c08635647865ca3e6ba9ee0b42d3d751ad93bd9e69bc9
          exitCode: 0
          finishedAt: "2022-08-23T12:22:14Z"
          reason: Completed
          startedAt: "2022-08-23T12:22:12Z"
    hostIP: 10.50.100.106
    initContainerStatuses:
    - containerID: docker://eb0c711f00565e2ed0dc33e6534db873f434aaef806fa4c3fbf8d8a46c22acfa
      image: quay.io/argoproj/argoexec:v3.3.9
      imageID: docker-pullable://quay.io/argoproj/argoexec@sha256:e633c7097757d9947ff79d3051eeaeb760e7e5d66b5d4d314078117d6cb18ebb
      lastState: {}
      name: init
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: docker://eb0c711f00565e2ed0dc33e6534db873f434aaef806fa4c3fbf8d8a46c22acfa
          exitCode: 0
          finishedAt: "2022-08-23T12:22:09Z"
          reason: Completed
          startedAt: "2022-08-23T12:22:08Z"
    phase: Succeeded
    podIP: 10.244.2.81
    podIPs:
    - ip: 10.244.2.81
    qosClass: BestEffort
    startTime: "2022-08-23T12:22:07Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

#### Logs from in your workflow's wait container, something like:
```sh

kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
time="2022-08-23T12:22:14.332Z" level=info msg="Saving file to s3" bucket=argo-artifacts endpoint="argo-minio.argo:9000" key=dotnet-exception-test-4w468/dotnet-exception-test-4w468/main.log path=/tmp/argo/outputs/logs/main.log
time="2022-08-23T12:22:14.407Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2022-08-23T12:22:14.407Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2022-08-23T12:22:14.407Z" level=info msg="No output parameters"
time="2022-08-23T12:22:14.407Z" level=info msg="No output artifacts"
time="2022-08-23T12:22:14.418Z" level=info msg="Create workflowtaskresults 403"
time="2022-08-23T12:22:14.418Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:default\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
time="2022-08-23T12:22:14.430Z" level=info msg="Patch pods 200"
time="2022-08-23T12:22:14.434Z" level=info msg="Killing sidecars []"
time="2022-08-23T12:22:14.434Z" level=info msg="Alloc=6516 TotalAlloc=12332 Sys=18898 NumGC=4 Goroutines=9"
```

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

### LINKED ISSUE #9446: Emissary Executor Zombie Processes
## Checklist

 

* [X] Double-checked my configuration.
* [X] Tested using the latest version.
* [X] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

When restarting a service, it seems that the process is not being cleaned up properly with an emissary container. A zombie process remains, indicated by `<defunct>`.

What version are you running?

Originally v3.3.6 but also tried with  v3.3.9 and  v3.4.0-rc2

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

Workflow to replicate:

```yaml
metadata:
  generateName: emiss-test-
spec:
  entrypoint: first-step
  templates:
    - name: first-step
      metadata:
      container:
        name: main
        image: ubuntu:22.04 
        command: ["bash","-c"]
        args:
           - |
            ps aux
            apt-get update
            apt-get install -y psmisc
            apt-get purge openssh-server openssh-client
            apt-get install -y openssh-server openssh-client
            service ssh start
            ps aux 
            pstree
            service ssh restart
            ps aux 
            pstree
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
```

Output:

```bash
 * Starting OpenBSD Secure Shell server sshd
   ...done.
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.0 760096 38320 ?        Ssl  20:38   0:00 /var/run/argo/argoexec emissary -- bash -c ps aux apt-get update apt-get install -y psmisc apt-get purge openssh-ser
ver openssh-client apt-get install -y openssh-server openssh-client service ssh start ps aux  pstree service ssh restart ps aux  pstree
root        28  0.0  0.0   3980  2952 ?        S    20:38   0:00 /usr/bin/bash -c ps aux apt-get update apt-get install -y psmisc apt-get purge openssh-server openssh-client apt-get
 install -y openssh-server openssh-client service ssh start ps aux  pstree service ssh restart ps aux  pstree
root      3970  0.0  0.0  12176  3036 ?        Ss   20:40   0:00 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups
root      3971  0.0  0.0   5896  3004 ?        R    20:40   0:00 ps aux
argoexec-+-bash---pstree
         |-sshd
         `-18*[{argoexec}]

 * Restarting OpenBSD Secure Shell server sshd
   ...done.

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.0 760096 38320 ?        Ssl  20:38   0:00 /var/run/argo/argoexec emissary -- bash -c ps aux apt-get update apt-get install -y psmisc apt-get purge openssh-ser
ver openssh-client apt-get install -y openssh-server openssh-client service ssh start ps aux  pstree service ssh restart ps aux  pstree
root        28  0.0  0.0   3980  2952 ?        S    20:38   0:00 /usr/bin/bash -c ps aux apt-get update apt-get install -y psmisc apt-get purge openssh-server openssh-client apt-get
 install -y openssh-server openssh-client service ssh start ps aux  pstree service ssh restart ps aux  pstree
root      3970  0.0  0.0      0     0 ?        Zs   20:40   0:00 [sshd] <defunct>
root      3983  0.0  0.0  12176  3052 ?        Ss   20:40   0:00 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups
root      3984  0.0  0.0   5896  2900 ?        R    20:40   0:00 ps aux
argoexec-+-pstree
         |-2*[sshd]
         `-18*[{argoexec}]
```

Note: there is a zombie process after restarting the service (denoted by the `<defunct>`) as well as `-2*[sshd]` from the `pstree`.

Same workflow with docker executor:

```yaml
metadata:
  generateName: docker-test-
  labels:
    workflows.argoproj.io/container-runtime-executor: docker
spec:
  entrypoint: first-step
  templates:
    - name: first-step
      metadata:
      container:
        name: main
        image: ubuntu:22.04 
        command: ["bash","-c"]
        args:
           - |
            ps aux
            apt-get update
            apt-get install -y psmisc
            apt-get purge openssh-server openssh-client
            apt-get install -y openssh-server openssh-client
            service ssh start
            ps aux 
            pstree
            service ssh restart
            ps aux 
            pstree
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
```

Output:

```bash
 * Starting OpenBSD Secure Shell server sshd
   ...done.
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   3980  3024 ?        Ss   20:38   0:00 bash -c ps aux apt-get update apt-get install -y psmisc apt-get purge openssh-server openssh-client apt-get install
-y openssh-server openssh-client service ssh start ps aux  pstree service ssh restart ps aux  pstree
root      3948  0.0  0.0  12176  3016 ?        Ss   20:40   0:00 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups
root      3949  0.0  0.0   5896  2868 ?        R    20:40   0:00 ps aux
bash-+-pstree
     `-sshd

 * Restarting OpenBSD Secure Shell server sshd
   ...done.

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   3980  3024 ?        Ss   20:38   0:00 bash -c ps aux apt-get update apt-get install -y psmisc apt-get purge openssh-server openssh-client apt-get install
-y openssh-server openssh-client service ssh start ps aux  pstree service ssh restart ps aux  pstree
root      3961  0.0  0.0  12176  3108 ?        Ss   20:40   0:00 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups
root      3962  0.0  0.0   5896  2860 ?        R    20:40   0:00 ps aux
pstree---sshd
```

Note: no zombie processes and only one instance of `sshd` from the `pstree`.

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

time="2022-08-25T21:30:30.804Z" level=info msg="Processing workflow" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:30.808Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:30.809Z" level=info msg="Pod node emiss-test-npwx5 initialized Pending" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:30.832Z" level=info msg="Created pod: emiss-test-npwx5 (emiss-test-npwx5)" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:30.832Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:30.832Z" level=info msg=reconcileAgentPod namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:30.841Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=11382 workflow=emiss-test-npwx5
time="2022-08-25T21:30:40.836Z" level=info msg="Processing workflow" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:40.836Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=emiss-test-npwx5
time="2022-08-25T21:30:40.836Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=emiss-test-npwx5 old.message= old.phase=Pending old.progress=0/1 workflow=emiss-test-npwx5
time="2022-08-25T21:30:40.836Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:40.836Z" level=info msg=reconcileAgentPod namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:40.849Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=11406 workflow=emiss-test-npwx5
time="2022-08-25T21:30:50.829Z" level=info msg="Processing workflow" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:50.829Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=emiss-test-npwx5
time="2022-08-25T21:30:50.829Z" level=info msg="node unchanged" namespace=argo nodeID=emiss-test-npwx5 workflow=emiss-test-npwx5
time="2022-08-25T21:30:50.829Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=emiss-test-npwx5
time="2022-08-25T21:30:50.829Z" level=info msg=reconcileAgentPod namespace=argo workflow=emiss-test-npwx5
```

Seemingly related Github issues:

https://github.com/argoproj/argo-workflows/issues/8680
https://github.com/argoproj/argo-workflows/issues/8246
https://github.com/argoproj/argo-workflows/issues/7259

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>

Fixes #9415

### CODE REVIEW

File: test/e2e/signals_test.go [hunk 1]
```diff
@@ -136,6 +136,18 @@ func (s *SignalsSuite) TestSubProcess() {
...
 }
 
+func (s *SignalsSuite) TestSignaled() {
+	s.Given().
+		Workflow("@testdata/signaled-workflow.yaml").
+		When().
+		SubmitWorkflow().
+		WaitForWorkflow().
+		Then().
+		ExpectWorkflow(func(t *testing.T, metadata *metav1.ObjectMeta, status *wfv1.WorkflowStatus) {
```
Comment (terrytangyuan) [inline test/e2e/signals_test.go:146]: Do you want to also check the specific exit code?

**Review by terrytangyuan — APPROVED** [review]
