### PR TITLE
fix(artifacts): only retry on transient S3 errors

### LINKED ISSUE #5220: All S3 put errors get retried, not only transient ones
```
time="2021-02-26T00:33:50.146Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/file.tgz, key: doc.pdf"
time="2021-02-26T00:33:50.146Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-02-26T00:33:50.146Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/file.tgz to s3 (endpoint: minio:9000, bucket: test, key: doc.pdf)"
time="2021-02-26T00:33:50.156Z" level=warning msg="Failed to put file: The specified bucket does not exist"
time="2021-02-26T00:33:52.243Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/file.tgz, key: doc.pdf"
time="2021-02-26T00:33:52.243Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-02-26T00:33:52.243Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/file.tgz to s3 (endpoint: minio:9000, bucket: test, key: doc.pdf)"
time="2021-02-26T00:33:52.251Z" level=warning msg="Failed to put file: The specified bucket does not exist"
time="2021-02-26T00:33:56.280Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/file.tgz, key: doc.pdf"
time="2021-02-26T00:33:56.280Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-02-26T00:33:56.280Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/file.tgz to s3 (endpoint: minio:9000, bucket: test, key: doc.pdf)"
time="2021-02-26T00:33:56.293Z" level=warning msg="Failed to put file: The specified bucket does not exist"
time="2021-02-26T00:34:04.707Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/file.tgz, key: doc.pdf"
time="2021-02-26T00:34:04.707Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-02-26T00:34:04.707Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/file.tgz to s3 (endpoint: minio:9000, bucket: test, key: doc.pdf)"
time="2021-02-26T00:34:04.719Z" level=warning msg="Failed to put file: The specified bucket does not exist"
time="2021-02-26T00:34:21.329Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/file.tgz, key: doc.pdf"
time="2021-02-26T00:34:21.329Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-02-26T00:34:21.329Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/file.tgz to s3 (endpoint: minio:9000, bucket: test, key: doc.pdf)"
time="2021-02-26T00:34:21.335Z" level=warning msg="Failed to put file: The specified bucket does not exist"
time="2021-02-26T00:34:21.335Z" level=error msg="executor error: timed out waiting for the condition"
```

### PR DESCRIPTION
**Pull request by dinever**
Closes #5220 

Hi,

This PR fixes the issue of executor retrying non-transient S3 errors.

I took the list of retryable errors from [the minio-go repo](https://github.com/minio/minio-go/blob/92fe50d14294782d96402deb861d442992038109/retry.go#L90-L102).

As of today, this package doesn't have any unit tests. As the logic is getting more complex it's kind of risky to have no tests. I'll see if I can add some. (Might need some minor refactoring)

Thanks!

### CODE REVIEW

File: workflow/artifacts/s3/s3.go [hunk 1]
```diff
@@ -57,30 +71,42 @@ func (s3Driver *ArtifactDriver) Load(inputArtifact *wfv1.Artifact, path string)
 			s3cli, err := s3Driver.newS3Client(ctx)
 			if err != nil {
 				log.Warnf("Failed to create new S3 client: %v", err)
-				return false, nil
+				if isTransientS3Err(err) {
+					return false, nil
+				}
+				return false, fmt.Errorf("failed to create new S3 client: %v", err)
```
Comment (dinever) [inline workflow/artifacts/s3/s3.go:77]: Just to clarify, the `ExponentialBackoff` will stop and return if the condition function returns `true` or an error.

```go
type ConditionFunc func() (done bool, err error)
```

So we need to return:
1. `true, nil` if function finishes successfully
1. `false, fmt.Errorf("...")` if we want to return the error without retrying (for non-transient errors like `NoSuchBucket`)
1. `false, nil` if we want to retry (transient errors)

File: workflow/artifacts/s3/s3.go [hunk 2]
```diff
@@ -29,6 +30,19 @@ type ArtifactDriver struct {
 	Context     context.Context
 }
 
+// s3TransientErrorCodes is a list of S3 error codes that are transient (retryable))))
```
Comment (terrytangyuan) [inline workflow/artifacts/s3/s3.go:33]: Remove the redundant `()))`

File: workflow/artifacts/s3/s3.go [hunk 3]
```diff
@@ -57,30 +71,42 @@ func (s3Driver *ArtifactDriver) Load(inputArtifact *wfv1.Artifact, path string)
...
+				return false, fmt.Errorf("failed to create new S3 client: %v", err)
 			}
 			origErr := s3cli.GetFile(inputArtifact.S3.Bucket, inputArtifact.S3.Key, path)
 			if origErr == nil {
 				return true, nil
 			}
 			if !argos3.IsS3ErrCode(origErr, "NoSuchKey") {
-				log.Warnf("Failed get file: %v", origErr)
-				return false, nil
+				log.Warnf("Failed to get file: %v", origErr)
```
Comment (terrytangyuan) [inline workflow/artifacts/s3/s3.go:84]: You can remove this redundant warning that's the same as the error returned below. Same in other places too.

File: workflow/artifacts/s3/s3.go (hunk 1 above)
Comment (terrytangyuan) [reply workflow/artifacts/s3/s3.go:77]: You can just return `!isTransientS3Err(err), err`?

Comment (dinever) [reply workflow/artifacts/s3/s3.go:77]: Thanks @terrytangyuan! I'm a little confused here, please correct me if I'm wrong:

If we just return `!isTransientS3Err(err), err`:

1. If it's not a transient error, this will return `true, err`. `wait.ExponentialBackoff` will return immediately which is expected
2. If it is a transient error, this will return `false, err`. `wait.ExponentialBackoff` will return immediately too since `err != nil`. As a result, transient errors won't get retried.

For example, I tried the following:

```go
package main

import (
	"fmt"
	"time"

	"k8s.io/apimachinery/pkg/util/wait"
)

func main() {
	i := 0
	err := wait.ExponentialBackoff(wait.Backoff{Duration: time.Second * 2, Factor: 2.0, Steps: 5, Jitter: 0.1},
		func() (bool, error) {
			i++
			return false, fmt.Errorf("error")
		},
	)
	fmt.Println(err, i) // expecting output to be error, 1
}
```

Thanks!

File: workflow/artifacts/s3/s3.go (hunk 2 above)
Comment (dinever) [reply workflow/artifacts/s3/s3.go]: Thanks! Removed those in 044196f88cb01a82961fcfe9620c64a73cbb8ceb.

File: workflow/artifacts/s3/s3.go (hunk 3 above)
Comment (dinever) [reply workflow/artifacts/s3/s3.go]: My original thought is that: if the error is transient, `wait.ExponentialBackoff` will return a `wait.ErrWaitTimeout`. In this case, UI/CLI will only show a timeout error. Need logs to further check what the transient error actually is.

For now I moved the logging to the transient error block: 51c917569166aabfefc3f6983260eb2736d0e896. Will wait for our discussion in https://github.com/argoproj/argo-workflows/pull/5579#discussion_r606054053 to make further changes. Thanks!

**Comment by dinever** [comment]
Will rebase after #5601

File: workflow/artifacts/s3/s3.go [hunk 4]
```diff
@@ -51,107 +69,126 @@ func (s3Driver *ArtifactDriver) Load(inputArtifact *wfv1.Artifact, path string)
...
+		if err = s3cli.PutDirectory(outputArtifact.S3.Bucket, outputArtifact.S3.Key, path); err != nil {
+			return !isTransientS3Err(err), fmt.Errorf("failed to put directory: %v", err)
+		}
+	} else {
+		if err = s3cli.PutFile(outputArtifact.S3.Bucket, outputArtifact.S3.Key, path); err != nil {
+			return !isTransientS3Err(err), fmt.Errorf("failed to put file: %v", err)
+		}
+	}
+	return true, nil
 }
```
Comment (dinever) [inline workflow/artifacts/s3/s3.go:160]: extracted some logic into new functions for unit testing.

File: workflow/artifacts/s3/s3.go [hunk 5]
```diff
@@ -29,7 +31,23 @@ type ArtifactDriver struct {
 	Context     context.Context
 }
 
-var _ artifactscommon.ArtifactDriver = &ArtifactDriver{}
+// s3TransientErrorCodes is a list of S3 error codes that are transient (retryable)
+// Reference: https://github.com/minio/minio-go/blob/92fe50d14294782d96402deb861d442992038109/retry.go#L90-L102
+var s3TransientErrorCodes = []string{
```
Comment (alexec) [inline workflow/artifacts/s3/s3.go:36]: minor - could you move to own file?

Comment (dinever) [reply workflow/artifacts/s3/s3.go]: Sure. Moved this to `error_codes.go` in f5c55fcdcd0a0390269d9328c63ad56090c5d3cc. Thanks!

File: workflow/artifacts/s3/s3.go [hunk 6]
```diff
@@ -51,107 +56,126 @@ func (s3Driver *ArtifactDriver) Load(inputArtifact *wfv1.Artifact, path string)
...
+				return !isTransientS3Err(err), fmt.Errorf("failed to list directory: %v", err)
 			}
 			return true, nil
 		})
 
 	return files, err
 }
+
+// isTransientS3Err checks if an minio.ErrorResponse error is transient (retryable)
+func isTransientS3Err(err error) bool {
```
Comment (alexec) [inline workflow/artifacts/s3/s3.go:171]: minor - please put in `workflow/artifacts/s3/error_codes.go` (maybe rename that to `workflow/artifacts/s3/errors.go`)

**Review by alexec — CHANGES_REQUESTED** [review]
I request one final small change. Once you've done that - dismiss this review so I get notified.

**Review by alexec — APPROVED** [review]

File: workflow/artifacts/s3/s3.go (hunk 6 above)
Comment (dinever) [reply workflow/artifacts/s3/s3.go]: thanks! refactored in 513a4b5fb50aad5471ff22027538b41bb722397d
