### PR TITLE
fix: Retry for http timeout error. Fixes #9271

### LINKED ISSUE #9271: Support retry when putting file to OSS and encounter 'dial tcp: i/o timeout' error
# Summary
Sometimes the pod become failed due to putting main.log to OSS failure. The error showed in pod are:
```
2022-07-18T04:09:55.916Z OSS Save path: /tmp/argo/outputs/logs/main.log, key: 2022/07/18/testhhb9k/testhhb9k-4053391036/main.log
2022-07-18T04:10:25.923Z failed to put file: Put "https://xxx-artifact.oss-us-east-1-internal.aliyuncs.com/2022%2F07%2F18%2Ftesthhb9k%2Ftesthhb9k-4053391036%2Fmain.log": dial tcp: i/o timeout
2022-07-18T04:10:25.923Z executor error: Put \"https://xxx-artifact.oss-us-east-1-internal.aliyuncs.com/2022%2F07%2F18%2Fctesthhb9k%2Ftesthhb9k-4053391036%2Fmain.log\": dial tcp: i/o timeout"
```
It meet the timeout setting - 30s in the [default config](https://github.com/aliyun/aliyun-oss-go-sdk/blob/c82fb81e272d84f716d3f13c36fe0542a49adfeb/oss/conf.go#L198). I'd like to request for adding `dial tcp: i/o timeout` like error into this white list, so that the request can be retry again.
https://github.com/argoproj/argo-workflows/blob/2d1758fe90fd60b37d0dfccb55c3f79d8a897289/workflow/artifacts/oss/oss.go#L37

# Use Cases

Make the request can be retried automatically when encounter dial tcp: i/o timeout error.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by jingkkkkai**
Signed-off-by: Jingkai Hung <jkhung@netbasequid.com>

Fixes #[9271](https://github.com/argoproj/argo-workflows/issues/9271)

### CODE REVIEW

File: workflow/artifacts/gcs/gcs.go [hunk 1]
```diff
@@ -334,3 +335,7 @@ func (g *ArtifactDriver) ListObjects(artifact *wfv1.Artifact) ([]string, error)
 func (g *ArtifactDriver) IsDirectory(artifact *wfv1.Artifact) (bool, error) {
 	return false, errors.New(errors.CodeNotImplemented, "IsDirectory currently unimplemented for GCS")
 }
+
+func isTransientErr(err error) bool {
+	return http.IsHttpTimeoutErr(err) || isTransientGCSErr(err)
```
Comment (terrytangyuan) [inline workflow/artifacts/gcs/gcs.go:340]: Why not adding `http.IsHttpTimeoutErr` to the existing `isTransientGCSErr`?

Comment (terrytangyuan) [reply workflow/artifacts/gcs/gcs.go:340]: There's also already `isTransientError` in the codebase. Consider reusing it.

**Review by terrytangyuan — CHANGES_REQUESTED** [review]

**Review by terrytangyuan — APPROVED** [review]
