### PR TITLE
fix: support ALPN and H2C with gRPC. Fixes #14627

### LINKED ISSUE #14627: http2 connections are assumed to be gRPC
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

This is an issue with the web server itself, not a workflow.

argo-server refuses non-gRPC connections via http2.

```
% curl http://127.0.0.1:2746 --http2-prior-knowledge -v
*   Trying 127.0.0.1:2746...
* Connected to 127.0.0.1 (127.0.0.1) port 2746
* [HTTP/2] [1] OPENED stream for http://127.0.0.1:2746/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: http]
* [HTTP/2] [1] [:authority: 127.0.0.1:2746]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: 127.0.0.1:2746
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/2 415 
< content-type: application/grpc
< grpc-status: 3
< grpc-message: invalid gRPC request content-type ""
< 
* Connection #0 to host 127.0.0.1 left intact
```

In https://github.com/argoproj/argo-workflows/blob/162e6454d881de4fa42cd8c756b7dc9f84ccbcd1/server/apiserver/argoserver.go#L277-L280 it seems like `cmux` can check the `Content-Type` header, per https://github.com/soheilhy/cmux/blob/5ec6847320e53b5fee0ab9a4757b56625a946c85/README.md?plain=1#L22

### Version(s)

v3.6.5, 162e6454d881de4fa42cd8c756b7dc9f84ccbcd1

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
`% curl http://{argo-server} --http2-prior-knowledge -v`

expected: `<!doctype html><html lang="en">...`

actual: `… grpc-message: invalid gRPC request content-type "" …`
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

### PR DESCRIPTION
**Pull request by MasonM**
<!-- markdownlint-disable MD041 -- this is rendered within existing HTML, so allow starting without an H1 -->

<!--

### Before you open your PR

- Run `make pre-commit -B` to fix codegen and lint problems (build will fail).
- [Signed-off your commits](https://github.com/apps/dco/) (otherwise the DCO check will fail).
- Used [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/).

### When you open your PR

- PR title format should also conform to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
- "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
- Create the PR as draft.
- Once builds are green, mark your PR "Ready for review".

When changes are requested, please address them and then dismiss the review to get it reviewed again.

-->

<!-- Does this PR fix an issue -->

Fixes #14627.

### Motivation

https://github.com/argoproj/argo-workflows/pull/14435 tried to fix the bug in the `release-3.6` branch where requests failed with the following error:
```
Service Unavailable: connection error: desc = "transport: authentication handshake failed: credentials: cannot check peer: missing selected ALPN property. If you upgraded from a grpc-go version earlier than 1.67, your TLS connections may have stopped working due to ALPN enforcement. For more details, see: https://github.com/grpc/grpc-go/issues/434" on the UI
```

Unfortunately, this didn't work and broke the readiness probe, so it was reverted in https://github.com/argoproj/argo-workflows/commit/1285c11c80efa606ba87b138300309a57dd36368. The problem is the readiness probe makes a GET request to `/`: https://github.com/argoproj/argo-workflows/blob/1e2a87f2afdebbcd0e55069df5a945f5faca9d45/manifests/base/argo-server/argo-server-deployment.yaml#L30-L36

That request should be going to the HTTP server, and it does when using HTTP/1.1, since `argoserver` is configured to  forward all HTTP/1.1 requests to the listener for the HTTP server: 
https://github.com/argoproj/argo-workflows/blob/1e2a87f2afdebbcd0e55069df5a945f5faca9d45/server/apiserver/argoserver.go#L279-L280

but with ALPN enabled, the client (the kubelet in this case) automatically upgraded the request to HTTP/2, which caused it to be forwarded to the gRPC server instead.

The reason this wasn't caught in https://github.com/argoproj/argo-workflows/pull/14435 is because the Argo server isn't run inside Kubernetes in either the local dev environment or CI builds, so the readiness probe wasn't being used. Additionally, http://localhost:8080/ in the local dev environment points to the [webpack-dev-server](https://webpack.js.org/configuration/dev-server/), which proxies requests to the Argo server, without ALPN: https://github.com/argoproj/argo-workflows/blob/7fd6b10f87879ac0dcdb85466c4e2e2f613ace29/ui/webpack.config.js#L112-L119 

### Modifications
Initially, I tried to fix this by changing cmux to only forward requests with `Content-Type: application/grpc` (which is guaranteed to be present per the [gRPC over HTTP2 spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)) to the gRPC server:
https://github.com/argoproj/argo-workflows/compare/main...MasonM:argo-workflows:fix-http2-multiplexing

but that doesn't work with TLS enabled due to the following limitation mentioned at https://github.com/soheilhy/cmux/:
> TLS: net/http uses a type assertion to identify TLS connections; since cmux's lookahead-implementing connection wraps the underlying TLS connection, this type assertion fails. Because of that, you can serve HTTPS using cmux but http.Request.TLS would not be set in your handlers.

Link to the code it's referencing: https://github.com/golang/go/blob/1e756dc5f73dc19eb1cbf038807d18ef1cc54ebc/src/net/http/server.go#L1959

Instead, this uses the solution proposed in https://github.com/grpc/grpc-go/issues/555#issuecomment-443293451, which relies on the [h2c package](https://pkg.go.dev/golang.org/x/net/http2/h2c).

I had to partially revert #14588 to restore the changes in `util/tls/tls.go` that enabled ALPN. To be extra safe, I didn't remove the `ENV GRPC_ENFORCE_ALPN_ENABLED=false` workaround yet, though it should theoretically be okay to remove now.  

### Verification

I added basic tests to `argo_server_test.go` for the readiness probe, but that only tests when TLS is disabled. I wrote the following script to manually test with both HTTPS and HTTP:
```shell
#!/bin/bash

set -euo pipefail
BASEURL="$scheme://localhost:2746"
docurl() {
    printf "Testing %s with HTTP/1.1\n" "$*"
    curl -kv --http1.1 "$@" 2>&1 | egrep -i 'ALPN|^< HTTP|< Content-Type|< Grpc-Metadata-Argo-Version'

    printf "Testing %s with HTTP/2 with prior knowledge\n" "$*"
    curl -kv --http2-prior-knowledge "$@" 2>&1 | egrep -i 'ALPN|^< HTTP|< Content-Type|< Grpc-Metadata-Argo-Version'

    printf "Testing %s with ALPN\n" "$*"
    curl -kv --alpn "$@" 2>&1 | egrep -i 'ALPN|^< HTTP|< Content-Type|< Grpc-Metadata-Argo-Version'
}

printf 'Testing root path\n'
docurl "$BASEURL/"

printf '\nTesting grpc-gateway\n'
docurl "$BASEURL/api/v1/workflow-templates/argo"

printf '\nTesting grpc server\n'
docurl -XPOST -H 'Content-Type: application/grpc' "$BASEURL/workflowtemplate.WorkflowTemplateService/ListWorkflowTemplates"
```

<details>
<summary>Output with HTTP</summary>

```
$ scheme=http ./test_mux.sh 
Testing root path                                                                                                                                                                                                                                    
Testing http://localhost:2746/ with HTTP/1.1                                                                                                                                                                                                         
< HTTP/1.1 200 OK                                                                                                                                                                                                                                    
< Content-Type: text/html; charset=utf-8
Testing http://localhost:2746/ with HTTP/2 with prior knowledge
< HTTP/2 200                                                                                                              
< content-type: text/html; charset=utf-8
Testing http://localhost:2746/ with ALPN     
< HTTP/1.1 200 OK           
< Content-Type: text/html; charset=utf-8                 
                                                             
Testing grpc-gateway                    
Testing http://localhost:2746/api/v1/workflow-templates/argo with HTTP/1.1
< HTTP/1.1 200 OK     
< Content-Type: application/json
< Grpc-Metadata-Argo-Version: latest+19a02a0.dirty
Testing http://localhost:2746/api/v1/workflow-templates/argo with HTTP/2 with prior knowledge
< HTTP/2 200                             
< content-type: application/json
< grpc-metadata-argo-version: latest+19a02a0.dirty
Testing http://localhost:2746/api/v1/workflow-templates/argo with ALPN
< HTTP/1.1 200 OK                       
< Content-Type: application/json
< Grpc-Metadata-Argo-Version: latest+19a02a0.dirty
                                                                                                                          
Testing grpc server         
Testing -XPOST -H Content-Type: application/grpc http://localhost:2746/workflowtemplate.WorkflowTemplateService/ListWorkflowTemplates with HTTP/1.1
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
Testing -XPOST -H Content-Type: application/grpc http://localhost:2746/workflowtemplate.WorkflowTemplateService/ListWorkflowTemplates with HTTP/2 with prior knowledge
< HTTP/2 200                                                                                                              
< content-type: application/grpc
Testing -XPOST -H Content-Type: application/grpc http://localhost:2746/workflowtemplate.WorkflowTemplateService/ListWorkflowTemplates with ALPN
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
```
</details>

<details>
<summary>Output with HTTPS</summary>

```
$ scheme=https ./test_mux.sh
Testing root path
Testing https://localhost:2746/ with HTTP/1.1
* ALPN: curl offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
Testing https://localhost:2746/ with HTTP/2 with prior knowledge
* ALPN: curl offers h2
* ALPN: server accepted h2
< HTTP/2 200 
< content-type: text/html; charset=utf-8
Testing https://localhost:2746/ with ALPN
* ALPN: curl offers h2,http/1.1
* ALPN: server accepted h2
< HTTP/2 200 
< content-type: text/html; charset=utf-8

Testing grpc-gateway
Testing https://localhost:2746/api/v1/workflow-templates/argo with HTTP/1.1
* ALPN: curl offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
< HTTP/1.1 200 OK
< Content-Type: application/json
< Grpc-Metadata-Argo-Version: latest+19a02a0.dirty
Testing https://localhost:2746/api/v1/workflow-templates/argo with HTTP/2 with prior knowledge
* ALPN: curl offers h2
* ALPN: server accepted h2
< HTTP/2 200 
< content-type: application/json
< grpc-metadata-argo-version: latest+19a02a0.dirty
Testing https://localhost:2746/api/v1/workflow-templates/argo with ALPN
* ALPN: curl offers h2,http/1.1
* ALPN: server accepted h2
< HTTP/2 200 
< content-type: application/json
< grpc-metadata-argo-version: latest+19a02a0.dirty

Testing grpc server
Testing -XPOST -H Content-Type: application/grpc https://localhost:2746/workflowtemplate.WorkflowTemplateService/ListWorkflowTemplates with HTTP/1.1
* ALPN: curl offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
Testing -XPOST -H Content-Type: application/grpc https://localhost:2746/workflowtemplate.WorkflowTemplateService/ListWorkflowTemplates with HTTP/2 with prior knowledge
* ALPN: curl offers h2
* ALPN: server accepted h2
< HTTP/2 200 
< content-type: application/grpc
Testing -XPOST -H Content-Type: application/grpc https://localhost:2746/workflowtemplate.WorkflowTemplateService/ListWorkflowTemplates with ALPN
* ALPN: curl offers h2,http/1.1
* ALPN: server accepted h2
< HTTP/2 200 
< content-type: application/grpc
```
</details>


### Documentation

N/A
<!--
### Beyond this PR

Thank you for submitting this! Have you ever thought of becoming a Reviewer or Approver on the project?

Argo Workflows is seeking more community involvement and ultimately more [Reviewers and Approvers](https://github.com/argoproj/argoproj/blob/main/community/membership.md) to help keep it viable.
See [Sustainability Effort](https://github.com/argoproj/argo-workflows/blob/main/community/sustainability_effort.md) for more information.

-->

### CODE REVIEW

File: util/grpc/mux.go [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+// "If a request is an h2c connection, it's hijacked and redirected to
+// s.ServeConn. Otherwise the returned Handler just forwards requests to h. This
+// works because h2c is designed to be parseable as valid HTTP/1, but ignored by
+// any HTTP server that does not handle h2c. Therefore we leverage the HTTP/1
+// compatible parts of the Go http library to parse and recognize h2c requests.
+// Once a request is recognized as h2c, we hijack the connection and convert it
+// to an HTTP/2 connection which is understandable to s.ServeConn. (s.ServeConn
+// understands HTTP/2 except for the h2c part of it.)"
+func NewMuxHandler(grpcServerHandler http.Handler, httpServerHandler http.Handler) http.Handler {
+	return h2c.NewHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```
Comment (MasonM) [inline util/grpc/mux.go:51]: One possible concern here is performance, since `h2c` buffers the entire request in memory, unlike cmux. I'm not sure if that's actually going to be a problem here.

**Comment by Joibel** [comment]
This LGTM, and works for me. Should we merge the reversion of the ENV var in the Dockerfile into this PR, or do you think it wants doing separately?

**Comment by MasonM** [comment]
@Joibel Thanks for the review! I was thinking of doing it separately to be extra safe.
