### PR TITLE
fix: ensure that nodes complete when workflow fails with `parallelism` and `failFast`. Fixes #13806

### LINKED ISSUE #13806: `StepGroup` node stuck `Running` when looping with `FailFast`
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

workflow

https://github.com/argoproj/argo-workflows/blob/2cc6b32df3a5527c3bb54d13ebdcf74c6318c3aa/workflow/controller/operator.go#L2781-L2785

`Steps` node is directly marked as `Failed`, while its child node of `StepGroup` type remain in`Running`.

### Version(s)

2cc6b32

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loop-arbitrary-sequential-steps-
spec:
  entrypoint: loop-arbitrary-sequential-steps-example
  arguments:
    parameters:
      - name: step_params
        value: |
          [
            { "exit_code": 0, "message": "succeeds 1" },
            { "exit_code": 1, "message": "will fail and stop here" },
            { "exit_code": 0, "message": "will not run" }
          ]
  templates:
    - name: loop-arbitrary-sequential-steps-example
      inputs:
        parameters:
          - name: step_params
      parallelism: 1
      failFast: true
      steps:
        - - name: unit-step
            template: unit-step-template
            arguments:
              parameters:
                - name: exit_code
                  value: "{{item.exit_code}}"
                - name: message
                  value: "{{item.message}}"
            withParam: "{{inputs.parameters.step_params}}"

    - name: unit-step-template
      inputs:
        parameters:
          - name: exit_code
          - name: message
      container:
        image: alpine
        command: [ '/bin/sh', '-c' ]
        args: [ "echo {{inputs.parameters.message}}; exit {{inputs.parameters.exit_code}}" ]
```

### Logs from the workflow controller

```text
INFO[2024-10-24T19:06:29.900Z] Processing workflow                           Phase= ResourceVersion=11622643 namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:29.905Z] resolved artifact repository                  artifactRepositoryRef="argo/#"
INFO[2024-10-24T19:06:29.905Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:29.905Z] Updated phase  -> Running                     namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:36.865Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.866Z] was unable to obtain node for , letting display name to be nodeName  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.866Z] Steps node loop-arbitrary-sequential-steps-5lsg4 initialized Running  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.866Z] StepGroup node loop-arbitrary-sequential-steps-5lsg4-3955538712 initialized Running  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:36.868Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.869Z] Pod node loop-arbitrary-sequential-steps-5lsg4-3045436625 initialized Pending  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
W1024 19:06:36.902029 1530355 warnings.go:70] metadata.name: this is used in the Pod's hostname, which can result in surprising behavior; a DNS label is recommended: [must be no more than 63 characters]
INFO[2024-10-24T19:06:36.908Z] Created pod: loop-arbitrary-sequential-steps-5lsg4[0].unit-step(0:exit_code:0,message:succeeds 1) (loop-arbitrary-sequential-steps-5lsg4-unit-step-template-3045436625)  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:36.911Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.912Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:36.912Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.913Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:36.916Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.918Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:36.918Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.919Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:36.920Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.921Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.921Z] Workflow step group node loop-arbitrary-sequential-steps-5lsg4-3955538712 not yet completed  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.922Z] TaskSet Reconciliation                        namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.922Z] reconcileAgentPod                             namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.923Z] Workflow to be dehydrated                     Workflow Size=2888
INFO[2024-10-24T19:06:36.935Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11622681 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.960Z] Processing workflow                           Phase=Running ResourceVersion=11622681 namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.962Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:36.962Z] node changed                                  namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-5lsg4-3045436625 old.message= old.phase=Pending old.progress=0/1 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:37.584Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
ERRO[2024-10-24T19:06:37.584Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:37.584Z] Workflow to be dehydrated                     Workflow Size=3208
INFO[2024-10-24T19:06:37.602Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11622686 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:37.909Z] Processing workflow                           Phase=Running ResourceVersion=11622686 namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:37.912Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:37.912Z] node unchanged                                namespace=argo nodeID=loop-arbitrary-sequential-steps-5lsg4-3045436625 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:38.593Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
ERRO[2024-10-24T19:06:38.593Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:39.789Z] Processing workflow                           Phase=Running ResourceVersion=11622686 namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:39.791Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:39.791Z] node unchanged                                namespace=argo nodeID=loop-arbitrary-sequential-steps-5lsg4-3045436625 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:41.624Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
ERRO[2024-10-24T19:06:41.624Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:42.777Z] Processing workflow                           Phase=Running ResourceVersion=11622686 namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:42.781Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:42.782Z] marking its taskResult as completed since wait container did not exit normally  exitCode=2 namespace=argo nodeID=loop-arbitrary-sequential-steps-5lsg4-3045436625 reason=Error workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:42.782Z] node changed                                  namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-5lsg4-3045436625 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:45.354Z] template (node loop-arbitrary-sequential-steps-5lsg4) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
ERRO[2024-10-24T19:06:45.354Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:45.354Z] Workflow to be dehydrated                     Workflow Size=3247
INFO[2024-10-24T19:06:45.364Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11622716 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:46.357Z] Processing workflow                           Phase=Running ResourceVersion=11622716 namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:46.358Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:46.358Z] Pod failed: Error (exit code 2): unexpected end of JSON input  displayName="unit-step(0:exit_code:0,message:succeeds 1)" namespace=argo pod=loop-arbitrary-sequential-steps-5lsg4-unit-step-template-3045436625 templateName=unit-step-template workflow=loop-arbitrary-sequential-steps-5lsg4
WARN[2024-10-24T19:06:46.358Z] marking its taskResult as completed since wait container did not exit normally  exitCode=2 namespace=argo nodeID=loop-arbitrary-sequential-steps-5lsg4-3045436625 reason=Error workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:46.358Z] node changed                                  namespace=argo new.message="Error (exit code 2): unexpected end of JSON input" new.phase=Error new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-5lsg4-3045436625 old.message= old.phase=Running old.progress=0/1 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:47.027Z] node loop-arbitrary-sequential-steps-5lsg4 phase Running -> Failed  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:47.027Z] node loop-arbitrary-sequential-steps-5lsg4 message: template has failed or errored children and failFast enabled  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:47.027Z] node loop-arbitrary-sequential-steps-5lsg4 finished: 2024-10-24 11:06:47.027910922 +0000 UTC  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
ERRO[2024-10-24T19:06:47.027Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:47.028Z] Workflow to be dehydrated                     Workflow Size=3442
INFO[2024-10-24T19:06:47.041Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11622721 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:47.048Z] cleaning up pod                               action=labelPodCompleted key=argo/loop-arbitrary-sequential-steps-5lsg4-unit-step-template-3045436625/labelPodCompleted
INFO[2024-10-24T19:06:48.067Z] Processing workflow                           Phase=Running ResourceVersion=11622721 namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:48.069Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:48.627Z] TaskSet Reconciliation                        namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:48.627Z] reconcileAgentPod                             namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:48.627Z] Updated phase Running -> Failed               namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:48.627Z] Updated message  -> template has failed or errored children and failFast enabled  namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:48.627Z] Marking workflow completed                    namespace=argo workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:06:48.627Z] Workflow to be dehydrated                     Workflow Size=3528
INFO[2024-10-24T19:06:48.640Z] Workflow update successful                    namespace=argo phase=Failed resourceVersion=11622727 workflow=loop-arbitrary-sequential-steps-5lsg4
INFO[2024-10-24T19:11:29.715Z] Alloc=5715 TotalAlloc=20847 Sys=28757 NumGC=9 Goroutines=180 
INFO[2024-10-24T19:11:56.066Z] Processing workflow                           Phase= ResourceVersion=11623287 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:11:56.071Z] resolved artifact repository                  artifactRepositoryRef="argo/#"
INFO[2024-10-24T19:11:56.071Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:11:56.071Z] Updated phase  -> Running                     namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
WARN[2024-10-24T19:12:00.232Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.232Z] was unable to obtain node for , letting display name to be nodeName  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.232Z] Steps node loop-arbitrary-sequential-steps-hzg6w initialized Running  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.233Z] StepGroup node loop-arbitrary-sequential-steps-hzg6w-3057648027 initialized Running  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
WARN[2024-10-24T19:12:00.233Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.233Z] Pod node loop-arbitrary-sequential-steps-hzg6w-2176193230 initialized Pending  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
W1024 19:12:00.290482 1530355 warnings.go:70] metadata.name: this is used in the Pod's hostname, which can result in surprising behavior; a DNS label is recommended: [must be no more than 63 characters]
INFO[2024-10-24T19:12:00.291Z] Created pod: loop-arbitrary-sequential-steps-hzg6w[0].unit-step(0:exit_code:0,message:succeeds 1) (loop-arbitrary-sequential-steps-hzg6w-unit-step-template-2176193230)  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
WARN[2024-10-24T19:12:00.291Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.292Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
WARN[2024-10-24T19:12:00.292Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.292Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.292Z] Workflow step group node loop-arbitrary-sequential-steps-hzg6w-3057648027 not yet completed  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.292Z] TaskSet Reconciliation                        namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.292Z] reconcileAgentPod                             namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.292Z] Workflow to be dehydrated                     Workflow Size=2602
INFO[2024-10-24T19:12:00.302Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623297 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.304Z] Processing workflow                           Phase=Running ResourceVersion=11623297 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.305Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.305Z] node changed                                  namespace=argo new.message= new.phase=Pending new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-hzg6w-2176193230 old.message= old.phase=Pending old.progress=0/1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.306Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:00.306Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:00.306Z] Workflow to be dehydrated                     Workflow Size=2907
INFO[2024-10-24T19:12:00.315Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623302 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:01.294Z] Processing workflow                           Phase=Running ResourceVersion=11623302 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:01.296Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:01.297Z] node changed                                  namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-hzg6w-2176193230 old.message= old.phase=Pending old.progress=0/1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:01.297Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:01.297Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:01.297Z] Workflow to be dehydrated                     Workflow Size=2922
INFO[2024-10-24T19:12:01.305Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623308 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:02.815Z] Processing workflow                           Phase=Running ResourceVersion=11623308 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:02.816Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:02.816Z] node unchanged                                namespace=argo nodeID=loop-arbitrary-sequential-steps-hzg6w-2176193230 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:02.817Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:02.817Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:05.822Z] Processing workflow                           Phase=Running ResourceVersion=11623308 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:05.823Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:05.823Z] node changed                                  namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-hzg6w-2176193230 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:05.824Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:05.824Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:05.824Z] Workflow to be dehydrated                     Workflow Size=2966
INFO[2024-10-24T19:12:05.829Z] cleaning up pod                               action=terminateContainers key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-2176193230/terminateContainers
INFO[2024-10-24T19:12:05.830Z] https://0.0.0.0:45855/api/v1/namespaces/argo/pods/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-2176193230/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false 
INFO[2024-10-24T19:12:05.831Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623330 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:05.934Z] signaled container                            container=wait error="<nil>" namespace=argo pod=loop-arbitrary-sequential-steps-hzg6w-unit-step-template-2176193230 stderr= stdout="killing 1 with terminated\n"
INFO[2024-10-24T19:12:06.824Z] Processing workflow                           Phase=Running ResourceVersion=11623330 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:06.826Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:06.826Z] task-result changed                           namespace=argo nodeID=loop-arbitrary-sequential-steps-hzg6w-2176193230 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:06.826Z] node unchanged                                namespace=argo nodeID=loop-arbitrary-sequential-steps-hzg6w-2176193230 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:06.826Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:06.827Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:06.827Z] Workflow to be dehydrated                     Workflow Size=3132
INFO[2024-10-24T19:12:06.831Z] cleaning up pod                               action=terminateContainers key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-2176193230/terminateContainers
INFO[2024-10-24T19:12:06.834Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623336 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:07.832Z] Processing workflow                           Phase=Running ResourceVersion=11623336 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:07.833Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:07.833Z] node unchanged                                namespace=argo nodeID=loop-arbitrary-sequential-steps-hzg6w-2176193230 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:07.834Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:07.834Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:07.839Z] cleaning up pod                               action=terminateContainers key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-2176193230/terminateContainers
INFO[2024-10-24T19:12:08.935Z] cleaning up pod                               action=killContainers key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-2176193230/killContainers
INFO[2024-10-24T19:12:08.945Z] Processing workflow                           Phase=Running ResourceVersion=11623336 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.946Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.947Z] node changed                                  namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-hzg6w-2176193230 old.message= old.phase=Running old.progress=0/1 workflow=loop-arbitrary-sequential-steps-hzg6w
WARN[2024-10-24T19:12:08.948Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.948Z] Pod node loop-arbitrary-sequential-steps-hzg6w-1135654439 initialized Pending  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
W1024 19:12:08.957949 1530355 warnings.go:70] metadata.name: this is used in the Pod's hostname, which can result in surprising behavior; a DNS label is recommended: [must be no more than 63 characters]
INFO[2024-10-24T19:12:08.959Z] Created pod: loop-arbitrary-sequential-steps-hzg6w[0].unit-step(1:exit_code:1,message:will fail and stop here) (loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439)  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
WARN[2024-10-24T19:12:08.959Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.959Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.959Z] Workflow step group node loop-arbitrary-sequential-steps-hzg6w-3057648027 not yet completed  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.959Z] TaskSet Reconciliation                        namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.959Z] reconcileAgentPod                             namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.959Z] Workflow to be dehydrated                     Workflow Size=3705
INFO[2024-10-24T19:12:08.971Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623344 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:08.983Z] cleaning up pod                               action=labelPodCompleted key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-2176193230/labelPodCompleted
INFO[2024-10-24T19:12:09.962Z] Processing workflow                           Phase=Running ResourceVersion=11623344 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:09.964Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:09.964Z] node changed                                  namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-hzg6w-1135654439 old.message= old.phase=Pending old.progress=0/1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:09.965Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:09.965Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:09.965Z] Workflow to be dehydrated                     Workflow Size=3744
INFO[2024-10-24T19:12:09.973Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623358 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:10.978Z] Processing workflow                           Phase=Running ResourceVersion=11623358 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:10.980Z] Task-result reconciliation                    namespace=argo numObjs=2 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:10.980Z] node unchanged                                namespace=argo nodeID=loop-arbitrary-sequential-steps-hzg6w-1135654439 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:10.980Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:10.980Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:13.855Z] Processing workflow                           Phase=Running ResourceVersion=11623358 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:13.857Z] Task-result reconciliation                    namespace=argo numObjs=2 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:13.857Z] node changed                                  namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-hzg6w-1135654439 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:13.858Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:13.858Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:13.858Z] Workflow to be dehydrated                     Workflow Size=3788
INFO[2024-10-24T19:12:13.863Z] cleaning up pod                               action=terminateContainers key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439/terminateContainers
INFO[2024-10-24T19:12:13.863Z] https://0.0.0.0:45855/api/v1/namespaces/argo/pods/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false 
INFO[2024-10-24T19:12:13.865Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623374 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:13.963Z] signaled container                            container=wait error="<nil>" namespace=argo pod=loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439 stderr= stdout="killing 1 with terminated\n"
INFO[2024-10-24T19:12:14.858Z] Processing workflow                           Phase=Running ResourceVersion=11623374 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:14.860Z] Task-result reconciliation                    namespace=argo numObjs=2 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:14.860Z] task-result changed                           namespace=argo nodeID=loop-arbitrary-sequential-steps-hzg6w-1135654439 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:14.860Z] node unchanged                                namespace=argo nodeID=loop-arbitrary-sequential-steps-hzg6w-1135654439 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:14.860Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:14.860Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:14.860Z] Workflow to be dehydrated                     Workflow Size=3954
INFO[2024-10-24T19:12:14.865Z] cleaning up pod                               action=terminateContainers key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439/terminateContainers
INFO[2024-10-24T19:12:14.868Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623379 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:15.866Z] Processing workflow                           Phase=Running ResourceVersion=11623379 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:15.867Z] Task-result reconciliation                    namespace=argo numObjs=2 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:15.867Z] node unchanged                                namespace=argo nodeID=loop-arbitrary-sequential-steps-hzg6w-1135654439 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:15.868Z] template (node loop-arbitrary-sequential-steps-hzg6w) active children parallelism exceeded 1  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:15.868Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:15.873Z] cleaning up pod                               action=terminateContainers key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439/terminateContainers
INFO[2024-10-24T19:12:16.964Z] cleaning up pod                               action=killContainers key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439/killContainers
INFO[2024-10-24T19:12:17.017Z] Processing workflow                           Phase=Running ResourceVersion=11623379 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:17.019Z] Task-result reconciliation                    namespace=argo numObjs=2 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:17.019Z] Pod failed: Error (exit code 1)               displayName="unit-step(1:exit_code:1,message:will fail and stop here)" namespace=argo pod=loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439 templateName=unit-step-template workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:17.019Z] node changed                                  namespace=argo new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=loop-arbitrary-sequential-steps-hzg6w-1135654439 old.message= old.phase=Running old.progress=0/1 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:17.020Z] node loop-arbitrary-sequential-steps-hzg6w phase Running -> Failed  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:17.020Z] node loop-arbitrary-sequential-steps-hzg6w message: template has failed or errored children and failFast enabled  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:17.020Z] node loop-arbitrary-sequential-steps-hzg6w finished: 2024-10-24 11:12:17.020331522 +0000 UTC  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
ERRO[2024-10-24T19:12:17.020Z] error in entry template execution             error="Max parallelism reached" namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:17.020Z] Workflow to be dehydrated                     Workflow Size=4093
INFO[2024-10-24T19:12:17.027Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=11623387 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:17.036Z] cleaning up pod                               action=labelPodCompleted key=argo/loop-arbitrary-sequential-steps-hzg6w-unit-step-template-1135654439/labelPodCompleted
INFO[2024-10-24T19:12:18.048Z] Processing workflow                           Phase=Running ResourceVersion=11623387 namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:18.050Z] Task-result reconciliation                    namespace=argo numObjs=2 workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:18.050Z] TaskSet Reconciliation                        namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:18.051Z] reconcileAgentPod                             namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:18.051Z] Updated phase Running -> Failed               namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:18.051Z] Updated message  -> template has failed or errored children and failFast enabled  namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:18.051Z] Marking workflow completed                    namespace=argo workflow=loop-arbitrary-sequential-steps-hzg6w
INFO[2024-10-24T19:12:18.051Z] Workflow to be dehydrated                     Workflow Size=4179
INFO[2024-10-24T19:12:18.058Z] Workflow update successful                    namespace=argo phase=Failed resourceVersion=11623394 workflow=loop-arbitrary-sequential-steps-hzg6w
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by jswxstw**
Fixes #13806

### Motivation

The `FailFast` feature has two serious flaws:
- If parallelism is greater than 1 and one node fails while there are still other incomplete nodes, it cannot fail fast.
- It only mark the `Steps` node as Failed, the last `StepGroup` node is still Running.

### Modifications

- Do not fail fast when there are incomplete nodes.
- Mark the last `StepGroup` node as `Failed`.

### Verification

local test and e2e tests

Test workflow:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo
spec:
  entrypoint: main
  templates:
    - name: main
      parallelism: 2
      failFast: true
      steps:
        - - name: step0
            template: sleep
        - - name: step1
            template: fail
          - name: step2
            template: sleep
    - name: fail
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["exit 1"]
    - name: sleep
      container:
        image: alpine:latest
        command: [ sh, -c ]
        args: [ "sleep 5" ]
```
demo

### CODE REVIEW

**Comment by agilgur5** [comment]
Have you seen #10312 and #11992?

**Comment by jswxstw** [comment]
> Have you seen #10312 and #11992?

@agilgur5 Not yet, but #10312 is not related to this issue, `failFast` in these two issues is not the same, and the problems caused are also different:
- #10312: `failFast` in `DAGTemplate` doesn't work in some scenes.
- #13806: Using `failFast` in `Template` with parallelism leads to nodes getting stuck.

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -2770,6 +2770,25 @@ func (woc *wfOperationCtx) markNodeWaitingForLock(nodeName string, lockName stri
 	return node, nil
 }
 
+func (woc *wfOperationCtx) findLeafNodeWithType(boundaryID string, nodeType wfv1.NodeType) *wfv1.NodeStatus {
+	var leafNode *wfv1.NodeStatus
+	var dfs func(nodeID string)
+	dfs = func(nodeID string) {
+		node, err := woc.wf.Status.Nodes.Get(nodeID)
+		if err != nil {
```
Comment (shuangkun) [inline workflow/controller/operator.go:2778]: Can this function output some logs for effective troubleshooting when problems occur?

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -2770,6 +2770,25 @@ func (woc *wfOperationCtx) markNodeWaitingForLock(nodeName string, lockName stri
...
+			return
+		}
+		if node.Type == nodeType {
+			leafNode = node
+		}
+		for _, childID := range node.Children {
+			dfs(childID)
+		}
+	}
+	dfs(boundaryID)
```
Comment (shuangkun) [inline workflow/controller/operator.go:2788]: Can this recursion have some restrictions?

File: workflow/controller/operator.go (hunk 1 above)
Comment (jswxstw) [reply workflow/controller/operator.go:2778]: Sure, error log is added.

File: workflow/controller/operator.go (hunk 2 above)
Comment (jswxstw) [reply workflow/controller/operator.go:2789]: I don't think we need to add any additional restrictions here, as the number of recursive calls is limited by the number of nodes, which is already limited by [Maximum Recursion Depth](https://argo-workflows.readthedocs.io/en/latest/scaling/#maximum-recursion-depth).

**Review by shuangkun — APPROVED** [review]

**Comment by jswxstw** [comment]
We usually set global [workflow-level parallelism](https://argo-workflows.readthedocs.io/en/latest/synchronization/#workflow-level-parallelism) to limit resource usage, so once the workflow enables `failFast` during looping, issue #13806 becomes inevitable, making feature #5315 almost unusable.
Therefore, I believe this issue is quite serious and requires urgent resolution.

**Review by MasonM — APPROVED** [review]
Looks good. I ran both examples from https://github.com/argoproj/argo-workflows/issues/13806 and verified both correctly failed with this fix:
```
$ ./dist/argo list -o wide
NAME                STATUS      AGE   DURATION   PRIORITY   MESSAGE                                                        P/R/C   PARAMETERS
dag-4rrxm           Failed      55s   37s        0          template has failed or errored children and failFast enabled   0/0/2   
steps-gnh5p         Failed      1m    41s        0          template has failed or errored children and failFast enabled   0/0/2   
```

**Comment by jswxstw** [comment]
@terrytangyuan @Joibel @isubasinghe Could you please take some time to review this PR? Thank you very much!

**Review by terrytangyuan — APPROVED** [review]
LGTM. Thanks!
