### PR TITLE
fix: allow mountPaths with traling slash

### LINKED ISSUE #5520: Executor trying to copy from base image when using trailing slash in `volumeMounts[*].volumePath`
## Summary 

Having declared a template with:

```
volumeMounts:
- name: out
  mountPath: /tmp/out/
```

When running it, just before completion we'd run into the error (`executor error: CopyFile() is not implemented in the k8sapi executor.`)

After a bit of digging into the code, I have tried with
```
volumeMounts:
- name: out
  mountPath: /tmp/out
```

And it worked. It turns out that when checking if the artifact is from the base image or a mount dir, eventually this method is called:

https://github.com/argoproj/argo-workflows/blob/d717865716ea399284c6193ceff9970e66bc5f45/workflow/common/util.go#L40

The above linked line adds a trailing slash to the path, therefore ending up with 2 when there is already present.

## Diagnostics

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 
2.12.3

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: output-artifact-bug
spec:
  entrypoint: mytemplate
  serviceAccount: <redacted>
  templates:
  - name: mytemplate
    outputs:
      artifacts:
      - name: test-out-artifact
        path: "/tmp/out/myartifact.tar"
        gcs:
          bucket: <redacted>
          key: "mykey.tar"
          serviceAccountKeySecret:
            name: <redacted>
            key: <redacted>
    volumes:
    - name: out
      emptyDir: {}
    script:
      image: bash:5.1
      command: [bash]
      source: |
        touch /tmp/out/myartifact.tar
      volumeMounts:
      - name: out
        mountPath: /tmp/out/
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

time="2021-03-26T15:08:59.072Z" level=info msg="Processing workflow" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.073Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.083Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.083Z" level=info msg="Updated message  -> invalid spec: templates.mytemplate.outputs.artifacts.test-out-artifact: k8sapi executor does not support outputs from base image layer.  Use an emptyDir: https://argoproj.github.io/argo/empty-dir/" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.083Z" level=info msg="Marking workflow completed" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.083Z" level=info msg="Checking daemoned children of " namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.092Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=1436328119 workflow=output-artifact-bug-dtmcw

```

Changing the workload to the following (removing trailing slash in the `volumeMounts.mountPath`), will work.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: output-artifact-bug
spec:
  entrypoint: mytemplate
  serviceAccount: <redacted>
  templates:
  - name: mytemplate
    outputs:
      artifacts:
      - name: test-out-artifact
        path: "/tmp/out/myartifact.tar"
        gcs:
          bucket: <redacted>
          key: "mykey.tar"
          serviceAccountKeySecret:
            name: <redacted>
            key: <redacted>
    volumes:
    - name: out
      emptyDir: {}
    script:
      image: bash:5.1
      command: [bash]
      source: |
        touch /tmp/out/myartifact.tar
      volumeMounts:
      - name: out
        mountPath: /tmp/out
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by rccrdpccl**
Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Fixes #5520

### CODE REVIEW

File: workflow/common/util.go [hunk 1]
```diff
@@ -37,7 +37,8 @@ func FindOverlappingVolume(tmpl *wfv1.Template, path string) *apiv1.VolumeMount
 	var volMnt *apiv1.VolumeMount
 	deepestLen := 0
 	for _, mnt := range tmpl.GetVolumeMounts() {
-		if path != mnt.MountPath && !strings.HasPrefix(path, mnt.MountPath+"/") {
+		mnt := mnt
```
Comment (rccrdpccl) [inline workflow/common/util.go:40]: I've discovered this additional bug by adding an extra volume and run the test. If not scoped correctly, `mnt` would change value of `volMnt`.

Comment (alexec) [reply workflow/common/util.go:40]: I don't understand this line - it appears to be a no-op?

File: workflow/common/util_test.go [hunk 2]
```diff
@@ -57,14 +57,24 @@ func TestFindOverlappingVolume(t *testing.T) {
 		Name:      "workdir",
 		MountPath: "/user-mount",
 	}
+	volMntTrailing := corev1.VolumeMount{
```
Comment (alexec) [inline workflow/common/util_test.go:60]: good test!

File: workflow/common/util.go (hunk 1 above)
Comment (rccrdpccl) [reply workflow/common/util.go:40]: It appears, however `mnt` *will* change value in the for loop. As it is copied by reference, the actual value will be changed once `volMnt` is returned.

This can be tested by leaving the old code but adding multiple volumeMounts in the test.

Comment (rccrdpccl) [reply workflow/common/util.go:40]: With the line `mnt := mnt` we are changing scope of the `mnt` variable and thus creating an new variable with different reference (that will be copied later)

Comment (simster7) [reply workflow/common/util.go:40]: Could we at least have the second `mnt` have a different name?
```suggestion
		mount := mnt
```

Or something?

Comment (alexec) [reply workflow/common/util.go:40]: this seems odd to me, not something I would expect Go to do, not saying it is wrong, just that it unconventional. We want the deepest mount yes, so how about we sort the mounts by `len(mnt.MountPath)` (longest first) and then use the first that matches

File: workflow/common/util_test.go [hunk 3]
```diff
@@ -57,14 +57,38 @@ func TestFindOverlappingVolume(t *testing.T) {
...
+			VolumeMounts: []corev1.VolumeMount{volMnt, deeperVolMnt},
 		},
 	}
+
 	assert.Equal(t, &volMnt, FindOverlappingVolume(templateWithVolMount, "/user-mount"))
 	assert.Equal(t, &volMnt, FindOverlappingVolume(templateWithVolMount, "/user-mount/subdir"))
-	assert.Nil(t, FindOverlappingVolume(templateWithVolMount, "/user-mount-coincidental-prefix"))
+	assert.Equal(t, &volMnt, FindOverlappingVolume(templateWithVolMount, "/user-mount/"))
+
+	assert.Equal(t, &deeperVolMnt, FindOverlappingVolume(templateWithDeeperVolMount, "/user-mount/deeper"))
```
Comment (rccrdpccl) [inline workflow/common/util_test.go:85]: These tests make sure that the slice is sorted (if it wasn't sorted, the first path would match)

**Review by alexec — APPROVED** [review]
