### PR TITLE
fix: Workflow level http template hook status update. Fixes #8529

### LINKED ISSUE #8529: LifeCycle hooks phase not updated at workflow level
## Summary

The phase of LifeCycle hooks configured at a workflows level are not updated once complete. They are stuck in 'pending' state forever. 

This prevents workflows from being retried, which negatively impacts long running workflows with lots of steps 

What happened/what you expected to happen?

Lifecycle hook phase should change to 'Completed' once completed

What version are you running?

v3.3.3

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

Fixes #8529

### CODE REVIEW

File: workflow/controller/hooks.go [hunk 1]
```diff
@@ -24,11 +24,15 @@ func (woc *wfOperationCtx) executeWfLifeCycleHook(ctx context.Context, tmplCtx *
 		if execute {
 			hookNodeName := generateLifeHookNodeName(woc.wf.ObjectMeta.Name, string(hookName))
 			woc.log.WithField("lifeCycleHook", hookName).WithField("node", hookNodeName).Infof("Running workflow level hooks")
-			_, err := woc.executeTemplate(ctx, hookNodeName, &wfv1.WorkflowStep{Template: hook.Template, TemplateRef: hook.TemplateRef}, tmplCtx, hook.Arguments, &executeTemplateOpts{})
+			hookNode, err := woc.executeTemplate(ctx, hookNodeName, &wfv1.WorkflowStep{Template: hook.Template, TemplateRef: hook.TemplateRef}, tmplCtx, hook.Arguments, &executeTemplateOpts{})
 			if err != nil {
 				return err
 			}
 			woc.addChildNode(woc.wf.Name, hookNodeName)
+			// If the hookNode node is HTTP template, it requires HTTP reconciliation, do it here
```
Comment (alexec) [inline workflow/controller/hooks.go:32]: needs a test

Comment (sarabala1979) [reply workflow/controller/hooks.go:32]: added test

**Review by terrytangyuan — APPROVED** [review]
