### PR TITLE
fix: transient errors for s3 artifacts: Fixes #7349

### LINKED ISSUE #7349: When connection problems occur while loading artifacts, the workflow init step exits and the workflow fails.
## Summary

*What happened/what you expected to happen?*

When connection problems occur while loading artifacts, the workflow init step exits and the workflow fails. This is a regression. 
We propose a fix in PR: [7352](https://github.com/argoproj/argo-workflows/pull/7352).

In this PR we add an extra check for Transient errors every time the S3 Transient errors are checked. 

What version is it broken in?

3.1.0 >=

(but mainly tested with 3.2.4)

What version was it working in?

v3.0.8

## Diagnostics

I have reproduced this error by sabotaging the connection with S3 right away when the `init` for the `use-artifact` task starts for a workflow with the workflow manifest: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: s3-test
  namespace: delivery
spec:
  entrypoint: s3-test
  templates:
  - name: s3-test
    dag:
      tasks:
        - name: use-artifact
          template: use-artifact
          arguments:
            params:
            - name: index
              value: "{{item}}"
            artifacts:
              - name: big-file
                s3:
                  endpoint: s3-endpoint:9000
                  insecure: true
                  accessKeySecret:
                    key: S3_ACCESS_KEY
                    name: TODO
                  secretKeySecret:
                    key: S3_SECRET_KEY
                    name: TODO
                  bucket: testbucket
                  key: "testprefix/testfile.bigfile"
          withParam: '["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]'

  - name: use-artifact
    activeDeadlineSeconds: 18000
    inputs:
      artifacts:
        - name: big-file
          path: "/data/testfile.bigfile"
          archive:
            none: {}
      params:
        - name: index
          value: "{{item}}"
    env:
      - name: INDEX
        value: "{{inputs.parameters.index}}"
    script:
      image: busybox
      command: [sh]
      source: |
        #!/usr/bin/env sh
        echo "In use-artifact # ${INDEX}"
        ls /data

```

*What Kubernetes provider are you using?*

AKS / K3s (for local testing)

*What executor are you running?* K8SAPI/Kubelet

the worklfow controller I used was: `argoproj/workflow-controller:v3.2.4`

the argo executor: `argoproj/argoexec:v3.2.4`

```bash
# Logs from the workflow controller:
time="2021-12-06T14:27:44Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true
time="2021-12-06T14:27:44Z" level=info msg="cron config" cronSyncPeriod=10s
time="2021-12-06T14:27:44.608Z" level=info msg="not enabling pprof debug endpoints"
time="2021-12-06T14:27:44.611Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-12-06T14:27:44.625Z" level=info msg="Get configmaps 200"
time="2021-12-06T14:27:44.630Z" level=info msg="Configuration:\nartifactRepository:\n  s3:\n    accessKeySecret:\n      key: access-key\n      name: s3-argo\n    bucket: argo-artifacts\n    endpoint: s3-endpoint:9000\n    insecure: true\n    secretKeySecret:\n      key: secret-key\n      name: s3-argo\ncontainerRuntimeExecutor: pns\nexecutor:\n  env:\n  - name: RETRY_BACKOFF_DURATION\n    value: 10s\n  - name: TRANSIENT_ERROR_PATTERN\n    value: 'network is unreachable|connection reset by peer|EOF|tcp: lookup|TLS handshake|dial\n      tcp'\n  imagePullPolicy: IfNotPresent\n  name: \"\"\n  resources:\n    limits:\n      cpu: 100m\n      memory: 512Mi\n    requests:\n      cpu: 100m\n      memory: 128Mi\ninitialDelay: 0s\nmetricsConfig: {}\nnodeEvents: {}\npersistence:\n  clusterName: local\n  connectionPool:\n    maxIdleConns: 100\n  nodeStatusOffLoad: true\n  postgresql:\n    database: argo\n    host: database.default\n    passwordSecret:\n      key: password\n      name: postgres-argo\n    port: 5432\n    sslMode: disable\n    tableName: argo_workflows\n    userNameSecret:\n      key: username\n      name: postgres-argo\npodSpecLogStrategy: {}\ntelemetryConfig: {}\n"
time="2021-12-06T14:27:44.630Z" level=info msg="Persistence configuration enabled"
time="2021-12-06T14:27:44.630Z" level=info msg="Creating DB session"
time="2021-12-06T14:27:44.633Z" level=info msg="Get secrets 200"
time="2021-12-06T14:27:44.636Z" level=info msg="Get secrets 200"
time="2021-12-06T14:27:49.725Z" level=info msg="Persistence Session created successfully"
time="2021-12-06T14:27:49.726Z" level=info msg="Migrating database schema" clusterName=local dbType=postgres
time="2021-12-06T14:27:49.816Z" level=info msg="Node status offloading config" ttl=5m0s
time="2021-12-06T14:27:49.816Z" level=info msg="Node status offloading is enabled"
time="2021-12-06T14:27:49.816Z" level=info msg="Workflow archiving is disabled"
time="2021-12-06T14:27:49.817Z" level=info msg="Starting Workflow Controller" version=v3.2.4
time="2021-12-06T14:27:49.817Z" level=info msg="Workers: workflow: 32, pod: 32, pod cleanup: 4"
time="2021-12-06T14:27:49.825Z" level=info msg="List workflows 200"
time="2021-12-06T14:27:49.833Z" level=info msg="Manager initialized successfully"
time="2021-12-06T14:27:49.835Z" level=info msg="List configmaps 200"
time="2021-12-06T14:27:49.835Z" level=info msg="List workflowtasksets 200"
time="2021-12-06T14:27:49.836Z" level=info msg="List configmaps 200"
time="2021-12-06T14:27:49.836Z" level=info msg="Watch configmaps 200"
time="2021-12-06T14:27:49.840Z" level=info msg="List workflows 200"
time="2021-12-06T14:27:49.836Z" level=info msg="Watch configmaps 200"
time="2021-12-06T14:27:49.839Z" level=info msg="List workflowtemplates 200"
time="2021-12-06T14:27:49.839Z" level=info msg="List pods 200"
time="2021-12-06T14:27:49.841Z" level=info msg="Watch configmaps 200"
time="2021-12-06T14:27:49.846Z" level=info msg="Watch workflowtasksets 200"
time="2021-12-06T14:27:49.849Z" level=info msg="Watch workflowtemplates 200"
time="2021-12-06T14:27:49.853Z" level=info msg="Watch workflows 200"
time="2021-12-06T14:27:49.853Z" level=info msg="Watch pods 200"
time="2021-12-06T14:27:49.938Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-12-06T14:27:49.939Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-12-06T14:27:49.941Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-12-06T14:27:49.941Z" level=info msg="Leader election is turned off. Running in single-instance mode"
time="2021-12-06T14:27:49.941Z" level=info msg="started leading" id=single-instance
time="2021-12-06T14:27:49.941Z" level=info msg="Starting CronWorkflow controller"
time="2021-12-06T14:27:49.941Z" level=info msg="Performing periodic GC every 5m0s"
time="2021-12-06T14:27:49.942Z" level=info msg="Archive disabled - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2021-12-06T14:27:49.942Z" level=info msg="Starting workflow TTL controller (workflowTTLWorkers 4)"
time="2021-12-06T14:27:49.942Z" level=info msg="Started workflow TTL worker"
time="2021-12-06T14:27:49.943Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2021-12-06T14:27:49.945Z" level=info msg="List workflows 200"
time="2021-12-06T14:27:49.946Z" level=info msg="List clusterworkflowtemplates 200"
time="2021-12-06T14:27:49.946Z" level=info msg="List cronworkflows 200"
time="2021-12-06T14:27:49.948Z" level=info msg="Watch cronworkflows 200"
time="2021-12-06T14:27:49.948Z" level=info msg="Watch clusterworkflowtemplates 200"
time="2021-12-06T14:27:49.948Z" level=info msg="Watch workflows 200"
time="2021-12-06T14:27:49.952Z" level=info msg="List workflows 200"
time="2021-12-06T14:27:49.952Z" level=info msg="Processing workflow" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.957Z" level=info msg="Get configmaps 404"
time="2021-12-06T14:27:49.958Z" level=warning msg="Non-transient error: configmaps \"artifact-repositories\" not found"
time="2021-12-06T14:27:49.958Z" level=info msg="resolved artifact repository" artifactRepositoryRef=default-artifact-repository
time="2021-12-06T14:27:49.958Z" level=info msg="Updated phase  -> Running" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.958Z" level=info msg="DAG node s3-test initialized Running" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.958Z" level=info msg="TaskGroup node s3-test-2947705148 initialized Running (message: )" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.958Z" level=info msg="All of node s3-test.use-artifact(0:1) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.959Z" level=info msg="Pod node s3-test-4277031784 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.963Z" level=info msg="Create events 201"
time="2021-12-06T14:27:49.964Z" level=info msg="Queueing Succeeded workflow delivery/ihr-rp-cleanup-s3-artifacts-v1-0-gcvr6 for delete in 6m48s"
time="2021-12-06T14:27:49.964Z" level=info msg="Queueing Succeeded workflow delivery/ihr-rp-cleanup-s3-artifacts-v1-0-lxt55 for delete in 7m48s"
time="2021-12-06T14:27:49.966Z" level=info msg="Watch workflows 200"
time="2021-12-06T14:27:49.967Z" level=info msg="Queueing Succeeded workflow delivery/ihr-rp-cleanup-s3-artifacts-v1-0-gcvr6 for delete in 6m48s"
time="2021-12-06T14:27:49.968Z" level=info msg="Queueing Succeeded workflow delivery/ihr-rp-cleanup-s3-artifacts-v1-0-lxt55 for delete in 7m48s"
time="2021-12-06T14:27:49.973Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:49.976Z" level=info msg="Created pod: s3-test.use-artifact(0:1) (s3-test-4277031784)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.976Z" level=info msg="All of node s3-test.use-artifact(1:2) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.977Z" level=info msg="Pod node s3-test-4104246146 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.984Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:49.985Z" level=info msg="Created pod: s3-test.use-artifact(1:2) (s3-test-4104246146)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.985Z" level=info msg="All of node s3-test.use-artifact(2:3) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.985Z" level=info msg="Pod node s3-test-730929232 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.996Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:49.997Z" level=info msg="Created pod: s3-test.use-artifact(2:3) (s3-test-730929232)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.997Z" level=info msg="All of node s3-test.use-artifact(3:4) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:49.997Z" level=info msg="Pod node s3-test-3760270942 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.006Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:50.007Z" level=info msg="Created pod: s3-test.use-artifact(3:4) (s3-test-3760270942)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.007Z" level=info msg="All of node s3-test.use-artifact(4:5) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.007Z" level=info msg="Pod node s3-test-1166831712 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.016Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:50.017Z" level=info msg="Created pod: s3-test.use-artifact(4:5) (s3-test-1166831712)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.017Z" level=info msg="All of node s3-test.use-artifact(5:6) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.017Z" level=info msg="Pod node s3-test-995326002 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.025Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:50.026Z" level=info msg="Created pod: s3-test.use-artifact(5:6) (s3-test-995326002)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.026Z" level=info msg="All of node s3-test.use-artifact(6:7) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.027Z" level=info msg="Pod node s3-test-1285683160 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.034Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:50.035Z" level=info msg="Created pod: s3-test.use-artifact(6:7) (s3-test-1285683160)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.035Z" level=info msg="All of node s3-test.use-artifact(7:8) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.035Z" level=info msg="Pod node s3-test-1168726182 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.041Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:50.043Z" level=info msg="Created pod: s3-test.use-artifact(7:8) (s3-test-1168726182)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.043Z" level=info msg="All of node s3-test.use-artifact(8:9) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.043Z" level=info msg="Pod node s3-test-2043629272 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.050Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:50.050Z" level=info msg="Created pod: s3-test.use-artifact(8:9) (s3-test-2043629272)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.050Z" level=info msg="All of node s3-test.use-artifact(9:10) dependencies [] completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.051Z" level=info msg="Pod node s3-test-2113296805 initialized Pending" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.064Z" level=info msg="Create pods 201"
time="2021-12-06T14:27:50.064Z" level=info msg="Created pod: s3-test.use-artifact(9:10) (s3-test-2113296805)" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.065Z" level=info msg="TaskSet Reconciliation" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.065Z" level=info msg=reconcileAgentPod namespace=delivery workflow=s3-test
time="2021-12-06T14:27:50.083Z" level=info msg="Update workflows 200"
time="2021-12-06T14:27:50.095Z" level=info msg="Workflow update successful" namespace=delivery phase=Running resourceVersion=25332 workflow=s3-test
time="2021-12-06T14:27:50.100Z" level=info msg="Create events 201"
time="2021-12-06T14:27:50.103Z" level=info msg="Create events 201"
time="2021-12-06T14:27:59.979Z" level=info msg="Processing workflow" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-2113296805 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-730929232 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-3760270942 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-1166831712 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-995326002 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-1285683160 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-1168726182 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-4277031784 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-4104246146 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.980Z" level=info msg="Updating node s3-test-2043629272 message: PodInitializing" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.983Z" level=info msg="TaskSet Reconciliation" namespace=delivery workflow=s3-test
time="2021-12-06T14:27:59.983Z" level=info msg=reconcileAgentPod namespace=delivery workflow=s3-test
time="2021-12-06T14:28:00.001Z" level=info msg="Update workflows 200"
time="2021-12-06T14:28:00.001Z" level=info msg="Workflow update successful" namespace=delivery phase=Running resourceVersion=25569 workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Processing workflow" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(8:9)" namespace=delivery pod=s3-test-2043629272 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-2043629272 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-2043629272 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(5:6)" namespace=delivery pod=s3-test-995326002 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-995326002 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-995326002 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(1:2)" namespace=delivery pod=s3-test-4104246146 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-4104246146 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-4104246146 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(2:3)" namespace=delivery pod=s3-test-730929232 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-730929232 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-730929232 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(3:4)" namespace=delivery pod=s3-test-3760270942 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-3760270942 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-3760270942 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(4:5)" namespace=delivery pod=s3-test-1166831712 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-1166831712 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-1166831712 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(7:8)" namespace=delivery pod=s3-test-1168726182 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.002Z" level=info msg="Updating node s3-test-1168726182 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Updating node s3-test-1168726182 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(6:7)" namespace=delivery pod=s3-test-1285683160 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Updating node s3-test-1285683160 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Updating node s3-test-1285683160 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(0:1)" namespace=delivery pod=s3-test-4277031784 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Updating node s3-test-4277031784 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Updating node s3-test-4277031784 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Pod failed: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" displayName="use-artifact(9:10)" namespace=delivery pod=s3-test-2113296805 templateName=use-artifact workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Updating node s3-test-2113296805 status Pending -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.003Z" level=info msg="Updating node s3-test-2113296805 message: Error (exit code 1): artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.005Z" level=info msg="node s3-test-2947705148 phase Running -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="node s3-test-2947705148 finished: 2021-12-06 14:28:10.0060263 +0000 UTC" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="Outbound nodes of s3-test set to [s3-test-4277031784 s3-test-4104246146 s3-test-730929232 s3-test-3760270942 s3-test-1166831712 s3-test-995326002 s3-test-1285683160 s3-test-1168726182 s3-test-2043629272 s3-test-2113296805]" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="node s3-test phase Running -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="node s3-test finished: 2021-12-06 14:28:10.0061608 +0000 UTC" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="Checking daemoned children of s3-test" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="TaskSet Reconciliation" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg=reconcileAgentPod namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="Updated phase Running -> Error" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="Marking workflow completed" namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.006Z" level=info msg="Checking daemoned children of " namespace=delivery workflow=s3-test
time="2021-12-06T14:28:10.010Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.020Z" level=info msg="Update workflows 200"
time="2021-12-06T14:28:10.020Z" level=info msg="Workflow update successful" namespace=delivery phase=Error resourceVersion=25726 workflow=s3-test
time="2021-12-06T14:28:10.023Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.027Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-730929232/labelPodCompleted
time="2021-12-06T14:28:10.027Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-4277031784/labelPodCompleted
time="2021-12-06T14:28:10.027Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-3760270942/labelPodCompleted
time="2021-12-06T14:28:10.027Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-2113296805/labelPodCompleted
time="2021-12-06T14:28:10.027Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.033Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.038Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.039Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-2043629272/labelPodCompleted
time="2021-12-06T14:28:10.042Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.042Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.042Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.042Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-995326002/labelPodCompleted
time="2021-12-06T14:28:10.043Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-4104246146/labelPodCompleted
time="2021-12-06T14:28:10.046Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.047Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-1166831712/labelPodCompleted
time="2021-12-06T14:28:10.052Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.052Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-1168726182/labelPodCompleted
time="2021-12-06T14:28:10.056Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.056Z" level=info msg="cleaning up pod" action=labelPodCompleted key=delivery/s3-test-1285683160/labelPodCompleted
time="2021-12-06T14:28:10.060Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.063Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.065Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.068Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.070Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.071Z" level=info msg="Patch pods 200"
time="2021-12-06T14:28:10.079Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.087Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.090Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.093Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.096Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.099Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.102Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.105Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.109Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.112Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.115Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.118Z" level=info msg="Create events 201"
time="2021-12-06T14:28:10.123Z" level=info msg="Patch events 200"
time="2021-12-06T14:28:10.127Z" level=info msg="Patch events 200"
time="2021-12-06T14:28:10.131Z" level=info msg="Patch events 200"
time="2021-12-06T14:28:10.162Z" level=info msg="Patch events 200"
time="2021-12-06T14:29:44.076Z" level=info msg="List workflows 200"
time="2021-12-06T14:29:44.076Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=delivery

# The workflow's pods that are problematic:
s3-test-2113296805                                         0/2     Init:Error   0          5m1s
s3-test-4277031784                                         0/2     Init:Error   0          5m2s
s3-test-3760270942                                         0/2     Init:Error   0          5m1s
s3-test-730929232                                          0/2     Init:Error   0          5m2s
s3-test-2043629272                                         0/2     Init:Error   0          5m1s
s3-test-4104246146                                         0/2     Init:Error   0          5m2s
s3-test-1166831712                                         0/2     Init:Error   0          5m1s
s3-test-995326002                                          0/2     Init:Error   0          5m1s
s3-test-1168726182                                         0/2     Init:Error   0          5m1s
s3-test-1285683160                                         0/2     Init:Error   0          5m1s

# Logs from in the use-artifact workflow's init container:
time="2021-12-06T14:28:02.760Z" level=info msg="Starting Workflow Executor" executorType=pns version=v3.2.4
time="2021-12-06T14:28:02.762Z" level=info msg="Creating a pns executor"
time="2021-12-06T14:28:02.762Z" level=info msg="Initialized PNS executor (namespace: delivery, pod: s3-test-2113296805, pid: 8)"
time="2021-12-06T14:28:02.762Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=delivery podName=s3-test-2113296805 template="{\"name\":\"use-artifact\",\"inputs\":{\"artifacts\":[{\"name\":\"big-file\",\"path\":\"/data/testfile.bigfile\",\"s3\":{\"endpoint\":\"s3-endpoint:9000\",\"bucket\":\"testbucket\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"s3-endpoint-94727k6g52\",\"key\":\"S3_ACCESS_KEY\"},\"secretKeySecret\":{\"name\":\"s3-endpoint-94727k6g52\",\"key\":\"S3_SECRET_KEY\"},\"key\":\"testprefix/testfile.bigfile\"}}]},\"outputs\":{},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"busybox\",\"command\":[\"sh\"],\"resources\":{},\"source\":\"#!/usr/bin/env sh\\necho \\\"In use-artifact # ${INDEX}\\\"\\nls /data\\n\"},\"activeDeadlineSeconds\":18000}" version="&Version{Version:v3.2.4,BuildDate:2021-11-17T23:18:57Z,GitCommit:8771ca279c329753e420dbdd986a9c914876b151,GitTag:v3.2.4,GitTreeState:clean,GoVersion:go1.16.10,Compiler:gc,Platform:linux/amd64,}"
time="2021-12-06T14:28:02.762Z" level=info msg="Loading script source to /argo/staging/script"
time="2021-12-06T14:28:02.763Z" level=info msg="Start loading input artifacts..."
time="2021-12-06T14:28:02.763Z" level=info msg="Downloading artifact: big-file"
time="2021-12-06T14:28:02.763Z" level=info msg="S3 Load path: /argo/inputs/artifacts/big-file.tmp, key: testprefix/testfile.bigfile"
time="2021-12-06T14:28:02.763Z" level=info msg="Creating s3-endpoint client using static credentials" endpoint="s3-endpoint:9000"
time="2021-12-06T14:28:02.763Z" level=info msg="Getting file from s3" bucket=testbucket endpoint="s3-endpoint:9000" key=testprefix/testfile.bigfile path=/argo/inputs/artifacts/big-file.tmp
time="2021-12-06T14:28:02.764Z" level=error msg="executor error: artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused"
time="2021-12-06T14:28:02.764Z" level=info msg="Alloc=5058 TotalAlloc=9453 Sys=73809 NumGC=3 Goroutines=3"
time="2021-12-06T14:28:02.765Z" level=fatal msg="artifact big-file failed to load: failed to get file: Get \"http://s3-endpoint:9000/testbucket/?location=\": dial tcp XXX.XXX.XXX.XXX:9000: connect: connection refused"


# Logs from in the workflow's wait container:
Error from server (BadRequest): container "wait" in pod "s3-test-4277031784" is waiting to start: PodInitializing

```

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍

### PR DESCRIPTION
**Pull request by RoelvandenBerg**
When connection problems occur while loading artifacts, the workflow init step exits and the workflow fails. This is a regression.
We propose a fix in this PR for issue: #7349.
Fixes #7349

In this PR we add an extra check for Transient errors every time the S3 Transient errors are checked.

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

File: workflow/artifacts/s3/s3.go [hunk 1]
```diff
@@ -72,7 +79,7 @@ func (s3Driver *ArtifactDriver) Load(inputArtifact *wfv1.Artifact, path string)
 			log.Infof("S3 Load path: %s, key: %s", path, inputArtifact.S3.Key)
 			s3cli, err := s3Driver.newS3Client(ctx)
 			if err != nil {
-				return !isTransientS3Err(err), fmt.Errorf("failed to create new S3 client: %v", err)
+				return !(isTransientS3Err(err) || errorsutil.IsTransientErr(err)), fmt.Errorf("failed to create new S3 client: %v", err)
```
Comment (alexec) [inline workflow/artifacts/s3/s3.go:82]: what about changing `isTransientS3Err` to call `IsTransientErr`. To avoid duplication.

File: workflow/artifacts/s3/s3.go [hunk 2]
```diff
@@ -37,7 +39,12 @@ type ArtifactDriver struct {
 
 var (
 	_            artifactscommon.ArtifactDriver = &ArtifactDriver{}
-	defaultRetry                                = wait.Backoff{Duration: time.Second * 2, Factor: 2.0, Steps: 5, Jitter: 0.1}
+	defaultRetry                                = wait.Backoff{
```
Comment (alexec) [inline workflow/artifacts/s3/s3.go:42]: I don't think this will work, because these enviers are never set.

File: workflow/artifacts/s3/s3.go (hunk 1 above)
Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go:82]: Sounds good. Will do.

File: workflow/artifacts/s3/s3.go (hunk 2 above)
Comment (alexec) [reply workflow/artifacts/s3/s3.go:42]: Could you propose new hard-coded values? Presumably more retries?

Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go:42]: This way we are able to set the retry in a way that matches our situation.

Comment (terrytangyuan) [reply workflow/artifacts/s3/s3.go:41]: I recall that we had some logic on this on an `init()` somewhere. Perhaps see if you can reuse those instead.

File: workflow/artifacts/s3/s3.go [hunk 3]
```diff
@@ -89,20 +96,20 @@ func loadS3Artifact(s3cli argos3.S3Client, inputArtifact *wfv1.Artifact, path st
 		return true, nil
 	}
 	if !argos3.IsS3ErrCode(origErr, "NoSuchKey") {
-		return !isTransientS3Err(origErr), fmt.Errorf("failed to get file: %v", origErr)
+		return !(isTransientS3Err(origErr) || errorsutil.IsTransientErr(origErr)), fmt.Errorf("failed to get file: %v", origErr)
```
Comment (terrytangyuan) [inline workflow/artifacts/s3/s3.go]: Merge these to a single function?

File: workflow/artifacts/s3/s3.go (hunk 2 above)
Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go:41]: @terrytangyuan and @alexec I propose to use `DefaultRetry` from `util/retry/retry.go:18` 
except that `DefaultRetry` doesn't have jitter. Is it ok to add jitter to `DefaultRetry`? Or rather not?

Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go:41]: Or does `DefaultRetry` fit the bill beter / or perhaps even its own set of env parameters since you might see this as a special case (like `DefaultRetry` and `ExecutorRetry`)?

Comment (alexec) [reply workflow/artifacts/s3/s3.go:41]: whatever we do, please log the settings

Comment (terrytangyuan) [reply workflow/artifacts/s3/s3.go:41]: Definitely not S3 specific retries. ExecutorRetry sounds good. Perhaps this PR can be generalized to other artifact drivers? WDYT @alexec

Comment (alexec) [reply workflow/artifacts/s3/s3.go:41]: I think we should be able to set-up different one for different cases. But, I wonder if we want to do more retries for artifacts by default? E.g. spend up-to 1m trying to get it?

Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go:41]: The current retries have been in the code for a while. This was the last time they were increased: https://github.com/argoproj/argo-workflows/pull/1138 which fixes this issue: https://github.com/argoproj/argo-workflows/issues/1081, there is a difference between the two: 10 milliseconds (or less than a second) and the current 2 seconds (a bit over a minute). For our case (large workflows with a lot of steps that take a long time to process) waiting a bit for a transient errors is ok and I even tweaked them higher so both backoffs are even a bit too small for our case.

Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go:41]: @alexec and @terrytangyuan what do you think about using `ExecutorRetry` as default? I somehow don't feel I should make this decision. I'm quite agnostic to what default is used, apart from my thoughts above ☝️. 
If you decide I'll make a commit that contains that and:

> whatever we do, please log the settings

**Review by alexec — DISMISSED** [review]
`lint` build is failing where running `./hack/check-logging.sh`. Can you run this script and check output? It's meant to make sure you do not add `Infof/Errorf` logging statements.

**Comment by RoelvandenBerg** [comment]
I found a problem in my local test setup. That is fixed now. Sorry for the many fix: codestyle commits. I'm going to squash the previous (codestyle) commits run the tests again and force push them again.

File: workflow/artifacts/s3/s3.go (hunk 2 above)
Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go:41]: The idea of using the ExecutorRetry creates a cyclical import.

**Comment by alexec** [comment]
@terrytangyuan would you be willing to own reviewing this?

File: workflow/artifacts/s3/s3.go (hunk 2 above)
Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go:41]: I propose this solution: https://github.com/PDOK/argo-workflows/pull/3

File: workflow/artifacts/s3/s3.go [hunk 4]
```diff
@@ -37,7 +38,12 @@ type ArtifactDriver struct {
 
 var (
 	_            artifactscommon.ArtifactDriver = &ArtifactDriver{}
-	defaultRetry                                = wait.Backoff{Duration: time.Second * 2, Factor: 2.0, Steps: 5, Jitter: 0.1}
+	defaultRetry                                = wait.Backoff{
+		Steps:    envutil.LookupEnvIntOr("RETRY_BACKOFF_STEPS", 5),
+		Duration: envutil.LookupEnvDurationOr("RETRY_BACKOFF_DURATION", time.Second*2),
```
Comment (terrytangyuan) [inline workflow/artifacts/s3/s3.go:43]: Consider moving this to a separate file to avoid cyclical imports? 

Also please log these variables. Example: https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/cache_gc.go#L22-L24

Comment (RoelvandenBerg) [reply workflow/artifacts/s3/s3.go]: @terrytangyuan I fixed the executor retry strategy logging to log the moment an executor is instantiated (otherwise it would also log these  when using the argo cli).

**Review by terrytangyuan — APPROVED** [review]

**Comment by RoelvandenBerg** [comment]
In case you want me to rebase onto master and force-push this to deal with the lint error, just let me know.

**Comment by terrytangyuan** [comment]
Yes please fix the lint errors

**Comment by ado120** [comment]
Hey all, 

I have an issue currently with a s3 backend for workflow artifacts. If I run a workflow I'm able to view the pod logs for a few minutes before I get a 500 Internal Server Error. Is this related? Using Argo Workflows 3.2.4
