### PR TITLE
fix(controller): default volume/mount to emissary. Fixes #7118

### LINKED ISSUE #7118: Bug in default executor code
## Summary

This link looks wrong, "" should not be docker anymore:

https://github.com/argoproj/argo-workflows/blob/ca87f2906995b8fecb796d94299f54f6dfbd6a41/workflow/controller/workflowpod.go#L538

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by tczhao**
fixes #7118

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

File: workflow/controller/workflowpod.go [hunk 1]
```diff
@@ -638,10 +638,10 @@ func (woc *wfOperationCtx) createVolumes(tmpl *wfv1.Template) []apiv1.Volume {
 	}
 	switch woc.getContainerRuntimeExecutor() {
 	case common.ContainerRuntimeExecutorKubelet, common.ContainerRuntimeExecutorK8sAPI, common.ContainerRuntimeExecutorPNS:
-	case common.ContainerRuntimeExecutorEmissary:
-		volumes = append(volumes, volumeVarArgo)
-	default:
+	case common.ContainerRuntimeExecutorDocker:
 		volumes = append(volumes, woc.getVolumeDockerSock(tmpl))
+	default:
+		volumes = append(volumes, volumeVarArgo)
```
Comment (mweibel) [inline workflow/controller/workflowpod.go:644]: if I may (been working on #6714 so I saw this too): this changes behaviour because Go's switch-case doesn't fallthrough by default. Before only emissary had /var/run/argo as volume, with this change all except Docker have it as volume. 
This changes anyway in #6714 (all will have that volume + mount) so I'm not sure how important it is to get the correct behaviour here.

Comment (alexec) [reply workflow/controller/workflowpod.go:644]: +1

Comment (tczhao) [reply workflow/controller/workflowpod.go:644]: Correct me if I'm wrong. Because go doesn't fall through by default, we have the following and the behaviour is expected

```
pns/k8sapi/kubelet:
   do nothing
docker:
   attach dockerSock
emissary or empty (default):
   attach varArgo
```

**Review by alexec — APPROVED** [review]

File: workflow/controller/workflowpod.go (hunk 1 above)
Comment (mweibel) [reply workflow/controller/workflowpod.go:644]: aah, right. My bad. Sorry about the confusion.
