### PR TITLE
fix: add retry for invalid connection. Fixes #13578

### LINKED ISSUE #13578: Invalid connection error should retry
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

My large workflow failed when encounter "invalid connection", Because my cluster has been working fine, this is an occasional problem.
We should retry when offload info encounters this error.

### Version(s)

latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
time="2024-09-09T13:24:51.702Z" level=warning msg="Non-transient error: invalid connection"
31605 time="2024-09-09T13:24:51.702Z" level=warning msg="Failed to dehydrate: workflow is longer than maximum allowed size. compressed size 1113230 > maxSize 1048576Tried to of      fload but encountered error: invalid connection" namespace=default workflow=large-workflow-t696s
31606 time="2024-09-09T13:24:51.703Z" level=info msg="cleaning up pod" action=deletePod key=default/large-workflow-t696s-sleep-545703870/deletePod
31607 time="2024-09-09T13:24:51.705Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=large-workflow-t696s
31608 time="2024-09-09T13:24:51.705Z" level=info msg="Updated message  -> workflow is longer than maximum allowed size. compressed size 1113230 > maxSize 1048576Tried to offloa      d but encountered error: invalid connection" namespace=default workflow=large-workflow-t696s
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by shuangkun**
My large workflow failed when encounter "invalid connection".  My cluster has been working fine, this is an occasional problem.We should retry when offload info encounters this error.

Fixes #13578

### CODE REVIEW

File: util/errors/errors.go [hunk 1]
```diff
@@ -112,6 +112,9 @@ func isTransientNetworkErr(err error) bool {
 	} else if strings.Contains(errorString, "connect: connection refused") {
 		// If err is connection refused, retry.
 		return true
+	} else if strings.Contains(errorString, "invalid connection") {
```
Comment (terrytangyuan) [inline util/errors/errors.go:115]: Is this a common error or is it a vendor specific error?

Comment (shuangkun) [reply util/errors/errors.go:115]: looks like a common error https://stackoverflow.com/questions/65253798/go-sql-driver-get-invalid-connection-when-wait-timeout-is-8h-as-default

**Comment by shuangkun** [comment]
After many tests，I have verified that this correction method is useful when running many large workflows in the cluster. We can avoid failure when encountering invalid connection.

**Review by terrytangyuan — APPROVED** [review]
