### PR TITLE
feat: fix bugs in retryWorkflow if failed pod node has children nodes. Fix #9244

### LINKED ISSUE #9244: argo retry ends up in runtime error: invalid memory address or nil pointer dereference
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

Launching a retry of the workflow using the command:
❯ argo retry test-pipeline-testbug --node-field-selector=displayName=test-api-account-contract -n cloud-workflows
INFO[2022-07-27T21:59:29.478Z] Deleting pod: test-pipeline-testbug-3884315966
INFO[2022-07-27T21:59:29.673Z] Deleting pod: test-pipeline-testbug-3458427787
INFO[2022-07-27T21:59:29.798Z] Deleting pod: test-pipeline-testbug-2633680513

Since I selected a specific node we would have expected to see only pod deleted but there were three (but we are not sure we properly understand the retry command).

Then the workflow ends up broken in the UI with the message: 
image
and on one step there is the message:
"Ancestor task node kube-prometheus-stack-helm not found"

What we expected is that the workflow specific node that was failed (test-api-account-contract) would have restarted successfully and only this one.

What version are you running?
v3.3.8

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

The DAG workflow has a step (kube-prometheus-stack-helm) that always fail so we used a continue on fail (as show in this example https://github.com/argoproj/argo-workflows/blob/master/examples/dag-continue-on-fail.yaml), then on the next steps I simulated two errors (test-stock-integration and test-api-account-contract).

Sorry it's a bit long but I didn't modify the structure of the workflow in case it matters. Also it's in Json because it's generated using the Go SDK but it should not cause any issues to debug.

```json
{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "Workflow",
  "metadata": {
    "name": "test-pipeline-testbug",
    "creationTimestamp": null,
    "generateName": "test-pipeline-"
  },
  "spec": {
    "arguments": {},
    "entrypoint": "test-pipeline-dag",
    "templates": [
      {
        "dag": {
          "tasks": [
            {
              "arguments": {},
              "name": "init-infra-app",
              "template": "init-infra-app"
            },
            {
              "arguments": {},
              "depends": "init-infra-app",
              "name": "aad-pod-identity-helm",
              "template": "aad-pod-identity-helm"
            },
            {
              "arguments": {},
              "depends": "aad-pod-identity-helm",
              "name": "akv2k8s-helm",
              "template": "akv2k8s-helm"
            },
            {
              "arguments": {},
              "depends": "akv2k8s-helm",
              "name": "dynatrace-operator-helm",
              "template": "dynatrace-operator-helm"
            },
            {
              "arguments": {},
              "depends": "dynatrace-operator-helm",
              "name": "ingress-nginx-helm",
              "template": "ingress-nginx-helm"
            },
            {
              "arguments": {},
              "depends": "akv2k8s-helm",
              "name": "kube-prometheus-stack-helm",
              "template": "kube-prometheus-stack-helm"
            },
            {
              "arguments": {},
              "depends": "aad-pod-identity-helm && akv2k8s-helm && dynatrace-operator-helm && ingress-nginx-helm && (kube-prometheus-stack-helm || kube-prometheus-stack-helm.Failed)",
              "name": "end-infra-app",
              "template": "end-infra-app"
            },
            {
              "arguments": {},
              "depends": "end-infra-app",
              "name": "init-app-config",
              "template": "init-app-config"
            },
            {
              "arguments": {},
              "depends": "init-app-config",
              "name": "app-config-backend",
              "template": "app-config-backend"
            },
            {
              "arguments": {},
              "depends": "init-app-config",
              "name": "app-config-frontend",
              "template": "app-config-frontend"
            },
            {
              "arguments": {},
              "depends": "app-config-backend && app-config-frontend",
              "name": "end-app-config",
              "template": "end-app-config"
            },
            {
              "arguments": {},
              "depends": "end-app-config",
              "name": "init-test-api",
              "template": "init-test-api"
            },
            {
              "arguments": {},
              "depends": "init-test-api",
              "name": "test-stock-integration",
              "template": "test-stock-integration"
            },
            {
              "arguments": {},
              "depends": "test-stock-integration",
              "name": "end-test-api",
              "template": "end-test-api"
            },
            {
              "arguments": {},
              "depends": "end-app-config",
              "name": "init-test-web",
              "template": "init-test-web"
            },
            {
              "arguments": {},
              "depends": "init-test-web",
              "name": "graphql-gateway",
              "template": "graphql-gateway"
            },
            {
              "arguments": {},
              "depends": "graphql-gateway",
              "name": "end-test-web",
              "template": "end-test-web"
            },
            {
              "arguments": {},
              "depends": "end-app-config",
              "name": "init-test-api-contract",
              "template": "init-test-api-contract"
            },
            {
              "arguments": {},
              "depends": "init-test-api-contract",
              "name": "test-api-account-contract",
              "template": "test-api-account-contract"
            },
            {
              "arguments": {},
              "depends": "test-api-account-contract",
              "name": "end-test-api-contract",
              "template": "end-test-api-contract"
            },
            {
              "arguments": {},
              "depends": "end-app-config",
              "name": "apim-opco",
              "template": "apim-opco"
            }
          ]
        },
        "inputs": {},
        "metadata": {},
        "name": "test-pipeline-dag",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "init-infra-app",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "init-infra-app",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "aad-pod-identity-helm",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "aad-pod-identity-helm",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "akv2k8s-helm",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "akv2k8s-helm",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "dynatrace-operator-helm",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "dynatrace-operator-helm",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "ingress-nginx-helm",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "ingress-nginx-helm",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "false"
          ],
          "image": "alpine",
          "name": "kube-prometheus-stack-helm",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "kube-prometheus-stack-helm",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "end-infra-app",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "end-infra-app",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "init-app-config",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "init-app-config",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "app-config-backend",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "app-config-backend",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "app-config-frontend",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "app-config-frontend",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "end-app-config",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "end-app-config",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "init-test-api",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "init-test-api",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "false"
          ],
          "image": "alpine",
          "name": "test-stock-integration",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "test-stock-integration",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "end-test-api",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "end-test-api",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "init-test-web",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "init-test-web",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "graphql-gateway",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "graphql-gateway",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "end-test-web",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "end-test-web",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "init-test-api-contract",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "init-test-api-contract",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "false"
          ],
          "image": "alpine",
          "name": "test-api-account-contract",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "test-api-account-contract",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "end-test-api-contract",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "end-test-api-contract",
        "outputs": {}
      },
      {
        "container": {
          "command": [
            "true"
          ],
          "image": "alpine",
          "name": "apim-opco",
          "resources": {}
        },
        "inputs": {},
        "metadata": {},
        "name": "apim-opco",
        "outputs": {}
      }
    ]
  },
  "status": {
    "finishedAt": null,
    "startedAt": null
  }
}
```

Those logs are the logs of the retry.
```bash
# Logs from the workflow controller:
time="2022-07-27T19:59:30.134Z" level=info msg="Processing workflow" namespace=cloud-workflows workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.135Z" level=info msg="Task-result reconciliation" namespace=cloud-workflows numObjs=0 workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.137Z" level=error msg="Mark error node" error="Ancestor task node kube-prometheus-stack-helm not found" namespace=cloud-workflows nodeName=test-pipeline-testbug.apim-opco workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.137Z" level=error msg="node is already fulfilled" fromPhase=Succeeded namespace=cloud-workflows nodeName=test-pipeline-testbug.apim-opco toPhase=Error workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.137Z" level=info msg="node test-pipeline-testbug-2338818649 phase Succeeded -> Error" namespace=cloud-workflows workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.137Z" level=info msg="node test-pipeline-testbug-2338818649 message: Ancestor task node kube-prometheus-stack-helm not found" namespace=cloud-workflows workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.137Z" level=error msg="Recovered from panic" namespace=cloud-workflows r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 174 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:194 +0xd4\npanic({0x1ce07c0, 0x33713e0})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x266\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfScope).addParamToScope(...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/scope.go:53\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00094c000, {0x22b0668, 0xc000058018}, 0xc000596fc0, {0xc0003d88b0, 0x9})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:381 +0x7cb\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc00094c000, {0x22b0668, 0xc000058018}, {0xc000af6c48, 0x0}, 0xc001a80180, {0xc000ffff60, 0x1e}, 0xc0013d5440, {0x2292360, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x433\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00094c000, {0x22b0668, 0xc000058018}, {0xc000af6c48, 0x18}, {0x2292360, 0xc00094c0c0}, 0xc001a80100, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1889 +0x232c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc00094c000, {0x22b0668, 0xc000058018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:350 +0x16a8\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000430000, {0x22b0668, 0xc000058018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:756 +0x8ee\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:678 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f5bdefd6cc0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x226dbe0, 0xc0016e53b0}, 0x1, 0xc00009c720)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:294 +0x1a6c\n" workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.137Z" level=info msg="Updated phase Running -> Error" namespace=cloud-workflows workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.138Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=cloud-workflows workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.139Z" level=info msg="Marking workflow completed" namespace=cloud-workflows workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.139Z" level=info msg="Checking daemoned children of " namespace=cloud-workflows workflow=test-pipeline-testbug
time="2022-07-27T19:59:30.139Z" level=info msg="Workflow to be dehydrated" Workflow Size=17271
time="2022-07-27T19:59:30.145Z" level=info msg="cleaning up pod" action=deletePod key=cloud-workflows/test-pipeline-testbug-1340600742-agent/deletePod
time="2022-07-27T19:59:30.154Z" level=info msg="Delete pods 404"
time="2022-07-27T19:59:30.157Z" level=info msg="Create events 201"
time="2022-07-27T19:59:30.175Z" level=info msg="Update workflows 200"
time="2022-07-27T19:59:30.177Z" level=info msg="Workflow update successful" namespace=cloud-workflows phase=Error resourceVersion=35575823 workflow=test-pipeline-testbug
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by smile-luobin**
Fix bugs in retry workflow if the failed node has children nodes. Fix #9244.

For example.  node `t2` was failed, but it has child node `t3`.

    {
      "apiVersion": "argoproj.io/v1alpha1",
      "kind": "Workflow",
      "metadata": {
        "generateName": "test-pipeline-"
      },
      "spec": {
        "arguments": {},
        "entrypoint": "test-pipeline-dag",
        "templates": [
          {
            "dag": {
              "tasks": [
                {
                  "arguments": {},
                  "name": "t1",
                  "template": "succeeded"
                },
                {
                  "arguments": {},
                  "depends": "t1",
                  "name": "t2",
                  "template": "failed"
                },
                {
                  "arguments": {},
                  "depends": "t2 || t2.Failed",
                  "name": "t3",
                  "template": "succeeded"
                },
                {
                  "arguments": {},
                  "depends": "t3",
                  "name": "t4-1",
                  "template": "succeeded"
                },
                {
                  "arguments": {},
                  "depends": "t3",
                  "name": "t4-2",
                  "template": "succeeded"
                },
                {
                  "arguments": {},
                  "depends": "t3",
                  "name": "t4-3",
                  "template": "failed"
                }
              ]
            },
            "inputs": {},
            "metadata": {},
            "name": "test-pipeline-dag",
            "outputs": {}
          },
          {
            "container": {
              "command": [
                "true"
              ],
              "image": "alpine"
            },
            "name": "succeeded"
          },
          {
            "container": {
              "command": [
                "false"
              ],
              "image": "alpine",
              "resources": {}
            },
            "name": "failed"
          }
        ]
      },
      "status": {
        "finishedAt": null,
        "startedAt": null
      }
    }

### CODE REVIEW

File: workflow/util/util.go [hunk 1]
```diff
@@ -848,6 +857,20 @@ func FormulateRetryWorkflow(ctx context.Context, wf *wfv1.Workflow, restartSucce
...
+
+			descendantNodeIDs := getDescendantNodeIDs(wf, node)
+			for _, descendantNodeID := range descendantNodeIDs {
+				deletedNodes[descendantNodeID] = true
+				descendantNode := wf.Status.Nodes[descendantNodeID]
+				if descendantNode.Type == wfv1.NodeTypePod {
+					templateName := getTemplateFromNode(descendantNode)
+					version := GetWorkflowPodNameVersion(wf)
+					podName := PodName(wf.Name, descendantNode.Name, templateName, descendantNode.ID, version)
+					podsToDelete = append(podsToDelete, podName)
```
Comment (terrytangyuan) [inline workflow/util/util.go:871]: I suspect there will be redundant pod names here.

Comment (terrytangyuan) [inline workflow/util/util.go:871]: Can we refactor this? Similar code above

File: workflow/util/util_test.go [hunk 2]
```diff
@@ -920,13 +920,14 @@ func TestFormulateRetryWorkflow(t *testing.T) {
...
+			// node #3 & node #4 are deleted and will be recreated. so only 3 nodes in wf.Status.Nodes
+			if assert.Len(t, wf.Status.Nodes, 3) {
 				assert.Equal(t, wfv1.NodeSucceeded, wf.Status.Nodes["my-nested-dag-1"].Phase)
 				// These should all be running since the child node #3 belongs up to node #1.
 				assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["1"].Phase)
 				assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["2"].Phase)
-				assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["3"].Phase)
-				assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["4"].Phase)
+				//assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["3"].Phase)
+				//assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["4"].Phase)
```
Comment (terrytangyuan) [inline workflow/util/util_test.go:930]: Remove commented code

File: workflow/util/util_test.go [hunk 3]
```diff
@@ -950,14 +951,15 @@ func TestFormulateRetryWorkflow(t *testing.T) {
...
+			// node #4 is deleted and will be recreated. so only 4 nodes in wf.Status.Nodes
+			if assert.Len(t, wf.Status.Nodes, 4) {
 				assert.Equal(t, wfv1.NodeSucceeded, wf.Status.Nodes["my-nested-dag-2"].Phase)
 				// This should be running since it's node #4's parent node.
 				assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["1"].Phase)
 				// This should be running since it's node #1's child node and node #1 is being retried.
 				assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["2"].Phase)
 				assert.Equal(t, wfv1.NodeSucceeded, wf.Status.Nodes["3"].Phase)
-				assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["4"].Phase)
+				//assert.Equal(t, wfv1.NodeRunning, wf.Status.Nodes["4"].Phase)
```
Comment (terrytangyuan) [inline workflow/util/util_test.go:962]: Same here

File: workflow/util/util_test.go [hunk 4]
```diff
@@ -1048,3 +1050,280 @@ func TestGetTemplateFromNode(t *testing.T) {
...
+  annotations:
+    workflows.argoproj.io/pod-name-format: v1
+  creationTimestamp: "2022-08-04T08:35:10Z"
+  generateName: test-pipeline-
+  generation: 10
+  labels:
+    workflows.argoproj.io/completed: "true"
+    workflows.argoproj.io/phase: Failed
+    workflows.argoproj.io/resubmitted-from-workflow: test-pipeline-t5h77
+  managedFields:
```
Comment (terrytangyuan) [inline workflow/util/util_test.go:1067]: Is this needed? Can we make this YAML more concise and only contain what's needed for the test?

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
Thank you for the fix! I left some comments.

File: workflow/util/util.go (hunk 1 above)
Comment (smile-luobin) [reply workflow/util/util.go]: done

Comment (smile-luobin) [reply workflow/util/util.go]: done

File: workflow/util/util_test.go (hunk 2 above)
Comment (smile-luobin) [reply workflow/util/util_test.go]: done

File: workflow/util/util_test.go (hunk 3 above)
Comment (smile-luobin) [reply workflow/util/util_test.go]: done

File: workflow/util/util_test.go (hunk 4 above)
Comment (smile-luobin) [reply workflow/util/util_test.go]: done

**Review by terrytangyuan — APPROVED** [review]
Thank you!
