### PR TITLE
fix: SSO with Jumpcloud "email_verified" field #12257

### LINKED ISSUE #12257: SSO with Jumpcloud "email_verified" causes failure to authenticate
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have tried to setup Jumpcloud as the OIDC provider.
When one sets the email profile in Jumpcloud, the attributes email (dynamic) and email_verified (statically set to true) are added.
Attempting to login in this scenario causes the following error to occur upon callback:
`time="2023-11-24T18:22:44.257Z" level=error msg="failed to get claims from the id token" error="json: cannot unmarshal string into Go struct field claimAlias.email_verified of type bool"
`
Removing email_verified from the list of attributes solves the issue. 
i have tried the following values for email_verified: `1, true, TRUE, True` but they all fail equally. 

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by sonbui00**
Fixes #12257

### Motivation
- Support Jumpcloud

### Modifications
- Support "email_verified" field as string "true" 

### Verification

- Unit test included

### CODE REVIEW

**Review by sarabala1979 — APPROVED** [review]

File: server/auth/types/claims.go [hunk 1]
```diff
@@ -12,7 +12,7 @@ type Claims struct {
 	jwt.Claims
 	Groups                  []string               `json:"groups,omitempty"`
 	Email                   string                 `json:"email,omitempty"`
-	EmailVerified           bool                   `json:"email_verified,omitempty"`
+	EmailVerified           bool                   `json:"-"`
```
Comment (agilgur5) [inline server/auth/types/claims.go:15]: Hmm I'm thinking the more correct way of handling this would have been to use a custom type like in [this SO question's answers](https://stackoverflow.com/q/30856454/3431180)
