### PR TITLE
fix: retry forevever on task result creation related transient errors. Fixes #14560

### LINKED ISSUE #14560: task result creation should retry forever on transient errors.
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Currently transient errors do not retry, it has a cap of a max of 5 retries then gives up and reports container failure. 
This is not ideal, nor does it make sense. The task results are a must and we will spin the controller forever waiting for them if they do not arrive. This happens when this issue is  combined with say a podGC policy of OnSuccess. 

### Version(s)

:latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by isubasinghe**
Fixes #14560

### Motivation

Currently the task result creation is only attempted 5 times when transient errors occur, this doensn't make any sense since we are relient on them to progress the state of the workflow. This change ensure that we retry effectively always when transient errors happen.

### Modifications
Modify the number of steps from 5 to the maximum int32 value.

### Verification

None performed since this only modifies the parameters passed.

### Documentation

Not documented .

### CODE REVIEW

File: workflow/executor/executor.go [hunk 1]
```diff
@@ -858,18 +859,33 @@ func (we *WorkflowExecutor) ReportOutputsLogs(ctx context.Context) error {
...
-		Steps:    5,
+		Factor:   2.0,
+		Jitter:   0.2,
+		Steps:    math.MaxInt32, // effectively infinite retries
 		Cap:      30 * time.Second,
 	}, errorsutil.IsTransientErr, func() error {
 		err := we.upsertTaskResult(ctx, result)
-		if apierr.IsForbidden(err) {
+		if apierr.IsForbidden(err) && shouldLogRetry(count) {
 			log.WithError(err).Warn("failed to patch task result, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/")
```
Comment (Joibel) [inline workflow/executor/executor.go]: Log a count here?

**Comment by jswxstw** [comment]
Some conflict errors are being ignored in `errorsutil.IsTransientErr`.

I think `isResourceQuotaConflictErr(err)` should be replaced with `apierr.IsConflict(err)`.

https://github.com/argoproj/argo-workflows/blob/2104eda0351cd67ed01d1e02544fea4b08d519f5/util/errors/errors.go#L52

File: workflow/executor/executor.go [hunk 2]
```diff
@@ -858,18 +859,33 @@ func (we *WorkflowExecutor) ReportOutputsLogs(ctx context.Context) error {
...
-		Jitter:   0.1,
-		Steps:    5,
+		Factor:   2.0,
+		Jitter:   0.2,
+		Steps:    math.MaxInt32, // effectively infinite retries
 		Cap:      30 * time.Second,
 	}, errorsutil.IsTransientErr, func() error {
 		err := we.upsertTaskResult(ctx, result)
-		if apierr.IsForbidden(err) {
+		if apierr.IsForbidden(err) && shouldLogRetry(count) {
```
Comment (jswxstw) [inline workflow/executor/executor.go]: `shouldLogRetry` here will not take any effect because `apierr.IsForbidden(err)` is not transient error.

**Comment by isubasinghe** [comment]
@jswxstw I think lets address that in a different PR to keep the PR atomic, and also just to get this one merged in fast (this is mostly why)

File: workflow/executor/executor.go (hunk 1 above)
Comment (isubasinghe) [reply workflow/executor/executor.go]: Sure

**Comment by jswxstw** [comment]
Sure, I will submit a new PR to fix my issue.

File: workflow/executor/executor.go (hunk 2 above)
Comment (isubasinghe) [reply workflow/executor/executor.go]: You are correct, thanks changing it now. I am surprised there is no logging of failed transient errors in that case.

File: workflow/executor/executor.go [hunk 3]
```diff
@@ -858,18 +859,35 @@ func (we *WorkflowExecutor) ReportOutputsLogs(ctx context.Context) error {
 	return we.reportResult(ctx, wfv1.NodeResult{Outputs: &outputs})
 }
 
+func shouldLogRetry(attempt uint64) bool {
```
Comment (jswxstw) [inline workflow/executor/executor.go]: I think `shouldLogRetry` is unnecessary,  because backoff is already configured during retries.

Comment (isubasinghe) [reply workflow/executor/executor.go]: I disagree, the delay between logs at its worse case will be 30 seconds. As time goes on, `shouldLogRetry` basically makes sure we place less emphasis on this container in the logs (since it is likely the user probably noticed it and likely doesn't care, this is my hypothesis anyway).

Comment (Joibel) [reply workflow/executor/executor.go]: I'm inclined to agree with @jswxstw here. This container is dying, and nothing else should be happening, this is just unnecessary complexity.

**Review by Joibel — APPROVED** [review]
Approving anyway, but think we can lose the logging complexity.
