### PR TITLE
fix: Reduce agent permissions. Fixes #7986

### LINKED ISSUE #7986: Reduce agent permissions
# Summary

The agent should not be able to update the task set, only patch its status. This means the agent cannot add work to the workflow. 

This got overlooking in the implementation and code review.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>

Fixes #7986

Removing `pod patch` is not as useful, if the attacker can still create work using the task-set. This fixes that.

### CODE REVIEW

**Comment by alexec** [comment]
@jessesuen can I get your rubber-stamp approval of the proto change? It is only adding status sub-resource

File: workflow/executor/agent.go [hunk 1]
```diff
@@ -176,7 +176,7 @@ func (ae *AgentExecutor) patchWorker(ctx context.Context, taskSetInterface v1alp
 
 			ae.log.Info("Processing Patch")
 
-			_, err = taskSetInterface.Patch(ctx, ae.WorkflowName, types.MergePatchType, patch, metav1.PatchOptions{})
+			_, err = taskSetInterface.Patch(ctx, ae.WorkflowName, types.MergePatchType, patch, metav1.PatchOptions{}, "status")
```
Comment (alexec) [inline workflow/executor/agent.go:179]: this can be made a non-breaking change by trying to patch "status" first, if 403 error, try and patch resource instead (print warning about permissions)

**Review by sarabala1979 — APPROVED** [review]
LGTM
