### PR TITLE
fix: prevent `failed to get a template` when using inline template. Fixes #15051

### LINKED ISSUE #15051: workflow fails with `failed to get a template` when using inline template and `retryStrategy`
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

The workflows below fail with message `failed to get a template`, from version 3.7.0 onwards.
It works well with versions 3.5.5 to 3.6.13.

### Version(s)

v3.7.0, v3.7.2, v3.7.4, 753c067cc0ffc8381a70bfa6e33ffd5481000b5f

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-inline-
spec:
  entrypoint: main
  retryStrategy:
    retryPolicy: OnTransientError
    limit: 1
  templates:
    - name: main
      dag:
        tasks:
          - name: hello
            inline:
              script:
                image: python:alpine
                command: [python]
                source: |
                  print("hello")
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-inline-
spec:
  entrypoint: main
  retryStrategy:
    retryPolicy: OnTransientError
    limit: 1
  templates:
    - name: main
      steps:
        - - name: hello
            inline:
              script:
                image: python:alpine
                command: [python]
                source: |
                  print("hello")
```

### Logs from the workflow controller

```text
time="2025-11-14T13:33:16.657Z" level=info msg="Processing workflow" Phase= ResourceVersion=19371 namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.658Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.658Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.658Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.658Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.658Z" level=info msg="Retry node dag-inline-fwtp7 initialized Running" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.658Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.658Z" level=info msg="DAG node dag-inline-fwtp7-1134409721 initialized Running" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.658Z" level=warning msg="was unable to obtain the node for dag-inline-fwtp7-2325674491, taskName hello"
time="2025-11-14T13:33:16.658Z" level=warning msg="was unable to obtain the node for dag-inline-fwtp7-2325674491, taskName hello"
time="2025-11-14T13:33:16.659Z" level=warning msg="was unable to obtain the node for dag-inline-fwtp7-2325674491, taskName hello"
time="2025-11-14T13:33:16.659Z" level=info msg="All of node dag-inline-fwtp7(0).hello dependencies [] completed" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=info msg="Retry node dag-inline-fwtp7-2325674491 initialized Running" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=info msg="Pod node dag-inline-fwtp7-162281334 initialized Pending" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=error msg="Mark error node" error="failed to get a template" namespace=argo nodeName="dag-inline-fwtp7(0).hello(0)" workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=info msg="node dag-inline-fwtp7-162281334 phase Pending -> Error" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=info msg="node dag-inline-fwtp7-162281334 message: failed to get a template" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=info msg="node dag-inline-fwtp7-162281334 finished: 2025-11-14 13:33:16.659877673 +0000 UTC" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=info msg="Retry Policy: OnTransientError (onFailed: false, onError false)" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.659Z" level=info msg="Node not set to be retried after status: Error" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="node dag-inline-fwtp7-2325674491 phase Running -> Error" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="node dag-inline-fwtp7-2325674491 message: failed to get a template" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="node dag-inline-fwtp7-2325674491 finished: 2025-11-14 13:33:16.660025714 +0000 UTC" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="Outbound nodes of dag-inline-fwtp7-1134409721 set to [dag-inline-fwtp7-162281334]" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="node dag-inline-fwtp7-1134409721 phase Running -> Error" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="node dag-inline-fwtp7-1134409721 finished: 2025-11-14 13:33:16.660116423 +0000 UTC" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="Retry Policy: OnTransientError (onFailed: false, onError false)" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="Node not set to be retried after status: Error" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="node dag-inline-fwtp7 phase Running -> Error" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="node dag-inline-fwtp7 finished: 2025-11-14 13:33:16.660289923 +0000 UTC" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg=reconcileAgentPod namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.660Z" level=info msg="Marking workflow completed" namespace=argo workflow=dag-inline-fwtp7
time="2025-11-14T13:33:16.663Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=19373 workflow=dag-inline-fwtp7
```

### Logs from in your workflow's wait container

```text
The pods are not created.
```

### PR DESCRIPTION
**Pull request by MasonM**
Fixes #15051

### Motivation

https://github.com/argoproj/argo-workflows/pull/14576 introduced a bug where retries fail with the error `failed to get a template` when submitting a workflow using an inline template, e.g.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-inline-
spec:
  entrypoint: main
  retryStrategy:
    retryPolicy: OnTransientError
    limit: 1
  templates:
    - name: main
      steps:
        - - name: hello
            inline:
              script:
                image: python:alpine
                command: [python]
                source: |
                  print("hello")
```

### Modifications

This is basically the same bug that was fixed in https://github.com/argoproj/argo-workflows/pull/12683. I mostly reverted the logic for `FindRetryNode()` back to the version before https://github.com/argoproj/argo-workflows/pull/14576, except with a check to skip any node that doesn't have either `templateName` or `templateRef`. I'm not 100% sure this is correct, so I added two integration tests to `workflow/controller/operator_test.go` to cover this.

### Verification

Tested manually by submitting the above workflow using the UI:
image

### Documentation

N/A

### CODE REVIEW

File: workflow/controller/retry_tweak.go [hunk 1]
```diff
@@ -13,12 +13,17 @@ type RetryTweak = func(retryStrategy wfv1.RetryStrategy, nodes wfv1.Nodes, pod *
...
 func FindRetryNode(nodes wfv1.Nodes, nodeID string) *wfv1.NodeStatus {
-	if parentNode := nodes.FindByChild(nodeID); parentNode != nil && parentNode.Type == wfv1.NodeTypeRetry {
-		return parentNode
-	}
 	boundaryID := nodes[nodeID].BoundaryID
-	if parentNode := nodes.FindByChild(boundaryID); parentNode != nil && parentNode.Type == wfv1.NodeTypeRetry {
-		return parentNode
+	boundaryNode := nodes[boundaryID]
+	for _, node := range nodes {
+		if node.Type != wfv1.NodeTypeRetry || (node.TemplateName == "" && node.TemplateRef == nil) {
```
Comment (jswxstw) [inline workflow/controller/retry_tweak.go]: This filter condition excludes inline template nodes, causing `FindRetryNode` to find the wrong closest retry node ancestor for the nodeID.

File: workflow/controller/retry_tweak_test.go [hunk 2]
```diff
@@ -15,14 +15,14 @@ func TestFindRetryNode(t *testing.T) {
...
-			Children:     []string{"B1", "B2", "B3"},
+			Children:     []string{"B1", "B2"},
 			TemplateName: "tmpl1",
 		},
 		"B1": wfv1.NodeStatus{
 			ID:           "B1",
 			Type:         wfv1.NodeTypeSkipped,
 			Phase:        wfv1.NodeSkipped,
-			BoundaryID:   "A1",
+			BoundaryID:   "",
```
Comment (jswxstw) [inline workflow/controller/retry_tweak_test.go]: `BoundaryID` is not empty if its ancestor node is `Steps`, this is the reason why the earlier unit tests didn’t cover #14517.

**Review by jswxstw — COMMENTED** [review]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-inline-
spec:
  entrypoint: main
  templates:
    - name: main
      retryStrategy:
        retryPolicy: OnTransientError
        limit: 1
      steps:
        - - name: hello
            inline:
              retryStrategy:
                limit: "2"
                affinity:
                  nodeAntiAffinity: {}
              script:
                image: python:alpine
                command: [python]
                source: |
                  exit(1)
```

Considering the above scenario, the current fix filters out inline template nodes, causing `FindRetryNode` to find the wrong closest retry node ancestor, which leads to selecting an incorrect `retryStrategy` and subsequently introduces #14517.

```shell
# argo get steps-inline-c6dpq               
Name:                steps-inline-c6dpq
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed
Message:             child 'steps-inline-c6dpq-3826336146' failed
Conditions:          
 PodRunning          False
 Completed           True
Created:             Thu Feb 26 11:15:14 +0800 (1 minute ago)
Started:             Thu Feb 26 11:15:14 +0800 (1 minute ago)
Finished:            Thu Feb 26 11:15:33 +0800 (1 minute ago)
Duration:            19 seconds
Progress:            0/3
ResourcesDuration:   0s*(1 cpu),6s*(100Mi memory)

STEP                      TEMPLATE  PODNAME                        DURATION  MESSAGE
 ✖ steps-inline-c6dpq(0)  main                                               child 'steps-inline-c6dpq-3826336146' failed  
 └───✖ hello                                                                 No more retries left                          
     ├─✖ hello(0)                   steps-inline-c6dpq-882272905   4s        main: Error (exit code 1)                     
     ├─✖ hello(1)                   steps-inline-c6dpq-412646668   3s        main: Error (exit code 1)                     
     └─✖ hello(2)                   steps-inline-c6dpq-3096521255  3s        main: Error (exit code 1)
```

**Comment by jswxstw** [comment]
### Root Cause

`scheduleOnDifferentHost` unconditionally calls `ResolveTemplate(ctx, retryNode)` to recover the template for the retry node. This works for named templates and `templateRef`, but **fails for inline templates** because:

- Inline template nodes have empty `TemplateName` and nil `TemplateRef` (only `Inline` is set on the step/task)
- `NodeStatus.GetTemplate()` always returns nil (it doesn't store inline content)
- So `ResolveTemplate` falls through all three lookups and hits `"failed to get a template"`

The error then bubbles up from `scheduleOnDifferentHost` → `createWorkflowPod`, blocking Pod creation entirely.

### Proposed Fix

Pass the already-resolved `tmpl` into `scheduleOnDifferentHost`, and only call `ResolveTemplate` when the retry node actually has a `TemplateName` or `TemplateRef`. For inline templates (both are zero-value), just use the passed-in template directly:

```diff
-func (woc *wfOperationCtx) scheduleOnDifferentHost(ctx context.Context, node *wfv1.NodeStatus, pod *apiv1.Pod) error {
+func (woc *wfOperationCtx) scheduleOnDifferentHost(ctx context.Context, node *wfv1.NodeStatus, tmpl *wfv1.Template, pod *apiv1.Pod) error {
     if node != nil && pod != nil {
         if retryNode := FindRetryNode(woc.wf.Status.Nodes, node.ID); retryNode != nil {
-            scope, name := retryNode.GetTemplateScope()
-            tmplCtx, err := woc.createTemplateContext(ctx, scope, name)
-            ...
-            _, retryTmpl, _, err := tmplCtx.ResolveTemplate(ctx, retryNode)
-            ...
+            retryTmpl := tmpl
+            if retryNode.TemplateName != "" || retryNode.TemplateRef != nil {
+                scope, name := retryNode.GetTemplateScope()
+                tmplCtx, err := woc.createTemplateContext(ctx, scope, name)
+                ...
+                _, resolvedTmpl, _, err := tmplCtx.ResolveTemplate(ctx, retryNode)
+                ...
+                retryTmpl = resolvedTmpl
+            }
             if retryStrategy := woc.retryStrategy(retryTmpl); retryStrategy != nil {
                 RetryOnDifferentHost(retryNode.ID)(*retryStrategy, woc.wf.Status.Nodes, pod)
             }
```

This is safe — `tmpl` at this call site in `createWorkflowPod` is already fully resolved (including `retryStrategy`), and for named/templateRef nodes the behavior is unchanged.

| Scenario | Before | After |
|----------|--------|-------|
| Named template + retryStrategy | ✅ | ✅ (unchanged) |
| TemplateRef + retryStrategy | ✅ | ✅ (unchanged) |
| **Inline template + retryStrategy** | ❌ `failed to get a template` | ✅ uses passed-in tmpl |

### Note on inline steps/dag + template-level retryStrategy

One edge case worth mentioning: if an inline template is itself a `steps`/`dag` (not a leaf), and `retryStrategy` with `nodeAntiAffinity` is defined **on that inline template** (not workflow-level), then:

- The retry node wraps the inline steps/dag, but `createWorkflowPod` is called for the **leaf Pod node** inside it
- The `tmpl` passed in is the leaf template, which doesn't carry the outer inline template's `retryStrategy`
- `woc.retryStrategy(tmpl)` falls back to `woc.execWf.Spec.RetryStrategy` — if that's nil too, `nodeAntiAffinity` won't take effect

**Comment by MasonM** [comment]
@jswxstw Thanks for the review, and sorry for the delay. I incorporated your suggestion and updated the tests. 

Also, I spent awhile trying to figure out why the example workflow intermittently succeeds. I think the problem is that `FindByChild()` is non-deterministic, because it assumes every node has a single parent, which isn't always the case (e.g. https://github.com/argoproj/argo-workflows/blob/main/examples/dag-diamond.yaml). I renamed that method to `FindRetryNodeByChild()` and had it only return a node if it's a retry node, which should hopefully solve that.

**Review by jswxstw — APPROVED** [review]
LGTM

**Comment by isubasinghe** [comment]
I think I hate inline templates.

**Review by isubasinghe — CHANGES_REQUESTED** [review]
I think the best fix for this is to ban inline templates 😄.

But composite inline templates will not work here I think. 
See:
```yaml
apiVersion: argoproj.io/v1alpha1
  kind: Workflow
  metadata:
    generateName: inline-composite-retry-
  spec:
    entrypoint: main
    templates:
      - name: main
        steps:
        - - name: step1
            inline:
              retryStrategy:
                limit: "1"
                affinity:
                  nodeAntiAffinity: {}
              steps:
              - - name: fail
                  template: fail
      - name: fail
        container:
          image: alpine:latest
          command: [sh, -c]
          args: ["exit 1"]
```

**Comment by MasonM** [comment]
@isubasinghe Thanks! You're right that's broken, but that's an existing bug that's not related to https://github.com/argoproj/argo-workflows/issues/15051, since it still breaks if you remove the `retryStrategy` section. In any case, I went ahead and fixed that one too and added a test case.

**Review by isubasinghe — APPROVED** [review]
