### PR TITLE
fix: Allow setting workflow input parameters in UI. Fixes #4234

### LINKED ISSUE #4234: Allow setting workflow *input* parameters in UI
# Summary

The user should be given the chance to set input parameters in the UI when submitting a workflow from a template.

The work done in https://github.com/argoproj/argo/issues/3498 is great, but it only works when (default?) values for the parameters have been set in arguments.parameters.

Instead I suggest both the list of inputs.parameters and arguments.parameters should be considered when presenting a list of parameters to the user.

# Use Cases

I have several workflow templates configured that take required parameters. I frequently submit these via the UI.

In version 2.10.0 I was able to paste in some arguments.parameters with values in the yaml and submit the workflow.

In version 2.9.0 I could do the same, but without values and specify the values in the UI.

As if 2.11.0 I'm unable to submit these workflow via the UI without adding arguments.parameters with default values to the workflowtemplate.spec:

image

Shows as no parameters:

image

This appears to be the line in question:
https://github.com/alexec/argo/blob/d26ede0b6d132d5f8ddb40f6eabd97d53a182a74/ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx#L91

Instead of referencing this.state.template.spec.arguments.parameters I think it should get the inputs.parameters from whichever template/entrypoint is selected in the dropdown, possibly referencing arguments.parameters (of the same template/entrypoint?) to fill in some default values if they're specified.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kennytrytek**
Signed-off-by: Kenny Trytek <kenneth.g.trytek@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).
I am committing on my own time.

Local testing showing this fix in action:

<details><summary>Using this WorkflowTemplate</summary>
<p>

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: whalesay-test
spec:
  entrypoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: hello
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message-param-1
      container:
        image: argoproj/argosay:v2
        args: ["echo", "{{inputs.parameters.message-param-1}}"]
        imagePullPolicy: IfNotPresent
    - name: whalesay-template-two
      inputs:
        parameters:
          - name: message-two
      container:
        image: argoproj/argosay:v2
        args: ["echo", "{{inputs.parameters.message-two}}"]
        imagePullPolicy: IfNotPresent
```

</p>
</details>

submit-wf-template

### CODE REVIEW

**Review by alexec — COMMENTED** [review]
this seems not quite there yet to me, it should not matter which entrypoint you have, the parameters should always be `spec.arguments.parameters`

**Comment by kennytrytek** [comment]
> @alexec 
> this seems not quite there yet to me, it should not matter which entrypoint you have, the parameters should always be `spec.arguments.parameters`

Looking at the example template in the PR description:
Workflow input parameter: `message`
whalesay-template parameter: `message-param-1`
whalesay-template-two parameter: `message-two`

The existing UI is unable to submit the workflow at all because the parameters for whalesay-template and whalesay-template-two do not have default values. How would those values get populated in the workflow submission if they cannot be set in the UI?

**Comment by alexec** [comment]
Can we break this into 2 PRs?

* One to allow you to choose entrypoint.
* Another where we can discus the arguments.

**Comment by kennytrytek** [comment]
@alexec, the current UI already allows you to choose an entrypoint, so I don't think there's anything to do for your first bullet point suggestion. This PR should fit the bill for the second bullet point though.

**Review by alexec — CHANGES_REQUESTED** [review]
I still can't get my head around this. Can I please ask you to attach an example of a workflow template that this would impact?

**Comment by kennytrytek** [comment]
@alexc, please see the pull request description for an example workflow template and a GIF showing the UI behavior. The original issue has a GIF showing the current UI behavior for that template.

**Comment by kennytrytek** [comment]
@alexc, please see the pull request description for an example workflow template and a GIF showing the new UI behavior. The original issue has a GIF showing the current UI behavior for that template.

File: ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx [hunk 1]
```diff
@@ -129,8 +129,7 @@ export const ClusterWorkflowTemplateDetails = ({history, location, match}: Route
                         namespace={namespace}
                         name={template.metadata.name}
                         entrypoint={template.spec.entrypoint}
-                        entrypoints={(template.spec.templates || []).map(t => t.name)}
-                        parameters={template.spec.arguments.parameters || []}
```
Comment (alexec) [inline ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx:133]: I think we still need these - otherwise how do you submit the workflow template specifying the spec arguments?

Comment (alexec) [inline ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx:133]: I think we still need these - otherwise how do you submit the workflow template specifying the spec arguments?

**Comment by alexec** [comment]
@kennytrytek I think we want this PR, but I don't want to lose the ability to set the `spec.arguments`. Could I please ask you to support both?

**Comment by kennytrytek** [comment]
Yes, sorry I've been slow on this; I was prioritizing the WorkflowNodeRunning PR ahead of this one. I understand what you're saying; we need to be able to handle the case where there are workflow input parameters, and not just entrypoint parameters.

My current thought is to add an empty option like `<none>` in the entrypoint selector, using the workflow input parameters for that case.

**Comment by alexec** [comment]
that sounds good to me

**Comment by alexec** [comment]
in the future -  I'd like to add the ability to resubmit a workflow with different parameters

**Comment by kennytrytek** [comment]
Sorry for the slow updates on this one. I tested it with some templates from the examples folder, and it appears to do what I would expect; either entrypoint or workflow parameters can be used.

**Review by alexec — APPROVED** [review]
