### PR TITLE
fix: allow wf templates without parameter values (Fixes #6044)

### LINKED ISSUE #6044: "argo template lint" errors on missing arguments
Here's what happens:

```sh
$ argo template lint ./k8s/environments/staging/wftmpl-webhooks.yaml
./k8s/environments/staging/wftmpl-webhooks.yaml:
   ✖ in "webhooks" (WorkflowTemplate): spec.arguments.commit.value is required
```

My workflow template starts with this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: webhooks
spec:
  arguments:
    parameters:
    - name: commit
```

First of all, there's no flag to pass parameters to the linter to make it pass.

Second of all, how does that error make any sense? The arguments to the template doesn't matter to linting. Those arguments can be anything at runtime, so they cannot possibly be linted.

Is `argo template lint` intended for some other use case than linting workflow templates?

```sh
$ argo version
argo: v3.0.7+e79e7cc.dirty
  BuildDate: 2021-05-26T00:43:44Z
  GitCommit: e79e7ccda747fa4487bf889142c744457c26e9f7
  GitTreeState: dirty
  GitTag: v3.0.7
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kennytrytek**
This change allows linting and creation of workflow templates without requiring parameter values. As best as I can determine, this fixes a regression of previous behavior.

------

### Testing
Unit tests were added to prove the behavior shown below.

Using this workflow example from the issue, I can lint and create a template without specified parameter values.
```a.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-parameters
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{workflow.parameters.message}}" ] 
```

Lint:
```
$ ~/git/argo-workflows/dist/argo lint ./a.yaml 
✔ no linting errors found!
```

Create:
```
$ ~/git/argo-workflows/dist/argo template create ./a.yaml 
Name:                hello-world-parameters
Namespace:           argo
Created:             Mon Nov 01 19:47:28 -0500 (now)
```

Submitting without providing parameters does not work (as expected):
```
$ ~/git/argo-workflows/dist/argo submit --from workflowtemplate/hello-world-parameters
FATA[2021-11-01T19:48:55.857Z] Failed to submit workflow: spec.arguments.message.value is required 
```

If parameters are provided, it succeeds:
```
$ ~/git/argo-workflows/dist/argo submit --from workflowtemplate/hello-world-parameters -p 'message=hi'
Name:                hello-world-parameters-xqhhm
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Mon Nov 01 19:49:33 -0500 (now)
Progress:            
Parameters:          
  message:           hi
```

Signed-off-by: Kenny Trytek <kenneth.g.trytek@gmail.com>

### CODE REVIEW

**Comment by kennytrytek** [comment]
CI/Lint looks to be very flaky. Closing/reopening to rerun.

**Comment by kennytrytek** [comment]
Got the lint error resolved. This is ready for review.

File: workflow/validate/validate_test.go [hunk 1]
```diff
@@ -2733,17 +2733,29 @@ spec:
...
+	err = validateWorkflowTemplate(workflowTemplateWithEmptyEnumList, ValidateOpts{Submit: true})
 	assert.EqualError(t, err, "spec.arguments.message.enum should contain at least one value")
 }
 
 func TestWorkflowTemplateWithArgumentValueNotFromEnumList(t *testing.T) {
-	err := validateWorkflowTemplate(workflowTemplateWithArgumentValueNotFromEnumList)
+	err := validateWorkflowTemplate(workflowTemplateWithArgumentValueNotFromEnumList, ValidateOpts{})
+	assert.NoError(t, err)
+	err = validateWorkflowTemplate(workflowTemplateWithArgumentValueNotFromEnumList, ValidateOpts{Lint: true})
+	assert.NoError(t, err)
```
Comment (tczhao) [inline workflow/validate/validate_test.go:2757]: I think linting should report error if value is not from the enum list

because when submitting using wfTemplate from UI,
the parameter field will default to the specified value,
This will cause an extra burden for user, they need to go through an extra steps to select the correct value from dropdown list

**Comment by terrytangyuan** [comment]
@sarabala1979 It would be good if you could review this one as you have another PR https://github.com/argoproj/argo-workflows/pull/7161 that's trying to fix the same issue.

File: workflow/validate/validate.go [hunk 2]
```diff
@@ -149,9 +154,11 @@ func ValidateWorkflow(wftmplGetter templateresolution.WorkflowTemplateNamespaced
 	if err != nil {
 		return nil, errors.Errorf(errors.CodeBadRequest, "spec.templates%s", err.Error())
 	}
-	if ctx.Lint {
-		// if we are just linting we don't care if spec.arguments.parameters.XXX doesn't have an
-		// explicit value. workflows without a default value is a desired use case
+
+	if ctx.Lint || (ctx.WorkflowTemplateValidation && !ctx.Submit) {
```
Comment (sarabala1979) [inline workflow/validate/validate.go:158]: @tczhao are you expecting `ctx.WorkflowTemplateValidation` options in the workflow submission scenario?

File: workflow/validate/validate_test.go (hunk 1 above)
Comment (kennytrytek) [reply workflow/validate/validate_test.go:2757]: Yes, I agree that behavior sounds better. I shied away from doing that initially because it started to get complicated, but maybe it's worth a second look.

Comment (kennytrytek) [reply workflow/validate/validate_test.go]: Updated to always validate enum values and artifact usage in https://github.com/argoproj/argo-workflows/pull/7124/commits/81612aec3af70c87661e33832ecd30d3084d405c.

**Comment by kennytrytek** [comment]
Retested on latest commit. ✅ 

Lint fails with current Argo:
```
$ argo template lint ./a.yaml
ERRO[2021-11-08T18:23:01.113Z] spec.arguments.message.value is required     
FATA[2021-11-08T18:23:01.113Z] Errors encountered in validation  
```

Lint succeeds with these changes:
```
$ ~/git/argo-workflows/dist/argo template lint ./a.yaml 
✔ no linting errors found!
```

Create:
```
$ ~/git/argo-workflows/dist/argo template create ./a.yaml 
Name:                hello-world-parameters
Namespace:           argo
Created:             Mon Nov 08 18:24:41 -0600 (now)
```

Submitting without providing parameters does not work (as expected):
```
$ ~/git/argo-workflows/dist/argo submit --from workflowtemplate/hello-world-parameters
FATA[2021-11-08T18:25:25.301Z] Failed to submit workflow: spec.arguments.message.value is required 
```

If parameters are provided, it succeeds:
```
$ ~/git/argo-workflows/dist/argo submit --from workflowtemplate/hello-world-parameters -p 'message=hi'
Name:                hello-world-parameters-n5tqk
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Mon Nov 08 18:26:02 -0600 (now)
Progress:            
Parameters:          
  message:           hi
```

File: workflow/validate/validate.go (hunk 2 above)
Comment (kennytrytek) [reply workflow/validate/validate.go]: I do not believe `ctx.WorkflowTemplateValidation` will ever be `true` in a workflow submission scenario because only a `Workflow` can be submitted, not a `WorkflowTemplate`. The purpose of `(ctx.WorkflowTemplateValidation && !ctx.Submit)` is to use more permissive validation for the `Create` workflow template action and the more restrictive validation for workflow submission (if we are not linting).

Comment (kennytrytek) [reply workflow/validate/validate.go]: This line was refactored in https://github.com/argoproj/argo-workflows/commit/81612aec3af70c87661e33832ecd30d3084d405c.

**Review by sarabala1979 — APPROVED** [review]
