### PR TITLE
fix: Add pod name format annotation. Fixes #6962 and #6989

### LINKED ISSUE #6962: Log viewing problem in UI due pod name changes
## Summary

https://github.com/argoproj/argo-workflows/pull/6712
introduce POD_NAMES Whether to have pod names contain the template name (v2) or be the node id (v1).

https://github.com/argoproj/argo-workflows/pull/6925
forces all podname on UI to align with v2,

These introduce problems:

- by setting POD_NAMES to v2 on workflow-controller

all the historical archived workflow logs won't be viewable in UI because they are stored without the template name

- by setting POD_NAMES to v1 on workflow-controller

all the new workflow/archived workflows logs won't be viewable in UI because they are stored without the template name

What version of Argo Workflows are you running?
master: https://github.com/argoproj/argo-workflows/commit/cf9a6cdd098901873ac584db649b694041530eb2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by JPZ13**
Signed-off-by: J.P. Zivalich <jp@pipekit.io>

This PR:
- Adds the pod name version as an annotation to a workflow
- Displays ui logs for a given workflow based on the annotation
- Adds a function to get a template name from a template ref

Fixes #6962 and #6989

### CODE REVIEW

**Comment by JPZ13** [comment]
@tczhao I validated that the default v2 logs are showing up properly. I have some other obligations to attend to this evening and can't validate the v1 path until tomorrow. In the meantime, are you free to review?

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -263,6 +264,8 @@ func (woc *wfOperationCtx) operate(ctx context.Context) {
 
 	if woc.wf.Status.Phase == wfv1.WorkflowUnknown {
 		woc.markWorkflowRunning(ctx)
+		setWfPodNamesAnnotation(woc.wf)
```
Comment (agilgur5) [inline workflow/controller/operator.go:267]: apparently there's a small bug here since line 238 above wasn't updated with this. See https://github.com/argoproj/argo-workflows/issues/10178#issuecomment-2068596407

Working on a fix for that

File: ui/src/app/shared/pod-name.ts [hunk 2]
```diff
@@ -1,8 +1,24 @@
...
+        if (workflowName === nodeName) {
+            return workflowName;
+        }
+
+        const prefix = ensurePodNamePrefixLength(`${workflowName}-${templateName}`);
+
+        const hash = createFNVHash(nodeName);
+        return `${prefix}-${hash}`;
+    }
+
```
Comment (agilgur5) [inline ui/src/app/shared/pod-name.ts:21]: huh this looks like the logic in `workflow/util/pod_name.go` _before_ this PR. this PR changed that file a bit to invert the conditionals, but it's also slightly semantically different.

noticed this was divergent in https://github.com/argoproj/argo-workflows/pull/12928#issuecomment-2068605536, working on fixing this

Comment (agilgur5) [reply ui/src/app/shared/pod-name.ts:21]: Resolved in #12964

File: workflow/controller/operator.go (hunk 1 above)
Comment (agilgur5) [reply workflow/controller/operator.go:267]: Fixed in #12965
