### PR TITLE
fix: respect `workflowDefaults` when validating workflows. Fixes #10946. Fixes #11465

### LINKED ISSUE #10946: `workflowMetadata` set in `workflowDefaults` doesn't work for `WorkflowTemplate`
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I set default key-value pair in labels of workflowMetadata in workflowDefaults like the following:
image
Then, I tried to use workflow.labels directly in workflowtemplate and submitted it. It cause error:
```
time="2023-04-20T15:56:10.021Z" level=fatal msg="Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.whalesay-template: failed to resolve {{workflow.labels.arg-name}}
```

It seems that workflow submitted by workflowtemplate cannot get the default workflowMetadata or metadata in workflowDefaults.

How can I make workflow.labels in workflowtemplate get default value?

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  entrypoint: whalesay-template
  templates:
    - name: whalesay-template
      container:
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{workflow.labels.arg-name}}'
```

### Logs from the workflow controller

```text
no
```

### Logs from in your workflow's wait container

```text
no
```

### LINKED ISSUE #11465: `failed to resolve {{workflow.annotations.xxx}}` when annotations are defined in `workflowDefaults`
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

## The issue
- you define an annotation in the workflow-controller-configmap section `workflowDefaults`
- you make a reference to this annotation in the workflow at any place with `{{workflow.annotations.xxx}}` where xxx is the name annotation
- when trying to submit the workflowTemplate argo refuses it with the error:
`ERROR - Workflow <workflow.yaml>: templates.exit.steps failed to resolve {{workflow.annotations.xxx}}`

This is really annoying because I wanted to use annotations to get some behavior in the exit-handler.
I will use something else, but I think it should be supported.

## Expected behavior
labels and annotations can be dynamic by definition, this should raise a warning but not an error.

### Version

v3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
---
# In the workflow-controller-configmap
  workflowDefaults: |
    metadata:
      annotations:
        xxx: hello test
---
# The workflow
metadata:
  name: delightful-tiger
  labels:
    example: 'true'
spec:
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.annotations.xxx}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
```

### Logs from the UI or argo-server

```text
Bad Request: templates.argosay: failed to resolve {{workflow.annotations.xxx}}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by MasonM**
Fixes #10946 and Fixes #11465

### Motivation

Submitting a workflow with a variable reference that points to a label or annotation that comes from `workflowDefaults` will always fail with an error like the following:
```
msg="Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.whalesay-template: failed to resolve {{workflow.labels.arg-name}}
```

### Modifications

This error is happening here: https://github.com/argoproj/argo-workflows/blob/2dac1266b446d059ac6df78afe3d09a6ddb3af4b/workflow/validate/validate.go#L705

The `scope` argument comes from `ValidateWorkflow()`, which isn't aware of `workflowDefaults`, and therefore doesn't include any labels/annotations defined therein. This is purely a validation issue, since `workflowDefaults` is merged into the workflow at runtime by
https://github.com/argoproj/argo-workflows/blob/2dac1266b446d059ac6df78afe3d09a6ddb3af4b/workflow/controller/controller.go#L1375

This updates `ValidateWorkflow()` to take in the `workflowDefaults` (if any) and use that to populate the context with any labels/annotations, which is ultimately used to populate the `scope` argument.  Most of the changes in this PR is just passing around the `workflowDefaults` so that it can ultimately get passed to `ValidateWorkflow()`.

### Verification

I opted to modify the existing `TestSubmitWorkflowTemplateWorkflowMetadataSubstitution` E2E test to verify this is working. I could've added a new test, but considering how slow the CI pipeline already is, that seems suboptimal.
```
$ make TestSubmitWorkflowTemplateWorkflowMetadataSubstitution
<SNIP>
Checking expectation workflow-template-submittable-t8f5r
workflow-template-submittable-t8f5r : Succeeded 
Found node id=workflow-template-submittable-t8f5r type=Pod
=== PASS: WorkflowTemplateSuite/TestSubmitWorkflowTemplateWorkflowMetadataSubstitution
--- PASS: TestWorkflowTemplateSuite (8.24s)
    --- PASS: TestWorkflowTemplateSuite/TestSubmitWorkflowTemplateWorkflowMetadataSubstitution (8.24s)
=== RUN   TestWorkflowSuite
--- PASS: TestWorkflowSuite (0.00s)
PASS
ok      github.com/argoproj/argo-workflows/v3/test/e2e  38.532s
```

### CODE REVIEW

**Comment by MasonM** [comment]
Test failures seem due to flakiness. `CI / E2E Tests (test-executor, minimal, false) (pull_request) ` is failing with the same error on the `main` branch: https://github.com/argoproj/argo-workflows/actions/runs/10969440498/job/30462136331

For the failure in `CI / E2E Tests (test-api, mysql, true) (pull_request) `, I verified `make TestCronCountersReplace` passes locally:
```
        
=== PASS: MetricsSuite/TestCronCountersReplace
=== SLOW TEST:  MetricsSuite/TestCronCountersReplace took 2m1s
--- PASS: TestMetricsSuite (121.10s)
    --- PASS: TestMetricsSuite/TestCronCountersReplace (121.09s)
=== RUN   TestPodCleanupSuite
--- PASS: TestPodCleanupSuite (0.01s)
=== RUN   TestProgressSuite
--- PASS: TestProgressSuite (0.01s)
=== RUN   TestResourceTemplateSuite
--- PASS: TestResourceTemplateSuite (0.01s)
=== RUN   TestRetrySuite
--- PASS: TestRetrySuite (0.01s)
=== RUN   TestRunAsNonRootSuite
--- PASS: TestRunAsNonRootSuite (0.01s)
=== RUN   TestSemaphoreSuite
--- PASS: TestSemaphoreSuite (0.01s)
=== RUN   TestSignalsSuite
--- PASS: TestSignalsSuite (0.01s)
=== RUN   TestConfigMapKeySelectorSubstitutionSuite
--- PASS: TestConfigMapKeySelectorSubstitutionSuite (0.00s)
=== RUN   TestWorkflowInputsOverridableSuiteSuite
--- PASS: TestWorkflowInputsOverridableSuiteSuite (0.00s)
=== RUN   TestWorkflowTemplateSuite
--- PASS: TestWorkflowTemplateSuite (0.00s)
=== RUN   TestWorkflowSuite
--- PASS: TestWorkflowSuite (0.00s)
PASS
ok      github.com/argoproj/argo-workflows/v3/test/e2e  124.559s
```

**Review by terrytangyuan — APPROVED** [review]
Thank you!

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -3931,7 +3931,7 @@ func (woc *wfOperationCtx) setExecWorkflow(ctx context.Context) error {
 		// Validate the execution wfSpec
 		err := waitutil.Backoff(retry.DefaultRetry,
 			func() (bool, error) {
-				validationErr := validate.ValidateWorkflow(wftmplGetter, cwftmplGetter, woc.wf, validateOpts)
+				validationErr := validate.ValidateWorkflow(wftmplGetter, cwftmplGetter, woc.wf, woc.controller.Config.WorkflowDefaults, validateOpts)
```
Comment (agilgur5) [inline workflow/controller/operator.go:3934]: In the Controller, this is normally handled via `setWorkflowDefaults` above and the difference between `woc.wf` and `woc.execWf`.

That's probably why this worked in direct submissions but not cron ones or server ones, if I had to guess. Also the cron part means this doesn't just affect the server, if I'm not mistaken

Comment (MasonM) [reply workflow/controller/operator.go:3934]: I'm not sure what you mean by "direct submissions", but if you mean submitting workflows via a `POST` request to `/api/v1/workflows`, then that too is broken. The E2E tests I updated in this PR checks for that. I created a branch of `main` that cherry-picks just the tests so you can see for yourself: https://github.com/argoproj/argo-workflows/compare/main...MasonM:argo-workflows:test-main-10946

Run `make TestSubmitWorkflowTemplateWorkflowMetadataSubstitution` and you should see the test fail with the following error:
```
workflow-template-submittable-v5xfw : Failed invalid spec: templates.whalesay-template: failed to resolve {{workflow.labels.default-label}}
Did not find node
```

Comment (agilgur5) [reply workflow/controller/operator.go:3934]: > I'm not sure what you mean by "direct submissions"

Sorry I meant through the k8s API / `kubectl` directly. Versus "server ones" I meant as through the API that are ofc failing. "cron ones" I meant bc they do go through the same `Submit` method as this PR shows, meaning it would be affecting the Controller too

Comment (MasonM) [reply workflow/controller/operator.go:3940]: Oh, okay. Yes, it looks like Cron workflows are affected too, so I updated the title to remove the `(server)` scope.

**Review by tczhao — APPROVED** [review]
