### PR TITLE
fix: panic on synchronization if workflow has mutex and semaphore

### LINKED ISSUE #7888: Observed invalid memory address or nil pointer dereference
## Summary

What happened/what you expected to happen? 

workflow failed but one of the template is shown as running. Upon checking the log, the controller was panic and the high level description is `runtime error: invalid memory address or nil pointer dereference`.

What executor are you using? PNS/Emissary

k8sapi

## Diagnostics

Our DAG is complex, I can't create a simplified DAG to reproduce the error yet. But it seems to me that it is semaphore related. In fact, we use the semaphore at the template-level as suggested in the doc [here](https://argoproj.github.io/argo-workflows/synchronization/#template-level-synchronization).

What Kubernetes provider are you using? `GKE 1.20.11-gke.1801`

What version of Argo Workflows are you running? `3.2.6`

The complete error and stack trace:

```
time="2022-02-15T04:57:26.663Z" level=error msg="Recovered from panic" namespace=mynamespace 
r="runtime error: invalid memory address or nil pointer dereference"
stack="
goroutine 290 [running]:
runtime/debug.Stack(0xc01e470a24, 0x1f22520, 0x331a940)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2(0xc00466c480, 0x24f2c28, 0xc00012a000)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:192 +0xd1
panic(0x1f22520, 0x331a940)
    /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.(*SemaphoreStatus).GetHolding(0x0, 0xc0030c7c70, 0x47, 0x47, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/workflow_types.go:2945 +0x45
github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.(*SemaphoreStatus).LockReleased(0x0, 0xc019a11ec0, 0x55, 0xc0030c7c70, 0x47, 0x2)
    /go/src/github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/workflow_types.go:2992 +0x76
github.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).Release(0xc0005b3800, 0xc004f58000, 0xc008919f80, 0x25, 0xc01d8e3d50)
    /go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:195 +0x343
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc00c7a25a0, 0xeb, 0x24dbf80, 0xc005642960, 0xc03040c9c0, 0xc005633540, 0x2, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1656 +0x534
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f99d0, 0xc0297e7740, 0xa)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:483 +0x90b
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f99d0, 0xc0297e7770, 0xf)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:408 +0x4a5
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f99d0, 0xc0297e7737, 0x9)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:408 +0x4a5
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc03fdb0600, 0x3d, 0xc03040c9c0, 0xc030ce3da8, 0x6, 0xc033dccb40, 0x24dbf80, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x309
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc03fdb0600, 0x3d, 0x24dbf80, 0xc005624690, 0xc03168bbc0, 0xc0055f9900, 0x1, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1806 +0x16bc
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f97a0, 0xc030ce3cc0, 0xd)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:483 +0x90b
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc010b9c3f0, 0x2f, 0xc03168bbc0, 0xc030ce3a10, 0x6, 0xc024648b40, 0x24dbf80, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x309
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc010b9c3f0, 0x2f, 0x24dbf80, 0xc0055efc20, 0xc03168b9c0, 0xc0055f8c80, 0x3, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1806 +0x16bc
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f9570, 0xc019a10f0a, 0x5)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:483 +0x90b
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f9570, 0xc030ce38a0, 0x6)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:408 +0x4a5
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc010b8d1d0, 0x29, 0xc03168b9c0, 0xc030ce34c4, 0x6, 0xc02f22d8c0, 0x24dbf80, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x309
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc010b8d1d0, 0x29, 0x24dbf80, 0xc0055ee690, 0xc03168b6c0, 0xc0055f4000, 0x5, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1806 +0x16bc
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f92d0, 0xc030ce3390, 0xe)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:483 +0x90b
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f92d0, 0xc0072cd6e5, 0x13)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:408 +0x4a5
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc0145f92d0, 0xc030ce33a0, 0x10)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:408 +0x4a5
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc031c213a0, 0x1a, 0xc03168b6c0, 0xc030ce3098, 0x6, 0xc0176998c0, 0x24dd0f0, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x309
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00466c480, 0x24f2c28, 0xc00012a000, 0xc031c213a0, 0x1a, 0x24dd0f0, 0xc00466c540, 0xc03168b680, 0xc004f2ee60, 0x2, ...)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1806 +0x16bc
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc00466c480, 0x24f2c28, 0xc00012a000)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:344 +0xf3e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000477400, 0x24f2c28, 0xc00012a000, 0x0)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:770 +0x945
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc000477400)
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:692 +0x9b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc006c00e40)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc006c00e40, 0x24ab6c0, 0xc006966a80, 0x1, 0xc00e3a6600)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc006c00e40, 0x3b9aca00, 0x0, 0x1, 0xc00e3a6600)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc006c00e40, 0x3b9aca00, 0xc00e3a6600)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading
    /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:309 +0x48a
" 
workflow=myworkflow
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

Fixes #7888, #7934

### CODE REVIEW

**Review by alexec — APPROVED** [review]
I approve this. I think we should get rid of lockType as I think it is redundant.

File: workflow/sync/sync_manager.go [hunk 1]
```diff
@@ -272,11 +272,14 @@ func (cm *Manager) ReleaseAll(wf *wfv1.Workflow) bool {
 }
 
 func ensureInit(wf *wfv1.Workflow, lockType wfv1.SynchronizationType) {
-	if lockType == wfv1.SynchronizationTypeSemaphore && (wf.Status.Synchronization == nil || wf.Status.Synchronization.Semaphore == nil) {
```
Comment (sarabala1979) [inline workflow/sync/sync_manager.go:275]: If workflow has mutex and semaphore and mutext initialized `wf.Status.Synchronization` before. This code was re-initializing `wf.Status.Synchronization` with only semaphore. So mutex is nil which is causing nil pointer expection.
