### PR TITLE
fix: optimize index to prevent 'out of sort memory' error Fixes #14240

### LINKED ISSUE #14240: UI shows out of memory in sort
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I have a namespace with more than 50 workflows
When I use latest version:

Image

When I use v3.6.4, it works well:

Image

When the workflows num is only five, all work well.

### Version(s)

latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
over 50 simple workflows in one namespace.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by downfa11**
Fixes #14240 

### Motivation

The existing index(`argo_archived_workflows_i1`) lacked a sort order, causing the database to extract all data first and then perform sorting on startedat within the sort buffer. This resulted in 'Out of sort memory' errors and system failure.
  
This issue specifically occurs under the following conditions:
- The optimizer selects `argo_archived_workflows_i1` instead of `argo_archived_workflows_i4` during namespace filtering.
- The workflow JSON data is large enough to exceed the MySQL `sort_buffer_size`.

### Modifications

Since this modification includes all existing index columns, it resolves the failure without causing any side effects to existing queries.
- Added `startedat DESC` to the `argo_archived_workflows_i1(clustername, instanceid, namespace)` index.

### Verification

Detailed reproduction steps and query execution plans can be found in this https://github.com/argoproj/argo-workflows/issues/14240#issuecomment-3753236025

**Actual UI failure state**:
스크린샷 2026-01-18 133344

**Resolved state under the same conditions**:
스크린샷 2026-01-18 133302

### CODE REVIEW

**Comment by shuangkun** [comment]
Nice. Could you add Fixes #14240 at the end of the title.

File: persist/sqldb/migrate.go [hunk 1]
```diff
@@ -188,6 +188,12 @@ func Migrate(ctx context.Context, session db.Session, clusterName, tableName str
 		}),
 		// add argo_archived_workflows index
 		sqldb.AnsiSQLChange(`create index argo_archived_workflows_i1 on argo_archived_workflows (clustername,instanceid,namespace)`),
+		// change argo_archived_workflows_i1 index to add startedat DESC to resolve MySQL out of sort memory issues. #14240
```
Comment (MasonM) [inline persist/sqldb/migrate.go]: These lines should go at the end of the `changes []Change` array, since the `schema_version` is based on the index of each entry in the array.

Comment (downfa11) [reply persist/sqldb/migrate.go]: Thank you for the review! I missed that part, but I've corrected it now. 

could you take another look when you have a moment?
