### PR TITLE
fix: do not patch empty progress. fixes #7184

### LINKED ISSUE #7184: Patching pod status too often
I see this far too often in the logs:

```
             logs | params-8k49h wait time="2021-11-08T22:55:51.206Z" level=info msg="patching pod progress annotation" progress=
             logs | params-8k49h wait time="2021-11-08T22:55:51.224Z" level=info msg="Patch pods 200"
```

We should never patch with "".

Caused by:feat: self reporting workflow progress (#6714)

### PR DESCRIPTION
**Pull request by mweibel**
fixes #7184

### CODE REVIEW

File: workflow/executor/executor.go [hunk 1]
```diff
@@ -980,9 +980,11 @@ func (we *WorkflowExecutor) monitorProgress(ctx context.Context, progressFile st
 			log.WithError(ctx.Err()).Info("stopping progress monitor (context done)")
 			return
 		case <-annotationPatchTicker.C:
-			log.WithField("progress", we.progress).Infof("patching pod progress annotation")
-			if err := we.AddAnnotation(ctx, common.AnnotationKeyProgress, we.progress); err != nil {
-				log.WithField("progress", we.progress).WithError(err).Warn("failed to patch progress annotation")
+			if we.progress.IsValid() {
```
Comment (simster7) [inline workflow/executor/executor.go:983]: ... else print warning?

Comment (simster7) [reply workflow/executor/executor.go:983]: I just saw #7184. Perhaps then

```go
if we.progress.IsValid() {
  ...
} else if we.progress != "" {
  log.Warnf("invalid progress...") // This is just an example, actual log with correct parameters of course
}
```

Comment (mweibel) [reply workflow/executor/executor.go:983]: I too did wonder if I should print a warning or not. I didn't add one because `progress` at this point should only be invalid when no progress is reported by the pod. In this case you're probably not interested in the warning, unless you're debugging something related to this. If the progress could not be parsed (invalid format) that's reported elsewhere already. 

So, should I add a warning or not?

Comment (simster7) [reply workflow/executor/executor.go:983]: > I didn't add one because progress at this point should only be invalid when no progress is reported by the pod.

Then perhaps 
```suggestion
			if we.progress != "" {
```
is more explicit?

> If the progress could not be parsed (invalid format) that's reported elsewhere already.

Great, then no warning necessary.

Comment (mweibel) [reply workflow/executor/executor.go]: fine for me 👍 changed the line ✅

**Review by simster7 — APPROVED** [review]
