### PR TITLE
fix: retry only proper node (#11589)

### LINKED ISSUE #11589: retryStrategy does not work correctly when we use hook
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

## Abstract

- Controller does not retry failed node when we use running hook.
  - image
- Controller marks workflow as succeeded when we use running hook.
   - image

## Root cause

- I think the root cause is the following logic.
  - Controller get a  hooked node as a `lastChiledNode`
    - https://github.com/argoproj/argo-workflows/blob/e46202a4c00f5c685a02eca9392ddfc1305ac9a0/workflow/controller/operator.go#L917
  - `lastChiledNode` = Running Node is succeeded. This node is retried node usually.
  - Then the parent node is marked as succeeded.
     - https://github.com/argoproj/argo-workflows/blob/e46202a4c00f5c685a02eca9392ddfc1305ac9a0/workflow/controller/operator.go#L943
  
## How to fix

- We should make sure `lastChiledNode` is last retried node.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
spec:
  templates:
    - name: argosay
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - /bin/sleep 2; exit 1; /argosay
        resources: {}
      retryStrategy:
        limit: 3
    - name: hook
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - /bin/sleep 2; /argosay
        resources: {}
  entrypoint: argosay
  arguments: {}
  hooks:
    failed:
      template: hook
      arguments: {}
      expression: workflow.status == "Failed"
    running:
      template: hook
      arguments: {}
      expression: workflow.status == "Running"
    succeed:
      template: hook
      arguments: {}
      expression: workflow.status == "Succeeded"
```

### Logs from the workflow controller

```text
time="2023-08-17T00:17:07.438Z" level=info msg="resolved artifact repository" artifactRepositoryRef="argo/#"
time="2023-08-17T00:17:07.438Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.438Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.438Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.438Z" level=info msg="Retry node omniscient-dragon-6gv5q initialized Running" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.438Z" level=info msg="lastChildNode: nil"
time="2023-08-17T00:17:07.438Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.438Z" level=info msg="Pod node omniscient-dragon-6gv5q-2532542085 initialized Pending" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.438Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.443Z" level=info msg="Created pod: omniscient-dragon-6gv5q(0) (omniscient-dragon-6gv5q-argosay-2532542085)" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.443Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.443Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.443Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.443Z" level=info msg="Pod node omniscient-dragon-6gv5q-794260213 initialized Pending" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.443Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.447Z" level=info msg="Created pod: omniscient-dragon-6gv5q.hooks.running (omniscient-dragon-6gv5q-hook-794260213)" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.447Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.447Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:07.447Z" level=info msg="Workflow to be dehydrated" Workflow Size=2224
time="2023-08-17T00:17:07.450Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1637 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.430Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.430Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.430Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=omniscient-dragon-6gv5q-794260213 old.message= old.phase=Pending old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.430Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=omniscient-dragon-6gv5q-2532542085 old.message= old.phase=Pending old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.431Z" level=info msg="lastChildNode: &NodeStatus{ID:omniscient-dragon-6gv5q-794260213,Name:omniscient-dragon-6gv5q.hooks.running,DisplayName:omniscient-dragon-6gv5q.hooks.running,Type:Pod,TemplateName:hook,TemplateRef:nil,Phase:Pending,BoundaryID:,Message:PodInitializing,StartedAt:2023-08-17 00:17:07 +0900 JST,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],TemplateScope:local/,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:6,SynchronizationStatus:nil,Progress:0/1,}"
time="2023-08-17T00:17:08.431Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.431Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.431Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.431Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.431Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:08.431Z" level=info msg="Workflow to be dehydrated" Workflow Size=2542
time="2023-08-17T00:17:08.436Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1648 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=info msg="node unchanged" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=info msg="node unchanged" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=info msg="lastChildNode: &NodeStatus{ID:omniscient-dragon-6gv5q-794260213,Name:omniscient-dragon-6gv5q.hooks.running,DisplayName:omniscient-dragon-6gv5q.hooks.running,Type:Pod,TemplateName:hook,TemplateRef:nil,Phase:Pending,BoundaryID:,Message:PodInitializing,StartedAt:2023-08-17 00:17:07 +0900 JST,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],TemplateScope:local/,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:6,SynchronizationStatus:nil,Progress:0/1,}"
time="2023-08-17T00:17:09.560Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:09.560Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.563Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.563Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.563Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=omniscient-dragon-6gv5q-794260213 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.564Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=omniscient-dragon-6gv5q-2532542085 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.564Z" level=info msg="lastChildNode: &NodeStatus{ID:omniscient-dragon-6gv5q-794260213,Name:omniscient-dragon-6gv5q.hooks.running,DisplayName:omniscient-dragon-6gv5q.hooks.running,Type:Pod,TemplateName:hook,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2023-08-17 00:17:07 +0900 JST,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],TemplateScope:local/,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:6,SynchronizationStatus:nil,Progress:0/1,}"
time="2023-08-17T00:17:10.564Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.564Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.564Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.564Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.564Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:10.564Z" level=info msg="Workflow to be dehydrated" Workflow Size=2511
time="2023-08-17T00:17:10.570Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1665 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.577Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.577Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=2 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.577Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.577Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.577Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=omniscient-dragon-6gv5q-794260213 old.message= old.phase=Running old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.577Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=omniscient-dragon-6gv5q-2532542085 old.message= old.phase=Running old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.577Z" level=info msg="lastChildNode: &NodeStatus{ID:omniscient-dragon-6gv5q-794260213,Name:omniscient-dragon-6gv5q.hooks.running,DisplayName:omniscient-dragon-6gv5q.hooks.running,Type:Pod,TemplateName:hook,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2023-08-17 00:17:07 +0900 JST,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,},Key:omniscient-dragon-6gv5q/omniscient-dragon-6gv5q-hook-794260213/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[],OutboundNodes:[],TemplateScope:local/,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:6,SynchronizationStatus:nil,Progress:0/1,}"
time="2023-08-17T00:17:13.577Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.578Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.578Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.578Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.578Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.578Z" level=info msg="Workflow to be dehydrated" Workflow Size=2761
time="2023-08-17T00:17:13.581Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1674 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:13.583Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/omniscient-dragon-6gv5q-hook-794260213/terminateContainers
time="2023-08-17T00:17:13.583Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/omniscient-dragon-6gv5q-argosay-2532542085/terminateContainers
time="2023-08-17T00:17:13.583Z" level=info msg="https://0.0.0.0:33703/api/v1/namespaces/argo/pods/omniscient-dragon-6gv5q-hook-794260213/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-08-17T00:17:13.583Z" level=info msg="https://0.0.0.0:33703/api/v1/namespaces/argo/pods/omniscient-dragon-6gv5q-argosay-2532542085/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-08-17T00:17:13.595Z" level=info msg="signaled container" container=wait error="unable to upgrade connection: container not found (\"wait\")" namespace=argo pod=omniscient-dragon-6gv5q-hook-794260213 stderr="<nil>" stdout="<nil>"
time="2023-08-17T00:17:13.595Z" level=info msg="signaled container" container=wait error="unable to upgrade connection: container not found (\"wait\")" namespace=argo pod=omniscient-dragon-6gv5q-argosay-2532542085 stderr="<nil>" stdout="<nil>"
time="2023-08-17T00:17:14.584Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.584Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=2 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg="node unchanged" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg="node unchanged" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg="lastChildNode: &NodeStatus{ID:omniscient-dragon-6gv5q-794260213,Name:omniscient-dragon-6gv5q.hooks.running,DisplayName:omniscient-dragon-6gv5q.hooks.running,Type:Pod,TemplateName:hook,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2023-08-17 00:17:07 +0900 JST,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,},Key:omniscient-dragon-6gv5q/omniscient-dragon-6gv5q-hook-794260213/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[],OutboundNodes:[],TemplateScope:local/,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:6,SynchronizationStatus:nil,Progress:0/1,}"
time="2023-08-17T00:17:14.585Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:14.585Z" level=info msg="Workflow to be dehydrated" Workflow Size=2762
time="2023-08-17T00:17:14.590Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/omniscient-dragon-6gv5q-hook-794260213/terminateContainers
time="2023-08-17T00:17:14.590Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/omniscient-dragon-6gv5q-argosay-2532542085/terminateContainers
time="2023-08-17T00:17:14.591Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1677 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=2 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=omniscient-dragon-6gv5q-794260213 old.message= old.phase=Running old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="Pod failed: Error (exit code 1)" displayName="omniscient-dragon-6gv5q(0)" namespace=argo pod=omniscient-dragon-6gv5q-argosay-2532542085 templateName=argosay workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=omniscient-dragon-6gv5q-2532542085 old.message= old.phase=Running old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="lastChildNode: &NodeStatus{ID:omniscient-dragon-6gv5q-794260213,Name:omniscient-dragon-6gv5q.hooks.running,DisplayName:omniscient-dragon-6gv5q.hooks.running,Type:Pod,TemplateName:hook,TemplateRef:nil,Phase:Succeeded,BoundaryID:,Message:,StartedAt:2023-08-17 00:17:07 +0900 JST,FinishedAt:2023-08-17 00:17:12 +0900 JST,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,},Key:omniscient-dragon-6gv5q/omniscient-dragon-6gv5q-hook-794260213/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[],OutboundNodes:[],TemplateScope:local/,ResourcesDuration:ResourcesDuration{cpu: 7s,memory: 5s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:6,SynchronizationStatus:nil,Progress:0/1,}"
time="2023-08-17T00:17:16.596Z" level=info msg="Node omniscient-dragon-6gv5q is Changed to Succeeded"
time="2023-08-17T00:17:16.596Z" level=info msg="node omniscient-dragon-6gv5q phase Running -> Succeeded" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="node omniscient-dragon-6gv5q finished: 2023-08-16 15:17:16.596558443 +0000 UTC" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="Running workflow level hooks" lifeCycleHook=succeed namespace=argo node=omniscient-dragon-6gv5q.hooks.succeed workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=info msg="Pod node omniscient-dragon-6gv5q-854958522 initialized Pending" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.596Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.601Z" level=info msg="Created pod: omniscient-dragon-6gv5q.hooks.succeed (omniscient-dragon-6gv5q-hook-854958522)" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.601Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.601Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.601Z" level=info msg="Workflow to be dehydrated" Workflow Size=3270
time="2023-08-17T00:17:16.604Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1685 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:16.610Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/omniscient-dragon-6gv5q-argosay-2532542085/labelPodCompleted
time="2023-08-17T00:17:16.610Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/omniscient-dragon-6gv5q-hook-794260213/labelPodCompleted
time="2023-08-17T00:17:17.602Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=2 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=omniscient-dragon-6gv5q-854958522 old.message= old.phase=Pending old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg="Running workflow level hooks" lifeCycleHook=succeed namespace=argo node=omniscient-dragon-6gv5q.hooks.succeed workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:17.603Z" level=info msg="Workflow to be dehydrated" Workflow Size=3309
time="2023-08-17T00:17:17.607Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1698 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.607Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.607Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=2 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.607Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.607Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.607Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=omniscient-dragon-6gv5q-854958522 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.607Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.607Z" level=info msg="Running workflow level hooks" lifeCycleHook=succeed namespace=argo node=omniscient-dragon-6gv5q.hooks.succeed workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.608Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.608Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.608Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:18.608Z" level=info msg="Workflow to be dehydrated" Workflow Size=3293
time="2023-08-17T00:17:18.611Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1705 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.612Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.612Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=2 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.612Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.612Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.612Z" level=info msg="node unchanged" namespace=argo nodeID=omniscient-dragon-6gv5q-854958522 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.613Z" level=info msg="Running workflow level hooks" lifeCycleHook=succeed namespace=argo node=omniscient-dragon-6gv5q.hooks.succeed workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.613Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.613Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.613Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.613Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:19.614Z" level=info msg="Workflow to be dehydrated" Workflow Size=3294
time="2023-08-17T00:17:19.619Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1707 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=3 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-854958522 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=omniscient-dragon-6gv5q-854958522 old.message= old.phase=Running old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="Running workflow level hooks" lifeCycleHook=succeed namespace=argo node=omniscient-dragon-6gv5q.hooks.succeed workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.613Z" level=info msg="Workflow to be dehydrated" Workflow Size=3416
time="2023-08-17T00:17:22.617Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1713 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:22.619Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/omniscient-dragon-6gv5q-hook-854958522/terminateContainers
time="2023-08-17T00:17:23.614Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.614Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=3 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.614Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.614Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.614Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-854958522 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.614Z" level=info msg="node unchanged" namespace=argo nodeID=omniscient-dragon-6gv5q-854958522 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.615Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.615Z" level=info msg="Running workflow level hooks" lifeCycleHook=succeed namespace=argo node=omniscient-dragon-6gv5q.hooks.succeed workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.615Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.615Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.615Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.615Z" level=info msg="Workflow to be dehydrated" Workflow Size=3417
time="2023-08-17T00:17:23.619Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1714 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:23.620Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/omniscient-dragon-6gv5q-hook-854958522/terminateContainers
time="2023-08-17T00:17:24.620Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=3 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-854958522 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="node unchanged" namespace=argo nodeID=omniscient-dragon-6gv5q-854958522 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="Running workflow level hooks" lifeCycleHook=succeed namespace=argo node=omniscient-dragon-6gv5q.hooks.succeed workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=error msg="was unable to obtain node for " namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.620Z" level=info msg="Workflow to be dehydrated" Workflow Size=3417
time="2023-08-17T00:17:24.624Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1714 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:24.625Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/omniscient-dragon-6gv5q-hook-854958522/terminateContainers
time="2023-08-17T00:17:25.623Z" level=info msg="Processing workflow" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.623Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=3 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.623Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-2532542085 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.623Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-794260213 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.623Z" level=info msg="task-result changed" namespace=argo nodeID=omniscient-dragon-6gv5q-854958522 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.623Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=omniscient-dragon-6gv5q-854958522 old.message= old.phase=Running old.progress=0/1 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.624Z" level=info msg="Running workflow level hooks" lifeCycleHook=running namespace=argo node=omniscient-dragon-6gv5q.hooks.running workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.624Z" level=info msg="Running workflow level hooks" lifeCycleHook=succeed namespace=argo node=omniscient-dragon-6gv5q.hooks.succeed workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.624Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.624Z" level=info msg=reconcileAgentPod namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.624Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.624Z" level=info msg="Marking workflow completed" namespace=argo workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.624Z" level=info msg="Workflow to be dehydrated" Workflow Size=3524
time="2023-08-17T00:17:25.627Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=1717 workflow=omniscient-dragon-6gv5q
time="2023-08-17T00:17:25.629Z" level=info msg="cleaning up pod" action=deletePod key=argo/omniscient-dragon-6gv5q-1340600742-agent/deletePod
time="2023-08-17T00:17:25.640Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/omniscient-dragon-6gv5q-hook-854958522/labelPodCompleted
time="2023-08-17T00:17:43.595Z" level=info msg="cleaning up pod" action=killContainers key=argo/omniscient-dragon-6gv5q-hook-794260213/killContainers
time="2023-08-17T00:17:43.595Z" level=info msg="cleaning up pod" action=killContainers key=argo/omniscient-dragon-6gv5q-argosay-2532542085/killContainers
time="2023-08-17T00:17:52.620Z" level=info msg="cleaning up pod" action=killContainers key=argo/omniscient-dragon-6gv5q-hook-854958522/killContainers
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by toyamagu-2021**
Signed-off-by: toyamagu-2021 <toyamagu2021@gmail.com>

Fixes #11589 

### Motivation

* Retry only retried nodes.

### Modifications

* When retring, exclude hooked nodes. 

### Verification

* retryStrategy works correctly
  * image
* This PR also works fine for WorkflowTemplateLevelHook
  * image
* When running, the hook node is DAG
  * image
* When running the hook node is Step
  * image
* Works file for a most complicated case
  * image

<details>
<summary>manifest</summary>

```yaml
spec:
  templates:
    - name: argosay
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - /bin/sleep 2; exit 100; /argosay
        resources: {}
      retryStrategy:
        limit: 1
    - name: hook
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: A
            template: argosay
            arguments: {}
            hooks:
              failed:
                template: argosay2
                arguments: {}
                expression: steps.A.status == "Failed"
              running:
                template: argosay2
                arguments: {}
                expression: steps.A.status == "Running"
              succeed:
                template: argosay2
                arguments: {}
                expression: steps.A.status == "Succeeded"
        - - name: B
            template: argosay
            arguments: {}
    - name: argosay2
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - exit 0
        resources: {}
  entrypoint: argosay
  arguments: {}
  hooks:
    running:
      template: hook
      arguments: {}
      expression: workflow.status == "Running"
```

</details>

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1719,6 +1729,21 @@ func getChildNodeIndex(node *wfv1.NodeStatus, nodes wfv1.Nodes, index int) *wfv1
 	return &lastChildNode
 }
 
+func getChildNodeIdsRetried(node *wfv1.NodeStatus, nodes wfv1.Nodes) []string {
+	childrenIds := []string{}
+	r := regexp.MustCompile(`^` + regexp.QuoteMeta(node.Name) + `\(\d+\)`)
+	for i := 0; i < len(node.Children); i++ {
+		n := getChildNodeIndex(node, nodes, i)
+		if node == nil {
+			continue
```
Comment (juliev0) [inline workflow/controller/operator.go:1738]: Is this check correct? If so, why bother calling the line above it (since `node` is passed in as a parameter to the method and is not modified on line 1736)?

**Review by juliev0 — COMMENTED** [review]
Thanks for fixing.

So, in your example from [your](https://github.com/argoproj/argo-workflows/issues/11589) original issue, are you saying the _hook_ node is actually a child of the _argosay_ node? That seems kind of surprising, doesn't it? Are both nodes of type "Pod"?

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -1719,6 +1729,21 @@ func getChildNodeIndex(node *wfv1.NodeStatus, nodes wfv1.Nodes, index int) *wfv1
...
+		}
+		if r.MatchString(n.Name) {
+			childrenIds = append(childrenIds, n.ID)
+		}
+	}
+	return childrenIds
```
Comment (juliev0) [inline workflow/controller/operator.go:1744]: Can you add comments to this function? I'm trying to understand why you're not just looking for all child nodes of "Type"="Retry"

**Review by juliev0 — COMMENTED** [review]
is it possible to post in this PR an example `WorkflowStatus` corresponding to a WorkflowSpec: mainly just want to see the "tree" of Nodes to understand the relationship between the nodes, where both Retry and Hook are involved. Thank you!

File: test/e2e/hooks_test.go [hunk 3]
```diff
@@ -567,6 +567,71 @@ spec:
 		})
 }
 
+func (s *HooksSuite) TestWorkflowLevelHooksWithRetry() {
```
Comment (terrytangyuan) [inline test/e2e/hooks_test.go:570]: Nice test

File: workflow/controller/operator.go (hunk 2 above)
Comment (toyamagu-2021) [reply workflow/controller/operator.go:1746]: As commented, we can't distinguish retried nodes from other nodes because they have the same node type `type: Pod`.
Only the parent node has `type: Retry`.
(I also don't like this function I wrote, so any suggestions are very welcome.)

example parent node

```
    lovely-bear:
      id: lovely-bear
      name: lovely-bear
      displayName: lovely-bear
      type: Retry
      templateName: argosay
      templateScope: local/lovely-bear
      phase: Failed
      message: No more retries left
      startedAt: '2023-09-30T13:49:20Z'
      finishedAt: '2023-09-30T13:49:56Z'
      progress: 2/6
      resourcesDuration:
        cpu: 42
        memory: 30
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-argosay-74551197/main.log
        exitCode: '1'
      children:
        - lovely-bear-477066958
        - lovely-bear-794339884
        - lovely-bear-4167892875
        - lovely-bear-410250672
        - lovely-bear-74551197
        - lovely-bear-2163413524
```

example child node

```
    lovely-bear-410250672:
      id: lovely-bear-410250672
      name: lovely-bear(2)
      displayName: lovely-bear(2)
      type: Pod
      templateName: argosay
      templateScope: local/lovely-bear
      phase: Failed
      message: Error (exit code 1)
      startedAt: '2023-09-30T13:49:38Z'
      finishedAt: '2023-09-30T13:49:43Z'
      progress: 0/1
      resourcesDuration:
        cpu: 7
        memory: 5
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-argosay-410250672/main.log
        exitCode: '1'
      hostNodeName: k3d-k3s-default-server-0
```

example hooked node

```
    lovely-bear-2163413524:
      id: lovely-bear-2163413524
      name: lovely-bear.hooks.failed
      displayName: lovely-bear.hooks.failed
      type: Pod
      templateName: hook
      templateScope: local/lovely-bear
      phase: Succeeded
      startedAt: '2023-09-30T13:49:56Z'
      finishedAt: '2023-09-30T13:50:01Z'
      progress: 1/1
      resourcesDuration:
        cpu: 7
        memory: 5
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-hook-2163413524/main.log
        exitCode: '0'
      hostNodeName: k3d-k3s-default-server-0
```

**Review by toyamagu-2021 — COMMENTED** [review]
@juliev0 
Thanks! It is clear enough?

* Node type of retried nodes
  * `type: Pod`
* parent node of hooked node
  * `type: Rety`

Full `nodeStatus` is following:

<summary> nodeStatus </summary>
<details>

```yaml
status:
  phase: Failed
  startedAt: '2023-09-30T13:49:20Z'
  finishedAt: '2023-09-30T13:50:05Z'
  progress: 2/6
  message: No more retries left
  nodes:
    lovely-bear:
      id: lovely-bear
      name: lovely-bear
      displayName: lovely-bear
      type: Retry
      templateName: argosay
      templateScope: local/lovely-bear
      phase: Failed
      message: No more retries left
      startedAt: '2023-09-30T13:49:20Z'
      finishedAt: '2023-09-30T13:49:56Z'
      progress: 2/6
      resourcesDuration:
        cpu: 42
        memory: 30
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-argosay-74551197/main.log
        exitCode: '1'
      children:
        - lovely-bear-477066958
        - lovely-bear-794339884
        - lovely-bear-4167892875
        - lovely-bear-410250672
        - lovely-bear-74551197
        - lovely-bear-2163413524
    lovely-bear-2163413524:
      id: lovely-bear-2163413524
      name: lovely-bear.hooks.failed
      displayName: lovely-bear.hooks.failed
      type: Pod
      templateName: hook
      templateScope: local/lovely-bear
      phase: Succeeded
      startedAt: '2023-09-30T13:49:56Z'
      finishedAt: '2023-09-30T13:50:01Z'
      progress: 1/1
      resourcesDuration:
        cpu: 7
        memory: 5
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-hook-2163413524/main.log
        exitCode: '0'
      hostNodeName: k3d-k3s-default-server-0
    lovely-bear-410250672:
      id: lovely-bear-410250672
      name: lovely-bear(2)
      displayName: lovely-bear(2)
      type: Pod
      templateName: argosay
      templateScope: local/lovely-bear
      phase: Failed
      message: Error (exit code 1)
      startedAt: '2023-09-30T13:49:38Z'
      finishedAt: '2023-09-30T13:49:43Z'
      progress: 0/1
      resourcesDuration:
        cpu: 7
        memory: 5
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-argosay-410250672/main.log
        exitCode: '1'
      hostNodeName: k3d-k3s-default-server-0
    lovely-bear-4167892875:
      id: lovely-bear-4167892875
      name: lovely-bear(1)
      displayName: lovely-bear(1)
      type: Pod
      templateName: argosay
      templateScope: local/lovely-bear
      phase: Failed
      message: Error (exit code 1)
      startedAt: '2023-09-30T13:49:29Z'
      finishedAt: '2023-09-30T13:49:34Z'
      progress: 0/1
      resourcesDuration:
        cpu: 7
        memory: 5
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-argosay-4167892875/main.log
        exitCode: '1'
      hostNodeName: k3d-k3s-default-server-0
    lovely-bear-477066958:
      id: lovely-bear-477066958
      name: lovely-bear(0)
      displayName: lovely-bear(0)
      type: Pod
      templateName: argosay
      templateScope: local/lovely-bear
      phase: Failed
      message: Error (exit code 1)
      startedAt: '2023-09-30T13:49:20Z'
      finishedAt: '2023-09-30T13:49:25Z'
      progress: 0/1
      resourcesDuration:
        cpu: 7
        memory: 5
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-argosay-477066958/main.log
        exitCode: '1'
      hostNodeName: k3d-k3s-default-server-0
    lovely-bear-74551197:
      id: lovely-bear-74551197
      name: lovely-bear(3)
      displayName: lovely-bear(3)
      type: Pod
      templateName: argosay
      templateScope: local/lovely-bear
      phase: Failed
      message: Error (exit code 1)
      startedAt: '2023-09-30T13:49:47Z'
      finishedAt: '2023-09-30T13:49:52Z'
      progress: 0/1
      resourcesDuration:
        cpu: 7
        memory: 5
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-argosay-74551197/main.log
        exitCode: '1'
      hostNodeName: k3d-k3s-default-server-0
    lovely-bear-794339884:
      id: lovely-bear-794339884
      name: lovely-bear.hooks.running
      displayName: lovely-bear.hooks.running
      type: Pod
      templateName: hook
      templateScope: local/lovely-bear
      phase: Succeeded
      startedAt: '2023-09-30T13:49:20Z'
      finishedAt: '2023-09-30T13:49:25Z'
      progress: 1/1
      resourcesDuration:
        cpu: 7
        memory: 5
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: lovely-bear/lovely-bear-hook-794339884/main.log
        exitCode: '0'
      hostNodeName: k3d-k3s-default-server-0
  conditions:
    - type: PodRunning
      status: 'False'
    - type: Completed
      status: 'True'
  resourcesDuration:
    cpu: 42
    memory: 30
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
    namespace: argo
    artifactRepository:
      archiveLogs: true
      s3:
        endpoint: minio:9000
        bucket: my-bucket
        insecure: true
        accessKeySecret:
          name: my-minio-cred
          key: accesskey
        secretKeySecret:
          name: my-minio-cred
          key: secretkey
  artifactGCStatus:
    notSpecified: true
```

</details>

File: workflow/controller/operator.go (hunk 2 above)
Comment (juliev0) [reply workflow/controller/operator.go:1746]: Yes, thank you! I forgot the parent was "Retry" and the children were "Pod"

Comment (juliev0) [reply workflow/controller/operator.go:1746]: Okay, starting to understand the logic now looking at what you posted. Thanks for doing that.

So, I can assume that the spec for this is a running hook which has `expression: workflow.status == "Running"`, right? Does it seem a little odd that the hook node is a child of the Retry node? Do you figure that it would be the child of whatever the first running Node is?

Comment (juliev0) [reply workflow/controller/operator.go:1746]: I also can't really remember what is a child of what. If there are 3 Steps A-> B-> C, do you know if B would be a child of A because it follows it, or are A, B, and C siblings (which is what I would assume)?

Comment (toyamagu-2021) [reply workflow/controller/operator.go:1746]: > So, I can assume that the spec for this is a running hook which has expression: workflow.status == "Running", right?

Yes

> Does it seem a little odd that the hook node is a child of the Retry node?

I think, not.

1. Hooks should be triggered by retry node status.
   * `Succeed`/`Failed` hook should be triggered when `Retry` node succeeded/failed.
   * So `Running` hook should be triggered depending on `Retry` node status, shouldn't be?
2. It might be difficult technically.
   * We should change hook logic around [here](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/controller/steps.go#L316-L317)

> I also can't really remember what is a child of what. If there are 3 Steps A-> B-> C, do you know if B would be a child of A because it follows it, or are A, B, and C siblings (which is what I would assume)?

I don't fully understand what you mentioning here, but it depends on steps

a: parent -> b, c: childs

```yaml
 - - name: a
 - - name: b
    - name: c
``` 

a, b, c: parents

```yaml
 - - name: a
   - name: b
   - name: c
```

Comment (juliev0) [reply workflow/controller/operator.go:1746]: Thanks for clarifying. I see now that the relationship from parent to child is "child follows parent sequentially", right? Since the hook is on the workflow level, I do have to wonder what it would look like if there were 2 steps running in parallel and the same hook of expression `workflow.status == "Running"`. What would the hook be a child of? Whichever parallel step happened to get started first?

Comment (juliev0) [reply workflow/controller/operator.go:1746]: In the example from your Issue, the Hook is on the [workflow](https://github.com/argoproj/argo-workflows/blob/master/examples/life-cycle-hooks-wf-level.yaml) level, not the [step](https://github.com/argoproj/argo-workflows/blob/master/examples/life-cycle-hooks-tmpl-level.yaml) level, right?

Comment (toyamagu-2021) [reply workflow/controller/operator.go:1746]: Thank you for pointing that out!
When we use step with WorkflowLevelHook, a hook is connected to the Steps node, so retryStrategy works fine.
image

<details>
<summary>workflow</summary>

```yaml
spec:
  templates:
    - name: hello-hello-hello
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: a
            template: whalesay
            arguments: {}
          - name: b
            template: whalesay
            arguments: {}
    - name: whalesay
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: docker/whalesay
        command:
          - sh -c
        args:
          - exit 1
        resources: {}
      retryStrategy:
        limit: '1'
    - name: hook
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: docker/whalesay
        command:
          - cowsay
        args:
          - test
        resources: {}
      retryStrategy:
        limit: '0'
  entrypoint: hello-hello-hello
  arguments: {}
  hooks:
    failed:
      template: hook
      arguments: {}
      expression: workflow.status == "Failed"
    running:
      template: hook
      arguments: {}
      expression: workflow.status == "Running"
    succeed:
      template: hook
      arguments: {}
      expression: workflow.status == "Succeeded"
```

</details>

But we have the same problem for [WorkflowTemplateLevelHook](https://github.com/argoproj/argo-workflows/issues/11589#issuecomment-1743902549)
I added validation for WorkflowTemplateLevelHook in the PR description

Comment (juliev0) [reply workflow/controller/operator.go:1746]: I see. So, this PR resolves both cases? And is this particular method - `getChildNodeIdsRetried()` - the logic that runs in both cases? You were saying the hook in the Workflow-level case is a child of the StepGroup?

Comment (juliev0) [reply workflow/controller/operator.go:1746]: I do see what you mean that going off the regular expression of the name doesn't seem great. It does make me wonder if perhaps the NodeStatus could potentially have some new key/value pair in it or potentially even the "Type" field could have a new value like "HookPod" - what are your thoughts since you've looked at this code more than I?

Comment (juliev0) [reply workflow/controller/operator.go:1746]: I am kind of thinking we shouldn't rely on somebody not changing the name in the future

Comment (toyamagu-2021) [reply workflow/controller/operator.go:1746]: > I see. So, this PR resolves both cases? And is this particular method - getChildNodeIdsRetried() - the logic that runs in both cases?

Yes. This PR resolves both cases.

> It does make me wonder if perhaps the NodeStatus could potentially have some new key/value pair in it like isHook - what do you think?

Ideally, completely agree with you.
I'm going to write a code that changes NodeStatus go struct!

Comment (juliev0) [reply workflow/controller/operator.go:1746]: thank you! Once you do I think you'll need to run `make codegen` to auto-generate the CRD and other files from that struct

File: workflow/controller/steps.go [hunk 4]
```diff
@@ -260,7 +260,7 @@ func (woc *wfOperationCtx) executeStepGroup(ctx context.Context, stepGroup []wfv
 		// Check the step's when clause to decide if it should execute
 		proceed, err := shouldExecute(step.When)
 		if err != nil {
-			woc.initializeNode(childNodeName, wfv1.NodeTypeSkipped, stepTemplateScope, &step, stepsCtx.boundaryID, wfv1.NodeError, err.Error())
```
Comment (toyamagu-2021) [inline workflow/controller/steps.go:263]: Only top-level dag or step nodes should be marked as `hooked`.

File: workflow/controller/dag.go [hunk 5]
```diff
@@ -511,7 +511,7 @@ func (woc *wfOperationCtx) executeDAGTask(ctx context.Context, dagCtx *dagContex
 		}
 		execute, proceed, err := dagCtx.evaluateDependsLogic(taskName)
 		if err != nil {
-			woc.initializeNode(nodeName, wfv1.NodeTypeSkipped, dagTemplateScope, task, dagCtx.boundaryID, wfv1.NodeError, err.Error())
```
Comment (toyamagu-2021) [inline workflow/controller/dag.go:514]: Only top-level dag or step nodes should be marked as `hooked`.

File: workflow/controller/steps.go [hunk 6]
```diff
@@ -68,7 +68,7 @@ func (woc *wfOperationCtx) executeSteps(ctx context.Context, nodeName string, tm
 		{
 			sgNode, err := woc.wf.GetNodeByName(sgNodeName)
 			if err != nil {
-				_ = woc.initializeNode(sgNodeName, wfv1.NodeTypeStepGroup, stepTemplateScope, &wfv1.WorkflowStep{}, stepsCtx.boundaryID, wfv1.NodeRunning)
```
Comment (toyamagu-2021) [inline workflow/controller/steps.go:71]: Only top-level dag or step nodes should be marked as `hooked`.
I confirmed this case [See PR description]

File: workflow/controller/operator.go (hunk 2 above)
Comment (toyamagu-2021) [reply workflow/controller/operator.go:1739]: Hi, I've added `NodeStatus.Hooked` and some node initialization. Could you give me feedback :)?

File: workflow/controller/steps.go (hunk 6 above)
Comment (juliev0) [reply workflow/controller/steps.go:71]: Sorry, can you clarify what you mean? I figure `hooked` means that the Node is a hook, right?

Are you referring here to the case in which the hook is itself a `StepGroup`? Is that your picture titled "When running hook node is Step"?

File: workflow/controller/operator.go [hunk 7]
```diff
@@ -1719,6 +1725,20 @@ func getChildNodeIndex(node *wfv1.NodeStatus, nodes wfv1.Nodes, index int) *wfv1
 	return &lastChildNode
 }
 
+func getChildNodeIdsRetried(node *wfv1.NodeStatus, nodes wfv1.Nodes) []string {
+	childrenIds := []string{}
+	for i := 0; i < len(node.Children); i++ {
+		n := getChildNodeIndex(node, nodes, i)
+		if n == nil {
+			continue
```
Comment (juliev0) [inline workflow/controller/operator.go:1733]: curious - what could cause us to hit the "continue" line? Is it just sort of "in case"?

**Comment by juliev0** [comment]
Thanks for updating all of the logic to add in the new `hooked` variable. 
Thanks for showing the pictures to show what you verified. It seems like you investigated a lot of possible hook specs.

I'm wondering if I can request that you add even more to the description above as far as what you did? I'm short on time, so the more thorough you are there, the more it will help me to understand. And then we can get this merged.

File: workflow/controller/operator.go (hunk 7 above)
Comment (toyamagu-2021) [reply workflow/controller/operator.go:1733]: Yes, just in case.

File: workflow/controller/steps.go (hunk 6 above)
Comment (toyamagu-2021) [reply workflow/controller/steps.go:71]: Sorry for the little description. And thank you for pointing out that.
It's only a definition of `hooked` status.
As far as I understood, `StepGroup`/`DagTask` is children of `Step`/`Dag` node, and we cannot hook `StepGroup`/`DagTask` itself.

I mean the following situation:
image
Only top-level Step nodes are marked as `Hooked: true` and children are not.

<details>
<summary>manifest</summary>

```yaml
spec:
  templates:
    - name: argosay
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - /bin/sleep 2; exit 100; /argosay
        resources: {}
      retryStrategy:
        limit: 1
    - name: hook
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: A
            template: argosay2
            arguments: {}
        - - name: B
            template: argosay2
            arguments: {}
    - name: argosay2
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - exit 0
        resources: {}
  entrypoint: argosay
  arguments: {}
  hooks:
    failed:
      template: hook
      arguments: {}
      expression: workflow.status == "Failed"
    running:
      template: hook
      arguments: {}
      expression: workflow.status == "Running"
    succeed:
      template: hook
      arguments: {}
      expression: workflow.status == "Succeeded"
```

</details>

This 'definition' might be useful if we would like to retry hooked nodes.
image

<details>
<summary>manifest</summary>

```
spec:
  templates:
    - name: argosay
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - /bin/sleep 2; exit 100; /argosay
        resources: {}
      retryStrategy:
        limit: 1
    - name: hook
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: A
            template: argosay
            arguments: {}
        - - name: B
            template: argosay
            arguments: {}
    - name: argosay2
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - exit 0
        resources: {}
      retryStrategy:
        limit: 1
  entrypoint: argosay
  arguments: {}
  hooks:
    failed:
      template: hook
      arguments: {}
      expression: workflow.status == "Failed"
    running:
      template: hook
      arguments: {}
      expression: workflow.status == "Running"
    succeed:
      template: hook
      arguments: {}
      expression: workflow.status == "Succeeded"
```

</details>

Comment (juliev0) [reply workflow/controller/steps.go:71]: thanks for drawing - one correction - I think "Type: Step" is supposed to be "Type: Steps", right? (I just tried running your example)

Comment (toyamagu-2021) [reply workflow/controller/steps.go:71]: Oh, yes exactly. Fixed.

File: workflow/controller/operator.go [hunk 8]
```diff
@@ -3938,3 +3968,22 @@ func setWfPodNamesAnnotation(wf *wfv1.Workflow) {
...
+	if len(childNodeIds) == 0 {
+		childNodeIds = node.Children
+	}
+
+	lastChildNode, err := nodes.Get(childNodeIds[len(childNodeIds)-1])
+	if err != nil {
+		panic(fmt.Sprintf("could not find nodeId %s in Children of node %+v", childNodeIds[len(childNodeIds)-1], node))
+	}
+	return childNodeIds, lastChildNode
+}
```
Comment (juliev0) [inline workflow/controller/operator.go:3989]: please add a comment to the top of this function

File: workflow/controller/operator.go (hunk 2 above)
Comment (juliev0) [reply workflow/controller/operator.go:1739]: can you add a thorough comment to the top of this function to explain what it's doing, what the various cases are, etc?

File: workflow/controller/steps.go (hunk 6 above)
Comment (juliev0) [reply workflow/controller/steps.go:71]: I looked carefully at your two examples above: I see - in the first one your hook calls a template which defines some steps. In your second example, your [template-level] hook calls a template which is a Pod.

File: workflow/controller/operator.go (hunk 8 above)
Comment (juliev0) [reply workflow/controller/operator.go:3989]: I really hate to mention this - but I'm debating if in addition to the "Hooked" boolean you added, we should have a "Retried" boolean? And maybe the logic should be based on that instead? Would it make this method more readable? (sorry) What do you think?

Comment (juliev0) [reply workflow/controller/operator.go:3989]: I guess it's mainly that I find line 3981 unclear. If you think there's a good way to make it more clear through comments, then we don't need to add the "Retried" boolean. thank you!

Comment (toyamagu-2021) [reply workflow/controller/operator.go:3989]: I'm inclining to implement `NodeStatus.Retried` (bool) for future expansion.
What do you think on keeping the `Hooked` field? We could delete `Hooked` if we add `Retried` field to resolve this issue.
Or you would like to keep `Hooked` field for clarification?

Just FYI:

I've added that line(3981) for retrying `Hooked` node where all `Retry` Node children are marked as `Hooked`.
I can write a comment on this, but `Retried` NodeStatus should be more clear and extensive.

image

<details>
<summary>sample yaml</summary>

```yaml
spec:
  templates:
    - name: argosay
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - /bin/sleep 2; exit 100; /argosay
        resources: {}
      retryStrategy:
        limit: 2
    - name: argosay2
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - /bin/sh
          - '-c'
        args:
          - sleep 2; exit 0
        resources: {}
  entrypoint: argosay2
  arguments: {}
  hooks:
    failed:
      template: argosay
      arguments: {}
      expression: workflow.status == "Failed"
    running:
      template: argosay
      arguments: {}
      expression: workflow.status == "Running"
    succeed:
      template: argosay
      arguments: {}
      expression: workflow.status == "Succeeded"
```

</details>

Comment (toyamagu-2021) [reply workflow/controller/operator.go:3988]: I should fix some unit tests, but added `NodeStatus.NodeFlag` to clarify node is hooked, retried, etc.
[`b0d7e6d` (#11839)](https://github.com/argoproj/argo-workflows/pull/11839/commits/b0d7e6d26d544fb3575633ad83f7d5c823d10ed7#diff-94d0f1284fafd0a1cb05dc2309b4be043b6fb01d66626ab1867d40c84b573ec2https)

I hope you like this idea :).

Comment (juliev0) [reply workflow/controller/operator.go:3988]: great, thanks so much for reworking this a few times! I think `NodeFlag` is good. :)

Comment (toyamagu-2021) [reply workflow/controller/operator.go:3976]: I've fixed some unit tests and e2e tests.
And added a description in PR for a complicated case we have discussed.
Kindly review them :).

File: workflow/controller/operator.go [hunk 9]
```diff
@@ -1765,14 +1775,17 @@ type executeTemplateOpts struct {
...
 }
 
 // executeTemplate executes the template with the given arguments and returns the created NodeStatus
 // for the created node (if created). Nodes may not be created if parallelism or deadline exceeded.
 // nodeName is the name to be used as the name of the node, and boundaryID indicates which template
 // boundary this node belongs to.
 func (woc *wfOperationCtx) executeTemplate(ctx context.Context, nodeName string, orgTmpl wfv1.TemplateReferenceHolder, tmplCtx *templateresolution.Context, args wfv1.Arguments, opts *executeTemplateOpts) (*wfv1.NodeStatus, error) {
-	woc.log.Debugf("Evaluating node %s: template: %s, boundaryID: %s", nodeName, common.GetTemplateHolderString(orgTmpl), opts.boundaryID)
+	//woc.log.Debugf("Evaluating node %s: template: %s, boundaryID: %s", nodeName, common.GetTemplateHolderString(orgTmpl), opts.boundaryID)
+	woc.log.Infof("Evaluating node %s: template: %s, boundaryID: %s, recursion: %d", nodeName, common.GetTemplateHolderString(orgTmpl), opts.boundaryID, woc.currentStackDepth)
```
Comment (juliev0) [inline workflow/controller/operator.go:1788]: delete old comment?

Comment (toyamagu-2021) [reply workflow/controller/operator.go]: Great catch. Simply forgotten...

**Review by juliev0 — APPROVED** [review]
