### PR TITLE
fix: Fixed memoization is unchecked after mutex synchronization. Fixes #11219

### LINKED ISSUE #11219: Mutex check happens after memoization cache check and lock info missing from UI
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When using both memoize and mutex in a template, the cache check happens prior to the mutex check and the UI does not show any information about the job waiting for a lock to be released.

If I have a long running template and multiple workflows run it, I was expecting the other workflows to wait for the cached result behind the lock before even starting, it appears the behaviour is that all workflows will all check cache in parallel for a cache-hit: NO and then proceed to run consecutively. Both in the UI and CLI, the information about the job waiting for a lock is missing.

Example workflow simplified to include two jobs but the same issue happens when multiple workflows use the template.

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-steps-simple
spec:
  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: job-1
            template: sleep
            arguments:
              parameters:
                - name: sleep_duration
                  value: 30
          - name: job-2
            template: sleep
            arguments:
              parameters:
                - name: sleep_duration
                  value: 15

    - name: sleep
      synchronization:
        mutex:
          name: mutex-example-steps-simple
      inputs:
        parameters:
          - name: sleep_duration
      script:
        image: alpine:latest
        command: [/bin/sh]
        source: |
          echo "Sleeping for {{ inputs.parameters.sleep_duration }}"
          sleep {{ inputs.parameters.sleep_duration }}
      memoize:
        key: "memo-key-5"
        cache:
          configMap:
            name: cache-example-steps-simple
```

### Logs from the workflow controller

```text
time="2023-06-15T13:17:42.050Z" level=info msg="Processing workflow" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.156Z" level=info msg="Updated phase  -> Running" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.156Z" level=info msg="Steps node example-steps-simple4xnjt initialized Running" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.156Z" level=info msg="StepGroup node example-steps-simple4xnjt-3033033798 initialized Running" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.305Z" level=info msg="Pod node example-steps-simple4xnjt-3810396681 initialized Pending" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.305Z" level=info msg="ci-workflows/Mutex/mutex-example-steps-simple acquired by ci-workflows/example-steps-simple4xnjt/example-steps-simple4xnjt-3810396681. Lock availability: 0/1" mutex=ci-workflows/Mutex/mutex-example-steps-simple
time="2023-06-15T13:17:42.305Z" level=info msg="Node example-steps-simple4xnjt[0].job-1 acquired synchronization lock" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.417Z" level=info msg="Created pod: example-steps-simple4xnjt[0].job-1 (example-steps-simple4xnjt-sleep-3810396681)" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.503Z" level=info msg="Pod node example-steps-simple4xnjt-3760063824 initialized Pending" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.503Z" level=info msg="Workflow step group node example-steps-simple4xnjt-3033033798 not yet completed" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.503Z" level=info msg="TaskSet Reconciliation" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.503Z" level=info msg=reconcileAgentPod namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:42.511Z" level=info msg="Workflow update successful" namespace=ci-workflows phase=Running resourceVersion=435875605 workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.418Z" level=info msg="Processing workflow" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.419Z" level=info msg="Task-result reconciliation" namespace=ci-workflows numObjs=0 workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.419Z" level=info msg="node changed" namespace=ci-workflows new.message= new.phase=Running new.progress=0/1 nodeID=example-steps-simple4xnjt-3810396681 old.message= old.phase=Pending old.progress=0/1 workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.419Z" level=info msg="Workflow pod is missing" namespace=ci-workflows nodeName="example-steps-simple4xnjt[0].job-2" nodePhase=Pending recentlyStarted=false workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.419Z" level=info msg="Node example-steps-simple4xnjt[0].job-1 acquired synchronization lock" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.420Z" level=info msg="Workflow step group node example-steps-simple4xnjt-3033033798 not yet completed" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.420Z" level=info msg="TaskSet Reconciliation" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.420Z" level=info msg=reconcileAgentPod namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:17:52.430Z" level=info msg="Workflow update successful" namespace=ci-workflows phase=Running resourceVersion=435876641 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.602Z" level=info msg="Processing workflow" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.603Z" level=info msg="Task-result reconciliation" namespace=ci-workflows numObjs=1 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.603Z" level=info msg="task-result changed" namespace=ci-workflows nodeID=example-steps-simple4xnjt-3810396681 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.603Z" level=info msg="node changed" namespace=ci-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=example-steps-simple4xnjt-3810396681 old.message= old.phase=Running old.progress=0/1 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.603Z" level=info msg="Saving ConfigMap cache entry" key=memo-key-5 name=cache-example-steps-simple namespace=argo-workflows nodeId=example-steps-simple4xnjt-3810396681
time="2023-06-15T13:18:26.786Z" level=info msg="Workflow pod is missing" namespace=ci-workflows nodeName="example-steps-simple4xnjt[0].job-2" nodePhase=Pending recentlyStarted=false workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.786Z" level=info msg="Lock has been released by ci-workflows/example-steps-simple4xnjt/example-steps-simple4xnjt-3810396681. Available locks: 1" mutex=ci-workflows/Mutex/mutex-example-steps-simple
time="2023-06-15T13:18:26.787Z" level=info msg="ci-workflows/Mutex/mutex-example-steps-simple acquired by ci-workflows/example-steps-simple4xnjt/example-steps-simple4xnjt-3760063824. Lock availability: 0/1" mutex=ci-workflows/Mutex/mutex-example-steps-simple
time="2023-06-15T13:18:26.787Z" level=info msg="Node example-steps-simple4xnjt[0].job-2 acquired synchronization lock" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.893Z" level=info msg="Created pod: example-steps-simple4xnjt[0].job-2 (example-steps-simple4xnjt-sleep-3760063824)" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.893Z" level=info msg="Workflow step group node example-steps-simple4xnjt-3033033798 not yet completed" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.893Z" level=info msg="TaskSet Reconciliation" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.893Z" level=info msg=reconcileAgentPod namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:26.902Z" level=info msg="Workflow update successful" namespace=ci-workflows phase=Running resourceVersion=435879700 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.787Z" level=info msg="Processing workflow" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.788Z" level=info msg="Task-result reconciliation" namespace=ci-workflows numObjs=1 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.788Z" level=info msg="node changed" namespace=ci-workflows new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=example-steps-simple4xnjt-3760063824 old.message= old.phase=Pending old.progress=0/1 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.788Z" level=info msg="node unchanged" namespace=ci-workflows nodeID=example-steps-simple4xnjt-3810396681 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.788Z" level=info msg="Node example-steps-simple4xnjt[0].job-2 acquired synchronization lock" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.788Z" level=info msg="Workflow step group node example-steps-simple4xnjt-3033033798 not yet completed" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.788Z" level=info msg="TaskSet Reconciliation" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.788Z" level=info msg=reconcileAgentPod namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:27.798Z" level=info msg="Workflow update successful" namespace=ci-workflows phase=Running resourceVersion=435879775 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.813Z" level=info msg="Processing workflow" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.814Z" level=info msg="Task-result reconciliation" namespace=ci-workflows numObjs=1 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.814Z" level=info msg="node changed" namespace=ci-workflows new.message= new.phase=Running new.progress=0/1 nodeID=example-steps-simple4xnjt-3760063824 old.message= old.phase=Pending old.progress=0/1 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.814Z" level=info msg="node unchanged" namespace=ci-workflows nodeID=example-steps-simple4xnjt-3810396681 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.815Z" level=info msg="Node example-steps-simple4xnjt[0].job-2 acquired synchronization lock" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.815Z" level=info msg="Workflow step group node example-steps-simple4xnjt-3033033798 not yet completed" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.815Z" level=info msg="TaskSet Reconciliation" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.815Z" level=info msg=reconcileAgentPod namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:37.826Z" level=info msg="Workflow update successful" namespace=ci-workflows phase=Running resourceVersion=435880541 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.606Z" level=info msg="Processing workflow" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.607Z" level=info msg="Task-result reconciliation" namespace=ci-workflows numObjs=2 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.607Z" level=info msg="task-result changed" namespace=ci-workflows nodeID=example-steps-simple4xnjt-3760063824 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.607Z" level=info msg="node changed" namespace=ci-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=example-steps-simple4xnjt-3760063824 old.message= old.phase=Running old.progress=0/1 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.607Z" level=info msg="Saving ConfigMap cache entry" key=memo-key-5 name=cache-example-steps-simple namespace=argo-workflows nodeId=example-steps-simple4xnjt-3760063824
time="2023-06-15T13:18:54.617Z" level=info msg="node unchanged" namespace=ci-workflows nodeID=example-steps-simple4xnjt-3810396681 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Lock has been released by ci-workflows/example-steps-simple4xnjt/example-steps-simple4xnjt-3760063824. Available locks: 1" mutex=ci-workflows/Mutex/mutex-example-steps-simple
time="2023-06-15T13:18:54.618Z" level=info msg="Step group node example-steps-simple4xnjt-3033033798 successful" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="node example-steps-simple4xnjt-3033033798 phase Running -> Succeeded" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="node example-steps-simple4xnjt-3033033798 finished: 2023-06-15 13:18:54.618227534 +0000 UTC" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Outbound nodes of example-steps-simple4xnjt-3810396681 is [example-steps-simple4xnjt-3810396681]" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Outbound nodes of example-steps-simple4xnjt-3760063824 is [example-steps-simple4xnjt-3760063824]" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Outbound nodes of example-steps-simple4xnjt is [example-steps-simple4xnjt-3810396681 example-steps-simple4xnjt-3760063824]" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="node example-steps-simple4xnjt phase Running -> Succeeded" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="node example-steps-simple4xnjt finished: 2023-06-15 13:18:54.618324516 +0000 UTC" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Checking daemoned children of example-steps-simple4xnjt" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="TaskSet Reconciliation" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg=reconcileAgentPod namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Updated phase Running -> Succeeded" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Marking workflow completed" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Marking workflow as pending archiving" namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Checking daemoned children of " namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.618Z" level=info msg="Released all acquired locks" key=example-steps-simple4xnjt namespace=ci-workflows workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:54.624Z" level=info msg="cleaning up pod" action=deletePod key=ci-workflows/example-steps-simple4xnjt-1340600742-agent/deletePod
time="2023-06-15T13:18:54.625Z" level=info msg="Workflow update successful" namespace=ci-workflows phase=Succeeded resourceVersion=435881554 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:59.014Z" level=info msg="archiving workflow" namespace=ci-workflows uid=f9c8ed34-d088-43c4-a421-6317321ab8b3 workflow=example-steps-simple4xnjt
time="2023-06-15T13:18:59.414Z" level=info msg="Queueing Succeeded workflow ci-workflows/example-steps-simple4xnjt for delete in 59m55s due to TTL"
time="2023-06-15T13:19:04.015Z" level=info msg="cleaning up pod" action=deletePod key=ci-workflows/example-steps-simple4xnjt-sleep-3760063824/deletePod
time="2023-06-15T13:19:04.015Z" level=info msg="cleaning up pod" action=deletePod key=ci-workflows/example-steps-simple4xnjt-sleep-3810396681/deletePod
```

### Logs from in your workflow's wait container

```text
time="2023-06-15T13:17:45 UTC" level=info msg="Starting Workflow Executor" version=untagged
time="2023-06-15T13:17:45 UTC" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-06-15T13:17:45 UTC" level=info msg="Executor initialized" deadline="2023-06-15 14:17:42 +0000 UTC" includeScriptOutput=false namespace=ci-workflows podName=example-step
s-simple4xnjt-sleep-3810396681 template="{\"name\":\"sleep\",\"inputs\":{\"parameters\":[{\"name\":\"sleep_duration\",\"value\":\"30\"}]},\"outputs\":{},\"metadata\":{},\"script\"
:{\"name\":\"\",\"image\":\"alpine:latest\",\"command\":[\"/bin/sh\"],\"resources\":{},\"source\":\"echo \\\"Sleeping for 30\\\"\\nsleep 30\\n\"},\"archiveLocation\":{\"archiveLog
s\":true,\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"argo-workflows-artifacts-infrastructure-production\",\"region\":\"us-east-1\",\"insecure\":false,\"useSDKCreds\":tr
ue,\"key\":\"example-steps-simple4xnjt/example-steps-simple4xnjt-sleep-3810396681\"}},\"activeDeadlineSeconds\":1800,\"synchronization\":{\"mutex\":{\"name\":\"mutex-example-steps
-simple\"}},\"memoize\":{\"key\":\"memo-key-5\",\"cache\":{\"configMap\":{\"name\":\"cache-example-steps-simple\",\"key\":\"\"}},\"maxAge\":\"\"},\"timeout\":\"45m\"}" version="&V
ersion{Version:untagged,BuildDate:2023-06-13T00:26:22Z,GitCommit:bc457cae6a431461f858e2a2f953fbb16af43a8f,GitTag:untagged,GitTreeState:clean,GoVersion:go1.20.4,Compiler:gc,Platfor
m:linux/amd64,}"
time="2023-06-15T13:17:45 UTC" level=info msg="Starting deadline monitor"
time="2023-06-15T13:18:16 UTC" level=info msg="Main container completed" error="<nil>"
time="2023-06-15T13:18:16 UTC" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-06-15T13:18:16 UTC" level=info msg="No output parameters"
time="2023-06-15T13:18:16 UTC" level=info msg="No output artifacts"
time="2023-06-15T13:18:16 UTC" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: example-steps-simple4xnjt/example-steps-simple4xnjt-sleep-3810396681/main.log"
time="2023-06-15T13:18:16 UTC" level=info msg="Creating minio client using AWS SDK credentials"
time="2023-06-15T13:18:16 UTC" level=info msg="Saving file to s3" bucket=argo-workflows-artifacts-infrastructure-production endpoint=s3.amazonaws.com key=example-steps-simple4xnjt
/example-steps-simple4xnjt-sleep-3810396681/main.log path=/tmp/argo/outputs/logs/main.log
time="2023-06-15T13:18:16 UTC" level=info msg="Save artifact" artifactName=main-logs duration=93.346992ms error="<nil>" key=example-steps-simple4xnjt/example-steps-simple4xnjt-sle
ep-3810396681/main.log
time="2023-06-15T13:18:16 UTC" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2023-06-15T13:18:16 UTC" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2023-06-15T13:18:16 UTC" level=info msg="Create workflowtaskresults 201"
time="2023-06-15T13:18:16 UTC" level=info msg="Alloc=11816 TotalAlloc=20511 Sys=44157 NumGC=5 Goroutines=10"
time="2023-06-15T13:18:16 UTC" level=info msg="Deadline monitor stopped"
time="2023-06-15T13:18:16 UTC" level=info msg="stopping progress monitor (context done)" error="context canceled"
```

### PR DESCRIPTION
**Pull request by shmruin**
Fixes #11219 

### Motivation

As it is described in issue #11219 , currently when using [Mutex](https://argoproj.github.io/argo-workflows/executor_swagger/#mutex) synchronization with [Memoization](https://argoproj.github.io/argo-workflows/fields/#memoize) cache, it seems working not correctly.
When running like the example in verification, two jobs related to same mutex and memozation works like this.

* job-1 runs first (acquire the key)
* when job-1 runs end, job-2 runs after that (no matter what memoization is)

**This means mutex synchronization is OK but memoization cache doesn't have an effect.**
However, the correct way I think how it works to be is,

* job-1 runs first, and write the memoization cache.
* when job-1 runs end, job-2 trys to run (acquire the key), but check the memoization.
* as memoization cache already be written, job-2 just succeed and completed immediately.

I think in this way, mutex will be more usable with memoization.

### Modifications

**I just change the order of check & update/initialize logic in `executeTemplate` in `operator.go`**
Currently it works like below.

1. Check if node is NIL and using memoization, and if so, initialize the nodes with memoization features on them.
2. Check if synchronization is added, if so, mark lock/unlock to the node. which is related to synchronization managing.

This is why memoization cache never set to 'NO' to all nodes when mutex is applied.
Two (or can be more) nodes sharing same mutex key will pass the memoization check stage, which is of course not hit, and waiting for key acquired at the next synchronization checking stage.
When acquiring or waiting for the key, the are already initialized with memoization as not hit.

I twisted this behaviour to check synchronization first and then memoization. When synchronization is applied, and when it acquires the key, it goes down to the memoization check logic if the template own it.

스크린샷 2023-07-27 오전 3 32 40
스크린샷 2023-07-27 오전 3 33 02

### Verification

I added a test in `operator_concurrency_test.go` or you can check it with the case below.
Mutex synchronization should work and memoization of job-1 is NO and job-2 is YES, which immediately make job-2 as succeed.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-steps-simple
spec:
  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: job-1
            template: sleep
            arguments:
              parameters:
                - name: sleep_duration
                  value: 30
          - name: job-2
            template: sleep
            arguments:
              parameters:
                - name: sleep_duration
                  value: 15

    - name: sleep
      synchronization:
        mutex:
          name: mutex-example-steps-simple
      inputs:
        parameters:
          - name: sleep_duration
      script:
        image: alpine:latest
        command: [/bin/sh]
        source: |
          echo "Sleeping for {{ inputs.parameters.sleep_duration }}"
          sleep {{ inputs.parameters.sleep_duration }}
      memoize:
        key: "memo-key-1"
        cache:
          configMap:
            name: cache-example-steps-simple
```

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1906,16 +1862,79 @@ func (woc *wfOperationCtx) executeTemplate(ctx context.Context, nodeName string,
...
+			unlockedNode = true
 		}
 
 		woc.updated = woc.updated || wfUpdated
 	}
+
+	// If memoization is on, check if node output exists in cache
+	if processedTmpl.Memoize != nil {
+		// Apply memoize only when node is nil or node is using synchronization (mutex) that acquiring the lock.
+		// This additional condition will make the cache correctly works after synchronization.\
```
Comment (juliev0) [inline workflow/controller/operator.go:1882]: I'm thinking maybe modify the comment to something like:
`// Check memoization cache if the node is about to be created, or was created in the past but is only now allowed to run due to acquiring a lock`
What do you think?

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -2366,6 +2385,30 @@ func (woc *wfOperationCtx) initializeNode(nodeName string, nodeType wfv1.NodeTyp
...
 
+// Update a node status that has been cached and marked as finished
+func (woc *wfOperationCtx) updateAsCacheNode(node *wfv1.NodeStatus, memStat *wfv1.MemoizationStatus) *wfv1.NodeStatus {
+	node.MemoizationStatus = memStat
+
+	woc.wf.Status.Nodes[node.ID] = *node
+	woc.updated = true
+
+	return node
+}
```
Comment (juliev0) [inline workflow/controller/operator.go:2396]: I notice this function has the same comment as the one below - is it right?

Comment (shmruin) [reply workflow/controller/operator.go:2396]: My mistake. for `updateAsCacheNode`, I think `Update a node status with cache status` comment is proper.

File: workflow/controller/operator.go [hunk 3]
```diff
@@ -2387,6 +2404,30 @@ func (woc *wfOperationCtx) initializeNode(nodeName string, nodeType wfv1.NodeTyp
...
+	node.Outputs = outputs
+	node.FinishedAt = metav1.Time{Time: time.Now().UTC()}
+	node.MemoizationStatus = memStat
+
+	woc.wf.Status.Nodes[node.ID] = *node
+	woc.log.Infof("%s node %v updated %s%s", node.Type, node.ID, node.Phase, message)
+	woc.updated = true
+
+	return node
+}
```
Comment (juliev0) [inline workflow/controller/operator.go:2429]: nitpick: I wonder if we could call `updateAsCacheNode()` from here? It looks like all of the functionality of that is in here. What do you think?

File: workflow/controller/operator.go [hunk 4]
```diff
@@ -1922,10 +1879,70 @@ func (woc *wfOperationCtx) executeTemplate(ctx context.Context, nodeName string,
...
 	}
+
+	// Check memoization cache if the node is about to be created, or was created in the past but is only now allowed to run due to acquiring a lock
+	if processedTmpl.Memoize != nil {
+		if node == nil || unlockedNode {
+			memoizationCache := woc.controller.cacheFactory.GetCache(controllercache.ConfigMapCache, processedTmpl.Memoize.Cache.ConfigMap.Name)
+			if memoizationCache == nil {
+				woc.log.WithFields(log.Fields{"cacheName": processedTmpl.Memoize.Cache.ConfigMap.Name}).WithError(err)
+				return woc.initializeNodeOrMarkError(node, nodeName, templateScope, orgTmpl, opts.boundaryID, err), err
+			}
```
Comment (juliev0) [inline workflow/controller/operator.go:1896]: I noticed this line in the original code: `err := fmt.Errorf("cache could not be found or created")`
Was that removed on purpose?

File: workflow/controller/operator.go [hunk 5]
```diff
@@ -1912,6 +1868,7 @@ func (woc *wfOperationCtx) executeTemplate(ctx context.Context, nodeName string,
 				// unexpected behavior and is a bug.
 				panic("bug: GetLockName should not return an error after a call to TryAcquire")
 			}
+			woc.log.Infof("Not Acquire lockname: %s", lockName)
```
Comment (Joibel) [inline workflow/controller/operator.go:1871]: Suggestion: "Could not acquire lock named: %s".

File: workflow/controller/operator.go [hunk 6]
```diff
@@ -1922,10 +1879,70 @@ func (woc *wfOperationCtx) executeTemplate(ctx context.Context, nodeName string,
 					return nil, err
 				}
 			}
+			// Set this value to check that this node is using synchronization, and acquire the lock.
```
Comment (Joibel) [inline workflow/controller/operator.go:1882]: Suggestion: "and has acquired the lock"

File: workflow/controller/operator.go (hunk 4 above)
Comment (Joibel) [reply workflow/controller/operator.go:1896]: Good catch @juliev0. It needs to go back in (or something similar), otherwise `err` used on new line 1894 and 1895 will be from somewhere else (1802 probably).

File: workflow/controller/operator.go [hunk 7]
```diff
@@ -2387,6 +2404,30 @@ func (woc *wfOperationCtx) initializeNode(nodeName string, nodeType wfv1.NodeTyp
 	return &node
 }
 
+// Update a node status with cache status
+func (woc *wfOperationCtx) updateAsCacheNode(node *wfv1.NodeStatus, memStat *wfv1.MemoizationStatus) *wfv1.NodeStatus {
+	node.MemoizationStatus = memStat
+
+	woc.wf.Status.Nodes[node.ID] = *node
```
Comment (Joibel) [inline workflow/controller/operator.go:2411]: This should use `woc.wf.Status.Nodes.Set` instead. It was introduced super recently in https://github.com/argoproj/argo-workflows/pull/11451

File: workflow/controller/operator.go [hunk 8]
```diff
@@ -2387,6 +2404,30 @@ func (woc *wfOperationCtx) initializeNode(nodeName string, nodeType wfv1.NodeTyp
...
+}
+
+// Update a node status that has been cached and marked as finished
+func (woc *wfOperationCtx) updateAsCacheHitNode(node *wfv1.NodeStatus, outputs *wfv1.Outputs, memStat *wfv1.MemoizationStatus, message ...string) *wfv1.NodeStatus {
+	node.Phase = wfv1.NodeSucceeded
+	node.Outputs = outputs
+	node.FinishedAt = metav1.Time{Time: time.Now().UTC()}
+	node.MemoizationStatus = memStat
+
+	woc.wf.Status.Nodes[node.ID] = *node
```
Comment (Joibel) [inline workflow/controller/operator.go:2424]: Same as above, use the Set() function, or ideally do what Julie suggested.

File: workflow/controller/operator_concurrency_test.go [hunk 9]
```diff
@@ -1046,3 +1048,95 @@ func TestSynchronizationForPendingShuttingdownWfs(t *testing.T) {
...
+		switch node.DisplayName {
+		case "job-1":
+			assert.Equal(t, wfv1.NodeSucceeded, node.Phase)
+			job1CacheHit = node.MemoizationStatus.Hit
+		case "job-2":
+			assert.Equal(t, wfv1.NodeSucceeded, node.Phase)
+			job2CacheHit = node.MemoizationStatus.Hit
+		}
+	}
+	assert.False(t, job1CacheHit)
```
Comment (Joibel) [inline workflow/controller/operator_concurrency_test.go:1140]: nit: Why not just assert in the case above (line 1134), it feels more readble.

**Review by Joibel — CHANGES_REQUESTED** [review]

File: workflow/controller/operator.go (hunk 6 above)
Comment (shmruin) [reply workflow/controller/operator.go:1882]: Thanks!

File: workflow/controller/operator.go (hunk 4 above)
Comment (shmruin) [reply workflow/controller/operator.go:1896]: oops, another mistake. I'll add that line as original code does.

File: workflow/controller/operator.go (hunk 7 above)
Comment (shmruin) [reply workflow/controller/operator.go:2411]: More safety. thanks.

File: workflow/controller/operator.go (hunk 3 above)
Comment (shmruin) [reply workflow/controller/operator.go:2429]: You're right. I just try to mimic relation btw `initializeCacheNode` and `initializeCacheHitNode` but I think `updateAsCacheNode` and `updateAsCacheHitNode` is not like that. As you said I can call `updateAsCacheNode` here to apply DRY. Thanks!

File: workflow/controller/operator_concurrency_test.go (hunk 9 above)
Comment (shmruin) [reply workflow/controller/operator_concurrency_test.go:1140]: Nice catch. It seems really weird... why did I do that? :)

File: workflow/controller/operator.go (hunk 3 above)
Comment (shmruin) [reply workflow/controller/operator.go:2424]: Plus, I wanna remove the return values. I think these functions are all side-effects with updating node and no need to return something.

**Review by juliev0 — APPROVED** [review]

**Comment by juliev0** [comment]
@Joibel once you re-review and approve as well, I'll merge this

**Comment by shmruin** [comment]
@juliev0 , @Joibel , Could you merge this PR if this is OK?

**Comment by juliev0** [comment]
thanks for the contribution!
