### PR TITLE
fix: Correct default emissary bug. Fixes #7224

### LINKED ISSUE #7224: Pods stuck in running state on latest
## Summary
Pods are stuck in a perpetually running state when using the `latest` tag for a cluster wide installation. Note that I'm not getting this error when running `make start UI=true` on the master branch. Just reporting this so that any lighting demos tomorrow aren't affected.

UI view:
argo ui

## Diagnostics

K8s version: Docker Desktop

Argo Installation: https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/install.yaml

Workflow: Any sample workflow generated by the UI is resulting in the hanging pods

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>
Fixes #7224

### CODE REVIEW

File: workflow/controller/controller.go [hunk 1]
```diff
@@ -1102,10 +1102,13 @@ func (wfc *WorkflowController) GetContainerRuntimeExecutor(labels labels.Labels)
...
 	}
-	if executor == "" && wfc.containerRuntimeExecutor != "" {
+	if executor != "" {
+		return executor
+	}
+	if wfc.containerRuntimeExecutor != "" {
 		return wfc.containerRuntimeExecutor
 	}
-	return executor
+	return common.ContainerRuntimeExecutorEmissary
```
Comment (sarabala1979) [inline workflow/controller/controller.go:1111]: Can we have PNS as default? Emissary. has backward compactable issue

**Review by sarabala1979 — APPROVED** [review]
