### PR TITLE
fix: Concurrent map read and map write in agent. Fixes #9685

### LINKED ISSUE #9685: "fatal error: concurrent map read and map write" in agent
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When running many same plugin tasks in a wf at the same time, agent main container fail for "fatal error: concurrent map read and map write"

### Version

v3.3.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
dag with 100 parallel tasks
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

### Logs from in your workflow's wait container

time="2022-09-25T03:34:10.662Z" level=info msg="Starting Workflow Executor" version=v0.0.0+unknown
time="2022-09-25T03:34:10.662Z" level=info msg="loading token file for plugin" filename=/var/run/argo/aidi-job-plugin/token plugin=aidi-job-plugin
time="2022-09-25T03:34:10.663Z" level=info msg="Starting Agent" requeueTime=10s taskWorkers=16 workflow=hobot-dag-32855
time="2022-09-25T03:34:10.692Z" level=info msg="Watch workflowtasksets 200"
time="2022-09-25T03:34:10.764Z" level=info msg="TaskSet Event" event_type=ADDED workflow=hobot-dag-32855
time="2022-09-25T03:34:10.764Z" level=info msg="Processing task" nodeID=hobot-dag-32855-3844469951
time="2022-09-25T03:34:10.860Z" level=info msg="Processing task" nodeID=hobot-dag-32855-3978690903
time="2022-09-25T03:34:10.860Z" level=info msg="Processing task" nodeID=hobot-dag-32855-1864122529
time="2022-09-25T03:34:10.861Z" level=info msg="Processing task" nodeID=hobot-dag-32855-1863283886
fatal error: concurrent map read and map write

goroutine 99 [running]:
runtime.throw({0x22dd7f3, 0x0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc00061b288 sp=0xc00061b258 pc=0x434371
runtime.mapaccess2_faststr(0xc0002335e0, 0x22a3eb2, {0xc000054ba0, 0x1a})
	/usr/local/go/src/runtime/map_faststr.go:116 +0x3d4 fp=0xc00061b2f0 sp=0xc00061b288 pc=0x412a74
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:129 +0x1ad fp=0xc00061bfa8 sp=0xc00061b2f0 pc=0x1d02b4d
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent·dwrap·3()
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x36 fp=0xc00061bfe0 sp=0xc00061bfa8 pc=0x1d02896
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00061bfe8 sp=0xc00061bfe0 pc=0x464da1
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 1 [chan send]:
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent(0xc0005ef780, {0x2741190, 0xc000058030})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:112 +0xb88
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.NewAgentMainCommand.func1(0xc00023c000, {0x22a13f6, 0x0, 0x0})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/cmd/argoexec/commands/agent.go:79 +0x2c
github.com/spf13/cobra.(*Command).execute(0xc00023c000, {0x3a47ba0, 0x0, 0x0})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00019e500)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/cmd/argoexec/main.go:15 +0x25

goroutine 63 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000457280)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/go.opencensus.io/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/go.opencensus.io/stats/view/worker.go:34 +0x92

goroutine 83 [select]:
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).patchWorker(0xc0005ef780, {0x2741190, 0xc000058030}, {0x27776f0, 0xc0000e7120}, 0xc00059a420, 0x2540be400)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:170 +0x150
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:83 +0x3f4

goroutine 84 [runnable]:
github.com/sirupsen/logrus.NewEntry(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:74
github.com/sirupsen/logrus.(*Logger).newEntry(0xc0002335e0)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:100 +0x5a
github.com/sirupsen/logrus.(*Logger).WithField(0xc0002335e0, {0x22a3eb2, 0x6}, {0x1e91360, 0xc000516020})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:113 +0x78
github.com/sirupsen/logrus.WithField(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/exported.go:70
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:125 +0x17d
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 85 [semacquire]:
sync.runtime_Semacquire(0x2042c80)
	/usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x2042c80)
	/usr/local/go/src/sync/waitgroup.go:130 +0x71
encoding/json.typeEncoder.func1(0x2042c80, {0x2042c80, 0xc0004452d0, 0x30}, {0x18, 0x6f})
	/usr/local/go/src/encoding/json/encode.go:396 +0x55
encoding/json.(*encodeState).reflectValue(0xc0004e1380, {0x2042c80, 0xc0004452d0, 0x40d1e7}, {0x0, 0x30})
	/usr/local/go/src/encoding/json/encode.go:360 +0x78
encoding/json.(*encodeState).marshal(0x1fbfb40, {0x2042c80, 0xc0004452d0}, {0xf0, 0x8b})
	/usr/local/go/src/encoding/json/encode.go:332 +0xfa
encoding/json.Marshal({0x2042c80, 0xc0004452d0})
	/usr/local/go/src/encoding/json/encode.go:161 +0x45
github.com/argoproj/argo-workflows/v3/workflow/util/plugins.(*Client).Call(0xc0005ef700, {0x2741190, 0xc000058030}, {0x22b6be0, 0xc0004452c0}, {0x2042c80, 0xc0004452d0}, {0x1f45d00, time="2022-09-25T03:34:10.861Z" level=info msg="Processing task" nodeID=hobot-dag-32855-3827839427
0xc0004452c0})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/util/plugins/plugin.go:46 +0x1f4
github.com/argoproj/argo-workflows/v3/workflow/executor/plugins/rpc.(*plugin).ExecuteTemplate(0xc0005ef700, {0x2741190, 0xc000058030}, {0xc0004452a0, 0xc000960240}, 0xc000445160)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/plugins/rpc/plugin.go:25 +0x91
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).executePluginTemplate(_, {_, _}, {{0xc000ca2f88, 0x8}, {{0xc0006cbb80, 0x2, 0x4}, {0x0, 0x0, ...}}, ...}, ...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:350 +0x164
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).processTask(_, {_, _}, {{0xc000ca2f88, 0x8}, {{0xc0006cbb80, 0x2, 0x4}, {0x0, 0x0, ...}}, ...})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:233 +0x10e
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:137 +0x2b0
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 86 [runnable]:
internal/poll.(*FD).Write(0xc0000e8120, {0xc00072e3c0, 0x63, 0x9c})
	/usr/local/go/src/internal/poll/fd_unix.go:280 +0x444
os.(*File).write(...)
	/usr/local/go/src/os/file_posix.go:49
os.(*File).Write(0xc00000e020, {0xc00072e3c0, 0x203000, 0xc00010f230})
	/usr/local/go/src/os/file.go:176 +0x65
github.com/sirupsen/logrus.(*Entry).write(0xc0003fd5e0)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:286 +0x15b
github.com/sirupsen/logrus.(*Entry).log(0xc00010f5d0, 0x4, {0xc0005a9ea0, 0xf})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:251 +0x1f7
github.com/sirupsen/logrus.(*Entry).Log(0xc0003fd490, 0x4, {0xc00010f5d0, 0x1a, 0xc000445360})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Info(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:310
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:136 +0x273
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 87 [runnable]:
github.com/sirupsen/logrus.NewEntry(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:74
github.com/sirupsen/logrus.(*Logger).newEntry(0xc0002335e0)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:100 +0x5a
github.com/sirupsen/logrus.(*Logger).WithField(0xc0002335e0, {0x22a3eb2, 0x6}, {0x1e91360, 0xc00099c010})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:113 +0x78
github.com/sirupsen/logrus.WithField(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/exported.go:70
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:125 +0x17d
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 88 [runnable]:
fmt.(*pp).doPrint(0xc000624000, {0xc0009895d0, 0x1, 0x1})
	/usr/local/go/src/fmt/print.go:1149 +0x1de
fmt.Sprint({0xc0009895d0, 0x1, 0x1})
	/usr/local/go/src/fmt/print.go:249 +0x45
github.com/sirupsen/logrus.(*Entry).Log(0xc000354070, 0x4, {0xc0009895d0, 0x1a, 0xc000482070})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:293 +0x3b
github.com/sirupsen/logrus.(*Entry).Info(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:310
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:136 +0x273
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 89 [runnable]:
github.com/sirupsen/logrus.(*Entry).Dup(0xc0008b0070)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:83 +0x8d
github.com/sirupsen/logrus.(*Entry).log(0xc0007135d0, 0x4, {0xc000d92010, 0xf})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:224 +0x3c
github.com/sirupsen/logrus.(*Entry).Log(0xc0008b0070, 0x4, {0xc0007135d0, 0x1a, 0xc000d88000})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Info(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:310
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:136 +0x273
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 90 [runnable]:
github.com/sirupsen/logrus.(*Logger).WithField(0xc0002335e0, {0x22a3eb2, 0x6}, {0x1e91360, 0xc00012e000})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:112 +0x1d0
github.com/sirupsen/logrus.WithField(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/exported.go:70
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:125 +0x17d
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 91 [semacquire]:
sync.runtime_SemacquireMutex(0x0, 0x48, 0x467493)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000233610)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/sirupsen/logrus.(*MutexWrap).Lock(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:58
github.com/sirupsen/logrus.(*Entry).log(0xc0009835d0, 0x4, {0xc000c44020, 0xf})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:233 +0x10e
github.com/sirupsen/logrus.(*Entry).Log(0xc00068c150, 0x4, {0xc0009835d0, 0x1a, 0xc000c3c010})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Info(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:310
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:136 +0x273
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 92 [semacquire]:
sync.runtime_Semacquire(0x2042c80)
	/usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x2042c80)
	/usr/local/go/src/sync/waitgroup.go:130 +0x71
encoding/json.typeEncoder.func1(0x2042c80, {0x2042c80, 0xc000e0e7e0, 0x30}, {0x78, 0x78})
	/usr/local/go/src/encoding/json/encode.go:396 +0x55
encoding/json.(*encodeState).reflectValue(0xc000602680, {0x2042c80, 0xc000e0e7e0, 0x40d1e7}, {0x0, 0x30})
	/usr/local/go/src/encoding/json/encode.go:360 +0x78
encoding/json.(*encodeState).marshal(0x1fbfb40, {0x2042c80, 0xc000e0e7e0}, {0xf0, 0x4b})
	/usr/local/go/src/encoding/json/encode.go:332 +0xfa
encoding/json.Marshal({0x2042c80, 0xc000e0e7e0})
	/usr/local/go/src/encoding/json/encode.go:161 +0x45
github.com/argoproj/argo-workflows/v3/workflow/util/plugins.(*Client).Call(0xc0005ef700, {0x2741190, 0xc000058030}, {0x22b6be0, 0xc000e0e7d0}, {0x2042c80, 0xc000e0e7e0}, {0x1f45d00, 0xc000e0e7d0})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/util/plugins/plugin.go:46 +0x1f4
github.com/argoproj/argo-workflows/v3/workflow/executor/plugins/rpc.(*plugin).ExecuteTemplate(0xc0005ef700, {0x2741190, 0xc000058030}, {0xc000e0e7c0, 0xc000e15440}, 0xc000e0e750)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/plugins/rpc/plugin.go:25 +0x91
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).executePluginTemplate(_, {_, _}, {{0xc000ce25e0, 0x8}, {{0xc000ce5600, 0x2, 0x4}, {0x0, 0x0, ...}}, ...}, ...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:350 +0x164
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).processTask(_, {_, _}, {{0xc000ce25e0, 0x8}, {{0xc000ce5600, 0x2, 0x4}, {0x0, 0x0, ...}}, ...})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:233 +0x10e
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:137 +0x2b0
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 93 [semacquire]:
sync.runtime_SemacquireMutex(0x0, 0x48, 0x467493)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000233610)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/sirupsen/logrus.(*MutexWrap).Lock(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:58
github.com/sirupsen/logrus.(*Entry).log(0xc0006155d0, 0x4, {0xc000e8a010, 0xf})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:233 +0x10e
github.com/sirupsen/logrus.(*Entry).Log(0xc000e84070, 0x4, {0xc0006155d0, 0x1a, 0xc000e80010})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Info(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:310
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:136 +0x273
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 94 [semacquire]:
sync.runtime_SemacquireMutex(0x0, 0x48, 0x467493)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000233610)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/sirupsen/logrus.(*MutexWrap).Lock(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:58
github.com/sirupsen/logrus.(*Entry).log(0xc000a8f5d0, 0x4, {0xc000c44010, 0xf})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:233 +0x10e
github.com/sirupsen/logrus.(*Entry).Log(0xc00068c070, 0x4, {0xc000a8f5d0, 0x1a, 0xc000c3c000})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Info(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:310
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:136 +0x273
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 95 [semacquire]:
sync.runtime_Semacquire(0x2042c80)
	/usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x2042c80)
	/usr/local/go/src/sync/waitgroup.go:130 +0x71
encoding/json.typeEncoder.func1(0x2042c80, {0x2042c80, 0xc000e0e8a0, 0x30}, {0x78, 0x78})
	/usr/local/go/src/encoding/json/encode.go:396 +0x55
encoding/json.(*encodeState).reflectValue(0xc000603380, {0x2042c80, 0xc000e0e8a0, 0x40d1e7}, {0x0, 0x30})
	/usr/local/go/src/encoding/json/encode.go:360 +0x78
encoding/json.(*encodeState).marshal(0x1fbfb40, {0x2042c80, 0xc000e0e8a0}, {0xf0, 0xeb})
	/usr/local/go/src/encoding/json/encode.go:332 +0xfa
encoding/json.Marshal({0x2042c80, 0xc000e0e8a0})
	/usr/local/go/src/encoding/json/encode.go:161 +0x45
github.com/argoproj/argo-workflows/v3/workflow/util/plugins.(*Client).Call(0xc0005ef700, {0x2741190, 0xc000058030}, {0x22b6be0, 0xc000e0e890}, {0x2042c80, 0xc000e0e8a0}, {0x1f45d00, 0xc000e0e890})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/util/plugins/plugin.go:46 +0x1f4
github.com/argoproj/argo-workflows/v3/workflow/executor/plugins/rpc.(*plugin).ExecuteTemplate(0xc0005ef700, {0x2741190, 0xc000058030}, {0xc000e0e880, 0xc000e15680}, 0xc000e0e810)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/plugins/rpc/plugin.go:25 +0x91
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).executePluginTemplate(_, {_, _}, {{0xc000ca2f30, 0x8}, {{0xc0006cba20, 0x2, 0x4}, {0x0, 0x0, ...}}, ...}, ...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:350 +0x164
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).processTask(_, {_, _}, {{0xc000ca2f30, 0x8}, {{0xc0006cba20, 0x2, 0x4}, {0x0, 0x0, ...}}, ...})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:233 +0x10e
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:137 +0x2b0
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 96 [runnable]:
github.com/sirupsen/logrus.NewEntry(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/entry.go:74
github.com/sirupsen/logrus.(*Logger).newEntry(0xc0002335e0)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:100 +0x5a
github.com/sirupsen/logrus.(*Logger).WithField(0xc0002335e0, {0x22a3eb2, 0x6}, {0x1e91360, 0xc000e80000})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:113 +0x78
github.com/sirupsen/logrus.WithField(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/exported.go:70
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:125 +0x17d
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 97 [runnable]:
github.com/sirupsen/logrus.(*Logger).WithField(0xc0002335e0, {0x22a3eb2, 0x6}, {0x1e91360, 0xc000f80000})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/logger.go:112 +0x1d0
github.com/sirupsen/logrus.WithField(...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/github.com/sirupsen/logrus/exported.go:70
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:125 +0x17d
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 98 [runnable]:
encoding/json.typeFields({0x27a2ec0, 0x1ff68c0})
	/usr/local/go/src/encoding/json/encode.go:1316 +0x116c
encoding/json.cachedTypeFields({0x27a2ec0, 0x1ff68c0})
	/usr/local/go/src/encoding/json/encode.go:1417 +0xab
encoding/json.newStructEncoder({0x27a2ec0, 0x1ff68c0})
	/usr/local/go/src/encoding/json/encode.go:771 +0x27
encoding/json.newTypeEncoder({0x27a2ec0, 0x1ff68c0}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:451 +0x366
encoding/json.typeEncoder({0x27a2ec0, 0x1ff68c0})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.newPtrEncoder({0x27a2ec0, 0x21b9740})
	/usr/local/go/src/encoding/json/encode.go:950 +0x2c
encoding/json.newTypeEncoder({0x27a2ec0, 0x21b9740}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:459 +0x2fb
encoding/json.typeEncoder({0x27a2ec0, 0x21b9740})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.typeFields({0x27a2ec0, 0x209de00})
	/usr/local/go/src/encoding/json/encode.go:1385 +0x688
encoding/json.cachedTypeFields({0x27a2ec0, 0x209de00})
	/usr/local/go/src/encoding/json/encode.go:1417 +0xab
encoding/json.newStructEncoder({0x27a2ec0, 0x209de00})
	/usr/local/go/src/encoding/json/encode.go:771 +0x27
encoding/json.newTypeEncoder({0x27a2ec0, 0x209de00}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:451 +0x366
encoding/json.typeEncoder({0x27a2ec0, 0x209de00})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.newPtrEncoder({0x27a2ec0, 0x21b53e0})
	/usr/local/go/src/encoding/json/encode.go:950 +0x2c
encoding/json.newTypeEncoder({0x27a2ec0, 0x21b53e0}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:459 +0x2fb
encoding/json.typeEncoder({0x27a2ec0, 0x21b53e0})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.typeFields({0x27a2ec0, 0x22086a0})
	/usr/local/go/src/encoding/json/encode.go:1385 +0x688
encoding/json.cachedTypeFields({0x27a2ec0, 0x22086a0})
	/usr/local/go/src/encoding/json/encode.go:1417 +0xab
encoding/json.newStructEncoder({0x27a2ec0, 0x22086a0})
	/usr/local/go/src/encoding/json/encode.go:771 +0x27
encoding/json.newTypeEncoder({0x27a2ec0, 0x22086a0}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:451 +0x366
encoding/json.typeEncoder({0x27a2ec0, 0x22086a0})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.newArrayEncoder({0x27a2ec0, 0x1ff5ec0})
	/usr/local/go/src/encoding/json/encode.go:922 +0x2c
encoding/json.newSliceEncoder({0x27a2ec0, 0x1ff5ec0})
	/usr/local/go/src/encoding/json/encode.go:901 +0xb3
encoding/json.newTypeEncoder({0x27a2ec0, 0x1ff5ec0}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:455 +0x390
encoding/json.typeEncoder({0x27a2ec0, 0x1ff5ec0})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.typeFields({0x27a2ec0, 0x207fca0})
	/usr/local/go/src/encoding/json/encode.go:1385 +0x688
encoding/json.cachedTypeFields({0x27a2ec0, 0x207fca0})
	/usr/local/go/src/encoding/json/encode.go:1417 +0xab
encoding/json.newStructEncoder({0x27a2ec0, 0x207fca0})
	/usr/local/go/src/encoding/json/encode.go:771 +0x27
encoding/json.newTypeEncoder({0x27a2ec0, 0x207fca0}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:451 +0x366
encoding/json.typeEncoder({0x27a2ec0, 0x207fca0})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.typeFields({0x27a2ec0, 0x2293960})
	/usr/local/go/src/encoding/json/encode.go:1385 +0x688
encoding/json.cachedTypeFields({0x27a2ec0, 0x2293960})
	/usr/local/go/src/encoding/json/encode.go:1417 +0xab
encoding/json.newStructEncoder({0x27a2ec0, 0x2293960})
	/usr/local/go/src/encoding/json/encode.go:771 +0x27
encoding/json.newTypeEncoder({0x27a2ec0, 0x2293960}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:451 +0x366
encoding/json.typeEncoder({0x27a2ec0, 0x2293960})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.newPtrEncoder({0x27a2ec0, 0x2259740})
	/usr/local/go/src/encoding/json/encode.go:950 +0x2c
encoding/json.newTypeEncoder({0x27a2ec0, 0x2259740}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:459 +0x2fb
encoding/json.typeEncoder({0x27a2ec0, 0x2259740})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.typeFields({0x27a2ec0, 0x2042c80})
	/usr/local/go/src/encoding/json/encode.go:1385 +0x688
encoding/json.cachedTypeFields({0x27a2ec0, 0x2042c80})
	/usr/local/go/src/encoding/json/encode.go:1417 +0xab
encoding/json.newStructEncoder({0x27a2ec0, 0x2042c80})
	/usr/local/go/src/encoding/json/encode.go:771 +0x27
encoding/json.newTypeEncoder({0x27a2ec0, 0x2042c80}, 0x1)
	/usr/local/go/src/encoding/json/encode.go:451 +0x366
encoding/json.typeEncoder({0x27a2ec0, 0x2042c80})
	/usr/local/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.valueEncoder({0x2042c80, 0xc000cdbe00, 0x30})
	/usr/local/go/src/encoding/json/encode.go:378 +0x2f
encoding/json.(*encodeState).reflectValue(0xc000603a00, {0x2042c80, 0xc000cdbe00, 0x40d1e7}, {0x0, 0x30})
	/usr/local/go/src/encoding/json/encode.go:360 +0x4a
encoding/json.(*encodeState).marshal(0x1fbfb40, {0x2042c80, 0xc000cdbe00}, {0xf0, 0x8b})
	/usr/local/go/src/encoding/json/encode.go:332 +0xfa
encoding/json.Marshal({0x2042c80, 0xc000cdbe00})
	/usr/local/go/src/encoding/json/encode.go:161 +0x45
github.com/argoproj/argo-workflows/v3/workflow/util/plugins.(*Client).Call(0xc0005ef700, {0x2741190, 0xc000058030}, {0x22b6be0, 0xc000cdbdf0}, {0x2042c80, 0xc000cdbe00}, {0x1f45d00, 0xc000cdbdf0})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/util/plugins/plugin.go:46 +0x1f4
github.com/argoproj/argo-workflows/v3/workflow/executor/plugins/rpc.(*plugin).ExecuteTemplate(0xc0005ef700, {0x2741190, 0xc000058030}, {0xc000cdbde0, 0xc000cef200}, 0xc000cdbd70)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/plugins/rpc/plugin.go:25 +0x91
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).executePluginTemplate(_, {_, _}, {{0xc000ce21c0, 0x8}, {{0xc000ce4580, 0x2, 0x4}, {0x0, 0x0, ...}}, ...}, ...)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:350 +0x164
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).processTask(_, {_, _}, {{0xc000ce21c0, 0x8}, {{0xc000ce4580, 0x2, 0x4}, {0x0, 0x0, ...}}, ...})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:233 +0x10e
github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).taskWorker(0xc0005ef780, {0x2741190, 0xc000058030}, 0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:137 +0x2b0
created by github.com/argoproj/argo-workflows/v3/workflow/executor.(*AgentExecutor).Agent
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/workflow/executor/agent.go:85 +0x405

goroutine 116 [select]:
golang.org/x/net/http2.(*clientStream).writeRequest(0xc0001f2a80, 0xc000a95000)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/transport.go:1340 +0xaa8
golang.org/x/net/http2.(*clientStream).doRequest(0xc00059a300, 0xc00059a420)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/transport.go:1202 +0x1e
created by golang.org/x/net/http2.(*ClientConn).RoundTrip
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/transport.go:1131 +0x30f

goroutine 117 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0001f2ac8, 0x2)
	/usr/local/go/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0xc000b6e000)
	/usr/local/go/src/sync/cond.go:56 +0x8c
golang.org/x/net/http2.(*pipe).Read(0xc0001f2ab0, {0xc000b0e001, 0x7dff, 0x7dff})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/pipe.go:76 +0xeb
golang.org/x/net/http2.transportResponseBody.Read({0x42efac}, {0xc000b0e001, 0xc000bafcd0, 0xc000bafcb0})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/transport.go:2401 +0x85
encoding/json.(*Decoder).refill(0xc000224c80)
	/usr/local/go/src/encoding/json/stream.go:165 +0x17f
encoding/json.(*Decoder).readValue(0xc000224c80)
	/usr/local/go/src/encoding/json/stream.go:140 +0xbb
encoding/json.(*Decoder).Decode(0xc000224c80, {0x1fa3ce0, 0xc000cf0240})
	/usr/local/go/src/encoding/json/stream.go:63 +0x78
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc00069ef30, {0xc000b6e000, 0x8000, 0xa000})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:152 +0x19c
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc0006a0460, 0xc000b80000, {0x271c548, 0xc000ca00c0})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0xa7
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc0005b0280)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x4f
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0005a45c0)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:105 +0x11c
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:76 +0x135

goroutine 115 [IO wait]:
internal/poll.runtime_pollWait(0x7fc30f8e5448, 0x72)
	/usr/local/go/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc0005ef900, 0xc0006e6000, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0005ef900, {0xc0006e6000, 0x4a8f, 0x4a8f})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0005ef900, {0xc0006e6000, 0x2a0b, 0xc0002248c0})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000388000, {0xc0006e6000, 0x6126f9, 0xc00069b7f0})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00045aed0, {0xc0006e6000, 0x0, 0x409bcd})
	/usr/local/go/src/crypto/tls/conn.go:778 +0x3d
bytes.(*Buffer).ReadFrom(0xc0001d4278, {0x26f6180, 0xc00045aed0})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0001d4000, {0x26fc540, 0xc000388000}, 0xc0006e8089)
	/usr/local/go/src/crypto/tls/conn.go:800 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0001d4000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:607 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:575
crypto/tls.(*Conn).Read(0xc0001d4000, {0xc0001dd000, 0x1000, 0xc00069bcb0})
	/usr/local/go/src/crypto/tls/conn.go:1278 +0x16f
bufio.(*Reader).Read(0xc00037d2c0, {0xc0006c0200, 0x9, 0x21ef})
	/usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x26f5e80, 0xc00037d2c0}, {0xc0006c0200, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader({0xc0006c0200, 0x9, 0xc00169efc0}, {0x26f5e80, 0xc00037d2c0})
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0006c01c0)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/frame.go:498 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00069bf98)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/transport.go:2118 +0x130
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0001f2900)
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/transport.go:2014 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/Users/yangxue.chen/code/go/src/argoproj/argo-workflows/vendor/golang.org/x/net/http2/transport.go:725 +0xac5

### PR DESCRIPTION
**Pull request by chenyangxueHDU**
Fixes #9685 

This handles concurrent map read and map write in agent

### CODE REVIEW

File: workflow/executor/agent.go [hunk 1]
```diff
@@ -41,6 +42,7 @@ type AgentExecutor struct {
 	RESTClient        rest.Interface
 	Namespace         string
 	consideredTasks   map[string]bool
+	lock              sync.RWMutex
```
Comment (alexec) [inline workflow/executor/agent.go:45]: there is a better approach, change `map[string]bool` to `sync.Map`, this does not risk programming errors

Comment (alexec) [reply workflow/executor/agent.go:45]: https://pkg.go.dev/sync#Map

Comment (chenyangxueHDU) [reply workflow/executor/agent.go:45]: ok

**Review by alexec — APPROVED** [review]
