### PR TITLE
fix: filter hook node to find the correct lastNode. Fixes: #12109

### LINKED ISSUE #12109: Can't use retryStrategy AND hooks on a step that outputs an artifact with downstream consumers
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I would expect for me to be able to use both hooks and retries on the same step.  When I use one or the other, it works.  But together, it messes up the resolution of artifacts for my downstream consumers.  The error shows on the workflow as `unable to resolve references: Unable to resolve: "steps.build.outputs.artifacts.result"`.  Additionally, the build step shows as Running but all the pods have completed or errored.

### Version

v3.5.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retries-with-hooks-and-artifact
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      when retries and hooks are both included, the workflow cannot resolve the artifact 
    workflows.argoproj.io/version: '>= 3.5.0'
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: build
            template: output-artifact
            hooks:
              started:
                expression: steps["build"].status == "Running"
                template: started
              success:
                expression: steps["build"].status == "Succeeded"
                template: success
              failed:
                expression: steps["build"].status == "Failed" || steps["build"].status == "Error"
                template: failed
        - - name: print
            template: print-artifact
            arguments:
              artifacts:
                - name: message
                  from: "{{steps.build.outputs.artifacts.result}}"
    
    - name: output-artifact
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          import time
          import random
          time.sleep(random.randint(20,40)) # lifecycle hook for running won't trigger unless it runs for more than "a few seconds"
          with open("result.txt", "w") as f:
            f.write("Welcome")
          # sys.exit("fail!")
      timeout: 30s
      retryStrategy: 
        limit: 3
      outputs:
        artifacts:
          - name: result
            path: /result.txt

    - name: started
      container:
        image: python:alpine3.6
        command: [sh, -c]
        args: ["echo STARTED!"]

    - name: success
      container:
        image: python:alpine3.6
        command: [sh, -c]
        args: ["echo SUCCEEDED!"]

    - name: failed
      container:
        image: python:alpine3.6
        command: [sh, -c]
        args: ["echo FAILED or ERROR!"]

    - name: print-artifact
      inputs:
        artifacts:
          - name: message
            path: /tmp/message
      container:
        image: python:alpine3.6
        command: [sh, -c]
        args: ["cat /tmp/message"]
```

### Logs from the workflow controller

```text
time="2023-10-30T21:00:05.483Z" level=info msg="Processing workflow" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.489Z" level=info msg="Updated phase  -> Running" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.489Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.489Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.489Z" level=info msg="Steps node retries-with-hooks-and-artifactm8mr9 initialized Running" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.489Z" level=info msg="StepGroup node retries-with-hooks-and-artifactm8mr9-1288286827 initialized Running" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.489Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.489Z" level=info msg="Retry node retries-with-hooks-and-artifactm8mr9-1973829493 initialized Running" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.489Z" level=info msg="Pod node retries-with-hooks-and-artifactm8mr9-2959657300 initialized Pending" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.505Z" level=info msg="Created pod: retries-with-hooks-and-artifactm8mr9[0].build(0) (retries-with-hooks-and-artifactm8mr9-output-artifact-2959657300)" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.506Z" level=info msg="Running hooks" hookName=started lifeCycleHook=started namespace=appanalysis-dev node="retries-with-hooks-and-artifactm8mr9[0].build.hooks.started" workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.506Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.506Z" level=info msg="Pod node retries-with-hooks-and-artifactm8mr9-2383126216 initialized Pending" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.519Z" level=info msg="Created pod: retries-with-hooks-and-artifactm8mr9[0].build.hooks.started (retries-with-hooks-and-artifactm8mr9-started-2383126216)" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.519Z" level=info msg="Workflow step group node retries-with-hooks-and-artifactm8mr9-1288286827 not yet completed" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.519Z" level=info msg="TaskSet Reconciliation" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.519Z" level=info msg=reconcileAgentPod namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:05.527Z" level=info msg="Workflow update successful" namespace=appanalysis-dev phase=Running resourceVersion=69916791 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.507Z" level=info msg="Processing workflow" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.507Z" level=info msg="Task-result reconciliation" namespace=appanalysis-dev numObjs=0 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.507Z" level=info msg="node changed" namespace=appanalysis-dev new.message= new.phase=Succeeded new.progress=0/1 nodeID=retries-with-hooks-and-artifactm8mr9-2383126216 old.message= old.phase=Pending old.progress=0/1 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.508Z" level=info msg="node changed" namespace=appanalysis-dev new.message= new.phase=Running new.progress=0/1 nodeID=retries-with-hooks-and-artifactm8mr9-2959657300 old.message= old.phase=Pending old.progress=0/1 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.508Z" level=info msg="node retries-with-hooks-and-artifactm8mr9-1973829493 phase Running -> Succeeded" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.508Z" level=info msg="node retries-with-hooks-and-artifactm8mr9-1973829493 finished: 2023-10-30 21:00:15.508423924 +0000 UTC" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.508Z" level=info msg="Running hooks" hookName=started lifeCycleHook=started namespace=appanalysis-dev node="retries-with-hooks-and-artifactm8mr9[0].build.hooks.started" workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.508Z" level=info msg="Running hooks" hookName=success lifeCycleHook=success namespace=appanalysis-dev node="retries-with-hooks-and-artifactm8mr9[0].build.hooks.success" workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.508Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.508Z" level=info msg="Pod node retries-with-hooks-and-artifactm8mr9-2102555102 initialized Pending" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.524Z" level=info msg="Created pod: retries-with-hooks-and-artifactm8mr9[0].build.hooks.success (retries-with-hooks-and-artifactm8mr9-success-2102555102)" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.524Z" level=info msg="Workflow step group node retries-with-hooks-and-artifactm8mr9-1288286827 not yet completed" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.524Z" level=info msg="TaskSet Reconciliation" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.524Z" level=info msg=reconcileAgentPod namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.533Z" level=info msg="Workflow update successful" namespace=appanalysis-dev phase=Running resourceVersion=69916945 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:15.539Z" level=info msg="cleaning up pod" action=labelPodCompleted key=appanalysis-dev/retries-with-hooks-and-artifactm8mr9-started-2383126216/labelPodCompleted
time="2023-10-30T21:00:25.523Z" level=info msg="Processing workflow" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.523Z" level=info msg="Task-result reconciliation" namespace=appanalysis-dev numObjs=0 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.523Z" level=info msg="node changed" namespace=appanalysis-dev new.message= new.phase=Succeeded new.progress=0/1 nodeID=retries-with-hooks-and-artifactm8mr9-2102555102 old.message= old.phase=Pending old.progress=0/1 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.523Z" level=info msg="node unchanged" namespace=appanalysis-dev nodeID=retries-with-hooks-and-artifactm8mr9-2959657300 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="Running hooks" hookName=started lifeCycleHook=started namespace=appanalysis-dev node="retries-with-hooks-and-artifactm8mr9[0].build.hooks.started" workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="Running hooks" hookName=success lifeCycleHook=success namespace=appanalysis-dev node="retries-with-hooks-and-artifactm8mr9[0].build.hooks.success" workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="Step group node retries-with-hooks-and-artifactm8mr9-1288286827 successful" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="node retries-with-hooks-and-artifactm8mr9-1288286827 phase Running -> Succeeded" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="node retries-with-hooks-and-artifactm8mr9-1288286827 finished: 2023-10-30 21:00:25.524383375 +0000 UTC" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="StepGroup node retries-with-hooks-and-artifactm8mr9-2429312014 initialized Running" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="SG Outbound nodes of retries-with-hooks-and-artifactm8mr9-1973829493 are [retries-with-hooks-and-artifactm8mr9-2102555102]" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=error msg="Mark error node" error="unable to resolve references: Unable to resolve: \"steps.build.outputs.artifacts.result\"" namespace=appanalysis-dev nodeName="retries-with-hooks-and-artifactm8mr9[1]" workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="node retries-with-hooks-and-artifactm8mr9-2429312014 phase Running -> Error" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="node retries-with-hooks-and-artifactm8mr9-2429312014 message: unable to resolve references: Unable to resolve: \"steps.build.outputs.artifacts.result\"" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="node retries-with-hooks-and-artifactm8mr9-2429312014 finished: 2023-10-30 21:00:25.524554118 +0000 UTC" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="step group retries-with-hooks-and-artifactm8mr9-2429312014 was unsuccessful: unable to resolve references: Unable to resolve: \"steps.build.outputs.artifacts.result\"" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="Outbound nodes of retries-with-hooks-and-artifactm8mr9 is []" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="node retries-with-hooks-and-artifactm8mr9 phase Running -> Failed" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="node retries-with-hooks-and-artifactm8mr9 message: unable to resolve references: Unable to resolve: \"steps.build.outputs.artifacts.result\"" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="node retries-with-hooks-and-artifactm8mr9 finished: 2023-10-30 21:00:25.524615435 +0000 UTC" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="TaskSet Reconciliation" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg=reconcileAgentPod namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="Updated phase Running -> Failed" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="Updated message  -> unable to resolve references: Unable to resolve: \"steps.build.outputs.artifacts.result\"" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.524Z" level=info msg="Marking workflow completed" namespace=appanalysis-dev workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.530Z" level=info msg="cleaning up pod" action=deletePod key=appanalysis-dev/retries-with-hooks-and-artifactm8mr9-1340600742-agent/deletePod
time="2023-10-30T21:00:25.537Z" level=info msg="Workflow update successful" namespace=appanalysis-dev phase=Failed resourceVersion=69917068 workflow=retries-with-hooks-and-artifactm8mr9
time="2023-10-30T21:00:25.549Z" level=info msg="cleaning up pod" action=labelPodCompleted key=appanalysis-dev/retries-with-hooks-and-artifactm8mr9-success-2102555102/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
time="2023-10-30T21:00:35.493Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-10-30T21:00:35.493Z" level=info msg="No output parameters"
time="2023-10-30T21:00:35.493Z" level=info msg="Saving output artifacts"
time="2023-10-30T21:00:35.493Z" level=info msg="Staging artifact: result"
time="2023-10-30T21:00:35.493Z" level=info msg="Copying /result.txt from container base image layer to /tmp/argo/outputs/artifacts/result.tgz"
time="2023-10-30T21:00:35.493Z" level=info msg="/var/run/argo/outputs/artifacts/result.txt.tgz -> /tmp/argo/outputs/artifacts/result.tgz"
time="2023-10-30T21:00:35.493Z" level=error msg="executor error: open /var/run/argo/outputs/artifacts/result.txt.tgz: no such file or directory"
time="2023-10-30T21:00:35.537Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:appanalysis-dev:argo-submitter\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"appanalysis-dev\""
time="2023-10-30T21:00:35.556Z" level=info msg="Alloc=9439 TotalAlloc=13839 Sys=23653 NumGC=3 Goroutines=5"
time="2023-10-30T21:00:35.556Z" level=fatal msg="open /var/run/argo/outputs/artifacts/result.txt.tgz: no such file or directory"
time="2023-10-30T21:00:09.475Z" level=info msg="Starting Workflow Executor" version=v3.5.0
time="2023-10-30T21:00:09.477Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-10-30T21:00:09.477Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=appanalysis-dev podName=retries-with-hooks-and-artifactm8mr9-started-2383126216 template="{\"name\":\"started\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"python:alpine3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo STARTED!\"],\"resources\":{}}}" version="&Version{Version:v3.5.0,BuildDate:2023-10-13T13:06:32Z,GitCommit:bf735a2e861d6b1c686dd4a076afc3468aa89c4a,GitTag:v3.5.0,GitTreeState:clean,GoVersion:go1.21.3,Compiler:gc,Platform:linux/amd64,}"
time="2023-10-30T21:00:09.478Z" level=info msg="Starting deadline monitor"
time="2023-10-30T21:00:11.478Z" level=info msg="Main container completed" error="<nil>"
time="2023-10-30T21:00:11.478Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-10-30T21:00:11.478Z" level=info msg="No output parameters"
time="2023-10-30T21:00:11.478Z" level=info msg="No output artifacts"
time="2023-10-30T21:00:11.478Z" level=info msg="Alloc=8708 TotalAlloc=12828 Sys=19301 NumGC=3 Goroutines=7"
time="2023-10-30T21:00:17.486Z" level=info msg="Starting Workflow Executor" version=v3.5.0
time="2023-10-30T21:00:17.488Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-10-30T21:00:17.488Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=appanalysis-dev podName=retries-with-hooks-and-artifactm8mr9-success-2102555102 template="{\"name\":\"success\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"python:alpine3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo SUCCEEDED!\"],\"resources\":{}}}" version="&Version{Version:v3.5.0,BuildDate:2023-10-13T13:06:32Z,GitCommit:bf735a2e861d6b1c686dd4a076afc3468aa89c4a,GitTag:v3.5.0,GitTreeState:clean,GoVersion:go1.21.3,Compiler:gc,Platform:linux/amd64,}"
time="2023-10-30T21:00:17.489Z" level=info msg="Starting deadline monitor"
time="2023-10-30T21:00:19.489Z" level=info msg="Main container completed" error="<nil>"
time="2023-10-30T21:00:19.489Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-10-30T21:00:19.489Z" level=info msg="No output parameters"
time="2023-10-30T21:00:19.489Z" level=info msg="No output artifacts"
time="2023-10-30T21:00:19.489Z" level=info msg="Alloc=8450 TotalAlloc=12809 Sys=19557 NumGC=3 Goroutines=7"
```

### PR DESCRIPTION
**Pull request by shuangkun**
Let retryStrategy AND hooks on a step works well.

Fixes #12109 

### Modifications

Filter hook node to find the correct lastNode when buildLocalScope. 
So the error
```
unable to resolve references: Unable to resolve: "steps.build.outputs.artifacts.result"
```
won't occur.

### Verification

local test and e2e.

### CODE REVIEW

File: test/e2e/hooks_test.go [hunk 1]
```diff
@@ -650,6 +650,122 @@ spec:
...
+        image: python:alpine3.6
+        command: [ python ]
+        source: |
+          import time
+          import random
+          time.sleep(random.randint(0,20)) # lifecycle hook for running won't trigger unless it runs for more than "a few seconds"
+          with open("result.txt", "w") as f:
+            f.write("Welcome")
+          # sys.exit("fail!")
+      timeout: 10s
```
Comment (tczhao) [inline test/e2e/hooks_test.go:702]: With this construct

1. the test doesn't test the original issue (resolve artifact), the test will pass with/without the code change. We need to check if workflow phase succeed.
2. there's a chance all retries timeout and never execute `print-artifact`
3. it could add ~60s to the e2e test, is there a way to reduce this?

**Review by tczhao — CHANGES_REQUESTED** [review]
I think the operator changes look good but there are issues with the added test.

File: test/e2e/cli_test.go [hunk 2]
```diff
@@ -1733,6 +1735,138 @@ func (s *CLISuite) TestPluginStruct() {
...
+    
+    - name: output-artifact
+      script:
+        image: python:alpine3.6
+        command: [ python ]
+        source: |
+          import time
+          import random
+          import sys
+          time.sleep(random.randint(0,5)) # lifecycle hook for running won't trigger unless it runs for more than "a few seconds"
```
Comment (tczhao) [inline test/e2e/cli_test.go:1786]: `random.randint(0,5)` can return 0, this is a problem
I saw other templates in hooks_test.go uses sleep(1), is that sufficient?

File: test/e2e/cli_test.go [hunk 3]
```diff
@@ -1733,6 +1735,138 @@ func (s *CLISuite) TestPluginStruct() {
...
+				}
+			}
+		}).
+		ExpectWorkflowNode(func(status wfv1.NodeStatus) bool {
+			return status.Name == "retries-with-hooks-and-artifact[0].build(0)"
+		}, func(t *testing.T, status *wfv1.NodeStatus, pod *corev1.Pod) {
+			assert.Contains(t, children, status.ID)
+			assert.Equal(t, false, status.NodeFlag.Hooked)
+		}).
+		ExpectWorkflowNode(func(status wfv1.NodeStatus) bool {
```
Comment (tczhao) [inline test/e2e/cli_test.go:1847]: I think we should add test for other hooks as well, not limited to `hooks.started`

File: test/e2e/cli_test.go [hunk 4]
```diff
@@ -1733,6 +1735,138 @@ func (s *CLISuite) TestPluginStruct() {
...
+			assert.Equal(t, wfv1.NodeSucceeded, status.Phase)
+		})
+
+	s.Run("ContainerLogs", func() {
+		s.Given().
+			RunCli([]string{"logs", workflowName, podName, "-c", "main"}, func(t *testing.T, output string, err error) {
+				if assert.NoError(t, err) {
+					assert.Contains(t, output, "Welcome")
+				}
+			})
```
Comment (tczhao) [inline test/e2e/cli_test.go:1866]: I think we are safe to remove this, and move the test to `hooks_test.go`
Your other tests are sufficient without the need to explicitly checking container stdout

**Review by tczhao — CHANGES_REQUESTED** [review]

**Review by tczhao — APPROVED** [review]
LGTM

File: workflow/controller/operator.go [hunk 5]
```diff
@@ -1764,7 +1764,15 @@ func (woc *wfOperationCtx) deletePVCs(ctx context.Context) error {
...
-		return getChildNodeIndex(node, woc.wf.Status.Nodes, -1)
+		for i := len(node.Children) - 1; i >= 0; i-- {
+			childNode := getChildNodeIndex(node, woc.wf.Status.Nodes, i)
+			if childNode == nil {
+				continue
+			}
+			if childNode.NodeFlag == nil || !childNode.NodeFlag.Hooked {
+				return childNode
+			}
+		}
```
Comment (juliev0) [inline workflow/controller/operator.go:1775]: So, it looks like you're trying to get the last child node that's not hooked, right? Can you add a comment?

**Comment by juliev0** [comment]
I see `possiblyGetRetryChildNode()` gets called in 3 places. Want to make sure your change should apply to all 3, right?

**Comment by shuangkun** [comment]
> I see `possiblyGetRetryChildNode()` gets called in 3 places. Want to make sure your change should apply to all 3, right?

Yes, all places need to find correct last child node.

**Review by juliev0 — APPROVED** [review]

**Comment by agilgur5** [comment]
Backported cleanly to `release-3.5` as 3d0648893
