### PR TITLE
fix: allow artifact gc to delete directory. Fixes #12857

### LINKED ISSUE #12857: artifactGC does not run when the output artifact uses `archive: none`
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

If I use an output artifact with `archive: none: {}` and `artifactGC`, then the artifacts are not deleted with the error: 

```
Artifact Garbage Collection failed for strategy OnWorkflowCompletion, err:The specified key does not exist.
```

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifactgc-test
spec:
  entrypoint: entrypoint
  arguments:
    parameters:
      - name: service-account
        value: 'data-manager-workflows' # an existing service account
  serviceAccountName: data-manager-workflows
  templates:
    - name: entrypoint
      dag:
        tasks:
          - name: generate-task-without-archiving
            template: generate-task-without-archiving

    - name: generate-task-without-archiving
      script:
        image: alpine:latest
        command: [ "sh", "-e" ]
        source: |
          echo "test message" > /opt/hello-world.txt
          md5sum /opt/*
      outputs:
        artifacts:
          - name: collected-artifacts
            path: /opt/
            archive: { none: { } }
            artifactGC:
              strategy: OnWorkflowCompletion
              serviceAccountName: "{{workflow.parameters.service-account}}"
            s3:
              key: fanout/collected-other-datasets/{{workflow.name}}/
              bucket: "io-realcity-apps-demo-mars-test-data"
              endpoint: "storage.googleapis.com"
              accessKeySecret:
                name: "s3-credentials"
                key: "accesskey"
              secretKeySecret:
                name: "s3-credentials"
                key: "secretkey"
```

### Logs from the garbage collection pod

```text
❯ kubectl logs -n demo-mars --context rc-test artifactgc-test7m7pm-artgc-wfcomp-3448090692 
time="2024-03-28T15:43:27.994Z" level=info msg="S3 Delete artifact: key: fanout/collected-other-datasets/artifactgc-test7m7pm/"
time="2024-03-28T15:43:28.094Z" level=info msg="Creating minio client using static credentials" endpoint=storage.googleapis.com
time="2024-03-28T15:43:28.095Z" level=info msg="Deleting object from s3" bucket=io-realcity-apps-demo-mars-test-data endpoint=storage.googleapis.com key=fanout/collected-other-datasets/artifactgc-test7m7pm/
time="2024-03-28T15:43:28.324Z" level=warning msg="Non-transient error: The specified key does not exist."
time="2024-03-28T15:43:28.388Z" level=info msg="S3 Delete artifact: key: fanout/collected-other-datasets/artifactgc-test7m7pm/"
time="2024-03-28T15:43:28.394Z" level=info msg="Creating minio client using static credentials" endpoint=storage.googleapis.com
time="2024-03-28T15:43:28.488Z" level=info msg="Deleting object from s3" bucket=io-realcity-apps-demo-mars-test-data endpoint=storage.googleapis.com key=fanout/collected-other-datasets/artifactgc-test7m7pm/
time="2024-03-28T15:43:28.624Z" level=warning msg="Non-transient error: The specified key does not exist."
time="2024-03-28T15:43:28.645Z" level=info msg="S3 Delete artifact: key: fanout/collected-other-datasets/artifactgc-test7m7pm/"
time="2024-03-28T15:43:28.689Z" level=info msg="Creating minio client using static credentials" endpoint=storage.googleapis.com
time="2024-03-28T15:43:28.689Z" level=info msg="Deleting object from s3" bucket=io-realcity-apps-demo-mars-test-data endpoint=storage.googleapis.com key=fanout/collected-other-datasets/artifactgc-test7m7pm/
time="2024-03-28T15:43:28.869Z" level=warning msg="Non-transient error: The specified key does not exist."
time="2024-03-28T15:43:28.909Z" level=info msg="S3 Delete artifact: key: fanout/collected-other-datasets/artifactgc-test7m7pm/"
time="2024-03-28T15:43:28.912Z" level=info msg="Creating minio client using static credentials" endpoint=storage.googleapis.com
time="2024-03-28T15:43:28.912Z" level=info msg="Deleting object from s3" bucket=io-realcity-apps-demo-mars-test-data endpoint=storage.googleapis.com key=fanout/collected-other-datasets/artifactgc-test7m7pm/
time="2024-03-28T15:43:29.023Z" level=warning msg="Non-transient error: The specified key does not exist."
time="2024-03-28T15:43:29.103Z" level=info msg="S3 Delete artifact: key: fanout/collected-other-datasets/artifactgc-test7m7pm/"
time="2024-03-28T15:43:29.291Z" level=info msg="Creating minio client using static credentials" endpoint=storage.googleapis.com
time="2024-03-28T15:43:29.292Z" level=info msg="Deleting object from s3" bucket=io-realcity-apps-demo-mars-test-data endpoint=storage.googleapis.com key=fanout/collected-other-datasets/artifactgc-test7m7pm/
time="2024-03-28T15:43:29.446Z" level=warning msg="Non-transient error: The specified key does not exist."

```

### Logs from in your workflow's wait container

no relevant wait container. the artifact is uploaded successfully to 

```text
io-realcity-apps-demo-mars-test-data/fanout/collected-other-datasets/artifactgc-test7m7pm/hello-world.txt
```

### PR DESCRIPTION
**Pull request by tczhao**
Fixes #12857

### Motivation

We see error `The specified key does not exist` when gc artifact are not compressed and is directory

### Modifications

Determine if artifact is dir and delete accordingly (used in artifact gc)

### Verification

Test log
```
time="2024-05-25T03:16:16.108Z" level=info msg="S3 Delete artifactttt: key: fanout/collected-other-datasets/yo-test-zl4wk/"
time="2024-05-25T03:16:16.108Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-05-25T03:16:16.112Z" level=info msg="Listing directory from s3" bucket=my-bucket endpoint="minio:9000" key=fanout/collected-other-datasets/yo-test-zl4wk/
time="2024-05-25T03:16:16.113Z" level=info msg="Deleting object from s3" bucket=my-bucket endpoint="minio:9000" key=fanout/collected-other-datasets/yo-test-zl4wk/hello-world.txt
time="2024-05-25T03:16:16.115Z" level=info msg="Deleting object from s3" bucket=my-bucket endpoint="minio:9000" key=fanout/collected-other-datasets/yo-test-zl4wk/hello-world2.txt
```

### CODE REVIEW

File: workflow/artifacts/s3/s3.go [hunk 1]
```diff
@@ -180,7 +180,27 @@ func (s3Driver *ArtifactDriver) Delete(artifact *wfv1.Artifact) error {
 		if err != nil {
 			return err
 		}
-		return s3cli.Delete(artifact.S3.Bucket, artifact.S3.Key)
+
+		isDir, err := s3cli.IsDirectory(artifact.S3.Bucket, artifact.S3.Key)
+		if err != nil {
+			return fmt.Errorf("failed to test if %s is a directory: %v", artifact.S3.Key, err)
```
Comment (agilgur5) [inline workflow/artifacts/s3/s3.go:186]:
```suggestion
			return fmt.Errorf("failed checking if %s is a directory: %v", artifact.S3.Key, err)
```

the word "test" has a connotation around testing, so would be better to avoid that. I was confused by the error message myself when I first read it.

File: workflow/artifacts/s3/s3.go [hunk 2]
```diff
@@ -180,7 +180,27 @@ func (s3Driver *ArtifactDriver) Delete(artifact *wfv1.Artifact) error {
...
+				return fmt.Errorf("unable to list files in %s: %s", artifact.S3.Key, err)
+			}
+			for _, objKey := range keys {
+				err = s3cli.Delete(artifact.S3.Bucket, objKey)
+				if err != nil {
+					return err
+				}
+			}
+		}
+		return nil
```
Comment (agilgur5) [inline workflow/artifacts/s3/s3.go:203]:
```suggestion
		}
		
		keys, err := s3cli.ListDirectory(artifact.S3.Bucket, artifact.S3.Key)
		if err != nil {
			return fmt.Errorf("unable to list files in %s: %s", artifact.S3.Key, err)
		}
		for _, objKey := range keys {
			err = s3cli.Delete(artifact.S3.Bucket, objKey)
			if err != nil {
				return err
			}
		}
	}
	return nil
```

the else is unnecessary with the early return, so let's reduce nesting to reduce code complexity

see also other places where I've refactored code to reduce nesting: #11596, #12146, etc

File: workflow/artifacts/s3/s3.go [hunk 3]
```diff
@@ -180,7 +180,27 @@ func (s3Driver *ArtifactDriver) Delete(artifact *wfv1.Artifact) error {
...
-		return s3cli.Delete(artifact.S3.Bucket, artifact.S3.Key)
+
+		isDir, err := s3cli.IsDirectory(artifact.S3.Bucket, artifact.S3.Key)
+		if err != nil {
+			return fmt.Errorf("failed to test if %s is a directory: %v", artifact.S3.Key, err)
+		}
+
+		if !isDir {
+			return s3cli.Delete(artifact.S3.Bucket, artifact.S3.Key)
+		} else {
```
Comment (agilgur5) [inline workflow/artifacts/s3/s3.go:191]: this could potentially be optimized I'm thinking -- try deleting and if it doesn't work and gives the appropriate error, then proceed with the directory deletion

similar to what I did in #12974

File: workflow/artifacts/s3/s3.go [hunk 4]
```diff
@@ -180,7 +180,27 @@ func (s3Driver *ArtifactDriver) Delete(artifact *wfv1.Artifact) error {
...
+			keys, err := s3cli.ListDirectory(artifact.S3.Bucket, artifact.S3.Key)
+			if err != nil {
+				return fmt.Errorf("unable to list files in %s: %s", artifact.S3.Key, err)
+			}
+			for _, objKey := range keys {
+				err = s3cli.Delete(artifact.S3.Bucket, objKey)
```
Comment (agilgur5) [inline workflow/artifacts/s3/s3.go:197]: this can probably be parallelized.

I am also a bit concerned that for large directories this could potentially hit a rate limit or cause a lot of load, although I think in this case `archive: none` is already an edge case and a large dir would be another edge case, so potentially not necessary to think about that. though maybe should leave a comment for future reference

**Review by agilgur5 — COMMENTED** [review]
Nice work figuring out the problem and fixing it!

Left a few modifications below and some optimization suggestions

File: workflow/artifacts/s3/s3.go (hunk 3 above)
Comment (tczhao) [reply workflow/artifacts/s3/s3.go]: Make sense, the current change doubles the API calls

Comment (tczhao) [reply workflow/artifacts/s3/s3.go]: However, looking deeper I realise
For 
```
err = deleteFile
if isNotFound(err) {
    deleteDir
}
```
to work, `deleteFile` needs to return the appropriate error.
In s3, delete only adds a marker and will return `204` regardless if the key exist or not
- https://stackoverflow.com/questions/30697746/why-does-s3-deleteobject-not-fail-when-the-specified-key-doesnt-exist
- https://github.com/minio/minio-go/blob/master/api-remove.go#L198-L200

File: workflow/artifacts/s3/s3.go (hunk 4 above)
Comment (tczhao) [reply workflow/artifacts/s3/s3.go]: `	err := retry.OnError(retry.DefaultBackoff, isTransientS3Err, func() error {`
currently we have `retry.DefaultBackoff` and `isTransientS3Err` to handle the rate limit situation

File: workflow/artifacts/s3/s3.go (hunk 3 above)
Comment (tczhao) [reply workflow/artifacts/s3/s3.go]: Updated, use simple path suffix check instead of s3cli.ListDirectory to determine if the path is a directory

Comment (agilgur5) [reply workflow/artifacts/s3/s3.go]: Huh does the `/` check actually work? Great workaround if so!

File: workflow/artifacts/s3/s3.go (hunk 4 above)
Comment (agilgur5) [reply workflow/artifacts/s3/s3.go]: Ah right above this code/surrounding it, good point.

I do think this could still be parallelized, although that can be a separate PR as it seems we lack parallelization in several (most?) places for artifacts (related: #12442)

File: workflow/artifacts/s3/s3.go [hunk 5]
```diff
@@ -180,7 +181,23 @@ func (s3Driver *ArtifactDriver) Delete(artifact *wfv1.Artifact) error {
 		if err != nil {
 			return err
 		}
-		return s3cli.Delete(artifact.S3.Bucket, artifact.S3.Key)
+
+		// s3cli.IsDirectory will introduce additional api requests for simple file delete (most scenarios)
```
Comment (agilgur5) [inline workflow/artifacts/s3/s3.go:185]:
```suggestion
		// check suffix instead of s3cli.IsDirectory as it requires another request for file delete (most scenarios)
```

the comment was a bit unclear to me since it previously mentioned something that the code doesn't use. notate the used technique first, then the unused one for clarity. also simplify a bit of the rest

**Review by agilgur5 — APPROVED** [review]
LGTM if [the suffix check works](https://github.com/argoproj/argo-workflows/pull/13091#discussion_r1633914055). It might be good to have a test case as well
I'll leave it up to you if you want to do [parallelization](https://github.com/argoproj/argo-workflows/pull/13091#discussion_r1633916364) in this PR or separately

**Review by juliev0 — APPROVED** [review]

**Comment by juliev0** [comment]
@tczhao do you want to re-trigger the CI, and then it sounds like this can be merged?

**Comment by agilgur5** [comment]
CI doesn't need to be retrigerred as only the Windows tests are failing which are not required to pass

**Comment by juliev0** [comment]
> CI doesn't need to be retrigerred as only the Windows tests are failing which are not required to pass. Can just hit merge

ahh, thanks
