### PR TITLE
fix(ui): Changed placing of chat/get help button. Fixes #5817

### LINKED ISSUE #5817: UI "problem" - An overlay on top of drop down.
## Summary 

In the web UI - bottom right corner, there is a drop down to select how many workflows to be shown on a page. The "Get Help" overlay button hoovers just on top of the drop down, making it difficult to click.

It is not an error as such, more a UI problem that make it difficult to click on an option for how a page should look like.   

## Diagnostics

Using GKE - v1.18.16-gke.2100  
Argo Workflows v3.0.2 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kaaquist**
Changed placing of chat/"get help" button.  Fix #5817

Signed-off-by: Kasper Aaquist Johansen <kasperaaquist@gmail.com>
Before: https://www.dropbox.com/s/0u3f6sjzjjneygj/before.png?dl=0
After: https://www.dropbox.com/s/ymxsq97b1ckgmbf/after.png?dl=0

I have tried to align it such it is placed top middle of the drop down menu.

### CODE REVIEW

**Comment by alexec** [comment]
@kaaquist can we instead fix this by adding more padding to the workflow list page instead?

**Comment by kaaquist** [comment]
@alexec sure why not but I'm not entirely sure I get what you mean when you say _adding more padding to the workflow list_. 
Here is a picture of the before and after fix. 
before: https://www.dropbox.com/s/vnf7bxn2n9y9nmu/before-new.png?dl=0
After: https://www.dropbox.com/s/0dnewymxepnooay/after-new.png?dl=0

**Comment by alexec** [comment]
Instead of moving the chat button, why don't we add enough white space to the workflow list page to push the dropdown above the chat button.

**Comment by kaaquist** [comment]
Ok, now with padding instead. 
Before padding : https://www.dropbox.com/s/k3qb5pxkil6awh7/new_before_padding.png?dl=0
After padding : https://www.dropbox.com/s/kcnk3bve1adeyp5/new_using_padding.png?dl=0

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Error on build, please fix.

File: ui/src/app/shared/components/pagination-panel.tsx [hunk 1]
```diff
@@ -2,10 +2,13 @@ import * as React from 'react';
 import {Pagination, parseLimit} from '../pagination';
 import {WarningIcon} from './fa-icons';
 
+require('./pagination-panel-p.scss');
```
Comment (alexec) [inline ui/src/app/shared/components/pagination-panel.tsx]: not needed?

**Comment by kaaquist** [comment]
@alexec sorry ... React beginner error - forgot double brace and camel-case in the css propertie. Now it should pass all test everything.  
*Local build:*
```sh
> yarn --cwd ui build
yarn run v1.19.1
$ rm -Rf dist && NODE_ENV=production webpack -p --config ./src/app/webpack.config.js
isProd= true
Hash: c83e33511b8af9dc68ee
Version: webpack 4.35.0
Time: 109962ms
Built at: 05/27/2021 9:10:47 PM
                            Asset       Size  Chunks                    Chunk Names
        1.42f3fb2a3ec478e6f171.js    106 KiB       1  [emitted]         
    1.42f3fb2a3ec478e6f171.js.map    479 KiB       1  [emitted]         
        2.f6e0690797bdae7f3f1d.js   3.51 KiB       2  [emitted]         
    2.f6e0690797bdae7f3f1d.js.map   9.46 KiB       2  [emitted]         
 assets/favicon/favicon-16x16.png  956 bytes          [emitted]         
 assets/favicon/favicon-32x32.png   2.12 KiB          [emitted]         
       assets/favicon/favicon.ico   1.12 KiB          [emitted]         
       assets/fonts/argo-icon.eot   28.2 KiB          [emitted]         
       assets/fonts/argo-icon.svg    190 KiB          [emitted]         
       assets/fonts/argo-icon.ttf     28 KiB          [emitted]         
      assets/fonts/argo-icon.woff   16.8 KiB          [emitted]         
   assets/fonts/fa-brands-400.eot    129 KiB          [emitted]         
   assets/fonts/fa-brands-400.svg    692 KiB          [emitted]  [big]  
   assets/fonts/fa-brands-400.ttf    129 KiB          [emitted]         
  assets/fonts/fa-brands-400.woff     87 KiB          [emitted]         
 assets/fonts/fa-brands-400.woff2   74.2 KiB          [emitted]         
  assets/fonts/fa-regular-400.eot   33.6 KiB          [emitted]         
  assets/fonts/fa-regular-400.svg    141 KiB          [emitted]         
  assets/fonts/fa-regular-400.ttf   33.3 KiB          [emitted]         
 assets/fonts/fa-regular-400.woff   16.4 KiB          [emitted]         
assets/fonts/fa-regular-400.woff2   13.3 KiB          [emitted]         
    assets/fonts/fa-solid-900.eot    190 KiB          [emitted]         
    assets/fonts/fa-solid-900.svg    829 KiB          [emitted]  [big]  
    assets/fonts/fa-solid-900.ttf    189 KiB          [emitted]         
   assets/fonts/fa-solid-900.woff   96.7 KiB          [emitted]         
  assets/fonts/fa-solid-900.woff2   74.3 KiB          [emitted]         
   assets/images/Download-200.png   6.62 KiB          [emitted]         
    assets/images/Message-200.png   20.3 KiB          [emitted]         
assets/images/User-Manual-200.png     20 KiB          [emitted]         
           assets/images/logo.png   40.8 KiB          [emitted]         
    assets/jsonschema/schema.json    415 KiB          [emitted]  [big]  
 assets/openapi-spec/swagger.json    574 KiB          [emitted]  [big]  
                      codicon.ttf   55.2 KiB          [emitted]         
                 editor.worker.js    123 KiB          [emitted]         
             editor.worker.js.map    530 KiB          [emitted]         
                       index.html  547 bytes          [emitted]         
                   json.worker.js    229 KiB          [emitted]         
               json.worker.js.map   1000 KiB          [emitted]         
     main.fabe1eba768af484a7de.js   7.66 MiB       0  [emitted]  [big]  main
 main.fabe1eba768af484a7de.js.map   24.7 MiB       0  [emitted]         main
Entrypoint main [big] = main.fabe1eba768af484a7de.js main.fabe1eba768af484a7de.js.map
  [55] ./src/app/shared/services/index.ts 1.28 KiB {0} [built]
  [68] ./src/app/shared/base.ts 636 bytes {0} [built]
  [98] ./src/app/shared/utils.ts 3.52 KiB {0} [built]
 [111] ./src/app/shared/context.ts 306 bytes {0} [built]
 [119] ./node_modules/history/es/index.js + 9 modules 35.1 KiB {0} [built]
       |    10 modules
 [207] (webpack)/buildin/module.js 546 bytes {0} [built]
 [575] ./src/app/app.tsx 2.21 KiB {0} [built]
[1441] ./src/app/index.tsx 497 bytes {0} [built]
[1889] ./src/app/app-router.tsx 9.96 KiB {0} [built]
[1890] ./src/app/apidocs/index.tsx 182 bytes {0} [built]
[2578] ./src/app/archived-workflows/index.ts 260 bytes {0} [built]
[3043] ./src/app/cluster-workflow-templates/index.ts 291 bytes {0} [built]
[3050] ./src/app/cron-workflows/index.ts 244 bytes {0} [built]
[3073] ./src/app/event-flow/index.ts 232 bytes {0} [built]
[3085] ./src/app/event-sources/index.ts 240 bytes {0} [built]
    + 3187 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  main.fabe1eba768af484a7de.js (7.66 MiB)
  assets/jsonschema/schema.json (415 KiB)
  assets/openapi-spec/swagger.json (574 KiB)
  assets/fonts/fa-brands-400.svg (692 KiB)
  assets/fonts/fa-solid-900.svg (829 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (7.66 MiB)
      main.fabe1eba768af484a7de.js

Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/app/index.html 720 bytes {0} [built]
    [2] (webpack)/buildin/global.js 475 bytes {0} [built]
    [3] (webpack)/buildin/module.js 546 bytes {0} [built]
        + 1 hidden module
Child vs/editor/editor:
                   Asset     Size  Chunks             Chunk Names
        editor.worker.js  123 KiB       0  [emitted]  main
    editor.worker.js.map  530 KiB       0  [emitted]  main
    Entrypoint main = editor.worker.js editor.worker.js.map
    [1] (webpack)/buildin/global.js 475 bytes {0} [built]
    [6] ./node_modules/monaco-editor/esm/vs/editor/editor.worker.js + 31 modules 357 KiB {0} [built]
        |    32 modules
        + 5 hidden modules
Child vs/language/json/jsonWorker:
                 Asset      Size  Chunks             Chunk Names
        json.worker.js   229 KiB       0  [emitted]  main
    json.worker.js.map  1000 KiB       0  [emitted]  main
    Entrypoint main = json.worker.js json.worker.js.map
    [1] (webpack)/buildin/global.js 475 bytes {0} [built]
    [7] ./node_modules/monaco-editor/esm/vs/language/json/json.worker.js + 56 modules 669 KiB {0} [built]
        |    57 modules
        + 6 hidden modules
Done in 110.63s.
```

File: ui/src/app/shared/components/pagination-panel.tsx (hunk 1 above)
Comment (kaaquist) [reply ui/src/app/shared/components/pagination-panel.tsx]: I removed it.

**Review by alexec — APPROVED** [review]

**Comment by kaaquist** [comment]
@alexec there was a lint error. Now that is fixed and added.
