### PR TITLE
fix: Correct limit in WorkflowTaskResultInformer List API calls. Fixes #11607

### LINKED ISSUE #11607: Why are all workflowtaskresults objects listed before deleting the workflowtaskresults object
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When observing the long request in the kube-apiserver log, it was found that all workflowtaskresults objects were listed before the workflowtaskresults was deleted, which took up to 13s. I have 34,000 workflowtaskresults objects in my cluster. Is there any improvement

`
I0818 02:59:15.836968       1 trace.go:205] Trace[604122088]: "List etcd3" key:/argoproj.io/workflowtaskresults/argo-map,resourceVersion:,resourceVersionMatch:,limit:0,continue: (18-Aug-2023 02:59:02.626) (total time: 13210ms):
Trace[604122088]: [13.21006542s] [13.21006542s] END
I0818 02:59:15.844376       1 trace.go:205] Trace[41997032]: "Delete" url:/apis/argoproj.io/v1alpha1/namespaces/argo-map/workflowtaskresults,user-agent:workflow-controller/v0.0.0 (linux/amd64) kubernetes/$Format/argo-workflows/v3.4.9 argo-controller,audit-id:07d3e912-1902-4066-8bbf-2ed1282bc3ae,client:10.3.9.93,accept:application/json, */*,protocol:HTTP/2.0 (18-Aug-2023 02:59:02.626) (total time: 13217ms):
Trace[41997032]: [13.217758822s] [13.217758822s] END
I0818 02:59:16.231448       1 trace.go:205] Trace[1909717067]: "List etcd3" key:/argoproj.io/workflowtaskresults/argo-map,resourceVersion:,resourceVersionMatch:,limit:0,continue: (18-Aug-2023 02:59:02.662) (total time: 13568ms):
Trace[1909717067]: [13.568856088s] [13.568856088s] END
I0818 02:59:16.237932       1 trace.go:205] Trace[1067855512]: "Delete" url:/apis/argoproj.io/v1alpha1/namespaces/argo-map/workflowtaskresults,user-agent:workflow-controller/v0.0.0 (linux/amd64) kubernetes/$Format/argo-workflows/v3.4.9 argo-controller,audit-id:b96fbade-70de-4cde-a4a4-fc3c449f9c58,client:10.3.9.93,accept:application/json, */*,protocol:HTTP/2.0 (18-Aug-2023 02:59:02.662) (total time: 13575ms):
Trace[1067855512]: [13.575625916s] [13.575625916s] END
`

### Version

v3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

n/a
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

n/a
```

### PR DESCRIPTION
**Pull request by terrytangyuan**
Potentially fixes #11607. This seems like a similar issue that we fixed in https://github.com/argoproj/argo-workflows/pull/11343.

### CODE REVIEW

**Review by agilgur5 — APPROVED** [review]
I thought the same thing when I first saw the issue! Hadn't had a chance to look into it yet but had been looking to make at least the same change as #11343, so makes sense to me!

File: workflow/controller/taskresult.go [hunk 1]
```diff
@@ -31,6 +31,9 @@ func (wfc *WorkflowController) newWorkflowTaskResultInformer() cache.SharedIndex
 		},
 		func(options *metav1.ListOptions) {
 			options.LabelSelector = labelSelector
+			// `ResourceVersion=0` does not honor the `limit` in API calls, which results in making significant List calls
+			// without `limit`. For details, see https://github.com/argoproj/argo-workflows/pull/11343
+			options.ResourceVersion = ""
 		},
```
Comment (juliev0) [inline workflow/controller/taskresult.go:37]: Out of curiosity, where would this get set to 0 in the first place?

Comment (juliev0) [reply workflow/controller/taskresult.go:37]: and then how about `Limit`? where is that being set?

Comment (terrytangyuan) [reply workflow/controller/taskresult.go:37]: It will be set by the framework during pagination along with offset.

Comment (juliev0) [reply workflow/controller/taskresult.go:37]: Can you help clarify how the UI is enabling that to be called? I guess I'm confused because I thought that creating a `ListWatch` as is being called from `NewFilteredWorkflowTaskResultInformer()` simply performs an initial list and starts a watch on a particular resource.

Comment (juliev0) [reply workflow/controller/taskresult.go:37]: Just spoke to Anton. Sorry, I mistakenly thought when you said "pagination" that you were referring to the UI - hence my question about the UI. He clarified that this is some sort of pagination happening when the Controller is doing listing from the K8S API.

Comment (juliev0) [reply workflow/controller/taskresult.go:37]: So, I'm guessing when say that the `Limit` is being set by the framework, you are referring to the kubernetes client/informer framework, right?

Comment (terrytangyuan) [reply workflow/controller/taskresult.go:37]: Yes the informers framework.

**Review by juliev0 — APPROVED** [review]
