### PR TITLE
fix: ArtifactGC Fails for Stopped Workflows. Fixes #11879

### LINKED ISSUE #11879: Artifacts not set in Status.Nodes | ArtifactGC prevents Workflow deletion
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

This issue stems from #10840. I expect to be able to delete a workflow and have the garbage collection remove the artifact from the repository.

In this specific case, the workflow finalizer isn't removed from the workflow due to a failure [here](https://github.com/argoproj/argo-workflows/blob/d0588ea092012c36ce06f44b008dc057bdf72154/workflow/controller/artifact_gc.go#L135), implying that the artifacts aren't being written to Status.Nodes. Upon inspecting the workflow manifest's `Status.Nodes`, I can confirm that no output artifacts are listed. Artifacts are successfully being written to GCS upon triggering "stop" for the workflow.

**Steps to Reproduce**
1) Have a workflow with a long-running process
2) Stop the workflow mid-execution
3) Artifacts are written to GCS
4) Attempt to delete the workflow
5) Notice that the workflow cannot be deleted since the finalizer can't be removed & the artifacts are not deleted.

**Partial Remedy**
While preparing this ticket, I notice that by adding at least one successful workflow and artifact to my DAG (in parallel), the workflow's finalizer is successfully deleted & the successful DAG step's artifacts are also successfully cleaned up, **however**, the failed (stopped) DAG step's artifacts are not cleaned up. This can lead to dangling resources in GCS.

**Suggested Fix**
Ensure that stopped/failed workflow step's output artifacts are written to `Status.Nodes`

### Version

3.5.0-rc1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# https://argoproj.github.io/argo-workflows/cron-workflows/
# https://argoproj.github.io/argo-workflows/fields/
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: TEMP
spec:
  # Start up 5 minutes to 6 AM to ensure system is online.
  schedule: "55 5 * * *"
  timezone: America/New_York
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  # Run the workflow for 16 hours, 10 minutes (between 5:55 AM and 10:05 PM)
  activeDeadlineSeconds: 58200
  workflowSpec:
    entrypoint: test-dag
    templates:
      - name: test-dag
        dag:
          tasks:
            - name: test
              template: test
              continueOn:
                failed: true
    # Clean up artifacts https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection
    artifactGC:
      strategy: OnWorkflowDeletion
      serviceAccountName: argo-workflows-sa
      forceFinalizerRemoval: true
    # How long to keep workflows around after they have completed https://argoproj.github.io/argo-workflows/fields/#ttlstrategy
    ttlStrategy:
      # 5 minutes
      secondsAfterCompletion: 300
      secondsAfterSuccess: 300
      secondsAfterFailure: 300
    # a temporary volume, named workdir, will be used as a working directory for this workflow. This volume is passed
    # around from step to step.
    volumeClaimTemplates:
      - metadata:
          name: logs
        spec:
          accessModes: [ "ReadWriteMany" ]
          resources:
            requests:
              storage: 2.5G
    serviceAccountName: argo-workflows-sa
    templates:
      - name: test
        volumes:
          - name: logs
            emptyDir: { }
        container:
          name: test
          image: alpine:latest
          command:
            - sh
            - '-c'
          args:
            - |
              echo 'testing' > /tmp/test.txt
              while true
              do
                # loop indefinitely
                sleep 1
              done
        outputs:
          artifacts:
            - name: 'test'
              path: /tmp/test.txt
              archive:
                none: { }
              gcs:
                # https://argoproj.github.io/argo-workflows/variables/
                key: "{{workflow.name}}-{{workflow.creationTimestamp.Y}}-{{workflow.creationTimestamp.m}}-{{workflow.creationTimestamp.d}}_{{workflow.creationTimestamp.H}}-{{workflow.creationTimestamp.M}}-{{workflow.creationTimestamp.S}}/test.txt"
```

### Logs from the workflow controller

```text
time="2023-09-24T06:32:14.100Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=pipeline-dev workflow=pipeline-cron-workflow-dev-9thnn
time="2023-09-24T06:32:14.100Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=pipeline-dev workflow=pipeline-cron-workflow-dev-9thnn
time="2023-09-24T06:32:14.100Z" level=debug msg="No Artifact Search Results returned from strategy OnWorkflowDeletion" namespace=pipeline-dev workflow=pipeline-cron-workflow-dev-9thnn
time="2023-09-24T06:32:14.101Z" level=debug msg="Log changes patch: {\"status\":{\"artifactGCStatus\":{\"strategiesProcessed\":{\"OnWorkflowDeletion\":true}}}}"
time="2023-09-24T06:32:14.101Z" level=info msg="Workflow to be dehydrated" Workflow Size=4845
time="2023-09-24T06:32:14.113Z" level=debug msg="Update workflows 200"
time="2023-09-24T06:32:14.114Z" level=info msg="Workflow update successful" namespace=pipeline-dev phase=Failed resourceVersion=121464951 workflow=pipeline-cron-workflow-dev-9thnn
```

### Logs from in your workflow's wait container

```text
time="2023-09-24T06:29:25.935Z" level=info msg="Starting Workflow Executor" version=v3.5.0-rc1
time="2023-09-24T06:29:25.941Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-09-24T06:29:25.941Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=pipeline-dev podName=pipeline-cron-workflow-dev-9thnn-test-2481151211 template="{\"name\":\"test\",\"inputs\":{},\"outputs\":{\"artifacts\":[{\"name\":\"test\",\"path\":\"/tmp/test.txt\",\"gcs\":{\"key\":\"pipeline-cron-workflow-dev-9thnn-2023-09-24_06-28-19/test.txt\"},\"archive\":{\"none\":{}}}]},\"metadata\":{},\"container\":{\"name\":\"test\",\"image\":\"alpine:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo 'testing' \\u003e /tmp/test.txt\\nwhile true\\ndo\\n  # loop indefinitely\\n  sleep 1\\ndone\\n\"],\"resources\":{}},\"volumes\":[{\"name\":\"logs\",\"emptyDir\":{}}],\"archiveLocation\":{\"archiveLogs\":false,\"gcs\":{\"bucket\":\"project-workflow-artifacts\",\"key\":\"pipeline-cron-workflow-dev-9thnn/pipeline-cron-workflow-dev-9thnn-test-2481151211\"}}}" version="&Version{Version:v3.5.0-rc1,BuildDate:2023-08-15T18:44:17Z,GitCommit:6cd3e810e9c953e0a78070f41ab8f7d799fe51d3,GitTag:v3.5.0-rc1,GitTreeState:clean,GoVersion:go1.20.7,Compiler:gc,Platform:linux/amd64,}"
time="2023-09-24T06:29:25.942Z" level=info msg="Starting deadline monitor"
time="2023-09-24T06:31:19.023Z" level=info msg="Main container completed" error="<nil>"
time="2023-09-24T06:31:19.040Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-09-24T06:31:19.040Z" level=info msg="No output parameters"
time="2023-09-24T06:31:19.040Z" level=info msg="Saving output artifacts"
time="2023-09-24T06:31:19.045Z" level=info msg="Deadline monitor stopped"
time="2023-09-24T06:31:19.050Z" level=info msg="Staging artifact: test"
time="2023-09-24T06:31:19.052Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2023-09-24T06:31:19.058Z" level=info msg="Copying /tmp/test.txt from container base image layer to /tmp/argo/outputs/artifacts/test.tgz"
time="2023-09-24T06:31:19.065Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/test.txt.tgz -> /tmp/argo/outputs/artifacts/test.tgz"
time="2023-09-24T06:31:19.080Z" level=info msg="Untaring /tmp/argo/outputs/artifacts/test.tgz archive before upload"
time="2023-09-24T06:31:19.105Z" level=info msg="GCS Save path: /tmp/argo/outputs/artifacts/test.txt, key: pipeline-cron-workflow-dev-9thnn-2023-09-24_06-28-19/test.txt"
time="2023-09-24T06:31:19.773Z" level=info msg="Save artifact" artifactName=test duration=668.368403ms error="<nil>" key=pipeline-cron-workflow-dev-9thnn-2023-09-24_06-28-19/test.txt
time="2023-09-24T06:31:19.773Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/test.txt
time="2023-09-24T06:31:19.773Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/test.txt"
time="2023-09-24T06:31:19.795Z" level=debug msg="Create workflowtaskresults 201"
time="2023-09-24T06:31:19.798Z" level=info msg="Alloc=26019 TotalAlloc=37269 Sys=47741 NumGC=5 Goroutines=10"
```

### PR DESCRIPTION
**Pull request by Garett-MacGowan**
Fixes #11879

### Motivation

Currently, stopped workflows will happily save artifacts to a storage bucket but the artifacts won't get garbage collected after workflow deletion. The changes make it so that a stopped workflow's artifacts are properly garbage collected upon workflow deletion.

### Modifications

The `operator.go`'s call to `woc.taskResultReconciliation()` previously occurred after Artifact Garbage Collection (`ArtifactGC`) and an early return due to `if woc.wf.Labels[common.LabelKeyCompleted] == "true"`, leading to a scenerio in which garbage collection would fail upon workflow deletion. This in turn would cause workflow deletion to get blocked by the ArtifactGC finalizer. `woc.taskResultReconciliation()` is responsible for updating the node status in the workflow based on the artifact outputs saved during workflow execution with `reportOutputs()` in `executor.go`. 

### Verification

I tested the changes by adding an `e2e` test called `TestStoppedWorkflow` which uses a custom workflow with the following logic.

1) Ensure no artifact exists in the bucket.
2) Start the workflow.
3) Workflow runs and creates a test artifact.
4) Verifiy the artifact exists in the bucket.
4) The workflow submits a CLI-based stop event for itself.
5) The workflow is deleted by the test.
6) Artifacts are verified to have been deleted.
7) Finalizer is removed incase the test failed.

---

I made some additional minor tweaks to other files, most notably, `timeout = v - 30*time.Second + defaultTimeout` in `when.go` which would cause custom timeout settings to be incorrect when using the `WaitForWorkflow()` e2e testing utility.

### CODE REVIEW

**Comment by juliev0** [comment]
> @juliev0 Could you help review when you get a chance?

Yes. It may be more than a couple of weeks from now, though, as I have a vacation followed by a Hackathon week at work. (It looks like this is still in "Draft" state as well.)

File: test/e2e/fixtures/when.go [hunk 1]
```diff
@@ -258,7 +258,7 @@ func (w *When) WaitForWorkflow(options ...interface{}) *When {
 	for _, opt := range options {
 		switch v := opt.(type) {
 		case time.Duration:
-			timeout = v - 30*time.Second + defaultTimeout
+			timeout = v
```
Comment (juliev0) [inline test/e2e/fixtures/when.go:261]: curious why you ended up changing this? Possibly you're right to. It does seem less kludgey and more intuitive than the old way, but I also see it was changed on purpose [here](https://github.com/argoproj/argo-workflows/commit/95bd1ccba0f79e0e00ac97988b59922f6af53bf2#diff-22b3b50dbaaa2bcad4a4d25afc8bacef81ca3eaac993d26192e8f91c761bed37). Looking at that PR, it seems like in the CI the `E2E_TIMEOUT` was specifically made longer than the default 30 seconds. So, there was some notion that all tests should be delayed by x amount if that environment variable is set. Of course, now I see the CI doesn't use that environment variable but instead uses something called [E2E_SUITE_TIMEOUT](https://github.com/argoproj/argo-workflows/blob/master/.github/workflows/ci-build.yaml#L162) cc @agilgur5 
In any case, I do see the `time.Duration` comment above isn't correct as far as "30s by default"

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -276,6 +266,19 @@ func (woc *wfOperationCtx) operate(ctx context.Context) {
 		woc.computeMetrics(woc.execWf.Spec.Metrics.Prometheus, localScope, realTimeScope, true)
 	}
 
+	// Reconciliation of Outputs (Artifacts). See reportOutputs() of executor.go
+	woc.taskResultReconciliation()
```
Comment (juliev0) [inline workflow/controller/operator.go:270]: I do see this will now get executed in the case of `woc.wf.Status.Phase == wfv1.WorkflowUnknown` which before it wouldn't. This may be right but want to make sure. I also like not having the `if` statement if it's unnecessary. I believe this would happen for a just submitted workflow, or it appears a [resubmitted](https://github.com/argoproj/argo-workflows/blob/master/workflow/util/util.go#L752) workflow. It does seem like this probably won't ever be harmful - if there's a WorkflowTaskResult of the same name then we probably ought to use it, right?

Comment (juliev0) [reply workflow/controller/operator.go:270]: (unless there's some weird case that a previous Workflow of the same name still had a WorkflowTaskResult lying around from before...but I believe a WorkflowTaskResult should get deleted at the same time as the Workflow it relates to)

File: workflow/controller/operator.go [hunk 3]
```diff
@@ -276,6 +266,19 @@ func (woc *wfOperationCtx) operate(ctx context.Context) {
...
+	// check to see if we can do garbage collection of Artifacts;
+	if err := woc.garbageCollectArtifacts(ctx); err != nil {
+		woc.log.WithError(err).Error("failed to GC artifacts")
+		return
+	}
+
+	if woc.wf.Labels[common.LabelKeyCompleted] == "true" { // abort now, we do not want to perform any more processing on a complete workflow because we could corrupt it
+		return
+	}
+
```
Comment (juliev0) [inline workflow/controller/operator.go:281]: doing `taskResultReconciliation()` right before garbage collecting seems like it should have an overall effect of speeding up the process of garbage collection

File: test/e2e/fixtures/when.go (hunk 1 above)
Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: I changed this because I was using different timeouts to debug my test case and I noticed it wasn't using my manually specified timeout. Subtracting 30 seconds and adding the default timeout to a manually specified value makes no sense to me.

File: workflow/controller/operator.go (hunk 2 above)
Comment (Garett-MacGowan) [reply workflow/controller/operator.go:270]: @juliev0 if I'm not mistaken, this change resolved some intermittent test failures I was receiving. I believe the issue was that artifacts could be created and garbage collected while `wfv1.WorkflowUnknown` was set. This would cause `taskReconciliation` to not run and garbage collection to fail since the node status wouldn't get updated with the artifact info.

File: workflow/controller/operator.go (hunk 3 above)
Comment (Garett-MacGowan) [reply workflow/controller/operator.go:281]: Yeah, since garbage collection should execute on the first pass through the operator loop.

File: workflow/controller/operator.go (hunk 2 above)
Comment (juliev0) [reply workflow/controller/operator.go:270]: huh - that's weird that artifacts were created and garbage collected while `wfv1.WorkflowUnknown` was set. I wonder if there could be a case of `wfv1.WorkflowUnknown` that I'm unaware of if so. Anyway, it seems to be harmless.

File: test/e2e/fixtures/when.go (hunk 1 above)
Comment (juliev0) [reply test/e2e/fixtures/when.go:261]: Here's what I'm thinking: this environment variable which used to be called `E2E_TIMEOUT` and is now called [E2E_WAIT_TIMEOUT](https://github.com/argoproj/argo-workflows/blob/master/test/e2e/fixtures/e2e_suite.go#L40) appears to be something that will allow things to run more slowly in certain environments. Is it possible to both 1. preserve the ability to run everything more slowly across the board in certain environments, and 2. have the parameters/comments be named in an intuitive way so that it's not a surprise to the caller of the function what the actual behavior is?

Comment (juliev0) [reply test/e2e/fixtures/when.go:261]: (sorry, I know this wasn't the original intention of this particular issue, but I'm thinking we shouldn't remove the intention of the `E2E_WAIT_TIMEOUT` environment variable.)

File: workflow/controller/operator.go (hunk 2 above)
Comment (Garett-MacGowan) [reply workflow/controller/operator.go:270]: Agreed. I'm not 100% on this, but as you say the change should be harmless.

File: test/e2e/fixtures/when.go (hunk 1 above)
Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: `defaultTimeout` is set [here](https://github.com/argoproj/argo-workflows/blob/8fa8f7970bfd3ccc5cff1246ea08a7771a03b8ad/test/e2e/fixtures/e2e_suite.go#L40)

```
var defaultTimeout = env.LookupEnvDurationOr("E2E_WAIT_TIMEOUT", 60*time.Second)
```

the default value for `timeout` is set to `defaultTimeout` [here](https://github.com/argoproj/argo-workflows/blob/4ffeb5f43bd1624b6b20db35f9c905b1479d4c39/test/e2e/fixtures/when.go#L251)

I think implementation in this PR is working as it should. Perhaps I'm misunderstanding your ask.

Comment (juliev0) [reply test/e2e/fixtures/when.go:261]: So, I'm thinking: there are probably multiple places where `WaitForWorkflow()` is being called and some duration is being passed into it. What if someone wants to use the `E2E_WAIT_TIMEOUT` environment variable to basically add some overall buffer to **all** tests because they're running on some slow environment? (including both tests where `WaitForWorkflow()` was passed a duration, and tests where it wasn't) It seems to me that this was the original reason why it was done this way (even if it's kludgey). If somebody set `E2E_WAIT_TIMEOUT` to 2 minutes, then the tests where `WaitForWorkflow()` is not passed a duration would timeout after 2 minutes, and the tests where it is passed a duration would also include that 2 minute lag in the calculation. 

Note: I do think that including **30 seconds** in the calculation seems odd, though.

Does it make sense what I'm saying?

Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: I see what you're saying. Maybe something like `E2E_WAIT_TIMEOUT_BIAS` so the `defaultTimeout` could be:

```
var defaultTimeout = env.LookupEnvDurationOr("E2E_WAIT_TIMEOUT", 60*time.Second) + env.LookupEnvDurationOr("E2E_WAIT_TIMEOUT_BIAS", 0*time.Second) 
```

Is this along the lines of what you are thinking?

Comment (juliev0) [reply test/e2e/fixtures/when.go:261]: yeah, something like that. Although, above where you wrote `var defaultTimeout = env.LookupEnvDurationOr("E2E_WAIT_TIMEOUT", 60*time.Second)` did you mean to write something involving "E2E_WAIT_TIMEOUT_BIAS" or `timeoutBias`?

Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: I edited my mistake.

Comment (juliev0) [reply test/e2e/fixtures/when.go:261]: What do you think if we only have "E2E_WAIT_TIMEOUT_BIAS" and then `defaultTimeout` is set to `60*time.Second + E2E_WAIT_TIMEOUT_BIAS`?

Comment (juliev0) [reply test/e2e/fixtures/when.go:261]: actually, that may not be right either - but it would be good to only have "E2E_WAIT_TIMEOUT_BIAS" if we can

Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: Sure, my only concern that 60 seconds is potentially too long?

Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: One other thing is I'm generally hesitant to change env variable names since it will be a pain for people to update.

Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: This line `timeout = v - 30*time.Second + defaultTimeout` only matters when a manual timeout value is specified. So it's basically saying "add the default timeout to the manually specified value" (ignoring the -30 which makes no sense). In this case  renaming the variable to include `bias` makes sense.

It makes less sense when it's used in the true default case `timeout := defaultTimeout`

**Comment by Garett-MacGowan** [comment]
Failing test is `RetryTestSuite/TestRetryBackoff`

File: test/e2e/fixtures/when.go (hunk 1 above)
Comment (juliev0) [reply test/e2e/fixtures/when.go:261]: What about this small modification?:

```
var timeoutBias = env.LookupEnvDurationOr("E2E_WAIT_TIMEOUT_BIAS", 0*time.Second)
var defaultTimeout = env.LookupEnvDurationOr("E2E_WAIT_TIMEOUT", 60*time.Second) + timeoutBias
```
in the method:
```
timeout := defaultTimeout
```

And then in the switch statement, you could add the bias.
```
timeout = v + timeoutBias
```

Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: Yes, this.

Comment (juliev0) [reply test/e2e/fixtures/when.go:261]: Thank you! Just thinking, if you see any of the tests which call this and pass a duration in intermittently fail, then it could possibly be that before they were getting an additional 30 seconds added on (E2E_WAIT_TIMEOUT=60 - 30). If so, could you bump up the duration passed in?

Comment (Garett-MacGowan) [reply test/e2e/fixtures/when.go:261]: Yeah, no problem.

**Comment by Garett-MacGowan** [comment]
> Failing test is `RetryTestSuite/TestRetryBackoff`

This was fixed by adding the 30s. Good catch @juliev0

**Comment by Garett-MacGowan** [comment]
Sadly my test (`TestStoppedWorkflow`) ran into the intermittent error I was receiving earlier. I'll try and debug it.

**Comment by juliev0** [comment]
> Sadly my test (`TestStoppedWorkflow`) ran into the intermittent error I was receiving earlier. I'll try and debug it.

Sorry to hear. Thank you!

**Comment by Garett-MacGowan** [comment]
@agilgur5 @juliev0

I'm having a hard time debugging this. The failure rate is like 1/30+ test runs on my local machine. The artifacts are being saved, but the task reconciliation never receives the on-deletion-wf-stopped artifact for some reason. Task reconciliation does, however, receive the main-logs artifact. My best guess is that somehow the artifact gets saved in the wait container but fails to be properly written in reportOutputs / `reportResult.

Is there an easy way to write the wait container logs to a file in the same way that the controller logs are written to a file in the logs directory? Without this, It's basically impossible for me to debug it.

**Comment by juliev0** [comment]
> @agilgur5 @juliev0
> 
> I'm having a hard time debugging this. The failure rate is like 1/30+ test runs on my local machine. The artifacts are being saved, but the task reconciliation never receives the `on-deletion-wf-stopped` artifact for some reason. Task reconciliation does, however, receive the `main-logs` artifact. My best guess is that somehow the artifact gets saved in the wait container but fails to be properly written in `reportOutputs` / `reportResult`.
> 
> Is there an easy way to write the wait container logs to a file in the same way that the controller logs are written to a file in the logs directory? Without this, It's basically impossible for me to debug it.

Interesting. So, is the difference between state of "latest" branch and this one that basically it fails for stopped workflows 1/30 times (at least in this unit test) vs 100%? Are you seeing it fail more often than that in the CI, though?

As far as the wait container logs, no, I don't know of a wait container log artifact unfortunately. But maybe you could run something like: `kubectl logs --follow -lworkflows.argoproj.io/workflow=<name> --container wait`. Based on [this](https://stackoverflow.com/questions/77146944/does-kubectl-logs-f-l-follow-newly-created-pod#:~:text=The%20%2Dfollow%20flag%20will%20continuously,specified%20with%20the%20%2Dl%20flag.) post, it seems like that should follow newly created pods after you start running.

**Comment by Garett-MacGowan** [comment]
> Interesting. So, is the difference between state of "latest" branch and this one that basically it fails for stopped workflows 1/30 times (at least in this unit test) vs 100%?

Yeah, it should fail 100% of the time on the latest branch. I'll double check tomorrow by undoing my changes locally and run the test a few times.

> Are you seeing it fail more often than that in the CI, though?

I will resubmit the CI job tomorrow to see. If it fails again, then yes.

> kubectl logs --follow -lworkflows.argoproj.io/workflow=<name> --container wait

Thanks for this, I will test it out.

**Comment by Garett-MacGowan** [comment]
> Interesting. So, is the difference between state of "latest" branch and this one that basically it fails for stopped workflows 1/30 times (at least in this unit test) vs 100%? Are you seeing it fail more often than that in the CI, though?

I've confirmed the test fails 100% of the time on latest.

> But maybe you could run something like: kubectl logs --follow -lworkflows.argoproj.io/workflow=<name> --container=wait. Based on [this](https://stackoverflow.com/questions/77146944/does-kubectl-logs-f-l-follow-newly-created-pod#:~:text=The%20%2Dfollow%20flag%20will%20continuously,specified%20with%20the%20%2Dl%20flag.) post, it seems like that should follow newly created pods after you start running.

I ended up using the following command to watch the logs between multiple test runs so that I can rapid fire the tests until I hit a failure. Note that I added the `template=artgc-dag-artifact-creator` label to the `artgc-dag-artifact-creator` template locally.

```
kubectl get pods -l 'template=artgc-dag-artifact-creator' --watch -o name | while read -r pod; do kubectl logs -f -c wait "$pod"; done
```

As a result of the above, I was able to confirm that the workflowtaskresults are being properly created (`Create workflowtaskresults 201`).

Maybe a fresh set of eyes can help.

Here is an excerpt of the controller logs of a failure (this is from near the end of the test):
```
time="2023-10-11T20:02:54.540Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.541Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.541Z" level=debug msg="woc wf status nodes: map[artgc-dag-wf-stopped-hllgt:{artgc-dag-wf-stopped-hllgt artgc-dag-wf-stopped-hllgt artgc-dag-wf-stopped-hllgt DAG artgc-dag-wf-stopped-main nil local/artgc-dag-wf-stopped-hllgt Failed   2023-10-11 20:02:25 +0000 UTC 2023-10-11 20:02:48 +0000 UTC %!s(v1alpha1.EstimatedDuration=0) 1/3 6s*(1 cpu),4s*(100Mi memory)  %!s(*bool=<nil>) nil nil [artgc-dag-wf-stopped-hllgt-3193530808 artgc-dag-wf-stopped-hllgt-2203728917] [artgc-dag-wf-stopped-hllgt-3193530808 artgc-dag-wf-stopped-hllgt-3113225067]  nil nil} artgc-dag-wf-stopped-hllgt-2203728917:{artgc-dag-wf-stopped-hllgt-2203728917 artgc-dag-wf-stopped-hllgt.delay-stop-workflow delay-stop-workflow Pod artgc-dag-delay-stop nil local/artgc-dag-wf-stopped-hllgt Succeeded artgc-dag-wf-stopped-hllgt  2023-10-11 20:02:25 +0000 UTC 2023-10-11 20:02:41 +0000 UTC %!s(v1alpha1.EstimatedDuration=0) 1/1 6s*(1 cpu),4s*(100Mi memory)  %!s(*bool=<nil>) nil &Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-hllgt/artgc-dag-wf-stopped-hllgt-artgc-dag-delay-stop-2203728917/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,} [artgc-dag-wf-stopped-hllgt-3113225067] [] k3d-k3s-default-server-0 nil nil} artgc-dag-wf-stopped-hllgt-3113225067:{artgc-dag-wf-stopped-hllgt-3113225067 artgc-dag-wf-stopped-hllgt.stop-workflow stop-workflow Pod artgc-dag-workflow-stopper nil local/artgc-dag-wf-stopped-hllgt Failed artgc-dag-wf-stopped-hllgt workflow shutdown with strategy:  Stop 2023-10-11 20:02:43 +0000 UTC 2023-10-11 20:02:48 +0000 UTC %!s(v1alpha1.EstimatedDuration=0) 0/1   %!s(*bool=<nil>) nil &Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-hllgt/artgc-dag-wf-stopped-hllgt-artgc-dag-workflow-stopper-3113225067/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,} [] [] k3d-k3s-default-server-0 nil nil} artgc-dag-wf-stopped-hllgt-3193530808:{artgc-dag-wf-stopped-hllgt-3193530808 artgc-dag-wf-stopped-hllgt.create-artifact create-artifact Pod artgc-dag-artifact-creator nil local/artgc-dag-wf-stopped-hllgt Failed artgc-dag-wf-stopped-hllgt workflow shutdown with strategy:  Stop 2023-10-11 20:02:25 +0000 UTC 2023-10-11 20:02:48 +0000 UTC %!s(v1alpha1.EstimatedDuration=0) 0/1   %!s(*bool=<nil>) nil nil [] [] k3d-k3s-default-server-0 nil nil}]" namespace=argo workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.541Z" level=debug msg="woc wf status outputs: nil" namespace=argo workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.541Z" level=debug msg="woc wf artifactgc status: &ArtGCStatus{StrategiesProcessed:map[ArtifactGCStrategy]bool{OnWorkflowCompletion: true,OnWorkflowDeletion: true,},PodsRecouped:map[string]bool{},NotSpecified:false,}" namespace=argo workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.541Z" level=info msg="reconciling artifact-gc pod" message= namespace=argo phase=Succeeded pod=artgc-dag-wf-stopped-hllgt-artgc-wfdel-2470140894 workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.541Z" level=info msg="processing completed Artifact GC Pod \"artgc-dag-wf-stopped-hllgt-artgc-wfdel-2470140894\"" namespace=argo workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.545Z" level=debug msg="List workflowartifactgctasks 200"
time="2023-10-11T20:02:54.546Z" level=debug msg="processing WorkflowArtifactGCTask artgc-dag-wf-stopped-hllgt-artgc-wfdel-2470140894-0" namespace=argo workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.546Z" level=debug msg="deleting WorkflowArtifactGCTask: artgc-dag-wf-stopped-hllgt-artgc-wfdel-2470140894-0" namespace=argo workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.556Z" level=debug msg="Delete workflowartifactgctasks 200"
time="2023-10-11T20:02:54.556Z" level=info msg="no remaining artifacts to GC, removing artifact GC finalizer (forceFinalizerRemoval=false)" namespace=argo workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.557Z" level=debug msg="Log changes patch: {\"metadata\":{\"finalizers\":null},\"status\":{\"artifactGCStatus\":{\"podsRecouped\":{\"artgc-dag-wf-stopped-hllgt-artgc-wfdel-2470140894\":true}},\"nodes\":{\"artgc-dag-wf-stopped-hllgt-2203728917\":{\"outputs\":{\"artifacts\":[{\"deleted\":true,\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-hllgt/artgc-dag-wf-stopped-hllgt-artgc-dag-delay-stop-2203728917/main.log\"}}]}},\"artgc-dag-wf-stopped-hllgt-3113225067\":{\"outputs\":{\"artifacts\":[{\"deleted\":true,\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-hllgt/artgc-dag-wf-stopped-hllgt-artgc-dag-workflow-stopper-3113225067/main.log\"}}]}}}}}"
time="2023-10-11T20:02:54.557Z" level=info msg="Workflow to be dehydrated" Workflow Size=4597
time="2023-10-11T20:02:54.573Z" level=debug msg="Update workflows 200"
time="2023-10-11T20:02:54.573Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=392281 workflow=artgc-dag-wf-stopped-hllgt
time="2023-10-11T20:02:54.590Z" level=debug msg="DeleteCollection workflowtaskresults 200"
```

Here is an excerpt of the controller logs of a success (this is from near the end of the test):
```
time="2023-10-11T20:02:00.286Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.287Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.287Z" level=debug msg="woc wf status nodes: map[artgc-dag-wf-stopped-7zxmc:{artgc-dag-wf-stopped-7zxmc artgc-dag-wf-stopped-7zxmc artgc-dag-wf-stopped-7zxmc DAG artgc-dag-wf-stopped-main nil local/artgc-dag-wf-stopped-7zxmc Failed   2023-10-11 20:01:29 +0000 UTC 2023-10-11 20:01:53 +0000 UTC %!s(v1alpha1.EstimatedDuration=0) 1/3 6s*(1 cpu),4s*(100Mi memory)  %!s(*bool=<nil>) nil nil [artgc-dag-wf-stopped-7zxmc-141800804 artgc-dag-wf-stopped-7zxmc-1982811905] [artgc-dag-wf-stopped-7zxmc-141800804 artgc-dag-wf-stopped-7zxmc-2210815367]  nil nil} artgc-dag-wf-stopped-7zxmc-141800804:{artgc-dag-wf-stopped-7zxmc-141800804 artgc-dag-wf-stopped-7zxmc.create-artifact create-artifact Pod artgc-dag-artifact-creator nil local/artgc-dag-wf-stopped-7zxmc Failed artgc-dag-wf-stopped-7zxmc workflow shutdown with strategy:  Stop 2023-10-11 20:01:29 +0000 UTC 2023-10-11 20:01:53 +0000 UTC %!s(v1alpha1.EstimatedDuration=0) 0/1   %!s(*bool=<nil>) nil &Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:on-deletion-wf-stopped,Path:/mnt/vol/test.txt,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:minio:9000,Bucket:my-bucket-3,Region:,Insecure:*true,AccessKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:accesskey,Optional:nil,},SecretKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:secretkey,Optional:nil,},RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:on-deletion-wf-stopped,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:&ArtifactGC{Strategy:OnWorkflowDeletion,PodMetadata:nil,ServiceAccountName:,},Deleted:false,},Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-7zxmc/artgc-dag-wf-stopped-7zxmc-artgc-dag-artifact-creator-141800804/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,} [] [] k3d-k3s-default-server-0 nil nil} artgc-dag-wf-stopped-7zxmc-1982811905:{artgc-dag-wf-stopped-7zxmc-1982811905 artgc-dag-wf-stopped-7zxmc.delay-stop-workflow delay-stop-workflow Pod artgc-dag-delay-stop nil local/artgc-dag-wf-stopped-7zxmc Succeeded artgc-dag-wf-stopped-7zxmc  2023-10-11 20:01:29 +0000 UTC 2023-10-11 20:01:44 +0000 UTC %!s(v1alpha1.EstimatedDuration=0) 1/1 4s*(100Mi memory),6s*(1 cpu)  %!s(*bool=<nil>) nil &Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-7zxmc/artgc-dag-wf-stopped-7zxmc-artgc-dag-delay-stop-1982811905/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,} [artgc-dag-wf-stopped-7zxmc-2210815367] [] k3d-k3s-default-server-0 nil nil} artgc-dag-wf-stopped-7zxmc-2210815367:{artgc-dag-wf-stopped-7zxmc-2210815367 artgc-dag-wf-stopped-7zxmc.stop-workflow stop-workflow Pod artgc-dag-workflow-stopper nil local/artgc-dag-wf-stopped-7zxmc Failed artgc-dag-wf-stopped-7zxmc workflow shutdown with strategy:  Stop 2023-10-11 20:01:47 +0000 UTC 2023-10-11 20:01:53 +0000 UTC %!s(v1alpha1.EstimatedDuration=0) 0/1   %!s(*bool=<nil>) nil &Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-7zxmc/artgc-dag-wf-stopped-7zxmc-artgc-dag-workflow-stopper-2210815367/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,} [] [] k3d-k3s-default-server-0 nil nil}]" namespace=argo workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.287Z" level=debug msg="woc wf status outputs: nil" namespace=argo workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.287Z" level=debug msg="woc wf artifactgc status: &ArtGCStatus{StrategiesProcessed:map[ArtifactGCStrategy]bool{OnWorkflowCompletion: true,OnWorkflowDeletion: true,},PodsRecouped:map[string]bool{},NotSpecified:false,}" namespace=argo workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.287Z" level=info msg="reconciling artifact-gc pod" message= namespace=argo phase=Succeeded pod=artgc-dag-wf-stopped-7zxmc-artgc-wfdel-2470140894 workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.287Z" level=info msg="processing completed Artifact GC Pod \"artgc-dag-wf-stopped-7zxmc-artgc-wfdel-2470140894\"" namespace=argo workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.292Z" level=debug msg="List workflowartifactgctasks 200"
time="2023-10-11T20:02:00.292Z" level=debug msg="processing WorkflowArtifactGCTask artgc-dag-wf-stopped-7zxmc-artgc-wfdel-2470140894-0" namespace=argo workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.292Z" level=debug msg="deleting WorkflowArtifactGCTask: artgc-dag-wf-stopped-7zxmc-artgc-wfdel-2470140894-0" namespace=argo workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.364Z" level=debug msg="Delete workflowartifactgctasks 200"
time="2023-10-11T20:02:00.364Z" level=info msg="no remaining artifacts to GC, removing artifact GC finalizer (forceFinalizerRemoval=false)" namespace=argo workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.365Z" level=debug msg="Log changes patch: {\"metadata\":{\"finalizers\":null},\"status\":{\"artifactGCStatus\":{\"podsRecouped\":{\"artgc-dag-wf-stopped-7zxmc-artgc-wfdel-2470140894\":true}},\"nodes\":{\"artgc-dag-wf-stopped-7zxmc-141800804\":{\"outputs\":{\"artifacts\":[{\"artifactGC\":{\"strategy\":\"OnWorkflowDeletion\"},\"deleted\":true,\"name\":\"on-deletion-wf-stopped\",\"path\":\"/mnt/vol/test.txt\",\"s3\":{\"accessKeySecret\":{\"key\":\"accesskey\",\"name\":\"my-minio-cred\"},\"bucket\":\"my-bucket-3\",\"endpoint\":\"minio:9000\",\"insecure\":true,\"key\":\"on-deletion-wf-stopped\",\"secretKeySecret\":{\"key\":\"secretkey\",\"name\":\"my-minio-cred\"}}},{\"deleted\":true,\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-7zxmc/artgc-dag-wf-stopped-7zxmc-artgc-dag-artifact-creator-141800804/main.log\"}}]}},\"artgc-dag-wf-stopped-7zxmc-1982811905\":{\"outputs\":{\"artifacts\":[{\"deleted\":true,\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-7zxmc/artgc-dag-wf-stopped-7zxmc-artgc-dag-delay-stop-1982811905/main.log\"}}]}},\"artgc-dag-wf-stopped-7zxmc-2210815367\":{\"outputs\":{\"artifacts\":[{\"deleted\":true,\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-7zxmc/artgc-dag-wf-stopped-7zxmc-artgc-dag-workflow-stopper-2210815367/main.log\"}}]}}}}}"
time="2023-10-11T20:02:00.365Z" level=info msg="Workflow to be dehydrated" Workflow Size=4950
time="2023-10-11T20:02:00.384Z" level=debug msg="Update workflows 200"
time="2023-10-11T20:02:00.385Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=392104 workflow=artgc-dag-wf-stopped-7zxmc
time="2023-10-11T20:02:00.407Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-10-11T20:02:01.388Z" level=debug msg="Won't process Workflow since it's completed" key=argo/artgc-dag-wf-stopped-7zxmc
```

The `woc wf status nodes` and `woc wf artifactgc status` logs are after `woc.taskResultReconciliation` in `operator.go`. Notice how the `on-deletion-wf-stopped` is present in the success case and not present in the failure case. I've verified the result passed in `reportResult` of `executor.go` includes both the `on-deletion-wf-stopped` and `main-logs` artifacts. 

For example, here is a result logged from `reportResult` for a failure case:

```
{  &Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:on-deletion-wf-stopped,Path:/mnt/vol/test.txt,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:minio:9000,Bucket:my-bucket-3,Region:,Insecure:*true,AccessKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:accesskey,Optional:nil,},SecretKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:secretkey,Optional:nil,},RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:on-deletion-wf-stopped,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:&ArtifactGC{Strategy:OnWorkflowDeletion,PodMetadata:nil,ServiceAccountName:,},Deleted:false,},Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-hllgt/artgc-dag-wf-stopped-hllgt-artgc-dag-artifact-creator-3193530808/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,} }"
```

At this point, I'm peppering logs in taskResultReconciliation to see if there may be an issue there. Perhaps there is a bug in the reconcoliation logic? Will follow up shortly.

**Comment by Garett-MacGowan** [comment]
`on-deletion-wf-stopped` is not referenced a single time during `taskResultReconciliation()` in the failure case. I'm **lost**.

Here's the logs:

```
time="2023-10-11T22:19:51.054Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main"
time="2023-10-11T22:19:51.055Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator"
time="2023-10-11T22:19:51.055Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.055Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-workflow-stopper)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.056Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.062Z" level=debug msg="Get configmaps 200"
time="2023-10-11T22:19:51.062Z" level=info msg="resolved artifact repository" artifactRepositoryRef="argo/#"
time="2023-10-11T22:19:51.062Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.062Z" level=info msg="adding artifact GC finalizer" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.062Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.062Z" level=info msg="Creating pvc artgc-dag-wf-stopped-kg8tk-artifacts" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.063Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405097\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowRunning' Workflow Running"
time="2023-10-11T22:19:51.071Z" level=debug msg="Create events 201"
time="2023-10-11T22:19:51.076Z" level=debug msg="Create persistentvolumeclaims 201"
time="2023-10-11T22:19:51.077Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.077Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.077Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.077Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.077Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.077Z" level=debug msg="Initializing node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.077Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.077Z" level=info msg="DAG node artgc-dag-wf-stopped-kg8tk initialized Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.077Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-3846913764, taskName create-artifact"
time="2023-10-11T22:19:51.077Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-3846913764, taskName create-artifact"
time="2023-10-11T22:19:51.077Z" level=info msg="All of node artgc-dag-wf-stopped-kg8tk.create-artifact dependencies [] completed" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.077Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.077Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.077Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.077Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.077Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:51.078Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.078Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.078Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.078Z" level=debug msg="Initializing node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.078Z" level=info msg="Pod node artgc-dag-wf-stopped-kg8tk-3846913764 initialized Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.078Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.078Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.078Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.078Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.078Z" level=debug namespace=argo needLocation=true workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.086Z" level=debug msg="Get serviceaccounts 200"
time="2023-10-11T22:19:51.089Z" level=debug msg="Creating Pod: artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.098Z" level=debug msg="Create pods 201"
W1011 22:19:51.098305   22635 warnings.go:70] metadata.name: this is used in the Pod's hostname, which can result in surprising behavior; a DNS label is recommended: [must be no more than 63 characters]
time="2023-10-11T22:19:51.099Z" level=info msg="Created pod: artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.099Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:51.099Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-3444961409, taskName delay-stop-workflow"
time="2023-10-11T22:19:51.099Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-3444961409, taskName delay-stop-workflow"
time="2023-10-11T22:19:51.099Z" level=info msg="All of node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow dependencies [] completed" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.099Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.099Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.099Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Initializing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.099Z" level=info msg="Pod node artgc-dag-wf-stopped-kg8tk-3444961409 initialized Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.099Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:51.099Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow with container template: artgc-dag-delay-stop\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.099Z" level=debug namespace=argo needLocation=true workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.104Z" level=debug msg="Get serviceaccounts 200"
time="2023-10-11T22:19:51.106Z" level=debug msg="Creating Pod: artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.114Z" level=debug msg="Create pods 201"
time="2023-10-11T22:19:51.115Z" level=info msg="Created pod: artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.115Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:51.115Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:51.115Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.115Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.116Z" level=debug msg="Log changes patch: {\"metadata\":{\"annotations\":{\"workflows.argoproj.io/pod-name-format\":\"v2\"},\"finalizers\":[\"workflows.argoproj.io/artifact-gc\"],\"labels\":{\"workflows.argoproj.io/phase\":\"Running\"}},\"spec\":{\"activeDeadlineSeconds\":300,\"podSpecPatch\":\"terminationGracePeriodSeconds: 3\\n\"},\"status\":{\"artifactGCStatus\":{},\"artifactRepositoryRef\":{\"artifactRepository\":{\"archiveLogs\":true,\"s3\":{\"accessKeySecret\":{\"key\":\"accesskey\",\"name\":\"my-minio-cred\"},\"bucket\":\"my-bucket\",\"endpoint\":\"minio:9000\",\"insecure\":true,\"secretKeySecret\":{\"key\":\"secretkey\",\"name\":\"my-minio-cred\"}}},\"configMap\":\"artifact-repositories\",\"key\":\"default-v1\",\"namespace\":\"argo\"},\"nodes\":{\"artgc-dag-wf-stopped-kg8tk\":{\"children\":[\"artgc-dag-wf-stopped-kg8tk-3846913764\",\"artgc-dag-wf-stopped-kg8tk-3444961409\"],\"displayName\":\"artgc-dag-wf-stopped-kg8tk\",\"finishedAt\":null,\"id\":\"artgc-dag-wf-stopped-kg8tk\",\"name\":\"artgc-dag-wf-stopped-kg8tk\",\"phase\":\"Running\",\"startedAt\":\"2023-10-11T22:19:51Z\",\"templateName\":\"artgc-dag-wf-stopped-main\",\"templateScope\":\"local/artgc-dag-wf-stopped-kg8tk\",\"type\":\"DAG\"},\"artgc-dag-wf-stopped-kg8tk-3444961409\":{\"boundaryID\":\"artgc-dag-wf-stopped-kg8tk\",\"displayName\":\"delay-stop-workflow\",\"finishedAt\":null,\"id\":\"artgc-dag-wf-stopped-kg8tk-3444961409\",\"name\":\"artgc-dag-wf-stopped-kg8tk.delay-stop-workflow\",\"phase\":\"Pending\",\"startedAt\":\"2023-10-11T22:19:51Z\",\"templateName\":\"artgc-dag-delay-stop\",\"templateScope\":\"local/artgc-dag-wf-stopped-kg8tk\",\"type\":\"Pod\"},\"artgc-dag-wf-stopped-kg8tk-3846913764\":{\"boundaryID\":\"artgc-dag-wf-stopped-kg8tk\",\"displayName\":\"create-artifact\",\"finishedAt\":null,\"id\":\"artgc-dag-wf-stopped-kg8tk-3846913764\",\"name\":\"artgc-dag-wf-stopped-kg8tk.create-artifact\",\"phase\":\"Pending\",\"startedAt\":\"2023-10-11T22:19:51Z\",\"templateName\":\"artgc-dag-artifact-creator\",\"templateScope\":\"local/artgc-dag-wf-stopped-kg8tk\",\"type\":\"Pod\"}},\"persistentVolumeClaims\":[{\"name\":\"artifacts\",\"persistentVolumeClaim\":{\"claimName\":\"artgc-dag-wf-stopped-kg8tk-artifacts\"}}],\"phase\":\"Running\",\"startedAt\":\"2023-10-11T22:19:51Z\"}}"
time="2023-10-11T22:19:51.116Z" level=info msg="Workflow to be dehydrated" Workflow Size=3063
time="2023-10-11T22:19:51.125Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:19:51.126Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405106 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:51.128Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405106\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artgc-dag-wf-stopped-kg8tk"
time="2023-10-11T22:19:51.135Z" level=debug msg="Create events 201"
time="2023-10-11T22:19:52.055Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.056Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.056Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.056Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.056Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.056Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.056Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.056Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.056Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.056Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:52.057Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:52.057Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow with container template: artgc-dag-delay-stop\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-3444961409) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:52.057Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:52.057Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.057Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:52.540Z" level=debug msg="Get leases 200"
time="2023-10-11T22:19:52.545Z" level=debug msg="Update leases 200"
time="2023-10-11T22:19:54.341Z" level=debug msg="Syncing all CronWorkflows"
time="2023-10-11T22:19:56.114Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.115Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 old.message= old.phase=Pending old.progress=0/1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 old.message= old.phase=Pending old.progress=0/1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.116Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.116Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:56.117Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.117Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:56.117Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:56.117Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:56.117Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.117Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.117Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.117Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:56.117Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow with container template: artgc-dag-delay-stop\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.117Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-3444961409) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.117Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:56.117Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:56.117Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.117Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:56.118Z" level=debug msg="Log changes patch: {\"status\":{\"conditions\":[{\"status\":\"False\",\"type\":\"PodRunning\"}],\"nodes\":{\"artgc-dag-wf-stopped-kg8tk-3444961409\":{\"hostNodeName\":\"k3d-k3s-default-server-0\",\"message\":\"PodInitializing\"},\"artgc-dag-wf-stopped-kg8tk-3846913764\":{\"hostNodeName\":\"k3d-k3s-default-server-0\",\"message\":\"PodInitializing\"}}}}"
time="2023-10-11T22:19:56.118Z" level=info msg="Workflow to be dehydrated" Workflow Size=3450
time="2023-10-11T22:19:56.143Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:19:56.143Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405136 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.549Z" level=debug msg="Get leases 200"
time="2023-10-11T22:19:57.554Z" level=debug msg="Update leases 200"
time="2023-10-11T22:19:57.936Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.937Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.937Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.937Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.937Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.937Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.937Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.937Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.939Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.939Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.939Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:57.939Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:57.939Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.940Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.940Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.940Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:57.940Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.940Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.940Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:19:57.940Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow with container template: artgc-dag-delay-stop\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.940Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-3444961409) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.940Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:57.940Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:19:57.940Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:19:57.940Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.559Z" level=debug msg="Get leases 200"
time="2023-10-11T22:20:02.566Z" level=debug msg="Update leases 200"
time="2023-10-11T22:20:02.902Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.902Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.902Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:02.903Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.903Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.903Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:02.904Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow with container template: artgc-dag-delay-stop\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.904Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-3444961409) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.904Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:02.904Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:02.904Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:02.904Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.342Z" level=debug msg="Syncing all CronWorkflows"
time="2023-10-11T22:20:04.907Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.907Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:04.908Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.908Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:04.908Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:04.909Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.909Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.909Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.909Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:04.909Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow with container template: artgc-dag-delay-stop\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.909Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-3444961409) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.909Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:04.909Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:04.909Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.909Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.909Z" level=debug msg="Log changes patch: {\"status\":{\"conditions\":[{\"status\":\"True\",\"type\":\"PodRunning\"}],\"nodes\":{\"artgc-dag-wf-stopped-kg8tk-3444961409\":{\"message\":null,\"phase\":\"Running\"},\"artgc-dag-wf-stopped-kg8tk-3846913764\":{\"message\":null,\"phase\":\"Running\"}}}}"
time="2023-10-11T22:20:04.909Z" level=info msg="Workflow to be dehydrated" Workflow Size=3419
time="2023-10-11T22:20:04.917Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:04.918Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405164 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:04.918Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405164\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow"
time="2023-10-11T22:20:04.919Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405164\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artgc-dag-wf-stopped-kg8tk.create-artifact"
time="2023-10-11T22:20:04.924Z" level=debug msg="Create events 201"
time="2023-10-11T22:20:04.930Z" level=debug msg="Create events 201"
time="2023-10-11T22:20:06.919Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.920Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.920Z" level=debug msg="result: &WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-kg8tk-3444961409  argo  574562ae-7d3e-444e-962b-ae0a52e6f226 405168 1 2023-10-11 22:20:06 +0000 UTC <nil> <nil> map[workflows.argoproj.io/workflow:artgc-dag-wf-stopped-kg8tk] map[] [{v1 Pod artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409 f496561d-e39a-43b8-b930-15b8c2ee14c2 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-11 22:20:06 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"f496561d-e39a-43b8-b930-15b8c2ee14c2\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.920Z" level=debug msg="woc.wf.Status.Nodes.Get err: %!s(<nil>)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.920Z" level=debug msg="old: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Running,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:0/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.920Z" level=debug msg="newNode: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Running,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Children:[],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:0/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.920Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.920Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 old.message= old.phase=Running old.progress=0/1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:06.921Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.921Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:06.921Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:06.922Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.922Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.922Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.922Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:06.922Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow with container template: artgc-dag-delay-stop\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.922Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-3444961409) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.922Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:06.922Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:06.922Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.922Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.922Z" level=debug msg="Log changes patch: {\"status\":{\"nodes\":{\"artgc-dag-wf-stopped-kg8tk-3444961409\":{\"outputs\":{\"artifacts\":[{\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log\"}}],\"exitCode\":\"0\"}}}}}"
time="2023-10-11T22:20:06.922Z" level=info msg="Workflow to be dehydrated" Workflow Size=3567
time="2023-10-11T22:20:06.926Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/terminateContainers
time="2023-10-11T22:20:06.926Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-10-11T22:20:06.926Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409
time="2023-10-11T22:20:06.934Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:06.934Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405170 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:06.951Z" level=debug msg="Create pods/exec 500"
time="2023-10-11T22:20:06.951Z" level=info msg="signaled container" container=wait error="unable to upgrade connection: container not found (\"wait\")" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409 stderr="<nil>" stdout="<nil>"
time="2023-10-11T22:20:07.572Z" level=debug msg="Get leases 200"
time="2023-10-11T22:20:07.578Z" level=debug msg="Update leases 200"
time="2023-10-11T22:20:07.932Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.933Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.933Z" level=debug msg="result: &WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-kg8tk-3444961409  argo  574562ae-7d3e-444e-962b-ae0a52e6f226 405168 1 2023-10-11 22:20:06 +0000 UTC <nil> <nil> map[workflows.argoproj.io/workflow:artgc-dag-wf-stopped-kg8tk] map[] [{v1 Pod artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409 f496561d-e39a-43b8-b930-15b8c2ee14c2 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-11 22:20:06 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"f496561d-e39a-43b8-b930-15b8c2ee14c2\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.933Z" level=debug msg="woc.wf.Status.Nodes.Get err: %!s(<nil>)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.933Z" level=debug msg="old: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Running,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:0/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.933Z" level=debug msg="newNode: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Running,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:0/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.933Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.933Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.933Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.934Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.934Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.934Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.934Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.934Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.934Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.934Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.934Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:07.934Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-delay-stop), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.935Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:07.935Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:07.935Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:07.935Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.935Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.935Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.935Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:07.935Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow with container template: artgc-dag-delay-stop\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.935Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.delay-stop-workflow (artgc-dag-wf-stopped-kg8tk-3444961409) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.935Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:07.935Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:07.935Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.935Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:07.935Z" level=debug msg="Log changes patch: {\"status\":{\"conditions\":[{\"status\":\"False\",\"type\":\"PodRunning\"}]}}"
time="2023-10-11T22:20:07.935Z" level=info msg="Workflow to be dehydrated" Workflow Size=3568
time="2023-10-11T22:20:07.939Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/terminateContainers
time="2023-10-11T22:20:07.943Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:07.944Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405173 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.946Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=debug msg="result: &WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-kg8tk-3444961409  argo  574562ae-7d3e-444e-962b-ae0a52e6f226 405168 1 2023-10-11 22:20:06 +0000 UTC <nil> <nil> map[workflows.argoproj.io/workflow:artgc-dag-wf-stopped-kg8tk] map[] [{v1 Pod artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409 f496561d-e39a-43b8-b930-15b8c2ee14c2 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-11 22:20:06 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"f496561d-e39a-43b8-b930-15b8c2ee14c2\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=debug msg="woc.wf.Status.Nodes.Get err: %!s(<nil>)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=debug msg="old: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Running,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:0/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=debug msg="newNode: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Running,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:0/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 old.message= old.phase=Running old.progress=0/1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.947Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.947Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.947Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.947Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:08.947Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:08.947Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:08.948Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:08.948Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:08.948Z" level=warning msg="was unable to obtain the node for artgc-dag-wf-stopped-kg8tk-1504799495, taskName stop-workflow"
time="2023-10-11T22:20:08.948Z" level=info msg="All of node artgc-dag-wf-stopped-kg8tk.stop-workflow dependencies [delay-stop-workflow] completed" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-delay-stop)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-delay-stop)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-delay-stop)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-workflow-stopper), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Initializing node artgc-dag-wf-stopped-kg8tk.stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-workflow-stopper), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=info msg="Pod node artgc-dag-wf-stopped-kg8tk-1504799495 initialized Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:08.948Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.stop-workflow with container template: artgc-dag-workflow-stopper\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.948Z" level=debug namespace=argo needLocation=true workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.952Z" level=debug msg="Get serviceaccounts 200"
time="2023-10-11T22:20:08.954Z" level=debug msg="Cache hit" cmd="&{[argo] []}" image="argoproj/argocli:latest"
time="2023-10-11T22:20:08.954Z" level=debug msg="Creating Pod: artgc-dag-wf-stopped-kg8tk.stop-workflow (artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.961Z" level=debug msg="Create pods 201"
W1011 22:20:08.961687   22635 warnings.go:70] metadata.name: this is used in the Pod's hostname, which can result in surprising behavior; a DNS label is recommended: [must be no more than 63 characters]
time="2023-10-11T22:20:08.962Z" level=info msg="Created pod: artgc-dag-wf-stopped-kg8tk.stop-workflow (artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.962Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.962Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.963Z" level=debug msg="Log changes patch: {\"status\":{\"nodes\":{\"artgc-dag-wf-stopped-kg8tk-1504799495\":{\"boundaryID\":\"artgc-dag-wf-stopped-kg8tk\",\"displayName\":\"stop-workflow\",\"finishedAt\":null,\"id\":\"artgc-dag-wf-stopped-kg8tk-1504799495\",\"name\":\"artgc-dag-wf-stopped-kg8tk.stop-workflow\",\"phase\":\"Pending\",\"startedAt\":\"2023-10-11T22:20:08Z\",\"templateName\":\"artgc-dag-workflow-stopper\",\"templateScope\":\"local/artgc-dag-wf-stopped-kg8tk\",\"type\":\"Pod\"},\"artgc-dag-wf-stopped-kg8tk-3444961409\":{\"children\":[\"artgc-dag-wf-stopped-kg8tk-1504799495\"],\"finishedAt\":\"2023-10-11T22:20:06Z\",\"phase\":\"Succeeded\",\"resourcesDuration\":{\"cpu\":6,\"memory\":4}}}}}"
time="2023-10-11T22:20:08.963Z" level=info msg="Workflow to be dehydrated" Workflow Size=3936
time="2023-10-11T22:20:08.972Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:08.973Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405178 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:08.973Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405178\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeSucceeded' Succeeded node artgc-dag-wf-stopped-kg8tk.delay-stop-workflow"
time="2023-10-11T22:20:08.978Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/labelPodCompleted
time="2023-10-11T22:20:08.994Z" level=debug msg="Patch pods 200"
time="2023-10-11T22:20:09.013Z" level=debug msg="Create events 201"
time="2023-10-11T22:20:09.952Z" level=info msg="cleaning up pod" action=killContainers key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/killContainers
time="2023-10-11T22:20:09.964Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.966Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.966Z" level=debug msg="result: &WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-kg8tk-3444961409  argo  574562ae-7d3e-444e-962b-ae0a52e6f226 405168 1 2023-10-11 22:20:06 +0000 UTC <nil> <nil> map[workflows.argoproj.io/workflow:artgc-dag-wf-stopped-kg8tk] map[] [{v1 Pod artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409 f496561d-e39a-43b8-b930-15b8c2ee14c2 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-11 22:20:06 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"f496561d-e39a-43b8-b930-15b8c2ee14c2\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.966Z" level=debug msg="woc.wf.Status.Nodes.Get err: %!s(<nil>)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.966Z" level=debug msg="old: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Succeeded,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:2023-10-11 22:20:06 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[artgc-dag-wf-stopped-kg8tk-1504799495],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{cpu: 6s,memory: 4s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.966Z" level=debug msg="newNode: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Succeeded,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:2023-10-11 22:20:06 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[artgc-dag-wf-stopped-kg8tk-1504799495],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{cpu: 6s,memory: 4s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.966Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.966Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=artgc-dag-wf-stopped-kg8tk-1504799495 old.message= old.phase=Pending old.progress=0/1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.966Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.967Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.967Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.967Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.967Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.968Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.969Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.969Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:09.969Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:09.969Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:09.969Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.969Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.969Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.969Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.969Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.969Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.970Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-workflow-stopper), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.970Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.stop-workflow of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.970Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:09.970Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.stop-workflow with container template: artgc-dag-workflow-stopper\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.970Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.stop-workflow (artgc-dag-wf-stopped-kg8tk-1504799495) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.970Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.970Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:09.972Z" level=debug msg="Log changes patch: {\"status\":{\"nodes\":{\"artgc-dag-wf-stopped-kg8tk-1504799495\":{\"hostNodeName\":\"k3d-k3s-default-server-0\",\"message\":\"PodInitializing\"}}}}"
time="2023-10-11T22:20:09.972Z" level=info msg="Workflow to be dehydrated" Workflow Size=3975
time="2023-10-11T22:20:09.985Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:09.986Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405188 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.988Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.990Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.991Z" level=debug msg="result: &WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-kg8tk-3444961409  argo  574562ae-7d3e-444e-962b-ae0a52e6f226 405168 1 2023-10-11 22:20:06 +0000 UTC <nil> <nil> map[workflows.argoproj.io/workflow:artgc-dag-wf-stopped-kg8tk] map[] [{v1 Pod artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409 f496561d-e39a-43b8-b930-15b8c2ee14c2 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-11 22:20:06 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"f496561d-e39a-43b8-b930-15b8c2ee14c2\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.991Z" level=debug msg="woc.wf.Status.Nodes.Get err: %!s(<nil>)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.991Z" level=debug msg="old: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Succeeded,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:2023-10-11 22:20:06 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[artgc-dag-wf-stopped-kg8tk-1504799495],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{cpu: 6s,memory: 4s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.991Z" level=debug msg="newNode: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Succeeded,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:2023-10-11 22:20:06 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[artgc-dag-wf-stopped-kg8tk-1504799495],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{cpu: 6s,memory: 4s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.991Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.991Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-1504799495 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.991Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.992Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.992Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.992Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.992Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.992Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.992Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.992Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:10.992Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:10.993Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-workflow-stopper), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.993Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:10.993Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:10.993Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:10.993Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.stop-workflow of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.993Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.993Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.993Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:10.993Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.stop-workflow with container template: artgc-dag-workflow-stopper\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.993Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.stop-workflow (artgc-dag-wf-stopped-kg8tk-1504799495) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.993Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.993Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:10.994Z" level=debug msg="Log changes patch: {}"
time="2023-10-11T22:20:10.994Z" level=info msg="Workflow to be dehydrated" Workflow Size=3975
time="2023-10-11T22:20:11.003Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:11.003Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405188 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.582Z" level=debug msg="Get leases 200"
time="2023-10-11T22:20:12.588Z" level=debug msg="Update leases 200"
time="2023-10-11T22:20:12.949Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.950Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.950Z" level=debug msg="result: &WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-kg8tk-3444961409  argo  574562ae-7d3e-444e-962b-ae0a52e6f226 405168 1 2023-10-11 22:20:06 +0000 UTC <nil> <nil> map[workflows.argoproj.io/workflow:artgc-dag-wf-stopped-kg8tk] map[] [{v1 Pod artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409 f496561d-e39a-43b8-b930-15b8c2ee14c2 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-11 22:20:06 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"f496561d-e39a-43b8-b930-15b8c2ee14c2\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.950Z" level=debug msg="woc.wf.Status.Nodes.Get err: %!s(<nil>)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.950Z" level=debug msg="old: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Succeeded,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:2023-10-11 22:20:06 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[artgc-dag-wf-stopped-kg8tk-1504799495],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{cpu: 6s,memory: 4s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.950Z" level=debug msg="newNode: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Succeeded,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:2023-10-11 22:20:06 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[artgc-dag-wf-stopped-kg8tk-1504799495],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{cpu: 6s,memory: 4s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.950Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.950Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-1504799495 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.951Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.951Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.951Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.951Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.951Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.951Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.951Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.create-artifact: template: *v1alpha1.DAGTask (artgc-dag-artifact-creator), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.951Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:12.951Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:12.951Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact of Pod is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.952Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.create-artifact with container template: artgc-dag-artifact-creator\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.952Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.create-artifact (artgc-dag-wf-stopped-kg8tk-3846913764) creation: already exists" namespace=argo podPhase=Running workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.952Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Getting the template by name: artgc-dag-delay-stop" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-delay-stop)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk.stop-workflow: template: *v1alpha1.DAGTask (artgc-dag-workflow-stopper), boundaryID: artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.952Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.stop-workflow of Pod is Pending" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.952Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.952Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:12.953Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk.stop-workflow with container template: artgc-dag-workflow-stopper\n" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.953Z" level=debug msg="Skipped pod artgc-dag-wf-stopped-kg8tk.stop-workflow (artgc-dag-wf-stopped-kg8tk-1504799495) creation: already exists" namespace=argo podPhase=Pending workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.953Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.953Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:12.954Z" level=debug msg="Log changes patch: {}"
time="2023-10-11T22:20:12.954Z" level=info msg="Workflow to be dehydrated" Workflow Size=3975
time="2023-10-11T22:20:12.962Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:12.963Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=405188 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.051Z" level=debug msg="Check the workflow existence"
time="2023-10-11T22:20:14.162Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.163Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.163Z" level=debug msg="result: &WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-kg8tk-3444961409  argo  574562ae-7d3e-444e-962b-ae0a52e6f226 405168 1 2023-10-11 22:20:06 +0000 UTC <nil> <nil> map[workflows.argoproj.io/workflow:artgc-dag-wf-stopped-kg8tk] map[] [{v1 Pod artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409 f496561d-e39a-43b8-b930-15b8c2ee14c2 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-11 22:20:06 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"f496561d-e39a-43b8-b930-15b8c2ee14c2\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.163Z" level=debug msg="woc.wf.Status.Nodes.Get err: %!s(<nil>)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.163Z" level=debug msg="old: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Succeeded,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:2023-10-11 22:20:06 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[artgc-dag-wf-stopped-kg8tk-1504799495],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{cpu: 6s,memory: 4s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=debug msg="newNode: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-3444961409,Name:artgc-dag-wf-stopped-kg8tk.delay-stop-workflow,DisplayName:delay-stop-workflow,Type:Pod,TemplateName:artgc-dag-delay-stop,TemplateRef:nil,Phase:Succeeded,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:,StartedAt:2023-10-11 22:19:51 +0000 UTC,FinishedAt:2023-10-11 22:20:06 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:*0,},Children:[artgc-dag-wf-stopped-kg8tk-1504799495],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{cpu: 6s,memory: 4s,},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3444961409 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=artgc-dag-wf-stopped-kg8tk-1504799495 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="Terminating pod as part of workflow shutdown" namespace=argo podName=artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495 shutdownStrategy=Stop workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="node artgc-dag-wf-stopped-kg8tk-1504799495 phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="node artgc-dag-wf-stopped-kg8tk-1504799495 message: workflow shutdown with strategy:  Stop" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="node artgc-dag-wf-stopped-kg8tk-1504799495 finished: 2023-10-11 22:20:14.1644284 +0000 UTC" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="node unchanged" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-3846913764 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="Terminating pod as part of workflow shutdown" namespace=argo podName=artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764 shutdownStrategy=Stop workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="node artgc-dag-wf-stopped-kg8tk-3846913764 phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="node artgc-dag-wf-stopped-kg8tk-3846913764 message: workflow shutdown with strategy:  Stop" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=info msg="node artgc-dag-wf-stopped-kg8tk-3846913764 finished: 2023-10-11 22:20:14.1647255 +0000 UTC" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-kg8tk: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.164Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:14.164Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:14.164Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-10-11T22:20:14.164Z" level=debug msg="Executing node artgc-dag-wf-stopped-kg8tk of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.165Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-artifact-creator)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:14.165Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-kg8tk)" tmpl="*v1alpha1.NodeStatus (artgc-dag-workflow-stopper)"
time="2023-10-11T22:20:14.165Z" level=info msg="Outbound nodes of artgc-dag-wf-stopped-kg8tk set to [artgc-dag-wf-stopped-kg8tk-3846913764 artgc-dag-wf-stopped-kg8tk-1504799495]" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.165Z" level=info msg="node artgc-dag-wf-stopped-kg8tk phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.165Z" level=info msg="node artgc-dag-wf-stopped-kg8tk finished: 2023-10-11 22:20:14.1658436 +0000 UTC" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.165Z" level=debug msg="Checking daemoned children of artgc-dag-wf-stopped-kg8tk" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.165Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.166Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.166Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.166Z" level=info msg="Updated message  -> Stopped with strategy 'Stop'" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.166Z" level=info msg="Marking workflow completed" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.166Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405198\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowFailed' Stopped with strategy 'Stop'"
time="2023-10-11T22:20:14.167Z" level=debug msg="Log changes patch: {\"metadata\":{\"labels\":{\"workflows.argoproj.io/completed\":\"true\",\"workflows.argoproj.io/phase\":\"Failed\"}},\"status\":{\"conditions\":[{\"status\":\"True\",\"type\":\"PodRunning\"},{\"status\":\"True\",\"type\":\"Completed\"}],\"finishedAt\":\"2023-10-11T22:20:14Z\",\"message\":\"Stopped with strategy 'Stop'\",\"nodes\":{\"artgc-dag-wf-stopped-kg8tk\":{\"finishedAt\":\"2023-10-11T22:20:14Z\",\"outboundNodes\":[\"artgc-dag-wf-stopped-kg8tk-3846913764\",\"artgc-dag-wf-stopped-kg8tk-1504799495\"],\"phase\":\"Failed\"},\"artgc-dag-wf-stopped-kg8tk-1504799495\":{\"finishedAt\":\"2023-10-11T22:20:14Z\",\"message\":\"workflow shutdown with strategy:  Stop\",\"phase\":\"Failed\"},\"artgc-dag-wf-stopped-kg8tk-3846913764\":{\"finishedAt\":\"2023-10-11T22:20:14Z\",\"message\":\"workflow shutdown with strategy:  Stop\",\"phase\":\"Failed\"}},\"phase\":\"Failed\"}}"
time="2023-10-11T22:20:14.167Z" level=info msg="Workflow to be dehydrated" Workflow Size=4325
time="2023-10-11T22:20:14.170Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/terminateContainers
time="2023-10-11T22:20:14.170Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764/terminateContainers
time="2023-10-11T22:20:14.170Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=main&stderr=true&stdout=true&tty=false"
time="2023-10-11T22:20:14.170Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=main&stderr=true&stdout=true&tty=false"
time="2023-10-11T22:20:14.170Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764
time="2023-10-11T22:20:14.170Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495
time="2023-10-11T22:20:14.171Z" level=info msg="cleaning up pod" action=deletePod key=argo/artgc-dag-wf-stopped-kg8tk-1340600742-agent/deletePod
time="2023-10-11T22:20:14.179Z" level=debug msg="Create events 201"
time="2023-10-11T22:20:14.185Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:14.186Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=405201 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:14.186Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405201\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artgc-dag-wf-stopped-kg8tk.stop-workflow: workflow shutdown with strategy:  Stop"
time="2023-10-11T22:20:14.187Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405201\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-kg8tk.stop-workflow: workflow shutdown with strategy:  Stop"
time="2023-10-11T22:20:14.187Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405201\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-kg8tk.create-artifact: workflow shutdown with strategy:  Stop"
time="2023-10-11T22:20:14.187Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-kg8tk\", UID:\"a79f56c0-9c76-444e-b499-749078a78c6a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"405201\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-kg8tk"
time="2023-10-11T22:20:14.188Z" level=info msg="Queueing Failed workflow argo/artgc-dag-wf-stopped-v9k8t for delete due to max rention(2 workflows)"
time="2023-10-11T22:20:14.188Z" level=info msg="Deleting garbage collected workflow 'argo/artgc-dag-wf-stopped-v9k8t'"
time="2023-10-11T22:20:14.188Z" level=debug msg="Delete pods 404"
time="2023-10-11T22:20:14.213Z" level=debug msg="Create events 201"
time="2023-10-11T22:20:14.216Z" level=debug msg="Delete workflows 404"
time="2023-10-11T22:20:14.217Z" level=info msg="Workflow already deleted 'argo/artgc-dag-wf-stopped-v9k8t'"
time="2023-10-11T22:20:14.229Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-10-11T22:20:14.235Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/labelPodCompleted
time="2023-10-11T22:20:14.235Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764/labelPodCompleted
time="2023-10-11T22:20:14.239Z" level=debug msg="Create events 201"
time="2023-10-11T22:20:14.242Z" level=debug msg="Create pods/exec 500"
time="2023-10-11T22:20:14.242Z" level=info msg="signaled container" container=main error="unable to upgrade connection: container not found (\"main\")" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495 stderr="<nil>" stdout="<nil>"
time="2023-10-11T22:20:14.243Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-10-11T22:20:14.243Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495
time="2023-10-11T22:20:14.244Z" level=debug msg="Create pods/exec 101"
time="2023-10-11T22:20:14.255Z" level=debug msg="Create events 201"
time="2023-10-11T22:20:14.267Z" level=debug msg="Create events 201"
time="2023-10-11T22:20:14.284Z" level=debug msg="Patch pods 200"
time="2023-10-11T22:20:14.284Z" level=debug msg="Patch pods 200"
time="2023-10-11T22:20:14.305Z" level=debug msg="Create pods/exec 101"
time="2023-10-11T22:20:14.343Z" level=debug msg="Syncing all CronWorkflows"
time="2023-10-11T22:20:14.367Z" level=info msg="signaled container" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764 stderr= stdout="killing 1 with terminated\n"
time="2023-10-11T22:20:14.367Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-10-11T22:20:14.367Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764
time="2023-10-11T22:20:14.386Z" level=debug msg="Create pods/exec 101"
time="2023-10-11T22:20:14.388Z" level=info msg="signaled container" container=wait error="Internal error occurred: error executing command in container: failed to exec in container: failed to create exec \"62b51bd59bb0a40d311c0b4fb64a5c55bec4ece6b598892df0c1b2a9683e9dfa\": task 41567c8e8f2f708d06d5e3aefd1fe01fa0fc8cf61b7143a733d15b76f77a4d10 not found: not found" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495 stderr="<nil>" stdout="<nil>"
time="2023-10-11T22:20:14.476Z" level=info msg="signaled container" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764 stderr= stdout="killing 1 with terminated\n"
time="2023-10-11T22:20:15.283Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.283Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.283Z" level=debug msg="result: &WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-kg8tk-1504799495  argo  7f404222-678e-4b3a-abb9-7e0139b7113a 405207 1 2023-10-11 22:20:14 +0000 UTC <nil> <nil> map[workflows.argoproj.io/workflow:artgc-dag-wf-stopped-kg8tk] map[] [{v1 Pod artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495 66d0f8f6-9b33-4aa2-8048-07d74777df64 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-11 22:20:14 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"66d0f8f6-9b33-4aa2-8048-07d74777df64\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.284Z" level=debug msg="woc.wf.Status.Nodes.Get err: %!s(<nil>)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.284Z" level=debug msg="old: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-1504799495,Name:artgc-dag-wf-stopped-kg8tk.stop-workflow,DisplayName:stop-workflow,Type:Pod,TemplateName:artgc-dag-workflow-stopper,TemplateRef:nil,Phase:Failed,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:workflow shutdown with strategy:  Stop,StartedAt:2023-10-11 22:20:08 +0000 UTC,FinishedAt:2023-10-11 22:20:14 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:0/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.284Z" level=debug msg="newNode: &NodeStatus{ID:artgc-dag-wf-stopped-kg8tk-1504799495,Name:artgc-dag-wf-stopped-kg8tk.stop-workflow,DisplayName:stop-workflow,Type:Pod,TemplateName:artgc-dag-workflow-stopper,TemplateRef:nil,Phase:Failed,BoundaryID:artgc-dag-wf-stopped-kg8tk,Message:workflow shutdown with strategy:  Stop,StartedAt:2023-10-11 22:20:08 +0000 UTC,FinishedAt:2023-10-11 22:20:14 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Children:[],OutboundNodes:[],TemplateScope:local/artgc-dag-wf-stopped-kg8tk,ResourcesDuration:ResourcesDuration{},HostNodeName:k3d-k3s-default-server-0,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:0/1,}" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.284Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-kg8tk-1504799495 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.284Z" level=debug msg="processing Artifact GC Strategy OnWorkflowCompletion" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.284Z" level=debug msg="processing Artifact GC Strategy OnWorkflowCompletion" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.284Z" level=debug msg="No Artifact Search Results returned from strategy OnWorkflowCompletion" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.284Z" level=debug msg="Log changes patch: {\"status\":{\"artifactGCStatus\":{\"strategiesProcessed\":{\"OnWorkflowCompletion\":true}},\"nodes\":{\"artgc-dag-wf-stopped-kg8tk-1504799495\":{\"outputs\":{\"artifacts\":[{\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/main.log\"}}]}}}}}"
time="2023-10-11T22:20:15.284Z" level=info msg="Workflow to be dehydrated" Workflow Size=4541
time="2023-10-11T22:20:15.294Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:15.295Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=405214 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:15.322Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-10-11T22:20:16.287Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.288Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.288Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.288Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.289Z" level=debug msg="list of artifacts pertaining to template artgc-dag-workflow-stopper to WorkflowArtifactGCTask \"artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894-0\": map[artgc-dag-wf-stopped-kg8tk-1504799495:{ArchiveLocation:&ArtifactLocation{ArchiveLogs:*true,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:minio:9000,Bucket:my-bucket,Region:,Insecure:*true,AccessKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:accesskey,Optional:nil,},SecretKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:secretkey,Optional:nil,},RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:{{workflow.name}}/{{pod.name}},},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,} Artifacts:map[main-logs:{Name:main-logs Path: Mode:<nil> From: ArtifactLocation:{ArchiveLogs:<nil> S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/main.log,} Git:nil HTTP:nil Artifactory:nil HDFS:nil Raw:nil OSS:nil GCS:nil Azure:nil} GlobalName: Archive:nil Optional:false SubPath: RecurseMode:false FromExpression: ArtifactGC:nil Deleted:false}]}]" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.289Z" level=debug msg="list of artifacts pertaining to template artgc-dag-delay-stop to WorkflowArtifactGCTask \"artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894-0\": map[artgc-dag-wf-stopped-kg8tk-1504799495:{ArchiveLocation:&ArtifactLocation{ArchiveLogs:*true,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:minio:9000,Bucket:my-bucket,Region:,Insecure:*true,AccessKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:accesskey,Optional:nil,},SecretKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:secretkey,Optional:nil,},RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:{{workflow.name}}/{{pod.name}},},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,} Artifacts:map[main-logs:{Name:main-logs Path: Mode:<nil> From: ArtifactLocation:{ArchiveLogs:<nil> S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/main.log,} Git:nil HTTP:nil Artifactory:nil HDFS:nil Raw:nil OSS:nil GCS:nil Azure:nil} GlobalName: Archive:nil Optional:false SubPath: RecurseMode:false FromExpression: ArtifactGC:nil Deleted:false}]} artgc-dag-wf-stopped-kg8tk-3444961409:{ArchiveLocation:&ArtifactLocation{ArchiveLogs:*true,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:minio:9000,Bucket:my-bucket,Region:,Insecure:*true,AccessKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:accesskey,Optional:nil,},SecretKeySecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:my-minio-cred,},Key:secretkey,Optional:nil,},RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:{{workflow.name}}/{{pod.name}},},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,} Artifacts:map[main-logs:{Name:main-logs Path: Mode:<nil> From: ArtifactLocation:{ArchiveLogs:<nil> S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log,} Git:nil HTTP:nil Artifactory:nil HDFS:nil Raw:nil OSS:nil GCS:nil Azure:nil} GlobalName: Archive:nil Optional:false SubPath: RecurseMode:false FromExpression: ArtifactGC:nil Deleted:false}]}]" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.289Z" level=info msg="Creating Artifact GC Task artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894-0" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.296Z" level=debug msg="Create workflowartifactgctasks 201"
time="2023-10-11T22:20:16.296Z" level=info msg="creating pod to delete artifacts: artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894" namespace=argo strategy=OnWorkflowDeletion workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.303Z" level=debug msg="Create pods 201"
time="2023-10-11T22:20:16.304Z" level=debug msg="Log changes patch: {\"status\":{\"artifactGCStatus\":{\"strategiesProcessed\":{\"OnWorkflowDeletion\":true}}}}"
time="2023-10-11T22:20:16.304Z" level=info msg="Workflow to be dehydrated" Workflow Size=4577
time="2023-10-11T22:20:16.318Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:16.321Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=405223 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:16.337Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-10-11T22:20:17.305Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:17.306Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:17.389Z" level=info msg="cleaning up pod" action=killContainers key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/killContainers
time="2023-10-11T22:20:17.477Z" level=info msg="cleaning up pod" action=killContainers key=argo/artgc-dag-wf-stopped-kg8tk-artgc-dag-artifact-creator-3846913764/killContainers
time="2023-10-11T22:20:17.593Z" level=debug msg="Get leases 200"
time="2023-10-11T22:20:17.599Z" level=debug msg="Update leases 200"
time="2023-10-11T22:20:18.986Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:18.987Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.212Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.213Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.213Z" level=info msg="reconciling artifact-gc pod" message= namespace=argo phase=Succeeded pod=artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.213Z" level=info msg="processing completed Artifact GC Pod \"artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894\"" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.219Z" level=debug msg="List workflowartifactgctasks 200"
time="2023-10-11T22:20:20.219Z" level=debug msg="processing WorkflowArtifactGCTask artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894-0" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.220Z" level=debug msg="deleting WorkflowArtifactGCTask: artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894-0" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.230Z" level=debug msg="Delete workflowartifactgctasks 200"
time="2023-10-11T22:20:20.230Z" level=info msg="no remaining artifacts to GC, removing artifact GC finalizer (forceFinalizerRemoval=false)" namespace=argo workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.235Z" level=debug msg="Log changes patch: {\"metadata\":{\"finalizers\":null},\"status\":{\"artifactGCStatus\":{\"podsRecouped\":{\"artgc-dag-wf-stopped-kg8tk-artgc-wfdel-2470140894\":true}},\"nodes\":{\"artgc-dag-wf-stopped-kg8tk-1504799495\":{\"outputs\":{\"artifacts\":[{\"deleted\":true,\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-workflow-stopper-1504799495/main.log\"}}]}},\"artgc-dag-wf-stopped-kg8tk-3444961409\":{\"outputs\":{\"artifacts\":[{\"deleted\":true,\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-kg8tk/artgc-dag-wf-stopped-kg8tk-artgc-dag-delay-stop-3444961409/main.log\"}}]}}}}}"
time="2023-10-11T22:20:20.235Z" level=info msg="Workflow to be dehydrated" Workflow Size=4597
time="2023-10-11T22:20:20.250Z" level=debug msg="Update workflows 200"
time="2023-10-11T22:20:20.260Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=405223 workflow=artgc-dag-wf-stopped-kg8tk
time="2023-10-11T22:20:20.288Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-10-11T22:20:21.262Z" level=debug msg="Won't process Workflow since it's completed" key=argo/artgc-dag-wf-stopped-kg8tk
```

**Comment by Garett-MacGowan** [comment]
Is there something between `taskResultReconciliation` and `reportResult` which could be stripping the artifact from the `wfv1.NodeResult`?

**Comment by Garett-MacGowan** [comment]
@juliev0 All tests passed this time but I think it might be that 29/~30 chance.

**Comment by juliev0** [comment]
Hmm, any chance that `taskResultReconciliation` occurred prior to `reportResult`?

**Comment by juliev0** [comment]
I am okay to merge something that improves things from 100% to “rarely” for now if you’d like that

**Comment by Garett-MacGowan** [comment]
@juliev0 

> Hmm, any chance that `taskResultReconciliation` occurred prior to `reportResult`?

Good point you make. I think it is possible, and it would explain the issue.

The check for the finalizer removal is the following:

```
// check if all artifacts have been deleted and if so remove Finalizer
removeFinalizer = anyPodSuccess && woc.allArtifactsDeleted()
```

where `woc.allArtifactsDeleted()` is

```
func (woc *wfOperationCtx) allArtifactsDeleted() bool {
	for _, n := range woc.wf.Status.Nodes {
		if n.Type != wfv1.NodeTypePod {
			continue
		}
		for _, a := range n.GetOutputs().GetArtifacts() {
			if !a.Deleted && woc.execWf.GetArtifactGCStrategy(&a) != wfv1.ArtifactGCNever && woc.execWf.GetArtifactGCStrategy(&a) != wfv1.ArtifactGCStrategyUndefined {
				return false
			}
		}
	}
	return true
}
```

Clearly this depends on the state of wf.Status.Nodes, which `taskResultReconciliation()` is suppose to update. If `reportResult` occurs after `taskResultReconciliation()`, but before garbage collection, then the finalizer will be removed and only the previously reported artifacts will be garbage collected.

Thoughts on a solution?

Maybe we could set up a mutex so that the `taskResultReconciliation()` and `garbageCollectArtifacts()` portions of the workflow can't be entered while artifacts are being saved in the wait containers? This would obviously lock the workflow loop any time an artifact is being written. Not sure if this is the best solution. If you think this is ok, is there any guidance you could give for implementation? I'm also not sure how you would test this effectively.

> I am okay to merge something that improves things from 100% to “rarely” for now if you’d like that

It's definitely in a better state than it was regardless of the above. If you're ok to merge it, so am I. It would be nice to get it working 100% though.

File: workflow/controller/operator.go (hunk 2 above)
Comment (Garett-MacGowan) [reply workflow/controller/operator.go:270]: Quick update here: irrespective of if artifacts can be written when `wfv1.WorkflowUnknown` is set, the more important thing with this change is that the reconciliation runs even when the workflow is marked as complete as per `woc.wf.Labels[common.LabelKeyCompleted] == "true"`

**Comment by juliev0** [comment]
Hmm, `allArtifactsDeleted` does seem very problematic. I may not have time right now to fully understand what's happening so may need to get back to you. (I tend to think we should not add a mutex.)

**Comment by Garett-MacGowan** [comment]
> Hmm, `allArtifactsDeleted` does seem very problematic. I may not have time right now to fully understand what's happening so may need to get back to you. (I tend to think we should not add a mutex.)

Yes, it would be best if we could avoid the complexity of the mutex. Thanks, I appreciate the help.

**Comment by juliev0** [comment]
I'm kind of thinking about how we really shouldn't even need to enter `garbageCollectArtifacts()` until the Workflow is completed and the final `taskResultReconciliation()` has occurred...but I wonder if there's a way to detect that.

**Comment by Garett-MacGowan** [comment]
> I'm kind of thinking about how we really shouldn't even need to enter `garbageCollectArtifacts()` until the Workflow is completed and the final `taskResultReconciliation()` has occurred...but I wonder if there's a way to detect that (like if the executor applied some label or annotation to the WorkflowTaskResult to indicate that it was done)...not sure if that makes any sense but thinking off the top of my head...

A fair point, yes we shouldn't need to. I'm trying to implement a solution along the lines of what you describe. Will share it shortly assuming it passes.

> I wonder why I haven't seen this issue before. It doesn't seem particular to stopped workflows. Is it simply because you changed the timing of things?

This particular issue should be relevant for garbage collection on all workflows, you're right. Yeah, it is likely because of the timings. Previously, the task reconciliation happened after garbage collection, so a whole operator loop happens before the next garbage collection, giving time for `reportResult()`

**Comment by Garett-MacGowan** [comment]
@juliev0 Ok, I think I've got it. My logs seem to indicate the issue is resolved in the edge case now. Ran the tests quite a few times and never ran into a failure.

I ended up adding a label, as you suggested. Took the chance to do a minor refactor to the wait container logic since it was a bit confusing to me in its previous state.

**Comment by juliev0** [comment]
> @juliev0 Ok, I think I've got it. My logs seem to indicate the issue is resolved in the edge case now. Ran the tests quite a few times and never ran into a failure.
> 
> I ended up adding a label, as you suggested. Took the chance to do a minor refactor to the wait container logic since it was a bit confusing to me in its previous state.

Great, thanks! I’ll take a look in a few days when I get time.

File: workflow/controller/taskresult.go [hunk 4]
```diff
@@ -83,4 +90,5 @@ func (woc *wfOperationCtx) taskResultReconciliation() {
 			woc.updated = true
 		}
 	}
+	return artifactsWriting
 }
```
Comment (juliev0) [inline workflow/controller/taskresult.go:94]: Is it possible for the TaskResult to have been created and not yet have that label on it and get to here?

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: The task result is upserted [here](https://github.com/argoproj/argo-workflows/blob/f9e026a660b0f4f1f4aca2c7022c00370c555fde/workflow/executor/executor.go#L297) with the label before artifacts are written, so no, I don't think so.

Comment (juliev0) [reply workflow/controller/taskresult.go:94]: Sorry, trying to understand. So, if this method gets called before the label is added and before any artifacts are written, then this method will return false, right? Then "false" will be passed into `garbageCollectArtifacts()`, right? (probably missing something but not sure what yet) :)

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: Yes, if this method gets called before the label is added and before artifacts are written, this method will return false. If any artifacts are in the process of being written, the `common.LabelKeyWritingArtifact` label will be `true`, which will prevent garbage collection for at least this loop through the controller.

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: `common.LabelKeyWritingArtifact` is set to false once `reportResult` of executor.go happens.

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: @juliev0 Sorry, I misunderstood your original question. Yes, it is possible for the TaskResult to have been created without the label (in `monitorProgress` of executor.go`).

Comment (juliev0) [reply workflow/controller/taskresult.go:94]: So, continuing with the scenario where this method gets called before the label is ever added and then returns false, we will enter into `processArtifactGCCompletion()`, right? Isn't it possible to prematurely remove the finalizer?

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: `processArtifactGCCompletion` still checks `removeFinalizer = anyPodSuccess && woc.allArtifactsDeleted()`. The problem before was that there was an unreported artifact (due to the race condition), which allowed the finalizer to be removed. The new label makes it so that we don't enter `processArtifactGCCompletion` if we know an artifact hasn't been reported yet.

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: Hmm... it might be possible that it would prematurely remove the finalizer if the reconciliation and GC happens before an artifact is even attempted to be written... E.g. if one wait container takes a long time for some reason?

If that's the case, perhaps it would be safer to add something like the following at the beginning of the wait container before `wfExecutor.Wait(ctx)`?:

```
func (we *WorkflowExecutor) ExpectArtifact(ctx context.Context) error {
	if len(we.Template.Outputs.Artifacts) == 0 {
		return nil
	}

	// Create an empty task result with a label to indicate that artifacts are to be written. Prevents garbage collection race condition.
	err = we.reportResult(ctx, wfv1.NodeResult{}, map[string]string{common.LabelKeyWritingArtifact: "true"})
	if err != nil {
		return err
	}
}
```

Logically, this would imply "don't process artifact GC completion until all the wait containers with artifacts to write are done.

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: `we.monitorProgress` (the only other instance where `reportResult` is called), is called in `wfExecutor.Wait(ctx)`, so the solution above would ensure the label is always set when there are artifacts to be written.

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: Or even better, we can put the above in the the `init` container? I assume the init container always runs before the `main` container?

Comment (juliev0) [reply workflow/controller/taskresult.go:94]: What if instead of the current Label, we have something simple which indicates whether the TaskResult has been fully written, and when the TraskResult gets created it starts off with that label set to false?

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: I can implement what you're suggesting as it might be easier to understand. I'll make it so that when the wait container starts, it creats an empty task result with an unfinished label, and then just before it exits, I'll switch the label to true. In reconciliation, all results must be marked finished, and then `processArtifactGCCompletion()` can proceed.

How does this sound?

Comment (juliev0) [reply workflow/controller/taskresult.go:94]: Yes, that would be great. Thank you. I'm thinking there could be some `defer` at the top of `waitContainer()` which will make it so this label gets set true even if we prematurely exit that method for some reason. And that would call some method of `wfExecutor`. Is this what you're thinking?

File: workflow/controller/artifact_gc.go [hunk 5]
```diff
@@ -64,6 +64,12 @@ func (woc *wfOperationCtx) garbageCollectArtifacts(ctx context.Context) error {
 		}
 	}
 
+	if artifactsWriting {
+		// If we don't do this, a race condition can occur where only some artifacts are garbage collected and finalizers are prematurely removed.
+		woc.log.Debug("Skipping garbage collection completion due to in-progress artifact reporting.")
+		return nil
+	}
+
```
Comment (juliev0) [inline workflow/controller/artifact_gc.go:72]: instead of passing in `artifactsWriting`, can we remove `processArtifactGCCompletion()` from this function, and have the caller conditionally call `processArtifactGCCompletion()`?

File: test/e2e/functional_test.go [hunk 6]
```diff
@@ -28,7 +28,7 @@ func (s *FunctionalSuite) TestArchiveStrategies() {
 		Workflow(`@testdata/archive-strategies.yaml`).
 		When().
 		SubmitWorkflow().
-		WaitForWorkflow(time.Minute).
+		WaitForWorkflow(time.Minute + time.Second*30).
```
Comment (juliev0) [inline test/e2e/functional_test.go:31]: nitpick: could we change these to `time.Second*90` for more conciseness and one less computation?

File: workflow/controller/artifact_gc.go (hunk 5 above)
Comment (juliev0) [reply workflow/controller/artifact_gc.go:72]: actually, wait...now I'm thinking about whether we need to be preventing `processArtifactGCStrategy()` from running as well, since it sort of relies on the Artifacts being in the Node Outputs as well.

Comment (juliev0) [reply workflow/controller/artifact_gc.go:72]: I'm thinking the part we should do early on is the adding of the finalizer (section starting on line 42). Everything after that we shouldn't. Can we break it into two methods? Maybe the first can just be called `addArtifactGCFinalizer()` or something and the second one can continue to remain as `garbageCollectArtifacts()`? something like that?

Comment (Garett-MacGowan) [reply workflow/controller/artifact_gc.go:72]: Sounds good. I'll do that.

File: test/e2e/functional_test.go (hunk 6 above)
Comment (Garett-MacGowan) [reply test/e2e/functional_test.go:31]: Yeah, good point.

File: workflow/controller/taskresult.go (hunk 4 above)
Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: Due to the nature of reconciliation + the fact that wait containers finish at different times, I found it necessary to set up some state in `wfOperationCtx` which tracks completions on a per task-result basis, maintaining completion status between reconciliation runs.

Previously, It was possible that reconciliation could execute and there only be one task-result in the list of objects, even if there were multiple artifacts in the workflow. This would cause false positives for "all complete" logic since it looks as though all have completed but only one had actually completed.

I've modified the test case to increase the frequency of the race condition (though it's not 100%, it's better than ~1/30). I'm running a battery of tests now.

Comment (juliev0) [reply workflow/controller/taskresult.go:94]: There’s one task result per workflow pod that executes I think, right? Or is it one task result per Workflow?

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: Per pod.

Comment (juliev0) [reply workflow/controller/taskresult.go:94]: "Previously, It was possible that reconciliation could execute and there only be one task-result in the list of objects, even if there were multiple artifacts in the workflow." - that could happen for a Workflow running just one Pod which has multiple output artifacts, right?

Comment (juliev0) [reply workflow/controller/taskresult.go:94]: Perhaps once your commit is in, I can see what you mean better...

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: Sorry, my comment was very unclear. "previously" was the wrong word. It can happen with one pod and multiple artifacts. E,g. the user-defined artifact as well as the container log artifact. I'm not really sure how it's happening with the log artifact + user-defined artifact for a given container since they are reported at the same time in the `wait` container (`outputs.Artifacts = append(outputs.Artifacts, logArtifacts...)` The `SharedInformer` cache's must not represent state changes of the entire target object all at once? By extension, it happens with multiple user-defined artifacts across multiple pods. 

I had to modify the state I mentioned above, as `wfOperationCtx` doesn't persist across each operator loop. I ended up putting it in with `ArtifactGCStatus`.

I will push shortly.

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: Ok, still getting intermittent errors, but I think I found the issue:

```
time="2023-10-25T15:37:21.967Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:21.967Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:21.967Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:21.967Z" level=info msg="Updated message  -> Stopped with strategy 'Stop'" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:21.967Z" level=info msg="Marking workflow completed" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:21.967Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-wfwgk\", UID:\"c9e57468-6cb8-4f95-8b97-29908ac7015d\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"619562\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowFailed' Stopped with strategy 'Stop'"
time="2023-10-25T15:37:21.968Z" level=debug msg="Log changes patch: {\"metadata\":{\"labels\":{\"workflows.argoproj.io/completed\":\"true\",\"workflows.argoproj.io/phase\":\"Failed\"}},\"status\":{\"conditions\":[{\"status\":\"True\",\"type\":\"PodRunning\"},{\"status\":\"True\",\"type\":\"Completed\"}],\"finishedAt\":\"2023-10-25T15:37:21Z\",\"message\":\"Stopped with strategy 'Stop'\",\"nodes\":{\"artgc-dag-wf-stopped-wfwgk\":{\"finishedAt\":\"2023-10-25T15:37:21Z\",\"outboundNodes\":[\"artgc-dag-wf-stopped-wfwgk-3359801380\",\"artgc-dag-wf-stopped-wfwgk-3058715464\"],\"phase\":\"Failed\"},\"artgc-dag-wf-stopped-wfwgk-3058715464\":{\"finishedAt\":\"2023-10-25T15:37:21Z\",\"message\":\"workflow shutdown with strategy:  Stop\",\"phase\":\"Failed\"},\"artgc-dag-wf-stopped-wfwgk-3359801380\":{\"finishedAt\":\"2023-10-25T15:37:21Z\",\"message\":\"workflow shutdown with strategy:  Stop\",\"phase\":\"Failed\"}},\"phase\":\"Failed\"}}"
time="2023-10-25T15:37:21.968Z" level=info msg="Workflow to be dehydrated" Workflow Size=5874
time="2023-10-25T15:37:21.972Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380/terminateContainers
time="2023-10-25T15:37:21.972Z" level=info msg="cleaning up pod" action=deletePod key=argo/artgc-dag-wf-stopped-wfwgk-1340600742-agent/deletePod
time="2023-10-25T15:37:21.972Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=main&stderr=true&stdout=true&tty=false"
time="2023-10-25T15:37:21.973Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380
time="2023-10-25T15:37:21.972Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464/terminateContainers
time="2023-10-25T15:37:21.973Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=main&stderr=true&stdout=true&tty=false"
time="2023-10-25T15:37:21.973Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464
time="2023-10-25T15:37:21.973Z" level=debug msg="Create events 201"
time="2023-10-25T15:37:21.978Z" level=debug msg="Update workflows 200"
time="2023-10-25T15:37:21.979Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=619565 workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:21.980Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-wfwgk\", UID:\"c9e57468-6cb8-4f95-8b97-29908ac7015d\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"619565\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artgc-dag-wf-stopped-wfwgk.stop-workflow: workflow shutdown with strategy:  Stop"
time="2023-10-25T15:37:21.980Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-wfwgk\", UID:\"c9e57468-6cb8-4f95-8b97-29908ac7015d\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"619565\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-wfwgk.stop-workflow: workflow shutdown with strategy:  Stop"
time="2023-10-25T15:37:21.980Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-wfwgk\", UID:\"c9e57468-6cb8-4f95-8b97-29908ac7015d\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"619565\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-wfwgk.create-artifact-2: workflow shutdown with strategy:  Stop"
time="2023-10-25T15:37:21.980Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-wfwgk\", UID:\"c9e57468-6cb8-4f95-8b97-29908ac7015d\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"619565\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-wfwgk"
time="2023-10-25T15:37:21.981Z" level=debug msg="Delete pods 404"
time="2023-10-25T15:37:21.994Z" level=debug msg="Create events 201"
time="2023-10-25T15:37:22.002Z" level=debug msg="Create events 201"
time="2023-10-25T15:37:22.011Z" level=debug msg="Create events 201"
time="2023-10-25T15:37:22.017Z" level=debug msg="Create events 201"
time="2023-10-25T15:37:22.019Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-10-25T15:37:22.025Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464/labelPodCompleted
time="2023-10-25T15:37:22.025Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380/labelPodCompleted
time="2023-10-25T15:37:22.036Z" level=debug msg="Patch pods 200"
time="2023-10-25T15:37:22.038Z" level=debug msg="Patch pods 200"
time="2023-10-25T15:37:22.058Z" level=debug msg="Create pods/exec 500"
time="2023-10-25T15:37:22.058Z" level=info msg="signaled container" container=main error="unable to upgrade connection: container not found (\"main\")" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464 stderr="<nil>" stdout="<nil>"
time="2023-10-25T15:37:22.058Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-10-25T15:37:22.058Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464
time="2023-10-25T15:37:22.059Z" level=debug msg="Create pods/exec 101"
time="2023-10-25T15:37:22.078Z" level=debug msg="Create pods/exec 101"
time="2023-10-25T15:37:22.127Z" level=info msg="signaled container" container=wait error="command terminated with exit code 137" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464 stderr="<nil>" stdout="<nil>"
time="2023-10-25T15:37:22.148Z" level=info msg="signaled container" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380 stderr= stdout="killing 1 with terminated\n"
time="2023-10-25T15:37:22.148Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-10-25T15:37:22.148Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380
time="2023-10-25T15:37:22.164Z" level=debug msg="Create pods/exec 101"
time="2023-10-25T15:37:22.311Z" level=info msg="signaled container" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380 stderr= stdout="killing 1 with terminated\n"
time="2023-10-25T15:37:22.969Z" level=debug msg="Syncing all CronWorkflows"
time="2023-10-25T15:37:23.040Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.041Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.041Z" level=debug msg="task result:\n&WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-wfwgk-3058715464  argo  2caee164-7b62-4046-86ce-b19838b09efe 619575 1 2023-10-25 15:37:22 +0000 UTC <nil> <nil> map[workflows.argoproj.io/report-outputs-completed:true workflows.argoproj.io/workflow:artgc-dag-wf-stopped-wfwgk] map[] [{v1 Pod artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464 6bcf6446-89a2-4a7b-a1b9-3c546e06cbec <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-10-25 15:37:22 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/report-outputs-completed\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"6bcf6446-89a2-4a7b-a1b9-3c546e06cbec\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-wfwgk/artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.041Z" level=debug msg="task result name:\nartgc-dag-wf-stopped-wfwgk-3058715464" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.041Z" level=debug msg="task result counter:\nmap[artgc-dag-wf-stopped-wfwgk-1114725310:0 artgc-dag-wf-stopped-wfwgk-3058715464:0 artgc-dag-wf-stopped-wfwgk-3359801380:1 artgc-dag-wf-stopped-wfwgk-3410134237:0]" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.041Z" level=debug msg="task result counter len: 4" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.041Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-wfwgk-3058715464 workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.041Z" level=debug msg="Skipping artifact GC" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.042Z" level=debug msg="Log changes patch: {\"status\":{\"nodes\":{\"artgc-dag-wf-stopped-wfwgk-3058715464\":{\"outputs\":{\"artifacts\":[{\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-wfwgk/artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464/main.log\"}}]}}}}}"
time="2023-10-25T15:37:23.042Z" level=info msg="Workflow to be dehydrated" Workflow Size=6064
time="2023-10-25T15:37:23.237Z" level=debug msg="Update workflows 200"
time="2023-10-25T15:37:23.237Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=619577 workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.258Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-10-25T15:37:23.419Z" level=debug msg="Get leases 200"
time="2023-10-25T15:37:23.426Z" level=debug msg="Update leases 200"
time="2023-10-25T15:37:24.242Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:24.243Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:24.243Z" level=debug msg="Skipping artifact GC" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:25.128Z" level=info msg="cleaning up pod" action=killContainers key=argo/artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464/killContainers
time="2023-10-25T15:37:25.312Z" level=info msg="cleaning up pod" action=killContainers key=argo/artgc-dag-wf-stopped-wfwgk-artgc-dag-artifact-creator-2-3359801380/killContainers
```

Important lines are:
```
time="2023-10-25T15:37:22.127Z" level=info msg="signaled container" container=wait error="command terminated with exit code 137" namespace=argo pod=artgc-dag-wf-stopped-wfwgk-artgc-dag-workflow-stopper-3058715464 stderr="<nil>" stdout="<nil>"
```
and
```
time="2023-10-25T15:37:23.041Z" level=debug msg="task result counter:\nmap[artgc-dag-wf-stopped-wfwgk-1114725310:0 artgc-dag-wf-stopped-wfwgk-3058715464:0 artgc-dag-wf-stopped-wfwgk-3359801380:1 artgc-dag-wf-stopped-wfwgk-3410134237:0]" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
time="2023-10-25T15:37:23.041Z" level=debug msg="task result counter len: 4" namespace=argo workflow=artgc-dag-wf-stopped-wfwgk
```

The wait container is being killed when the test fails.

I'm thinking it is to do with the following not being at the top level of the wait container:
```
ctx := context.Background() // don't allow cancellation to impact capture of results, parameters, or artifacts
```
`NewWaitCommand` looks like this:
```
func NewWaitCommand() *cobra.Command {
	command := cobra.Command{
		Use:   "wait",
		Short: "wait for main container to finish and save artifacts",
		Run: func(cmd *cobra.Command, args []string) {
			ctx := cmd.Context()
			err := waitContainer(ctx)
			if err != nil {
				log.Fatalf("%+v", err)
			}
		},
	}
	return &command
}
```
I think `cmd.Context()` should be `ctx.Background()`, no?

Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:94]: Hmm, still not it.

```
time="2023-10-25T17:49:35.706Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-pxhfh-artgc-dag-artifact-creator-2-428993330
time="2023-10-25T17:49:35.706Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-pxhfh-artgc-dag-workflow-stopper-2323127074
time="2023-10-25T17:49:35.709Z" level=debug msg="Create events 201"
time="2023-10-25T17:49:35.709Z" level=info msg="cleaning up pod" action=deletePod key=argo/artgc-dag-wf-stopped-pxhfh-1340600742-agent/deletePod
time="2023-10-25T17:49:35.714Z" level=debug msg="Update workflows 200"
time="2023-10-25T17:49:35.715Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=634290 workflow=artgc-dag-wf-stopped-pxhfh
time="2023-10-25T17:49:35.715Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-pxhfh\", UID:\"66ecac64-54a8-4f40-bf89-ec795ab52ad3\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"634290\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-pxhfh"
time="2023-10-25T17:49:35.715Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-pxhfh\", UID:\"66ecac64-54a8-4f40-bf89-ec795ab52ad3\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"634290\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artgc-dag-wf-stopped-pxhfh.stop-workflow: workflow shutdown with strategy:  Stop"
time="2023-10-25T17:49:35.715Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-pxhfh\", UID:\"66ecac64-54a8-4f40-bf89-ec795ab52ad3\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"634290\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-pxhfh.stop-workflow: workflow shutdown with strategy:  Stop"
time="2023-10-25T17:49:35.715Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-pxhfh\", UID:\"66ecac64-54a8-4f40-bf89-ec795ab52ad3\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"634290\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-pxhfh.create-artifact-2: workflow shutdown with strategy:  Stop"
time="2023-10-25T17:49:35.720Z" level=info msg="Queueing Failed workflow argo/artgc-dag-wf-stopped-dhvxd for delete due to max rention(2 workflows)"
time="2023-10-25T17:49:35.720Z" level=info msg="Deleting garbage collected workflow 'argo/artgc-dag-wf-stopped-dhvxd'"
time="2023-10-25T17:49:35.728Z" level=debug msg="Delete pods 404"
time="2023-10-25T17:49:35.733Z" level=debug msg="Create events 201"
time="2023-10-25T17:49:35.744Z" level=debug msg="Delete workflows 404"
time="2023-10-25T17:49:35.744Z" level=info msg="Workflow already deleted 'argo/artgc-dag-wf-stopped-dhvxd'"
time="2023-10-25T17:49:35.747Z" level=debug msg="Create events 201"
time="2023-10-25T17:49:35.754Z" level=debug msg="Create events 201"
time="2023-10-25T17:49:35.758Z" level=debug msg="Create pods/exec 101"
time="2023-10-25T17:49:35.759Z" level=debug msg="Create pods/exec 101"
time="2023-10-25T17:49:35.767Z" level=debug msg="Create events 201"
time="2023-10-25T17:49:35.772Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-10-25T17:49:35.778Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-pxhfh-artgc-dag-workflow-stopper-2323127074/labelPodCompleted
time="2023-10-25T17:49:35.778Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-pxhfh-artgc-dag-artifact-creator-2-428993330/labelPodCompleted
time="2023-10-25T17:49:35.791Z" level=debug msg="Patch pods 200"
time="2023-10-25T17:49:35.791Z" level=debug msg="Patch pods 200"
time="2023-10-25T17:49:35.819Z" level=info msg="signaled container" container=main error="Internal error occurred: error executing command in container: failed to exec in container: failed to create exec \"c7d9abff3b18c09bb17e19d4c45a6c48256fc5b536c383043e5b683ff7f4c1f1\": task 06a801f5c6bdf2576ffa32494b941be68fa3a0e30e0ef5f15b893e1632d7f46c not found: not found" namespace=argo pod=artgc-dag-wf-stopped-pxhfh-artgc-dag-workflow-stopper-2323127074 stderr="<nil>" stdout="<nil>"
time="2023-10-25T17:49:35.819Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-pxhfh-artgc-dag-workflow-stopper-2323127074/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-10-25T17:49:35.819Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-pxhfh-artgc-dag-workflow-stopper-2323127074
time="2023-10-25T17:49:35.866Z" level=info msg="signaled container" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-pxhfh-artgc-dag-artifact-creator-2-428993330 stderr= stdout="killing 1 with terminated\n"
time="2023-10-25T17:49:35.866Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-pxhfh-artgc-dag-artifact-creator-2-428993330/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-10-25T17:49:35.867Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-pxhfh-artgc-dag-artifact-creator-2-428993330
time="2023-10-25T17:49:35.867Z" level=debug msg="Create pods/exec 101"
time="2023-10-25T17:49:35.881Z" level=info msg="signaled container" container=wait error="Internal error occurred: error executing command in container: failed to exec in container: failed to create exec \"81ed5a77b9b27168c3fa79c2d23eee476dfd30bd48107dbb4c8135a10109cf10\": cannot exec in a stopped state: unknown" namespace=argo pod=artgc-dag-wf-stopped-pxhfh-artgc-dag-workflow-stopper-2323127074 stderr="<nil>" stdout="<nil>"
time="2023-10-25T17:49:35.887Z" level=debug msg="Create pods/exec 101"
time="2023-10-25T17:49:36.017Z" level=info msg="signaled container" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-pxhfh-artgc-dag-artifact-creator-2-428993330 stderr= stdout="killing 1 with terminated\n"
```

**Comment by juliev0** [comment]
Sorry this issue turned into way more than you originally bargained for! But it does seem like you're uncovering some core potential problems here.

**Comment by Garett-MacGowan** [comment]
It's taking me way too long to reproduce the issue. I can't find a way to make it more probable. I think I might have to move on for now. Failure rate should be much better than before. 

Let me know what you think of the latest rendition of the fix @juliev0

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 7]
```diff
@@ -1336,6 +1336,9 @@ type ArtGCStatus struct {
 
 	// if this is true, we already checked to see if we need to do it and we don't
 	NotSpecified bool `json:"notSpecified,omitempty" protobuf:"varint,3,opt,name=notSpecified"`
+
+	// Have task results been completed? (mapped by Pod name) used to prevent premature garbage collection of artifacts.
+	TaskResultsCompleted map[string]bool `json:"taskResultsCompleted,omitempty" protobuf:"bytes,4,opt,name=taskResultsCompleted"`
```
Comment (juliev0) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:1341]: can we move it to outside of the ArtGCStatus, since it's relevant outside of ArtifactGC?

Comment (Garett-MacGowan) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:1341]: Sure, do you have a preference?

File: workflow/executor/executor.go [hunk 8]
```diff
@@ -780,25 +791,27 @@ func (we *WorkflowExecutor) CaptureScriptResult(ctx context.Context) error {
 	return nil
 }
 
+func (we *WorkflowExecutor) reportOutputsCompleted(ctx context.Context) error {
+	return we.reportResult(ctx, wfv1.NodeResult{}, map[string]string{common.LabelKeyReportOutputsCompleted: "true"})
+}
```
Comment (juliev0) [inline workflow/executor/executor.go:796]: is this adding an empty NodeResult? It looks like you're doing this in the defer in wait.go, meaning you add a NodeResult with Outputs at the end of the function and then add an empty NodeResult?

Comment (Garett-MacGowan) [reply workflow/executor/executor.go:796]: My bad, I should be able to pass null instead of an empty noderesult, I think. It should upsert.

File: pkg/apis/workflow/v1alpha1/workflow_types.go (hunk 7 above)
Comment (Garett-MacGowan) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:1341]: Maybe in `Outputs` or top level?

File: workflow/executor/executor.go (hunk 8 above)
Comment (juliev0) [reply workflow/executor/executor.go:796]: So, what I was thinking was this: remove all of the existing changes in wait.go and all of the report methods here. In the createTaskResult() function set this label to false. Then in wait.go do a `defer wfExecutor.FinalizeOutput()`. That method just upserts the label set to true. See any reason that can't work or isn't good design? It seems simple anyway.

Comment (juliev0) [reply workflow/executor/executor.go:796]: or let me know if you had something else in mind and I can try to advise based on that...I would for one like to remove the fact that two different reportOutputs-type methods are called at the end of the wait function

File: pkg/apis/workflow/v1alpha1/workflow_types.go (hunk 7 above)
Comment (juliev0) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:1341]: Hmm, let's go with top level?

File: workflow/executor/executor.go (hunk 8 above)
Comment (Garett-MacGowan) [reply workflow/executor/executor.go:796]: @juliev0 Do you mean combining the `wfExecutor.ReportOutputs` and `wfExecutor.ReportOutputsCompleted` functions? If so, I will need to add some state to avoid having to pass `logArtifacts` directly to the deferred `ReportOutputs` function. I'm thinking it would make most sense to add the state to  `executor.WorkflowExecutor` in the same way that `error` exists there.

Comment (juliev0) [reply workflow/executor/executor.go:796]: Is the purpose of `reportOutputsCompleted()` to simply add the label? If that's the case then why does it need to be added to `reportOutputs`?

Comment (Garett-MacGowan) [reply workflow/executor/executor.go:796]: Yes, it is to add the label. As you requested previously, it's mostly there as a backup incase there is a random failure that isn't caught. I'm happy to remove the label setting from `reportOutputs` since it should be set either way in the defer.

As per why we don't just go back to calling reportOutputs in `SaveLogs`, I didn't like it there since it seemed like the responsibility of `SaveLogs` should not include reporting outputs (since not all outputs are logs). This confused me when I was trying to debug the issue since I didn't expect it there.

Comment (juliev0) [reply workflow/executor/executor.go:796]: (if what i'm saying doesn't make sense I can try to clarify better - but it's basically the idea I was trying to capture [here](https://github.com/argoproj/argo-workflows/pull/11947/files#r1373975383))

Comment (juliev0) [reply workflow/executor/executor.go:796]: "As per why we don't just go back to calling reportOutputs in SaveLogs, I didn't like it there since it seemed like the responsibility of SaveLogs should not include reporting outputs (since not all outputs are logs). This confused me when I was trying to debug the issue since I didn't expect it there." - Oh, yes. Great point. i didn't realize that. Then let's keep doing that.

Comment (juliev0) [reply workflow/executor/executor.go:796]: "I'm happy to remove the label setting from reportOutputs since it should be set either way in the defer." Thanks so much. I think in that case `reportResult()` can remain as it was before (just reports NodeResults). (I apologize if I'm being too controlling. I'm still learning how to strike the right balance as a reviewer. Feel free to let me know if I make a bad suggestion.) :)

Comment (Garett-MacGowan) [reply workflow/executor/executor.go:796]: No problem. I'm implementing the change now.

**Comment by Garett-MacGowan** [comment]
I had to push a **potentially** incomplete commit, since I'm out of office for the weekend. I think it got past the critical part of make pre-commit -B. If not, will fix later today or tomorrow.

File: workflow/executor/executor.go (hunk 8 above)
Comment (juliev0) [reply workflow/executor/executor.go:811]: looks good! thank you!

File: workflow/common/common.go [hunk 9]
```diff
@@ -94,6 +97,8 @@ const (
 	LabelKeyOnExit = workflow.WorkflowFullName + "/on-exit"
 	// LabelKeyArtifactGCPodHash is a label applied to WorkflowTaskSets used by the Artifact Garbage Collection Pod
 	LabelKeyArtifactGCPodHash = workflow.WorkflowFullName + "/artifact-gc-pod"
+	// LabelKeyReportOutputsCompleted is a label applied to WorkflowTaskResults indicating whether all the outputs have been reported.
+	LabelKeyReportOutputsCompleted = workflow.WorkflowFullName + "/report-outputs-completed"
```
Comment (juliev0) [inline workflow/common/common.go:102]: Wait, I think I missed something. I thought there would be a label or an annotation, but why both? Were you transitioning from using a Label to an Annotation and didn't completely switch over?

File: workflow/executor/executor.go [hunk 10]
```diff
@@ -780,17 +791,34 @@ func (we *WorkflowExecutor) CaptureScriptResult(ctx context.Context) error {
...
+		Factor:   2,
+		Jitter:   0.1,
+		Steps:    5,
+		Cap:      30 * time.Second,
+	}, errorsutil.IsTransientErr, func() error {
+		err := we.patchTaskResultLabels(ctx, map[string]string{
+			common.LabelKeyReportOutputsCompleted: "true",
+		})
+		if apierr.IsForbidden(err) {
+			log.WithError(err).Warn("failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/")
```
Comment (Garett-MacGowan) [inline workflow/executor/executor.go:806]: @juliev0 In accordance with the logic in `reportResult()` of `executor.go`, I am using the annotation as a backup for "legacy/insecure pod patch". Let me know if you think this is unnecessary.

Comment (juliev0) [reply workflow/executor/executor.go:806]: I see. Can you add a comment here to indicate that the pod annotation is being added as a backup?

File: workflow/controller/taskresult.go (hunk 4 above)
Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go]: It turns out that with the new usage of `finalizeOutput` in the wait container `defer`, the `context.Background()` is now necessary at the top level, or the wait container will be killed before the defer runs.

File: workflow/executor/executor.go [hunk 11]
```diff
@@ -608,13 +609,23 @@ func (we *WorkflowExecutor) SaveLogs(ctx context.Context) {
...
 		we.AddError(err)
 	}
 }
 
+func (we *WorkflowExecutor) FinalizeOutput(ctx context.Context) {
+	err := we.finalizeOutput(ctx)
+	if err != nil {
+		we.AddError(err)
+	}
+}
```
Comment (juliev0) [inline workflow/executor/executor.go:627]: do we need to have 2 levels of methods: exposed and unexposed? I don't think the other methods here are doing that, right? I'd be interested in keeping it more concise and consistent.

Comment (Garett-MacGowan) [reply workflow/executor/executor.go:627]: Will do.

File: cmd/argoexec/commands/wait.go [hunk 12]
```diff
@@ -35,7 +36,10 @@ func waitContainer(ctx context.Context) error {
 	if err != nil {
 		wfExecutor.AddError(err)
 	}
-	ctx = context.Background() // don't allow cancellation to impact capture of results, parameters,or artifacts
+
+	// Don't allow cancellation to impact capture of results, parameters, or artifacts
+	ctx = context.Background()
+
```
Comment (juliev0) [inline cmd/argoexec/commands/wait.go:42]: Regarding your comment related to context: good finding. I think the call to `wfExecutor.Wait(ctx)` above still needs `ctx` to be set as it was. So, is the solution to maybe pass `context.Background()` into your defer as an argument? (which makes me wonder if the other defer there should as well)

Comment (Garett-MacGowan) [reply cmd/argoexec/commands/wait.go:42]: Yeah, that sounds right.

Comment (Garett-MacGowan) [reply cmd/argoexec/commands/wait.go:42]: Are you ok with the following? Note the use of bgCtx

```
func waitContainer(ctx context.Context) error {
	wfExecutor := initExecutor()
	
	// Don't allow cancellation to impact capture of results, parameters, artifacts, or defers.
	bgCtx := context.Background()

	defer wfExecutor.HandleError(bgCtx)    // Must be placed at the bottom of defers stack.
	defer wfExecutor.FinalizeOutput(bgCtx) // Ensures the LabelKeyReportOutputsCompleted is set to true.
	defer stats.LogStats()
	stats.StartStatsTicker(5 * time.Minute)

	// Wait for main container to complete
	err := wfExecutor.Wait(ctx)
	if err != nil {
		wfExecutor.AddError(err)
	}

	// Capture output script result
	err = wfExecutor.CaptureScriptResult(bgCtx)
	if err != nil {
		wfExecutor.AddError(err)
	}

	// Saving output parameters
	err = wfExecutor.SaveParameters(bgCtx)
	if err != nil {
		wfExecutor.AddError(err)
	}

	// Saving output artifacts
	err = wfExecutor.SaveArtifacts(bgCtx)
	if err != nil {
		wfExecutor.AddError(err)
	}
 
	// Save log artifacts
	logArtifacts := wfExecutor.SaveLogs(bgCtx)

	// Try to upsert TaskResult. If it fails, we will try to update the Pod's Annotations
	wfExecutor.ReportOutputs(bgCtx, logArtifacts)

	return wfExecutor.HasError()
}
```

**Comment by Garett-MacGowan** [comment]
@juliev0 Failing tests are timeout related. Are these tests known to be flakey? I believe these should be unrelated to the `E2E_WAIT_TIMEOUT` and `E2E_WAIT_TIMEOUT_BIAS` changes

File: workflow/common/common.go [hunk 13]
```diff
@@ -51,6 +51,9 @@ const (
 	// AnnotationKeyProgress is N/M progress for the node
 	AnnotationKeyProgress = workflow.WorkflowFullName + "/progress"
 
+	// AnnotationKeyReportOutputsCompleted is annotation indicating outputs have completed
+	AnnotationKeyReportOutputsCompleted = workflow.WorkflowFullName + "/report-outputs-completed"
+
```
[the remark this answers is not in the document]
Comment (juliev0) [reply workflow/common/common.go:57]: thanks...can you change "incase" to "in case"?

File: cmd/argoexec/commands/wait.go [hunk 14]
```diff
@@ -26,7 +26,12 @@ func NewWaitCommand() *cobra.Command {
 
 func waitContainer(ctx context.Context) error {
 	wfExecutor := initExecutor()
-	defer wfExecutor.HandleError(ctx) // Must be placed at the bottom of defers stack.
+
+	// Don't allow cancellation to impact capture of results, parameters, artifacts, or defers.
+	bgCtx := context.Background()
```
Comment (juliev0) [inline cmd/argoexec/commands/wait.go:31]: use of `bgCtx` looks good

**Comment by juliev0** [comment]
> @juliev0 Failing tests are timeout related. Are these tests known to be flakey? I believe these should be unrelated to the `E2E_WAIT_TIMEOUT` and `E2E_WAIT_TIMEOUT_BIAS` changes

There are flakey tests out there - if you don't think they're related, then keep issuing empty commits and hopefully you can get it to pass (although, you may not want to invest a lot of effort in that if I may still ask for changes...up to you)

File: test/e2e/functional_test.go [hunk 15]
```diff
@@ -28,7 +28,7 @@ func (s *FunctionalSuite) TestArchiveStrategies() {
 		Workflow(`@testdata/archive-strategies.yaml`).
 		When().
 		SubmitWorkflow().
-		WaitForWorkflow(time.Minute).
+		WaitForWorkflow(time.Second * 90).
```
Comment (juliev0) [inline test/e2e/functional_test.go:31]: How did you go about finding all the places to change this? If I do "Find all References" from my VSCODE IDE for `WaitForWorkflow()`, I think I see a bunch of other places where a time is being passed in (agent_test.go, cron_test.go, etc)

Comment (juliev0) [reply test/e2e/functional_test.go:31]: (if you change them I'd say you don't need to strictly add 30 seconds each time by the way - adding a little extra is good too - e.g. I think it would be weird to change 5 to 35 and might as well round up to 45 seconds or a minute)

Comment (Garett-MacGowan) [reply test/e2e/functional_test.go:31]: If I recall correctly, I only changed the instances where the tests were failing.

Comment (juliev0) [reply test/e2e/functional_test.go:31]: Have you tried to do it any time a test failed even once? I’m a little concerned about creating new failures that are very intermittent but sometimes do time out

Comment (Garett-MacGowan) [reply test/e2e/functional_test.go:31]: Yeah, I haven't seen failures for the other cases. I've been keeping an eye on that as a potential issue.

If you want to ensure the exact behavior as before, I can add 30 seconds to all cases. I can round up to the nearest 15 seconds as you've suggested above, too.

Comment (juliev0) [reply test/e2e/functional_test.go:31]: That would be really great! Thank you!

**Comment by Garett-MacGowan** [comment]
@juliev0 On this test run, we get this failure:

```
Not equal: 
      expected: "OOMKilled (exit code 137): "
      actual  : "Error (exit code 137): "
```

Test is:
```
ExpectWorkflow(func(t *testing.T, metadata *metav1.ObjectMeta, status *wfv1.WorkflowStatus) {
	assert.Equal(t, wfv1.WorkflowFailed, status.Phase)
	assert.Equal(t, "OOMKilled (exit code 137)", status.Message)
	one := status.Nodes.FindByDisplayName("one")
	if assert.NotNil(t, one) {
		assert.Equal(t, wfv1.NodeFailed, one.Phase)
		assert.Equal(t, "OOMKilled (exit code 137): ", one.Message)
	}
	two := status.Nodes.FindByDisplayName("two")
	if assert.NotNil(t, two) {
		assert.Equal(t, wfv1.NodeFailed, two.Phase)
		assert.Equal(t, "Error (exit code 143): ", two.Message)
	}
})
```

The error code is the same. I think it should be safe to change the asserts to something like:

```
assert.Contains(t, "(exit code 137)", status.Message)
```

File: workflow/controller/operator.go [hunk 16]
```diff
@@ -234,16 +234,6 @@ func (woc *wfOperationCtx) operate(ctx context.Context) {
...
-		woc.log.WithError(err).Error("failed to GC artifacts")
-		return
-	}
-	if woc.wf.Labels[common.LabelKeyCompleted] == "true" { // abort now, we do not want to perform any more processing on a complete workflow because we could corrupt it
-		return
-	}
-
 	// Workflow Level Synchronization lock
 	if woc.execWf.Spec.Synchronization != nil {
 		acquired, wfUpdate, msg, err := woc.controller.syncManager.TryAcquire(woc.wf, "", woc.execWf.Spec.Synchronization)
```
Comment (juliev0) [inline workflow/controller/operator.go:239]: So, I'm seeing that we can now execute this Synchronization code on a completed workflow due to the check being moved.

Comment (juliev0) [reply workflow/controller/operator.go:239]: I'm thinking your functionality may need to move up...

**Comment by juliev0** [comment]
This is looking good. Thanks for all the changes. What are you seeing as far as your testing now? I know you were having some intermittent problem? If current state seems to be an improvement on previous state, I'll be okay to merge.

**Comment by Garett-MacGowan** [comment]
> This is looking good. Thanks for all the changes. What are you seeing as far as your testing now? I know you were having some intermittent problem? If current state seems to be an improvement on previous state, I'll be okay to merge.

No problem! I just ran a batch of tests. Still failing around 1/30. Artifacts exist but not garbage collected :(

**Comment by Garett-MacGowan** [comment]
Looking a little closer, I think it's possible the wait container is being killed by the cli command. Here's an extended view of the logs:

```
time="2023-11-03T05:40:34.709Z" level=info msg="Terminating pod as part of workflow shutdown" namespace=argo podName=artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598 shutdownStrategy=Stop workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=artgc-dag-wf-stopped-5z8k4-1709936038 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="Terminating pod as part of workflow shutdown" namespace=argo podName=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038 shutdownStrategy=Stop workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1709936038 phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1709936038 message: workflow shutdown with strategy:  Stop" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1709936038 finished: 2023-11-03 05:40:34.709211428 +0000 UTC" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1170001598 phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1170001598 message: workflow shutdown with strategy:  Stop" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1170001598 finished: 2023-11-03 05:40:34.709272128 +0000 UTC" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=debug msg="Evaluating node artgc-dag-wf-stopped-5z8k4: template: *v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main), boundaryID: " namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Getting the template by name: artgc-dag-wf-stopped-main" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.WorkflowStep (artgc-dag-wf-stopped-main)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Executing node artgc-dag-wf-stopped-5z8k4 of DAG is Running" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator-2)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator-2)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator-2" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.DAGTask (artgc-dag-artifact-creator-2)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.DAGTask (artgc-dag-workflow-stopper)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.NodeStatus (artgc-dag-artifact-creator-2)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.NodeStatus (artgc-dag-artifact-creator-2)"
time="2023-11-03T05:40:34.709Z" level=debug msg="Getting the template by name: artgc-dag-artifact-creator-2" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.NodeStatus (artgc-dag-artifact-creator-2)"
time="2023-11-03T05:40:34.710Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.NodeStatus (artgc-dag-workflow-stopper)"
time="2023-11-03T05:40:34.710Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.NodeStatus (artgc-dag-workflow-stopper)"
time="2023-11-03T05:40:34.710Z" level=debug msg="Getting the template by name: artgc-dag-workflow-stopper" base="*v1alpha1.Workflow (namespace=argo,name=artgc-dag-wf-stopped-5z8k4)" tmpl="*v1alpha1.NodeStatus (artgc-dag-workflow-stopper)"
time="2023-11-03T05:40:34.710Z" level=info msg="Outbound nodes of artgc-dag-wf-stopped-5z8k4 set to [artgc-dag-wf-stopped-5z8k4-1170001598 artgc-dag-wf-stopped-5z8k4-1709936038]" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=info msg="node artgc-dag-wf-stopped-5z8k4 phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=info msg="node artgc-dag-wf-stopped-5z8k4 finished: 2023-11-03 05:40:34.710118025 +0000 UTC" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=debug msg="Checking daemoned children of artgc-dag-wf-stopped-5z8k4" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=info msg=reconcileAgentPod namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=info msg="Updated message  -> Stopped with strategy 'Stop'" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=info msg="Marking workflow completed" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.710Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-5z8k4\", UID:\"d7008727-d7bb-4d9d-8690-83ba2aa5fcc1\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"793516\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowFailed' Stopped with strategy 'Stop'"
time="2023-11-03T05:40:34.711Z" level=debug msg="Log changes patch: {\"metadata\":{\"labels\":{\"workflows.argoproj.io/completed\":\"true\",\"workflows.argoproj.io/phase\":\"Failed\"}},\"status\":{\"conditions\":[{\"status\":\"True\",\"type\":\"PodRunning\"},{\"status\":\"True\",\"type\":\"Completed\"}],\"finishedAt\":\"2023-11-03T05:40:34Z\",\"message\":\"Stopped with strategy 'Stop'\",\"nodes\":{\"artgc-dag-wf-stopped-5z8k4\":{\"finishedAt\":\"2023-11-03T05:40:34Z\",\"outboundNodes\":[\"artgc-dag-wf-stopped-5z8k4-1170001598\",\"artgc-dag-wf-stopped-5z8k4-1709936038\"],\"phase\":\"Failed\"},\"artgc-dag-wf-stopped-5z8k4-1170001598\":{\"finishedAt\":\"2023-11-03T05:40:34Z\",\"message\":\"workflow shutdown with strategy:  Stop\",\"phase\":\"Failed\"},\"artgc-dag-wf-stopped-5z8k4-1709936038\":{\"finishedAt\":\"2023-11-03T05:40:34Z\",\"message\":\"workflow shutdown with strategy:  Stop\",\"phase\":\"Failed\"}},\"phase\":\"Failed\"}}"
time="2023-11-03T05:40:34.712Z" level=info msg="Workflow to be dehydrated" Workflow Size=6006
time="2023-11-03T05:40:34.714Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598/terminateContainers
time="2023-11-03T05:40:34.714Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038/terminateContainers
time="2023-11-03T05:40:34.714Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=main&stderr=true&stdout=true&tty=false"
time="2023-11-03T05:40:34.714Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=main&stderr=true&stdout=true&tty=false"
time="2023-11-03T05:40:34.714Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598
time="2023-11-03T05:40:34.714Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038
time="2023-11-03T05:40:34.717Z" level=info msg="cleaning up pod" action=deletePod key=argo/artgc-dag-wf-stopped-5z8k4-1340600742-agent/deletePod
time="2023-11-03T05:40:34.717Z" level=debug msg="Create events 201"
time="2023-11-03T05:40:34.720Z" level=debug msg="Update workflows 200"
time="2023-11-03T05:40:34.721Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=793519 workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.722Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-5z8k4\", UID:\"d7008727-d7bb-4d9d-8690-83ba2aa5fcc1\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"793519\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-5z8k4"
time="2023-11-03T05:40:34.722Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-5z8k4\", UID:\"d7008727-d7bb-4d9d-8690-83ba2aa5fcc1\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"793519\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-5z8k4.create-artifact-2: workflow shutdown with strategy:  Stop"
time="2023-11-03T05:40:34.722Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-5z8k4\", UID:\"d7008727-d7bb-4d9d-8690-83ba2aa5fcc1\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"793519\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artgc-dag-wf-stopped-5z8k4.stop-workflow: workflow shutdown with strategy:  Stop"
time="2023-11-03T05:40:34.722Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artgc-dag-wf-stopped-5z8k4\", UID:\"d7008727-d7bb-4d9d-8690-83ba2aa5fcc1\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"793519\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node artgc-dag-wf-stopped-5z8k4.stop-workflow: workflow shutdown with strategy:  Stop"
time="2023-11-03T05:40:34.722Z" level=debug msg="Delete pods 404"
time="2023-11-03T05:40:34.731Z" level=debug msg="Create events 201"
time="2023-11-03T05:40:34.740Z" level=debug msg="Create pods/exec 101"
time="2023-11-03T05:40:34.741Z" level=debug msg="Create pods/exec 101"
time="2023-11-03T05:40:34.746Z" level=debug msg="Create events 201"
time="2023-11-03T05:40:34.749Z" level=info msg="signaled container" container=main error="Internal error occurred: error executing command in container: failed to exec in container: failed to load task: no running task found: task 713905eab5534683bb00a2e02176eeda435a11e1d95bd1101a35e4ead806cd97 not found: not found" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038 stderr="<nil>" stdout="<nil>"
time="2023-11-03T05:40:34.749Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-11-03T05:40:34.749Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038
time="2023-11-03T05:40:34.755Z" level=debug msg="Create events 201"
time="2023-11-03T05:40:34.757Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-11-03T05:40:34.761Z" level=debug msg="Create events 201"
time="2023-11-03T05:40:34.763Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038/labelPodCompleted
time="2023-11-03T05:40:34.763Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598/labelPodCompleted
time="2023-11-03T05:40:34.776Z" level=debug msg="Create pods/exec 101"
time="2023-11-03T05:40:34.823Z" level=debug msg="Patch pods 200"
time="2023-11-03T05:40:34.823Z" level=debug msg="Patch pods 200"
time="2023-11-03T05:40:34.861Z" level=info msg="signaled container" container=main error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598 stderr= stdout="killing 1 with terminated\n"
time="2023-11-03T05:40:34.861Z" level=info msg="https://0.0.0.0:42429/api/v1/namespaces/argo/pods/artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-11-03T05:40:34.861Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598
time="2023-11-03T05:40:34.873Z" level=info msg="signaled container" container=wait error="command terminated with exit code 137" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038 stderr="<nil>" stdout="<nil>"
time="2023-11-03T05:40:34.880Z" level=debug msg="Create pods/exec 101"
time="2023-11-03T05:40:34.963Z" level=info msg="signaled container" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598 stderr= stdout="killing 1 with terminated\n"
time="2023-11-03T05:40:35.246Z" level=debug msg="Get leases 200"
time="2023-11-03T05:40:35.250Z" level=debug msg="Update leases 200"
time="2023-11-03T05:40:35.829Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.830Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.831Z" level=debug msg="task result:\n&WorkflowTaskResult{ObjectMeta:{artgc-dag-wf-stopped-5z8k4-1709936038  argo  268d17c9-c4a7-4f08-a84d-3a9f4ad10cb0 793530 1 2023-11-03 05:40:34 +0000 UTC <nil> <nil> map[workflows.argoproj.io/report-outputs-completed:true workflows.argoproj.io/workflow:artgc-dag-wf-stopped-5z8k4] map[] [{v1 Pod artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038 d6e1d915-0cb6-4d78-b834-4b1d379ff932 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2023-11-03 05:40:34 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/report-outputs-completed\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"d6e1d915-0cb6-4d78-b834-4b1d379ff932\\\"}\":{}}},\"f:outputs\":{\".\":{},\"f:artifacts\":{}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{Artifact{Name:main-logs,Path:,Mode:nil,From:,ArtifactLocation:ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,CASecret:nil,},Key:artgc-dag-wf-stopped-5z8k4/artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038/main.log,},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,},GlobalName:,Archive:nil,Optional:false,SubPath:,RecurseMode:false,FromExpression:,ArtifactGC:nil,Deleted:false,},},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.831Z" level=debug msg="task result name:\nartgc-dag-wf-stopped-5z8k4-1709936038" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.831Z" level=debug msg="Marking task result complete artgc-dag-wf-stopped-5z8k4-1709936038" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.831Z" level=debug msg="task results completed:\nmap[artgc-dag-wf-stopped-5z8k4-1153223979:true artgc-dag-wf-stopped-5z8k4-1170001598:false artgc-dag-wf-stopped-5z8k4-1709936038:true artgc-dag-wf-stopped-5z8k4-2861242108:true]" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.831Z" level=debug msg="task result completed len: 4" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.831Z" level=info msg="task-result changed" namespace=argo nodeID=artgc-dag-wf-stopped-5z8k4-1709936038 workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.831Z" level=debug msg="Skipping artifact GC" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.832Z" level=debug msg="Log changes patch: {\"status\":{\"nodes\":{\"artgc-dag-wf-stopped-5z8k4-1709936038\":{\"outputs\":{\"artifacts\":[{\"name\":\"main-logs\",\"s3\":{\"key\":\"artgc-dag-wf-stopped-5z8k4/artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038/main.log\"}}]}}},\"taskResultsCompleted\":{\"artgc-dag-wf-stopped-5z8k4-1709936038\":true}}}"
time="2023-11-03T05:40:35.832Z" level=info msg="Workflow to be dehydrated" Workflow Size=6240
time="2023-11-03T05:40:35.839Z" level=debug msg="Update workflows 200"
time="2023-11-03T05:40:35.840Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=793535 workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:35.861Z" level=debug msg="DeleteCollection workflowtaskresults 200"
time="2023-11-03T05:40:36.833Z" level=info msg="Processing workflow" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:36.834Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:36.834Z" level=debug msg="Skipping artifact GC" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:37.874Z" level=info msg="cleaning up pod" action=killContainers key=argo/artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038/killContainers
time="2023-11-03T05:40:37.964Z" level=info msg="cleaning up pod" action=killContainers key=argo/artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598/killContainers
time="2023-11-03T05:40:40.255Z" level=debug msg="Get leases 200"
time="2023-11-03T05:40:40.261Z" level=debug msg="Update leases 200"
time="2023-11-03T05:40:42.843Z" level=debug msg="Syncing all CronWorkflows"
```

Most notably, this bit here:
```
time="2023-11-03T05:40:34.709Z" level=info msg="Terminating pod as part of workflow shutdown" namespace=argo podName=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038 shutdownStrategy=Stop workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1709936038 phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1709936038 message: workflow shutdown with strategy:  Stop" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1709936038 finished: 2023-11-03 05:40:34.709211428 +0000 UTC" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1170001598 phase Running -> Failed" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1170001598 message: workflow shutdown with strategy:  Stop" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
time="2023-11-03T05:40:34.709Z" level=info msg="node artgc-dag-wf-stopped-5z8k4-1170001598 finished: 2023-11-03 05:40:34.709272128 +0000 UTC" namespace=argo workflow=artgc-dag-wf-stopped-5z8k4
```

It seems both the wait container and the main container are being killed, hence `1170001598` and `1709936038`

**Comment by Garett-MacGowan** [comment]
@juliev0 Given the above, do you have any guidance on how we can ensure the wait container finishes?

**Comment by Garett-MacGowan** [comment]
The only other thing I can think of is that 60 seconds is not enough time to delete the workflow in rare circumstances

This doesn't make much sense to me, however. On average, workflow deletion completes in 5 seconds.

If I reduce the timeout locally to 4 seconds to force a failure, the test fails immediately on `WaitForWorkflowDeletion` and won't even proceed to the assertions which check for artifact deletion.

```
Condition "for artifacts to exist" met after 30s
Deleting artgc-dag-wf-stopped-g6v8z
Waiting 4s for workflows {{ } workflows.argoproj.io/test metadata.name=artgc-dag-wf-stopped-g6v8z false false   <nil> 0 }
    when.go:355: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
=== FAIL: ArtifactsSuite/TestStoppedWorkflow
```

**Comment by Garett-MacGowan** [comment]
@juliev0 I'm new to golang, so correct me if I'm wrong, but doesn't the code relating to bgCtx need to be in its own routine? In its current form, does bgCtx actually allow execution to continue if the wait container gets a kill signal?

**Comment by juliev0** [comment]
I haven't quite read through everything you wrote yet, but this error is I believe a Kubernetes client throttling issue:
```
when.go:355: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
```

In `WaitForWorkflowList()` it must pertain to this line which is invoking the kubernetes client:
```
wfList, err := w.client.List(ctx, listOptions)
```

It must be that we're timing out there

**Comment by juliev0** [comment]
> I haven't quite read through everything you wrote yet, but this error is I believe a Kubernetes client error:
> 
> ```
> when.go:355: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
> ```
> 
> In `WaitForWorkflowList()` it must pertain to this line which is invoking the kubernetes client:
> 
> ```
> wfList, err := w.client.List(ctx, listOptions)
> ```
> 
> It must be that we're timing out there. I'm familiar with that client a little bit, just that I know it does throttling of requests to kubernetes (a certain number allowed per second), but I'm not sure if the error is necessarily related to throttling or just timing out because the timeout has arrived.

I guess if the Workflow doesn't exist, that part makes sense. Anyway, I think that's just a message that the kubernetes client spits out. The error messages that follow are separate.

**Comment by juliev0** [comment]
> @juliev0 I'm new to golang, so correct me if I'm wrong, but doesn't the code relating to bgCtx need to be in its own routine? In its current form, does bgCtx actually allow execution to continue if the wait container gets a kill signal?

Ugh, I think I'm seeing that the wait container used to actually intercept the SIGTERM signal so that it could do this shut down and now it doesn't: https://github.com/argoproj/argo-workflows/commit/d75e37e8b1c885ac3ebb11205ec452365ee2af67

**Comment by Garett-MacGowan** [comment]
> > @juliev0 I'm new to golang, so correct me if I'm wrong, but doesn't the code relating to bgCtx need to be in its own routine? In its current form, does bgCtx actually allow execution to continue if the wait container gets a kill signal?
> 
> Ugh, I think I'm seeing that the wait container used to actually intercept the SIGTERM signal so that it could do this orderly shut down saving everything off and now it doesn't: [d75e37e](https://github.com/argoproj/argo-workflows/commit/d75e37e8b1c885ac3ebb11205ec452365ee2af67)

Ahh, I'm not sure exactly how to interpret this. I should probably do more reading on golang....

is the solution to add back the following?

```
	// use a function to constrain the scope of ctx
	func() {
		// this allows us to gracefully shutdown, capturing artifacts
		ctx, cancel := signal.NotifyContext(ctx, syscall.SIGTERM)
		defer cancel()

		// Wait for main container to complete
		err := wfExecutor.Wait(ctx)
		if err != nil {
			wfExecutor.AddError(err)
		}
	}()
```

**Comment by juliev0** [comment]
> > @juliev0 I'm new to golang, so correct me if I'm wrong, but doesn't the code relating to bgCtx need to be in its own routine? In its current form, does bgCtx actually allow execution to continue if the wait container gets a kill signal?
> 
> Ugh, I think I'm seeing that the wait container used to actually intercept the SIGTERM signal so that it could do this orderly shut down saving everything off and now it doesn't: [d75e37e](https://github.com/argoproj/argo-workflows/commit/d75e37e8b1c885ac3ebb11205ec452365ee2af67)

Sorry, I'm not sure this is a problem. I'm currently trying to digest that PR. It seems like the main container waits for SIGTERM and the wait container waits for the main container....

**Comment by Garett-MacGowan** [comment]
> > > @juliev0 I'm new to golang, so correct me if I'm wrong, but doesn't the code relating to bgCtx need to be in its own routine? In its current form, does bgCtx actually allow execution to continue if the wait container gets a kill signal?
> > 
> > 
> > Ugh, I think I'm seeing that the wait container used to actually intercept the SIGTERM signal so that it could do this orderly shut down saving everything off and now it doesn't: [d75e37e](https://github.com/argoproj/argo-workflows/commit/d75e37e8b1c885ac3ebb11205ec452365ee2af67)
> 
> Sorry, I'm not sure this is a problem. I'm currently trying to digest that PR. It seems like the main container waits for SIGTERM and the wait container waits for the main container....

Is there anything that prevents the wait container from receiving a SIGTERM though? For instance, by the CLI stop command? In   that case, wouldn't we still need to protect the wait container from SIGTERM?

**Comment by juliev0** [comment]
I'm wondering if the Controller is sending the SIGTERM to both containers or just the `main` container

**Comment by Garett-MacGowan** [comment]
> I'm wondering if the Controller is sending the SIGTERM to both containers or just the `main` container

By the looks of it, both containers. In `processNextPodCleanupItem()` of `controller.go`, the only other reference to `SIGTERM` I see, `signalContainers()` is called. It looks like `signalContainers()` simply loops through the containers for a given pod name and sends the same signal.

```
func (wfc *WorkflowController) signalContainers(namespace string, podName string, sig syscall.Signal) (time.Duration, error) {
	pod, err := wfc.getPod(namespace, podName)
	if pod == nil || err != nil {
		return 0, err
	}

	for _, c := range pod.Status.ContainerStatuses {
		if c.State.Running == nil {
			continue
		}
		// problems are already logged at info level, so we just ignore errors here
		_ = signal.SignalContainer(wfc.restConfig, pod, c.Name, sig)
	}
	if pod.Spec.TerminationGracePeriodSeconds == nil {
		return 30 * time.Second, nil
	}
	return time.Duration(*pod.Spec.TerminationGracePeriodSeconds) * time.Second, nil
}
```

**Comment by juliev0** [comment]
good finding. I'm trying to ping Alex Collins, who wrote this. He says "the controller waits for the main container to exit and then the controller SIGTERMs the wait container using kubctl exec". I'm trying to find out where this logic lives.

**Comment by juliev0** [comment]
> good finding. I'm trying to ping Alex Collins, who wrote this. He says "the controller waits for the main container to exit and then the controller SIGTERMs the wait container using kubctl exec". (If that's true, then maybe the only container left at that point in `signalContainers()` is the wait container? I'm trying to find out where this logic lives.

Of course, if what he says is true, then the fact that we are Sigterming the wait container and it’s not listening for Sigterm would confirm what you’re seeing.

**Comment by juliev0** [comment]
> @juliev0 I'm new to golang, so correct me if I'm wrong, but doesn't the code relating to bgCtx need to be in its own routine? In its current form, does bgCtx actually allow execution to continue if the wait container gets a kill signal?

Sorry, I never responded to this. You're right that we should revisit these contexts. I think sometimes there is a separate goroutine started by a method which should have a context passed to it, so that it knows to stop. In this case, I'm thinking the whole `waitContainer()` function is blocking on `wfExecutor.Wait(ctx)`. When it gets past that it goes through the rest of the function followed by the defers. Since each of those is using `context.Background()`, then each should be allowed to execute.

**Comment by juliev0** [comment]
That PR I called out did seem to fix a lot of issues, such as [this](https://github.com/argoproj/argo-workflows/issues/10337) one, so maybe we're just not understanding the full picture yet. My assumption is that if you don't handle SIGTERM then the application will just get killed, but maybe that's wrong? Or another possibility is that the `cmd.Context()` that's passed into `waitContainer()` actually looks for SIGTERM itself?

**Comment by juliev0** [comment]
Oh, just noticed that we are in fact intercepting the SIGTERM for wait container too - it's in the top level [main.go](https://github.com/argoproj/argo-workflows/blob/master/cmd/argoexec/main.go#L19) file

**Comment by Garett-MacGowan** [comment]
Hmm, maybe the container is being killed with  `SIGKILL` for some reason?
```
time="2023-11-03T05:40:34.861Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598
time="2023-11-03T05:40:34.873Z" level=info msg="signaled container" container=wait error="command terminated with exit code 137" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038 stderr="<nil>" stdout="<nil>"
```

What can cause `"command terminated with exit code 137"`?

**Comment by juliev0** [comment]
> "signaled container"

This log line indicates SIGTERM ([15==SIGTERM](https://faculty.cs.niu.edu/~hutchins/csci480/signals.htm)):
```
time="2023-11-03T05:40:34.861Z" level=debug msg="exec container command" command="[/var/run/argo/argoexec kill 15 1]" container=wait error="<nil>" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-artifact-creator-2-1170001598
```
As for the container actually exiting with code 137, I've seen that before. I'm not sure. I think it's just some default behavior of the CLI?

**Comment by juliev0** [comment]
Actually, I'm just realizing that that second log line could help us. If you look at the [code](https://github.com/argoproj/argo-workflows/blob/master/workflow/signal/signal.go#L52), it's supposed to log both stdout and stderr. So, that implies that any log lines in your wait container would be logged here. In that case, can you add some log lines for debugging to your wait container logic to see what's happening there?

**Comment by juliev0** [comment]
> Actually, I'm just realizing that that second log line could help us. If you look at the [code](https://github.com/argoproj/argo-workflows/blob/master/workflow/signal/signal.go#L52), it's supposed to log both stdout and stderr. So, that implies that any log lines in your wait container would be logged here. In that case, can you add some log lines for debugging to your wait container logic to see what's happening there?

Actually, there are a bunch of log lines being logged in the wait container already, right? This is interesting that it's showing nil here.

**Comment by Garett-MacGowan** [comment]
> > Actually, I'm just realizing that that second log line could help us. If you look at the [code](https://github.com/argoproj/argo-workflows/blob/master/workflow/signal/signal.go#L52), it's supposed to log both stdout and stderr. So, that implies that any log lines in your wait container would be logged here. In that case, can you add some log lines for debugging to your wait container logic to see what's happening there?
> 
> Actually, there are a bunch of log lines being logged in the wait container already, right? This is interesting that it's showing nil here.

There's this (but it's for the main container)
```
time="2023-11-03T05:40:34.749Z" level=info msg="signaled container" container=main error="Internal error occurred: error executing command in container: failed to exec in container: failed to load task: no running task found: task 713905eab5534683bb00a2e02176eeda435a11e1d95bd1101a35e4ead806cd97 not found: not found" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038 stderr="<nil>" stdout="<nil>"
```

**Comment by Garett-MacGowan** [comment]
Ok, some thoughts:

Given that the stop of the wait container is predicated on the main container exiting, does it actually protect the wait container from getting affected by `SIGTERM` once the main container exits?

The current logic reads to me "only allow the wait container to be killed once the main container exits". Once the main container exits, what stops the wait container from being killed by another `SIGTERM`?

```

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGTERM)
	defer stop()
	err := commands.NewRootCommand().ExecuteContext(ctx)
	if err != nil {
		if exitError, ok := err.(errors.Exited); ok {
			if exitError.ExitCode() >= 0 {
				os.Exit(exitError.ExitCode())
			} else {
				os.Exit(137) // probably SIGTERM or SIGKILL
			}
		} else {
			util.WriteTerminateMessage(err.Error()) // we don't want to overwrite any other message
			println(err.Error())
			os.Exit(64)
		}
	}
}
```

**Comment by juliev0** [comment]
> > > Actually, I'm just realizing that that second log line could help us. If you look at the [code](https://github.com/argoproj/argo-workflows/blob/master/workflow/signal/signal.go#L52), it's supposed to log both stdout and stderr. So, that implies that any log lines in your wait container would be logged here. In that case, can you add some log lines for debugging to your wait container logic to see what's happening there?
> > 
> > 
> > Actually, there are a bunch of log lines being logged in the wait container already, right? This is interesting that it's showing nil here.
> 
> There's this (but it's for the main container)
> 
> ```
> time="2023-11-03T05:40:34.749Z" level=info msg="signaled container" container=main error="Internal error occurred: error executing command in container: failed to exec in container: failed to load task: no running task found: task 713905eab5534683bb00a2e02176eeda435a11e1d95bd1101a35e4ead806cd97 not found: not found" namespace=argo pod=artgc-dag-wf-stopped-5z8k4-artgc-dag-workflow-stopper-1709936038 stderr="<nil>" stdout="<nil>"
> ```

That also shows `stderr="<nil>" stdout="<nil>"`. I guess the attempt to Stream stdout and stderr from each of them is resulting in an error ([here](https://github.com/argoproj/argo-workflows/blob/master/workflow/common/util.go#L103))

**Comment by Garett-MacGowan** [comment]
In order for artifacts to be written and outputs to be finalized, the wait container needs to outlive the main container (and it shouldn't be killed even if the main container is done).

**Comment by juliev0** [comment]
> Ok, some thoughts:
> 
> Given that the stop of the wait container is predicated on the main container exiting, does it actually protect the wait container from getting affected by `SIGTERM` once the main container exits?
> 
> The current logic reads to me "only allow the wait container to be killed once the main container exits". Once the main container exits, what stops the wait container from being killed by another `SIGTERM`?
> 
> ```
> 
> func main() {
> 	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGTERM)
> 	defer stop()
> 	err := commands.NewRootCommand().ExecuteContext(ctx)
> 	if err != nil {
> 		if exitError, ok := err.(errors.Exited); ok {
> 			if exitError.ExitCode() >= 0 {
> 				os.Exit(exitError.ExitCode())
> 			} else {
> 				os.Exit(137) // probably SIGTERM or SIGKILL
> 			}
> 		} else {
> 			util.WriteTerminateMessage(err.Error()) // we don't want to overwrite any other message
> 			println(err.Error())
> 			os.Exit(64)
> 		}
> 	}
> }
> ```

Sorry, I don't think I'm following. 
1. I thought the logic is "only allow the wait container to be killed once the main container exits, or otherwise when a SIGTERM arrives"
2. If SIGTERM does arrive (and we can see that that was sent to the wait container), then it seems to me your logic should work. The line that's waiting on the main container should get interrupted, and then the rest of the logic thereafter should be allowed to happen. Am I missing something?

**Comment by Garett-MacGowan** [comment]
> > Ok, some thoughts:
> > Given that the stop of the wait container is predicated on the main container exiting, does it actually protect the wait container from getting affected by `SIGTERM` once the main container exits?
> > The current logic reads to me "only allow the wait container to be killed once the main container exits". Once the main container exits, what stops the wait container from being killed by another `SIGTERM`?
> > ```
> > 
> > func main() {
> > 	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGTERM)
> > 	defer stop()
> > 	err := commands.NewRootCommand().ExecuteContext(ctx)
> > 	if err != nil {
> > 		if exitError, ok := err.(errors.Exited); ok {
> > 			if exitError.ExitCode() >= 0 {
> > 				os.Exit(exitError.ExitCode())
> > 			} else {
> > 				os.Exit(137) // probably SIGTERM or SIGKILL
> > 			}
> > 		} else {
> > 			util.WriteTerminateMessage(err.Error()) // we don't want to overwrite any other message
> > 			println(err.Error())
> > 			os.Exit(64)
> > 		}
> > 	}
> > }
> > ```
> 
> Sorry, I don't think I'm following.
> 
> 1. I thought the logic is "only allow the wait container to be killed once the main container exits, or otherwise when a SIGTERM arrives"
> 2. If SIGTERM does arrive (and we can see that that was sent to the wait container), then it seems to me your logic should work. The line that's waiting on the main container should get interrupted, and then the rest of the logic thereafter should be allowed to happen. Am I missing something?

For 1: what do you mean by "or otherwise when a SIGTERM arrives"? The wait container is killed by the SIGTERM once the main container exits due to the `defer stop()` right?

Maybe I'm misunderstanding, but this feels like a race condition because in the wait container, we're saying "continue execution once the main container exits" and in the main container we're saying "defer the killing of the wait container until the main container exits"

**Comment by juliev0** [comment]
> > > Ok, some thoughts:
> > > Given that the stop of the wait container is predicated on the main container exiting, does it actually protect the wait container from getting affected by `SIGTERM` once the main container exits?
> > > The current logic reads to me "only allow the wait container to be killed once the main container exits". Once the main container exits, what stops the wait container from being killed by another `SIGTERM`?
> > > ```
> > > 
> > > func main() {
> > > 	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGTERM)
> > > 	defer stop()
> > > 	err := commands.NewRootCommand().ExecuteContext(ctx)
> > > 	if err != nil {
> > > 		if exitError, ok := err.(errors.Exited); ok {
> > > 			if exitError.ExitCode() >= 0 {
> > > 				os.Exit(exitError.ExitCode())
> > > 			} else {
> > > 				os.Exit(137) // probably SIGTERM or SIGKILL
> > > 			}
> > > 		} else {
> > > 			util.WriteTerminateMessage(err.Error()) // we don't want to overwrite any other message
> > > 			println(err.Error())
> > > 			os.Exit(64)
> > > 		}
> > > 	}
> > > }
> > > ```
> > 
> > 
> > Sorry, I don't think I'm following.
> > 
> > 1. I thought the logic is "only allow the wait container to be killed once the main container exits, or otherwise when a SIGTERM arrives"
> > 2. If SIGTERM does arrive (and we can see that that was sent to the wait container), then it seems to me your logic should work. The line that's waiting on the main container should get interrupted, and then the rest of the logic thereafter should be allowed to happen. Am I missing something?
> 
> For 1: what do you mean by "or otherwise when a SIGTERM arrives"? The wait container is killed by the SIGTERM once the main container exits due to the `defer stop()` right?
> 
> Maybe I'm misunderstanding, but this feels like a race condition because in the wait container, we're saying "continue execution once the main container exits" and in the main container we're saying "defer the killing of the wait container until the main container exits"

Hmm, you can correct me where I'm mistaken but here's what I would think would happen if a SIGTERM is sent to main container and then sent to wait container:
1. The waitContainer() function is blocking on the main container being done. Going up the stack trace, the main.go function is blocking here: `err := commands.NewRootCommand().ExecuteContext(ctx)`.
2. main container finishes and so the wait container is able to progress through saving outputs and updating the TaskResult
3. wait container receives SIGTERM. This causes the cmd.Context() to mark as cancelled. This has no effect on the logic that's progressing through `waitContainer()`. 
4. `waitContainer()` is able to finish its logic and then coming back to main.go it can exit. At the end of the function, `defer stop()` is called which marks `ctx` as cancelled, which has no effect

**Comment by Garett-MacGowan** [comment]
> Hmm, you can correct me where I'm mistaken but here's what I would think would happen if a SIGTERM is sent to main container and then sent to wait container:
> 
> 1. The waitContainer() function is blocking on the main container being done. Going up the stack trace, the main.go function is blocking here: `err := commands.NewRootCommand().ExecuteContext(ctx)`.
> 2. main container finishes and so the wait container is able to progress through saving outputs and updating the TaskResult
> 3. wait container receives SIGTERM. This causes the cmd.Context() to mark as cancelled. This has no effect on the logic that's progressing through `waitContainer()`.
> 4. `waitContainer()` is able to finish its logic and then coming back to main.go it can exit. At the end of the function, `defer stop()` is called which marks `ctx` as cancelled, which has no effect

Ok, I didn't know the main container was blocked by the wait container. I'll take a better look at this tomorrow and try to come up with a theory or more questions.

Thanks for all the help @juliev0

**Comment by juliev0** [comment]
In `taskResultReconciliation()`, it looks like the TaskResultInformer is being used to keep track of the current TaskResults. Is it possible that at the time you're getting there, it hasn't updated to reflect the latest TaskResult value maybe?

Then looking at your log, the next time this is logged:
```
time="2023-11-03T05:40:36.834Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-5z8k4
```
the TaskResults have all been deleted? (I guess each one is owned by the corresponding Pod, right? so it gets deleted with the Pod)

**Comment by Garett-MacGowan** [comment]
> In `taskResultReconciliation()`, it looks like the TaskResultInformer (cache) is being used to keep track of the current TaskResults. Is it possible that at the time you're getting there, it hasn't updated to reflect the latest TaskResult value maybe?
> 
> Then looking at your log, the next time this is logged:
> 
> ```
> time="2023-11-03T05:40:36.834Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-5z8k4
> ```
> 
> the TaskResults have all been deleted? (I guess each one is owned by the corresponding Pod, right? so it gets deleted with the Pod)
> 
> Do you know what ensures that Pods/TaskResults only get deleted after `taskResultReconciliation()` is run?

Ahh, I see. I missed the logic regarding task result deletion. Currently, task results are being deleted in the event of `wf.Status.Phase.Completed()`, meaning if `WorkflowSucceeded`, `WorkflowFailed`, or `WorkflowError`.

This happens in `persistUpdates()` of `operator.go`, right before pod cleanup.

The current logic is:
```
	if woc.wf.Status.Phase.Completed(){
		if err := woc.deleteTaskResults(ctx); err != nil {
			woc.log.WithError(err).Warn("failed to delete task-results")
		}
	}
```

I think it may be sufficient to do.
```
	if woc.wf.Status.Phase.Completed() && woc.checkTaskResultsCompleted() {
		if err := woc.deleteTaskResults(ctx); err != nil {
			woc.log.WithError(err).Warn("failed to delete task-results")
		}
	}
```

I don't think we need to protect the pod from being deleted since, as we've discussed, the wait container should finish.

**Comment by juliev0** [comment]
> > In `taskResultReconciliation()`, it looks like the TaskResultInformer (cache) is being used to keep track of the current TaskResults. Is it possible that at the time you're getting there, it hasn't updated to reflect the latest TaskResult value maybe?
> > Then looking at your log, the next time this is logged:
> > ```
> > time="2023-11-03T05:40:36.834Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artgc-dag-wf-stopped-5z8k4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the TaskResults have all been deleted? (I guess each one is owned by the corresponding Pod, right? so it gets deleted with the Pod)
> > Do you know what ensures that Pods/TaskResults only get deleted after `taskResultReconciliation()` is run?
> 
> @juliev0 Ahh, I see. I missed the logic regarding task result deletion. Currently, task results are being deleted in the event of `wf.Status.Phase.Completed()`, meaning if `WorkflowSucceeded`, `WorkflowFailed`, or `WorkflowError`.
> 
> This happens in `persistUpdates()` of `operator.go`, right before pod cleanup.
> 
> The current logic is:
> 
> ```
> 	if woc.wf.Status.Phase.Completed(){
> 		if err := woc.deleteTaskResults(ctx); err != nil {
> 			woc.log.WithError(err).Warn("failed to delete task-results")
> 		}
> 	}
> ```
> 
> I think it may be sufficient to do.
> 
> ```
> 	if woc.wf.Status.Phase.Completed() && woc.checkTaskResultsCompleted() {
> 		if err := woc.deleteTaskResults(ctx); err != nil {
> 			woc.log.WithError(err).Warn("failed to delete task-results")
> 		}
> 	}
> ```
> 
> I don't think we need to protect the pod from being deleted since, as we've discussed, the wait container should finish.

Thanks for finding that code. It looks like there may be 2 ways for TaskResults to get deleted: 1. the code you found which would occur when the Workflow completes; 2. if the Pod that owns a TaskResult gets deleted I believe it will automatically get deleted through this [OwnerReference](https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/taskresult.go#L51). See [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) for information on that.

**Comment by juliev0** [comment]
> Thanks for finding that code. It looks like there may be 2 ways for TaskResults to get deleted: 1. the code you found which would occur when the Workflow completes; 2. if the Pod that owns a TaskResult gets deleted I believe it will automatically get deleted through this [OwnerReference](https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/taskresult.go#L51). See [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) for information on that.

And a Pod could be deleted as soon as it completes if the [PodGCStrategy](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L121) is configured as such

**Comment by Garett-MacGowan** [comment]
> > Thanks for finding that code. It looks like there may be 2 ways for TaskResults to get deleted: 1. the code you found which would occur when the Workflow completes; 2. if the Pod that owns a TaskResult gets deleted I believe it will automatically get deleted through this [OwnerReference](https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/taskresult.go#L51). See [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) for information on that.
> 
> And a Pod could be deleted as soon as it completes if the [PodGCStrategy](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L121) is configured as such

Thanks for the context.

If that's the case, what are your thoughts on removing the OwnerReference? I think deletion is already handled by the woc.deleteTaskResults() method, no? I do like the idea of having it as a safeguard though.

Alternatively, maybe we could set the OwnerReference to the Workflow? If so, any guidance on best practices for passing that reference?

FYI, with the change described above, the tests have passed well over 180 times with no failure. This isn't testing with `PodGCOnPodCompletion` though.

**Comment by juliev0** [comment]
> > > Thanks for finding that code. It looks like there may be 2 ways for TaskResults to get deleted: 1. the code you found which would occur when the Workflow completes; 2. if the Pod that owns a TaskResult gets deleted I believe it will automatically get deleted through this [OwnerReference](https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/taskresult.go#L51). See [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) for information on that.
> > 
> > 
> > And a Pod could be deleted as soon as it completes if the [PodGCStrategy](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L121) is configured as such
> 
> Thanks for the context.
> 
> If that's the case, what are your thoughts on removing the OwnerReference? I think deletion is already handled by the woc.deleteTaskResults() method, no? I do like the idea of having it as a safeguard though.
> 
> Alternatively, maybe we could set the OwnerReference to the Workflow? If so, any guidance on best practices for passing that reference?
> 
> FYI, with the change described above, the tests have passed well over 180 times with no failure. This isn't testing with `PodGCOnPodCompletion` though.

Great. I think setting the OwnerReference to the Workflow seems good just in case. Note, that of course there will be more TaskResults around with this change, but it seems okay to me, and also seems good for debugging. It looks like workflow name is already being passed in as an environment variable [here](https://github.com/argoproj/argo-workflows/blob/master/cmd/argoexec/commands/root.go#L120) and passed to the Executor for you to use. Can you pass the Workflow UID as well?

BTW, I just sent a message to Alex to see if there was ever some other intention for how to handle this.

**Comment by Garett-MacGowan** [comment]
Ok, tests running well locally. Added a test case for PodGC OnPodCompletion.

Here's the script i've been using in case anyone comes here in the future and needs to run them:

```
#!/bin/bash

# Number of times to run the test
total_runs=240
error_occurred=false

for ((i=1; i<=total_runs; i++)); do
    echo "Running test (Iteration $i)..."

    # Run the test command
    go test -failfast -v -timeout 0 -count 1 --tags executor ./test/e2e -run='.*/StoppedWorkflow'

    # Check if the test command failed (non-zero exit status)
    if [ $? -ne 0 ]; then
        echo "Error occurred during test (Iteration $i)"
        error_occurred=true
        break  # Exit the loop if an error occurs
    fi
done

# Notify if an error occurred
if [ "$error_occurred" = true ]; then
    echo "An error occurred during one or more test iterations."
else
    echo "All test iterations completed successfully."
fi

```

File: workflow/executor/executor.go [hunk 17]
```diff
@@ -780,17 +781,38 @@ func (we *WorkflowExecutor) CaptureScriptResult(ctx context.Context) error {
...
+// ReportOutputs updates the WorkflowTaskResult (or falls back to annotate the Pod)
+func (we *WorkflowExecutor) ReportOutputs(ctx context.Context, logArtifacts []wfv1.Artifact) error {
 	outputs := we.Template.Outputs.DeepCopy()
 	outputs.Artifacts = append(outputs.Artifacts, logArtifacts...)
 	return we.reportResult(ctx, wfv1.NodeResult{Outputs: outputs})
 }
 
 func (we *WorkflowExecutor) reportResult(ctx context.Context, result wfv1.NodeResult) error {
-	if !result.Outputs.HasOutputs() && !result.Progress.IsValid() {
-		return nil
```
Comment (juliev0) [inline workflow/executor/executor.go:792]: hmm, I wonder if removing this is check is okay or not. I know you wanted to be able to add the annotation, which is fine. But it does seem like if this were to resolve as true, we will do some of the things below which we weren't doing before. But maybe the check was just here to preemptively return in case there seemed to be nothing to do? (I'm not sure what causes Progress to be invalid.)

File: workflow/controller/taskresult.go [hunk 18]
```diff
@@ -53,10 +53,28 @@ func (wfc *WorkflowController) newWorkflowTaskResultInformer() cache.SharedIndex
...
+
+		// If the task result is completed, set the state to true.
+		if result.Labels[common.LabelKeyReportOutputsCompleted] == "true" {
+			woc.log.Debugf("Marking task result complete %s", resultName)
+			woc.wf.Status.MarkTaskResultComplete(resultName)
+		}
+
+		woc.log.Debugf("task results completed:\n%+v", woc.wf.Status.GetTaskResultsCompleted())
+		woc.log.Debugf("task result completed len: %d", len(woc.wf.Status.GetTaskResultsCompleted()))
+
```
Comment (juliev0) [inline workflow/controller/taskresult.go:77]: are these 2 debugging statements supposed to be within the for loop or outside?

File: workflow/controller/operator.go [hunk 19]
```diff
@@ -779,7 +787,8 @@ func (woc *wfOperationCtx) persistUpdates(ctx context.Context) {
 		woc.log.WithError(err).Warn("error updating taskset")
 	}
 
-	if woc.wf.Status.Phase.Completed() {
+	// Note that the woc.checkTaskResultsCompleted() resolves a ~1/30 garbage collection failure race conidtion.
```
Comment (juliev0) [inline workflow/controller/operator.go:790]: can we say in the comment "make sure the TaskResults are incorporated into WorkflowStatus before we delete them"?

**Comment by juliev0** [comment]
Thanks for adding all these tests!

File: workflow/controller/taskresult.go (hunk 18 above)
Comment (Garett-MacGowan) [reply workflow/controller/taskresult.go:77]: Inside the loop gives a more fine-grained view into what's going on. It's probably sufficient to move this outside the loop though.

File: workflow/executor/executor.go (hunk 17 above)
Comment (Garett-MacGowan) [reply workflow/executor/executor.go:792]: My assumption was that this was here to return early if there was nothing to do. I removed this before I realized that a task result is created before `ReportOutputs` of the wait container (when reporting progress for the first time, which happens early on in the wait container execution). I'll add it back.

I guess progress can be invalid if there are no tasks. Not sure if N can ever be greater than M. I'm pretty sure the progress should always be set at this point (it happens early on in wait container with `monitorProgress`)

IsValid logic is
```
in != "" && in.N() >= 0 && in.N() <= in.M() && in.M() > 0
```
where  `Progress in N/M format. N is number of task complete. M is number of tasks.`

Comment (juliev0) [reply workflow/executor/executor.go:792]: Thanks for going through the logic. It does seem safe to me to remove this line. If you don't have Outputs and you don't have Tasks, then it seems like it would probably be fine to still call `upsertTaskResult()` below, right?

**Comment by juliev0** [comment]
This is looking good! I think I can probably merge it on Monday! (I won't have time to work between now and Sunday and don't want to merge it in a hurry)

File: workflow/executor/executor.go (hunk 17 above)
Comment (Garett-MacGowan) [reply workflow/executor/executor.go:792]: Yeah, it would just create a shell of a `WorkflowTaskResult`

**Review by juliev0 — APPROVED** [review]
