### PR TITLE
fix(executor): Enable PNS executor to better kill sidecars. Fixes #5779

### LINKED ISSUE #5779: DAG/STEPS Hang v3.0.2 - Sidecars not being killed
## Summary 

What happened?
```text
DAG tasks randomly hang
```
Screen Shot 2021-04-29 at 7 01 35 PM

image

What did you expect to happen?
```text
DAG tasks successfully finished
```

## Diagnostics

What Kubernetes provider are you using? 
```text
GKE
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

What version of Argo Workflows are you running? 
```text
v3.0.2
```

### kubectl get wf -o yaml ${workflow} 

The workflow contains sensitive information regarding our organization, if it's important reach out me on CNCF slack

### kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

[controller-dag-hang.txt](https://github.com/argoproj/argo-workflows/files/6402148/controller-dag-hang.txt)

### Wait container logs

```yaml
W
{},\"mirrorVolumeMounts\":true}],\"sidecars\":[{\"name\":\"mysql\",\"image\":\"mysql:5.6\",\"env\":[{\"name\":\"MYSQL_ALLOW_EMPTY_PASSWORD\",\"value\":\"true\"}],\"reso
urces\":{},\"mirrorVolumeMounts\":true},{\"name\":\"redis\",\"image\":\"redis:alpine3.13\",\"resources\":{},\"mirrorVolumeMounts\":true},{\"name\":\"nginx\",\"image\":\
"nginx:1.19.7-alpine\",\"resources\":{},\"mirrorVolumeMounts\":true}],\"archiveLocation\":{\"archiveLogs\":true,\"gcs\":{\"bucket\":\"7shitfs-argo-workflow-artifacts\",
\"serviceAccountKeySecret\":{\"name\":\"devops-argo-workflow-sa\",\"key\":\"credentials.json\"},\"key\":\"argo-workflow-logs/2021/04/29/github-20979-9df1440/github-2097
9-9df1440-2290904989\"}},\"retryStrategy\":{\"limit\":\"1\",\"retryPolicy\":\"Always\"},\"tolerations\":[{\"key\":\"node_type\",\"operator\":\"Equal\",\"value\":\"large
\",\"effect\":\"NoSchedule\"}],\"hostAliases\":[{\"ip\":\"127.0.0.1\",\"hostnames\":[\"xyz.dev\",\"xyz.test\",\"cypress.xyz.test\",\"codeception.xyz.dev
\"]}],\"podSpecPatch\":\"containers:\\n- name: main\\n  resources:\\n    request:\\n      memory: \\\"8Gi\\\"\\n      cpu: \\\"2\\\"\\n    limits:\\n      memory: \\\"8
Gi\\\"\\n      cpu: \\\"2\\\"\\n- name: mysql\\n  resources:\\n    request:\\n      memory: \\\"2Gi\\\"\\n      cpu: \\\"0.5\\\"\\n    limits:\\n      memory: \\\"2Gi\\
\"\\n      cpu: \\\"0.5\\\"\\n- name: redis\\n  resources:\\n    request:\\n      memory: \\\"50Mi\\\"\\n      cpu: \\\"0.05\\\"\\n    limits:\\n      memory: \\\"50Mi\
\\"\\n      cpu: \\\"0.05\\\"\\n- name: nginx\\n  resources:\\n    request:\\n      memory: \\\"50Mi\\\"\\n      cpu: \\\"0.05\\\"\\n    limits:\\n      memory: \\\"50M
i\\\"\\n      cpu: \\\"0.05\\\"\\n\",\"timeout\":\"1200s\"}"
time="2021-04-29T22:33:05.291Z" level=info msg="Starting annotations monitor"
time="2021-04-29T22:33:05.291Z" level=info msg="Starting deadline monitor"
time="2021-04-29T22:33:10.299Z" level=info msg="Watch pods 200"
time="2021-04-29T22:38:05.291Z" level=info msg="Alloc=4475 TotalAlloc=47692 Sys=75089 NumGC=15 Goroutines=10"
time="2021-04-29T22:42:44.410Z" level=info msg="Main container completed"
time="2021-04-29T22:42:44.410Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-04-29T22:42:44.410Z" level=info msg="Capturing script exit code"
time="2021-04-29T22:42:44.410Z" level=info msg="Getting exit code of main"
time="2021-04-29T22:42:44.413Z" level=info msg="Get pods 200"
time="2021-04-29T22:42:44.414Z" level=info msg="Saving logs"
time="2021-04-29T22:42:44.415Z" level=info msg="Getting output of main"
time="2021-04-29T22:42:44.424Z" level=info msg="List log 200"
time="2021-04-29T22:42:44.427Z" level=info msg="GCS Save path: /tmp/argo/outputs/logs/main.log, key: argo-workflow-logs/2021/04/29/github-20979-9df1440/github-20979-9df
1440-2290904989/main.log"
time="2021-04-29T22:42:44.763Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2021-04-29T22:42:44.763Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2021-04-29T22:42:44.763Z" level=info msg="No output parameters"
time="2021-04-29T22:42:44.763Z" level=info msg="No output artifacts"
time="2021-04-29T22:42:44.763Z" level=info msg="Annotating pod with output"
time="2021-04-29T22:42:44.778Z" level=info msg="Patch pods 200"
time="2021-04-29T22:42:44.779Z" level=info msg="Killing sidecars []"
time="2021-04-29T22:42:44.779Z" level=info msg="Alloc=28577 TotalAlloc=72566 Sys=75089 NumGC=18 Goroutines=11"
```

I've been continuously trying to upgrade our argo workflow version, but since 3.x.x dag tasks stopped working properly. I'm currently using v2.12 with no problems at all.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Fixes #5779

### CODE REVIEW

File: workflow/executor/pns/pns.go [hunk 1]
```diff
@@ -140,23 +140,6 @@ func (p *PNSExecutor) Wait(ctx context.Context, containerNames []string) error {
 	}
 	p.rootFS = rootFS
 
-	/*
```
Comment (alexec) [inline workflow/executor/pns/pns.go:143]: this isn't really needed, we must speak to K8S API in all cases

File: workflow/executor/pns/pns.go [hunk 2]
```diff
@@ -179,7 +162,7 @@ func (p *PNSExecutor) pollRootProcesses(ctx context.Context, containerNames []st
 			}
 			// sidecars start after the main containers, so we can't just exit once we know about all the main containers,
 			// we need a bit more time
-			if p.haveContainerPIDs(containerNames) && time.Since(start) > 5*time.Second {
+			if p.haveContainerPIDs(containerNames) {
```
Comment (alexec) [inline workflow/executor/pns/pns.go:165]: we can exit straight away as we no longer need to wait for sidecars

File: workflow/executor/pns/pns.go [hunk 3]
```diff
@@ -217,8 +200,19 @@ func (p *PNSExecutor) Kill(ctx context.Context, containerNames []string, termina
 }
 
 func (p *PNSExecutor) ListContainerNames(ctx context.Context) ([]string, error) {
+	procs, err := gops.Processes()
```
Comment (alexec) [inline workflow/executor/pns/pns.go:203]: rather than rely on the map created by `pollRootProcesses` we can actually just look at processes

File: workflow/executor/pns/pns.go [hunk 4]
```diff
@@ -263,6 +257,13 @@ func (p *PNSExecutor) getContainerPID(containerName string) int {
 	if pid, ok := p.containerNameToPID[containerName]; ok {
 		return pid
 	}
+	procs, _ := gops.Processes()
```
Comment (alexec) [inline workflow/executor/pns/pns.go:260]: `containerNameToPID`  might not contain the container, lets look at the current processes

File: workflow/executor/pns/pns.go [hunk 5]
```diff
@@ -295,17 +296,16 @@ func (p *PNSExecutor) secureRootFiles() error {
 	for _, proc := range processes {
 		err = func() error {
 			pid := proc.Pid()
-			if pid == 1 || pid == p.thisPID || proc.PPid() != 0 {
-				// ignore the pause container, our own pid, and non-root processes
-				return nil
+			if !p.isRootContainerProcess(proc) {
+				return fmt.Errorf("ignoring PID %d (ppid=%d): %q", pid, proc.PPid(), proc.Executable())
```
Comment (alexec) [inline workflow/executor/pns/pns.go:300]: produces extra useful diagnostics

File: workflow/executor/pns/pns.go [hunk 6]
```diff
@@ -332,3 +332,17 @@ func (p *PNSExecutor) secureRootFiles() error {
...
+	return proc.Pid() != 1 && proc.Pid() != p.thisPID && proc.PPid() == 0
+}
+
+func sameFile(a *os.File, b *os.File) bool {
+	if a == nil || b == nil {
+		return false
+	}
+	x, _ := a.Stat()
+	y, _ := b.Stat()
+	return os.SameFile(x, y)
```
Comment (alexec) [inline workflow/executor/pns/pns.go:347]: copied from v2.12

**Review by whynowy — APPROVED** [review]
