### PR TITLE
fix(controller): Same workflow nodes are not executing parallel even semaphore locks available

### LINKED ISSUE #6110: semaphore lost
## Summary 

argo dont increase semaphore when pod completed, causes the flow keep running one by one.

## Diagnostics
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  maxbuilder: "60"
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-sema
spec:
  entrypoint: main
  serviceAccountName: std
  templates:
  - name: main
    dag:
      tasks:
      - name: build-all
        template: build-all
  - name: build-all
    steps:
    - - name: split
        template: split
    - - name: build
        template: build
        arguments:
          parameters:
          - name: baseid
            value: "{{item.baseid}}"
          - name: tarid
            value: "{{item.tarid}}"
        withParam: "{{steps.split.outputs.result}}"
  - name: split
    script: 
      image: python:3.9-slim
      command: ["python"]
      source: |
        import json
        import sys

        output = []
        for id in range(120):
            output.append({'baseid': id, 'tarid': id + 10000})

        json.dump(output, sys.stdout)
  - name: build
    synchronization:
      semaphore:
        configMapKeyRef:
          name: conf
          key: maxbuilder
    inputs:
      parameters:
      - name: baseid
      - name: tarid
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["sleep 10; echo acquired lock"]

```

```
std@master:/data/samba/std/aes-argo$ date && argo get @latest |grep Waiting |wc -l
Wed Jun  9 14:24:36 CST 2021
51
std@master:/data/samba/std/aes-argo$ date && argo get @latest |grep Waiting |wc -l
Wed Jun  9 14:25:02 CST 2021
49
std@master:/data/samba/std/aes-argo$ date && argo get @latest |grep Waiting |wc -l
Wed Jun  9 14:26:34 CST 2021
41
std@master:/data/samba/std/aes-argo$ date && argo get @latest |grep Waiting |wc -l
Wed Jun  9 14:27:58 CST 2021
33
std@master:/data/samba/std/aes-argo$ argo get @latest
Name:                test-semajwls7
Namespace:           argo
ServiceAccount:      std
Status:              Running
Conditions:          
 PodRunning          True
Created:             Wed Jun 09 14:22:32 +0800 (9 minutes ago)
Started:             Wed Jun 09 14:22:32 +0800 (9 minutes ago)
Duration:            9 minutes 28 seconds
Progress:            111/121
ResourcesDuration:   39m30s*(100Mi memory),39m30s*(1 cpu)

STEP                                        TEMPLATE   PODNAME                    DURATION  MESSAGE
 ● test-semajwls7                           main                                                                                                                 
 └─● build-all                              build-all                                                                                                            
   ├───✔ split                              split      test-semajwls7-834350695   3s                                                                             
   └─┬─✔ build(0:baseid:0,tarid:10000)      build      test-semajwls7-1431628376  13s                                                                            
     ├─✔ ...                                                                           
     ├─✔ build(60:baseid:60,tarid:10060)    build      test-semajwls7-1756982882  30s                                                                            
     ├─◷ build(61:baseid:61,tarid:10061)    build      test-semajwls7-1784892703  9m        Waiting for argo/ConfigMap/conf/maxbuilder lock. Lock status: 0/60   
     ├─◷ ...                                                                                Waiting for argo/ConfigMap/conf/maxbuilder lock. Lock status: 0/60
     ├─◷ build(69:baseid:69,tarid:10069)    build      test-semajwls7-4001026551  9m        Waiting for argo/ConfigMap/conf/maxbuilder lock. Lock status: 0/60   
     ├─● build(70:baseid:70,tarid:10070)    build      test-semajwls7-110265593   9m                                                                             
     ├─✔ build(71:baseid:71,tarid:10071)    build      test-semajwls7-3079006344  8m                                                                             
     ├─✔ ...                                                                            
     └─✔ build(119:baseid:119,tarid:10119)  build      test-semajwls7-2179176665  30s      
    
std@master:/data/samba/std/argo$ date && kubectl get pods -n argo |grep Completed |wc -l  && kubectl get pods -n argo |grep test-sema |grep Running |wc -l
Wed Jun  9 14:26:27 CST 2021
80
1
std@master:/data/samba/std/argo$ date && kubectl get pods -n argo |grep Completed |wc -l  && kubectl get pods -n argo |grep test-sema |grep Running |wc -l
Wed Jun  9 14:26:29 CST 2021
80
1
std@master:/data/samba/std/argo$ date && kubectl get pods -n argo |grep Completed |wc -l  && kubectl get pods -n argo |grep test-sema |grep Running |wc -l
Wed Jun  9 14:28:21 CST 2021
91
1
std@master:/data/samba/std/argo$ date && kubectl get pods -n argo |grep Completed |wc -l  && kubectl get pods -n argo |grep test-sema |grep Running |wc -l
Wed Jun  9 14:31:33 CST 2021
110
1

std@master:/data/samba/std/aes-argo$ argo list
NAME             STATUS      AGE   DURATION   PRIORITY
test-semajwls7   Succeeded   11m   10m        0
 
std@master:/data/samba/std/argo$ argo version
argo: v3.1.0-rc12
  BuildDate: 2021-06-03T01:30:42Z
  GitCommit: f529b2b5ccc779ecbc133deb02f130fafa40e810
  GitTreeState: clean
  GitTag: v3.1.0-rc12
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64                                 
```

### PR DESCRIPTION
**Pull request by sarabala1979**
closes #6110 

Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

### CODE REVIEW

File: workflow/sync/semaphore.go [hunk 1]
```diff
@@ -165,7 +176,8 @@ func (s *PrioritySemaphore) tryAcquire(holderKey string) (bool, string) {
 	if s.pending.Len() > 0 {
 		item := s.pending.peek()
 		nextKey = fmt.Sprintf("%v", item.key)
-		if holderKey != nextKey {
+		if holderKey != nextKey && !isSameWorkflowNodeKeys(holderKey, nextKey) {
```
Comment (sarabala1979) [inline workflow/sync/semaphore.go:179]: We don't want to prioritize/order the same workflow nodes. The executetemplate will make sure the template order.

if the workflow has multiple nodes to wait for lock, the operator node order and semaphore queue order are going out of sync. if it same workflow key

**Review by alexec — CHANGES_REQUESTED** [review]
please clean-up PR

**Comment by sarabala1979** [comment]
> please clean-up PR

done. I missed to cleanup my env

**Review by alexec — APPROVED** [review]
