### PR TITLE
fix: Mark taskResult completed if wait container terminated not gracefully. Fixes #13373

### LINKED ISSUE #13373: workflow stuck in `Running`, but only pod exited with `OOMKilled (exit code 137)`
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

If the pod was exited  with "OOMKilled (exit code 137)", after the pods was cleaned by gc controller,  we expect  the status of wf to be "Eorror" not running.

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
set source limit to wf, and use many mem out of the limits, and the pod was killed by OOMKilled.
```

### Logs from the workflow controller

```text
time="2024-07-22T08:07:05.052Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1290040021 namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.069Z" level=info msg="Task-result reconciliation" namespace=argo-simu-simulation-platform numObjs=1 workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.072Z" level=debug msg="task result:\n&WorkflowTaskResult{ObjectMeta:{simulation-platform-new-scenario-183614-1557733-prod-fqjrw  argo-simu-simulation-platform  9e46d1e0-3ccf-4c7d-92e5-e252fb8fa700 1290022481 1 2024-07-20 10:35:55 +0000 UTC <nil> <nil> map[workflows.argoproj.io/controller-instanceid:argo-simu workflows.argoproj.io/report-outputs-completed:false workflows.argoproj.io/workflow:simulation-platform-new-scenario-183614-1557733-prod-fqjrw] map[] [{argoproj.io/v1alpha1 Workflow simulation-platform-new-scenario-183614-1557733-prod-fqjrw 90e473b7-57f1-4fbe-b044-96352b232605 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2024-07-20 10:35:55 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/controller-instanceid\":{},\"f:workflows.argoproj.io/report-outputs-completed\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"90e473b7-57f1-4fbe-b044-96352b232605\\\"}\":{}}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:nil,Progress:,},}" namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.072Z" level=debug msg="task result name:\nsimulation-platform-new-scenario-183614-1557733-prod-fqjrw" namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.076Z" level=debug msg="Marking task result incomplete simulation-platform-new-scenario-183614-1557733-prod-fqjrw" namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.076Z" level=info msg="task-result changed" namespace=argo-simu-simulation-platform nodeID=simulation-platform-new-scenario-183614-1557733-prod-fqjrw workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.076Z" level=debug msg="Skipping artifact GC" namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.076Z" level=debug msg="Evaluating node simulation-platform-new-scenario-183614-1557733-prod-fqjrw: template: *v1alpha1.WorkflowStep (run-gpu), boundaryID: " namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.076Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo-simu-simulation-platform,name=simulation-platform-new-scenario-183614-1557733-prod-fqjrw)" tmpl="*v1alpha1.WorkflowStep (run-gpu)"
time="2024-07-22T08:07:05.076Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo-simu-simulation-platform,name=simulation-platform-new-scenario-183614-1557733-prod-fqjrw)" tmpl="*v1alpha1.WorkflowStep (run-gpu)"
time="2024-07-22T08:07:05.076Z" level=debug msg="Getting the template by name: run-gpu" base="*v1alpha1.Workflow (namespace=argo-simu-simulation-platform,name=simulation-platform-new-scenario-183614-1557733-prod-fqjrw)" tmpl="*v1alpha1.WorkflowStep (run-gpu)"
time="2024-07-22T08:07:05.077Z" level=debug msg="Node simulation-platform-new-scenario-183614-1557733-prod-fqjrw already completed" namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.077Z" level=info msg="TaskSet Reconciliation" namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.077Z" level=info msg=reconcileAgentPod namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.077Z" level=debug msg="Task results completion status: map[simulation-platform-new-scenario-183614-1557733-prod-fqjrw:false]" namespace=argo-simu-simulation-platform workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.077Z" level=debug msg="taskresults of workflow are incomplete or still have daemon nodes, so can't mark workflow completed" fromPhase=Running namespace=argo-simu-simulation-platform toPhase=Error workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
time="2024-07-22T08:07:05.085Z" level=info msg="Workflow update successful" namespace=argo-simu-simulation-platform phase=Running resourceVersion=1290040021 workflow=simulation-platform-new-scenario-183614-1557733-prod-fqjrw
```

### Logs from in your workflow's wait container

```text
The error pod was cleaned by gc controller
```

### PR DESCRIPTION
**Pull request by jswxstw**
Fixes #13373 

### Motivation

https://github.com/argoproj/argo-workflows/issues/12103#issuecomment-2296174496

### Modifications

Mark its taskResult as completed if pod has been terminated not gracefully.

### Verification

This issue only occurs when `wait` container is terminated not gracefully, it is hard to reproduce it.
1. submit a workflow with a long running pod.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sleep-example-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: sleep
        template: sleep

  - name: sleep
    container:
      image: alpine:latest
      command: [sh, -c, sleep 3600]
```

2. `kill -9` wait/main container
```shell
ctr task kill --signal 9 8c66238d4723b9237c4e71d3fd16710f5f985d2ce8f7218ff987e143b3e8140b # wait container
ctr task kill --signal 9 5da93afce108bc59f746e8c8df791ae6c808deaedaa87abc8f6ea5f4697da2df # main container
```

3. Pod `Error` and wait container does not write `LabelKeyReportOutputsCompleted` to `true`
```shell
# sleep-example-tdnk7-sleep-1943014577   0/2     Error     0            9m21s
# k logs -f sleep-example-tdnk7-sleep-1943014577 -c wait
time="2024-08-21T03:55:14.519Z" level=info msg="Starting Workflow Executor" version=untagged
time="2024-08-21T03:55:14.522Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2024-08-21T03:55:14.522Z" level=info msg="Executor initialized" deadline="2024-08-21 04:00:13 +0000 UTC" includeScriptOutput=false namespace=argo podName=sleep-example-tdnk7-sleep-1943014577 templateName=sleep version="&Version{Version:untagged,BuildDate:2024-08-15T12:58:34Z,GitCommit:c143e3e78c1b6d585d64a2d9363bf0c9c64caf6c,GitTag:untagged,GitTreeState:clean,GoVersion:go1.22.6,Compiler:gc,Platform:linux/amd64,}"
time="2024-08-21T03:55:14.529Z" level=debug msg="Create workflowtaskresults 201"
time="2024-08-21T03:55:14.530Z" level=info msg="Starting deadline monitor"
time="2024-08-21T03:55:21.534Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:55:21.538Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-08-21T03:55:28.535Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:55:28.538Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-08-21T03:55:35.535Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:55:35.538Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-08-21T03:55:42.535Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:55:42.538Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-08-21T03:55:49.536Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:55:49.540Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-08-21T03:55:56.534Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:55:56.538Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-08-21T03:56:03.534Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:56:03.537Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-08-21T03:56:10.535Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:56:10.538Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-08-21T03:56:17.535Z" level=debug msg="Create workflowtaskresults 409"
time="2024-08-21T03:56:17.538Z" level=debug msg="Patch workflowtaskresults 200"

```

4. Workflow Failed as expected.
```shell
# argo get sleep-example-tdnk7
Name:                sleep-example-tdnk7
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed
Message:             child 'sleep-example-tdnk7-1943014577' failed
Conditions:
 PodRunning          False
 Completed           True
Created:             Wed Aug 21 11:55:13 +0800 (14 minutes ago)
Started:             Wed Aug 21 11:55:13 +0800 (14 minutes ago)
Finished:            Wed Aug 21 11:56:37 +0800 (13 minutes ago)
Duration:            1 minute 24 seconds
Progress:            0/1
ResourcesDuration:   13s*(1 cpu),2m0s*(100Mi memory)

STEP                    TEMPLATE  PODNAME                               DURATION  MESSAGE
 ✖ sleep-example-tdnk7  main                                                      child 'sleep-example-tdnk7-1943014577' failed
 └───✖ sleep            sleep     sleep-example-tdnk7-sleep-1943014577  1m        Error (exit code 137)
```
controller log: 
```
time="2024-08-21T11:56:37.580Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=2696088 namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=debug msg="task result:\n&WorkflowTaskResult{ObjectMeta:{sleep-example-tdnk7-1943014577  argo  64e126a5-83fe-4fc8-8c4d-9e416f3e8de4 2696021 1 2024-08-21 11:55:14 +0800 CST <nil> <nil> map[workflows.argoproj.io/report-outputs-completed:false workflows.argoproj.io/workflow:sleep-example-tdnk7] map[] [{argoproj.io/v1alpha1 Workflow sleep-example-tdnk7 28e951a9-8353-4d92-9cab-2853e00b7134 <nil> <nil>}] [] [{argoexec Update argoproj.io/v1alpha1 2024-08-21 11:55:14 +0800 CST FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/report-outputs-completed\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"28e951a9-8353-4d92-9cab-2853e00b7134\\\"}\":{}}}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:nil,Progress:,},}" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=debug msg="task result name:\nsleep-example-tdnk7-1943014577" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=debug msg="Marking task result incomplete sleep-example-tdnk7-1943014577" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=info msg="task-result changed" namespace=argo nodeID=sleep-example-tdnk7-1943014577 workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=debug msg="Skipping artifact GC" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=info msg="Pod failed: Error (exit code 137)" displayName=sleep namespace=argo pod=sleep-example-tdnk7-sleep-1943014577 templateName=sleep workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 137)" new.phase=Failed new.progress=0/1 nodeID=sleep-example-tdnk7-1943014577 old.message= old.phase=Running old.progress=0/1 workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=debug msg="TaskResult of the node not yet completed" namespace=argo nodeID=sleep-example-tdnk7-1943014577 workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=debug msg="Node failed or error, mark its taskResult as completed" namespace=argo nodeID=sleep-example-tdnk7-1943014577 workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=debug msg="Evaluating node sleep-example-tdnk7: template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.581Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.WorkflowStep (main)"
time="2024-08-21T11:56:37.581Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.WorkflowStep (main)"
time="2024-08-21T11:56:37.581Z" level=debug msg="Getting the template by name: main" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.WorkflowStep (main)"
time="2024-08-21T11:56:37.582Z" level=debug msg="Executing node sleep-example-tdnk7 of Steps is Running" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=debug msg="Evaluating node sleep-example-tdnk7[0].sleep: template: *v1alpha1.WorkflowStep (sleep), boundaryID: sleep-example-tdnk7" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.WorkflowStep (sleep)"
time="2024-08-21T11:56:37.582Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.WorkflowStep (sleep)"
time="2024-08-21T11:56:37.582Z" level=debug msg="Getting the template by name: sleep" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.WorkflowStep (sleep)"
time="2024-08-21T11:56:37.582Z" level=debug msg="Node sleep-example-tdnk7[0].sleep already completed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="Step group node sleep-example-tdnk7-2176115732 deemed failed: child 'sleep-example-tdnk7-1943014577' failed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="node sleep-example-tdnk7-2176115732 phase Running -> Failed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="node sleep-example-tdnk7-2176115732 message: child 'sleep-example-tdnk7-1943014577' failed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="node sleep-example-tdnk7-2176115732 finished: 2024-08-21 03:56:37.582246691 +0000 UTC" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="step group sleep-example-tdnk7-2176115732 was unsuccessful: child 'sleep-example-tdnk7-1943014577' failed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.NodeStatus (sleep)"
time="2024-08-21T11:56:37.582Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.NodeStatus (sleep)"
time="2024-08-21T11:56:37.582Z" level=debug msg="Getting the template by name: sleep" base="*v1alpha1.Workflow (namespace=argo,name=sleep-example-tdnk7)" tmpl="*v1alpha1.NodeStatus (sleep)"
time="2024-08-21T11:56:37.582Z" level=info msg="Outbound nodes of sleep-example-tdnk7-1943014577 is [sleep-example-tdnk7-1943014577]" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="Outbound nodes of sleep-example-tdnk7 is [sleep-example-tdnk7-1943014577]" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="node sleep-example-tdnk7 phase Running -> Failed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="node sleep-example-tdnk7 message: child 'sleep-example-tdnk7-1943014577' failed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="node sleep-example-tdnk7 finished: 2024-08-21 03:56:37.582346369 +0000 UTC" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=debug msg="Checking daemoned children of sleep-example-tdnk7" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg=reconcileAgentPod namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=debug msg="Task results completion status: map[sleep-example-tdnk7-1943014577:true]" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="Updated message  -> child 'sleep-example-tdnk7-1943014577' failed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=info msg="Marking workflow completed" namespace=argo workflow=sleep-example-tdnk7
time="2024-08-21T11:56:37.582Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"sleep-example-tdnk7\", UID:\"28e951a9-8353-4d92-9cab-2853e00b7134\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"2696088\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowFailed' child 'sleep-example-tdnk7-1943014577' failed"
time="2024-08-21T11:56:37.582Z" level=debug msg="Log changes patch: {\"metadata\":{\"labels\":{\"workflows.argoproj.io/completed\":\"true\",\"workflows.argoproj.io/phase\":\"Failed\"}},\"status\":{\"conditions\":[{\"status\":\"False\",\"type\":\"PodRunning\"},{\"status\":\"True\",\"type\":\"Completed\"}],\"finishedAt\":\"2024-08-21T03:56:37Z\",\"message\":\"child 'sleep-example-tdnk7-1943014577' failed\",\"nodes\":{\"sleep-example-tdnk7\":{\"finishedAt\":\"2024-08-21T03:56:37Z\",\"message\":\"child 'sleep-example-tdnk7-1943014577' failed\",\"outboundNodes\":[\"sleep-example-tdnk7-1943014577\"],\"phase\":\"Failed\"},\"sleep-example-tdnk7-1943014577\":{\"finishedAt\":\"2024-08-21T03:56:34Z\",\"message\":\"Error (exit code 137)\",\"phase\":\"Failed\",\"resourcesDuration\":{\"cpu\":13,\"memory\":120}},\"sleep-example-tdnk7-2176115732\":{\"finishedAt\":\"2024-08-21T03:56:37Z\",\"message\":\"child 'sleep-example-tdnk7-1943014577' failed\",\"phase\":\"Failed\"}},\"phase\":\"Failed\",\"taskResultsCompletionStatus\":{\"sleep-example-tdnk7-1943014577\":true}}}"
time="2024-08-21T11:56:37.582Z" level=info msg="Workflow to be dehydrated" Workflow Size=2233
time="2024-08-21T11:56:37.586Z" level=debug msg="Create events 201"
time="2024-08-21T11:56:37.588Z" level=debug msg="Update workflows 200"
time="2024-08-21T11:56:37.589Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=2696092 workflow=sleep-example-tdnk7
```

### CODE REVIEW

**Comment by yonirab** [comment]
@jswxstw Does this PR also address the scenario of a workflow with a step that gets OOMKilled and then retries and succeeds?
Does it make sure the workflow status is correctly reflected as Succeeded in such a case?

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1144,11 +1144,19 @@ func (woc *wfOperationCtx) podReconciliation(ctx context.Context) (error, bool)
...
+					woc.log.WithFields(log.Fields{"nodeID": newState.ID}).Debug("TaskResult of the node not yet completed")
+					switch {
+					case newState.Succeeded():
+						woc.log.WithFields(log.Fields{"nodeID": newState.ID}).Debug("Node succeeded, waiting for its taskResult to be completed")
+						taskResultIncomplete = true
+						return
+					case newState.FailedOrError():
+						// The wait container might have been terminated not gracefully, mark its taskResult as completed here.
+						woc.log.WithFields(log.Fields{"nodeID": newState.ID}).Debug("Node failed or error, mark its taskResult as completed")
+						woc.wf.Status.MarkTaskResultComplete(node.ID)
```
Comment (Joibel) [inline workflow/controller/operator.go:1158]: At this point the task result might have been written by the wait container, but the workflow controller might not have observed this. Just because the pod has failed it doesn't **always** mean the wait container didn't get a chance to write a workflowTaskResult.

Shouldn't we wait for the workflowTaskResult to possibly come through and check for this state somewhere around [here](https://github.com/argoproj/argo-workflows/blob/dcd943618e4e85443c75944f5f2c333f07c89805/workflow/controller/taskresult.go#L99). We don't record the transition time into failed, so this may be tricky to implement.

**Review by Joibel — CHANGES_REQUESTED** [review]

File: workflow/controller/operator.go (hunk 1 above)
Comment (jswxstw) [reply workflow/controller/operator.go:1158]: https://github.com/argoproj/argo-workflows/blob/dcd943618e4e85443c75944f5f2c333f07c89805/workflow/controller/operator.go#L1498-L1505

`assessNodeStatus` will check the status of `wait` container, so if the new state is failed or error, it also means `wait` container has been terminated.

Comment (Joibel) [reply workflow/controller/operator.go]: This does make sense. There is nothing to say that under these circumstances we might eventually receive a completed WorkflowTaskResult, although it does seem the more unlikely scenario.

The delay introduced in `podAbsentTimeout` is for similar reasons to the question above. At least here we've got positive confirmation of pod death, but we don't **know** that a completed WorkflowTaskResult hasn't yet arrived, we're assuming it won't.

The story of WorkflowTaskResults has changed during 3.5. Of note is #12574 which made WorkflowTaskResults completion a requirement.

#13454 and this PR are both trying to partially undo that requirement - for good reasons. What I'm trying to ensure is that this isn't an endless spiral of adding complexity circling around this issue.

I'm happy to merge it as is, because it's better than before. It's limited to pods that have been Evicted now, which probably means there are more pods that can slip through the cracks.

I think we'll also need a patch to convert [this](https://github.com/argoproj/argo-workflows/blob/dcd943618e4e85443c75944f5f2c333f07c89805/workflow/controller/taskresult.go#L99) test from
```go
if !foundPod && !node.Completed() {
```
to something like
```go
if (!foundPod || pod.Completed()) && !node.Completed() {
```
to cover my other concerns, but that can happen another day.

**Review by Joibel — APPROVED** [review]
