### PR TITLE
fix: Add --tls-certificate-secret-name parameter to server command. Fixes #5582 

### LINKED ISSUE #5582: TLS configuration and/or docs enhancement
# Summary

It looks like after 3.0 release argo server listens on https port with self-signed certificate (#5581 )
I think it would be great to have a dedicated ConfigMap with tls.cert and tls.key parameters which would be mounted inside pod (Like it is implemented in ArgoCD) so it would be very easy to generate a valid certificate with cert-manager or ue any pre-isued one.
At least it would be great to have a parameter or doc which would tell where the cert is read from. It looks like it is harcoded now and it's impossible to mount CM inside pod without even knowing where the self-signed cert is located...

# Use Cases

When deploying a new instance with Ingress it would be great to use ACME from cert-manager

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by chtcvl**
Signed-off-by: vladimir.ivanov <vladimir.ivanov@grasshopperasia.com>

Fixes #5582 

Add --tls-certificate-secret-name parameter to server command.
Since server runs on localhost:2746, get an error in the UI "certificate is valid for ... not for localhost". Therefore the merge request set InsecureSkipVerify on TLSconfig for grpc client on the gateway.

Tested to to work with secret generated by cert-manager.

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [x] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [x] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

File: server/apiserver/argoserver.go [hunk 1]
```diff
@@ -334,7 +334,10 @@ func (as *argoServer) newHTTPServer(ctx context.Context, port int, artifactServe
 		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(MaxGRPCMessageSize)),
 	}
 	if as.tlsConfig != nil {
-		dialOpts = append(dialOpts, grpc.WithTransportCredentials(credentials.NewTLS(as.tlsConfig)))
+		tlsConfig := as.tlsConfig
+		tlsConfig.InsecureSkipVerify = true
```
Comment (alexec) [inline server/apiserver/argoserver.go:338]: should you delete this line?

Comment (chtcvl) [reply server/apiserver/argoserver.go:338]: This `InsecureSkipVerify` is for communication within the same instance of argo-server process - between grpc-gateway and grpc-server goroutines (since server is serving on `localhost` and we can't have it in certificate SAN for publically trusted certificate). Setting it as `false` will break the gateway.
I provided more reasoning and alternative implementations at https://github.com/argoproj/argo-workflows/pull/9423#discussion_r970628566

Comment (tczhao) [reply server/apiserver/argoserver.go:338]: I think the correct place to do this is here instead
https://github.com/argoproj/argo-workflows/blob/9a32232a85ce0f24719a6aaa46eef86f86a500b4/util/tls/tls.go#L147-L149

**Review by tczhao — CHANGES_REQUESTED** [review]

File: server/apiserver/argoserver.go (hunk 1 above)
Comment (chtcvl) [reply server/apiserver/argoserver.go:338]: `func GetServerTLSConfigFromSecret` returns a **server** TLS config with proper certificates. Here we are patching **client** TLS config (dialOpts) for aforementioned reasons. 

We set `InsecureSkipVerify` on server TLS config as well, but this is unnecessary and can become a security risk in the long run.

File: server/apiserver/argoserver.go [hunk 2]
```diff
@@ -334,7 +334,10 @@ func (as *argoServer) newHTTPServer(ctx context.Context, port int, artifactServe
 		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(MaxGRPCMessageSize)),
 	}
 	if as.tlsConfig != nil {
-		dialOpts = append(dialOpts, grpc.WithTransportCredentials(credentials.NewTLS(as.tlsConfig)))
+		tlsConfig := as.tlsConfig
```
Comment (alexec) [inline server/apiserver/argoserver.go:337]: Will `as.tlConfig` be modified? Do you need to do `copy()` or similar?

Comment (chtcvl) [reply server/apiserver/argoserver.go]: Fixed with `Clone()`

**Review by alexec — APPROVED** [review]
LGTM. I'd like a second pair of eyes on this. @juliev0 ?

**Review by juliev0 — APPROVED** [review]

**Comment by chtcvl** [comment]
I don't seem to be able to merge this PR as it requires write access. Would appreciate help merging this.
