### PR TITLE
fix(executor): Always poll for Docker injected sidecars. Resolves #5448

### LINKED ISSUE #5448: v3.0: wait containers do not exit
Users are reporting that wait containers do not exit after the main container.

Please make sure that you do not report problems with <= v3.0.0-rc6 - these have know issues with killing injected sidecars.

Questions:

* What executor are you using?
* Do you have sidecars?
* Do you have injected sidecars (e.g. Istio)?
* Are you using outputs artifacts, outputs.result?
* What is the last 10 log lines of the wait container?
* Are you archiving logs? i.e `archiveLogs: true`

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

**Comment by alexec** [comment]
functional_test.go:310: timeout after 30s waiting for condition

File: workflow/executor/docker/docker.go [hunk 1]
```diff
@@ -249,7 +259,7 @@ func (d *DockerExecutor) syncContainerIDs(ctx context.Context, containerNames []
 			}
 			// sidecars start after the main containers, so we can't just exit once we know about all the main containers,
 			// we need a bit more time
-			if d.haveContainers(containerNames) && time.Since(started) > 3*time.Second {
+			if d.haveContainers(containerNames) && time.Since(started) > 30*time.Second {
```
Comment (alexec) [inline workflow/executor/docker/docker.go:262]: @whynowy @jessesuen I've increased this to up-to 30s (some for PNS). I'm assuming that all sidecar containers will start within 30s. Is this a valid assumption?

**Comment by alexec** [comment]
artifacts_test.go:52: timeout after 30s waiting for condition

pns

File: workflow/executor/docker/docker.go [hunk 2]
```diff
@@ -185,6 +185,8 @@ func (d *DockerExecutor) GetExitCode(ctx context.Context, containerName string)
 }
 
 func (d *DockerExecutor) Wait(ctx context.Context, containerNames []string) error {
+	ctx, cancel := context.WithCancel(ctx) // stop the polling when we are no longer waiting
+	defer cancel()
 	go func() {
 		err := d.pollContainerIDs(ctx, containerNames)
```
Comment (whynowy) [inline workflow/executor/docker/docker.go:191]: If `pollContainerIDs` returns with a timeout error, it could stay in `for !d.haveContainers(containerNames)` forever.

File: workflow/executor/docker/docker.go [hunk 3]
```diff
@@ -185,6 +185,8 @@ func (d *DockerExecutor) GetExitCode(ctx context.Context, containerName string)
 }
 
 func (d *DockerExecutor) Wait(ctx context.Context, containerNames []string) error {
+	ctx, cancel := context.WithCancel(ctx) // stop the polling when we are no longer waiting
```
Comment (whynowy) [inline workflow/executor/docker/docker.go:188]: It seems to be useless here to do `WithCancel(ctx)`. If the passed in `ctx` is cancelable, then there's no need to do it; If the passed in `ctx` is not cancelable, then I don't see a way could hit `ctx.Done()`.

**Comment by alexec** [comment]
pns: artifacts_test.go:52: timeout after 30s waiting for condition
emissary: cluster_workflow_template_test.go:55: timeout after 30s waiting for condition

File: workflow/executor/docker/docker.go (hunk 2 above)
Comment (alexec) [reply workflow/executor/docker/docker.go:189]: poll now runs for ever

**Comment by alexec** [comment]
@whynowy ready for review again.

I did not make your change - I'd prefer to wait forever, I don't think we ever can have a case now that we don't get all container names.

I've removed the PNS changes.

**Review by whynowy — APPROVED** [review]
LGTM

**Comment by alexec** [comment]
Set milestone as v3.0 for inclusing in v3.0.0-rc10.
