### PR TITLE
fix: Mark non-fulfilled taskSetNodes error when agent pod failed. Fixes #12703

### LINKED ISSUE #12703: Workflow is `Error` but node is not `Error` when Agent error
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Argo install mode: `cluster-install`
When I submit the example 1 to `khaos-workflow` namepsace , the agent pod can not be created because of rbac problems.
Then, the workflow turns to `Error` state, but the step is still `Pending`.
```shell
# argo get hello-nptwz -n khaos-workflow
Name:                hello-nptwz
Namespace:           khaos-workflow
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Error
Message:             failed to check if secret argo-workflows-agent-ca-certificates exists: secrets "argo-workflows-agent-ca-certificates" is forbidden: User "system:serviceaccount:argo:argo" cannot get resource "secrets" in API group "" in the namespace "khaos-workflow"
Conditions:
 Completed           True
Created:             Tue Feb 27 14:30:34 +0800 (18 minutes ago)
Started:             Tue Feb 27 14:30:34 +0800 (18 minutes ago)
Finished:            Tue Feb 27 14:30:34 +0800 (18 minutes ago)
Duration:            0 seconds
Progress:            0/1

STEP            TEMPLATE  PODNAME  DURATION  MESSAGE
 ◷ hello-nptwz  main
```

Workflow example 2 has two parallel steps: `plugin` and `container`. The workflow is `Error` because the `AgentPod` creation failed like example 1, then all steps are still `Pending`.
```shell
# argo get hello-l5kft -n khaos-workflow
Name:                hello-l5kft
Namespace:           khaos-workflow
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Error
Message:             serviceaccounts "khaos-executor-plugin" not found
Conditions:
 Completed           True
Created:             Thu Feb 29 11:48:56 +0800 (8 minutes ago)
Started:             Thu Feb 29 11:48:56 +0800 (8 minutes ago)
Finished:            Thu Feb 29 11:48:56 +0800 (8 minutes ago)
Duration:            0 seconds
Progress:            0/2

STEP              TEMPLATE         PODNAME                 DURATION  MESSAGE
 ⚠ hello-l5kft    main                                               Workflow operation error
 └─┬─◷ container  hello-container  hello-l5kft-3255363099  8m
   └─◷ plugin     hello-plugin
```
Step `plugin` was not executed but step `container` was actually executed successfully.
```shell
# kubectl get pod hello-l5kft-3255363099 -n khaos-workflow
NAME                     READY   STATUS      RESTARTS   AGE
hello-l5kft-3255363099   0/2     Completed   0          8m24s
```
Expected: Step `plugin` is `Error` and step `container` is `Succeeded`.

### Version

v3.4.14

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.
Example 1: 
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
spec:
  entrypoint: main
  templates:
    - name: main
      plugin:
        hello: { }
```
Example 2:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
      - - name: plugin
          template: hello-plugin
        - name: container
          template: hello-container
    - name: hello-plugin
      plugin:
        hello: {}
    - name: hello-container
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["echo hello"]
```

### Logs from the workflow controller

```text
time="2024-02-27T06:30:34.617Z" level=info msg="Updated phase  -> Running" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.617Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.617Z" level=warning msg="[DEBUG] boundaryID was nil" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.617Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.617Z" level=info msg="Plugin node hello-nptwz initialized Pending" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.617Z" level=info msg="TaskSet Reconciliation" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.617Z" level=info msg="Creating TaskSet" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.654Z" level=info msg=reconcileAgentPod namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.655Z" level=error msg="error in agent pod reconciliation" error="failed to check if secret argo-workflows-agent-ca-certificates exists: secrets \"argo-workflows-agent-ca-certificates\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot get resource \"secrets\" in API group \"\" in the namespace \"khaos-workflow\"" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.655Z" level=info msg="Updated phase Running -> Error" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.656Z" level=info msg="Updated message  -> failed to check if secret argo-workflows-agent-ca-certificates exists: secrets \"argo-workflows-agent-ca-certificates\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot get resource \"secrets\" in API group \"\" in the namespace \"khaos-workflow\"" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.656Z" level=info msg="Marking workflow completed" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.656Z" level=info msg="Marking workflow as pending archiving" namespace=khaos-workflow workflow=hello-nptwz
time="2024-02-27T06:30:34.656Z" level=info msg="Workflow to be dehydrated" Workflow Size=1277
time="2024-02-27T06:30:34.662Z" level=info msg="cleaning up pod" action=deletePod key=khaos-workflow/hello-nptwz-1340600742-agent/deletePod
time="2024-02-27T06:30:34.669Z" level=info msg="Workflow update successful" namespace=khaos-workflow phase=Error resourceVersion=85338826501 workflow=hello-nptwz
time="2024-02-27T06:30:34.712Z" level=info msg="archiving workflow" namespace=khaos-workflow uid=598bdc29-7662-49f0-8351-d35052680735 workflow=hello-nptwz
time="2024-02-27T06:30:34.745Z" level=info msg="Queueing Error workflow khaos-workflow/hello-nptwz for delete in 72h0m0s due to TTL"
time="2024-02-27T06:34:56.544Z" level=info msg="Alloc=14015 TotalAlloc=728044 Sys=61309 NumGC=133 Goroutines=279"
time="2024-02-27T06:35:11.972Z" level=info msg="Received Workflow Controller config map argo/workflow-controller-configmap update"
time="2024-02-27T06:35:11.979Z" level=info msg="Configuration:\nartifactRepository:\n  archiveLogs: true\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: my-minio-cred\n    bucket: my-bucket\n    endpoint: minio.argo:9000\n    insecure: true\n    secretKeySecret:\n      key: secretkey\n      name: my-minio-cred\nexecutor:\n  imagePullPolicy: Always\n  name: \"\"\n  resources:\n    requests:\n      cpu: 10m\n      memory: 64Mi\ninitialDelay: 0s\nlinks:\n- name: Workflow Link\n  scope: workflow\n  url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Pod Link\n  scope: pod\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Pod Logs Link\n  scope: pod-logs\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Event Source Logs Link\n  scope: event-source-logs\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Sensor Logs Link\n  scope: sensor-logs\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\nmetricsConfig:\n  enabled: true\n  path: /metrics\n  port: 9090\nnamespaceParallelism: 999999999\nnodeEvents: {}\npersistence:\n  archive: true\n  archiveTTL: 2160h0m0s\n  connectionPool:\n    connMaxLifetime: 30s\n    maxIdleConns: 10\n    maxOpenConns: 100\n  mysql:\n    database: argo\n    host: 10.0.240.33\n    passwordSecret:\n      key: password\n      name: argo-mysql-config\n    port: 3306\n    tableName: argo_workflows\n    userNameSecret:\n      key: username\n      name: argo-mysql-config\n  nodeStatusOffLoad: true\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\n  sessionExpiry: 0s\ntelemetryConfig: {}\nworkflowDefaults:\n  metadata:\n    annotations:\n      argo: workflows\n    creationTimestamp: null\n  spec:\n    arguments: {}\n    parallelism: 3\n    podGC:\n      strategy: OnWorkflowSuccess\n    ttlStrategy:\n      secondsAfterCompletion: 259200\n  status:\n    finishedAt: null\n    startedAt: null\n"
time="2024-02-27T06:35:11.979Z" level=info msg="Persistence configuration enabled"
time="2024-02-27T06:35:11.979Z" level=info msg="Node status offloading is enabled"
time="2024-02-27T06:35:11.979Z" level=info msg="Workflow archiving is enabled"
time="2024-02-27T06:35:11.979Z" level=info executorImage="ccr.ccs.tencentyun.com/cdb.khaos.eros/argoexec:develop" executorImagePullPolicy=Always managedNamespace=
time="2024-02-27T06:35:17.313Z" level=info msg="Performing periodic workflow GC"
time="2024-02-27T06:35:17.316Z" level=info msg="Deleting old offloads that are not live" len_wfs=0
time="2024-02-27T06:35:17.316Z" level=info msg="Workflow GC finished"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by jswxstw**
Fixes #12703

### Motivation

1. Node status is non-fulfilled when agent pod failed.
2. `argo-cluster-role` can not get secrets `argo-workflows-agent-ca-certificates`

### Modifications

1. Mark non-fulfilled taskSetNodes error when agent pod failed.
2. add secrets `argo-workflows-agent-ca-certificates` get permission to `argo-cluster-role`

### Verification

UT

Delete `hello-executor-plugin` serviceaccount to simulate agent pod failure scenario.
1. single step example
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
spec:
  entrypoint: main
  templates:
    - name: main
      plugin:
        hello: { }
```
```
# argo get hello-q8h7f
Name:                hello-q8h7f
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Error
Message:             create agent pod failed with reason:"serviceaccounts "hello-executor-plugin" not found"
Conditions:
 PodRunning          False
 Completed           True
Created:             Fri Mar 01 15:55:18 +0800 (53 seconds ago)
Started:             Fri Mar 01 15:55:18 +0800 (53 seconds ago)
Finished:            Fri Mar 01 15:55:19 +0800 (52 seconds ago)
Duration:            1 second
Progress:            0/1

STEP            TEMPLATE  PODNAME  DURATION  MESSAGE
 ⚠ hello-q8h7f  main                         create agent pod failed with reason:"serviceaccounts "hello-executor-plugin" not found"
```

2. parallel steps example
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
      - - name: plugin
          template: hello-plugin
        - name: container
          template: hello-container
    - name: hello-plugin
      plugin:
        hello: {}
    - name: hello-container
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["echo hello"]
```
```
# argo get hello-dtkm9
Name:                hello-dtkm9
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed
Message:             child 'hello-dtkm9-3577871718' failed
Conditions:
 PodRunning          False
 Completed           True
Created:             Fri Mar 01 15:55:35 +0800 (28 seconds ago)
Started:             Fri Mar 01 15:55:35 +0800 (28 seconds ago)
Finished:            Fri Mar 01 15:55:45 +0800 (18 seconds ago)
Duration:            10 seconds
Progress:            1/2
ResourcesDuration:   0s*(1 cpu),4s*(100Mi memory)

STEP              TEMPLATE         PODNAME                                 DURATION  MESSAGE
 ✖ hello-dtkm9    main                                                               child 'hello-dtkm9-3577871718' failed
 └─┬─✔ container  hello-container  hello-dtkm9-hello-container-1541734788  7s
   └─⚠ plugin     hello-plugin                                                       create agent pod failed with reason:"serviceaccounts "hello-executor-plugin" not found"
```

### CODE REVIEW

File: workflow/controller/agent.go [hunk 1]
```diff
@@ -40,21 +40,21 @@ func (woc *wfOperationCtx) reconcileAgentPod(ctx context.Context) error {
 	}
 	// Check Pod is just created
 	if pod.Status.Phase != "" {
-		woc.updateAgentPodStatus(ctx, pod)
+		woc.updateAgentPodStatus(pod)
```
Comment (shuangkun) [inline workflow/controller/agent.go:43]: Why did we remove ctx?

File: workflow/controller/agent.go [hunk 2]
```diff
@@ -262,7 +262,9 @@ func (woc *wfOperationCtx) createAgentPod(ctx context.Context) (*apiv1.Pod, erro
 	if err != nil {
 		log.WithError(err).Info("Failed to create Agent pod")
 		if apierr.IsAlreadyExists(err) {
-			return created, nil
+			if existing, err := woc.controller.kubeclientset.CoreV1().Pods(woc.wf.ObjectMeta.Namespace).Get(ctx, pod.Name, metav1.GetOptions{}); err == nil {
```
Comment (shuangkun) [inline workflow/controller/agent.go:265]: Why do we need another judgment here?  Is apierr.IsAlreadyExists enough?

File: workflow/controller/agent.go (hunk 1 above)
Comment (jswxstw) [reply workflow/controller/agent.go:43]: `ctx` here is nerver used in `updateAgentPodStatus` now because I use `markTaskSetNodesError` instead of `markWorkflowError` and `make pre-commit -B` will fail if I keep this unused `ctx`.

File: workflow/controller/agent.go (hunk 2 above)
Comment (jswxstw) [reply workflow/controller/agent.go:265]: > created, err := woc.controller.kubeclientset.CoreV1().Pods(woc.wf.ObjectMeta.Namespace).Create(ctx, pod, metav1.CreateOptions{})

`created` will be nil even if the err returned is `AlreadyExists`.

File: workflow/controller/workflowpod.go [hunk 3]
```diff
@@ -530,7 +530,9 @@ func (woc *wfOperationCtx) createWorkflowPod(ctx context.Context, nodeName strin
 			// workflow pod names are deterministic. We can get here if the
 			// controller fails to persist the workflow after creating the pod.
 			woc.log.Infof("Failed pod %s (%s) creation: already exists", nodeName, pod.Name)
-			return created, nil
+			if existing, err = woc.controller.kubeclientset.CoreV1().Pods(woc.wf.ObjectMeta.Namespace).Get(ctx, pod.Name, metav1.GetOptions{}); err == nil {
```
Comment (juliev0) [inline workflow/controller/workflowpod.go:533]:
```suggestion
                         // get a reference to the currently existing Pod
			if existing, err = woc.controller.kubeclientset.CoreV1().Pods(woc.wf.ObjectMeta.Namespace).Get(ctx, pod.Name, metav1.GetOptions{}); err == nil {
```

File: workflow/controller/agent.go (hunk 2 above)
Comment (juliev0) [inline workflow/controller/agent.go:265]:
```suggestion
                         // get a reference to the currently existing Pod
			if existing, err := woc.controller.kubeclientset.CoreV1().Pods(woc.wf.ObjectMeta.Namespace).Get(ctx, pod.Name, metav1.GetOptions{}); err == nil {
```

Comment (juliev0) [inline workflow/controller/agent.go:265]:
```suggestion
                         // get a reference to the currently existing Pod
			if existing, err := woc.controller.kubeclientset.CoreV1().Pods(woc.wf.ObjectMeta.Namespace).Get(ctx, pod.Name, metav1.GetOptions{}); err == nil {
```

Comment (juliev0) [reply workflow/controller/agent.go:265]: Were you hitting this case? Was it panicing when the nil result was referenced?

File: workflow/controller/taskset.go [hunk 4]
```diff
@@ -52,6 +52,15 @@ func (woc *wfOperationCtx) getDeleteTaskAndNodePatch() (tasksPatch map[string]in
 	}
 	return
 }
+
+func (woc *wfOperationCtx) markTaskSetNodesError(err error) {
+	for _, node := range woc.wf.Status.Nodes {
```
Comment (juliev0) [inline workflow/controller/taskset.go:57]: Okay, so we'd set each Node that's of an Agent type to NodeError. That seems good. Just out of curiosity, do you know if it would be possible in the code for another Agent type Node to get added to `woc.wf.Status.Nodes` after we call this?

**Comment by juliev0** [comment]
Using node-level errors seems good as far as I can tell. Want to confirm - when a standard (non-Agent) Pod fails to be created, I assume that the Node results in `NodeError`, and thus this would be the same as that?

File: workflow/controller/taskset.go (hunk 4 above)
Comment (jswxstw) [reply workflow/controller/taskset.go:57]: I can confirm that each workflow will only create one agent pod to execute HTTP/Plugin templates, so all taskset nodes belong to one same agent.

**Comment by jswxstw** [comment]
> Using node-level errors seems good as far as I can tell. Want to confirm - when a standard (non-Agent) Pod fails to be created, I assume that the Node results in `NodeError`, and thus this would be the same as that?

You are right, if creating non-agent pod with non-transient error or pod executing with error, the node will be marked as `NodeError`.

File: workflow/controller/taskset.go (hunk 4 above)
Comment (juliev0) [reply workflow/controller/taskset.go:57]: Right, I know, but I’m actually asking if a new TaskSet Node can come along and get added to woc.wf.Status.Nodes? Does my question make sense?

Comment (juliev0) [reply workflow/controller/taskset.go:57]: I’m not saying it’s necessarily a problem if it does but good to understand expected behavior

Comment (jswxstw) [reply workflow/controller/taskset.go:57]: > I’m actually asking if a new TaskSet Node can come along and get added to woc.wf.Status.Nodes?

Sorry, I misunderstood your question. Your concerns make sense and it is possible that this could happen if onExitHandler of HTTP/Plugin types are used. Howerver, it will not cause any problems because `taskSetReconciliation` will be called again, so new Agent type nodes added will also be marked as `ERROR`.

Comment (juliev0) [reply workflow/controller/taskset.go:57]: yes, I think this seems okay, thanks

File: manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml [hunk 5]
```diff
@@ -103,3 +103,11 @@ rules:
...
     - get
     - delete
+- apiGroups:
+    - ""
+  resources:
+    - secrets
+  verbs:
+    - get
+  resourceNames:
+    - argo-workflows-agent-ca-certificates
```
[the remark this answers is not in the document]
Comment (jswxstw) [reply manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml:113]: https://github.com/argoproj/argo-workflows/blob/7357a1bbd06dbef29ad6fa757194e95562206a49/manifests/namespace-install/workflow-controller-rbac/workflow-controller-role.yaml#L85-L90
`argo-role` in `namespace-install` and `cluster-install` already has this rule.

**Review by juliev0 — APPROVED** [review]
