### PR TITLE
fix(cli): handle multi-resource yaml in offline lint. Fixes #12137

### LINKED ISSUE #10608: Linter fails if objects are not sorted in order of import
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

**What happened:**
We are using `argo lint` in CI pipeline to verify that workflows generated by kustomize have valid syntax. This works well with small projects with few WorkflowTemplates. However on larger projects it starts returning linting errors, e.g.:
```bash
$ argo lint --offline --kinds=workflows,workflowtemplates,cronworkflows filename.yaml
/home/user/filename.yaml:
   ✖ in "hello-world" (CronWorkflow): cannot validate Workflow: templates.run-all.tasks.run-all couldn't find workflow template "hello-world" in namespace "user1"

✖ 1 linting errors found!
```
Once I sort input with yq by Kind - in order to make WorkflowTemplate precede CronWorkflow, error gets resolved:
```bash
$ yq ea '[.] | sort_by(.kind)  | reverse |  .[] | splitDoc' filename.yaml >  filename2.yaml
$ argo lint --offline --kinds=workflows,workflowtemplates,cronworkflows filename2.yaml
✔ no linting errors found!
```
However in case we have `WorkflowTemplate` that is referencing another `WorkflowTemplate` - linter return similar error and sorting becomes more tricky. I observe the same behaviour in both recent offline linter and and default (non-offline).

**What was expected:**
linter returns error only if template is missing in whole input, rather than only checking in files it have read before.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
  namespace: user1
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: run-all
    templates:
      - name: run-all
        dag:
          failFast: false
          tasks:
          - name: run-all
            templateRef:
              name: hello-world
              template: whalesay

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
  namespace: user1
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### LINKED ISSUE #12137: `argo lint --offline` detects error about Workflow referring to 2nd or later WorkflowTemplate but it is false-positive.
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

`argo lint --offline` detects error about Workflow referring to 2nd or later WorkflowTemplate but it is false-positive.

For example, `argo lint --offline` detects no error about following Workflow `hello-world-local-arg-` referring to WorkflowTemplate `hello-world-template-local-arg-1`.

```yaml
# workflow1.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg-1
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg-2
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-local-arg-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-local-arg-1
              template: hello-world
```

```bash
$ argo lint --offline workflow1.yaml
✔ no linting errors found!
```

But `argo lint --offline` detects error about following Workflow `hello-world-local-arg-` referring to WorkflowTemplate `hello-world-template-local-arg-2` although WorkflowTemplate `hello-world-template-local-arg-2` is defined.

```yaml
# workflow2.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg-1
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg-2
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-local-arg-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-local-arg-2
              template: hello-world
```

```bash
$ argo lint --offline workflow2.yaml
workflow2.yaml:
   ✖ in "hello-world-local-arg-" (Workflow): templates.whalesay.steps[0].hello-world couldn't find workflow template "hello-world-template-local-arg-2" in namespace ""

✖ 1 linting errors found!
```

### Version

v3.4.13, v3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg-1
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg-2
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-local-arg-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-local-arg-2
              template: hello-world
```

### Logs from the workflow controller

```text
None
```

### Logs from in your workflow's wait container

```text
None
```

### PR DESCRIPTION
**Pull request by wang-wayne**
Fixes https://github.com/argoproj/argo-workflows/issues/12137
Fixes #10608 

### Motivation
If there are multiple templates in one yaml file. The `argo lint --offline` can only get the first template.
Because the `yaml.Unmarshal` function is used to parse a single YAML document.

### Modifications

Read yaml file with `common.ParseObjects` in offline mode.

### Verification
e2e test.
`argo lint --offline test.yaml`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg-1
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg-2
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-local-arg-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-local-arg-2
              template: hello-world
```
Add unittest case.

### CODE REVIEW

**Comment by agilgur5** [comment]
@miltalex do you want to try reviewing this? Since you've worked on `argo lint` before

**Comment by agilgur5** [comment]
I'm curious if this also fixes #10608?

**Comment by miltalex** [comment]
> @miltalex do you want to try reviewing this? Since you've worked on `argo lint` before

I would be happy to review it

**Comment by wang-wayne** [comment]
> I'm curious if this also fixes #10608?

Yes, I had a validation. This PR also fixes https://github.com/argoproj/argo-workflows/issues/10608.

**Comment by wang-wayne** [comment]
> > @miltalex do you want to try reviewing this? Since you've worked on `argo lint` before
> 
> I would be happy to review it

Hi @miltalex , thank you for reviewing my PR! Do you have any comments or suggestions to share? I would appreciate any feedback you might have. Thank you!

**Review by miltalex — CHANGES_REQUESTED** [review]
Nice work, thank you very much for submitting the fix. I have a small stylistic suggestion otherwise LGTM

**Review by miltalex — APPROVED** [review]

**Review by miltalex — APPROVED** [review]

File: pkg/apiclient/offline-client.go [hunk 1]
```diff
@@ -50,42 +49,43 @@ func newOfflineClient(paths []string) (context.Context, Client, error) {
...
-			var generic map[string]interface{}
-			if err := yaml.Unmarshal(bytes, &generic); err != nil {
-				return fmt.Errorf("failed to parse YAML from file %s: %w", path, err)
-			}
-			switch generic["kind"] {
-			case "ClusterWorkflowTemplate":
-				cwftmpl := new(wfv1.ClusterWorkflowTemplate)
-				if err := yaml.Unmarshal(bytes, &cwftmpl); err != nil {
-					return fmt.Errorf("failed to unmarshal file %s as a ClusterWorkflowTemplate: %w", path, err)
+			for _, pr := range common.ParseObjects(bytes, false) {
```
Comment (agilgur5) [inline pkg/apiclient/offline-client.go:52]: I see this is copied from `lint.go`, so similarly I'd say this is fine for now, but a more clear name would be better in both places, like `parsed` instead of `pr` (which makes one think of "pull request")
```suggestion
			for _, parsed := range common.ParseObjects(bytes, false) {
```

File: pkg/apiclient/offline-client.go [hunk 2]
```diff
@@ -50,42 +49,43 @@ func newOfflineClient(paths []string) (context.Context, Client, error) {
...
+				obj, err := pr.Object, pr.Err
+				if err != nil {
+					return fmt.Errorf("failed to parse YAML from file %s: %w", path, err)
 				}
 
-				if _, ok := clusterWorkflowTemplateGetter.clusterWorkflowTemplates[cwftmpl.Name]; ok {
-					return fmt.Errorf("duplicate ClusterWorkflowTemplate found: %q", cwftmpl.Name)
+				if obj == nil {
+					continue // could not parse to kubernetes object
```
Comment (agilgur5) [inline pkg/apiclient/offline-client.go:59]: This too is copied from `lint.go`, although I would think both places should have an error in this case rather than a silent `continue`.

File: pkg/apiclient/offline-client.go [hunk 3]
```diff
@@ -50,42 +49,43 @@ func newOfflineClient(paths []string) (context.Context, Client, error) {
...
-				if err := yaml.Unmarshal(bytes, &wftmpl); err != nil {
-					return fmt.Errorf("failed to unmarshal file %s as a WorkflowTemplate: %w", path, err)
-				}
-				getter, ok := workflowTemplateGetters[wftmpl.Namespace]
-				if !ok {
-					getter = &offlineWorkflowTemplateNamespacedGetter{
-						namespace:         wftmpl.Namespace,
-						workflowTemplates: map[string]*wfv1.WorkflowTemplate{},
+				objName := obj.GetName()
+				namespace := obj.GetNamespace()
```
Comment (agilgur5) [inline pkg/apiclient/offline-client.go:63]: same here that this is copied from `lint.go`, but the naming could be consistent with `objName` as `objNs` in both places
```suggestion
				objNs := obj.GetNamespace()
```

**Review by agilgur5 — APPROVED** [review]
Nice work. This mostly LGTM, so I'll merge this, but there's some follow-ups that I think can be made in separate PRs to refactor this a tiny bit along with the existing code style it copies.
