### PR TITLE
fix: ensure variable sub and processing is performed. Fixes #12941

### LINKED ISSUE #12941: Error when using expressions with retries and `inputs.parameters` in podSpecPatch resources requests
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

This is a follow on issue to https://github.com/argoproj/argo-workflows/issues/10362.
The solution there only seems to work when resource parameters are referenced in the podSpecPatch via workflow.parameters.
However, in order to be able to modify resource requests for retries of steps, we need to be able to reference resource parameters in the podSpecPatch via inputs.parameters, in conjunction with expressions applied to {{retries}}.
That seems to fail with `Error applying PodSpecPatch`.

In the workflow_controller logs I see errors like the following:
```
Non-transient error: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'""
```

Not sure what might be causing that.

### Version

3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-
spec:
  entrypoint: wf
  templates:
  - name: wf
    steps:

    - - name: run-task1
        template: run-task
        arguments:
          parameters:
            - name: memreqnum
              value: '25'
            - name: memrequnit
              value: Mi
            - name: message
              value: "hello from run-task1"

      - name: run-task2
        template: run-task
        arguments:
          parameters:
            - name: memreqnum
              value: '300'
            - name: memrequnit
              value: Mi
            - name: message
              value: "hello from run-task2"
 

  - name: run-task
    inputs:
      parameters:
        - name: memreqnum
        - name: memrequnit
        - name: message
    retryStrategy:
      limit: "2"
      retryPolicy: "Always"
      expression: 'lastRetry.status == "Error" or (lastRetry.status == "Failed" and asInt(lastRetry.exitCode) not in [1,2,127])'
    podSpecPatch: |
      containers:
      - name: main
        resources:
          requests:
            memory: "{{=(sprig.int(retries)+1)*sprig.int(inputs.parameters.memreqnum)}}{{inputs.parameters.memrequnit}}"
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

time="2024-04-16T05:57:21.759Z" level=info msg="Processing workflow" Phase= ResourceVersion=1002197419 namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.766Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=wf-vp9xw
time="2024-04-16T05:57:21.766Z" level=info msg="Updated phase  -> Running" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.766Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.766Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.767Z" level=info msg="Retry node wf-vp9xw initialized Running" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.767Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.767Z" level=info msg="Steps node wf-vp9xw-2274503212 initialized Running" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.767Z" level=info msg="StepGroup node wf-vp9xw-3885283846 initialized Running" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.767Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.767Z" level=info msg="Retry node wf-vp9xw-587369068 initialized Running" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.767Z" level=info msg="Pod node wf-vp9xw-3271220583 initialized Pending" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.769Z" level=error msg="Mark error node" error="Error applying PodSpecPatch" namespace=default nodeName="wf-vp9xw(0)[0].run-task1(0)" workflow=wf-vp9xw
time="2024-04-16T05:57:21.769Z" level=info msg="node wf-vp9xw-3271220583 phase Pending -> Error" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.769Z" level=info msg="node wf-vp9xw-3271220583 message: Error applying PodSpecPatch" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.769Z" level=info msg="node wf-vp9xw-3271220583 finished: 2024-04-16 05:57:21.769247744 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.769Z" level=info msg="Retry Policy: Always (onFailed: true, onError true)" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.769Z" level=info msg="1 child nodes of wf-vp9xw(0)[0].run-task1 failed. Trying again..." namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.770Z" level=info msg="Pod node wf-vp9xw-654162282 initialized Pending" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.771Z" level=error msg="Mark error node" error="Error applying PodSpecPatch" namespace=default nodeName="wf-vp9xw(0)[0].run-task1(1)" workflow=wf-vp9xw
time="2024-04-16T05:57:21.771Z" level=info msg="node wf-vp9xw-654162282 phase Pending -> Error" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.771Z" level=info msg="node wf-vp9xw-654162282 message: Error applying PodSpecPatch" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.771Z" level=info msg="node wf-vp9xw-654162282 finished: 2024-04-16 05:57:21.771351431 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.771Z" level=info msg="Retry Policy: Always (onFailed: true, onError true)" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.771Z" level=info msg="2 child nodes of wf-vp9xw(0)[0].run-task1 failed. Trying again..." namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.772Z" level=info msg="Pod node wf-vp9xw-1056972233 initialized Pending" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=error msg="Mark error node" error="Error applying PodSpecPatch" namespace=default nodeName="wf-vp9xw(0)[0].run-task1(2)" workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=info msg="node wf-vp9xw-1056972233 phase Pending -> Error" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=info msg="node wf-vp9xw-1056972233 message: Error applying PodSpecPatch" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=info msg="node wf-vp9xw-1056972233 finished: 2024-04-16 05:57:21.773435805 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=info msg="Retry Policy: Always (onFailed: true, onError true)" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=info msg="No more retries left. Failing..." namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=info msg="node wf-vp9xw-587369068 phase Running -> Error" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=info msg="node wf-vp9xw-587369068 message: No more retries left" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=info msg="node wf-vp9xw-587369068 finished: 2024-04-16 05:57:21.773862122 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.773Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.774Z" level=info msg="Retry node wf-vp9xw-637701925 initialized Running" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.774Z" level=info msg="Pod node wf-vp9xw-2667399556 initialized Pending" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.775Z" level=error msg="Mark error node" error="Error applying PodSpecPatch" namespace=default nodeName="wf-vp9xw(0)[0].run-task2(0)" workflow=wf-vp9xw
time="2024-04-16T05:57:21.775Z" level=info msg="node wf-vp9xw-2667399556 phase Pending -> Error" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.775Z" level=info msg="node wf-vp9xw-2667399556 message: Error applying PodSpecPatch" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.775Z" level=info msg="node wf-vp9xw-2667399556 finished: 2024-04-16 05:57:21.775651548 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.775Z" level=info msg="Retry Policy: Always (onFailed: true, onError true)" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.776Z" level=info msg="1 child nodes of wf-vp9xw(0)[0].run-task2 failed. Trying again..." namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.776Z" level=info msg="Pod node wf-vp9xw-989490561 initialized Pending" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.777Z" level=error msg="Mark error node" error="Error applying PodSpecPatch" namespace=default nodeName="wf-vp9xw(0)[0].run-task2(1)" workflow=wf-vp9xw
time="2024-04-16T05:57:21.777Z" level=info msg="node wf-vp9xw-989490561 phase Pending -> Error" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.777Z" level=info msg="node wf-vp9xw-989490561 message: Error applying PodSpecPatch" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.777Z" level=info msg="node wf-vp9xw-989490561 finished: 2024-04-16 05:57:21.777513727 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.777Z" level=info msg="Retry Policy: Always (onFailed: true, onError true)" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.777Z" level=info msg="2 child nodes of wf-vp9xw(0)[0].run-task2 failed. Trying again..." namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.778Z" level=info msg="Pod node wf-vp9xw-1123564418 initialized Pending" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=error msg="Mark error node" error="Error applying PodSpecPatch" namespace=default nodeName="wf-vp9xw(0)[0].run-task2(2)" workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-1123564418 phase Pending -> Error" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-1123564418 message: Error applying PodSpecPatch" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-1123564418 finished: 2024-04-16 05:57:21.779335294 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="Retry Policy: Always (onFailed: true, onError true)" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="No more retries left. Failing..." namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-637701925 phase Running -> Error" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-637701925 message: No more retries left" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-637701925 finished: 2024-04-16 05:57:21.779739696 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="Step group node wf-vp9xw-3885283846 deemed failed: child 'wf-vp9xw-587369068' failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-3885283846 phase Running -> Failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-3885283846 message: child 'wf-vp9xw-587369068' failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-3885283846 finished: 2024-04-16 05:57:21.779795413 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="step group wf-vp9xw-3885283846 was unsuccessful: child 'wf-vp9xw-587369068' failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="Outbound nodes of wf-vp9xw-587369068 is [wf-vp9xw-1056972233]" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="Outbound nodes of wf-vp9xw-637701925 is [wf-vp9xw-1123564418]" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="Outbound nodes of wf-vp9xw-2274503212 is [wf-vp9xw-1056972233 wf-vp9xw-1123564418]" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-2274503212 phase Running -> Failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-2274503212 message: child 'wf-vp9xw-587369068' failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.779Z" level=info msg="node wf-vp9xw-2274503212 finished: 2024-04-16 05:57:21.77985872 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="Retry Policy: OnError (onFailed: false, onError true)" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="Node not set to be retried after status: Failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="node wf-vp9xw phase Running -> Failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="node wf-vp9xw message: child 'wf-vp9xw-587369068' failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="node wf-vp9xw finished: 2024-04-16 05:57:21.78010322 +0000 UTC" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg=reconcileAgentPod namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="Updated phase Running -> Failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="Updated message  -> child 'wf-vp9xw-587369068' failed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="Marking workflow completed" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.780Z" level=info msg="Marking workflow as pending archiving" namespace=default workflow=wf-vp9xw
time="2024-04-16T05:57:21.786Z" level=info msg="cleaning up pod" action=deletePod key=default/wf-vp9xw-1340600742-agent/deletePod
time="2024-04-16T05:57:21.797Z" level=info msg="Workflow update successful" namespace=default phase=Failed resourceVersion=1002197420 workflow=wf-vp9xw
time="2024-04-16T05:57:22.073Z" level=info msg="archiving workflow" namespace=default uid=693ecff0-fad6-4774-95d5-1035f1004dfd workflow=wf-vp9xw
time="2024-04-16T05:57:22.123Z" level=info msg="Queueing Failed workflow default/wf-vp9xw for delete in 29m59s due to TTL"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by isubasinghe**
Fixes #12941

### Motivation
This makes the behaviour  of the podSpec patch consistent by processing it via ProcessArgs in the case of template level expressions existing. It also fixes an issue where the replaceMap was emptied out for no reason. 

### Modifications
Performs the same processing applied to workflow level pod spec strategy.

### Verification
Unit test was added and additionally manual testing was performed.

### CODE REVIEW

File: workflow/common/util.go
Comment (Joibel) [inline workflow/common/util.go:1]: It feels like we could also now drop line 230 (I can't comment directly on the unchanged line it seems), to avoid the cost of running .Replace twice

File: workflow/controller/workflowpod.go [hunk 1]
```diff
@@ -376,7 +376,17 @@ func (woc *wfOperationCtx) createWorkflowPod(ctx context.Context, nodeName strin
 		podSpecPatchs = append(podSpecPatchs, processedTmpl.PodSpecPatch)
 	}
 	if tmpl.HasPodSpecPatch() {
-		podSpecPatchs = append(podSpecPatchs, tmpl.PodSpecPatch)
+		localParams := make(map[string]string)
```
Comment (Joibel) [inline workflow/controller/workflowpod.go:379]: This is duplicated code, can you tidy it into a function?

**Review by Joibel — CHANGES_REQUESTED** [review]

File: workflow/common/util.go
Comment (isubasinghe) [reply workflow/common/util.go:1]: It does feel like that but the comments indicate otherwise, thats why I didn't touch it.
line 228 and line 239 are what I am referring to.

File: workflow/controller/workflowpod.go (hunk 1 above)
Comment (isubasinghe) [reply workflow/controller/workflowpod.go]: Addressed!

File: workflow/common/util.go
Comment (isubasinghe) [reply workflow/common/util.go:1]: @terrytangyuan do you have any opinions on this and if the comments I am referring to make any sense?

Comment (terrytangyuan) [reply workflow/common/util.go:1]: It should be fine to remove as long as we have tests around it and make sure it still works with the case mentioned in the comment

Comment (isubasinghe) [reply workflow/common/util.go:1]: It is not fine to remove, the tests will break the comments in line 228 and 239 are accurate. If your input parameters have any global variables, they will fail to resolve.

Comment (Joibel) [reply workflow/common/util.go:1]: Does this mean there are some variables that can double substitute - as in reference other variables? I've tried following this through and haven't worked it out.

**Review by Joibel — APPROVED** [review]

File: workflow/common/util.go
Comment (isubasinghe) [reply workflow/common/util.go:1]: Yup that is it.
