### PR TITLE
fix: Workflow details accessing undefined templateRef. Fixes #9167

### LINKED ISSUE #9167: UI: `e.templateRef is undefined` when using inline template
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Creates a simple workflow with inline template. It should succeed.

What version are you running?
Argo v3.2.11

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

From https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/steps-inline-workflow.yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-inline-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This workflow demonstrates running a steps with inline templates.
    workflows.argoproj.io/version: ">= 3.2.0"
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: a
            inline:
              container:
                image: argoproj/argosay:v2
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixes #9167. This is a regression and needs to be backported.

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by alexec** [comment]
We do not back-port fixes to unsupported versions. Please upgrade to v3.3

File: ui/src/app/shared/pod-name.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export const getTemplateNameFromNode = (node: NodeStatus): string => {
     }
 
     // fall back to v1 pod names if no templateName or templateRef defined
-    if (!node.templateRef) {
+    if (node?.templateRef === undefined || node?.templateRef.template === '') {
```
Comment (agilgur5) [inline ui/src/app/shared/pod-name.ts:58]: the `node?.` part is not necessary; the `node.templateName` line above this would error out before reaching this line if it didn't exist.

#7605 did fix this, it just never got backported to 3.2.x. So #9167 was a pure duplicate.

This whole function can actually be simplified into a one-liner, which I'm working on.

Comment (agilgur5) [reply ui/src/app/shared/pod-name.ts:58]: Simplified in #12964
