### PR TITLE
fix: Support terminating with `templateRef`. Fixes #7214

### LINKED ISSUE #7214: workflows stuck because controller is not terminating istio sidecar
## Summary
What happened/what you expected to happen?

I created a simple workflow with `workflows.argoproj.io/kill-cmd-istio-proxy: '["pilot-agent", "request", "POST", "quitquitquit"]'` annotation. I expected the wait container to use this command to kill istio sidecar, but it didn't.

What version of Argo Workflows are you running?
v3.2.0

## Diagnostics

Run any workflow with k8sapi executor with `workflows.argoproj.io/kill-cmd-<sidecar_name>` and observe that the command in the annotation is not used.

Looking into the code reveals that the kill command is hardcoded and doesn't take the annotation into account. https://github.com/argoproj/argo-workflows/blob/e8a2f37784f57c289024f0c5061fde8ec248314e/workflow/executor/k8sapi/client.go#L112

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>
Fixes #7214

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1171,6 +1171,7 @@ func (woc *wfOperationCtx) assessNodeStatus(pod *apiv1.Pod, node *wfv1.NodeStatu
 	}
 
 	for _, c := range pod.Status.ContainerStatuses {
+		println("ALEX", "container=", c.Name, "terminated=", c.State.Terminated != nil)
```
Comment (terrytangyuan) [inline workflow/controller/operator.go:1174]: Remove?

Comment (alexec) [reply workflow/controller/operator.go:1174]: 👀 ops

**Review by terrytangyuan — APPROVED** [review]
LGTM. Although we probably want to document the precedence somewhere.
