### PR TITLE
fix(cli): Validate cron on update. Fixes #5691

### LINKED ISSUE #5691: CronWorkflow schedule giving inconsistent experience
## Summary 

This issue contains several minor issues related to CronWorkflow:

AFIAK we don't support the second-level CronWorkflow schedule. Second-level CronWorkflow will be rejected when submitting.  But the crontab translator seems to have no problem with it. This is an inconsistent user experience:

Screen Shot 2021-04-17 at 1 00 58 AM

Furthermore, for an existing & valid CronWorkflow, the user can actually update it to a second-level CronWorkflow, and the schedule doesn't seem to work (Next schedule time says "xx seconds ago").

crontab

We should have consistent UX for this.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

File: ui/src/app/cron-workflows/components/schedule-validator.tsx [hunk 1]
```diff
@@ -5,6 +5,9 @@ const x = require('cronstrue');
 
 export const ScheduleValidator = ({schedule}: {schedule: string}) => {
     try {
+        if (schedule.split(' ').length === 6) {
```
Comment (terrytangyuan) [inline ui/src/app/cron-workflows/components/schedule-validator.tsx:8]: Also provide an error message when length > 6 so users can be aware of mistakes earlier in the UI?

**Review by sarabala1979 — APPROVED** [review]
