### PR TITLE
fix: replace deprecated `bouk/staticfiles` with native Go `embed`. fixes #11654

### LINKED ISSUE #11654: Deprecated - Static files embed library
# Summary

From https://github.com/argoproj/argo-workflows/pull/11644 , lib for embed static files https://github.com/bouk/staticfiles is deprecated now. It should be replaced with Go standard library

# Use Cases
- maintainable code

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by sonbui00**
Fixes #11654

### Motivation

- bouk/staticfiles is deprecated
- Sometime server/static/files.go is added to git commit unexpectedly

### Modifications

- remove bouk/staticfiles, use standard lib

### Verification

- make test
- manual check

### CODE REVIEW

**Comment by sonbui00** [comment]
@agilgur5 Should I do anything to go forward for this?

**Comment by agilgur5** [comment]
Usually the process is that someone does initial reviews and if it's not an approver, we wait for an approver to then approve and merge. 

Workflows doesn't have many active approvers so there's occasionally a backlog as there is now. I also have some PRs that have been open for 3+ weeks 😕 That is probably the longest wait I've seen in the past few months though, fwiw (I've only been actively contributing the past few, so can't say beyond that).

I had initially deferred review to someone who may know `embed` etc better, but we might not actually have any contributors familiar it, so maybe I should do first review.

**Comment by agilgur5** [comment]
For context, I am currently a Member (though may become a Reviewer at the next membership meeting). Lead > Approver > Reviewer > Member. You can see the Argo governance docs [here](https://github.com/argoproj/argoproj/blob/master/community/membership.md). You are also welcome to request Membership if you're interested 😉 (we can probably find a sponsor as well; sponsors must be approvers+, though support from others in the community like me helps!)

File: server/static/static.go [hunk 1]
```diff
@@ -50,6 +50,49 @@ func (s *FilesServer) ServerFiles(w http.ResponseWriter, r *http.Request) {
...
 	}
 
-	// in my IDE (IntelliJ) the next line is red for some reason - but this is fine
-	ServeHTTP(w, r)
+	if r.URL.Path == "/" || !s.uiAssetExists(r.URL.Path) {
+		data, err := s.getIndexData()
+		if err != nil {
+			http.Error(w, err.Error(), http.StatusInternalServerError)
+			return
+		}
```
Comment (isubasinghe) [inline server/static/static.go:58]: This would be consistent with the previous behaviour because of the `!s.uiAssetExists`, just making that note because it isn't immediately obvious.

**Review by isubasinghe — APPROVED** [review]
I am happy with this, looks sensible, the one suggestion I would like to state is that perhaps some generation of the strings used for ByteReedSeeker could be done? Currently only a single "hello world" string is used in all the test cases.

File: server/static/static.go (hunk 1 above)
Comment (sonbui00) [reply server/static/static.go:58]: @isubasinghe not sure about your mention **ByteReedSeeker**
but the !s.uiAssetExists match with previouse logic here https://github.com/argoproj/argo-workflows/blob/baef4856ff2603c76dbe277c825eaa3f9788fc91/server/static/static.go#L21-L24
So if static files does not exist, the index.html will be return

**Comment by juliev0** [comment]
@sonbui00 sorry this ended up being delayed. I see @isubasinghe approved this awhile back. @isubasinghe is now an Approver and can merge. Do you want to fix the merge conflicts and get this merged still?

**Comment by sonbui00** [comment]
> @sonbui00 sorry this ended up being delayed. I see @isubasinghe approved this awhile back. @isubasinghe is now an Approver and can merge. Do you want to fix the merge conflicts and get this merged still?

@juliev0 I'll check it

**Comment by juliev0** [comment]
let me know when you've fixed the codegen and lint issues and we can merge this

**Comment by sonbui00** [comment]
@juliev0 codegen and lint issues have been fixed. help me review

**Comment by juliev0** [comment]
Sorry @isubasinghe - it looks like your original review has been removed with the fixes @sonbui00 made . Can you re-review/merge when you have time?

**Comment by isubasinghe** [comment]
@sonbui00 Could you please fix the merge conflicts? I will merge this in ASAP, sorry about forgetting to re-review this, just have a million things to do atm.

File: util/io/bytereadseeker.go [hunk 2]
```diff
@@ -0,0 +1,38 @@
+package io
+
+import (
+	"io"
+	"io/fs"
+)
+
+func NewByteReadSeeker(data []byte) *byteReadSeeker {
```
Comment (Joibel) [inline util/io/bytereadseeker.go:8]: Can't we just use https://pkg.go.dev/bytes#NewReader to do this?

File: util/io/subdirfs.go [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+	dir string
+	fs  fs.FS
+}
+
+func (s subDirFs) Open(name string) (fs.File, error) {
+	return s.fs.Open(filepath.Join(s.dir, name))
+}
+
+// NewSubDirFS returns file system that represents sub-directory in a wrapped file system
+func NewSubDirFS(dir string, fs fs.FS) *subDirFs {
```
Comment (Joibel) [inline util/io/subdirfs.go:18]: Less sure on this, but can't this be replaced with https://pkg.go.dev/io/fs#SubFS

**Review by Joibel — CHANGES_REQUESTED** [review]

File: util/io/bytereadseeker.go (hunk 2 above)
Comment (isubasinghe) [reply util/io/bytereadseeker.go:8]: Nice find, I didn't know about this

File: util/io/subdirfs.go (hunk 3 above)
Comment (isubasinghe) [reply util/io/subdirfs.go:18]: It does seem that you can replace this as well.

File: ui/dist/app/gitkeep
[the remark this answers is not in the document]
Comment (sonbui00) [reply ui/dist/app/gitkeep:1]: There is an issue with `CLI_PKG_FILES` in Makefile, that try to scan files, and have error when this folder not create or empty, `.gitkeep` also not work

`ui/embed.go:9:12: pattern dist/app: no matching files found`

I'm trying to fix `CLI_PKG_FILES` in Makefile now

[the remark this answers is not in the document]
Comment (Joibel) [reply ui/dist/app/gitkeep:1]: Ah, I see. That's messy, and probably not easy to fix. If you find a way that would be good, but I'm happy to accept this.

You should be able to just keep this `gitkeep` file as is, but revert both `.gitignore` changes. Once a file is tracked by git, it will be kept regardless of .gitignore.

File: .gitignore [hunk 4]
```diff
@@ -4,7 +4,7 @@ Pipfile
 .node-version
 .DS_Store
 vendor/
-dist/
+dist/*
```
[the remark this answers is not in the document]
Comment (sonbui00) [reply .gitignore]: reverted

File: ui/.gitignore
[the remark this answers is not in the document]
Comment (sonbui00) [reply ui/.gitignore:1]: reverted

File: util/io/subdirfs.go (hunk 3 above)
Comment (sonbui00) [reply util/io/subdirfs.go]: Thanks. I've updated with your suggestion

File: util/io/bytereadseeker.go (hunk 2 above)
Comment (sonbui00) [reply util/io/bytereadseeker.go]: Thanks. I've updated with your suggestion

File: Makefile [hunk 5]
```diff
@@ -115,7 +115,7 @@ endif
 HACK_PKG_FILES_AS_PKGS ?= false
 ifeq ($(HACK_PKG_FILES_AS_PKGS),false)
 	ARGOEXEC_PKG_FILES        := $(shell go list -f '{{ join .Deps "\n" }}' ./cmd/argoexec/ |  grep 'argoproj/argo-workflows/v3/' | xargs go list -f '{{ range $$file := .GoFiles }}{{ print $$.ImportPath "/" $$file "\n" }}{{ end }}' | cut -c 39-)
-	CLI_PKG_FILES             := $(shell go list -f '{{ join .Deps "\n" }}' ./cmd/argo/ |  grep 'argoproj/argo-workflows/v3/' | xargs go list -f '{{ range $$file := .GoFiles }}{{ print $$.ImportPath "/" $$file "\n" }}{{ end }}' | cut -c 39-)
+	CLI_PKG_FILES             := $(shell [ -f ui/dist/app/index.html ] || (mkdir -p ui/dist/app && touch ui/dist/app/placeholder); go list -f '{{ join .Deps "\n" }}' ./cmd/argo/ |  grep 'argoproj/argo-workflows/v3/' | xargs go list -f '{{ range $$file := .GoFiles }}{{ print $$.ImportPath "/" $$file "\n" }}{{ end }}' | cut -c 39-)
```
Comment (Joibel) [inline Makefile:118]: Ah, a hacky fix which does the job.

This needs to happen for the other definition of CLI_PKG_FILES, as it's currently silently breaking the windows unit tests: https://github.com/argoproj/argo-workflows/actions/runs/12125568542/job/33805817123

They pass because they're not required, but it would still be good if they ran.

**Review by Joibel — CHANGES_REQUESTED** [review]

File: Makefile (hunk 5 above)
Comment (sonbui00) [reply Makefile:118]: I've fixed it
