### PR TITLE
fix: cannot access HTTP template's outputs

### LINKED ISSUE #7199: cannot resolve HTTP template's outputs.parameters.result
> base on v3.2.3
1. looks like we cannot get HTTP template's result, validation will failed
2. ~other nodes cannot connect to HTTP node in DAG, because they got empty HTTP node's outbound nodes~ ( already fix in #7082 )
3. result should put in outputs.result instead of outputs.parameters.result I think ( this isn't a bug

tested with this workflow, submit failed with `Internal Server Error: templates.main.tasks.echo failed to resolve {{tasks.good.outputs.parameters.result}}`, that's problem 1
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-template-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        # url: http://dummy.restapiexample.com/api/v1/employees
        url: "{{inputs.parameters.url}}"
    - name: echo
      inputs:
        parameters:
        - name: msg
      container:
        image: alpine:latest
        command:
        - echo
        args:
        - "{{inputs.parameters.msg}}"
    - name: main
      dag:
        tasks:
        - name: good
          template: http
          arguments:
            parameters: [{name: url, value: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"}]
        - name: echo
          template: echo
          dependencies: [ good ]
          arguments:
            parameters:
            - name: msg
              value: "{{tasks.good.outputs.parameters.result}}"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by book987**
fix #7199 

Signed-off-by: book987 <book87987book@gmail.com>

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
🥇

**Review by sarabala1979 — APPROVED** [review]
LGTM

**Comment by sarabala1979** [comment]
@book987 Can you fix the lint issue?

**Comment by alexec** [comment]
looks like lint job is timing out, if this passes lint locally, it probably is transient problem

**Comment by alexec** [comment]
I think we need to increase the lint timeout:

https://github.com/argoproj/argo-workflows/blob/57d894cb9a59ae294978af2ae106cae269446107/.golangci.yml#L4

File: test/e2e/functional_test.go [hunk 1]
```diff
@@ -813,6 +813,14 @@ func (s *FunctionalSuite) TestDataTransformation() {
 		})
 }
 
+func (s *FunctionalSuite) TestHTTPOutputs() {
+	s.Given().
+		Workflow("@testdata/http-outputs.yaml").
+		When().
+		SubmitWorkflow().
+		WaitForWorkflow(fixtures.ToBeSucceeded)
```
Comment (simster7) [inline test/e2e/functional_test.go:821]: I think we should actually check that the outputs are present correctly? 

You can use `ExpectWorkflow` for this:

```go
	WaitForWorkflow(fixtures.ToBeSucceeded).
	ExpectWorkflow(func(t *testing.T, _ *metav1.ObjectMeta, status *wfv1.WorkflowStatus) {
                // look in `status` for outputs
	})
```

**Comment by book987** [comment]
> I think we need to increase the lint timeout:
> 
> https://github.com/argoproj/argo-workflows/blob/57d894cb9a59ae294978af2ae106cae269446107/.golangci.yml#L4
> 
> This could be fixed in this PR.

Lint passed, I also increase timeout 8m in this PR.

File: test/e2e/functional_test.go (hunk 1 above)
Comment (book987) [reply test/e2e/functional_test.go]: Hi, I've add ExpectWorkflow but some check failed, I'm fixing it now.

**Comment by alexec** [comment]
Test failure:
```
Checking expectation http-outputs-cqhc2
1040
http-outputs-cqhc2 : Succeeded 
1041
    functional_test.go:825: 
1042
        	Error Trace:	functional_test.go:825
1043
        	            				then.go:66
1044
        	            				then.go:41
1045
        	            				functional_test.go:823
1046
        	Error:      	Expected value not to be nil.
1047
        	Test:       	TestFunctionalSuite/TestHTTPOutputs
1048
=== FAIL: FunctionalSuite/TestHTTPOutputs
```

**Comment by book987** [comment]
> Test failure:
> 
> ```
> Checking expectation http-outputs-cqhc2
> 1040
> http-outputs-cqhc2 : Succeeded 
> 1041
>     functional_test.go:825: 
> 1042
>         	Error Trace:	functional_test.go:825
> 1043
>         	            				then.go:66
> 1044
>         	            				then.go:41
> 1045
>         	            				functional_test.go:823
> 1046
>         	Error:      	Expected value not to be nil.
> 1047
>         	Test:       	TestFunctionalSuite/TestHTTPOutputs
> 1048
> === FAIL: FunctionalSuite/TestHTTPOutputs
> ```

Hi, this e2e test passed on my laptop, I need some help 😢 Is there any way we can get the full workflow yaml?

```
/usr/local/Cellar/go/1.16/libexec/bin/go tool test2json -t /private/var/folders/c7/xsy5l1m919sbbzdlvnk40rlm0000gn/T/___TestHTTPOutputs_in_github_com_argoproj_argo_workflows_v3_test_e2e -test.v -test.paniconexit0 -test.run ^\QTestFunctionalSuite\E$/^\QTestHTTPOutputs\E$ -testify.m ^TestHTTPOutputs$
=== RUN   TestFunctionalSuite
time="2021-11-15T14:37:47+08:00" level=info msg="config map" name=workflow-controller-configmap
--- PASS: TestFunctionalSuite (10.26s)
=== RUN   TestFunctionalSuite/TestHTTPOutputs
Submitting workflow  http-outputs-
Waiting 30s for workflow metadata.name=http-outputs-g8wcb
 ? http-outputs-g8wcb Workflow 0s      

 ● http-outputs-g8wcb   Workflow 0s      
 └ ● http-outputs-g8wcb DAG      0s      
 └ ◷ http               HTTP     0s      

 ● http-outputs-g8wcb   Workflow 0s      
 └ ● http-outputs-g8wcb DAG      0s      
 └ ✔ http               HTTP     0s      

 ● http-outputs-g8wcb   Workflow 0s      
 └ ● http-outputs-g8wcb DAG      0s      
 └ ✔ http               HTTP     0s      
 └ ◷ echo               Pod      0s      

 ✔ http-outputs-g8wcb   Workflow 10s     
 └ ✔ http-outputs-g8wcb DAG      10s     
 └ ✔ http               HTTP     0s      
 └ ✔ echo               Pod      1s      

Condition "to be Succeeded" met after 10s
Checking expectation http-outputs-g8wcb
http-outputs-g8wcb : Succeeded 
=== PASS: FunctionalSuite/TestHTTPOutputs
    --- PASS: TestFunctionalSuite/TestHTTPOutputs (10.24s)
PASS

Process finished with exit code 0
```

**Comment by alexec** [comment]
I wonder if test is not using executor image built?

**Comment by book987** [comment]
> I wonder if test is not using executor image built?

You're right, I found this in argo log, it still put the result in `outputs.parameters`, that means CI is not using executor image built I think.

https://github.com/argoproj/argo-workflows/runs/4208211529?check_suite_focus=true#step:15:3186

**Comment by alexec** [comment]
That's is odd. This works fine for other builds. I wonder if it fails on forks?

**Comment by alexec** [comment]
Ok. So HTTP templates are run by the agent. Perhaps the agent does not have correct pull policy.

**Comment by alexec** [comment]
Agent does not respect pull policy:

https://github.com/argoproj/argo-workflows/blob/eb9a4289729c0d91bfa45cb5895e5bef61ce483e/workflow/controller/agent.go#L95

Can you please fix that in this PR too?

**Comment by book987** [comment]
> Agent does not respect pull policy:
> 
> https://github.com/argoproj/argo-workflows/blob/eb9a4289729c0d91bfa45cb5895e5bef61ce483e/workflow/controller/agent.go#L95
> 
> Can you please fix that in this PR too?

awesome! fixed.

File: test/e2e/testdata/http-outputs.yaml [hunk 2]
```diff
@@ -0,0 +1,48 @@
+apiVersion: argoproj.io/v1alpha1
+kind: Workflow
+metadata:
+  generateName: http-outputs-
+  labels:
```
Comment (alexec) [inline test/e2e/testdata/http-outputs.yaml:5]: please delete all the labels, not needed

File: workflow/executor/agent.go [hunk 3]
```diff
@@ -133,7 +134,7 @@ func (ae *AgentExecutor) executeHTTPTemplate(ctx context.Context, tmpl wfv1.Temp
 		return nil, err
 	}
 	outputs := &wfv1.Outputs{}
-	outputs.Parameters = append(outputs.Parameters, wfv1.Parameter{Name: "result", Value: wfv1.AnyStringPtr(response)})
```
Comment (alexec) [inline workflow/executor/agent.go:136]: @sarabala1979 is this a problem?

**Review by alexec — CHANGES_REQUESTED** [review]

File: test/e2e/testdata/http-outputs.yaml (hunk 2 above)
Comment (book987) [reply test/e2e/testdata/http-outputs.yaml]: deleted

**Comment by book987** [comment]
Hi, could you please take another look @alexec @sarabala1979

**Comment by alexec** [comment]
I've requested @sarabala1979 thoughts on this.

Bala - can you please add to you TODO list?

File: workflow/executor/agent.go [hunk 4]
```diff
@@ -133,7 +134,7 @@ func (ae *AgentExecutor) executeHTTPTemplate(ctx context.Context, tmpl wfv1.Temp
...
+	outputs.Result = pointer.StringPtr(response)
```
Comment (sarabala1979) [inline workflow/executor/agent.go:137]: This is breaking change. it may break existing workflows. Please revert it. We did as a parameter so downline step can refer to it. But now it is too late to change.

**Review by sarabala1979 — CHANGES_REQUESTED** [review]
This is breaking change. it may break existing workflows. Please revert it. We did as a parameter so the downline step can refer to it. But now it is too late to change.

File: workflow/executor/agent.go (hunk 4 above)
Comment (book987) [reply workflow/executor/agent.go:137]: I've try access HTTP template's output with steps and getting same error `Internal Server Error: templates.main.steps failed to resolve {{steps.good.outputs.parameters.result}}`, in v3.2.3 and v3.2.4. So looks like no one can use it's output in downline step currently. So this isn't a breaking change I think.

I rarely use steps, if I tested it in wrong way pls forgive me.

**Review by alexec — CHANGES_REQUESTED** [review]
LGTM. But need sync with master.

File: workflow/executor/agent.go (hunk 4 above)
Comment (sarabala1979) [reply workflow/executor/agent.go:137]: got it

**Review by sarabala1979 — APPROVED** [review]
LGMT

**Comment by book987** [comment]
> LGTM. But need sync with master.

sync completed.

**Comment by simster7** [comment]
@alexec Looks like it needs another review from you

**Review by simster7 — APPROVED** [review]

**Review by alexec — APPROVED** [review]
