### PR TITLE
fix: Return correct http error codes. Fixes #9237

### LINKED ISSUE #9237: Workflow API response failure due to RBAC restrictions
## Summary

If we are not authorized for a particular operation according to RBAC, the Workflow API will return an HTTP status 500 error.
Not authorized, we expect the API to return a HTTP status 4xx error such as 403.

Server administrators often monitor the API for HTTP status errors at 5xx.
However, since an unauthorized request is normal for the server, it is a false positive and turns into "The Boy Who Cried Wolf".

version: **v3.3.8**

## Diagnostics

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ui-readonly
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workfloweventbindings
  - workflowtemplates
  - cronworkflows
  - cronworkflows/finalizers
  - clusterworkflowtemplates
  verbs:
  - get
  - list
  - watch
```

For example, if the above privileges are assigned to a service account, the user using that service account will not be able to **retry** the workflow.

When the user performs a **retry** operation from UI, the following API was called:

`PUT /api/v1/workflows/namespace/workflow-name/retry`

The response to this would be a HTTP status of 500.

In this case, the error log for argocli is as follows.

```
time="2022-07-27T00:04:43.918Z" level=error msg="finished unary call with code Unknown" error="pods \"sample-workflow-pod-name\" is forbidden: User \"system:serviceaccount:argo:ui-readonly\" cannot delete resource \"pods\" in API group \"\" in the namespace \"sample-namespace\"" grpc.code=Unknown grpc.method=RetryWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2022-07-27T00:04:43Z" grpc.time_ms=49.319 span.kind=server system=grpc
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by isubasinghe**
Signed-off-by: Isitha Subasinghe <isitha@pipekit.io>

Fixes #9237

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [x] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [x] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

File: server/apiserver/argoserver.go [hunk 1]
```diff
@@ -314,6 +316,15 @@ func (as *argoServer) newGRPCServer(instanceIDService instanceid.Service, offloa
 	return grpcServer
 }
 
+func customHandler(ctx context.Context, mux *runtime.ServeMux, marshaller runtime.Marshaler, w http.ResponseWriter, r *http.Request, err error) {
+	_, ok := status.FromError(err)
+	if !ok {
+		// InvalidArgument is translated to a BadRequest
```
Comment (sarabala1979) [inline server/apiserver/argoserver.go:322]: @isubasinghe this will convert all errors into badrequest. we need to send this error if any spec validation error.

Comment (isubasinghe) [reply server/apiserver/argoserver.go:322]: @sarabala1979 Do you know anyway to determine if an error is a spec validation error? I wasn't able to find how, hence I felt forced to go with this approach. The limitation is from the fact that some errors are returned by fmt.Errorf, which makes it impossible to check against since they are just strings. 

I think personally the fix is to create a new `ServerError` struct and have it implement error. This way I think we can use reflection to check the error. This would be a pretty big change (I'd argue a breaking change) and require me to change every server type (info, workflow ...)

Comment (isubasinghe) [reply server/apiserver/argoserver.go:322]: Do you think the `ServerError` path is the way to go ?

**Review by alexec — COMMENTED** [review]
This does not look like the correct approach to me. There is an error translator somewhere you could take a look at.

**Comment by sarabala1979** [comment]
@alexec Can you provide more information to @isubasinghe, So, he can refactor?

**Comment by isubasinghe** [comment]
@sarabala1979 this is a refactor from the old one which Alex commented on. Every error goes through ToStatusError. 
Here I try to extract an ArgoError and map it into a grpc error, failing that I try to extract a k8s error and map that into a grpc error. 

In a general sense, the most relevant file here is just: https://github.com/argoproj/argo-workflows/pull/9916/files#diff-6ec3cdfd853ed9734ca0ba5e09bfc02c4a2ff21478a1d264ce3e4277e40f4c69

The others are just calling this.

**Comment by caelan-io** [comment]
What are your thoughts @alexec ? Can we merge to close #9237?

File: server/utils/errors.go [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+
+	"google.golang.org/grpc/codes"
+	"google.golang.org/grpc/status"
+
+	argoerrors "github.com/argoproj/argo-workflows/v3/errors"
+
+	apierr "k8s.io/apimachinery/pkg/api/errors"
+)
+
+func ArgoToStatusError(err argoerrors.ArgoError) error {
```
Comment (JPZ13) [inline server/utils/errors.go:15]: nit: Can you add a comment here given it's an exported function?

**Review by JPZ13 — APPROVED** [review]
Code looks great. Running well when tested locally. One quick nit, can you change the PR title to be something like `fix: Return correct http error codes. Fixes #9237` or something similar?

**Review by alexec — CHANGES_REQUESTED** [review]
This looks great. I think maybe a couple more tests?

File: server/utils/errors.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+
+	apierr "k8s.io/apimachinery/pkg/api/errors"
+)
+
+// REFER TO https://github.com/grpc-ecosystem/grpc-gateway/blob/8952e38d5addd28308e29c272c696a578aa8ace8/runtime/errors.go#L36 in order to understand
+// how the mapping behaviours for both HTTPToStatusError and ArgoToStatusError were chosen.
+
+// Converts an ArgoError into a grpc status error.
+// It defaults to a codes.Unknown if an appropriate error was not able to be found
+func ArgoToStatusError(err argoerrors.ArgoError) error {
```
Comment (alexec) [inline server/utils/errors.go:20]: Test?

File: server/utils/errors.go [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+	case argoerrors.CodeInternal:
+		return status.Error(codes.Internal, err.Error())
+	default:
+		return status.Error(codes.Unknown, err.Error())
+	}
+}
+
+// Return a new status error and true else nil and false
+// is meant to be as close to the opposite of grpc gateways status -> http error code converter
+// exceptions made where one to one mappings were not available
```
Comment (alexec) [inline server/utils/errors.go:43]: Test? Can be private?

File: server/utils/errors.go [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+	return nil, false
+}
+
+// Try to see if we can obtain a http
+// error code from the k8s layer or the ArgoError layer
+// if not we resort to a default value of `code`
+// NOTE: errors passed of the type from grpc's status are not converted
+// and returned as is. This is to keep user code as dumb as possible.
+// The assumption here is that the error in the lowest layer of the error stack is the most relevant error.
+func ToStatusError(err error, code codes.Code) error {
```
Comment (alexec) [inline server/utils/errors.go:99]: More tests?

File: server/utils/errors.go [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+	if err == nil {
+		return nil
+	}
+	argoerr, typeOkay := err.(argoerrors.ArgoError)
```
Comment (alexec) [inline server/utils/errors.go:103]: Could use `errors.As()`?

File: server/utils/errors.go [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+	if typeOkay {
+		return ArgoToStatusError(argoerr)
+	}
+	// allow callers to call ToStatusError on the same processed error
+	_, alreadyConverted := status.FromError(err)
```
Comment (alexec) [inline server/utils/errors.go:108]: Could probably move this up?

File: server/utils/errors.go [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+	apierr "k8s.io/apimachinery/pkg/api/errors"
+)
+
+// REFER TO https://github.com/grpc-ecosystem/grpc-gateway/blob/8952e38d5addd28308e29c272c696a578aa8ace8/runtime/errors.go#L36 in order to understand
+// how the mapping behaviours for both HTTPToStatusError and ArgoToStatusError were chosen.
+
+// Converts an ArgoError into a grpc status error.
+// It defaults to a codes.Unknown if an appropriate error was not able to be found
+func ArgoToStatusError(err argoerrors.ArgoError) error {
+	switch err.Code() {
```
Comment (alexec) [inline server/utils/errors.go:21]: Minor, but you could use a `map` to do a look up here.

File: server/utils/errors.go [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+// Return a new status error and true else nil and false
+// is meant to be as close to the opposite of grpc gateways status -> http error code converter
+// exceptions made where one to one mappings were not available
+func httpToStatusError(code int, msg string) (error, bool) {
+	// handle success & information  codes in one go
+	if code < 300 {
+		return status.Error(codes.OK, msg), true
+	}
+
+	errorMaps := map[int]codes.Code{
```
Comment (sarabala1979) [inline server/utils/errors.go:24]: @isubasinghe Can you move to constants instead of initializing every call?

Comment (isubasinghe) [reply server/utils/errors.go]: done

**Review by sarabala1979 — APPROVED** [review]
