### PR TITLE
fix!: Adjust parameter value overriding. Fixes #14426

### LINKED ISSUE #14426: Inconsistent behavior for Workflow Arguments vs Template inputs to prioritise `Value` over `ConfigMapKeyRef`
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Same issue as #10182 but for `Workflow.Spec.Arguments` (and referenced via `{{workflow.parameters.param-name}}`) which are dealt with in a different code path here: https://github.com/argoproj/argo-workflows/blob/bd13b1c92bdb6cbc60c71f7664c4472e6fdc1d3f/workflow/controller/operator.go#L646-L659

Which means passing a `value` to an argument that uses a `ValueFrom.ConfigMapKeyRef` does nothing, when it should prioritise the `value` to match template input behaviour. A workaround is moving the config map input to a template to get the fixed behaviour from #10182.

### Version(s)

v3.6.5

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-properties
  namespace: argo
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  message: "message from config map"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-template-echo
  namespace: argo
spec:
  entrypoint: echo
  arguments:
    parameters:
      - name: message
        valueFrom:
          configMapKeyRef:
            name: config-properties
            key: message
  templates:
    - name: echo
      container:
        image: busybox
        command: [echo]
        args: ["{{workflow.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-parameter-overwrite-
  namespace: argo
spec:
  entrypoint: echo
  arguments:
    parameters:
      - name: message
        value: "configmap argument overwrite with argument"
  workflowTemplateRef:
    name: wf-template-echo
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
time="2025-04-24T14:04:56.898Z" level=info msg="Processing workflow" Phase= ResourceVersion=864971 namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.906Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.906Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.906Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.906Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.906Z" level=info msg="Pod node wf-parameter-overwrite-8z8bv initialized Pending" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.907Z" level=warning msg="couldn't get boundaryTemplate through nodeName wf-parameter-overwrite-8z8bv" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.916Z" level=info msg="Created pod: wf-parameter-overwrite-8z8bv (wf-parameter-overwrite-8z8bv)" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.916Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.916Z" level=info msg=reconcileAgentPod namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56Z" level=info msg="add pod event" pod=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.922Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=864975 workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.922Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=864975 namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.922Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.922Z" level=info msg="node unchanged" namespace=argo nodeID=wf-parameter-overwrite-8z8bv workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.922Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56.922Z" level=info msg=reconcileAgentPod namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56Z" level=info msg="update pod event" pod=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:56Z" level=info msg="update pod event" pod=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:04:58Z" level=info msg="update pod event" pod=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:00Z" level=info msg="update pod event" pod=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:01Z" level=info msg="update pod event" pod=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:02Z" level=info msg="update pod event" pod=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:03Z" level=info msg="update pod event" pod=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.933Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=864975 namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.939Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.940Z" level=info msg="task-result changed" namespace=argo nodeID=wf-parameter-overwrite-8z8bv workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.941Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=wf-parameter-overwrite-8z8bv old.message= old.phase=Pending old.progress=0/1 workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.943Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.943Z" level=info msg=reconcileAgentPod namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.943Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.944Z" level=info msg="Marking workflow completed" namespace=argo workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06.959Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=865012 workflow=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06Z" level=info msg="queueing pod for cleanup" action=labelPodCompleted namespace=argo podName=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:06Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/wf-parameter-overwrite-8z8bv/labelPodCompleted namespace=argo podName=wf-parameter-overwrite-8z8bv
time="2025-04-24T14:05:07Z" level=info msg="delete pod event" pod=wf-parameter-overwrite-8z8bv
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
time="2025-04-24T14:05:01.152Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2025-04-24T14:05:01.152Z" level=info msg="No output parameters"
time="2025-04-24T14:05:01.152Z" level=info msg="No output artifacts"
time="2025-04-24T14:05:01.154Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: wf-parameter-overwrite-8z8bv/wf-parameter-overwrite-8z8bv/main.log"
time="2025-04-24T14:05:01.154Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2025-04-24T14:05:01.154Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=wf-parameter-overwrite-8z8bv/wf-parameter-overwrite-8z8bv/main.log path=/tmp/argo/outputs/logs/main.log
time="2025-04-24T14:05:01.178Z" level=info msg="Save artifact" artifactName=main-logs duration=23.951542ms error="<nil>" key=wf-parameter-overwrite-8z8bv/wf-parameter-overwrite-8z8bv/main.log
time="2025-04-24T14:05:01.178Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2025-04-24T14:05:01.178Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2025-04-24T14:05:01.208Z" level=info msg="Alloc=11599 TotalAlloc=17022 Sys=23381 NumGC=4 Goroutines=10"
```

### PR DESCRIPTION
**Pull request by nicdard**
Fixes #14426 

### Motivation

See the related issue description. It fixes the Inconsistent behavior for Workflow Arguments vs Template inputs to prioritise Value over ConfigMapKeyRef problem, and more in general the way the merge over the parameters containing values is performed.

### Modifications

* Modified the spec merge functionality `JoinWorkflowSpec` inside `workflow/util/merge.go`:
   * Arguments.Parameters has patch strategy `merge`
   * However when we merge the `Value`, `ValueFrom`, `Default` can conflict if they come from Wf, Wft or DefaultWf
   * The change aims of removing this ambiguity, so that the resulting `execWf` uses the proper value given the priority Wf -> Wft -> DefaultWf.
* No UI changes.

### Verification

Add unit tests to verify the changes. Tested with the given reproducible example from the issue and verified:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-properties
  namespace: argo
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  message: "message from config map"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-template-echo
  namespace: argo
spec:
  entrypoint: echo
  arguments:
    parameters:
      - name: message
        valueFrom:
          configMapKeyRef:
            name: config-properties
            key: message
  templates:
    - name: echo
      container:
        image: busybox
        command: [echo]
        args: ["{{workflow.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-parameter-overwrite-
  namespace: argo
spec:
  entrypoint: echo
  arguments:
    parameters:
      - name: message
        value: "configmap argument overwrite with argument"
  workflowTemplateRef:
    name: wf-template-echo
```

### CODE REVIEW

File: workflow/util/merge.go [hunk 1]
```diff
@@ -97,9 +97,36 @@ func JoinWorkflowSpec(wfSpec, wftSpec, wfDefaultSpec *wfv1.WorkflowSpec) (*wfv1.
 	if wfSpec.Suspend != targetWf.Spec.Suspend {
 		targetWf.Spec.Suspend = wfSpec.Suspend
 	}
+	// The value of an argument should respect the priority order of the merge.
+	// However, if Value, ValueFrom and Default are set in different places,
+	// i.e. the Workflow, WorflowTemplate and WorkflowDefault, we should only keep the one with the greatest priority.
+	wfParamsMap := parametersToMapByName(wfSpec)
+	wftParamsMap := parametersToMapByName(wfSpec)
```
Comment (MasonM) [inline workflow/util/merge.go:104]: I think you meant this (though it's kinda a moot point):
```suggestion
	wftParamsMap := parametersToMapByName(wftSpec)
```

**Review by MasonM — COMMENTED** [review]
Thanks @nicdard! This does fix a special case of #14426, but the root issue here isn't in the merge logic, it's in the operator logic. I left a comment in that issue with an example `Workflow` that reproduces the inconsistency without using a `WorkflowTemplate`, which means this merge logic isn't involved: https://github.com/argoproj/argo-workflows/issues/14426#issuecomment-2870224091

I ran that example in your branch and unfortunately I still see the inconsistency. I suspect the only real fix here is changing the operator logic, like this: https://github.com/argoproj/argo-workflows/compare/main...MasonM:argo-workflows:fix-14462

but that would probably constitute a backwards-incompatible change, which makes me nervous. I don't know offhand if there's anybody relying on the current inconsistent behavior, but @Joibel might know. My gut feeling is it's worth breaking BC over, as long as we clearly communicate it.

File: workflow/util/merge.go (hunk 1 above)
Comment (nicdard) [reply workflow/util/merge.go:104]: yes sorry!

**Comment by nicdard** [comment]
> Thanks @nicdard! This does fix a special case of #14426, but the root issue here isn't in the merge logic, it's in the operator logic. I left a comment in that issue with an example `Workflow` that reproduces the inconsistency without using a `WorkflowTemplate`, which means this merge logic isn't involved: [#14426 (comment)](https://github.com/argoproj/argo-workflows/issues/14426#issuecomment-2870224091)
> 
> I ran that example in your branch and unfortunately I still see the inconsistency. I suspect the only real fix here is changing the operator logic, like this: [main...MasonM:argo-workflows:fix-14462](https://github.com/argoproj/argo-workflows/compare/main...MasonM:argo-workflows:fix-14462)
> 
> but that would probably constitute a backwards-incompatible change, which makes me nervous. I don't know offhand if there's anybody relying on the current inconsistent behavior, but @Joibel might know. My gut feeling is it's worth breaking BC over, as long as we clearly communicate it.

thank you for the extended answer and for the example!

**Comment by nicdard** [comment]
@MasonM as an example of the problem mentioned above:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-properties
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  message: "message from config map"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-template-echo
spec:
  entrypoint: echo
  arguments:
    parameters:
      - name: message
        value: "message from workflow template"
  templates:
    - name: echo
      container:
        image: busybox
        command: [echo]
        args: ["{{workflow.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-parameter-overwrite-
spec:
  entrypoint: echo
  arguments:
    parameters:
      - name: message
        valueFrom:
          configMapKeyRef:
            name: config-properties
            key: message
  workflowTemplateRef:
    name: wf-template-echo
```

If I understand properly, this should result in printing the `message from config map` message, which does not get fixed by re-ordering the operator logic. I am adding the operator logic fix tho, as your example shows that only changing merge does not really work.

File: workflow/controller/operator_workflow_template_ref_test.go [hunk 2]
```diff
@@ -216,6 +216,114 @@ func TestWorkflowTemplateRefParamMerge(t *testing.T) {
...
+      - name: message
+        valueFrom:
+          configMapKeyRef:
+            name: config-properties
+            key: message
+  workflowTemplateRef:
+    name: wf-template-echo
+`
+
+func TestWorkflowTemplateRefValueParamOverwrite(t *testing.T) {
```
Comment (nicdard) [inline workflow/controller/operator_workflow_template_ref_test.go:312]: @MasonM this test is showing that the merge logic is not correct, let me know what you think

I found a way to use the ConfigMap, but I am not sure it's needed (I was looking at the tests in `operator_concurrency_test.go` where a`ConfigMap` is used). As it is written, the test shows already that the overwrite is working, but when trying to get the value from it, since the confimap informer is missing, the value is not extracted. The code needed to not fail has been added in a separate commit

Comment (nicdard) [reply workflow/controller/operator_workflow_template_ref_test.go:324]: here is the code for the ConfigMap informer to run: https://github.com/argoproj/argo-workflows/pull/14462/commits/8a5782f63cb9fe2f0b2a0e4bb44e252c63d27ae2

**Comment by nicdard** [comment]
> @nicdard, @sarabala1979 , and I met on May 13th to discuss this, and I agreed to update the PR with the result of that converstation. Sorry for the delay!
> 
> My concern is the merge logic would constitute a fairly significant backwards-incompatible change, since the [the docs](https://argo-workflows.readthedocs.io/en/latest/workflow-templates/#create-workflow-from-workflowtemplate-spec) say "if you pass the arguments to created Workflow, it will be merged with workflow template arguments." So using the example in the PR description, the result of the merge would look like:
> 
> ```yaml
>     parameters:
>       - name: message
>         value: "configmap argument overwrite with argument"
>       - name: message
>         valueFrom:
>           configMapKeyRef:
>             name: config-properties
>             key: message
> ```
> 
> This PR changes that behavior so the `valueFrom` is deleted, which goes against the documentation. But @sarabala1979 pointed out that the new behavior is more intuitive, which I agree with, and he didn't think breaking compatibility was a major concern here. So, I'm fine with this, but we should probably defer to @Joibel. Assuming everyone is okay with breaking compatibility here, I think we'll need to update the documentation and the [upgrading guide](https://argo-workflows.readthedocs.io/en/latest/upgrading/) to make it clear. I did mention in the meeting I was hoping we could simplify the merge logic using something like [retainKeys](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-strategic-merge-patch-to-update-a-deployment-using-the-retainkeys-strategy), but after some experimentation, I couldn't figure out an easy way of doing so.
> 
> Also, I think it's probably worth splitting off the `{{workflow.parameters.param-name}}` change to a separate PR, partly because it's a much simpler change, and partly because it isn't a significant breaking change, since the [relevant docs](https://argo-workflows.readthedocs.io/en/latest/variables/) don't say anything about the precedence of `value`/`valueFrom`. In other words, it it could be considered "undefined behavior" right now.
> 
> In any case, thanks @nicdard for your persistence and great work on this!

Thank you @MasonM this is great recap!
Just one further note: @sarabala1979 also agreed that it would make sense to push both changes in one, even if the latter could be considered undefined behavior, it would still break some clients if they rely on the current precedence logic.

**Comment by isubasinghe** [comment]
@nicdard can you please rebase this?

**Comment by caelan-io** [comment]
@nicdard - hope you're well! simply a tag to ask for the rebase and then we'll get this merged and released 🙌

**Comment by nicdard** [comment]
> @nicdard - hope you're well! simply a tag to ask for the rebase and then we'll get this merged and released 🙌

Cool taking a look now

**Comment by nicdard** [comment]
@caelan-io I just rebased the branch now :)

**Comment by caelan-io** [comment]
Thank you! @isubasinghe will review and merge.

**Review by isubasinghe — APPROVED** [review]
