### PR TITLE
fix(test): windows tests fixes. Fixes #11994

### LINKED ISSUE #11994: Windows tests not run automatically
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

While working on reproducing #11810 and contributing the fix in #11993 I noticed a lot of failing tests for windows. Especially also the bug in question would've triggered a failed run when CI would run windows tests automatically. 
However it seems that this is not done currently. 

Running the tests on a windows machine, I get quite a lot of errors, see attached [logs.txt](https://github.com/argoproj/argo-workflows/files/12892852/logs.txt).

What is the reason for not running them automatically? 
Was it always like this or did that change recently? 

What can be done (besides providing windows fixes for those failing tests) to improve this in the future?

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
not applicable
```

### Logs from the workflow controller

```text
not applicable
```

### Logs from in your workflow's wait container

```text
not applicable
```

### PR DESCRIPTION
**Pull request by mweibel**
Fixes #11994 (or rather adjusts a few things fixed in #12011)

### Motivation

Adjusts changes based on review feedback.

### CODE REVIEW

File: cmd/argo/lint/formatter_pretty_test.go [hunk 1]
```diff
@@ -1,3 +1,4 @@
+// disabled on windows because colorized output is not supported - go-color will return just the text without colors.
 //go:build !windows
```
Comment (agilgur5) [inline cmd/argo/lint/formatter_pretty_test.go:2]: Could you change these to a `t.Skip` in `TestMain` instead (as mentioned in https://github.com/argoproj/argo-workflows/pull/12011#discussion_r1369420886)?

File: cmd/argo/lint/formatter_pretty_test.go [hunk 2]
```diff
@@ -1,3 +1,4 @@
+// disabled on windows because colorized output is not supported - go-color will return just the text without colors.
```
Comment (agilgur5) [inline cmd/argo/lint/formatter_pretty_test.go:1]: I might be mistaken, but I thought this file tests the output messages themselves too, which include colors. the output message part would still be relevant, no?

**Review by agilgur5 — COMMENTED** [review]
Thanks for following up on [my review](https://github.com/argoproj/argo-workflows/pull/12011#pullrequestreview-1685827398)!

small comments in-line -- you might be working on those already since this is a draft

File: cmd/argo/lint/formatter_pretty_test.go (hunk 2 above)
Comment (mweibel) [reply cmd/argo/lint/formatter_pretty_test.go]: fixed, thanks for bringing this to my attention again :)

**Comment by mweibel** [comment]
it took a while - sorry about the delay. I think I incorporated the bug fixes and also noticed a few of the tests I skipped last time seem to work now. Let's see if it works in CI, too.

File: pkg/apis/workflow/v1alpha1/workflow_types_test.go [hunk 3]
```diff
@@ -255,53 +255,60 @@ func TestArtifact_ValidatePath(t *testing.T) {
...
+		assert.Equal(t, filepath.Join("..", ".."), a3.Path)
 
 		a4 := Artifact{Name: "a4", Path: "../etc/passwd"}
 		err = a4.CleanPath()
 		require.NoError(t, err)
-		assert.Equal(t, "../etc/passwd", a4.Path)
+		assert.Equal(t, filepath.Join("..", "etc", "passwd"), a4.Path)
 	})
 
+	ensureRootPathSeparator := func(p string) string {
```
Comment (agilgur5) [inline pkg/apis/workflow/v1alpha1/workflow_types_test.go:266]: This probably makes more sense to convert to a plain named function as opposed to a variable assigned to an anonymous function since it doesn't use any scope

Comment (mweibel) [reply pkg/apis/workflow/v1alpha1/workflow_types_test.go:266]: I don't mind to adjust it, however a Go anon function is not really the same as UI anon functions I'd say. I simply opted for an anon function because it's only relevant to this test and there's no need to pollute the package namespace with that function, otherwise. 

but as said, I don't mind, happy to adjust it.

Comment (mweibel) [reply pkg/apis/workflow/v1alpha1/workflow_types_test.go]: adjusted.

**Review by agilgur5 — APPROVED** [review]
Thanks for making the adjustments and handling more tests, LGTM

**Comment by mweibel** [comment]
thanks for retest - it passed 👍

**Comment by agilgur5** [comment]
Right there were some flakey tests here (and in other PRs) that I wanted to make note of for an issue, had been meaning to come back to this for that 😅
