### PR TITLE
fix: Support `OOMKilled` with container-set. Fixes #10063

### LINKED ISSUE #10063: Pod hangs when container in ContainerSet is OOM Killed
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have a containerSet with 2 containers. The first container runs a script that results in it being OOM Killed. I expect the Pod and Workflow to fail at that point, but they just hang in the "Running" state until they reach their timeoutSeconds deadline.

I found this related issue https://github.com/argoproj/argo-workflows/issues/8680 but I am on 3.4.3 and still running into it.

I am using the emissary executor

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: example
  namespace: argo
  labels:
spec:
  automountServiceAccountToken: false
  dnsConfig:
    nameservers:
      - 10.33.0.2 # AWS VPC Default
      - 1.1.1.1 # CloudFlare
      - 8.8.8.8 # Google
  executor:
    serviceAccountName: "argo-workflow"
  templates:
    - name: entrypoint
      # max workflow duration https://argoproj.github.io/argo-workflows/fields/#workflowspec
      retryStrategy: # https://argoproj.github.io/argo-workflows/retries/
        limit: "3"
        retryPolicy: "OnTransientError"
      metadata:
      containerSet:
        containers:
          - name: one
            imagePullPolicy: Always
            resources:
              requests:
                memory: "50Mi"
                cpu: "50m"
              limits:
                memory: "50Mi"
            image: "ubuntu"
            command:
              - bash
              - '-c'
            args:
              - |
                /bin/bash <<'EOF'
                echo "hello one"
                apt update -y
                apt install stress -y
                echo 'stress --vm 1 --vm-bytes 512M --vm-hang 100' > abc.sh
                bash abc.sh
                EOF
          - name: two # if changing, update 'eks.amazonaws.com/skip-containers'
            imagePullPolicy: Always
            resources:
              requests:
                memory: "150Mi"
                cpu: "50m"
              limits:
                memory: "250Mi"
            image: "ubuntu"
            command:
              - bash
              - '-c'
            args:
              - |
                /bin/bash <<'EOF'
                echo "hello world"
                EOF
            dependencies:
              - one
  entrypoint: entrypoint
```
```


### Logs from the workflow controller

n/a

### Logs from in your workflow's wait container

time="2022-11-18T17:07:11.708Z" level=info msg="Starting Workflow Executor" version=v3.4.3
time="2022-11-18T17:07:11.711Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-11-18T17:07:11.711Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=postman-test-fxd4q-entrypoint-1784721547 template="templatehere"
time="2022-11-18T17:07:11.712Z" level=info msg="Starting deadline monitor"
```

### PR DESCRIPTION
**Pull request by alexec**
Fixes #10063

### CODE REVIEW

File: cmd/argoexec/commands/emissary.go [hunk 1]
```diff
@@ -70,24 +70,38 @@ func NewEmissaryCommand() *cobra.Command {
...
-							exitCode, err := strconv.Atoi(string(data))
-							if err != nil {
-								return fmt.Errorf("failed to read exit-code of dependency %q: %w", y, err)
-							}
-							if exitCode != 0 {
-								return fmt.Errorf("dependency %q exited with non-zero code: %d", y, exitCode)
+							select {
+							// If we receive a terminated or killed signal, we should exit immediately.
+							case s := <-signals:
+								if s == osspecific.Term || s == os.Kill {
```
Comment (alexec) [inline cmd/argoexec/commands/emissary.go:87]: We must ignore any signal that is not SIGKILL or SIGTERM. Otherwise we would exit if we got SIGURG (for example.)

File: workflow/executor/os-specific/signal_windows.go [hunk 2]
```diff
@@ -7,6 +7,10 @@ import (
 	"github.com/argoproj/argo-workflows/v3/util/errors"
 )
 
+var (
+	Term = os.Interrupt
```
Comment (alexec) [inline workflow/executor/os-specific/signal_windows.go:11]: There is to `os.Term` because Windows does not have that. We fake it.

**Comment by alexec** [comment]
`timed out waiting for the condition on workflows/sequence-ggd4h`

File: cmd/argoexec/commands/emissary.go [hunk 3]
```diff
@@ -70,24 +70,44 @@ func NewEmissaryCommand() *cobra.Command {
...
+								if os.IsNotExist(err) {
+									time.Sleep(time.Second)
+									continue
+								}
+								exitCode, err := strconv.Atoi(string(data))
+								if err != nil {
+									return fmt.Errorf("failed to read exit-code of dependency %q: %w", y, err)
+								}
+								if exitCode != 0 {
+									return fmt.Errorf("dependency %q exited with non-zero code: %d", y, exitCode)
```
Comment (terrytangyuan) [inline cmd/argoexec/commands/emissary.go:107]: Need a rebase here

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Can you resolve conflicts?

**Review by isubasinghe — APPROVED** [review]
Tested manually myself, verified to fix #10063. 
Approved

**Comment by caelan-io** [comment]
@alexec Hi Alex! I'm not sure if you saw, but @terrytangyuan posted about difficulty merging this into the patch release branch. ([see notes below from the cherry-pick release ticket](https://github.com/argoproj/argo-workflows/issues/11648))

Are you able to look into this and submit a PR to [the v3.4.11 release branch](https://github.com/argoproj/argo-workflows/tree/release-3.4.11)? 

Thanks again for pushing this fix! Since users had wanted it in 3.4.10, we wanted to see if it's possible to squeeze into 3.4.11.

> These cannot be cherry-picked since the v3.4.10 release branch diverges from master branch too much and have non-trivial conflicts to resolve. If you'd like to get them into this release, please submit a PR to the release branch by the end of next Tuesday. https://github.com/argoproj/argo-workflows/tree/release-3.4.10
> 
> * [x]  [143d0f5](https://github.com/argoproj/argo-workflows/commit/143d0f504c9382976b5a25a36b108b7f5e24ab37) fix: Fixed memoization is unchecked after mutex synchronization. @shmruin @jaen
> * [ ]  [61a4ac4](https://github.com/argoproj/argo-workflows/commit/61a4ac45cde5fca2788c83cba0383ea3c1cb868d) fix: Ignore failed read of exit code. @alexec
> * [ ]  [b26f5b8](https://github.com/argoproj/argo-workflows/commit/b26f5b80ef4a3774ea85dcf6dfae95bac2253b47) fix: Support OOMKilled with container-set. @alexec
> * [ ]  [1f6b19f](https://github.com/argoproj/argo-workflows/commit/1f6b19f3ab9f8758684bb6c93289d57c5dd1d963) fix: add guard against NodeStatus. @isubasinghe
> * [ ]  [105031b](https://github.com/argoproj/argo-workflows/commit/105031b88d45330a74777c6cd7410742827c3fe7) fix: always fail dag when shutdown is enabled. @isubasinghe
