### PR TITLE
fix(9656): stores all states except workflows, fixes #9656

### LINKED ISSUE #9656: Archived Workflows UI error: `Failed to execute 'setItem' on 'Storage'`
### Pre-requisites

- [X] I have double-checked my configuration
- [ ] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When opening the tab "Archived Workflows" in the web UI I got the following error:

`Failed to execute 'setItem' on 'Storage': Setting the value of 'ArchiveListOptions/options' exceeded the quota.`

Screenshot 2022-09-21 at 16 59 32

In particular, I am using a Postgres storage backend to archive the workflows and I already tried to increase resources for both workflow-controller and argo-server.

Any idea?

### Version

v3.3.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Cannot view any workflow in the UI.
```

### PR DESCRIPTION
**Pull request by athityakumar**
Fixes #9656 

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [x] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.

The `workflows` key/value is no longer stored in browser's local storage for archived workflows page, after this change:

image

* [x] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

**Review by ltartarini — APPROVED** [review]

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 1]
```diff
@@ -181,8 +181,54 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
         return params;
     }
 
+    private filterStateObject(state: State, whitelistedStates: string[], blacklistedStates: string[]) {
+        const filteredState: State = {} as State;
```
Comment (juliev0) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:185]: Just curious: why do we need both a blacklist and a whitelist? Is there a use case for that?

It seems if you pass `{whitelistedStates:['pagination'], blacklistedStates:[]}`, that's equivalent to  `{whitelistedStates:[], blacklistedStates:[]}`, so I'm wondering if `whitelistedStates` is really needed? 

I see that if you pass `{whitelistedStates:['pagination'], blacklistedStates:[`pagination`]}` then that would not be equivalent to `{whitelistedStates:[], blacklistedStates:[`pagination`]}` but I'm not sure if anyone would ever need to call it that way ?

Do let me know if I'm missing something, though. Is there some industry standard that uses both whitelists and blacklists together like this?

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 2]
```diff
@@ -181,8 +181,54 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
...
+            filteredState.deep = state.deep;
+        }
+
+        return filteredState;
+    }
+
     private saveHistory() {
-        this.storage.setItem('options', this.state, {} as State);
+        this.storage.setItem('options', this.filterStateObject(this.state, [], ['workflows']), {} as State);
         const newNamespace = Utils.managedNamespace ? '' : this.state.namespace;
```
Comment (juliev0) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:232]: I do like the way you abstracted this into a function

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 3]
```diff
@@ -181,8 +181,54 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
...
+        }
+
+        if (whitelistedStates.includes('error') || !blacklistedStates.includes('error')) {
+            filteredState.error = state.error;
+        }
+
+        if (whitelistedStates.includes('deep') || !blacklistedStates.includes('deep')) {
+            filteredState.deep = state.deep;
+        }
+
```
Comment (juliev0) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:226]: I'm a little confused. Shouldn't `workflows` be in here? Otherwise, passing it in here seems to have no effect

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx (hunk 2 above)
Comment (juliev0) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:232]: Although, I'm concerned about the way the function lists out each member individually. There seems to be some maintenance risk there if somebody adds a new field to the struct, they need to update this function, right? Is there any way to do this in a way that doesn't require the maintenance?

Comment (juliev0) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:232]: Maybe we should consider simply clearing the value for `this.state.workflows` and perhaps this is a little over-designed? (I'm open, though)

Comment (athityakumar) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:203]: Agree regarding the maintenance risk if the state expands - I've added looping to blacklist the keys instead of statically going through each key via multiple if conditions

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx (hunk 1 above)
Comment (athityakumar) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx]: Makes sense, I've removed whitelistedStates as we don't currently need it rn - I was initially thinking of a more generic function that filters the states (with either whitelist to select few states, or blacklist to reject few states)

**Review by sarabala1979 — APPROVED** [review]

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 4]
```diff
@@ -181,8 +181,25 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
...
+        return filteredState;
+    }
+
+    private fetchBrowserStorageStateObject(state: State) {
+        return this.filterOutStateObject(state, ['workflows']);
+    }
+
     private saveHistory() {
-        this.storage.setItem('options', this.state, {} as State);
+        this.storage.setItem('options', this.fetchBrowserStorageStateObject(this.state), {} as State);
```
Comment (alexec) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:202]: I don't think this is the correct approach. A new objects should be constructed with only allowed fields.

Comment (alexec) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:202]:
```typescript
interface Options {
        namespace: string
        name: string
        namePrefix: string
        selectedPhases: string[]
        selectedLabels: string[]
        minStartedAt: Date
        maxStartedAt: Date
        pagination: Pagination
}

**Review by alexec — CHANGES_REQUESTED** [review]

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx (hunk 4 above)
Comment (athityakumar) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:202]: @alexec - But that'd mean we have to set the attributes manually for the new `options` variable, which is an `Options` interface object right? @juliev0 had raised a concern earlier that manually specifying attributes may have a maintenance overhead (if/when we add a new attribute to `State` interface, we'd also have to add it to the `Options` interface and in the function that converts the `State` object to `Options` object) - due to which I tried to automate the logic by taking `blacklistedStates` as an input.

Please lmk if `Options` is the preferred approach - I can update my PR with the same changes 😄

Comment (athityakumar) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:202]: Ping @alexec @sarabala1979 ^

**Comment by athityakumar** [comment]
@sarabala1979 @alexec - Any next steps on this PR? Please lmk if any action is required from my side 😄

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx (hunk 4 above)
Comment (alexec) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx:202]: I think it preferable to construct new object to write lots of code to black list fields. Less code to maintain I think.

**Review by alexec — APPROVED** [review]
