### PR TITLE
fix(executor): Fix docker "created" issue. Fixes #5252 

### LINKED ISSUE #5252: Wait container not actually waiting for main container
## Summary 

About 5% of the time we are seeing the wait container thinking that the main container has exited when it actually hasn't.

## Diagnostics

What Kubernetes provider are you using? 
AWS EKS

What version of Argo Workflows are you running? 
V3 rc2

We are using the docker executor.

As can be seen in this truncated log the wait container starts then stops within 1 second.
The main container starts at roughly the same time the wait container ends.
The main container takes 20s to run. All the while the wait container has already thought it exited.
Because the wait container doesn't actually wait for the main container to finish its work there are parameters and artifacts that have not yet been written to the appropriate files for the wait container to pickup.

```
Status:             Failed
Containers:
  wait:
    Container ID:  docker://09aef6fedeeb54341f46d9fa3111d7d75439d2fe61e1b5fbd699310a3193c3cd
...
    State:      Terminated
      Reason:   Error
      Message:  Error: No such container:path: 86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0:/path/to/some/file
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
      Exit Code:    1
      Started:      Mon, 01 Mar 2021 21:11:29 -0500
      Finished:     Mon, 01 Mar 2021 21:11:30 -0500
    Ready:          False
    Restart Count:  0
...
  main:
    Container ID:   docker://86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0
...
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 01 Mar 2021 21:11:30 -0500
      Finished:     Mon, 01 Mar 2021 21:11:50 -0500
    Ready:          False
    Restart Count:  0
```

Here are some logs from the wait and main container:
```
time="2021-03-02T02:11:29.905Z" level=info msg="Starting Workflow Executor" version="{latest+ea3439c.dirty 2021-02-16T17:36:06Z ea3439c91c9fd0c2a57db0d8a5ccf2b9fb2454a3 v3.0.0-rc2 dirty go1.15.7 gc linux/amd64}"
time="2021-03-02T02:11:29.908Z" level=info msg="Creating a docker executor"
...
time="2021-03-02T02:11:29.909Z" level=info msg="Starting deadline monitor"
time="2021-03-02T02:11:29.940Z" level=info msg="mapped container name \"main\" to container ID \"86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0\""
time="2021-03-02T02:11:29.940Z" level=info msg="mapped container name \"wait\" to container ID \"09aef6fedeeb54341f46d9fa3111d7d75439d2fe61e1b5fbd699310a3193c3cd\""
time="2021-03-02T02:11:29.940Z" level=info msg="mapped container name \"POD\" to container ID \"b5310c19614deb9c591c0ca80312f8985a0ce2459eba31ecfc60640ace7144ae\""
time="2021-03-02T02:11:29.940Z" level=info msg="docker wait 86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0"
time="2021-03-02T02:11:29.966Z" level=info msg="Main container completed"
time="2021-03-02T02:11:29.966Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-03-02T02:11:29.966Z" level=info msg="Capturing script exit code"
time="2021-03-02T02:11:30.153Z" level=info msg="Saving logs"
time="2021-03-02T02:11:30.153Z" level=info msg="[docker logs 86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0]"
```
According to the logs above the main container completed at 11:29.966. Kubernetes disagrees as seen above.

Here is some logging from inside our main container using python logging:
(note, the very first thing we do in the code is time.sleep(10) to make it more likely to hit this issue)
```
2021-03-02 02:11:40,764 - root - DEBUG - Sleeping for 10s completed
...
2021-03-02 02:11:40,774 - root - DEBUG - complete. Sleeping for 10s
2021-03-02 02:11:50,784 - root - DEBUG - exiting after sleep
```

The code in this container is very simple. There are no conditionals. It does a bit of math, writes to files, then exits normally.

Things we have checked:
- verified that the container IDs that have been used match those that were checked for by docker wait ....
- verified that running this main container manually and doing docker wait... works successfully (made a script and validated running between 1 and 40 concurrently)

Random pieces of information that may or may not be useful:
- We have only seen this issue inside a withSequence. We do a bunch of preprocessing with long running and short running containers and they all work fine. Only when we get to the withSequence steps of our workflow do we see these issues.
- We have verified at a different part of our workflow using a completely different container that actually takes a long time to run (in essence video encoding) that we often get truncated files written as artifacts. We believe that in that case the main container manages to write a little bit before the wait container grabs the files as artifacts. The above is a simpler case of this but we can provide some details of those cases as well. 
- We have seen these issues when using main containers that run python code (not inline), shell scripts (inline and not inline), and a direct executable (some c++ code).
- 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

File: workflow/executor/docker/docker.go [hunk 1]
```diff
@@ -215,13 +215,23 @@ func (d *DockerExecutor) syncContainerIDs(ctx context.Context, containerNames []
...
+				if len(parts) != 3 {
 					continue
 				}
-				containerName := parts[0]
-				containerID := parts[1]
+				status := strings.SplitN(parts[0], " ", 2)[0] // Created,Exited,Up,
+				containerName := parts[1]
+				containerID := parts[2]
 				if d.containers[containerName] == "" && containerID != "" {
+					if status == "Created" { // for "Created" we must check to see if it was an early (non-zero) exit
```
Comment (terrytangyuan) [inline workflow/executor/docker/docker.go:226]: Consider adding a test that exercises this case?

File: workflow/executor/docker/docker.go [hunk 2]
```diff
@@ -215,13 +215,23 @@ func (d *DockerExecutor) syncContainerIDs(ctx context.Context, containerNames []
...
+						output, err := common.RunCommand("docker", "inspect", containerID, "--format={{.State.ExitCode}}")
+						if err != nil {
+							return err
+						}
+						if strings.TrimSpace(string(output)) == "0" { // this remain "0" until it is not "Created" anymore
```
Comment (terrytangyuan) [inline workflow/executor/docker/docker.go:231]:
```suggestion
						if strings.TrimSpace(string(output)) == "0" { // this remains "0" until it is not "Created" anymore
```

File: workflow/executor/docker/docker.go (hunk 1 above)
Comment (alexec) [reply workflow/executor/docker/docker.go:226]: I think this only occurs under load. The test case is to run the stress tests!

Comment (terrytangyuan) [reply workflow/executor/docker/docker.go:226]: Sounds good. So looks like #5252 isn't a regression since this case was not covered in previous releases anyways, right?

Comment (alexec) [reply workflow/executor/docker/docker.go:226]: I'm not actually clear, but I'm prioritizing like a regression

**Review by simster7 — APPROVED** [review]
