### PR TITLE
fix: ensure labels is defined before key access. Fixes #11602

### LINKED ISSUE #11602: UI - label undefined for some workflows
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

UI accesses "label" field of non existing object causing it to crash. 

Will fix this myself. 

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by isubasinghe**
Verified manually, this is a simple change, just checks if a key existed before accessing it.

### CODE REVIEW

File: ui/src/app/workflows/components/workflows-row/workflows-row.tsx [hunk 1]
```diff
@@ -94,7 +94,8 @@ export class WorkflowsRow extends React.Component<WorkflowsRowProps, WorkflowRow
                         </div>
                         <div className='columns small-1'>{isArchivedWorkflow(wf) ? 'true' : 'false'}</div>
                         {(this.props.columns || []).map(column => {
-                            const value = wf.metadata?.labels[column.key];
+                            // best not to make any assumptions and wait until this data is filled
+                            const value = wf?.metadata?.labels ? wf.metadata.labels[column.key] : 'unknown';
```
Comment (agilgur5) [inline ui/src/app/workflows/components/workflows-row/workflows-row.tsx:98]:
```suggestion
                            const value = wf?.metadata?.labels?.[column.key] ?? 'unknown';
```

I believe this is the more conventional syntax nowadays with some slightly nicer properties

Though I think with `?.[column.key]`, `'unknown'` would technically no longer be required, so could also also do:

```suggestion
                            const value = wf?.metadata?.labels?.[column.key];
```

**Comment by isubasinghe** [comment]
Thanks @agilgur5, I went with the first option.

**Review by terrytangyuan — APPROVED** [review]
