### PR TITLE
fix: requeue workflow if expected variables are missing. Fixes #15513

### LINKED ISSUE #15513: Workflow with variables that are not present, yet are required should force a requeue.
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

This is an enhancement rather than a particular bug report. This is to treat the case where we might call evaluate on an expression where the input variables have not yet been populated. 

When this happens, the codebase should requeue the workflow , hoping that in the future that these variables will be populated. 

### Version(s)

:latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by isubasinghe**
Fixes #15513

### Motivation

This PR forces workflows to be requeue-ed when they are missing the variables referenced in their expression. 
This ensures we do not make invalid progress on expressions. 

### Modifications

* Modified `hasVarInEnv` to handle more cases (previously it couldn't handle `time.Time` due to being unable to flatten the struct thanks to its unexported fields which resulted in a panic). 
* Lex and check for variables, if there are missing we requeue
* added some code to allow for relaxations of strictness when placeholders are present. 

### Verification

Added some tests along with fuzzing. 
We fuzz using the old definition of expressionReplace to ensure semantic equivalence. 

### Documentation

N/A

## Summary by CodeRabbit

* **New Features**
  * Added strict template replacement mode (ReplaceStrict) and a requeue signal for unresolved references.

* **Improvements**
  * Stricter variable validation for templates with configurable strict prefixes.
  * Workflow: dependency and step reference resolution now defers or requeues on missing variables; nested multi-pass variable resolution improved.
  * Placeholder prefix standardized for internal placeholders.
  
* **Tests**
  * Added extensive unit, comparison and fuzz tests covering template replacement, expressions, and placeholder behavior.

### CODE REVIEW

**Comment by Joibel** [comment]
@coderabbitai review

File: util/template/expression_template.go [hunk 1]
```diff
@@ -43,7 +49,122 @@ func anyVarNotInEnv(expression string, env map[string]any) *string {
...
+	if n, ok := (*node).(*ast.MemberNode); ok {
+		path, ok := getMemberPath(n)
+		if ok {
+			if !v.seen[path] {
+				v.identifiers = append(v.identifiers, path)
+				v.seen[path] = true
+			}
+		}
+	}
+}
```
[the remark this answers is not in the document]
Comment (isubasinghe) [reply util/template/expression_template.go:107]: You are wrong here, this is intentional. Both variables foo and foo.bar are present.

File: util/template/template.go [hunk 2]
```diff
@@ -31,17 +34,46 @@ type impl struct {
...
+		// Match any string starting with one of the prefixes
+		regexStr := "^(" + strings.Join(patterns, "|") + ")"
+		strictRegex = regexp.MustCompile(regexStr)
+
+		expressionRegexStr := "^(" + strings.Join(expressionPatterns, "|") + ")$"
+		expressionStrictRegex = regexp.MustCompile(expressionRegexStr)
+	}
+
+	return t.replace(ctx, replaceMap, strictRegex, expressionStrictRegex, true)
+}
```
[the remark this answers is not in the document]
Comment (isubasinghe) [reply util/template/template.go]: Valid, this is a mistake.

File: util/template/replace.go [hunk 3]
```diff
@@ -4,8 +4,17 @@ import (
...
+	"strings"
 )
 
+func IsMissingVariableErr(err error) bool {
+	if err == nil {
+		return false
+	}
+	msg := err.Error()
+	return strings.Contains(msg, "failed to resolve") || strings.Contains(msg, "failed to evaluate expression:")
+}
```
[the remark this answers is not in the document]
Comment (isubasinghe) [reply util/template/replace.go:25]: Yeah I agree this should be narrowed.

File: workflow/controller/steps.go [hunk 4]
```diff
@@ -437,19 +442,29 @@ func (woc *wfOperationCtx) resolveReferences(ctx context.Context, stepGroup []wf
...
 		if err != nil {
 			return argoerrors.InternalWrapError(err)
 		}
-		newStepStr, err := template.Replace(ctx, string(stepBytes), woc.globalParams.Merge(scope.getParameters()), true)
+		newStepStr, err := template.ReplaceStrict(ctx, string(stepBytes), woc.globalParams.Merge(scope.getParameters()), []string{"steps", "tasks"})
 		if err != nil {
+			if template.IsMissingVariableErr(err) {
+				woc.requeue()
+				return ErrRequeue
+			}
```
[the remark this answers is not in the document]
Comment (isubasinghe) [reply workflow/controller/steps.go:462]: I think with making `IsMissingVariableErr` narrower, this issue is addressed right?

File: util/template/template.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (isubasinghe) [reply util/template/template.go]: I have resolved the issue, double check it.

**Comment by isubasinghe** [comment]
@coderabbitai review

File: workflow/controller/steps.go [hunk 5]
```diff
@@ -22,6 +22,8 @@ import (
 	"github.com/argoproj/argo-workflows/v3/workflow/templateresolution"
 )
 
+var ErrRequeue = errors.New("requeue")
```
Comment (eduardodbr) [inline workflow/controller/steps.go]: should this be defined alongside the remaining errors (like `ErrDeadlineExceeded` or `ErrParallelismReached`) in operator.go ?

File: util/template/expression_template.go [hunk 6]
```diff
@@ -43,7 +49,121 @@ func anyVarNotInEnv(expression string, env map[string]any) *string {
...
+
+func expressionReplaceCore(ctx context.Context, w io.Writer, expression string, env map[string]any, allowUnresolved bool) (int, error) {
+	shouldAllowFailure := false
+
+	maps.VisitMap(env, func(key string, value any) bool {
+		rv := reflect.Indirect(reflect.ValueOf(value))
+		if rv.Kind() == reflect.String {
+			placeholder := strings.HasPrefix(rv.String(), "__argo__internal__placeholder")
+			if placeholder {
```
Comment (eduardodbr) [inline util/template/expression_template.go]: wondering if we should use IsPlaceholder() here instead of searching for the string "__argo__internal__placeholder"

File: util/template/template.go [hunk 7]
```diff
@@ -31,17 +34,44 @@ type impl struct {
...
+	if !allowUnresolved {
+		regex = matchAllRegex
+	}
+	return t.replace(ctx, replaceMap, regex, regex, allowUnresolved)
+}
+
+func GetStrictRegex(strictPrefixes []string) *regexp.Regexp {
+	if len(strictPrefixes) == 0 {
+		return nil
+	}
```
Comment (eduardodbr) [inline util/template/template.go:63]: this is not used anywhere else so I think it can be unexported

File: util/template/expression_template.go [hunk 8]
```diff
@@ -43,7 +49,121 @@ func anyVarNotInEnv(expression string, env map[string]any) *string {
...
+		return nil, err
+	}
+	visitor := &identifierVisitor{
+		seen: make(map[string]bool),
+	}
+	ast.Walk(&tree.Node, visitor)
+	return visitor.identifiers, nil
+}
+
 func expressionReplace(ctx context.Context, w io.Writer, expression string, env map[string]any, allowUnresolved bool) (int, error) {
```
Comment (eduardodbr) [inline util/template/expression_template.go]: every occurrence of`expressionReplace` was replaced by either `expressionReplaceStrict` or `expressionReplaceCore`, so I guess it can be deleted

File: workflow/controller/operator.go [hunk 9]
```diff
@@ -213,7 +213,7 @@ func (woc *wfOperationCtx) operate(ctx context.Context) {
 	// ExecWF is a runtime execution spec which merged from Wf, WFT and Wfdefault
 	err := woc.setExecWorkflow(ctx)
 	if err != nil {
-		woc.log.WithError(err).Error(ctx, "Unable to set ExecWorkflow")
+		woc.log.WithError(err).WithField("stack", debug.Stack()).Error(ctx, "Unable to set ExecWorkflow")
 		return
```
Comment (eduardodbr) [inline workflow/controller/operator.go:219]: was this on purpose? just checking

File: util/template/template.go [hunk 10]
```diff
@@ -31,17 +34,44 @@ type impl struct {
...
 	})
 	return replacedTmpl.String(), err
 }
+
+func (t *impl) Replace(ctx context.Context, replaceMap map[string]any, allowUnresolved bool) (string, error) {
+	var regex *regexp.Regexp
+	if !allowUnresolved {
+		regex = matchAllRegex
+	}
+	return t.replace(ctx, replaceMap, regex, regex, allowUnresolved)
```
Comment (eduardodbr) [inline util/template/template.go]: `Replace` calls `t.replace` with `regex,regex` as arguments while `ReplaceStrict` calls `t.replace` with `strictRegex, strictRegex`.  It seems `t.replace` could use a single regex

File: util/template/simple_template.go [hunk 11]
```diff
@@ -4,14 +4,25 @@ import (
...
 	"strconv"
 	"strings"
 
 	"github.com/argoproj/argo-workflows/v3/errors"
 	"github.com/argoproj/argo-workflows/v3/util/logging"
 )
 
+var matchAllRegex = regexp.MustCompile(".*")
+
 func simpleReplace(ctx context.Context, w io.Writer, tag string, replaceMap map[string]any, allowUnresolved bool) (int, error) {
```
Comment (eduardodbr) [inline util/template/simple_template.go]: all occurrences of `simpleReplace` were replaced by `simpleReplaceStrict`. Is it safe to delete?

File: workflow/controller/operator.go (hunk 9 above)
Comment (isubasinghe) [reply workflow/controller/operator.go:219]: Ah this should be removed, thanks.

File: util/template/expression_placeholder_test.go [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+
+func TestExpressionReplaceCore_PlaceholderBehavior(t *testing.T) {
+	ctx := logging.TestContext(t.Context())
+
+	env := map[string]any{
+		"foo": "__argo__internal__placeholder-1",
+	}
+	expression := "foo"
+
+	t.Run("AllowUnresolved=true", func(t *testing.T) {
```
Comment (Joibel) [inline util/template/expression_placeholder_test.go]: nit really: This is surprising as a test that proves `allowUnresolved` makes no difference, so it might be nicer presented as a loop.

File: util/template/expression_asint_test.go [hunk 13]
```diff
@@ -0,0 +1,41 @@
...
+func TestExpressionReplaceCore_AsIntPlaceholder(t *testing.T) {
+	ctx := logging.TestContext(t.Context())
+
+	e := env.GetFuncMap(map[string]any{
+		"foo": "__argo__internal__placeholder-1",
+	})
+
+	expression := "asInt(foo)"
+
+	t.Run("AllowUnresolved=true", func(t *testing.T) {
```
Comment (Joibel) [inline util/template/expression_asint_test.go]: nit really: This is surprising as a test that proves allowUnresolved makes no difference, so it might be nicer presented as a loop.

File: util/template/expression_template.go [hunk 14]
```diff
@@ -168,7 +279,101 @@ func hasVariableInExpression(expression, variable string) bool {
 
 // hasVarInEnv checks if a parameter is in env or not
 func hasVarInEnv(env map[string]any, parameter string) bool {
```
Comment (Joibel) [inline util/template/expression_template.go:281]: This is now a monster of a function which could  use some unit test coverage really.

File: util/maps/maps.go [hunk 15]
```diff
@@ -0,0 +1,116 @@
+package maps
```
Comment (Joibel) [inline util/maps/maps.go:1]: Could use a unit test, although in a way this is also simple.

Comment (isubasinghe) [reply util/maps/maps.go:1]: Yeah I think this doesn't need one

File: util/template/expression_template.go (hunk 14 above)
Comment (isubasinghe) [reply util/template/expression_template.go:281]: Sure added some

File: util/template/expression_asint_test.go (hunk 13 above)
Comment (isubasinghe) [reply util/template/expression_asint_test.go]: done

File: util/template/expression_placeholder_test.go (hunk 12 above)
Comment (isubasinghe) [reply util/template/expression_placeholder_test.go]: Done
