### PR TITLE
fix: avoid panic when not passing AuthSupplier

### LINKED ISSUE #9585: panic when not passing  AuthSupplier option
## Checklist

 
* [x] Tested using `:latest` images.
* [x] Attached the smallest workflow that reproduces the issue.

## Summary

What happened/what you expected to happen?

when I try to use [argo client library ](https://argoproj.github.io/argo-workflows/client-libraries/#client-libraries) I got  panic `panic: runtime error: invalid memory address or nil pointer dereference`                                                                     
,when I try  connecting to a server without auth. 

no error or panic expected. SHOULD NOT panic in any way.

What version are you running?
v3.3.9
## Diagnostics

[this code](https://gist.githubusercontent.com/wujunwei/0672ecf83f3cd72f8c8633e677851c8f/raw/0e6c7e99b78d248bcee62da9c0af3bf4ad731691/argo.go) can reproduce it .
```go
ctx, client, err := apiclient.NewClientFromOpts(
		apiclient.Opts{
			ArgoServerOpts: apiclient.ArgoServerOpts{
				URL:                "localhost:31092",  //nodeport
				Secure:             true,
				InsecureSkipVerify: true,
			},
			ClientConfigSupplier: func() clientcmd.ClientConfig { return GetConfig() },
			Context:              context.Background(),
		})
```

to fix this ,I have to add `AuthSupplier: func() string {return ""},` to `apiclient.Opts`
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by wujunwei**
Signed-off-by: wujunwei <wjw3323@live.com>

Fixes #9585

Fix panic: runtime error: invalid memory address or nil pointer dereference

### CODE REVIEW

File: pkg/apiclient/apiclient.go [hunk 1]
```diff
@@ -68,10 +68,19 @@ func NewClientFromOpts(opts Opts) (context.Context, Client, error) {
 	if opts.ArgoServerOpts.URL != "" && opts.InstanceID != "" {
 		return nil, nil, fmt.Errorf("cannot use instance ID with Argo Server")
 	}
+	var auth string
 	if opts.ArgoServerOpts.HTTP1 {
-		return newHTTP1Client(opts.ArgoServerOpts.GetURL(), opts.AuthSupplier(), opts.ArgoServerOpts.InsecureSkipVerify, opts.ArgoServerOpts.Headers)
+		if opts.AuthSupplier != nil {
```
Comment (terrytangyuan) [inline pkg/apiclient/apiclient.go:73]: Should we check auth supplier and return error instead? Otherwise it's `auth=""`

Comment (wujunwei) [reply pkg/apiclient/apiclient.go]: > Should we check auth supplier and return error instead? Otherwise it's `auth=""`

Of course, but we can only do something like below when there is no any Authentication.
```go
apiclient.Opts{
			ArgoServerOpts: ArgoServerOpts,
			AuthSupplier: func() string {
				return ""
			},
		})
```

**Review by alexec — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]
