### PR TITLE
fix(Artifact GC): modified `SearchArtifact` to return `ArtifactSearchResults`. Fixes #8543

### LINKED ISSUE #8543: Artifact GC: `SearchArtifact` to return `ArtifactSearchResults`
Currently, this func returns `Artifacts`, but we need to know which node ID the artifact was from, we can't add that to `Artifact`, but we can introduce some new types:

```golang
type ArtifactSearchResults []ArtifactSearchResult

type ArtifactSearchResult struct {
Artifact
NodeID string
}
```

### PR DESCRIPTION
**Pull request by rohankmr414**
Signed-off-by: Rohan Kumar <rohankmr414@gmail.com>

Fixes #8543

### CODE REVIEW

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 1]
```diff
@@ -1301,11 +1308,11 @@ func (w *Workflow) SearchArtifacts(q *ArtifactSearchQuery) Artifacts {
 				match = false
 			}
 			if match == true {
-				artifacts = append(artifacts, a)
+				results = append(results, ArtifactSearchResult{Artifact: a, NodeID: n.ID})
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:1311]: test?

Comment (rohankmr414) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:1311]: done @alexec

**Review by alexec — APPROVED** [review]
