### PR TITLE
fix(server): Fix the issue where GetArtifact didn't look for input artifacts

### LINKED ISSUE #5704: GetArtifact doesn't look for input artifacts
## Summary 

When running [the artifacts example](https://argoproj.github.io/argo-workflows/examples/#artifacts), the UI link to input artifacts gives not found error.

artifacts

## Diagnostics

The root cause is simple: `returnArtifact` only looks for output artifacts:

https://github.com/argoproj/argo-workflows/blob/91c08cdd83386bfcf48fcb237dd05216bc61b7a0/server/artifacts/artifact_server.go#L127-L133

I'll submit a fix soon but look forward to further discussions.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by dinever**
Fixes #5704

### CODE REVIEW

File: server/artifacts/artifact_server.go [hunk 1]
```diff
@@ -128,6 +128,9 @@ func (a *ArtifactServer) returnArtifact(ctx context.Context, w http.ResponseWrit
 	kubeClient := auth.GetKubeClient(ctx)
 
 	art := wf.Status.Nodes[nodeId].Outputs.GetArtifactByName(artifactName)
+	if art == nil {
+		art = wf.Status.Nodes[nodeId].Inputs.GetArtifactByName(artifactName)
+	}
```
Comment (dinever) [inline server/artifacts/artifact_server.go:133]: I think a better approach might be adding `inputs/outputs` as part of the URL parameters.

For example, Instead of:

```
/artifacts/argo/artifact-passing-fxng8/artifact-passing-fxng8-3010801439/message
```

We can add `input/` before the artifact name.

```
/artifacts/argo/artifact-passing-fxng8/artifact-passing-fxng8-3010801439/input/message
```

Happy to implement this too. But want to hear some thoughts first.

File: server/artifacts/artifact_server.go [hunk 2]
```diff
@@ -128,6 +128,9 @@ func (a *ArtifactServer) returnArtifact(ctx context.Context, w http.ResponseWrit
 	kubeClient := auth.GetKubeClient(ctx)
 
 	art := wf.Status.Nodes[nodeId].Outputs.GetArtifactByName(artifactName)
+	if art == nil {
```
Comment (terrytangyuan) [inline server/artifacts/artifact_server.go:131]: What if inputs and outputs both contain artifact with the same name? Then we would only get the output artifact.

Comment (dinever) [reply server/artifacts/artifact_server.go:131]: Yes. That's why I propose a different approach in https://github.com/argoproj/argo-workflows/pull/5705#discussion_r615542424, to differentiate input/output from the URL.

Will implement it once we reach an agreement. Thanks!

File: server/artifacts/artifact_server.go (hunk 1 above)
Comment (alexec) [reply server/artifacts/artifact_server.go:133]: I think the correct solution would a new end point for input artifacts.  I’m interested to understand when users would want to see inputs mind you.

Comment (dinever) [reply server/artifacts/artifact_server.go:133]: Thanks for the feedback @alexec!

> I’m interested to understand when users would want to see inputs mind you.

I think people use input artifact links mostly for convenience.

For example, an organization may have a big workflow with multiple different steps gathering data from the different data source. Each step is maintained by a different team.  There is a final step to aggregate all the data. It's easier for developers to click that final step and view all the input artifacts instead of finding them in the previous steps' outputs.

> I think the correct solution would a new endpoint for input artifacts.

I wonder if we are talking about something like this:

```diff
        mux.HandleFunc("/api/", func(w http.ResponseWriter, r *http.Request) { webhookInterceptor(w, r, gwmux) })
-       mux.HandleFunc("/artifacts/", artifactServer.GetArtifact)
-       mux.HandleFunc("/artifacts-by-uid/", artifactServer.GetArtifactByUID)
+       mux.HandleFunc("/artifacts/input/", artifactServer.GetInputArtifact)
+       mux.HandleFunc("/artifacts/output/", artifactServer.GetOutputArtifact)
+       mux.HandleFunc("/artifacts-by-uid/input/", artifactServer.GetInputArtifactByUID)
+       mux.HandleFunc("/artifacts-by-uid/output/", artifactServer.GetOutputArtifactByUID)
```

The current URL pattern is `/artificats/{namespace}/{workflowName}/{nodeID}/{artifactName}`, another option is to put `input`/`output` between `nodeID` and `artifactName`: `/artificats/{namespace}/{workflowName}/{nodeID}/input/{artifactName}`

Let me know what you think. Thanks!

Comment (alexec) [reply server/artifacts/artifact_server.go:133]: We should keep the old URL otherwise it might break users.

```
/output-artifacts/{namespace}/{workflowName}/{nodeID}/{artifactName}
/output-artifacts-by-uid/{namespace}/{uuid}/{nodeID}/{artifactName}
```

**Comment by dinever** [comment]
Thanks @alexec!

I've pushed the latest commit which adds two new endpoints to support input artifacts:

```
/input-artifacts/:namespace/:workflowName/:nodeId/:artifactName
/input-artifacts-by-uid/:uid/:nodeId/:artifactName
```

The original URL for output artifacts was not changed. The handler functions were renamed to `GetOutputArtifacts...` tho for clarification.

Please take a look when available. Thanks!

artifacts

**Review by alexec — APPROVED** [review]
