### PR TITLE
fix(controller): Work-around Golang flaw. Fixes #5192

### LINKED ISSUE #5192: Command being replaced into the workflow: Golang fundamental flaw bug - again
## Summary 
I’m facing a quite weird issue when I’m trying to suppress the stderr from the phpunit tests executions and not sure if the workflow command translation is replacing and send the command to the container.

**Issue**
We’re appending  `2> /dev/null` at the end of the phpunit binary (e.g:  `$phpunit 2>dev/null`) - this is a workaround to avoid the stderr payloads being printed during the test execution.
Noticed the command at the Summary tab (name value) has changed from `2> /dev/nul`l to `2u003e/dev/null`
The images are showing the modified command along with the container log output:

### Console output
Screen Shot 2021-02-24 at 5 39 33 PM

### ArgoWF Summary output
Screen Shot 2021-02-24 at 5 38 23 PM

## Diagnostics
The phpunit is failing due the incorrect command parameter received from the workflow (`command`).

Expected:  `phpunit --group unit 2> /dev/null`
     Found:  `phpunit --group unit 2\u300e/dev/null`

Kubernetes provider: 1.18.15-gke.1100
Argo Workflow version: V3.0.0-rc3

```yaml
- name: test-phpunit
        templateRef: 
          name: php
          template: main
        arguments:
          parameters:
            - name: repo
              value: "{{workflow.parameters.repo}}"
            - name: repo-full-name
              value: "{{workflow.parameters.repo-full-name}}"
            - name: revision
              value: "{{workflow.parameters.revision}}"
            - name: sha
              value: "{{workflow.parameters.sha}}"
            - name: command
              value: "{{item.command}}"
            - name: context
              value: "{{item.context}}"
            - name: tag
              value: "{{item.tag}}"
        withItems:
           - { tag: 'Unit-Test', command: './bin/phpunit --group unit 2> /dev/null', context: 'Unit Test' }
           - { tag: 'Integration-Test', command: './bin/phpunit --group integration 2> /dev/null',  context: 'Integration Test' }
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Fixes #5192

### CODE REVIEW

File: util/json/fix.go [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package json
+
+import "strings"
+
+func Fix(s string) string {
```
Comment (terrytangyuan) [inline util/json/fix.go:5]: Need a rebase since these changes already landed in master branch?

**Comment by alexec** [comment]
@simster7 any chance of a code review on this? I'd like to backport it to v2.12 and to v3.0.

**Review by simster7 — APPROVED** [review]

File: pkg/apis/workflow/v1alpha1/item.go [hunk 2]
```diff
@@ -58,15 +60,15 @@ func (i *Item) UnmarshalJSON(value []byte) error {
...
 		panic(err)
 	}
 	// this convenience to remove quotes from strings will cause many problems
-	if jsonBytes[0] == '"' {
-		return string(jsonBytes[1 : len(jsonBytes)-1])
+	if x[0] == '"' {
+		return jsonutil.Fix(string(x[1 : len(x)-1]))
 	}
-	return string(jsonBytes)
+	return jsonutil.Fix(string(x))
```
Comment (sarabala1979) [inline pkg/apis/workflow/v1alpha1/item.go:71]: Suggestion:
Can it be the common wrapper function `json.Marshal` which contains the above definition? So, the developer will call the wrapper function instead of call `json.Marshal` and `jsonutil.fix`.

**Review by sarabala1979 — APPROVED** [review]
