### PR TITLE
fix(controller): Fix the issue of {{retries}} in PodSpecPatch not being updated

### LINKED ISSUE #5388: {{retries}} variable in PodSpecPatch not correctly updated
## Summary 

When using `{{retries}}` inside a PodSpecPatch:

```yaml
podSpecPatch: |
  containers:
    - name: main
      resources:
        limits:
          memory: "{{=(sprig.int(retries) + 1) * 64}}Mi"
```

The variable is not being updated at each retry.

## Diagnostics

What Kubernetes provider are you using? 

Running on local k3d

What version of Argo Workflows are you running? 

Latest master (982e5e9df483e0ce9aa43080683fabadf54e83f2)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-add-memory-
spec:
  entrypoint: retry-add-memory
  templates:
  - name: retry-add-memory
    retryStrategy:
      limit: "5"
      retryPolicy: "Always"
    podSpecPatch: |
      containers:
        - name: main
          resources:
            limits:
              memory: "{{=(sprig.int(retries) + 1) * 64}}Mi"
    container:
      image: python
      command: ["python", "-c"]
      args: ["[i for i in range(10 ** 7)]"]
      resources:
        limits:
          memory: 64Mi
```

In this example, the memory limit will always be 64MB not matter how many times we retry.

The reason is that before executing the template, we replaced the variables at this step:

https://github.com/argoproj/argo-workflows/blob/982e5e9df483e0ce9aa43080683fabadf54e83f2/workflow/controller/operator.go#L1502-L1506

After this point, `{{retries}}` in pod spec patch is replaced by the actual value (0). Later before we retry, `SubstituteParams` won't work for pod spec patch anymore.

https://github.com/argoproj/argo-workflows/blob/982e5e9df483e0ce9aa43080683fabadf54e83f2/workflow/controller/operator.go#L1685-L1688

I'll open a PR soon for my proposed fix for this issue. Thanks!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by dinever**
Fixes #5388

Hi, this is my proposed fix for #5388. The PR basically re-processes all args before each retry. Let me know if there is a better way to fix it. Thanks!

Example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-add-memory-
spec:
  entrypoint: retry-add-memory
  templates:
  - name: retry-add-memory
    retryStrategy:
      limit: "5"
      retryPolicy: "Always"
    podSpecPatch: |
      containers:
        - name: main
          resources:
            limits:
              memory: "{{=(sprig.int(retries) + 1) * 64}}Mi"
    container:
      image: python
      command: ["python", "-c"]
      args: ["[i for i in range(10 ** 7)]"]
      resources:
        limits:
          memory: 64Mi
```

Screen Shot 2021-03-12 at 10 42 45 PM

### CODE REVIEW

File: workflow/controller/operator_test.go [hunk 1]
```diff
@@ -1128,7 +1183,7 @@ func TestStepsRetriesVariable(t *testing.T) {
 		expected = append(expected, fmt.Sprintf("cowsay %d", i))
 	}
 	// ordering not preserved
-	assert.Subset(t, expected, actual)
+	assert.ElementsMatch(t, expected, actual)
```
Comment (dinever) [inline workflow/controller/operator_test.go:1186]: `assert.Subset` should not be used for this case here.

For example, if we have

```
expected = [0, 1, 2, 3, 4, 5]
actual = [0, 0, 0, 0, 0, 0]
```

This case will actually pass since the elements of `actual` is a subset of `expected`.

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -1685,7 +1685,8 @@ func (woc *wfOperationCtx) executeTemplate(ctx context.Context, nodeName string,
 			// Inject the retryAttempt number
 			localParams[common.LocalVarRetries] = strconv.Itoa(len(retryParentNode.Children))
 
-			processedTmpl, err = common.SubstituteParams(processedTmpl, map[string]string{}, localParams)
+			// Re-process the args to make sure {{retries}} variable is correctly updated
+			processedTmpl, err = common.ProcessArgs(resolvedTmpl, &args, woc.globalParams, localParams, false)
```
Comment (simster7) [inline workflow/controller/operator.go:1689]: Should this not be
```suggestion
			// Re-process the args to make sure {{retries}} variable is correctly updated
			processedTmpl, err = common.ProcessArgs(processedTmpl, &args, woc.globalParams, localParams, false)
```
?

Comment (dinever) [reply workflow/controller/operator.go:1689]: Hi. Unfortunately, `processedTmpl` won't work here. Its `PodSpecPatch` is already processed and `{{retries}}` is replaced with `0`. The raw `PodSpecPatch` is lost. Only `resolvedTmpl` has the original `PodSpecPatch`.

`processedTmpl.PodSpecPatch`:
```yaml
containers:
  - name: main
    resources:
      limits:
        memory: "64Mi"
```

`resolvedTmpl.PodSpecPatch`:
```yaml
containers:
  - name: main
    resources:
      limits:
        memory: "{{=(sprig.int(retries) + 1) * 64}}Mi"
```

Another option is that we store the original `PodSpecPatch` as a copy, and substitute args with that. This might work, haven't tested tho:

```diff
                localParams[common.LocalVarPodName] = woc.wf.NodeID(nodeName)
        }
 
+       originalPodSpecPatch := resolvedTmpl.PodSpecPatch
+
        // Inputs has been processed with arguments already, so pass empty arguments.
        processedTmpl, err := common.ProcessArgs(resolvedTmpl, &args, woc.globalParams, localParams, false)
        if err != nil {
@@ -1685,8 +1687,10 @@ func (woc *wfOperationCtx) executeTemplate(ctx context.Context, nodeName string,
                        // Inject the retryAttempt number
                        localParams[common.LocalVarRetries] = strconv.Itoa(len(retryParentNode.Children))
 
+                       // Replace PodSPecPatch with the original one to make sure variables are updated
+                       processedTmpl.PodSpecPatch = originalPodSpecPatch
+
                        processedTmpl, err = common.SubstituteParams(processedTmpl, map[string]string{}, localParams)
```

Let me know what you think. Thanks!

Comment (simster7) [reply workflow/controller/operator.go:1689]: Ah I see. My worry is if we use `resolvedTmpl` again would we not lose all of the other variables we have already processed? For example:

```yaml
arguments:
  parameters:
    - name: message
      value: "This is retry #{{retries}} on pod {{pod.name}}"
```

Would your code not output: `value: "This is retry #0 on pod {{pod.name}}"`? Correct me if I'm wrong

Comment (simster7) [reply workflow/controller/operator.go:1689]: Ah, never mind. I see you're using `ProcessArgs`. Disregard that.

Comment (simster7) [reply workflow/controller/operator.go:1689]: The reason why this worked before and does not work now is because before expressions where allowed, the first call to `ProcessArgs` would leave `{{retries}}` as-is because it didn't then exist in the environment. Then, when we used `SubstituteParams` here we could be sure that a `{{retires}}` (if any) was still not resolved.

However, with the expression, I assume sprint is evaluating `sprig.int(retries)` to 0 because it doesn't exist?

Comment (simster7) [reply workflow/controller/operator.go:1689]: Seems like even if we tell the original call to ignore any field with `retries` and leave it as-is, we will have to call `ProcessArgs` anyway... we won't be able to get away with `SubstituteParams` anymore

Comment (simster7) [reply workflow/controller/operator.go:1689]: I don't think your proposed solution in https://github.com/argoproj/argo-workflows/pull/5389#discussion_r593927074 would work because I don't believe `SubstituteParams` evaluates expressions

Comment (simster7) [reply workflow/controller/operator.go:1689]: I'm trying to see if we can avoid two calls to `ProcessArgs` (which are a bit expensive)... but it seems like a chicken-and-egg problem here

Comment (simster7) [reply workflow/controller/operator.go:1689]: Any ideas?

Comment (simster7) [reply workflow/controller/operator.go:1689]: > I assume sprint is evaluating sprig.int(retries) to 0 because it doesn't exist?

[This is actually the case](https://github.com/argoproj/argo-workflows/issues/5399)

Comment (dinever) [reply workflow/controller/operator.go:1689]: Thanks for the feedback!

> I assume sprint is evaluating sprig.int(retries) to 0 because it doesn't exist?

Yes. Looks like `sprig` will resolve `{{retries}}` to 0 in the original call. I used `sprig` because `{{retries}}` is actually a string here. Without `sprig` we can't do things like `{{=retries + 1}}`:

Screen Shot 2021-03-14 at 11 41 17 PM

Let me see what I can do. Thanks!

Comment (dinever) [reply workflow/controller/operator.go:1689]: > Seems like even if we tell the original call to ignore any field with retries and leave it as-is, we will have to call ProcessArgs anyway... we won't be able to get away with SubstituteParams anymore

Actually I do think `SubstituteParams` evaluates expressions. I was able to pull it off with this fix only:

```diff
diff --git a/util/template/expression_template.go b/util/template/expression_template.go
index 39bd6f01..86840ada 100644
--- a/util/template/expression_template.go
+++ b/util/template/expression_template.go
@@ -4,6 +4,7 @@ import (
        "fmt"
        "io"
        "os"
+       "strings"

        "github.com/antonmedv/expr"
 )
@@ -15,6 +16,12 @@ func init() {
 }

 func expressionReplace(w io.Writer, expression string, env map[string]interface{}, allowUnresolved bool) (int, error) {
+       if strings.Contains(expression, "retries") {
+               _, ok := env["retries"]
+               if !ok && allowUnresolved {
+                       return w.Write([]byte(fmt.Sprintf("{{%s%s}}", kindExpression, expression)))
+               }
+       }
        result, err := expr.Eval(expression, env)
        if (err != nil || result == nil) && allowUnresolved { //  <nil> result is also un-resolved, and any error can be unresolved
                return w.Write([]byte(fmt.Sprintf("{{%s%s}}", kindExpression, expression)))
```

Basically skips resolving `retries` when it's not in the `env`. What do we think?

**Comment by dinever** [comment]
Hi @simster7, just checking in to see If you have any thoughts on this. We can fix this issue by adding our own type conversion functions that raises errors, see https://github.com/argoproj/argo-workflows/issues/5399#issuecomment-799512482, or explicitly skip the processing of `retries` variable when it's not present. I have some free time recently and am happy to work on it.

Thanks!

**Comment by simster7** [comment]
Hi @dinever, sorry I forgot about this! Let's go with your approach here: https://github.com/argoproj/argo-workflows/pull/5389#discussion_r594051674. Just make sure you add a comment explaining what the issue is above and how your code resolves it. I was going to say to also make sure you have some good tests but it looks like you already have that covered :)

**Comment by dinever** [comment]
Thanks for the feedback @simster7! Just pushed the latest commit 0f42d3765f8731803fc55554e58d79b9db2236e8 to explicitly skip the resolving of `retries` when it's not in `env`.

File: util/template/expression_template.go [hunk 3]
```diff
@@ -35,3 +42,17 @@ func envMap(replaceMap map[string]string) map[string]interface{} {
...
+	if err != nil {
+		return false
+	}
+	for _, token := range tokens {
+		if token.Kind == lexer.Identifier && token.Value == "retries" {
+			return true
+		}
+	}
+	return false
+}
```
Comment (dinever) [inline util/template/expression_template.go:58]: Can't really use a simple string matching method like `strings.Contains` since we don't want this logic to be applied on user-defined variables( like `retriesCustom`), so I have to call the `lexer` package, similar to what's being done in `expr`: https://github.com/antonmedv/expr/blob/d389a61c1333215fad33523ca988970f6e77a2b6/parser/parser.go#L89-L91

File: util/template/expression_template_test.go [hunk 4]
```diff
@@ -0,0 +1,17 @@
+package template
+
+import (
+	"github.com/stretchr/testify/assert"
```
Comment (simster7) [inline util/template/expression_template_test.go:4]: We need this to be formatted in a specific order:

```
import (

native libraries

external libraries

internal libraries
)
```

In this case it should be 
```go
import (
    "testing"

    "github.com/stretchr/testify/assert"
)
```

File: workflow/controller/operator_test.go [hunk 5]
```diff
@@ -1068,7 +1068,62 @@ func TestRetriesVariable(t *testing.T) {
...
+              memory: "{{=(sprig.int(retries) + 1) * 64}}Mi"
+    container:
+      image: docker/whalesay:latest
+      command: [sh, -c]
+      args: ["cowsay hello"]
+`
+
+// TestRetriesVariableInPodSpecPatch makes sure that {{retries}} variable in pod spec patch is correctly
+// updated before each retry
+func TestRetriesVariableInPodSpecPatch(t *testing.T) {
```
Comment (simster7) [inline workflow/controller/operator_test.go:1099]: Excellent test!

**Review by simster7 — CHANGES_REQUESTED** [review]
One (tiny) formatting change and then we should be good to go! Thanks @dinever

File: util/template/expression_template.go (hunk 3 above)
Comment (simster7) [reply util/template/expression_template.go:58]: Great find

**Review by simster7 — APPROVED** [review]
Thanks a ton @dinever. This is an excellent contribution. Can I encourage you to maybe [do more](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)?

**Comment by dinever** [comment]
> Thanks a ton @dinever. This is an excellent contribution. Can I encourage you to maybe [do more](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)?

Thanks! Definitely. I'm trying to contribute more to Argo. Will pick up another issue.
