### PR TITLE
fix(server): don't use cluster scope list + watch in namespaced mode. Fixes #13177

### LINKED ISSUE #13177: v3.5.7: namespaced install causes the server to complain about list+watch on cluster scoped workflows
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

To reproduce install 3.5.7 namespaced 
`kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.7/namespace-install.yaml`

You will see
```
W0613 08:46:47.382693       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1alpha1.Workflow: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-server" cannot list
 resource "workflows" in API group "argoproj.io" at the cluster scope                                                                                                                                                                          
E0613 08:46:47.382720       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Workflow: failed to list *v1alpha1.Workflow: workflows.argoproj.io is forbidden: User "system:servicea
ccount:argo:argo-server" cannot list resource "workflows" in API group "argoproj.io" at the cluster scope    
```

This does not happen with 3.5.6 namespaced installs.

I believe this is coming from #12736 / #13021 on lines https://github.com/argoproj/argo-workflows/blob/b28486cdc0a2174d68a0d0d04ba788847552b826/server/workflow/workflow_server.go#L73 and https://github.com/argoproj/argo-workflows/blob/b28486cdc0a2174d68a0d0d04ba788847552b826/server/workflow/workflow_server.go#L76

It feels like these should be namespaced when the server is running namespaced.

### Version

v3.5.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not relevant.
```

### Logs from the workflow controller

```text
Not relevant. Server logs above.
```

### Logs from in your workflow's wait container

```text
Not relevant
```

### PR DESCRIPTION
**Pull request by jiachengxu**
Fixes https://github.com/argoproj/argo-workflows/issues/13177

### Verification
Try to apply the following manifests into a k8s cluster:
```
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.7/namespace-install.yaml
```
With the image built from this PR, don't see the following permission errors anymore:

> 14.612814       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1alpha1.Workflow: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-server" cannot list resource "workflows" in API group "argoproj.io" at the cluster scope
E0614 16:39:14.612865       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Workflow: failed to list *v1alpha1.Workflow: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-server" cannot list resource "workflows" in API group "argoproj.io" at the cluster scope

### CODE REVIEW

**Comment by jiachengxu** [comment]
Hi @Joibel @agilgur5, could you take a look at the PR?

File: server/apiserver/argoserver.go [hunk 1]
```diff
@@ -124,9 +124,9 @@ func init() {
 	}
 }
 
-func getResourceCacheNamespace(opts ArgoServerOpts) string {
-	if opts.ManagedNamespace != "" {
-		return opts.ManagedNamespace
+func getResourceCacheNamespace(managedNamespace string) string {
+	if managedNamespace != "" {
+		return managedNamespace
```
Comment (agilgur5) [inline server/apiserver/argoserver.go:129]: this logic is not quite correct (potentially due to #9989?) -- if not `managedNamespace`, it should check if `namespaced`, and, if so, use `namespace`, otherwise use cluster scope. Same as I wrote in https://github.com/argoproj/argo-workflows/issues/13177#issuecomment-2167280162.

Right now this is missing namespaced mode without managed namespace

Comment (agilgur5) [reply server/apiserver/argoserver.go:129]: Nevermind, apparently the CLI init handles this with [`managedNamespace = namespace`](https://github.com/argoproj/argo-workflows/blob/0ca0c0f721c9bf05c63dea98168cfa87441656c7/cmd/argo/commands/server.go#L98) in that case.

File: pkg/apiclient/argo-kube-client.go [hunk 2]
```diff
@@ -92,7 +93,7 @@ func newArgoKubeClient(ctx context.Context, clientConfig clientcmd.ClientConfig,
 func (a *argoKubeClient) NewWorkflowServiceClient() workflowpkg.WorkflowServiceClient {
 	wfArchive := sqldb.NullWorkflowArchive
 	wfLister := store.NewKubeLister(a.wfClient)
-	return &errorTranslatingWorkflowServiceClient{&argoKubeWorkflowServiceClient{workflowserver.NewWorkflowServer(a.instanceIDService, argoKubeOffloadNodeStatusRepo, wfArchive, a.wfClient, wfLister, nil)}}
+	return &errorTranslatingWorkflowServiceClient{&argoKubeWorkflowServiceClient{workflowserver.NewWorkflowServer(a.instanceIDService, argoKubeOffloadNodeStatusRepo, wfArchive, a.wfClient, wfLister, nil, v1.NamespaceAll)}}
```
Comment (agilgur5) [inline pkg/apiclient/argo-kube-client.go:96]: The SDK doesn't need a namespace since it doesn't use the Reflector/Store, right?

**Review by agilgur5 — COMMENTED** [review]
Thanks for fixing this, just one small comment

File: pkg/apiclient/argo-kube-client.go (hunk 2 above)
Comment (jiachengxu) [reply pkg/apiclient/argo-kube-client.go]: yes, you are right. Although it doesn't matter what namespace we pass here, I made it a nil pointer to make it more clear as you suggested.

File: server/apiserver/argoserver.go (hunk 1 above)
Comment (jiachengxu) [reply server/apiserver/argoserver.go:129]: Thank you for the review, yes, CLI init handles that case.

File: pkg/apiclient/argo-kube-client.go (hunk 2 above)
Comment (agilgur5) [reply pkg/apiclient/argo-kube-client.go]: Yea the explicitness is helpful.
Although I forgot that `nil` only works for pointers in Go, and that the string default `""` is, perhaps confusingly, equivalent to cluster-scope, so you had to refactor a bunch here. The other option would be to use an invalid NS name like `"-1"`, but I think `nil` is clearer than that.

File: server/workflow/workflow_server_test.go [hunk 3]
```diff
@@ -638,7 +638,7 @@ func getWorkflowServer() (workflowpkg.WorkflowServiceServer, context.Context) {
 	if err = wfStore.Add(&wfObj5); err != nil {
 		panic(err)
 	}
-	server := NewWorkflowServer(instanceIdSvc, offloadNodeStatusRepo, archivedRepo, wfClientset, wfStore, wfStore)
+	server := NewWorkflowServer(instanceIdSvc, offloadNodeStatusRepo, archivedRepo, wfClientset, wfStore, wfStore, nil)
```
[the remark this answers is not in the document]
Comment (jiachengxu) [reply server/workflow/workflow_server_test.go]: oh, I think I changed it by accident, and I changed it back the `metav1.NamespaceAll`

> With the new && namespace != nil check, this now takes a different path (but still passes apparently?)

This doesn't really matter regarding the test because we don't [start the reflector to perform list and watch](https://github.com/argoproj/argo-workflows/blob/main/server/workflow/workflow_server.go#L86-L88) in the test and we just [manually add objects to the reflector/store](https://github.com/argoproj/argo-workflows/blob/main/server/workflow/workflow_server_test.go#L631-L640).

[the remark this answers is not in the document]
Comment (agilgur5) [reply server/workflow/workflow_server_test.go]: But the reflector is [set](https://github.com/argoproj/argo-workflows/blob/dc6a18dc545bbf35103ffddb81a014eefcbb403d/server/workflow/workflow_server.go#L79) since the store is not `nil` in this case, so it would start wouldn't it? It just isn't used actively in this test

**Review by agilgur5 — APPROVED** [review]
LGTM, thanks for fixing this! Will have a patch out soon!

File: server/workflow/workflow_server_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (jiachengxu) [reply server/workflow/workflow_server_test.go]: the [`Run` method](https://github.com/argoproj/argo-workflows/blob/main/server/workflow/workflow_server.go#L85-L89) is not called in the test, so the reflector is not started.
