### PR TITLE
fix(controller): shutdownstrategy on running workflow

### LINKED ISSUE #5288: Shutdown strategy is not working 2.12.x onwards.
## Summary 

What happened/what you expected to happen?

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>
fixes #5288 
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

File: workflow/controller/exec_control.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ func (woc *wfOperationCtx) applyExecutionControl(ctx context.Context, pod *apiv1
 		return nil
 	case apiv1.PodPending:
 		// Check if we are currently shutting down
-		if woc.execWf.Spec.Shutdown != "" {
+		if woc.wf.Spec.Shutdown != "" {
```
Comment (terrytangyuan) [inline workflow/controller/exec_control.go:30]: This would be really easy to make mistakes. I know that there are notes on the use of `wf` v.s. `execWf` but I wonder if we could refactor a bit to prevent the misuse of `woc.execWf` on `Suspend` and `Shutdown`.

Comment (sarabala1979) [reply workflow/controller/exec_control.go:30]: Yes, Mainly `Shutdown` and `Suspend` can be changed during the runtime.  The above fix is only for the `WorkflowTemplateRef` scenario rest of the scenario will work as expected.
Possible refactoring for prevent:
1. Code can update `Shutdown` and `Suspend ` on workflow.spec` and `workflow.status.storedWorkflowSpec`.
2. Code needs to construct the `execWf` in each execution. This is a little bit costly operation on each execution. 

I am thinking option 1, We just use `execWf` for all places. Let me talk to the team about what they think.

Comment (sarabala1979) [reply workflow/controller/exec_control.go:30]: After given thought. if the user did patch through `kubectl` then option 1 won't work.

**Review by alexec — COMMENTED** [review]
how come `woc.wf` and `woc.execWf` are not the same? this is very confusing

should we actually be using `woc.wf.ExecSpec()`

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -412,8 +412,8 @@ func (woc *wfOperationCtx) operate(ctx context.Context) {
 	}
 
 	var workflowMessage string
-	if node.FailedOrError() && woc.execWf.Spec.Shutdown != "" {
```
Comment (alexec) [inline workflow/controller/operator.go:415]: can I ask you to add `woc.GetShutdownStrategy()` - that way we can refactor later

**Comment by sarabala1979** [comment]
> how come `woc.wf` and `woc.execWf` are not the same? this is very confusing
> 
> should we actually be using `woc.wf.ExecSpec()`
woc.wf. and woc.execwf is same for normal workflow usecase. But in `workflowtemplateRef` scenario, `execwf` will be calculated the first time. and stored in `storedWorkflowSpec`.  `storedWorkflowSpec` will be used for future execution. `Suspend` and `Shutdown` will be updated later point of runtime.

Another way to fix this issue is checking  `Suspend` and `Shutdown` in workflow and recalculate the` storedWorkflowSpec`

**Comment by alexec** [comment]
I think if we create one func on woc, we can make sure that func is correct

File: workflow/controller/operator.go (hunk 2 above)
Comment (sarabala1979) [reply workflow/controller/operator.go]: Added `needsStoredWfSpecUpdate()` determine to update the `storedWorkflowSpec`.

File: workflow/controller/operator.go [hunk 3]
```diff
@@ -3182,15 +3180,23 @@ func (woc *wfOperationCtx) setExecWorkflow() error {
...
 	if wfDefault == nil {
 		wfDefault = &wfv1.Workflow{}
 	}
-	// woc.wf.Status.StoredWorkflowSpec.Entrypoint == "" check is mainly to support  backward compatible with 2.11.x workflow to 2.12.x
-	// Need to recalculate StoredWorkflowSpec in 2.12.x format.
-	// This check can be removed once all user migrated from 2.11.x to 2.12.x
-	if woc.wf.Status.StoredWorkflowSpec == nil || woc.wf.Status.StoredWorkflowSpec.Entrypoint == "" {
+
+	if woc.wf.Status.StoredWorkflowSpec == nil || woc.needsStoredWfSpecUpdate() {
 		wftHolder, err := woc.fetchWorkflowSpec()
```
Comment (alexec) [inline workflow/controller/operator.go:3200]: could move this `nil` check into `needsStoredWfSpecUpdate `

File: workflow/controller/exec_control.go [hunk 4]
```diff
@@ -75,8 +75,8 @@ func (woc *wfOperationCtx) applyExecutionControl(ctx context.Context, pod *apiv1
 	}
 
 	for _, c := range woc.findTemplate(pod).GetMainContainerNames() {
-		if woc.wf.Spec.Shutdown != "" {
-			if _, onExitPod := pod.Labels[common.LabelKeyOnExit]; !woc.wf.Spec.Shutdown.ShouldExecute(onExitPod) {
+		if woc.execWf.Spec.Shutdown != "" {
```
Comment (alexec) [inline workflow/controller/exec_control.go:78]: can you please add `woc.GetShutdownStrategy()` and `woc.IsSuspend()` to hide this logic?

**Review by alexec — CHANGES_REQUESTED** [review]

File: workflow/controller/exec_control.go [hunk 5]
```diff
@@ -27,18 +27,18 @@ func (woc *wfOperationCtx) applyExecutionControl(ctx context.Context, pod *apiv1
...
 	case apiv1.PodPending:
 		// Check if we are currently shutting down
-		if woc.execWf.Spec.Shutdown != "" {
+		if woc.GetShutdownStrategy() != "" {
 			// Only delete pods that are not part of an onExit handler if we are "Stopping" or all pods if we are "Terminating"
 			_, onExitPod := pod.Labels[common.LabelKeyOnExit]
 
-			if !woc.execWf.Spec.Shutdown.ShouldExecute(onExitPod) {
-				woc.log.Infof("Deleting Pending pod %s/%s as part of workflow shutdown with strategy: %s", pod.Namespace, pod.Name, woc.execWf.Spec.Shutdown)
+			if !woc.GetShutdownStrategy().ShouldExecute(onExitPod) {
```
Comment (alexec) [inline workflow/controller/exec_control.go:34]: minor - could even be `woc.ShouldExecute(...)`

File: workflow/controller/operator.go [hunk 6]
```diff
@@ -3180,11 +3180,19 @@ func (woc *wfOperationCtx) setExecWorkflow() error {
 	return nil
 }
 
+func (woc *wfOperationCtx) GetShutdownStrategy() wfv1.ShutdownStrategy {
+	return woc.execWf.Spec.Shutdown
+}
+
+func (woc *wfOperationCtx) IsSuspend() bool {
```
Comment (alexec) [inline workflow/controller/operator.go:3187]: this name does not scan to me in English. maybe `ShouldSuspend`?

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 7]
```diff
@@ -414,6 +414,10 @@ const (
 	ShutdownStrategyStop      ShutdownStrategy = "Stop"
 )
 
+func (s ShutdownStrategy) Enabled()  bool {
+	return s != ""
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:418]: minor - could add `ShutdownStrategyNone`

**Review by alexec — APPROVED** [review]
