### PR TITLE
fix(executor): handle podlog in deadlineExceed termination. Fixes #7092 #7081

### LINKED ISSUE #7081: Unable to view log if pod get killed due activeDeadlineSeconds
## Summary

What happened/what you expected to happen?

With emissary
If a pod error exit due workflow activeDeadlineSeconds, log is saved.
However, because the output artifact does not appear in workflow.status.nodeid, users are not able to view log from UI `artifact not found`

Viewing log works If a pod error exit due program error, container log is saved and output field are added in workflow.status.nodeid

What version of Argo Workflows are you running?

~v3.2.1

## Diagnostics

Workflow
```
metadata:
  name: omniscient-bear2
  namespace: default
  labels:
    example: 'true'
spec:
  activeDeadlineSeconds: 100
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - bash
          - -c
        args:
          - 'echo 123; sleep 10000'

```

Wait container log
```
time="2021-10-27T10:46:01.788Z" level=info msg="Starting Workflow Executor" executorType=emissary version=latest+bd4e68a.dirty
time="2021-10-27T10:46:01.794Z" level=info msg="Creating a emissary executor"
time="2021-10-27T10:46:01.794Z" level=info msg="Executor initialized" deadline="2021-10-27 10:47:39 +0000 UTC" includeScriptOutput=false namespace=default podName=omniscient-bear2 template="{\"n
ame\":\"argosay\",\"inputs\":{\"parameters\":[{\"name\":\"message\",\"value\":\"hello argo\"}]},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"main\",\"image\":\"argoproj/argosay:v2\",
\"command\":[\"bash\",\"-c\"],\"args\":[\"sleep 10000\"],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":true,\"gcs\":{\"bucket\":\"wx-57a8a73b-9e03-4f1d-9349-bf67bf6d9c2c\",\"serviceAcco
untKeySecret\":{\"name\":\"service-ac-key\",\"key\":\"service-ac-key.json\"},\"key\":\"pipeline/log/omniscient-bear2/omniscient-bear2\"}}}" version="&Version{Version:latest+bd4e68a.dirty,BuildDa
te:2021-10-24T23:52:23Z,GitCommit:bd4e68a5e2013987ceadc089269f7d0cf61f2cb6,GitTag:untagged,GitTreeState:dirty,GoVersion:go1.16.9,Compiler:gc,Platform:linux/amd64,}"
time="2021-10-27T10:46:01.794Z" level=info msg="Starting deadline monitor"
time="2021-10-27T10:47:39.000Z" level=info msg="Step exceeded its deadline"
time="2021-10-27T10:47:39.035Z" level=info msg="Killing containers"
time="2021-10-27T10:47:39.047Z" level=info msg="Get pods 200"
time="2021-10-27T10:47:39.827Z" level=info msg="Main container completed"
time="2021-10-27T10:47:39.827Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-10-27T10:47:39.827Z" level=info msg="Saving logs"
time="2021-10-27T10:47:39.828Z" level=info msg="GCS Save path: /tmp/argo/outputs/logs/main.log, key: pipeline/log/omniscient-bear2/omniscient-bear2/main.log"
time="2021-10-27T10:47:40.081Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2021-10-27T10:47:40.081Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2021-10-27T10:47:40.081Z" level=info msg="No output parameters"
time="2021-10-27T10:47:40.081Z" level=info msg="No output artifacts"
time="2021-10-27T10:47:40.081Z" level=info msg="Annotating pod with output"
time="2021-10-27T10:47:40.096Z" level=info msg="Patch pods 200"
time="2021-10-27T10:47:40.097Z" level=info msg="Killing sidecars []"
time="2021-10-27T10:47:40.097Z" level=info msg="Alloc=26922 TotalAlloc=33488 Sys=74321 NumGC=5 Goroutines=8"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### LINKED ISSUE #7092: k8sapi/pns executor should be able to save log when deadlineExceeded
k8s/pns executor should be able to save log when deadlineExceeded

related #7081 but different executor

```yaml
metadata:
  name: omniscient-bear2
  namespace: default
  labels:
    example: 'true'
spec:
  activeDeadlineSeconds: 100
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - bash
          - -c
        args:
          - 'echo 123; sleep 10000'

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by tczhao**
Fixes #7092

At the moment, when deadlineexceed, the wait container will be stuck at the Wait step and won't proceed further to savelog and annotate output.
This is because when deadlineexceed, the main container.status.termianted is always nil, and k8sapi wait will only proceed when terminated becomes not nil

Fixes #7081

---

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Review by sarabala1979 — APPROVED** [review]

**Comment by sarabala1979** [comment]
@tczhao please fix the conflict

**Comment by tczhao** [comment]
Thanks @sarabala1979 , fixed conflict

**Review by alexec — CHANGES_REQUESTED** [review]
Needs master merge again.

**Comment by tczhao** [comment]
any further comments?

File: workflow/controller/controller.go [hunk 1]
```diff
@@ -1033,6 +1033,10 @@ func (wfc *WorkflowController) newPodInformer(ctx context.Context) cache.SharedI
 					diff.LogChanges(oldPod, newPod)
 					return
 				}
+				// Skip initial deadlineExceed process, informer will receive another update after pod fully terminated
+				if newPod.Status.Reason == common.ErrDeadlineExceeded && oldPod.Status.Reason != common.ErrDeadlineExceeded {
```
Comment (tczhao) [inline workflow/controller/controller.go:1037]: Added fix archiveLog annotation problem in deadlineExceed event for emissary
(because of network delays and queueing, the same problem may occur in pns/k8sapi as well, this fixes that)

image

Comment (alexec) [reply workflow/controller/controller.go:1037]: I think this is the wrong place for this. I can see new bugs appear in future. Whyt  happens if we pass the pod to be assessed, but then ignore it if deadline exceeded?

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -1202,18 +1202,21 @@ func (woc *wfOperationCtx) assessNodeStatus(pod *apiv1.Pod, node *wfv1.NodeStatu
...
-			if exitCode := getExitCode(pod); exitCode != nil {
-				woc.log.Infof("Updating node %s exit code %d", node.ID, *exitCode)
-				node.Outputs = &wfv1.Outputs{ExitCode: pointer.StringPtr(fmt.Sprintf("%d", int(*exitCode)))}
-				if outputStr, ok := pod.Annotations[common.AnnotationKeyOutputs]; ok {
-					woc.log.Infof("Setting node %v outputs: %s", node.ID, outputStr)
-					if err := json.Unmarshal([]byte(outputStr), node.Outputs); err != nil { // I don't expect an error to ever happen in production
-						node.Phase = wfv1.NodeError
-						node.Message = err.Error()
-					}
+			if exitCode != nil || pod.Status.Reason == common.ErrDeadlineExceeded {
```
Comment (alexec) [inline workflow/controller/operator.go:1207]: I think this condition is not needed. All that matters is that we have the annotation. I don't think we need to guard it. Try removing replacing the guard based on exit code with a guard based on `outputStr,ok := pod.Annotations[common.AnnotationKeyOutputs]; ok`

File: workflow/controller/controller.go (hunk 1 above)
Comment (tczhao) [reply workflow/controller/controller.go:1037]: Here are the approaches I have in mind:

1. use delayed pod clean up, 
after **main** container exit, pod is queue for delete straightaway
using delayed cleanup queue allows the informer to receive event from **wait** contianer exit
instead of triggering pod delete and informer never receive event from **wait** contianer exit

However, this introduces a new problem.
Even though the informer receive an event from **wait** container exit,
the workflow still won't get processed (won't update output log to status) due to condition `wf.Labels[common.LabelKeyCompleted] == "true"` (this is labeled from the **main** container exit)

Don't have a further idea on how to solve following this approach

2. skip process pod when main container exit due deadlineExceed
since there's always at least 2 pod update event to informer (1 from **main** container exit, 1 from **wait** container exit)
we skip the initial update (from reason Empty to reason deadlineExceed)
allow the wait container to finished and then have the controller annotate log, label complete

Comment (alexec) [reply workflow/controller/controller.go:1037]: > pod is queue for cleanup queue straightaway,

I thought we'd changed this to always delay clean-up by a short time (maybe 10s) by default. If that's not the case, then that solution is acceptable.

Comment (tczhao) [reply workflow/controller/controller.go:1037]: > I thought we'd changed this to always delay clean-up by a short time (maybe 10s) by default. If that's not the case, then that solution is acceptable.

we have delay queue but don't have this in case of deadlineExceed

I tried added deadlineExceed in delayed queue 
but what would happen is the **main** container exit informer update labels the workflow as complete
and **wait** container exit informer update won't get processed because workflow is complete

At the end of the day, we still rely on a similar mechanism to understand when it is the first deadlineExceed and if it should get processed with the current level of information from pod.

In this case, is it good enough to approve and merge?

Comment (alexec) [reply workflow/controller/controller.go:1037]: Maybe there is another pod which also updates the workflow, or there is rsync (every 20m). This cannot prevent those edge cases, so we get runtime not-deterministic bugs. So we need something more.

Comment (tczhao) [reply workflow/controller/controller.go:1037]: make sense, let me keep thinking

Comment (tczhao) [reply workflow/controller/controller.go:1024]: A late hello in 2022.

The solution is now changed to use a delayed enqueue instead of ignoring the first deadline informer message.

The deadlineExceed from informer will add to queue after 1s and is not rate-limited.
I wonder if this is ok, or we should have another queue that delayed the enqueue to ratelimitedwfQueue (thinking about complexity here)

**Comment by tczhao** [comment]
Hello @alexec , I've made some changes, could you have a review again?

Sorry was on holiday mode and took a while to get back

File: workflow/controller/operator.go [hunk 3]
```diff
@@ -1226,16 +1226,20 @@ func (woc *wfOperationCtx) assessNodeStatus(pod *apiv1.Pod, node *wfv1.NodeStatu
 		// we only need to update these values if the container transitions to complete
 		if newPhase.Fulfilled() {
 			// outputs are mixed between the annotation (parameters, artifacts, and result) and the pod's status (exit code)
+			outputs := &wfv1.Outputs{}
```
Comment (alexec) [inline workflow/controller/operator.go:1229]: does this need changing?

File: workflow/controller/controller.go (hunk 1 above)
Comment (alexec) [reply workflow/controller/controller.go:1024]: No. Think about a workflow this 1000 pods. It'll thunder the controller. We can't have that. Instead, I think it would be fine for there to always be a delay between queuing a workflow, and reconcilliation. 

Is there a way we can update the rate limiter to always delay by 1s? That'd be fine.

**Comment by alexec** [comment]
Rate limiting is set by DEFAULT_REQUEUE_TIME. This defaults to 10s. When run `make start` it is set to 100ms to speed up tests. Try running `make start DEFAULT_REQUEUE_TIME=10s`?

File: workflow/controller/operator.go (hunk 3 above)
Comment (tczhao) [reply workflow/controller/operator.go:1229]: Yes,
In deadlineExceed scenario,
it won't have an exit code, thus won't annotate the output in the original code
this fixed that

**Comment by tczhao** [comment]
setting `DEFAULT_REQUEUE_TIME=1s` works

I'm wondering what's the best strategy here or if there are any tricks available
seems with the existing change, its failing e2e because DEFAULT_REQUEUE_TIME=100ms

**Review by alexec — COMMENTED** [review]
@tczhao I plan to refactor `assessNodeStatus`. Perhaps you'd like to review my PR  #7996 and see if that fixes your issue.

The `k8sapi` executer will be removed in v3.4 or v3.5. I don't know how much work we should do on it.

**Comment by tczhao** [comment]
> Change e2e test set-up?
> 
> > I'm wondering what's the best strategy here or if there are any tricks available
> > seems with the existing change, its failing e2e because DEFAULT_REQUEUE_TIME=100ms
> 
> Change test set-up. If tests run much longer, then we discus. If not, happy day.

Change from 100ms to 1s results in about 12% increase in test time
test time is recorded from all e2e `Run make test-` scripts

image

**Comment by tczhao** [comment]
> 



> @tczhao I plan to refactor `assessNodeStatus`. Perhaps you'd like to review my PR #7996 and see if that fixes your issue.
> 
> The `k8sapi` executer will be removed in v3.4 or v3.5. I don't know how much work we should do on it.

- That #7996 PR solves the issue of not annotating artifact
but we still need `DEFAULT_REQUEUE_TIME` to be at 1s to pass the `ActiveDeadlineSeconds` test

- I'm not concerned too much on the k8sapi part,
maybe still a good patch on 3.3,
I will leave it up to you to make a judgement on if we need that

**Comment by alexec** [comment]
Please resolve conflicts.

**Review by alexec — APPROVED** [review]
