### PR TITLE
fix: Support for custom HTTP headers. Fixes #7985

### LINKED ISSUE #7985: Argo CLI support for custom request headers
# Summary

Add support for setting custom HTTP headers to `argo` CLI, similar to `argocd` `-H, --header`.

# Use Cases

When Argo Workflows is configured behind IAP proxy like Cloudflare Access, we need to set a custom header with key `cf-access-token` and the actual token as a value.
Otherwise, when we execute `argo list`, we face the following error:
```bash
FATA[2022-02-23T22:38:56.530Z] invalid character '<' looking for beginning of value
```
This is already implemented in `argocd` CLI.
As an example, you can see issue [#7036](https://github.com/argoproj/argo-cd/issues/7036).

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by tatodorov**
Signed-off-by: Todor Todorov <todor@todorov.uk>

Fixes #7985

Here is an example when I configure Argo Workflows behind Cloudflare Access and I don't set any header:  
```bash
$ ./argo list -A
FATA[2022-02-25T13:44:46.653Z] invalid character '<' looking for beginning of value
```

Here is an example when I configure Argo Workflows behind Cloudflare Access and I set `cf-access-token` header:  
```bash
$ export DOMAIN=argo-wf.example.com
$ cloudflared access token -app=https://$DOMAIN
$ ./argo -H "cf-access-token:$(cloudflared access token -app=https://$DOMAIN)" list -A
NAMESPACE     NAME                    STATUS      AGE   DURATION   PRIORITY
argo-events   eample-workflow-fsx8t   Succeeded   15h   52m        0
argo-events   eample-workflow-v9zrf   Succeeded   16h   3m         0
argo-events   eample-workflow-9r2q5   Succeeded   17h   1m         0
argo-events   eample-workflow-48ssl   Succeeded   17h   28m        0
argo-events   eample-workflow-pd9xd   Succeeded   18h   32m        0
```

### CODE REVIEW

File: cmd/argo/commands/client/conn.go [hunk 1]
```diff
@@ -46,6 +46,7 @@ func AddAPIClientFlagsToCmd(cmd *cobra.Command) {
 	cmd.PersistentFlags().StringVarP(&argoServerOpts.URL, "argo-server", "s", os.Getenv("ARGO_SERVER"), "API server `host:port`. e.g. localhost:2746. Defaults to the ARGO_SERVER environment variable.")
 	cmd.PersistentFlags().StringVar(&argoServerOpts.Path, "argo-base-href", os.Getenv("ARGO_BASE_HREF"), "An path to use with HTTP client (e.g. due to BASE_HREF). Defaults to the ARGO_BASE_HREF environment variable.")
 	cmd.PersistentFlags().BoolVar(&argoServerOpts.HTTP1, "argo-http1", os.Getenv("ARGO_HTTP1") == "true", "If true, use the HTTP client. Defaults to the ARGO_HTTP1 environment variable.")
+	cmd.PersistentFlags().StringSliceVarP(&argoServerOpts.Headers, "header", "H", []string{}, "Sets additional header to all requests made by Argo CLI. (Can be repeated multiple times to add multiple headers, also supports comma separated headers)")
```
Comment (alexec) [inline cmd/argo/commands/client/conn.go:49]: minor - can we add `ARGO_HEADERS`?

File: pkg/apiclient/http1/facade.go [hunk 2]
```diff
@@ -146,3 +157,15 @@ func errFromResponse(r *http.Response) error {
 	}
 	return status.Error(codes.Internal, fmt.Sprintf(": %v", r))
 }
+
+func parseHeaders(headerStrings []string) (http.Header, error) {
+	headers := http.Header{}
+	for _, kv := range headerStrings {
+		items := strings.Split(kv, ":")
```
Comment (alexec) [inline pkg/apiclient/http1/facade.go:164]: maybe `http` package has header parsing code to use? if not, I'd not bother checking here, just inline the logic at line 103 and keep it simple

**Review by alexec — CHANGES_REQUESTED** [review]
changes requested

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Lgtm
