### PR TITLE
fix: add query string to workflow detail page(#11371)

### LINKED ISSUE #11371: [Pre-release] UI crashes when thare are archived workflows which has same name and namespace.
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### Behaviour

- UI crashes when there are archived workflows that have the same name and namespace.

### To reproduce

- Create two archived workflow which has the same name.
- Open a workflow detail page.
- image
- image

### Cause

- [getWorkflow] pass to backend only ${name} and ${namespace} to backend
  -  https://github.com/argoproj/argo-workflows/blob/22d4e179c3818918c6c4a1fd5ea8d28c816462cc/ui/src/app/shared/services/workflows-service.ts#L69-L70
- Backend returns error when there are one more than workflows in DB
  - https://github.com/argoproj/argo-workflows/blob/22d4e179c3818918c6c4a1fd5ea8d28c816462cc/persist/sqldb/workflow_archive.go#L279

### To resolve

- I'm not sure, but we should pass uid to WorkflowDetails.ts by routing?
  - https://github.com/argoproj/argo-workflows/blob/22d4e179c3818918c6c4a1fd5ea8d28c816462cc/ui/src/app/workflows/components/workflows-container.tsx#L3

### Version

master

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by toyamagu-2021**
Signed-off-by: toyamagu2021@gmail.com <toyamagu2021@gmail.com>

Fixes #11371 

### Modifications

- Add query string `uid` to the workflow detail page.
- Pass `uid` from the workflow list page.
- Use `uid` in the following functions
  - `getArchived`
  - `resubmitArchived`

#### Resubmit Workflow

1. Prepare two archived workflows
   image
1. Successfully opened
    image
1. Resubmit with changed param
    image

#### Workflow GC

1. Create a finite-ttl workflow 
   URL: `http://localhost:8080/workflows/argo/omniscient-dragon?tab=workflow`
   image
2. Workflow gone by GC
   URL is set to: `http://localhost:8080/workflows/argo/omniscient-dragon?tab=summary&uid=4dd0192a-d976-4584-a13b-3e3a8eb196af`
   image
3. Refresh page
   image

### CODE REVIEW

File: ui/src/app/workflows/components/workflow-details/workflow-details.tsx [hunk 1]
```diff
@@ -352,6 +354,10 @@ export const WorkflowDetails = ({history, location, match}: RouteComponentProps<
         );
     };
     useEffect(() => {
+        // If a workflow is archived, we don't need watch.
+        if (isWfInDB) {
```
Comment (toyamagu-2021) [inline ui/src/app/workflows/components/workflow-details/workflow-details.tsx:358]: We should do this here because `workflows.watch` calls `getWorkflow` in the serverside, which cause error described in #11373.

https://github.com/toyamagu-2021/argo-workflows/blob/b9e5e986c533571cacfc37ee2352c5e6860aa8dd/server/workflow/workflow_server.go#L233

File: ui/src/app/workflows/components/workflow-details/workflow-details.tsx [hunk 2]
```diff
@@ -377,18 +385,19 @@ export const WorkflowDetails = ({history, location, match}: RouteComponentProps<
         );
         retryWatch.start();
         return () => retryWatch.stop();
-    }, [namespace, name]);
+    }, [namespace, name, isWfInDB]);
```
Comment (terrytangyuan) [inline ui/src/app/workflows/components/workflow-details/workflow-details.tsx:388]: Could you check if different cases for workflow deletion still work as before?

Comment (terrytangyuan) [reply ui/src/app/workflows/components/workflow-details/workflow-details.tsx:388]: I meant the workflow delete button:
1. Delete only live workflow
2. Also delete archived workflow (there will be a checkbox)

**Comment by terrytangyuan** [comment]
>Workflow gone by GC
The workflow can still be displayed since an archived workflow still exists, right?

**Comment by terrytangyuan** [comment]
@toyamagu-2021 I saw your thumbs-up to my comments and just wondering if that means "I have tested and everything looks good" or "I will be testing it".

File: ui/src/app/workflows/components/workflow-details/workflow-details.tsx (hunk 2 above)
Comment (toyamagu-2021) [reply ui/src/app/workflows/components/workflow-details/workflow-details.tsx:388]: Good point. I'm wrong. 
The checkbox is not shown because `isInCluster=false`.

We should call [this line](https://github.com/toyamagu-2021/argo-workflows/blob/b9e5e986c533571cacfc37ee2352c5e6860aa8dd/ui/src/app/workflows/components/workflow-details/workflow-details.tsx#L359) but this function throws error described in #11371.

I'm thinking about a better way to make 'isInCluster=true'

**Comment by toyamagu-2021** [comment]
@terrytangyuan 
Sorry to forget to reply.

1. https://github.com/argoproj/argo-workflows/pull/11373#issuecomment-1638069148
    Yes, I've tested.

File: ui/src/app/workflows/components/workflow-details/workflow-details.tsx (hunk 2 above)
Comment (terrytangyuan) [reply ui/src/app/workflows/components/workflow-details/workflow-details.tsx]: >  I'm thinking about a better way to make 'isInCluster=true'

This would depend on https://github.com/argoproj/argo-workflows/issues/11367#issuecomment-1640880037?

Comment (toyamagu-2021) [reply ui/src/app/workflows/components/workflow-details/workflow-details.tsx]: Yes, it should depends on a PR.
I'll submit a PR in Friday, or in this weekend.

**Comment by terrytangyuan** [comment]
Let me know when this is ready for another review.

**Comment by toyamagu-2021** [comment]
OK, I had some refactoring and additional following checks on the delete button.

- Not archiving -> no checkbox
- `Archived` -> with checkbox
- `Persisted` -> no checkbox

File: ui/src/app/workflows/components/workflow-details/workflow-details.tsx (hunk 2 above)
Comment (toyamagu-2021) [reply ui/src/app/workflows/components/workflow-details/workflow-details.tsx]: As commented below, I checked this point with/without a checkbox.
- No checkbox -> delete only live workflow ( `Archived` -> `Persisted` )
- With checkbox -> delete live workflow and archived workflow

**Review by terrytangyuan — APPROVED** [review]

File: ui/src/models/workflows.ts [hunk 3]
```diff
@@ -541,7 +541,17 @@ export const execSpec = (w: Workflow) => Object.assign({}, w.status.storedWorkfl
 
 export const archivalStatus = 'workflows.argoproj.io/workflow-archiving-status';
 
+export function isWorkflowInCluster(wf: Workflow): boolean {
+    if (!wf) {
+        return false;
+    }
+    return !wf.metadata.labels[archivalStatus] || wf.metadata.labels[archivalStatus] === 'Pending' || wf.metadata.labels[archivalStatus] === 'Archived';
```
Comment (agilgur5) [inline ui/src/models/workflows.ts:548]: there was a missing check for the existence of `labels` here, fixed in #12898
