### PR TITLE
fix: Fix expression template random errors. Fixes #6673

### LINKED ISSUE #6673: Expression results are printed incorrectly at random
## Summary 

The container prints out the result correctly (see the printed "1" below).

```
 ___ 
< 1 >
 --- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/  

```

However, it sometimes (1 out of 5 times) prints out the raw expression instead (see `{{=jsonpath(workflow.parameters.config, \
\ '$.a')}` below):

```

 _________________________________________ 
/ {{=jsonpath(workflow.parameters.config, \
\ '$.a')}}                                /
 ----------------------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/  
```

Reproducible workflow YAML:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template
spec:
  serviceAccountName: argo
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: a
            value: "{{=jsonpath(workflow.parameters.config, '$.a')}}"
          - name: b
            value: "{{=jsonpath(workflow.parameters.config, '$.b')}}"
          - name: c
            value: "{{=jsonpath(workflow.parameters.config, '$.c')}}"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.a}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  serviceAccountName: argo
  entrypoint: whalesay
  arguments:
    parameters:
      - name: config
        value: '{"a": "1", "b": "2", "c": "3"}'
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template
              template: hello-world
```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

k3d

What version of Argo Workflows are you running? 

v3.2.0-rc1

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

PNS

Did this work in a previous version? I.e. is it a regression?

Haven't checked.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Fixes #6673

### CODE REVIEW

File: util/expand/expand.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+)
+
+func Expand(m map[string]interface{}) map[string]interface{} {
+	return bellows.Expand(removeConflicts(m))
+}
+
+// It is possible for the map to contain conflicts:
+// {"a.b": 1, "a": 2}
+// What should the result be? We remove the less-specific key.
+// {"a.b": 1, "a": 2} -> {"a.b": 1, "a": 2}
```
Comment (whynowy) [inline util/expand/expand.go:17]: no change?

**Review by whynowy — APPROVED** [review]
Minor comments issue.
