### PR TITLE
fix: retry large archived wf. Fixes #12740

### LINKED ISSUE #12740: cannot retry large archived workflow that needs offloading
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

when I retry a large archived workflow (which is failed), it can not retry because of the server error.
image
And I have set offloadNodeStatus=true in configmap, due to the related code, the `offloadNodeStatus` is only valid for the workflow which are not archived. As for archived workflow, it is invalid, the workflow will get all infos from nodeOffloadRepo if need and save it to argo_archived_workflows table, then when retry this workflow, it create a new workflow with 
complete information not using nodeOffloadRepo, so it will be failed.

### Version

V3.5.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
    - - name: run-pod1
        template: run-pod
      - name: run-pod2
        template: run-pod
      - name: run-pod3
        template: run-pod
    - - name: run-pod4
        template: run-pod
      - name: run-pod5
        template: run-pod
      - name: run-pod6
        template: run-pod
    - - name: run-pod7
        template: run-pod
      - name: run-pod8
        template: run-pod
      - name: run-pod9
        template: run-pod
    - - name: run-pod10
        template: run-pod
      - name: run-pod11
        template: run-pod
      - name: run-pod12
        template: run-pod
    - - name: run-pod2-sleep
        template: run-pod-sleep

  - name: run-pod
    steps:
    - - name: run-pod1
        template: run-pod-1
      - name: run-pod2
        template: run-pod-1
      - name: run-pod3
        template: run-pod-1
    - - name: run-pod4
        template: run-pod-1
      - name: run-pod5
        template: run-pod-1
      - name: run-pod6
        template: run-pod-1
  - name: run-pod-1
    steps:
    - - name: run-pod1
        template: run-pod-2
      - name: run-pod2
        template: run-pod-2
      - name: run-pod3
        template: run-pod-2
    - - name: run-pod4
        template: run-pod-2
      - name: run-pod5
        template: run-pod-2
      - name: run-pod6
        template: run-pod-2
  - name: run-pod-2
    steps:
    - - name: run-pod1
        template: run-pod-3
      - name: run-pod2
        template: run-pod-3
      - name: run-pod3
        template: run-pod-3
    - - name: run-pod4
        template: run-pod-3
      - name: run-pod5
        template: run-pod-3
      - name: run-pod6
        template: run-pod-3
  - name: run-pod-3
    steps:
    - - name: run-pod1
        template: run-pod-4
      - name: run-pod2
        template: run-pod-4
      - name: run-pod3
        template: run-pod-4
    - - name: run-pod4
        template: run-pod-4
      - name: run-pod5
        template: run-pod-4
      - name: run-pod6
        template: run-pod-4
  - name: run-pod-4
    steps:
    - - name: run-pod1
        template: run-pod-5
      - name: run-pod2
        template: run-pod-5
      - name: run-pod3
        template: run-pod-5
    - - name: run-pod4
        template: run-pod-5
      - name: run-pod5
        template: run-pod-5
      - name: run-pod6
        template: run-pod-5
  - name: run-pod-5
    container:
      image: docker/whalesay:latest
      command: [python3, -c]
      args: ["print('gfn')"]
  - name: run-pod-sleep ## where running here, we need to stop wf
    container:
      image: docker/whalesay:latest
      command: [python3, -c]
      args: ["print('gfn')\nimport time\ntime.sleep(100)"]
  ttlStrategy:
    secondsAfterCompletion: 3
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```
argo server:
```
level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = etcdserver: request is too large" grpc.code=Internal grpc.method=RetryArchivedWorkflow grpc.service=workflowarchive.ArchivedWorkflowService grpc.start_time="2024-03-04T11:54:36Z" grpc.time_ms=282.849 span.kind=server system=grpc
``` 

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #12740

### CODE REVIEW

File: server/workflowarchive/archived_workflow_server.go [hunk 1]
```diff
@@ -298,13 +302,20 @@ func (w *archivedWorkflowServer) RetryArchivedWorkflow(ctx context.Context, req
...
+			return nil, sutils.ToStatusError(err, codes.Internal)
+		}
+		
 		wf.ObjectMeta.ResourceVersion = ""
 		wf.ObjectMeta.UID = ""
 		result, err := wfClient.ArgoprojV1alpha1().Workflows(req.Namespace).Create(ctx, wf, metav1.CreateOptions{})
 		if err != nil {
 			return nil, sutils.ToStatusError(err, codes.Internal)
 		}
+		offloadVersion, _ := w.offloadNodeStatusRepo.Get(string(oriUid), wf.GetOffloadNodeStatusVersion())
```
Comment (shuangkun) [inline server/workflowarchive/archived_workflow_server.go:317]: can you change "offloadVersion" to "offloadedNodes" and 
do some error handling？ thanks！

Comment (heidongxianhua) [reply server/workflowarchive/archived_workflow_server.go]: > can you change "offloadVersion" to "offloadedNodes" and do some error handling？ thanks！

yeah, I have rename the args and handle the errors. @shuangkun

File: server/workflowarchive/archived_workflow_server.go [hunk 2]
```diff
@@ -298,13 +303,31 @@ func (w *archivedWorkflowServer) RetryArchivedWorkflow(ctx context.Context, req
...
+		}
 
 		wf.ObjectMeta.ResourceVersion = ""
 		wf.ObjectMeta.UID = ""
 		result, err := wfClient.ArgoprojV1alpha1().Workflows(req.Namespace).Create(ctx, wf, metav1.CreateOptions{})
 		if err != nil {
 			return nil, sutils.ToStatusError(err, codes.Internal)
 		}
+		if large {
+			offloadedNodes, err := w.offloadNodeStatusRepo.Get(string(oriUid), wf.GetOffloadNodeStatusVersion())
```
Comment (shuangkun) [inline server/workflowarchive/archived_workflow_server.go:322]: what if wf.GetOffloadNodeStatusVersion() is "" ?

Comment (heidongxianhua) [reply server/workflowarchive/archived_workflow_server.go:322]: If we want to retry a archived workflow, it will create a new workflow, it is different to retry a not-archived workflow. So when retry large archived workflow, we need to `Dehydrate` the wf ( offload the node status) first, the key of these node status is the `uid` of workflow, and then we need to create a new workflow according the Dehydrated workflow. And as for the controller, it will read the offload-node status by the `uid` of the new created workflow, so we copy the node status info of the archived workflow and save it with new `uid` of the new  created workflow. we could only get the `uid` after creating the new workflow, and the controller may process the new created workflow before we update node status with new `uid`, so we catch the db error and make it retry.

File: util/errors/errors.go [hunk 3]
```diff
@@ -37,7 +37,8 @@ func IsTransientErr(err error) bool {
 		apierr.IsServiceUnavailable(err) ||
 		isTransientEtcdErr(err) ||
 		matchTransientErrPattern(err) ||
-		errors.Is(err, NewErrTransient(""))
+		errors.Is(err, NewErrTransient("")) ||
+		strings.Contains(err.Error(), "upper: no more rows in ")
```
[the remark this answers is not in the document]
Comment (heidongxianhua) [reply util/errors/errors.go:41]: yeah, the root cause is as mentioned above. and I will have a test for the function `isTransientSqbErr `.

File: server/workflowarchive/archived_workflow_server.go (hunk 2 above)
Comment (shuangkun) [reply server/workflowarchive/archived_workflow_server.go:319]: I known we should get offloadedNodes. But if version is "", we got err:
```
time="2024-03-12T14:01:23.864Z" level=info msg="Workflow to be dehydrated" Workflow Size=3361331
time="2024-03-12T14:01:24.370Z" level=debug msg="Getting offloaded nodes" uid=06ab13ed-7e5a-4a0c-aeae-40c19f196bc5 version=
time="2024-03-12T14:01:24.371Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = upper: no more rows in this result set" grpc.code=Internal grpc.method=RetryArchivedWorkflow grpc.service=workflowarchive.ArchivedWorkflowService grpc.start_time="2024-03-12T14:01:23Z" grpc.time_ms=1242.014 span.kind=server system=grpc
```
you can test it argo server UI.

File: util/errors/errors.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (shuangkun) [reply util/errors/errors.go]: Where did this error occur? Is there an example to reproduce?

File: server/workflowarchive/archived_workflow_server.go (hunk 2 above)
Comment (shuangkun) [reply server/workflowarchive/archived_workflow_server.go:319]: Maybe we don't need to check "large", becaust Dehydrate->CompressWorkflowIfNeeded>IsLarge have.

File: util/errors/errors.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (heidongxianhua) [reply util/errors/errors.go]: yeah, I run it local with `make start UI=true PROFILE=mysql ALWAYS_OFFLOAD_NODE_STATUS=true`, and submit a workflow and stop it when one step succeed, after it is archived, then retry it. (remove this error caght, it will retry failed at here https://github.com/argoproj/argo-workflows/blob/main/workflow/controller/controller.go#L854)

File: server/workflowarchive/archived_workflow_server.go (hunk 2 above)
Comment (heidongxianhua) [reply server/workflowarchive/archived_workflow_server.go:319]: > Maybe we don't need to check "large", becaust Dehydrate->CompressWorkflowIfNeeded>IsLarge have.

yeah, I have removed this check 'large'.

File: util/errors/errors.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (shuangkun) [reply util/errors/errors.go]: I haven't reproduced it, using the latest version. What version are you using?

[the remark this answers is not in the document]
Comment (shuangkun) [reply util/errors/errors.go]: It may occur in old version：https://github.com/argoproj/argo-workflows/issues/2333

[the remark this answers is not in the document]
Comment (heidongxianhua) [reply util/errors/errors.go]: Yeah，I have checked this issue, and I got the error with evrsion v3.5.0, and the latest commit it also has this error. I test it at locally according to  https://argo-workflows.readthedocs.io/en/latest/running-locally/, and do you add the env `ALWAYS_OFFLOAD_NODE_STATUS=true`? @shuangkun

[the remark this answers is not in the document]
Comment (shuangkun) [reply util/errors/errors.go]: I use `make start UI=true PROFILE=mysql ALWAYS_OFFLOAD_NODE_STATUS=true` run worflow-controller and server and I use latest.

[the remark this answers is not in the document]
Comment (heidongxianhua) [reply util/errors/errors.go]: And I just pull my branch `heidongxianhua:fix_retry_large_archived_wf` and  rebased by the branch `[argoproj:main](https://github.com/argoproj/argo-workflows/tree/main)`. If  i add the error check `https://github.com/argoproj/argo-workflows/pull/12741/files#diff-c2fc14b8209201e80dbf52f4293639d125ce3b6df398ebc93f5ee4e1abf05842R41`, it will run ok and the server.log contains this, but there is no error in controller.log:
image
 
But if i delete this check (run `make clean` and `make start UI=true PROFILE=mysql ALWAYS_OFFLOAD_NODE_STATUS=true`), we will get the error in controller.log, and it lost the node:
image
image
@shuangkun

[the remark this answers is not in the document]
Comment (shuangkun) [reply util/errors/errors.go]: OK, thanks! I reproduced it.  LGTM

**Comment by shuangkun** [comment]
Change the title.  add "Fixes #12740" at the end.    And commit empty Re-trigger CI.

**Comment by heidongxianhua** [comment]
yeah, i have changed the title and Re-trigger the CI again, couly you have a look? @shuangkun

**Review by shuangkun — APPROVED** [review]

**Comment by heidongxianhua** [comment]
thanks, but it has not been merged, could you merge it again? @shuangkun

**Comment by shuangkun** [comment]
> thanks, but it has not been merged, could you merge it again? @shuangkun

Sorry, I don't have permission. I just gave it a high priority to review.  @juliev0 @isubasinghe  Can you help have a look? Thanks!

**Comment by juliev0** [comment]
okay, I'll try to take a look at this one later

**Comment by juliev0** [comment]
@sarabala1979 Is it okay I assigned you to take a look at this? I see you worked on `offloadNodeStatusRepo` for workflow_server.go before.

**Comment by heidongxianhua** [comment]
sorry to bother, could you have a look as this PR? @sarabala1979

File: server/workflowarchive/archived_workflow_server.go [hunk 4]
```diff
@@ -299,12 +303,28 @@ func (w *archivedWorkflowServer) RetryArchivedWorkflow(ctx context.Context, req
...
+			return nil, sutils.ToStatusError(err, codes.Internal)
+		}
+
 		wf.ObjectMeta.ResourceVersion = ""
 		wf.ObjectMeta.UID = ""
 		result, err := wfClient.ArgoprojV1alpha1().Workflows(req.Namespace).Create(ctx, wf, metav1.CreateOptions{})
 		if err != nil {
 			return nil, sutils.ToStatusError(err, codes.Internal)
 		}
+		if !w.hydrator.IsHydrated(wf) {
```
Comment (juliev0) [inline server/workflowarchive/archived_workflow_server.go:318]: I assume this if statement is just in case? there isn't any reason why it shouldn't be dehydrated, right?

Comment (juliev0) [reply server/workflowarchive/archived_workflow_server.go:318]: (nothing wrong with that of course...just trying to make sure I understand)

**Comment by juliev0** [comment]
Can you add comments to the code?

File: server/workflowarchive/archived_workflow_server.go (hunk 4 above)
Comment (heidongxianhua) [reply server/workflowarchive/archived_workflow_server.go:318]: In line 307, we call the func  w.hydrator.Dehydrate(wf) to Dehydrate the wf, but within this function, it will automatically determine whether(according to the size of this wf, https://github.com/argoproj/argo-workflows/blob/main/workflow/hydrator/hydrator.go#L100) dehydration really needs to be performed, so we should to add this if statement . @juliev0

Comment (juliev0) [reply server/workflowarchive/archived_workflow_server.go:318]: got it. Okay, please add some comments around all of this code, because I think it will be hard otherwise for people to understand the purpose.

File: server/workflowarchive/archived_workflow_server.go [hunk 5]
```diff
@@ -299,12 +303,30 @@ func (w *archivedWorkflowServer) RetryArchivedWorkflow(ctx context.Context, req
 			}
 		}
 
+		log.WithFields(log.Fields{"Dehydrate workflow uid=": wf.UID}).Info("RetryArchivedWorkflow")
+		// It will dehydrate the wf actually only if needed (when the size of workflow is too large or set the env `ALWAYS_OFFLOAD_NODE_STATUS`=true)
```
Comment (juliev0) [inline server/workflowarchive/archived_workflow_server.go:307]:
```suggestion
		// If the Workflow needs to be dehydrated in order to capture and retain all of the previous state for the subsequent workflow, then do so
```

Comment (juliev0) [reply server/workflowarchive/archived_workflow_server.go:307]: do you think this is accurate?

File: server/workflowarchive/archived_workflow_server.go [hunk 6]
```diff
@@ -299,12 +303,30 @@ func (w *archivedWorkflowServer) RetryArchivedWorkflow(ctx context.Context, req
...
+			return nil, sutils.ToStatusError(err, codes.Internal)
+		}
+
 		wf.ObjectMeta.ResourceVersion = ""
 		wf.ObjectMeta.UID = ""
 		result, err := wfClient.ArgoprojV1alpha1().Workflows(req.Namespace).Create(ctx, wf, metav1.CreateOptions{})
 		if err != nil {
 			return nil, sutils.ToStatusError(err, codes.Internal)
 		}
+		// determine whether th wf is `Dehydrated` actually before
```
Comment (juliev0) [inline server/workflowarchive/archived_workflow_server.go:319]:
```suggestion
		// if the Workflow was dehydrated before, we need to capture and maintain its previous state for the new Workflow
```

Comment (juliev0) [reply server/workflowarchive/archived_workflow_server.go:319]: is this a correct statement?

**Review by juliev0 — APPROVED** [review]
