### PR TITLE
fix: Mark task result as completed if pod has been deleted for a while. Fixes #13533

### LINKED ISSUE #13533: Workflow stuck `Running` after pod runs 2min and then is deleted not gracefully
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

#13454 mark the node as failed after a timeout and mark the workflowtaskresult as completed only when the pod is absent and the node **has not been completed** in `taskResultReconciliation`.
If we want to check if pod is absent after a timeout, why use `<=` here?
https://github.com/argoproj/argo-workflows/blob/fed83ca9b9678d86e57aea55cf0f73dee879c86f/workflow/controller/taskresult.go#L58

I am very puzzled by this PR, see https://github.com/argoproj/argo-workflows/issues/13373#issuecomment-2315279931.

I think this PR has two problems: 
- problem1: If pod is deleted in 2min(`POD_ABSENT_TIMEOUT`), its task result will be marked as completed immediately. However, we cannot confirm that the pod did not exit gracefully and its task result may not have been observed by the controller yet.
- problem2: If pod is deleted after 2min(`POD_ABSENT_TIMEOUT`), node will be marked as `Error` with message `pod deleted` and its task result will always be incomplete if pod did not exit gracefully.

I reproduced the problem2 as below:

1. rewrite the executor `FinalizeOutput` logic to facilitate the simulation of abnormal exit midway
```golang
// FinalizeOutput adds a label or annotation to denote that outputs have completed reporting.
func (we *WorkflowExecutor) FinalizeOutput(ctx context.Context) {
	log.Info("FinalizeOutput start...")
	// sleep 5s here, avoid patching task result when exit not gracefully.
        time.Sleep(5 * time.Second)
	err := retryutil.OnError(wait.Backoff{
		Duration: time.Second,
		Factor:   2,
		Jitter:   0.1,
		Steps:    5,
		Cap:      30 * time.Second,
	}, errorsutil.IsTransientErr, func() error {
		err := we.patchTaskResultLabels(ctx, map[string]string{
			common.LabelKeyReportOutputsCompleted: "true",
		})
		if apierr.IsForbidden(err) || apierr.IsNotFound(err) {
			log.WithError(err).Warn("failed to patch task result, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/")
			// Only added as a backup in case LabelKeyReportOutputsCompleted could not be set
			err = we.AddAnnotation(ctx, common.AnnotationKeyReportOutputsCompleted, "true")
		}
		return err
	})
	if err != nil {
		we.AddError(err)
	}
	log.Info("FinalizeOutput end...")
}
```

2. submit the workflow demo, and delete the pod after it runs 2min.
```shell
# kubectl delete pod sleep-example-jr4lc-sleep-3885742982 --force        
# argo get sleep-example-jr4lc
Name:                sleep-example-jr4lc
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Running
Conditions:          
 PodRunning          False
Created:             Fri Aug 30 15:38:34 +0800 (29 minutes ago)
Started:             Fri Aug 30 15:38:34 +0800 (29 minutes ago)
Duration:            29 minutes 43 seconds
Progress:            0/1

STEP                    TEMPLATE  PODNAME                               DURATION  MESSAGE
 ✖ sleep-example-jr4lc  main                                                      child 'sleep-example-jr4lc-3885742982' failed  
 └───⚠ sleep            sleep     sleep-example-jr4lc-sleep-3885742982  2m        pod deleted 
```

workflow spec:
```YAML
nodes:
    sleep-example-jr4lc:
      children:
      - sleep-example-jr4lc-2587519231
      displayName: sleep-example-jr4lc
      finishedAt: "2024-08-30T07:41:15Z"
      id: sleep-example-jr4lc
      message: child 'sleep-example-jr4lc-3885742982' failed
      name: sleep-example-jr4lc
      outboundNodes:
      - sleep-example-jr4lc-3885742982
      phase: Failed
      progress: 0/1
      startedAt: "2024-08-30T07:38:34Z"
      templateName: main
      templateScope: local/sleep-example-jr4lc
      type: Steps
    sleep-example-jr4lc-2587519231:
      boundaryID: sleep-example-jr4lc
      children:
      - sleep-example-jr4lc-3885742982
      displayName: '[0]'
      finishedAt: "2024-08-30T07:41:15Z"
      id: sleep-example-jr4lc-2587519231
      message: child 'sleep-example-jr4lc-3885742982' failed
      name: sleep-example-jr4lc[0]
      nodeFlag: {}
      phase: Failed
      progress: 0/1
      startedAt: "2024-08-30T07:38:34Z"
      templateScope: local/sleep-example-jr4lc
      type: StepGroup
    sleep-example-jr4lc-3885742982:
      boundaryID: sleep-example-jr4lc
      displayName: sleep
      finishedAt: "2024-08-30T07:41:15Z"
      hostNodeName: k3d-k3s-default-server-0
      id: sleep-example-jr4lc-3885742982
      message: pod deleted
      name: sleep-example-jr4lc[0].sleep
      outputs:
        artifacts:
        - name: main-logs
          s3:
            key: sleep-example-jr4lc/sleep-example-jr4lc-sleep-3885742982/main.log
      phase: Error
      progress: 0/1
      startedAt: "2024-08-30T07:38:34Z"
      templateName: sleep
      templateScope: local/sleep-example-jr4lc
      type: Pod
  phase: Running
  progress: 0/1
  startedAt: "2024-08-30T07:38:34Z"
  taskResultsCompletionStatus:
    sleep-example-jr4lc-3885742982: false
```

### Version(s)

latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sleep-example-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: sleep
        template: sleep

  - name: sleep
    podSpecPatch: |
      terminationGracePeriodSeconds: 0
    container:
      image: alpine:latest
      command: [sh, -c, sleep 3600]
```

### Logs from the workflow controller
```text
INFO[2024-08-30T15:06:07.597Z] Processing workflow                           Phase= ResourceVersion=2977313 namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:07.602Z] resolved artifact repository                  artifactRepositoryRef="argo/#"
INFO[2024-08-30T15:06:07.602Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.466Z] Updated phase  -> Running                     namespace=argo workflow=sleep-example-f96kd
WARN[2024-08-30T15:06:21.466Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.466Z] was unable to obtain node for , letting display name to be nodeName  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.466Z] Steps node sleep-example-f96kd initialized Running  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.466Z] StepGroup node sleep-example-f96kd-3280373986 initialized Running  namespace=argo workflow=sleep-example-f96kd
WARN[2024-08-30T15:06:21.467Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.467Z] Pod node sleep-example-f96kd-165151271 initialized Pending  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.481Z] Created pod: sleep-example-f96kd[0].sleep (sleep-example-f96kd-sleep-165151271)  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.481Z] Workflow step group node sleep-example-f96kd-3280373986 not yet completed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.482Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.482Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.482Z] Workflow to be dehydrated                     Workflow Size=1442
INFO[2024-08-30T15:06:21.491Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2977322 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.503Z] Processing workflow                           Phase=Running ResourceVersion=2977322 namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.504Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.504Z] node changed                                  namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=sleep-example-f96kd-165151271 old.message= old.phase=Pending old.progress=0/1 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.505Z] Workflow step group node sleep-example-f96kd-3280373986 not yet completed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.505Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.505Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:21.505Z] Workflow to be dehydrated                     Workflow Size=1762
INFO[2024-08-30T15:06:21.512Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2977327 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:22.484Z] Processing workflow                           Phase=Running ResourceVersion=2977327 namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:22.485Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:22.485Z] node unchanged                                namespace=argo nodeID=sleep-example-f96kd-165151271 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:22.486Z] Workflow step group node sleep-example-f96kd-3280373986 not yet completed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:22.486Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:22.486Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:23.653Z] Processing workflow                           Phase=Running ResourceVersion=2977327 namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:23.654Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:23.654Z] node unchanged                                namespace=argo nodeID=sleep-example-f96kd-165151271 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:23.654Z] Workflow step group node sleep-example-f96kd-3280373986 not yet completed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:23.654Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:23.654Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:28.665Z] Processing workflow                           Phase=Running ResourceVersion=2977327 namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:28.666Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:28.666Z] node changed                                  namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=sleep-example-f96kd-165151271 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:28.667Z] Workflow step group node sleep-example-f96kd-3280373986 not yet completed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:28.667Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:28.667Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:06:28.667Z] Workflow to be dehydrated                     Workflow Size=1782
INFO[2024-08-30T15:06:28.673Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2977343 workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.528Z] Processing workflow                           Phase=Running ResourceVersion=2977343 namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.529Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.529Z] Determined controller should timeout for sleep-example-f96kd-165151271  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.529Z] node sleep-example-f96kd-165151271 phase Running -> Failed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.529Z] node sleep-example-f96kd-165151271 message: pod was absent  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.529Z] node sleep-example-f96kd-165151271 finished: 2024-08-30 07:07:11.529418633 +0000 UTC  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.529Z] task-result changed                           namespace=argo nodeID=sleep-example-f96kd-165151271 workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] Step group node sleep-example-f96kd-3280373986 deemed failed: child 'sleep-example-f96kd-165151271' failed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] node sleep-example-f96kd-3280373986 phase Running -> Failed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] node sleep-example-f96kd-3280373986 message: child 'sleep-example-f96kd-165151271' failed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] node sleep-example-f96kd-3280373986 finished: 2024-08-30 07:07:11.530083416 +0000 UTC  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] step group sleep-example-f96kd-3280373986 was unsuccessful: child 'sleep-example-f96kd-165151271' failed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] Outbound nodes of sleep-example-f96kd-165151271 is [sleep-example-f96kd-165151271]  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] Outbound nodes of sleep-example-f96kd is [sleep-example-f96kd-165151271]  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] node sleep-example-f96kd phase Running -> Failed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] node sleep-example-f96kd message: child 'sleep-example-f96kd-165151271' failed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] node sleep-example-f96kd finished: 2024-08-30 07:07:11.530243423 +0000 UTC  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] Updated phase Running -> Failed               namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] Updated message  -> child 'sleep-example-f96kd-165151271' failed  namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] Marking workflow completed                    namespace=argo workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:11.530Z] Workflow to be dehydrated                     Workflow Size=2121
INFO[2024-08-30T15:07:11.537Z] Workflow update successful                    namespace=argo phase=Failed resourceVersion=2977364 workflow=sleep-example-f96kd
INFO[2024-08-30T15:07:43.296Z] Processing workflow                           Phase= ResourceVersion=2977379 namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.300Z] resolved artifact repository                  artifactRepositoryRef="argo/#"
INFO[2024-08-30T15:07:43.300Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.300Z] Updated phase  -> Running                     namespace=argo workflow=sleep-example-hb5m4
WARN[2024-08-30T15:07:43.301Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.301Z] was unable to obtain node for , letting display name to be nodeName  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.301Z] Steps node sleep-example-hb5m4 initialized Running  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.301Z] StepGroup node sleep-example-hb5m4-3239910440 initialized Running  namespace=argo workflow=sleep-example-hb5m4
WARN[2024-08-30T15:07:43.301Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.301Z] Pod node sleep-example-hb5m4-3793842069 initialized Pending  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.312Z] Created pod: sleep-example-hb5m4[0].sleep (sleep-example-hb5m4-sleep-3793842069)  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.312Z] Workflow step group node sleep-example-hb5m4-3239910440 not yet completed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.312Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.312Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:43.312Z] Workflow to be dehydrated                     Workflow Size=1445
INFO[2024-08-30T15:07:43.318Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2977383 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:44.297Z] Processing workflow                           Phase=Running ResourceVersion=2977383 namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:44.298Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:44.298Z] node changed                                  namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=sleep-example-hb5m4-3793842069 old.message= old.phase=Pending old.progress=0/1 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:44.299Z] Workflow step group node sleep-example-hb5m4-3239910440 not yet completed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:44.299Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:44.299Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:44.299Z] Workflow to be dehydrated                     Workflow Size=1765
INFO[2024-08-30T15:07:44.307Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2977391 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:45.810Z] Processing workflow                           Phase=Running ResourceVersion=2977391 namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:45.811Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:45.811Z] node unchanged                                namespace=argo nodeID=sleep-example-hb5m4-3793842069 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:45.812Z] Workflow step group node sleep-example-hb5m4-3239910440 not yet completed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:45.812Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:45.812Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:48.820Z] Processing workflow                           Phase=Running ResourceVersion=2977391 namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:48.822Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:48.822Z] node changed                                  namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=sleep-example-hb5m4-3793842069 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:48.823Z] Workflow step group node sleep-example-hb5m4-3239910440 not yet completed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:48.823Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:48.823Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:07:48.823Z] Workflow to be dehydrated                     Workflow Size=1786
INFO[2024-08-30T15:07:48.829Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2977403 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:32.200Z] Processing workflow                           Phase=Running ResourceVersion=2977403 namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:32.200Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:32.201Z] Determined controller should timeout for sleep-example-hb5m4-3793842069  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:32.201Z] node sleep-example-hb5m4-3793842069 phase Running -> Failed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:32.201Z] node sleep-example-hb5m4-3793842069 message: pod was absent  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:32.201Z] node sleep-example-hb5m4-3793842069 finished: 2024-08-30 07:08:32.20109289 +0000 UTC  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:32.201Z] task-result changed                           namespace=argo nodeID=sleep-example-hb5m4-3793842069 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.359Z] Step group node sleep-example-hb5m4-3239910440 deemed failed: child 'sleep-example-hb5m4-3793842069' failed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.359Z] node sleep-example-hb5m4-3239910440 phase Running -> Failed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.359Z] node sleep-example-hb5m4-3239910440 message: child 'sleep-example-hb5m4-3793842069' failed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.359Z] node sleep-example-hb5m4-3239910440 finished: 2024-08-30 07:08:41.359849788 +0000 UTC  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.359Z] step group sleep-example-hb5m4-3239910440 was unsuccessful: child 'sleep-example-hb5m4-3793842069' failed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.359Z] Outbound nodes of sleep-example-hb5m4-3793842069 is [sleep-example-hb5m4-3793842069]  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.359Z] Outbound nodes of sleep-example-hb5m4 is [sleep-example-hb5m4-3793842069]  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] node sleep-example-hb5m4 phase Running -> Failed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] node sleep-example-hb5m4 message: child 'sleep-example-hb5m4-3793842069' failed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] node sleep-example-hb5m4 finished: 2024-08-30 07:08:41.360090041 +0000 UTC  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] Updated phase Running -> Failed               namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] Updated message  -> child 'sleep-example-hb5m4-3793842069' failed  namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] Marking workflow completed                    namespace=argo workflow=sleep-example-hb5m4
INFO[2024-08-30T15:08:41.360Z] Workflow to be dehydrated                     Workflow Size=2130
INFO[2024-08-30T15:08:41.367Z] Workflow update successful                    namespace=argo phase=Failed resourceVersion=2977427 workflow=sleep-example-hb5m4
INFO[2024-08-30T15:10:42.828Z] Alloc=6313 TotalAlloc=23796 Sys=32853 NumGC=7 Goroutines=179 
INFO[2024-08-30T15:15:42.828Z] Alloc=6003 TotalAlloc=24181 Sys=32853 NumGC=10 Goroutines=179 
INFO[2024-08-30T15:20:42.828Z] Alloc=5938 TotalAlloc=24352 Sys=32853 NumGC=12 Goroutines=179 
INFO[2024-08-30T15:25:42.828Z] Alloc=5845 TotalAlloc=24587 Sys=32853 NumGC=15 Goroutines=179 
INFO[2024-08-30T15:30:42.828Z] Alloc=5974 TotalAlloc=24930 Sys=32853 NumGC=17 Goroutines=179 
INFO[2024-08-30T15:35:42.828Z] Alloc=5925 TotalAlloc=25195 Sys=32853 NumGC=20 Goroutines=179 
INFO[2024-08-30T15:38:34.827Z] Processing workflow                           Phase= ResourceVersion=2978073 namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.832Z] resolved artifact repository                  artifactRepositoryRef="argo/#"
INFO[2024-08-30T15:38:34.832Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.832Z] Updated phase  -> Running                     namespace=argo workflow=sleep-example-jr4lc
WARN[2024-08-30T15:38:34.832Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.832Z] was unable to obtain node for , letting display name to be nodeName  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.832Z] Steps node sleep-example-jr4lc initialized Running  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.832Z] StepGroup node sleep-example-jr4lc-2587519231 initialized Running  namespace=argo workflow=sleep-example-jr4lc
WARN[2024-08-30T15:38:34.832Z] Node was nil, will be initialized as type Skipped  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.832Z] Pod node sleep-example-jr4lc-3885742982 initialized Pending  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.844Z] Created pod: sleep-example-jr4lc[0].sleep (sleep-example-jr4lc-sleep-3885742982)  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.844Z] Workflow step group node sleep-example-jr4lc-2587519231 not yet completed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.844Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.845Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:34.845Z] Workflow to be dehydrated                     Workflow Size=1445
INFO[2024-08-30T15:38:34.851Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2978077 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:35.828Z] Processing workflow                           Phase=Running ResourceVersion=2978077 namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:35.829Z] Task-result reconciliation                    namespace=argo numObjs=0 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:41.760Z] node changed                                  namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=sleep-example-jr4lc-3885742982 old.message= old.phase=Pending old.progress=0/1 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:41.761Z] Workflow step group node sleep-example-jr4lc-2587519231 not yet completed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:41.761Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:41.761Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:41.761Z] Workflow to be dehydrated                     Workflow Size=1765
INFO[2024-08-30T15:38:41.768Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2978102 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:42.761Z] Processing workflow                           Phase=Running ResourceVersion=2978102 namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:42.762Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:49.905Z] node changed                                  namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=sleep-example-jr4lc-3885742982 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:49.905Z] Workflow step group node sleep-example-jr4lc-2587519231 not yet completed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:49.906Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:49.906Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:38:49.906Z] Workflow to be dehydrated                     Workflow Size=1786
INFO[2024-08-30T15:38:49.912Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2978105 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:40:42.828Z] Alloc=6215 TotalAlloc=27810 Sys=32853 NumGC=22 Goroutines=179 
INFO[2024-08-30T15:41:00.059Z] Processing workflow                           Phase=Running ResourceVersion=2978105 namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:00.060Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:13.149Z] task-result changed                           namespace=argo nodeID=sleep-example-jr4lc-3885742982 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.759Z] Workflow pod is missing                       namespace=argo nodeName="sleep-example-jr4lc[0].sleep" nodePhase=Running recentlyStarted=false workflow=sleep-example-jr4lc
ERRO[2024-08-30T15:41:15.759Z] Mark error node                               error="pod deleted" namespace=argo nodeName="sleep-example-jr4lc[0].sleep" workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.760Z] node sleep-example-jr4lc-3885742982 phase Running -> Error  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.760Z] node sleep-example-jr4lc-3885742982 message: pod deleted  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.760Z] node sleep-example-jr4lc-3885742982 finished: 2024-08-30 07:41:15.760163079 +0000 UTC  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] Step group node sleep-example-jr4lc-2587519231 deemed failed: child 'sleep-example-jr4lc-3885742982' failed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] node sleep-example-jr4lc-2587519231 phase Running -> Failed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] node sleep-example-jr4lc-2587519231 message: child 'sleep-example-jr4lc-3885742982' failed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] node sleep-example-jr4lc-2587519231 finished: 2024-08-30 07:41:15.761176068 +0000 UTC  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] step group sleep-example-jr4lc-2587519231 was unsuccessful: child 'sleep-example-jr4lc-3885742982' failed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] Outbound nodes of sleep-example-jr4lc-3885742982 is [sleep-example-jr4lc-3885742982]  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] Outbound nodes of sleep-example-jr4lc is [sleep-example-jr4lc-3885742982]  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] node sleep-example-jr4lc phase Running -> Failed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] node sleep-example-jr4lc message: child 'sleep-example-jr4lc-3885742982' failed  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] node sleep-example-jr4lc finished: 2024-08-30 07:41:15.761561607 +0000 UTC  namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] TaskSet Reconciliation                        namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] reconcileAgentPod                             namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:15.761Z] Workflow to be dehydrated                     Workflow Size=2055
INFO[2024-08-30T15:41:15.769Z] Workflow update successful                    namespace=argo phase=Running resourceVersion=2978157 workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:16.772Z] Processing workflow                           Phase=Running ResourceVersion=2978157 namespace=argo workflow=sleep-example-jr4lc
INFO[2024-08-30T15:41:16.773Z] Task-result reconciliation                    namespace=argo numObjs=1 workflow=sleep-example-jr4lc
```

### Logs from in your workflow's wait container

```text
time="2024-08-30T07:38:36.240Z" level=info msg="Starting Workflow Executor" version=latest+3d41fb2.dirty
time="2024-08-30T07:38:36.245Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2024-08-30T07:38:36.245Z" level=info msg="Executor initialized" deadline="2024-08-30 07:43:34 +0000 UTC" includeScriptOutput=false namespace=argo podName=sleep-example-jr4lc-sleep-3885742982 templateName=sleep version="&Version{Version:latest+3d41fb2.dirty,BuildDate:2024-08-30T06:46:13Z,GitCommit:3d41fb2329ab5ed63db05cf2cbc373c082a6a7aa,GitTag:untagged,GitTreeState:dirty,GoVersion:go1.22.6,Compiler:gc,Platform:linux/amd64,}"
time="2024-08-30T07:38:36.254Z" level=info msg="Starting deadline monitor"
time="2024-08-30T07:40:59.062Z" level=info msg="Deadline monitor stopped"
time="2024-08-30T07:40:59.062Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2024-08-30T07:40:59.326Z" level=warning msg="Non-transient error: context canceled"
time="2024-08-30T07:40:59.326Z" level=info msg="Main container completed" error="context canceled"
time="2024-08-30T07:40:59.326Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2024-08-30T07:40:59.326Z" level=info msg="No output parameters"
time="2024-08-30T07:40:59.326Z" level=info msg="No output artifacts"
time="2024-08-30T07:40:59.326Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: sleep-example-jr4lc/sleep-example-jr4lc-sleep-3885742982/main.log"
time="2024-08-30T07:40:59.326Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-08-30T07:40:59.326Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=sleep-example-jr4lc/sleep-example-jr4lc-sleep-3885742982/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-08-30T07:40:59.335Z" level=info msg="Save artifact" artifactName=main-logs duration=8.712478ms error="<nil>" key=sleep-example-jr4lc/sleep-example-jr4lc-sleep-3885742982/main.log
time="2024-08-30T07:40:59.335Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2024-08-30T07:40:59.335Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2024-08-30T07:40:59.344Z" level=info msg="Alloc=6468 TotalAlloc=13910 Sys=23637 NumGC=5 Goroutines=7"
time="2024-08-30T07:40:59.344Z" level=info msg="FinalizeOutput start..."
```

### PR DESCRIPTION
**Pull request by jswxstw**
Fixes #13533

### Motivation

see #13533 for details.

### Modifications

Mark task result as completed if pod has been deleted for a while.

### Verification

Corner case, hard to reproduce.

### CODE REVIEW

File: workflow/controller/taskresult.go [hunk 1]
```diff
@@ -54,19 +54,14 @@ func (wfc *WorkflowController) newWorkflowTaskResultInformer() cache.SharedIndex
 	return informer
 }
 
-func podAbsentTimeout(node *wfv1.NodeStatus) bool {
-	return time.Since(node.StartedAt.Time) <= envutil.LookupEnvDurationOr("POD_ABSENT_TIMEOUT", 2*time.Minute)
+func recentlyDeleted(node *wfv1.NodeStatus) bool {
+	return time.Since(node.FinishedAt.Time) <= envutil.LookupEnvDurationOr("RECENTLY_DELETED_POD_DURATION", 10*time.Second)
```
Comment (agilgur5) [inline workflow/controller/taskresult.go:58]: If I'm not mistaken, the reason for using `startedAt` was because the `finishedAt` time may never have been recorded

Comment (jswxstw) [reply workflow/controller/taskresult.go:58]: > this almost certainly breaks the part of https://github.com/argoproj/argo-workflows/pull/13454 which was to ensure 3.4->3.5 upgrade worked as hoped for in flight workflows.

Do you mean this problem https://github.com/argoproj/argo-workflows/issues/12103#issuecomment-2185487682?

Comment (isubasinghe) [reply workflow/controller/taskresult.go:58]: That is correct. @jswxstw do you think you would be able to make time for a chat about this issue?

Comment (isubasinghe) [reply workflow/controller/taskresult.go:58]: Actually this doesn't break the 3.4 -> 3.5 upgrade path, the else if check is present meaning we never falsely update the TaskCompletionStatus.

Comment (jswxstw) [reply workflow/controller/taskresult.go:58]: > That is correct. @jswxstw do you think you would be able to make time for a chat about this issue?

Sure, I have time now.

> Actually this doesn't break the 3.4 -> 3.5 upgrade path, the else if check is present meaning we never falsely update the TaskCompletionStatus.

Yes, I kept this fix.

**Review by isubasinghe — APPROVED** [review]
This code should fix #13533. 

I am unsure if this will fix all related issues however. 

Confirmed that in flight workflows from 3.4 -> 3.5 upgrade path will work as expected.

Unfortunately, this path is impacted by another bug and will result in infinite recursion. There is a fix for this as well.

File: workflow/controller/taskresult.go (hunk 1 above)
Comment (isubasinghe) [reply workflow/controller/taskresult.go:58]: > Sure, I have time now.

Its alright, I have enough confidence now that this is a better approach than #13537

**Comment by jswxstw** [comment]
> I am unsure if this will fix all related issues however.

@isubasinghe As far as I know, almost all the related issues are that wait container does not report `LabelKeyReportOutputsCompleted` as expected:
1. waiti container with old versions do not have the label `LabelKeyReportOutputsCompleted`, fixed by #13454
2. wait container exits abnormally, including the following two situations:
    - pod not deleted: fixed by #13491
    - pod deleted: fixed by current issue.

**Comment by isubasinghe** [comment]
> > I am unsure if this will fix all related issues however.
> 
> @isubasinghe As far as I know, almost all the related issues are that wait container does not report `LabelKeyReportOutputsCompleted` as expected:
> 
>     1. wait container with old versions do not have the label `LabelKeyReportOutputsCompleted`, fixed by [fix: mark node failed if pod absent. Fixes #12993 #13454](https://github.com/argoproj/argo-workflows/pull/13454)
> 
>     2. wait container exits abnormally, including the following two situations:
>        
>        * pod not deleted: fixed by [fix: Mark taskResult completed if wait container terminated not gracefully. Fixes #13373 #13491](https://github.com/argoproj/argo-workflows/pull/13491)
>        * pod deleted: fixed by current PR.

Makes sense, I've gone through the code in quite a lot of depth for all of today effectively and I came to a similar conclusion, your agreement clears my doubts, thanks.

**Comment by ericblackburn** [comment]
I've upgraded to 3.5.11, [using chart 0.42.3](https://artifacthub.io/packages/helm/argo/argo-workflows), to use this bug fix but still see that workflows are stuck in a running state
image
image

**Comment by jswxstw** [comment]
> time="2024-09-24T16:26:00.429Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=testnamespace workflow=testworkflow-1727192700-n4v9v

@ericblackburn I think you should fix the RBAC problem.

**Comment by ericblackburn** [comment]
[Yep, that was it.](https://github.com/argoproj/argo-workflows/pull/13537#issuecomment-2378303180) Good call out.
image

**Comment by isubasinghe** [comment]
@jswxstw unfortunately I can confirm that the node.Message can be something other than  "pod deleted" when a pod is killed, this means that your fix won't work. Do you have any  ideas about how we can tackle this without checking the message?

**Comment by jswxstw** [comment]
> @jswxstw unfortunately I can confirm that the node.Message can be something other than "pod deleted" when a pod is killed, this means that your fix won't work. Do you have any ideas about how we can tackle this without checking the message?

Do you mean a pod will be deleted with a message not "pod deleted"?
If a pod is just killed but not deleted yet, #13491 will check the actual status of `wait` container.

**Comment by isubasinghe** [comment]
@jswxstw sorry yeah I meant deleted

**Comment by isubasinghe** [comment]
I think we should just see if the pod for that node disappeared in the `IsPodDeleted` function, opinions @jswxstw ?

**Comment by jswxstw** [comment]
> I think we should just see if the pod for that node disappeared in the `IsPodDeleted` function, opinions @jswxstw ?

Yes, we can use `woc.podExists` instead to check if its pod has disappeared.
However, If a pod is deleted with a message not "pod deleted", it means controller has observed the pod status after `podReconciliation` and it should already know the actual status of `wait` container. Are there other scenarios I haven't considered?

**Comment by Joibel** [comment]
I would like it to wait some time between observing a gone pod without a `completed` workflow task result and us kicking in the marking of the task result as completed. It could be that the completed WFTresult just hasn't been observed yet.

**Comment by jswxstw** [comment]
> This might be due to a race condition, I am currently unsure of how this happens.

https://github.com/argoproj/argo-workflows/blob/cf6223d8f21e1cfb49492c6b5aeca40752ee2787/workflow/controller/operator.go#L1459-L1461

Under normal circumstances, the node can only be set to `Completed` when `wait` container has truly exited.
Therefore, in theory, we should always be able to obtain the actual state of `wait` container here, unless the pod is deleted before the controller has a chance to observe it. In such cases, it will be marked as 'pod deleted'.

**Comment by isubasinghe** [comment]
Okay I found out what happens. If the node has been marked failed by some other failure and we are still waiting on task results, the message will never be updated to reflect `pod deleted` since podReconciliation will skip this node. 

I suggest that markNodePhase should be responsible for patching marking the task result completed in this case.
I see no reason why we would want to wait around for a task result when the node has already been marked Failed/Errored?

**Comment by isubasinghe** [comment]
Opinions @jswxstw ?

**Comment by jswxstw** [comment]
> Okay I found out what happens. If the node has been marked failed by some other failure and we are still waiting on task results, the message will never be updated to reflect `pod deleted` since podReconciliation will skip this node.

@isubasinghe Do you mean the node is marked failed in `podReconciliation`? It will not bring any problems if so because controller will check the actual state of `wait` container.

I found that it will casue some problems if controller marks the node as failed directly regardless of the pod's status, see https://github.com/argoproj/argo-workflows/issues/13726#issuecomment-2399634859. Are you encountering similar issues?

**Comment by isubasinghe** [comment]
@jswxstw I mean  if it is marked elsewhere. 

I think `markNodePhase` should include an if condition to check if the phase is error/failure and then markTaskResultsComplete(node.ID)

**Comment by jswxstw** [comment]
> @jswxstw I mean if it is marked failed elsewhere, not in podReconciliation.

@jswxstw Could you specify exactly where? In my opinion controller should not mark the node as failed directly regardless of the pod's status.

**Comment by isubasinghe** [comment]
@jswxstw I wasn't able to find where exactly, I think what we should do is if we mark nodes failed, we should mark the task result complete.

Also if we get a false label in `taskResultReconciliation` we should first make sure the node hasn't failed or errored first, before labelling task result incomplete.

**Comment by jswxstw** [comment]
@isubasinghe I think there are risks in doing this, because at this point we cannot confirm whether the informer has watched task result updates, this process may be delayed.

**Comment by isubasinghe** [comment]
@jswxstw but we don't care about a task result after we fail a node, correct? So it doesn't matter if we receive a task result or not.

**Comment by jswxstw** [comment]
@isubasinghe We may need the exact exit code of the node from the task result.

**Comment by isubasinghe** [comment]
@jswxstw I think it should be okay after looking at the code.

We seem to only add to scope if the node succeeded: https://github.com/argoproj/argo-workflows/blob/bb5130e841ab02cfe5b65f19c214fe309ca88bce/workflow/controller/operator.go#L1144 

So you are right that the second conditional will now return true, but he first condition still returns false. Therefore this behaviour should remain the same.

**Comment by isubasinghe** [comment]
Steps/DAGs doesn't seem to care about task results. I wonder if this is a bug on that part of  the codebase ?

**Comment by jswxstw** [comment]
> So you are right that the second conditional will now return true, but he first condition still returns false. Therefore this behaviour should remain the same.

There is an inconsistency in the judgment logic in these two places:
https://github.com/argoproj/argo-workflows/blob/bb5130e841ab02cfe5b65f19c214fe309ca88bce/workflow/controller/operator.go#L2335

https://github.com/argoproj/argo-workflows/blob/bb5130e841ab02cfe5b65f19c214fe309ca88bce/workflow/controller/operator.go#L1144

> Steps/DAGs doesn't seem to care about task results. I wonder if this is a bug on that part of the codebase ?

Only nodes of pod type have task results, other nodes depend on their child nodes.

**Comment by isubasinghe** [comment]
In my PR I have proposed an alternative fix: https://github.com/argoproj/argo-workflows/pull/13798, 
would you still prefer this?

**Comment by jswxstw** [comment]
> Sorry I meant, pods created by the templates {Step, DAG}. They do not wait until a task result is complete before creating a child. I think this is a bug? Because a task could have a `continueOn: Failed` and the child could rely upon the parents exit code.

Agree, we may also check if task result is Incomplete when node is failed.

> would you still prefer this?

This PR may exacerbate the above bug, but it is likely to have no impact, as nodes are rarely marked as failed directly outside of `podReconciliation`(this only occurs in the scenario of workflow shutdown).

**Comment by isubasinghe** [comment]
> but it is likely to have no impact 

yeah this is what I think as well. 


I do think we need to rethink the task result implementation entirely.

**Comment by isubasinghe** [comment]
@jswxstw I made the change here https://github.com/argoproj/argo-workflows/pull/13798 to check if the pod exists instead.

It turns out we do care about failed nodes, this was why the test was failing. 

I'm not sure if you'd agree with me, but I now think that this task result should maybe even be communicated via grpc or something like that to the controller directly. 
I

**Comment by agilgur5** [comment]
> I'm not sure if you'd agree with me, but I now think that this task result should maybe even be communicated via grpc or something like that to the controller directly.

security-wise, the Executor should never be able to directly communicate with the Controller. The CRs partly exist for that purpose, as well as for (temporary) durable storage in case of an outage

**Comment by isubasinghe** [comment]
> Security-wise, the Executor should never need to nor be able to directly communicate with the Controller.

I don't really risk here though personally, could you elaborate how this creates a security risk. 
I mean I don't really expect to make this change, but we want consistency. 


We only have two choices here that I would be confident fixes this class of bugs:

a) communicate directly to the controller.
b)  bypass the cache and hit the API directly

**Comment by agilgur5** [comment]
> I don't really see the risk here though personally, could you elaborate how this creates a security risk.

The Controller would now be accessible via network from every namespace that Workflows runs in. Other than breaking network policies all over, this creates a whole new attack surface, as well as gives the Controller an API as an additional attack surface (and dependencies).
Anything would be able to hit that API as well, since the Executor is like any other Workflow Pod container; comparatively RBAC is used to control access to `WorkflowTaskResults` etc

That's a massive can of worms and fundamental shift in the architecture that I don't think should be changed.

**Comment by jswxstw** [comment]
> I'm not sure if you'd agree with me, but I now think that this task result should maybe even be communicated via grpc or something like that to the controller directly.

I agree with @agilgur5. Argo, as a workflow engine for Kubernetes, is implemented based on asynchronous coordination. Transforming it into a synchronous mode is not in line with the Kubernetes style.

**Comment by isubasinghe** [comment]
> The Controller would now be accessible via network from every namespace that Workflows runs in. 

Yeah that is fair enough. 

> That's a massive can of worms and fundamental shift in the architecture that I don't think should be changed.

Yeah I agree on this, I just don't see how to fix these issue with any sort of confidence.

**Comment by jswxstw** [comment]
I feel that the reasons for these issues are twofold: 
- one is that we have split the original atomic operation to two: `podReconciliation` and `taskResultReconciliation`
- the other is that we did not fully consider the scenarios involving the coordination order and the loss of resources to be coordinated.

After so many fixes, we have actually covered the vast majority of scenarios. If there are still any edge cases that haven't been considered, the probability of them occurring will be very low, and the risk is manageable.

**Comment by agilgur5** [comment]
> state tracking can be done with a database

There's very little difference between a DB and using k8s resources/etcd. That also doesn't solve Pod tracking, which already uses k8s.
And similarly to my comments [above](https://github.com/argoproj/argo-workflows/pull/13537#issuecomment-2436694363) about Executor -> Controller connections, Executor -> DB connections also open up a can of worms around security

**Comment by agilgur5** [comment]
> I feel that the reasons for these issues are twofold:

Yea that sounds about right to me, with non-graceful termination as part of 2. 1. can't be done atomically given the different Informers involved, so it needs a different form of async coordination with some assumptions baked in

File: workflow/controller/taskresult.go (hunk 1 above)
Comment (agilgur5) [reply workflow/controller/taskresult.go:58]: Related: https://github.com/argoproj/argo-workflows/pull/13798#discussion_r1818921785
