### PR TITLE
fix: process aggregate outputs for steps node with retries. Fixes #14647

### LINKED ISSUE #14647: workflows that use withItems are failing with error Workflow operation error
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When running workflows that use `withItems`,  the error message  `Workflow operation error` appears after the execution of these item workflows

Image

Image

### Version(s)

v3.7.0-rc3

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-workflow-with-items
spec:
  schedule: "0 20 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  workflowSpec:
    entrypoint: process-items
    templates:
      - name: process-items
        steps:
          - - name: process-single-item
              template: echo-item
              arguments:
                parameters:
                  - name: item-value
                    value: "{{item}}"
              withItems:
                - Test Value1
                - Test Value2
                - Test Value3
      - name: echo-item
        inputs:
          parameters:
            - name: item-value
        container:
          image: busybox
          command: ["sh", "-c"]
          args: ["echo 'Processing item: {{inputs.parameters.item-value}}'"]
```

### Logs from the workflow controller

```level=error msg="Recovered from panic" namespace=argo r="failed to parse '0)' as int: strconv.Atoi: parsing \"0)\": invalid syntax" stack="goroutine 19346 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:195 +0xc5\npanic({0x2908680?, 0xc000e642e0?})\n\t/usr/local/go/src/runtime/panic.go:792 +0x132\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.parseLoopIndex({0xc001f9a850?, 0xc00349fda0?})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3298 +0x12a\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.loopNodes.Less({0xc0001b5c08, 0x6, 0xc0007a2008?}, 0xc00226d260?, 0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3305 +0x74\nsort.insertionSort({0x3429270, 0xc0003a4c90}, 0x0, 0x6)\n\t/usr/local/go/src/sort/zsortinterface.go:12 +0xa7\nsort.pdqsort({0x3429270, 0xc0003a4c90}, 0x18?, 0x297b9a0?, 0x1?)\n\t/usr/local/go/src/sort/zsortinterface.go:73 +0x305\nsort.Sort({0x3429270, 0xc0003a4c90})\n\t/usr/local/go/src/sort/sort.go:54 +0x54\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).processAggregateNodeOutputs(0xc000942040?, 0xc0010675e0, {0xc00057dc00, 0x1e}, {0xc0001b5c08, 0x6, 0x8})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3329 +0x1c6\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc003329bc0, {0x3442cb8, 0xc001e3a3f0}, {0xc001f2ec30, 0x21}, 0xc000942040, {0xc003bde630, 0x24}, 0xc0021b2248, {0x344a280, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:153 +0x1925\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc003329bc0, {0x3442cb8, 0xc001e3a3f0}, {0xc000ac8e20, 0x1e}, {0x344a280, 0xc002e73c80}, 0xc000942000, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2248 +0x3905\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc003329bc0, {0x3442cb8, 0xc001e3a3f0})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:368 +0x1d2b\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0003e2108, {0x3442cf0, 0xc000401180})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:742 +0x705\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0003e2108, {0x3442cf0, 0xc000401180})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:657 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1({0x3442cf0?, 0xc000401180?}, 0xc0027f8b70?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.1/pkg/util/wait/backoff.go:255 +0x51\nk8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext({0x3442cf0, 0xc000401180}, 0xc002127300, {0x3406a20, 0xc0027f8b70}, 0x1)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.1/pkg/util/wait/backoff.go:256 +0xe5\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x3442cf0, 0xc000401180}, 0xc002127300, 0x3b9aca00, 0x0, 0x1)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.1/pkg/util/wait/backoff.go:223 +0x8f\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.1/pkg/util/wait/backoff.go:172\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run in goroutine 19122\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:369 +0x196a\n```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by jswxstw**
Fixes #14647

### Modifications

 Filter retried nodes and only aggregate outputs of their parent nodes.

### Verification

E2E test and local test

### CODE REVIEW

File: workflow/controller/steps.go [hunk 1]
```diff
@@ -136,6 +136,10 @@ func (woc *wfOperationCtx) executeSteps(ctx context.Context, nodeName string, tm
 				var childNodes []wfv1.NodeStatus
 				for _, node := range woc.wf.Status.Nodes {
 					if node.BoundaryID == stepsCtx.boundaryID && strings.HasPrefix(node.Name, childNodeName+"(") && node.Type != wfv1.NodeTypeSkipped {
+						// Filter retried nodes and only aggregate outputs of their parent nodes.
+						if node.NodeFlag != nil && node.NodeFlag.Retried {
+							continue
+						}
```
Comment (isubasinghe) [inline workflow/controller/steps.go]: I did think of doing this myself, but it doesn't feel like the right fix, maybe this is fine for now though.
It really feels like we should  move away from parsing the name to sort and more generally just using the name to carry information.

Comment (jswxstw) [reply workflow/controller/steps.go]: > It really feels like we should move away from parsing the name to sort and more generally just using the name to carry information.

Agree, this approach is very unreliable.

However, this PR actually filters out the outputs of the underlying retried nodes during the processing of aggregate outputs, which is necessary.

Comment (isubasinghe) [reply workflow/controller/steps.go]: Yeah I agree this is necessary, the underlying nodes are irrelevant as long as the retry nodes are guaranteed to be equivalent to the output of the retried nodes.

**Comment by isubasinghe** [comment]
Okay I think lets do a proper non-parsing based fix later. I am just going to accept this for now.

**Review by isubasinghe — APPROVED** [review]
Lets fix this properly in 3.8
