### PR TITLE
fix(controller): Add configmap already exists judgment on offload Env…

### LINKED ISSUE #13755: When offloading env, no error judgment was made for configmap.
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

## What happened?
if workflow pod used offload envVarTemplate, when pod create failed, and a transient error occurred. The pod will retry on moment, then this node will failed with `IsAlreadyExists` error.
image
## What did you expect to happen?
we should process the `AlreadyExists` error

### Version(s)

main

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
None
```

### Logs from the workflow controller

```text
None
```

### Logs from in your workflow's wait container

```text
None
```

### PR DESCRIPTION
**Pull request by fyp711**
…VarTemplate

Fixes #13755 

### Motivation

if workflow pod used offload envVarTemplate, when pod create failed, and a transient error occurred. The pod will retry on moment, then this node will failed with IsAlreadyExists error.

### Modifications

We should process `Already Exists` error

### Verification

The best way to verifiy is constructing a too lang template, and than simulate a transient error

### CODE REVIEW

File: workflow/controller/workflowpod.go [hunk 1]
```diff
@@ -460,7 +460,9 @@ func (woc *wfOperationCtx) createWorkflowPod(ctx context.Context, nodeName strin
 		}
 		created, err := woc.controller.kubeclientset.CoreV1().ConfigMaps(woc.wf.ObjectMeta.Namespace).Create(ctx, cm, metav1.CreateOptions{})
 		if err != nil {
-			return nil, err
+			if !apierr.IsAlreadyExists(err) {
+				return nil, err
+			}
 		}
 		woc.log.Infof("Created configmap: %s", created.Name)
```
Comment (Joibel) [inline workflow/controller/workflowpod.go:467]: This log message is now misleading, could you fix it (I would suggest two possible logs, one for created and one for already exists)..

File: workflow/controller/workflowpod.go [hunk 2]
```diff
@@ -460,7 +460,9 @@ func (woc *wfOperationCtx) createWorkflowPod(ctx context.Context, nodeName strin
 		}
 		created, err := woc.controller.kubeclientset.CoreV1().ConfigMaps(woc.wf.ObjectMeta.Namespace).Create(ctx, cm, metav1.CreateOptions{})
 		if err != nil {
-			return nil, err
+			if !apierr.IsAlreadyExists(err) {
```
Comment (Joibel) [inline workflow/controller/workflowpod.go:463]: nit: probably neater as a single line
```go
if err != nil && !apierr.IsAlreadyExists(err)
```

**Review by Joibel — CHANGES_REQUESTED** [review]

File: workflow/controller/workflowpod.go (hunk 1 above)
Comment (fyp711) [reply workflow/controller/workflowpod.go:465]: fixed, thanks.

Comment (fyp711) [reply workflow/controller/workflowpod.go:465]: ok

Comment (fyp711) [reply workflow/controller/workflowpod.go]: fixed

File: workflow/controller/workflowpod.go [hunk 3]
```diff
@@ -460,9 +460,13 @@ func (woc *wfOperationCtx) createWorkflowPod(ctx context.Context, nodeName strin
...
+				return nil, err
+			}
+			woc.log.Infof("Configmap is already exists: %s", cm.Name)
```
[the remark this answers is not in the document]
Comment (fyp711) [reply workflow/controller/workflowpod.go]: Done

**Comment by Joibel** [comment]
Thanks for this, and for testing 3.6
