### PR TITLE
fix: cache calls to prevent exponential recursion. Fixes #14904

### LINKED ISSUE #14904: Controller cannot reconcile for the workflow having large amount of steps
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

 When running large and highly parallel steps-based workflows (hundreds to thousands of total steps and about 100 steps running in parallel), the controller cannot reconcile partway through. The workflow appears to stop indefinitely. When we submit a workflow described later, the workflow stops at 4~5th step.

 Pods belonging to the last scheduled steps remain in the `Completed` phase and controller logs show pod delete events for those pods. But the workflow is not reconciled further. As shown in attached images, Argo considers these pods to still be running.
```
hello-100-sleep-5-10-7nbs5-jlcc9-sleep-147858984                       0/2     Completed   0          19m
hello-100-sleep-5-10-7nbs5-jlcc9-sleep-1747241164                      0/2     Completed   0          19m
hello-100-sleep-5-10-7nbs5-jlcc9-sleep-2200685416                      0/2     Completed   0          19m
hello-100-sleep-5-10-7nbs5-jlcc9-sleep-3386732568                      0/2     Completed   0          19m
hello-100-sleep-5-10-7nbs5-jlcc9-sleep-4008404964                      0/2     Completed   0          19m
```

Image
Image
Image

 This behavior started in v3.7.0 and reproduces on 3.7.x. If we downgrade the controller to v3.6.x(we tried v3.6.10) while the workflow is stalled, reconciliation immediately resumes and the workflow runs to completion. We think this issue is introduced in v3.7.x.

 We tried below but there are no effects.
- Restarting the controller.
- Manually re-enqueuing for the workflow.
- Tuning controller scaling parameters in https://argo-workflows.readthedocs.io/en/latest/scaling/.

### Version(s)

v3.7.0, v3.7.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
## Below is a CronWorkflow manifest. The same result occurs even if we submit from a Workflow manifest.
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  generateName: hello-100-sleep-5-10-
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 4
  schedule: 12 * * * *
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 4
  suspend: true
  timezone: Asia/Tokyo
  workflowSpec:
    arguments:
      parameters:
      - name: HELLO_STEP_SEQ_NUM
        value: "100"
      - name: SLEEP_SEQ_NUM
        value: "5"
      - name: SLEEP_TIME_SEC
        value: "10"
    entrypoint: main
    podGC:
      strategy: OnPodCompletion
    serviceAccountName: argo
    templates:
    - name: main
      steps:
      - - name: hello-world1
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep1
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
      - - name: hello-world2
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep2
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
      - - name: hello-world3
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep3
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
      - - name: hello-world4
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep4
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
      - - name: hello-world5
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep5
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
      - - name: hello-world6
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep6
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
      - - name: hello-world7
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep7
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
      - - name: hello-world8
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep8
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
      - - name: hello-world9
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
          name: sleep9
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
      - - name: hello-world10
          template: hello-world
          withSequence:
            count: '{{workflow.parameters.HELLO_STEP_SEQ_NUM}}'
      - - name: sleep10
          template: sleep
          withSequence:
            count: '{{workflow.parameters.SLEEP_SEQ_NUM}}'
          arguments:
            parameters:
            - name: SLEEP_TIME_SEC
              value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
    - name: hello-world
      container:
        args:
        - echo hello_world
        command:
        - sh
        - -c
        image: XXXXX # in-house image based on rocky linux 9. We also confirmed reproducibility by using official rockylinux image.
        name: "hello"
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
    - name: sleep
      container:
        args:
        - sleep ${SLEEP_TIME_SEC}
        command:
        - sh
        - -c
        env:
        - name: SLEEP_TIME_SEC
          value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
        image: XXXXX # in-house image based on rocky linux 9. We also confirmed reproducibility by using official rockylinux image.
        name: "sleep"
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      inputs:
        parameters:
        - name: SLEEP_TIME_SEC
          value: '{{workflow.parameters.SLEEP_TIME_SEC}}'
    ttlStrategy:
      secondsAfterCompletion: 180
      secondsAfterFailure: 3600
      secondsAfterSuccess: 180
```

### Logs from the workflow controller

```text
...
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.424Z" level=info msg="Workflow update successful" namespace=argo-test-01 phase=Running resourceVersion=1672939709 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3001149299
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-960565807
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-987718533
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-346497755
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-599985645
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1998381637
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1184295101
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3119391055
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:16.443Z" level=info msg="queueing pod for cleanup after" action=deletePod after=5s namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3726389037
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:17.626Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-3386732568
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:17.750Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-1747241164
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:18.632Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-4008404964
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:18.643Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-3386732568
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:18.654Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-147858984
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:18.757Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-1747241164
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:19.640Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-2200685416
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:19.650Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-4008404964
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:19.662Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-147858984
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:20.650Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-2200685416
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:20.991Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-599985645/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-599985645
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:20.991Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1998381637/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1998381637
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:20.991Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1184295101/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1184295101
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:20.991Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3119391055/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3119391055
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:20.997Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-599985645
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.001Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3726389037/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3726389037
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.002Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3001149299/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3001149299
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.005Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-960565807/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-960565807
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.005Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-987718533/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-987718533
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.007Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3119391055
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.012Z" level=info msg="cleaning up pod" action=deletePod key=argo-test-01/hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-346497755/deletePod namespace=argo-test-01 podName=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-346497755
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.015Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1998381637
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.022Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1184295101
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.029Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-599985645
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.029Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3119391055
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.029Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1998381637
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.029Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-1184295101
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.029Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3726389037
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.036Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3001149299
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.042Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-960565807
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.048Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-987718533
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.055Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3726389037
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.055Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-3001149299
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.055Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-987718533
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.055Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-960565807
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.055Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-346497755
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.061Z" level=info msg="delete pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-hello-world-346497755
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.659Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-3386732568
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:21.780Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-1747241164
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:23.681Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-4008404964
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:24.679Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-147858984
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.688Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-2200685416
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.891Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1672939709 namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.911Z" level=info msg="Task-result reconciliation" namespace=argo-test-01 numObjs=420 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.923Z" level=info msg="Step group node hello-100-sleep-5-10-7nbs5-jlcc9-2650540567 successful" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.924Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-988256192 are [hello-100-sleep-5-10-7nbs5-jlcc9-988256192]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.924Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-2245360980 are [hello-100-sleep-5-10-7nbs5-jlcc9-2245360980]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.924Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-2065138256 are [hello-100-sleep-5-10-7nbs5-jlcc9-2065138256]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.924Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-1615151468 are [hello-100-sleep-5-10-7nbs5-jlcc9-1615151468]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.924Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-4117964688 are [hello-100-sleep-5-10-7nbs5-jlcc9-4117964688]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
... # similary logs are looped.
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.926Z" level=info msg="Step group node hello-100-sleep-5-10-7nbs5-jlcc9-1644030522 successful" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.926Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-1728522515 are [hello-100-sleep-5-10-7nbs5-jlcc9-1728522515]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.926Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-1067876951 are [hello-100-sleep-5-10-7nbs5-jlcc9-1067876951]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.926Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-3121970123 are [hello-100-sleep-5-10-7nbs5-jlcc9-3121970123]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.926Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-1064762503 are [hello-100-sleep-5-10-7nbs5-jlcc9-1064762503]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.926Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-3139644027 are [hello-100-sleep-5-10-7nbs5-jlcc9-3139644027]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.933Z" level=info msg="Step group node hello-100-sleep-5-10-7nbs5-jlcc9-1644177617 successful" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.934Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-1338515973 are [hello-100-sleep-5-10-7nbs5-jlcc9-1338515973]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.934Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-2978007377 are [hello-100-sleep-5-10-7nbs5-jlcc9-2978007377]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.934Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-689009613 are [hello-100-sleep-5-10-7nbs5-jlcc9-689009613]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.934Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-1695177057 are [hello-100-sleep-5-10-7nbs5-jlcc9-1695177057]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.934Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-3039378653 are [hello-100-sleep-5-10-7nbs5-jlcc9-3039378653]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
... # similary logs are looped.
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.956Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-3373418909 are [hello-100-sleep-5-10-7nbs5-jlcc9-3373418909]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.956Z" level=info msg="SG Outbound nodes of hello-100-sleep-5-10-7nbs5-jlcc9-4065518811 are [hello-100-sleep-5-10-7nbs5-jlcc9-4065518811]" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.957Z" level=info msg="Workflow step group node hello-100-sleep-5-10-7nbs5-jlcc9-2651673400 not yet completed" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.957Z" level=info msg="TaskSet Reconciliation" namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:25.957Z" level=info msg=reconcileAgentPod namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:26.039Z" level=info msg="Workflow update successful" namespace=argo-test-01 phase=Running resourceVersion=1672940155 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:32.859Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-1747241164
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:33.747Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-3386732568
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:34.755Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-3386732568
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:34.766Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-4008404964
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:34.868Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-1747241164
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:35.770Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-147858984
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:35.909Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-3386732568
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:35.999Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-1747241164
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:36.773Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-2200685416
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:36.787Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-4008404964
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:37.785Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-147858984
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:37.910Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-4008404964
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:38.788Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-2200685416
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:38.933Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-147858984
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:39.925Z" level=info msg="update pod event" pod=hello-100-sleep-5-10-7nbs5-jlcc9-sleep-2200685416
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:42.867Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1672940155 namespace=argo-test-01 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
workflow-controller-ccd976454-47wps workflow-controller time="2025-09-25T03:16:42.886Z" level=info msg="Task-result reconciliation" namespace=argo-test-01 numObjs=420 workflow=hello-100-sleep-5-10-7nbs5-jlcc9
# No relevant logs for hello-100-sleep-5-10-7nbs5-jlcc9 after this point.
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by isubasinghe**
Fixes #14904 

### Motivation

This function call is exponentially recursive and is therefore quite expensive on large step workflows.

### Modifications

Simple, I just added a caching mechanism when calling `childrenFulfilled`.

### Verification

Existing unit tests

### Documentation
N/A

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -2573,23 +2573,40 @@ func (woc *wfOperationCtx) hasDaemonNodes() bool {
...
 		return node.Fulfilled()
 	}
+
 	for _, childID := range node.Children {
 		childNode, err := woc.wf.Status.Nodes.Get(childID)
 		if err != nil {
 			continue
 		}
-		if !woc.childrenFulfilled(childNode) {
+		callResult := woc.childrenFulfilledHelper(childNode, cache)
```
Comment (Joibel) [inline workflow/controller/operator.go]: `callResult` is a terrible name for a variable

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -2573,23 +2573,40 @@ func (woc *wfOperationCtx) hasDaemonNodes() bool {
...
 			return false
 		}
 	}
+
+	cache[node.ID] = true
 	return true
 }
 
+// check if all of the nodes children are fulffilled
+func (woc *wfOperationCtx) childrenFulfilled(node *wfv1.NodeStatus) bool {
```
Comment (Joibel) [inline workflow/controller/operator.go:2605]: The separation here between the functions feels weird, but I think I follow that we can't make it better. Not expecting you to change anything for this comment.
