### PR TITLE
fix: constraint containerType outboundnode boundary. Fixes #12997

### LINKED ISSUE #12997: Complex DAG of container set nodes always failed
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

A complex workflow has below structure.
1. The outermost layer of the workflow is a dag. 
2. The dag dependencies are quite complicated. (40+ nodes and several nodes have more than 5 dependencies)
3. Each dag node is a container set.
4. Each container set has a simple DAG. (prepare-inputs -> main -> prepare-outputs)

The workflow below failed every time. When I changed the inner dag from containers to dag or step groups, it would succeed.

**Expectation**: Container sets works well as dag/step groups when it is used as node nested in the complex workflow.
**What happened**: 
- The workflows failed with error info below.
  ```bash
  &{0x3a297a0 map[namespace:pipeline workflow:pipeline-test-point-simplefied-g5gbq] 2024-04-30 03:46:14.425189512 +0000 UTC m=+158960.631405283 panic <nil> was unable to obtain node for pipeline-test-point-simplefied-g5gbq-2664608158 <nil> <nil> }
  ```
- The DAG showed in GUI was wrong with an invalid dependencies tree. For example, `I` and `J` has the same dependencies but they were connected as if `J` depended on `I`, as below.
  image
    - So far as I tested, DAGs showed in the Argo GUI were wrong even for some very simple container set. I suspected that if the crash were some how connected to such wrong DAG behavior.

### Version

latest (3.5.6)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pipeline-test-point-simplefied
spec:
  entrypoint: pipeline
  activeDeadlineSeconds: 172800
  arguments:
    parameters:
    - name: runNums
      value: '["006"]'
  templates:
  - name: whalesay # name of the template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
      resources: # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
  - name: whalesay-step-groups
    steps:
    - - name: prepare-inputs
        template: whalesay
    - - name: main
        template: whalesay
    - - name: prepare-outputs
        template: whalesay
  - name: whalesay-dag
    dag:
      tasks:
      - name: prepare-inputs
        template: whalesay
      - name: main
        depends: prepare-inputs
        template: whalesay
      - name: prepare-outputs
        depends: main
        template: whalesay
  - name: whalesay-container-set # name of the template
    containerSet:
      containers:
      - name: prepare-inputs
        image: docker/whalesay
        command: [cowsay]
        args: ["hello world"]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
      - name: main
        dependencies:
        - prepare-inputs
        image: docker/whalesay
        command: [cowsay]
        args: ["hello world"]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
      - name: prepare-outputs
        dependencies:
        - main
        image: docker/whalesay
        command: [cowsay]
        args: ["hello world"]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
  - name: pipeline
    dag:
      tasks:
      - name: A
        template: whalesay-container-set
      - name: B
        depends: A.Succeeded
        template: whalesay-container-set
      - name: C
        depends: B.Succeeded
        when: 'false'
        template: whalesay-container-set
      - name: D
        depends: C.Succeeded
        template: whalesay-container-set
      - name: E
        depends: D.Succeeded
        template: whalesay-container-set
      - name: F
        depends: D.Succeeded
        template: whalesay-container-set
      - name: G
        depends: E.Succeeded && F.Succeeded
        template: whalesay-container-set
      - name: H
        depends: A.Succeeded && G.Omitted
        template: whalesay-container-set
      - name: I
        depends: H.Succeeded
        template: whalesay-container-set
      - name: J
        depends: H.Succeeded
        template: whalesay-container-set
      - name: K
        depends: A.Succeeded && G.Omitted
        template: whalesay-container-set
      - name: L
        depends: B.Succeeded
        template: whalesay-container-set
      - name: M
        depends: B.Succeeded
        template: whalesay-container-set
      - name: N1
        depends: M.Succeeded && G.Omitted
        template: whalesay-container-set
      - name: O
        depends: N1.Succeeded
        template: whalesay-container-set
      - name: P
        depends: O.Succeeded
        template: whalesay-container-set
      - name: Q
        depends: O.Succeeded
        template: whalesay-container-set
        withParam: '{{workflow.parameters.runNums}}'
      - name: R
        depends: O.Succeeded
        template: whalesay-container-set
      - name: T
        depends: R.Succeeded
        template: whalesay-container-set
      - name: S
        depends: O.Succeeded
        template: whalesay-container-set
      - name: U
        depends: O.Succeeded
        template: whalesay-container-set
      - name: V
        depends: O.Succeeded
        template: whalesay-container-set
      - name: W
        depends: M.Succeeded && G.Omitted
        template: whalesay-container-set
      - name: X
        depends: Q.Succeeded
        template: whalesay-container-set
      - name: Y1
        depends: A.Succeeded && G.Omitted
        template: whalesay-container-set
      - name: Z
        depends: Y1.Succeeded && Q.Succeeded && R.Succeeded && V.Succeeded && U.Succeeded && S.Succeeded
        template: whalesay-container-set
      ### SSR
      - name: SSR-A
        depends: A.Succeeded
        template: whalesay-container-set
      - name: SSR-B
        depends: I.Succeeded && J.Succeeded
        template: whalesay-container-set

      - name: SSR-C
        depends: O.Succeeded
        template: whalesay-container-set
      - name: SSR-D
        depends: P.Succeeded
        template: whalesay-container-set
      - name: SSR-E
        depends: P.Succeeded
        template: whalesay-container-set
      - name: SSR-F
        depends: P.Succeeded
        template: whalesay-container-set
      - name: SSR-G
        depends: I.Succeeded && R.Succeeded
        template: whalesay-container-set
      - name: SSR-H
        depends: I.Succeeded && V.Succeeded
        template: whalesay-container-set
      - name: SSR-I
        depends: I.Succeeded && S.Succeeded
        template: whalesay-container-set
      - name: SSR-J
        depends: I.Succeeded && R.Succeeded
        template: whalesay-container-set
      - name: SSR-K
        depends: I.Succeeded && V.Succeeded
        template: whalesay-container-set
      - name: SSR-L
        depends: I.Succeeded && S.Succeeded
        template: whalesay-container-set
      - name: SSR-M
        depends: W.Succeeded
        template: whalesay-container-set
      - name: SSR-N
        depends: W.Succeeded
        template: whalesay-container-set
      - name: SSR-O
        depends: I.Succeeded && Z.Succeeded
        template: whalesay-container-set
      - name: SSR-P
        depends: I.Succeeded && Z.Succeeded
        template: whalesay-container-set
      - name: SSR-Q
        depends: I.Succeeded && Z.Succeeded
        template: whalesay-container-set
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by tczhao**
Fixes #12997

### Motivation

Root cause:
say we have dag
```
task: A(containerset)
task: B(containerset), depends: A
task: C(containerset), depends: A
```

if task B is processed and started before the controller can process C,
C will find the deepest node in A without considering boundaries and mistakenly attach to B

### Modifications

if a node(containerType) child node do not have the same boundyID, we return the current node as the deepest outbound node.

### Verification

Tested:
Before code change
- ran the workflow from the issue ticket, failed: incorrect dependency and controller panic
- ran new unit test without change, failed as expected

After code change
- ran the workflow from the issue ticket, succeeded with the correct dependencies
- ran unit test with the code change, succeed

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -2854,7 +2854,16 @@ func (woc *wfOperationCtx) getOutboundNodes(nodeID string) []string {
 		}
 		outboundNodes := make([]string, 0)
 		for _, child := range node.Children {
-			outboundNodes = append(outboundNodes, woc.getOutboundNodes(child)...)
+			childNode, err := woc.wf.Status.Nodes.Get(child)
```
Comment (Joibel) [inline workflow/controller/operator.go:2857]: Why not put all this new logic inside `getOutboundNodes()` - keep that the definitive source of outbound nodes rather than some answers to that question coming from here.

Comment (tczhao) [reply workflow/controller/operator.go:2857]: hmm, this code change is inside the `getOutboundNodes` function.
There containerType is missing handler for containerset situation causing it to find the wrong node

Comment (Joibel) [reply workflow/controller/operator.go:2857]: Yes. I forgot this recursed and just assumed it didn't.

**Review by Joibel — APPROVED** [review]

**Comment by agilgur5** [comment]
Merging as this has been approved and has no conflicts & passes tests.
