### PR TITLE
fix: don't clean up old offloaded records during save. Fixes: #13220

### LINKED ISSUE #13220: Stop a workflow during offload causes `upper: no more rows in this result set`
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When the workflow updates the nodestatus to the database and deletes the old records, if someone stops the workflow during the update, a conflict will occur. However, reapply cannot parse woc.orig at this time, resulting in upper: no more rows in this result set

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Any large workflow
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by shuangkun**
don't clean up old records when save

Fixes #13220

### CODE REVIEW

**Review by imliuda — APPROVED** [review]
We have encoutered the same issue, and the delete operation will cause many dead locks when there are many slow queries. I agree this this change.

File: persist/sqldb/offload_node_status_repo.go [hunk 1]
```diff
@@ -95,27 +95,8 @@ func (wdc *nodeOffloadRepo) Save(uid, namespace string, nodes wfv1.Nodes) (strin
...
-		And(wdc.oldOffload()).
-		Exec()
-	if err != nil {
-		return "", err
-	}
-	rowsAffected, err := rs.RowsAffected()
-	if err != nil {
-		return "", err
-	}
-	logCtx.WithField("rowsAffected", rowsAffected).Debug("Deleted offloaded nodes")
```
Comment (juliev0) [inline persist/sqldb/offload_node_status_repo.go:118]: Makes sense what you're saying. So, I notice that `Save()` can be called in either of [these cases](https://github.com/argoproj/argo-workflows/blob/v3.5.8/workflow/hydrator/hydrator.go#L106). Just want to confirm that the normal deletion method will take care of deleting the old Archived Workflows in either of those cases?

Comment (shuangkun) [reply persist/sqldb/offload_node_status_repo.go:118]: Don‘t take care of. 
We already have a periodic cleanup mechanism, so I think we can remove the cleanup during the save phase, because it does sometimes delete things that should not be deleted.

Comment (juliev0) [reply persist/sqldb/offload_node_status_repo.go:118]: I understand. But I'm just wondering if you tested both of these cases: `if packer.IsTooLargeError(err)` as well as `alwaysOffloadNodeStatus`

Comment (shuangkun) [reply persist/sqldb/offload_node_status_repo.go:118]: Yes, both cases have passed the test.

**Review by juliev0 — APPROVED** [review]
