### PR TITLE
fix(controller): Correct bug for repository ref without default key. Fixes #5646

### LINKED ISSUE #5646: V3.0.1 error upgrading "error getting config map for artifact repository ref"
## Summary 

What happened/what you expected to happen?

Upgraded from 2.12.2 to 3.0.1 Manually with yml files.

## Diagnostics

What Kubernetes provider are you using? 

Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}  

What version of Argo Workflows are you running? 

v3.0.1

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |
    # archiveLogs will archive the main container logs as an artifact
    archiveLogs: true

    s3:
      # Use the corresponding endpoint depending on your S3 provider:
      #   AWS: s3.amazonaws.com
      #   GCS: storage.googleapis.com
      #   Minio: my-minio-endpoint.default:9000
      endpoint: minio:9000
      bucket: my-bucket
      # region: us-west-2
      # insecure will disable TLS. Primarily used for minio installs not configured with TLS
      insecure: true
      # keyFormat is a format pattern to define how artifacts will be organized in a bucket.
      # It can reference workflow metadata variables such as workflow.namespace, workflow.name,
      # pod.name. Can also use strftime formating of workflow.creationTimestamp so that workflow
      # artifacts can be organized by date. If omitted, will use `{{workflow.name}}/{{pod.name}}`,
      # which has potential for have collisions.
      # The following example pattern organizes workflow artifacts under a "my-artifacts" sub dir,
      # then sub dirs for year, month, date and finally workflow name and pod.
      # e.g.: my-artifacts/2018/08/23/my-workflow-abc123/my-workflow-abc123-1234567890
      keyFormat: "my-artifacts\
        /{{workflow.creationTimestamp.Y}}\
        /{{workflow.creationTimestamp.m}}\
        /{{workflow.creationTimestamp.d}}\
        /{{workflow.name}}\
        /{{pod.name}}"
      # The actual secret object (in this example my-s3-credentials), should be created in every
      # namespace where a workflow needs to store its artifacts to S3. If omitted,
      # attempts to use IAM role to access the bucket (instead of accessKey/secretKey).
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
      # If this is set to true, argo workflows will use AWS SDK default credentials provider chain. This will allow things like
      # IRSA and any of the authentication methods that the golang SDK uses in it's default chain.
      useSDKCreds: false
  containerRuntimeExecutor: k8sapi
  # dockerSockPath: /var/someplace/else/docker.sock
  executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.1
        memory: 64Mi
      limits:
        cpu: 0.5
        memory: 512Mi
    # args & env allows command line arguments and environment variables to be appended to the
    # executor container and is mainly used for development/debugging purposes.
    args:
    - --loglevel
    - debug
    - --gloglevel
    - "6"
    env:
    # ARGO_TRACE enables some tracing information for debugging purposes. Currently it enables
    # logging of S3 request/response payloads (including auth headers)
    - name: ARGO_TRACE
      value: "1"
  kubeletInsecure: "false"
  kubeletPort: "10250"
  links: |
    - name: Example Workflow Link
      scope: workflow
      url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
    - name: Example Pod Link
      scope: pod
      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
  metricsConfig: |
    # Enabled controls metric emission. Default is true, set "enabled: false" to turn off
    enabled: true
    # Path is the path where metrics are emitted. Must start with a "/". Default is "/metrics"
    path: /metrics
    # Port is the port where metrics are emitted. Default is "9090"
    port: 9090
    # MetricsTTL sets how often custom metrics are cleared from memory. Default is "0", metrics are never cleared
    metricsTTL: "10m"
    # IgnoreErrors is a flag that instructs prometheus to ignore metric emission errors. Default is "false"
    ignoreErrors: false

    # DEPRECATED: Legacy metrics are now removed, this field is ignored
    disableLegacy: false
  nodeEvents: |
    enabled: true
  parallelism: |
    10
  persistence: |
    connectionPool: 
      maxIdleConns: 100  
      maxOpenConns: 0
      connMaxLifetime: 0s 
    # 0 means connections don't have a max lifetime
    #  if true node status is only saved to the persistence DB to avoid the 1MB limit in etc
    nodeStatusOffLoad: true
    # save completed workloads to the workflow archive\n
    archive: true
    # the number of days to keep archived workflows (the default is forever)\n
    archiveTTL: 180d
    # LabelSelector determines the workflow that matches with the matchlabels or matchrequirements, will be archived.
    # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    #archiveLabelSelector:
    #  matchLabels:
    #     workflows.argoproj.io/archive-strategy: "always"
    # Optional name of the cluster I'm running in. This must be unique for your cluster.
    #clusterName: default 
    postgresql:  
      host: ******.postgres.database.azure.com
      port: 5432
      database: argo
      tableName: argo_workflows
      # the database secrets must be in the same namespace of the controller 
      userNameSecret:    
        name: argo-postgres-config  
        key: username
      passwordSecret:    
        name: argo-postgres-config
        key: password 
      ssl: true
      # sslMode must be one of: disable, require, verify-ca, verify-full
      # you can find more information about those ssl options here: https://godoc.org/github.com/lib/pq  
      sslMode: require
    # Optional config for mysql:
    # mysql:
    #   host: localhost
    #   port: 3306
    #   database: argo
    #   tableName: argo_workflows
    #   userNameSecret:
    #     name: argo-mysql-config
    #     key: username
    #   passwordSecret:
    #     name: argo-mysql-config
    #     key: password
  sso: |
    # This is the root URL of the OIDC provider (required).
    issuer: https://login.microsoftonline.com/faac6158-54db-403b-83f5-b453fcdad8cc/v2.0
    # This is name of the secret and the key in it that contain OIDC client
    # ID issued to the application by the provider (required).
    clientId:
      name: argo-client-secret
      key: clientId
    # This is name of the secret and the key in it that contain OIDC client
    # secret issued to the application by the provider (required).
    clientSecret:
      name: argo-client-secret
      key: clientSecret
    # This is the redirect URL supplied to the provider (required). It must
    # be in the form <argo-server-root-url>/oauth2/callback. It must be
    # browser-accessible.
    redirectUrl: https://argo.aspeninsights.com/oauth2/callback
    # Additional scopes to request. Typically needed for SSO RBAC. >= v2.12
    scopes:
     - email
    # RBAC Config. >= v2.12
    rbac:
      enabled: false
  telemetryConfig: |
    enabled: false
    path: /telemetry
    port: 8080
  workflowDefaults: |
    metadata:
      annotations:
        argo: workflows
    spec:
      ttlStrategy:
        secondsAfterSuccess: 5
      parallelism: 3
  workflowRequirements: |
    referenceOnly: false
```

```
Paste the logs from the workflow controller:
time="2021-04-09T23:03:22.864Z" level=info msg="Updated message  -> failed to resolve artifact repository: error getting config map for artifact repository ref \"argo/#\": config map missing key argo/# for artifact repository ref \"\"" namespace=argo workflow=**REDACTED**
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Fixes #5646

### CODE REVIEW

File: workflow/artifactrepositories/artifactrepositories.go [hunk 1]
```diff
@@ -52,7 +53,7 @@ func (s *artifactRepositories) Resolve(ctx context.Context, ref *wfv1.ArtifactRe
 	}
 	for _, r := range refs {
 		resolvedRef, _, err := s.get(ctx, r)
-		if apierr.IsNotFound(err) {
+		if err != nil && (apierr.IsNotFound(err) || strings.Contains(err.Error(), "config map missing key")) {
```
Comment (terrytangyuan) [inline workflow/artifactrepositories/artifactrepositories.go:56]: Move this string to a constant so it can be reused by `get()` when emitting this error?

**Comment by alexec** [comment]
@sarabala1979 bump.

**Review by sarabala1979 — APPROVED** [review]
