### PR TITLE
fix(ui): Use proper podname for containersets. Fixes #13038

### LINKED ISSUE #13038: UI: Containerset nodes receive the wrong podname
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When trying to get the logs for a (any) containerset container in the UI, the user is faced with a blank page. 
image
This is due to the podname being incorrectly calculated for these nodes, which makes the request to the backend return an empty response.

Expected behavior would be to be able to view the logs in similar fashion as for pod nodes.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: graph-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This workflow demonstrates running a graph of tasks within containers in a single pod.
    workflows.argoproj.io/version: ">= 3.1.0"
spec:
  entrypoint: main
  templates:
    - name: main
      containerSet:
        containers:
          - name: a
            image: argoproj/argosay:v2
          - name: b
            image: argoproj/argosay:v2
            dependencies: ["a"]
          - name: c
            image: argoproj/argosay:v2
            dependencies: ["a"]
          - name: d
            image: argoproj/argosay:v2
            dependencies: ["b", "c"]
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by instauro**
Fixes #13038 
### Motivation

Containerset nodes currently do not retrieve their logs in the UI. This is due to the podname calculation failing, which makes the request to the backend incorrect. This fix will hopefully become obsolete when https://github.com/argoproj/argo-workflows/issues/12528 is fixed, but until then this should do the trick.

### Modifications

Uses a better podname when the node type is `Container`.
image
image

### Verification

Tried a few different containerset templates to verify the fix, and a few none-containetset templates to verify that there is no regression.

### CODE REVIEW

File: ui/src/app/shared/pod-name.ts [hunk 1]
```diff
@@ -19,7 +19,8 @@ export function getPodName(workflow: Workflow, node: NodeStatus): string {
     }
 
     const workflowName = workflow.metadata.name;
-    if (workflowName === node.name) {
+    const podNodeName = node.type == 'Container' ? node.name.replace(/\.[^/.]+$/, '') : node.name;
```
Comment (agilgur5) [inline ui/src/app/shared/pod-name.ts:22]: hmm this doesn't seem to match [the back-end](https://github.com/argoproj/argo-workflows/blob/0c1398ea6fa66cc77156f15a6d69c260c6b524da/workflow/util/pod_name.go#L51). these two functions should be equivalent per the comment on line 14 in this file

Comment (instauro) [reply ui/src/app/shared/pod-name.ts]: Sure, reverted the change and moved it outside the function call. Maybe there are still better ways to do this

Comment (agilgur5) [reply ui/src/app/shared/pod-name.ts]: It would be great if you could locate where in the back-end this gets set, that way we can keep them equivalent, whether in this function or elsewhere.

Comment (instauro) [reply ui/src/app/shared/pod-name.ts]: Looks like the pod is created based on the pod node name.
https://github.com/argoproj/argo-workflows/blob/main/workflow/controller/container_set_template.go#L20-L24

Then the containerset nodes are created
https://github.com/argoproj/argo-workflows/blob/main/workflow/controller/container_set_template.go#L31-L46
Where the container node names are just their pod node name concatenated with the container name.
```go
ctxNodeName := fmt.Sprintf("%s.%s", nodeName, c.Name)
```
So removing this postfix should map from containerset node name to pod node name, which can be used to calculate the pod name using the existing function.

Comment (agilgur5) [reply ui/src/app/shared/pod-name.ts]: Yea it looks like ContainerSet node -> Pod node name never happens directly in the back-end, which explains why they're not equivalent.

In that case, I'd prefer your earlier variant, since I intentionally consolidated `getPodName` in #12964.
Let's just leave a comment on why this block differs from the back-end then for explicitness

Comment (agilgur5) [reply ui/src/app/shared/pod-name.ts:24]: Reverted it back to the old variant and added some comments in https://github.com/argoproj/argo-workflows/pull/13039/commits/39c44cb3e7c78a43fa47413f0f94a910dfa7d935

GH PRs still don't record _all_ versions of amended commits (unlike Gerrit which has had this for at least a decade if not more 😕), but I remembered the new GH activity feed existed and was able to [find it there](https://github.com/instauro/argo-workflows/activity?ref=fix/containerset-podname).

**Review by agilgur5 — APPROVED** [review]
Made the revert myself plus added comments per https://github.com/argoproj/argo-workflows/pull/13039#discussion_r1650211514, so LGTM now

Thanks for root causing and fixing this!
