### PR TITLE
fix: nodeAntiAffinity is not working as expected when boundaryID is empty. Fixes: #9193

### LINKED ISSUE #9193: `retryStrategy` with `nodeAntiAffinity` is not working as expected.
## Summary

What happened/what you expected to happen?

I wanted to use `retryStrategy` with `nodeAntiAffinity` in order to prevent retrials from running on the same hosts. I was using the following small workflow for testing, but what happens is all retrials were started on the same host (node).
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: random-fail-
spec:
  entrypoint: random
  templates:
  - name: random
    retryStrategy:
      limit: 10
      retryPolicy: "Always"
      affinity:
        nodeAntiAffinity: {}
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        import time
        random.seed(time.time())
        i = random.randint(0, 10)
        print(i)
        exit(i)`
```
Not sure if this is an expected behavior and in my case i should use `RetryNodeAntiAffinity` which is, as mentioned in the documentation, is a placeholder for future expansion.

What version are you running?
Tested with v3.2.9 and v3.3.3

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by shuangkun**
Fixes #9193

### Motivation

The root cause is the workflow's boundaryID is empty. So did't find the retry node to fetch the HostNodeName. 
So I want to find the retry node and fetch the HostNodeName as the new pod‘s nodeAntiAffinity.

### Modifications

Find the correct retrynode when boundaryID is empty.

### Verification

e2e tests  and ut

### CODE REVIEW

File: workflow/controller/retry_tweak.go [hunk 1]
```diff
@@ -14,6 +14,13 @@ type RetryTweak = func(retryStrategy wfv1.RetryStrategy, nodes wfv1.Nodes, pod *
 // FindRetryNode locates the closes retry node ancestor to nodeID
 func FindRetryNode(nodes wfv1.Nodes, nodeID string) *wfv1.NodeStatus {
 	boundaryID := nodes[nodeID].BoundaryID
+	if boundaryID == "" {
+		for _, node := range nodes {
```
Comment (terrytangyuan) [inline workflow/controller/retry_tweak.go:18]: This is yet another loop. Can we somehow combine it with the loop below?

Comment (shuangkun) [reply workflow/controller/retry_tweak.go]: modifid, please take a look, thanks!

File: test/e2e/retry_test.go [hunk 2]
```diff
@@ -194,6 +194,45 @@ spec:
...
+			if status.Phase == wfv1.WorkflowFailed {
+				nodeStatus := status.Nodes.FindByDisplayName("test-nodeantiaffinity-strategy(0)")
+				nodeStatusRetry := status.Nodes.FindByDisplayName("test-nodeantiaffinity-strategy(1)")
+				assert.NotEqual(t, nodeStatus.HostNodeName, nodeStatusRetry.HostNodeName)
+			}
+			if status.Phase == wfv1.WorkflowRunning {
+				nodeStatus := status.Nodes.FindByDisplayName("test-nodeantiaffinity-strategy(0)")
+				nodeStatusRetry := status.Nodes.FindByDisplayName("test-nodeantiaffinity-strategy(1)")
+				assert.Contains(t, nodeStatusRetry.Message, "1 node(s) didn't match Pod's node affinity/selector")
+				assert.NotEqual(t, nodeStatus.HostNodeName, nodeStatusRetry.HostNodeName)
```
Comment (tczhao) [inline test/e2e/retry_test.go:231]: with these assertions tests,
I think we could wait for workflow completed then the check phase Failed.
instead of wait 5sec have a chance of the workflow still running or failed.

What do you think?

File: workflow/controller/operator_test.go [hunk 3]
```diff
@@ -7575,6 +7575,112 @@ func TestRetryOnDiffHost(t *testing.T) {
...
+    script:
+      image: python:alpine3.6
+      command: [python]
+      source: |
+        import random
+        import time
+        random.seed(time.time())
+        i = random.randint(1, 10)
+        print(i)
+        exit(i)
```
Comment (tczhao) [inline workflow/controller/operator_test.go:7601]: like the e2e test, we can shorten by just using exit, right?

**Review by terrytangyuan — APPROVED** [review]
