### PR TITLE
fix: Daemon step in running state, but dependents don't start

### LINKED ISSUE #6379: v3.2.4 Daemon step in running state, but dependents don't start
On `latest`, my workflow consistently gets stuck while progressing on a daemon step that has successfully started. Works fine on 3.1.2.

* [Workflow controller log](https://gist.github.com/atombender/a6235070181a77a091070afa8f548c9b)
* [Output of `kubectl describe pod` for stuck pod](https://gist.github.com/atombender/c704ff3e82f6c3c32baea7dddbdded2f)
* [Workflow YAML](https://gist.github.com/atombender/82d78abef7ca94ce620d0b4e91d36057) (slightly censored)

Eventually, it fails with "Pod was active on the node longer than the specified deadline", and the workflow fails.

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>
closes #6379 
Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -2038,6 +2038,21 @@ func (woc *wfOperationCtx) findTemplate(pod *apiv1.Pod) *wfv1.Template {
...
 		return nil // I don't expect this to happen in production, just in tests
 	}
+	return woc.GetNodeTemplate(node)
+}
+
+func (woc *wfOperationCtx) GetNodeTemplate(node *wfv1.NodeStatus) *wfv1.Template {
+	if node.TemplateRef != nil {
+		tmplCtx, err := woc.createTemplateContext(node.GetTemplateScope())
+		if err != nil {
+			woc.markNodePhase(node.Name, wfv1.NodeError, "Failed to create Template context", err.Error())
```
Comment (alexec) [inline workflow/controller/operator.go:2048]: I think you can use `woc.markNodeError`? If not, maybe we should add that func.

**Review by alexec — APPROVED** [review]
one minor suggestion

**Review by terrytangyuan — APPROVED** [review]
