### PR TITLE
fix(controller): Delete the PVCs in workflowtemplateRef

### LINKED ISSUE #6469: volumeClaimGC stategy not applied for workflows created from Worfklow Templates
## Summary 
For Workflow Templates defined with volumeClaimGC - strategy = OnWorkflowCompletion, the volumes are NOT being deleted when the workflow fails.

I expected that: 
For workflow templates with volumeClaimGC-strategy=OnWorkflowCompletion, the volumes would be deleted when the generated workflows failed.

What happened is that: 
The volumes are NOT deleted when the generated workflows fail.  

However:
1. The volumes are always deleted when the generated workflows are successful.  This makes me think that the volumeClaimGC strategy is defaulting to OnWorkflowSuccess, and the volumeClaimGC setting in workflow templates is not overriding that default.
2. If I change my workflow template to be a workflow and submit it, it does delete the volumes, even when the workflow fails.

## Diagnostics

What Kubernetes provider are you using? 
GKE Anthos on VMWare v1.7.1-gke.4

What version of Argo Workflows are you running? 
v3.0.2

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
K8SAPI

Did this work in a previous version? I.e. is it a regression?
I am NOT sure.  It may have worked in a previous version.  But, I'm not sure we tested for this specifically.

```bash
# Workflow Template with this issue:
`apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-eric
  namespace: argo-flows
spec:
  volumeClaimGC:
    strategy: OnWorkflowCompletion
  podGC:
    strategy: OnWorkflowCompletion
  entrypoint: volumes-pvc-example
  volumeClaimTemplates:                 
  - metadata:
      name: workdir                     
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi                  

  templates:
  - name: volumes-pvc-example
    steps:
    - - name: write
        template: write-message
    - - name: print
        template: print-message

  - name: write-message
    container:
      image: alpine:3.14.0
      command: [sh, -c]
      args: ["echo hello world | tee /mnt/vol/hello_world.txt"]      
      volumeMounts:                     
      - name: workdir
        mountPath: /mnt/vol

  - name: print-message
    container:
      image: alpine:3.14.0
      command: [sh, -c]
      args: ["echo getting message from volume; find /mnt/vol; cat /mnt/vol/hello_world.txt; exit 125"]
      volumeMounts:                     
      - name: workdir
        mountPath: /mnt/vol`

# Logs from the workflow controller:
time="2021-08-02T20:41:35.501Z" level=info msg="Processing workflow" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:35.506Z" level=info msg="Updated phase  -> Running" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:35.514Z" level=info msg="Creating pvc workflow-template-eric-5svxd-workdir" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:35.524Z" level=info msg="Steps node workflow-template-eric-5svxd initialized Running" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:35.524Z" level=info msg="StepGroup node workflow-template-eric-5svxd-3186688898 initialized Running" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:35.524Z" level=info msg="Pod node workflow-template-eric-5svxd-3056121651 initialized Pending" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:35.531Z" level=info msg="Created pod: workflow-template-eric-5svxd[0].write (workflow-template-eric-5svxd-3056121651)" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:35.531Z" level=info msg="Workflow step group node workflow-template-eric-5svxd-3186688898 not yet completed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:35.542Z" level=info msg="Workflow update successful" namespace=argo-flows phase=Running resourceVersion=304524487 workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:45.502Z" level=info msg="Processing workflow" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:45.506Z" level=info msg="Setting node workflow-template-eric-5svxd-3056121651 outputs" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:45.506Z" level=info msg="Updating node workflow-template-eric-5svxd-3056121651 status Pending -> Running" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:45.507Z" level=info msg="Workflow step group node workflow-template-eric-5svxd-3186688898 not yet completed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:45.524Z" level=info msg="Workflow update successful" namespace=argo-flows phase=Running resourceVersion=304524631 workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.525Z" level=info msg="Processing workflow" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.525Z" level=info msg="Updating node workflow-template-eric-5svxd-3056121651 status Running -> Succeeded" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.525Z" level=info msg="Step group node workflow-template-eric-5svxd-3186688898 successful" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.525Z" level=info msg="node workflow-template-eric-5svxd-3186688898 phase Running -> Succeeded" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.525Z" level=info msg="node workflow-template-eric-5svxd-3186688898 finished: 2021-08-02 20:41:55.52599334 +0000 UTC" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.526Z" level=info msg="StepGroup node workflow-template-eric-5svxd-2045663711 initialized Running" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.526Z" level=info msg="SG Outbound nodes of workflow-template-eric-5svxd-3056121651 are [workflow-template-eric-5svxd-3056121651]" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.526Z" level=info msg="Pod node workflow-template-eric-5svxd-2684117538 initialized Pending" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.539Z" level=info msg="Created pod: workflow-template-eric-5svxd[1].print (workflow-template-eric-5svxd-2684117538)" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.539Z" level=info msg="Workflow step group node workflow-template-eric-5svxd-2045663711 not yet completed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:41:55.552Z" level=info msg="Workflow update successful" namespace=argo-flows phase=Running resourceVersion=304524769 workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:05.540Z" level=info msg="Processing workflow" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:05.540Z" level=info msg="Updating node workflow-template-eric-5svxd-2684117538 message: ContainerCreating" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:05.540Z" level=info msg="SG Outbound nodes of workflow-template-eric-5svxd-3056121651 are [workflow-template-eric-5svxd-3056121651]" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:05.540Z" level=info msg="Workflow step group node workflow-template-eric-5svxd-2045663711 not yet completed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:05.556Z" level=info msg="Workflow update successful" namespace=argo-flows phase=Running resourceVersion=304524899 workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.557Z" level=info msg="Processing workflow" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.557Z" level=info msg="Pod failed: Error (exit code 125)" displayName=print namespace=argo-flows pod=workflow-template-eric-5svxd-2684117538 templateName=print-message workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.557Z" level=info msg="Setting node workflow-template-eric-5svxd-2684117538 outputs" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.557Z" level=info msg="Updating node workflow-template-eric-5svxd-2684117538 status Pending -> Failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.557Z" level=info msg="Updating node workflow-template-eric-5svxd-2684117538 message: Error (exit code 125)" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.557Z" level=info msg="SG Outbound nodes of workflow-template-eric-5svxd-3056121651 are [workflow-template-eric-5svxd-3056121651]" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="Step group node workflow-template-eric-5svxd-2045663711 deemed failed: child 'workflow-template-eric-5svxd-2684117538' failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="node workflow-template-eric-5svxd-2045663711 phase Running -> Failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="node workflow-template-eric-5svxd-2045663711 message: child 'workflow-template-eric-5svxd-2684117538' failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="node workflow-template-eric-5svxd-2045663711 finished: 2021-08-02 20:42:15.558153711 +0000 UTC" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="step group workflow-template-eric-5svxd-2045663711 was unsuccessful: child 'workflow-template-eric-5svxd-2684117538' failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="Outbound nodes of workflow-template-eric-5svxd-2684117538 is [workflow-template-eric-5svxd-2684117538]" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="Outbound nodes of workflow-template-eric-5svxd is [workflow-template-eric-5svxd-2684117538]" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="node workflow-template-eric-5svxd phase Running -> Failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="node workflow-template-eric-5svxd message: child 'workflow-template-eric-5svxd-2684117538' failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="node workflow-template-eric-5svxd finished: 2021-08-02 20:42:15.558287116 +0000 UTC" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="Checking daemoned children of workflow-template-eric-5svxd" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="Updated phase Running -> Failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="Updated message  -> child 'workflow-template-eric-5svxd-2684117538' failed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="Marking workflow completed" namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.558Z" level=info msg="Checking daemoned children of " namespace=argo-flows workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.578Z" level=info msg="Workflow update successful" namespace=argo-flows phase=Failed resourceVersion=304525037 workflow=workflow-template-eric-5svxd
time="2021-08-02T20:42:15.586Z" level=info msg="cleaning up pod" action=deletePod key=argo-flows/workflow-template-eric-5svxd-2684117538/deletePod
time="2021-08-02T20:42:15.586Z" level=info msg="cleaning up pod" action=deletePod key=argo-flows/workflow-template-eric-5svxd-3056121651/deletePod
time="2021-08-02T20:42:25.598Z" level=info msg="Workflow processing has been postponed due to max parallelism limit" key=argo-flows/workflow-template-eric-5svxd



```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>
closes #6469 
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1462,7 +1462,7 @@ func (woc *wfOperationCtx) createPVCs(ctx context.Context) error {
 }
 
 func (woc *wfOperationCtx) deletePVCs(ctx context.Context) error {
-	gcStrategy := woc.wf.Spec.GetVolumeClaimGC().GetStrategy()
+	gcStrategy := woc.execWf.Spec.GetVolumeClaimGC().GetStrategy()
```
Comment (sarabala1979) [inline workflow/controller/operator.go:1465]: this is the last place was missing

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Review by alexec — APPROVED** [review]
