### PR TITLE
fix: Permit enums w/o values. Fixes #11471.

### LINKED ISSUE #11471: Argo CLI: Lint: Enums can't have default in WorkflowTemplate
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

This appears to be a variation of #6044.

When creating a WorkflowTemplate I would expect that I can define an `enum` parameter that also provides a `default` matching one of the enum values if no value was provided when the `WorkflowTemplate` becomes an actual `Workflow`. This does not appear to be the case. When I attempt to `argo lint` this I get the following error:

```
in "value-bug-example" (WorkflowTemplate): rpc error: code = InvalidArgument desc = spec.arguments.test-parameter.value is required
```

### Version

v3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: value-bug-example

spec:
  arguments:
    parameters:
      - name: test-parameter
        enum: ['hello', 'goodbye']
        default: 'hello'

  templates:
    - name: test
      script:
        image: ubuntu
        source: echo {{workflow.parameters.test-parameter}}
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

### PR DESCRIPTION
**Pull request by farmdawgnation**
Fixes #11471 

### Motivation

As described in the above issue, it's currently pretty impossible to use `enum` fields and have `lint` pass. This makes them effectively useless in workflow templates.

### Modifications

Updated the enum checks in the validate code in order to respect `allowEmptyValues`.

### Verification

Updated unit tests and tweaked code until they passed as expected.

### CODE REVIEW

File: workflow/validate/validate.go [hunk 1]
```diff
@@ -865,8 +865,10 @@ func validateArgumentsValues(prefix string, arguments wfv1.Arguments, allowEmpty
 			if len(param.Enum) == 0 {
 				return errors.Errorf(errors.CodeBadRequest, "%s%s.enum should contain at least one value", prefix, param.Name)
 			}
-			if param.Value == nil {
+			if param.Value == nil && !allowEmptyValues {
```
Comment (Joibel) [inline workflow/validate/validate.go:868]: I think this would read easier as:
```go
if param.Value == nil {
  if allowEmptyValues {
    return nil
  }
  return errors.Errorf(errors.CodeBadRequest, "%s%s.value is required", prefix, param.Name)
}
```

Comment (farmdawgnation) [reply workflow/validate/validate.go:868]: Sounds good, I'll make that change.

**Review by Joibel — APPROVED** [review]
Looks good to me, thank you.

**Comment by farmdawgnation** [comment]
Someone may need to rerun the E2E tests... I don't seem to have permission to do so!

**Comment by Joibel** [comment]
> Someone may need to rerun the E2E tests... I don't seem to have permission to do so!

@Just push an empty commit or something similar to get the CI to re-run

**Review by terrytangyuan — APPROVED** [review]
