### PR TITLE
fix: Fix not working Running state lifecycle hooks in dag task. Fixes #9897

### LINKED ISSUE #9897: lifecycle hooks "Running" state not recognized when trigger by multi stage DAG template
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

This issue was already reported on [ISSUE-8449](https://github.com/argoproj/argo-workflows/issues/8449) but closed without any result.

I want contribute about this issue. so i reopen the ticket about this topic by this issue.

> Problem

lifecycle hooks "Running" state not recognized when trigger by multi stage DAG template.
I expected all each task would have two hook task(`{taskname}.hooks.running`, `{taskname}.hooks.success`),
but only last task work expectly, and other tasks have only `{taskname}.hooks.success`.

image

### Version

v3.4.2 (latest)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
        - name: step-1
          hooks:
            running:
              expression: tasks["step-1"].status == "Running"
              template: hooks
            success:
              expression: tasks["step-1"].status == "Succeeded"
              template: hooks
          template: echo
        - name: step2
          dependencies: [step-1]
          hooks:
            running:
              expression: tasks.step2.status == "Running"
              template: hooks
            success:
              expression: tasks.step2.status == "Succeeded"
              template: hooks
          template: echo
        - name: step3
          dependencies: [step2]
          hooks:
            running:
              expression: tasks.step3.status == "Running"
              template: hooks
            success:
              expression: tasks.step3.status == "Succeeded"
              template: hooks
          template: echo
    
    - name: echo
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was heads\"; sleep 1s"]
    
    - name: hooks
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"this is hook\""]
```

### Logs from the workflow controller

kubectl logs -n argo-workflows deploy/argo-workflows-workflow-controller | grep lifecycle-hook-tmpl-level-lrcmc
```
time="2022-10-24T08:54:53.282Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:54:53.287Z" level=info msg="Updated phase  -> Running" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:54:53.288Z" level=info msg="DAG node lifecycle-hook-tmpl-level-lrcmc initialized Running" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:54:53.288Z" level=info msg="All of node lifecycle-hook-tmpl-level-lrcmc.step-1 dependencies [] completed" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:54:53.288Z" level=info msg="Pod node lifecycle-hook-tmpl-level-lrcmc-2732540164 initialized Pending" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:54:53.329Z" level=info msg="Created pod: lifecycle-hook-tmpl-level-lrcmc.step-1 (lifecycle-hook-tmpl-level-lrcmc-echo-2732540164)" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:54:53.331Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:54:53.331Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:54:53.347Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=856860740 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:03.332Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:03.332Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:03.332Z" level=info msg="node changed" namespace=argo-workflows new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-2732540164 old.message= old.phase=Pending old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:03.333Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:03.333Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:03.349Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=856860970 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.353Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.353Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.353Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-2732540164 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.354Z" level=info msg="Running hooks" hookName=success lifeCycleHook=success namespace=argo-workflows node=lifecycle-hook-tmpl-level-lrcmc.step-1.hooks.success workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.354Z" level=info msg="Pod node lifecycle-hook-tmpl-level-lrcmc-709674995 initialized Pending" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.385Z" level=info msg="Created pod: lifecycle-hook-tmpl-level-lrcmc.step-1.hooks.success (lifecycle-hook-tmpl-level-lrcmc-hooks-709674995)" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.385Z" level=info msg="All of node lifecycle-hook-tmpl-level-lrcmc.step2 dependencies [step-1] completed" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.386Z" level=info msg="Pod node lifecycle-hook-tmpl-level-lrcmc-1575055088 initialized Pending" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.412Z" level=info msg="Created pod: lifecycle-hook-tmpl-level-lrcmc.step2 (lifecycle-hook-tmpl-level-lrcmc-echo-1575055088)" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.412Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.412Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.425Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=856861129 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:13.431Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-workflows/lifecycle-hook-tmpl-level-lrcmc-echo-2732540164/labelPodCompleted
time="2022-10-24T08:55:23.388Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:23.388Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:23.388Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Running new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-1575055088 old.message= old.phase=Pending old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:23.388Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-709674995 old.message= old.phase=Pending old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:23.389Z" level=info msg="Running hooks" hookName=success lifeCycleHook=success namespace=argo-workflows node=lifecycle-hook-tmpl-level-lrcmc.step-1.hooks.success workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:23.389Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:23.389Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:23.403Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=856861373 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:23.410Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-workflows/lifecycle-hook-tmpl-level-lrcmc-hooks-709674995/labelPodCompleted
time="2022-10-24T08:55:33.404Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.404Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.404Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-1575055088 old.message= old.phase=Running old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.405Z" level=info msg="Running hooks" hookName=success lifeCycleHook=success namespace=argo-workflows node=lifecycle-hook-tmpl-level-lrcmc.step2.hooks.success workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.405Z" level=info msg="Pod node lifecycle-hook-tmpl-level-lrcmc-650111839 initialized Pending" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.441Z" level=info msg="Created pod: lifecycle-hook-tmpl-level-lrcmc.step2.hooks.success (lifecycle-hook-tmpl-level-lrcmc-hooks-650111839)" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.442Z" level=info msg="All of node lifecycle-hook-tmpl-level-lrcmc.step3 dependencies [step2] completed" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.442Z" level=info msg="Pod node lifecycle-hook-tmpl-level-lrcmc-1591832707 initialized Pending" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.469Z" level=info msg="Created pod: lifecycle-hook-tmpl-level-lrcmc.step3 (lifecycle-hook-tmpl-level-lrcmc-echo-1591832707)" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.469Z" level=info msg="Running hooks" hookName=running lifeCycleHook=running namespace=argo-workflows node=lifecycle-hook-tmpl-level-lrcmc.step3.hooks.running workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.469Z" level=info msg="Pod node lifecycle-hook-tmpl-level-lrcmc-1462225964 initialized Pending" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.497Z" level=info msg="Created pod: lifecycle-hook-tmpl-level-lrcmc.step3.hooks.running (lifecycle-hook-tmpl-level-lrcmc-hooks-1462225964)" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.497Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.497Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.515Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=856861503 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:33.520Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-workflows/lifecycle-hook-tmpl-level-lrcmc-echo-1575055088/labelPodCompleted
time="2022-10-24T08:55:43.443Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.443Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.443Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-1462225964 old.message= old.phase=Pending old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.443Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-650111839 old.message= old.phase=Pending old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.443Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-1591832707 old.message= old.phase=Pending old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.444Z" level=info msg="Running hooks" hookName=success lifeCycleHook=success namespace=argo-workflows node=lifecycle-hook-tmpl-level-lrcmc.step3.hooks.success workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.444Z" level=info msg="Pod node lifecycle-hook-tmpl-level-lrcmc-1396976624 initialized Pending" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.472Z" level=info msg="Created pod: lifecycle-hook-tmpl-level-lrcmc.step3.hooks.success (lifecycle-hook-tmpl-level-lrcmc-hooks-1396976624)" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.472Z" level=info msg="Running hooks" hookName=running lifeCycleHook=running namespace=argo-workflows node=lifecycle-hook-tmpl-level-lrcmc.step3.hooks.running workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.472Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.472Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.484Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=856861809 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:43.490Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-workflows/lifecycle-hook-tmpl-level-lrcmc-hooks-1462225964/labelPodCompleted
time="2022-10-24T08:55:43.491Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-workflows/lifecycle-hook-tmpl-level-lrcmc-hooks-650111839/labelPodCompleted
time="2022-10-24T08:55:43.491Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-workflows/lifecycle-hook-tmpl-level-lrcmc-echo-1591832707/labelPodCompleted
time="2022-10-24T08:55:53.473Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.473Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.473Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=lifecycle-hook-tmpl-level-lrcmc-1396976624 old.message= old.phase=Pending old.progress=0/1 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="Running hooks" hookName=success lifeCycleHook=success namespace=argo-workflows node=lifecycle-hook-tmpl-level-lrcmc.step3.hooks.success workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="Running hooks" hookName=running lifeCycleHook=running namespace=argo-workflows node=lifecycle-hook-tmpl-level-lrcmc.step3.hooks.running workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="Outbound nodes of lifecycle-hook-tmpl-level-lrcmc set to [lifecycle-hook-tmpl-level-lrcmc-1591832707]" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="node lifecycle-hook-tmpl-level-lrcmc phase Running -> Succeeded" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="node lifecycle-hook-tmpl-level-lrcmc finished: 2022-10-24 08:55:53.474596405 +0000 UTC" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="Checking daemoned children of lifecycle-hook-tmpl-level-lrcmc" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="Marking workflow completed" namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.474Z" level=info msg="Checking daemoned children of " namespace=argo-workflows workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.480Z" level=info msg="cleaning up pod" action=deletePod key=argo-workflows/lifecycle-hook-tmpl-level-lrcmc-1340600742-agent/deletePod
time="2022-10-24T08:55:53.489Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Succeeded resourceVersion=856862058 workflow=lifecycle-hook-tmpl-level-lrcmc
time="2022-10-24T08:55:53.499Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-workflows/lifecycle-hook-tmpl-level-lrcmc-hooks-1396976624/labelPodCompleted
```

### Logs from in your workflow's wait container

kubectl logs -n argo-workflows -c wait -l workflows.argoproj.io/workflow=lifecycle-hook-tmpl-level-lrcmc,workflow.argoproj.io/phase!=Succeeded
```

time="2022-10-24T08:55:37.219Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-10-24T08:55:37.219Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-workflows podName=lifecycle-hook-tmpl-level-lrcmc-hooks-1462225964 template="{\"name\":\"hooks\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"this is hook\\\"\"],\"resources\":{}}}" version="&Version{Version:v3.4.2,BuildDate:2022-10-23T04:49:38Z,GitCommit:c08563baf7bafafe3aeb3284cd3410308603cad4,GitTag:v3.4.2,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
time="2022-10-24T08:55:37.220Z" level=info msg="Starting deadline monitor"
time="2022-10-24T08:55:39.221Z" level=info msg="Main container completed" error="<nil>"
time="2022-10-24T08:55:39.221Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-10-24T08:55:39.221Z" level=info msg="No output parameters"
time="2022-10-24T08:55:39.221Z" level=info msg="No output artifacts"
time="2022-10-24T08:55:39.221Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-24T08:55:39.221Z" level=info msg="Deadline monitor stopped"
time="2022-10-24T08:55:39.221Z" level=info msg="Alloc=6356 TotalAlloc=12104 Sys=18898 NumGC=4 Goroutines=4"
time="2022-10-24T08:55:34.994Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-10-24T08:55:34.994Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-workflows podName=lifecycle-hook-tmpl-level-lrcmc-hooks-650111839 template="{\"name\":\"hooks\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"this is hook\\\"\"],\"resources\":{}}}" version="&Version{Version:v3.4.2,BuildDate:2022-10-23T04:49:38Z,GitCommit:c08563baf7bafafe3aeb3284cd3410308603cad4,GitTag:v3.4.2,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
time="2022-10-24T08:55:34.995Z" level=info msg="Starting deadline monitor"
time="2022-10-24T08:55:36.995Z" level=info msg="Main container completed" error="<nil>"
time="2022-10-24T08:55:36.995Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-10-24T08:55:36.995Z" level=info msg="No output parameters"
time="2022-10-24T08:55:36.995Z" level=info msg="No output artifacts"
time="2022-10-24T08:55:36.995Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-24T08:55:36.995Z" level=info msg="Deadline monitor stopped"
time="2022-10-24T08:55:36.996Z" level=info msg="Alloc=6957 TotalAlloc=12142 Sys=19410 NumGC=4 Goroutines=6"
time="2022-10-24T08:55:17.529Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-10-24T08:55:17.529Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-workflows podName=lifecycle-hook-tmpl-level-lrcmc-hooks-709674995 template="{\"name\":\"hooks\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"this is hook\\\"\"],\"resources\":{}}}" version="&Version{Version:v3.4.2,BuildDate:2022-10-23T04:49:38Z,GitCommit:c08563baf7bafafe3aeb3284cd3410308603cad4,GitTag:v3.4.2,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
time="2022-10-24T08:55:17.529Z" level=info msg="Starting deadline monitor"
time="2022-10-24T08:55:19.529Z" level=info msg="Main container completed" error="<nil>"
time="2022-10-24T08:55:19.529Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-10-24T08:55:19.529Z" level=info msg="No output parameters"
time="2022-10-24T08:55:19.529Z" level=info msg="No output artifacts"
time="2022-10-24T08:55:19.530Z" level=info msg="Deadline monitor stopped"
time="2022-10-24T08:55:19.530Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-24T08:55:19.530Z" level=info msg="Alloc=6290 TotalAlloc=12187 Sys=19410 NumGC=4 Goroutines=5"
time="2022-10-24T08:55:21.886Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-10-24T08:55:21.886Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-workflows podName=lifecycle-hook-tmpl-level-lrcmc-echo-1575055088 template="{\"name\":\"echo\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"it was heads\\\"; sleep 1s\"],\"resources\":{}}}" version="&Version{Version:v3.4.2,BuildDate:2022-10-23T04:49:38Z,GitCommit:c08563baf7bafafe3aeb3284cd3410308603cad4,GitTag:v3.4.2,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
time="2022-10-24T08:55:21.886Z" level=info msg="Starting deadline monitor"
time="2022-10-24T08:55:24.887Z" level=info msg="Main container completed" error="<nil>"
time="2022-10-24T08:55:24.887Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-10-24T08:55:24.887Z" level=info msg="No output parameters"
time="2022-10-24T08:55:24.887Z" level=info msg="No output artifacts"
time="2022-10-24T08:55:24.887Z" level=info msg="Deadline monitor stopped"
time="2022-10-24T08:55:24.887Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-24T08:55:24.887Z" level=info msg="Alloc=6071 TotalAlloc=12141 Sys=19666 NumGC=4 Goroutines=5"
time="2022-10-24T08:55:35.551Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-10-24T08:55:35.551Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-workflows podName=lifecycle-hook-tmpl-level-lrcmc-echo-1591832707 template="{\"name\":\"echo\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"it was heads\\\"; sleep 1s\"],\"resources\":{}}}" version="&Version{Version:v3.4.2,BuildDate:2022-10-23T04:49:38Z,GitCommit:c08563baf7bafafe3aeb3284cd3410308603cad4,GitTag:v3.4.2,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
time="2022-10-24T08:55:35.551Z" level=info msg="Starting deadline monitor"
time="2022-10-24T08:55:38.553Z" level=info msg="Main container completed" error="<nil>"
time="2022-10-24T08:55:38.553Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-10-24T08:55:38.553Z" level=info msg="No output parameters"
time="2022-10-24T08:55:38.553Z" level=info msg="No output artifacts"
time="2022-10-24T08:55:38.553Z" level=info msg="Deadline monitor stopped"
time="2022-10-24T08:55:38.553Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-24T08:55:38.553Z" level=info msg="Alloc=7343 TotalAlloc=12130 Sys=19410 NumGC=3 Goroutines=4"
time="2022-10-24T08:55:03.338Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-10-24T08:55:03.338Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-workflows podName=lifecycle-hook-tmpl-level-lrcmc-echo-2732540164 template="{\"name\":\"echo\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"it was heads\\\"; sleep 1s\"],\"resources\":{}}}" version="&Version{Version:v3.4.2,BuildDate:2022-10-23T04:49:38Z,GitCommit:c08563baf7bafafe3aeb3284cd3410308603cad4,GitTag:v3.4.2,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
time="2022-10-24T08:55:03.338Z" level=info msg="Starting deadline monitor"
time="2022-10-24T08:55:06.338Z" level=info msg="Main container completed" error="<nil>"
time="2022-10-24T08:55:06.338Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-10-24T08:55:06.338Z" level=info msg="No output parameters"
time="2022-10-24T08:55:06.338Z" level=info msg="No output artifacts"
time="2022-10-24T08:55:06.339Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-24T08:55:06.339Z" level=info msg="Deadline monitor stopped"
time="2022-10-24T08:55:06.339Z" level=info msg="Alloc=6023 TotalAlloc=12047 Sys=19410 NumGC=4 Goroutines=6"
time="2022-10-24T08:55:49.252Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-10-24T08:55:49.252Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-workflows podName=lifecycle-hook-tmpl-level-lrcmc-hooks-1396976624 template="{\"name\":\"hooks\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.6\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"this is hook\\\"\"],\"resources\":{}}}" version="&Version{Version:v3.4.2,BuildDate:2022-10-23T04:49:38Z,GitCommit:c08563baf7bafafe3aeb3284cd3410308603cad4,GitTag:v3.4.2,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
time="2022-10-24T08:55:49.252Z" level=info msg="Starting deadline monitor"
time="2022-10-24T08:55:51.253Z" level=info msg="Main container completed" error="<nil>"
time="2022-10-24T08:55:51.253Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-10-24T08:55:51.253Z" level=info msg="No output parameters"
time="2022-10-24T08:55:51.253Z" level=info msg="No output artifacts"
time="2022-10-24T08:55:51.253Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-24T08:55:51.253Z" level=info msg="Deadline monitor stopped"
time="2022-10-24T08:55:51.253Z" level=info msg="Alloc=6253 TotalAlloc=12152 Sys=19154 NumGC=4 Goroutines=7"
```

### PR DESCRIPTION
**Pull request by GeunSam2**
Fixes #9897 

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [x] ~Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.~
* [x] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

**Comment by caelan-io** [comment]
@isubasinghe can you please give a review of this PR next week when you have some available time?

File: workflow/controller/dag.go [hunk 1]
```diff
@@ -358,6 +358,22 @@ func (woc *wfOperationCtx) executeDAGTask(ctx context.Context, dagCtx *dagContex
 
 	node := dagCtx.getTaskNode(taskName)
 	task := dagCtx.GetTask(taskName)
+	if node != nil && (node.Fulfilled() || node.Phase == "Running") {
+		scope, err := woc.buildLocalScopeFromTask(dagCtx, task)
+		if err != nil {
+			woc.markNodeError(node.Name, err)
+		}
+		scope.addParamToScope(fmt.Sprintf("tasks.%s.status", task.Name), string(node.Phase))
```
Comment (isubasinghe) [inline workflow/controller/dag.go:366]: not your mistake, but possible null pointer here. You should log and then return after the markNodeError

**Review by isubasinghe — CHANGES_REQUESTED** [review]

File: workflow/controller/dag.go [hunk 2]
```diff
@@ -358,6 +358,22 @@ func (woc *wfOperationCtx) executeDAGTask(ctx context.Context, dagCtx *dagContex
 
 	node := dagCtx.getTaskNode(taskName)
 	task := dagCtx.GetTask(taskName)
+	if node != nil && (node.Fulfilled() || node.Phase == "Running") {
```
[the remark this answers is not in the document]
Comment (GeunSam2) [reply workflow/controller/dag.go]: I fixed it! 👍

File: workflow/controller/dag.go (hunk 1 above)
Comment (GeunSam2) [reply workflow/controller/dag.go:368]: I moved the code as it was, but I couldn't check that a null pointer could occur. Thank you for the detailed review.

Comment (isubasinghe) [reply workflow/controller/dag.go:368]: Ah so `scope` can be a nil pointer I believe. So in the err != nil branch, just add a log and return. 
This was a bug that was present before your changes though, but its probably fine to make the change here. 
Alternatively I can push something too in a different branch

**Review by isubasinghe — APPROVED** [review]
I've approved your changes.

**Review by alexec — DISMISSED** [review]
Awesome work helping fixing this.

Would you like to add some tests?

**Comment by GeunSam2** [comment]
> Would you like to add some tests?

@alexec  sounds great! i'll try.
by the way. there are very many tests, what kind of test should i look?

**Comment by GeunSam2** [comment]
@alexec 
Hi, I am going to add some test to [e2e/hooks_test.go](https://github.com/argoproj/argo-workflows/blob/master/test/e2e/hooks_test.go)
but there seems to be a problem with the test.

If you allow it, I would like to fix the test in other PRs and add more tests on this issue.

**Comment by terrytangyuan** [comment]
Please add tests in this PR, not in a follow-up PR.

File: test/e2e/hooks_test.go [hunk 3]
```diff
@@ -28,34 +33,90 @@ metadata:
...
+			return strings.Contains(status.Name, ".hooks.running")
+		}, func(t *testing.T, status *v1alpha1.NodeStatus, pod *apiv1.Pod) {
+			assert.Equal(t, v1alpha1.NodeSucceeded, status.Phase)
+		}).ExpectWorkflowNode(func(status v1alpha1.NodeStatus) bool {
+			return strings.Contains(status.Name, ".hooks.failed")
+		}, func(t *testing.T, status *v1alpha1.NodeStatus, pod *apiv1.Pod) {
+			assert.Equal(t, v1alpha1.NodeSucceeded, status.Phase)
+		})
 }
+*/
```
Comment (GeunSam2) [inline test/e2e/hooks_test.go:117]: I found a new [bug](https://github.com/argoproj/argo-workflows/issues/10743) while writing above tests.
I have written test in advance in case the bug is fixed. so temporarily disable above two tests until the [issues](https://github.com/argoproj/argo-workflows/issues/10743) are resolved.

Comment (terrytangyuan) [reply test/e2e/hooks_test.go:117]: Would you like to look into that issue too?

**Comment by GeunSam2** [comment]
I'm ready for review

File: test/e2e/hooks_test.go [hunk 4]
```diff
@@ -19,7 +20,11 @@ type HooksSuite struct {
 	fixtures.E2ESuite
 }
 
-func (s *HooksSuite) TestWorkflowLevelHooks() {
+/*
+# Temporarily disable some tests until the following issues are resolved.
+# https://github.com/argoproj/argo-workflows/issues/10743
```
Comment (terrytangyuan) [inline test/e2e/hooks_test.go:25]: Since this PR would break this test, instead of commenting these out, it would be better if you could fix this issue first. WDYT?

Comment (GeunSam2) [reply test/e2e/hooks_test.go:25]: sure! i opened new PR https://github.com/argoproj/argo-workflows/pull/10758.

**Comment by caelan-io** [comment]
@GeunSam2 - should we close this PR and focus on getting #10758 merged?

**Comment by GeunSam2** [comment]
@caelan-io Thanks for remind.
It seems that the PR mentioned is merged, so I will rebase the conflicted test file and push it

File: test/e2e/hooks_test.go (hunk 3 above)
Comment (GeunSam2) [reply test/e2e/hooks_test.go]: @alexec i added all case of test. please check it.

File: test/e2e/hooks_test.go
Comment (GeunSam2) [inline test/e2e/hooks_test.go:1]: @alexec i added all case of test. please check it.

**Review by terrytangyuan — APPROVED** [review]

**Comment by GeunSam2** [comment]
i fixed ci error

**Review by terrytangyuan — APPROVED** [review]

**Comment by agilgur5** [comment]
@GeunSam2 I've seen a few test failures on `TestTemplateLevelHooksDagSuccessVersion` from this PR. Here's a [recent CI failure](https://github.com/argoproj/argo-workflows/actions/runs/6179936074/job/16775787988?pr=11814):

<details> <summary> Test log for posterity: </summary>

```
=== PASS: HooksSuite/TestTemplateLevelHooksDagSuccessVersion
    suite.go:87: test panicked: runtime error: invalid memory address or nil pointer dereference
        goroutine 639 [running]:
        runtime/debug.Stack()
        	/opt/hostedtoolcache/go/1.21.0/x64/src/runtime/debug/stack.go:24 +0x5e
        github.com/stretchr/testify/suite.failOnPanic(0xc00077c000, {0x1d55e80, 0x33e2870})
        	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:87 +0x39
        github.com/stretchr/testify/suite.Run.func1.1()
        	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:183 +0x24c
        panic({0x1d55e80?, 0x33e2870?})
        	/opt/hostedtoolcache/go/1.21.0/x64/src/runtime/panic.go:914 +0x21f
        github.com/argoproj/argo-workflows/v3/test/e2e.(*HooksSuite).TestTemplateLevelHooksDagSuccessVersion.func9(0xc0008c8fa8?, 0x2160270?, 0x4?)
        	/home/runner/work/argo-workflows/argo-workflows/test/e2e/hooks_test.go:284 +0x13
        github.com/argoproj/argo-workflows/v3/test/e2e.(*HooksSuite).TestTemplateLevelHooksDagSuccessVersion.(*Then).ExpectWorkflowNode.func13(0x2326900?, 0xc0001c5220, 0xc0008c94b8?)
        	/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:110 +0x379
        github.com/argoproj/argo-workflows/v3/test/e2e/fixtures.(*Then).expectWorkflow(0xc0008c9558, {0xc000059c00, 0x1f}, 0xc0008c9538)
        	/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:68 +0x313
        github.com/argoproj/argo-workflows/v3/test/e2e/fixtures.(*Then).ExpectWorkflowNode(...)
        	/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:85
        github.com/argoproj/argo-workflows/v3/test/e2e.(*HooksSuite).TestTemplateLevelHooksDagSuccessVersion(0x0?)
        	/home/runner/work/argo-workflows/argo-workflows/test/e2e/hooks_test.go:281 +0x3f5
        reflect.Value.call({0xc00096ee80?, 0xc0003d0308?, 0x221cbcc047?}, {0x2039e66, 0x4}, {0xc0009d1e70, 0x1, 0x1a95868?})
        	/opt/hostedtoolcache/go/1.21.0/x64/src/reflect/value.go:596 +0xce7
        reflect.Value.Call({0xc00096ee80?, 0xc0003d0308?, 0xc0007aeb00?}, {0xc0009d1e70?, 0x53054d?, 0x2da6378?})
        	/opt/hostedtoolcache/go/1.21.0/x64/src/reflect/value.go:380 +0xb9
        github.com/stretchr/testify/suite.Run.func1(0xc00077c000)
        	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:197 +0x467
        testing.tRunner(0xc00077c000, 0xc0005ec3f0)
        	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:1595 +0xff
        created by testing.(*T).Run in goroutine 594
        	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:1648 +0x3ad
=== SLOW TEST:  HooksSuite/TestTemplateLevelHooksDagFailVersion took 17s
=== SLOW TEST:  HooksSuite/TestTemplateLevelHooksDagSuccessVersion took 32s
=== NAME  TestHooksSuite
    e2e_suite.go:86: to learn how to diagnose failed tests: https://argoproj.github.io/argo-workflows/running-locally/#running-e2e-tests-locally
--- FAIL: TestHooksSuite (61.37s)
    --- PASS: TestHooksSuite/TestTemplateLevelHooksDagFailVersion (17.63s)
    --- PASS: TestHooksSuite/TestTemplateLevelHooksDagHasDependencyVersion (10.83s)
    --- FAIL: TestHooksSuite/TestTemplateLevelHooksDagSuccessVersion (32.90s)
FAIL
FAIL	github.com/argoproj/argo-workflows/v3/test/e2e	179.416s
```
</details>

I'm not entirely sure why there's a nil pointer on one of the hooks, so I was hoping you might be able to figure it out quicker than me!

**Comment by GeunSam2** [comment]
I'll check it!
(but not sure it faster than you haha)
