### PR TITLE
fix: Apply podSpecPatch  in `woc.execWf.Spec` and template to pod sequentially

### LINKED ISSUE #11130: securityContext default override not as expected
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

https://github.com/argoproj/argo-workflows/discussions/11127

I have the below controller configmap on v3.4.7.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce
  mainContainer: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  executor: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  workflowDefaults: |
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 8737
        runAsGroup: 8737
```

I am trying to remove `securityContext.capabilities.drop` from the `main` container in a containerset.

I've tried setting `capabilities` to `null` or `{}` on my `main` container.

I've tried setting `drop` to `null` or `[]` on my `main` container.

e.g.

```yaml
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              capabilities: null
```

```yaml
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              capabilities: {}
```

But when I check the yaml of my pod, the container's securityContext capabilities is still drop all.

Referencing @alexec's blog post

* https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce

And helm's deleting a default key

* https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key

@terrytangyuan 

> Seems like a bug. The logic here needs to be revisited: https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/workflowpod.go#L607-L629

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

### LINKED ISSUE #13122: `podSpecPatch` not applied when configured in `workflowDefaults` and workflow is submitted from template
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

workflowDefaults + podSpecPatch https://github.com/argoproj/argo-workflows/blob/a514a42/test/e2e/manifests/mixins/workflow-controller-configmap.yaml (`make start` also uses this config)
- works for direct submitted workflow, e.g. you can find `terminationGracePeriodSeconds: 3s` in the created pod
- doesn't work when workflow is submitted from template, e.g. use templateref, the  `terminationGracePeriodSeconds` is missing, or go back to default `30s`

### Version

latest(a514a42)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
any
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
time="2024-05-30T15:08:16.315Z" level=info msg="Processing workflow" Phase= ResourceVersion=536481 namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.317Z" level=debug msg="Get workflowtemplates 200"
time="2024-05-30T15:08:16.318Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-wtbcr)" tmpl="*v1alpha1.WorkflowStep (hello/p0#false)"
time="2024-05-30T15:08:16.318Z" level=debug msg="Found stored template" base="*v1alpha1.Workflow (namespace=argo,name=hello-wtbcr)" tmpl="*v1alpha1.WorkflowStep (hello/p0#false)"
time="2024-05-30T15:08:16.320Z" level=debug msg="Get workflowtemplates 200"
time="2024-05-30T15:08:16.320Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-wtbcr)" tmpl="*v1alpha1.WorkflowStep (hello/p0#false)"
time="2024-05-30T15:08:16.320Z" level=debug msg="Found stored template" base="*v1alpha1.Workflow (namespace=argo,name=hello-wtbcr)" tmpl="*v1alpha1.WorkflowStep (hello/p0#false)"
time="2024-05-30T15:08:16.321Z" level=debug msg="Get workflowtemplates 200"
time="2024-05-30T15:08:16.321Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-wtbcr)" tmpl="*v1alpha1.WorkflowStep (hello/p1#false)"
time="2024-05-30T15:08:16.322Z" level=debug msg="Found stored template" base="*v1alpha1.Workflow (namespace=argo,name=hello-wtbcr)" tmpl="*v1alpha1.WorkflowStep (hello/p1#false)"
time="2024-05-30T15:08:16.324Z" level=debug msg="Get workflowtemplates 200"
time="2024-05-30T15:08:16.326Z" level=debug msg="Get configmaps 200"
time="2024-05-30T15:08:16.326Z" level=info msg="resolved artifact repository" artifactRepositoryRef="argo/#"
time="2024-05-30T15:08:16.326Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=debug msg="Skipping artifact GC" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=debug msg="Evaluating node hello-wtbcr: template: *v1alpha1.WorkflowStep (p0), boundaryID: " namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=,name=)" tmpl="*v1alpha1.WorkflowStep (p0)"
time="2024-05-30T15:08:16.326Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=,name=)" tmpl="*v1alpha1.WorkflowStep (p0)"
time="2024-05-30T15:08:16.326Z" level=debug msg="Getting the template by name: p0" base="*v1alpha1.Workflow (namespace=,name=)" tmpl="*v1alpha1.WorkflowStep (p0)"
time="2024-05-30T15:08:16.326Z" level=debug msg="Inject a retry node for node hello-wtbcr" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"hello-wtbcr\", UID:\"96fbb953-c5fd-4752-9160-0a36538ecdc2\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"536481\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowRunning' Workflow Running"
time="2024-05-30T15:08:16.326Z" level=debug msg="Initializing node hello-wtbcr: template: *v1alpha1.WorkflowStep (p0), boundaryID: " namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=info msg="Retry node hello-wtbcr initialized Running" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=debug msg="Initializing node hello-wtbcr(0): template: *v1alpha1.WorkflowStep (p0), boundaryID: " namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=info msg="Pod node hello-wtbcr-3688744399 initialized Pending" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.326Z" level=debug msg="Executing node hello-wtbcr(0) with container template: p0\n" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.327Z" level=debug namespace=argo needLocation=true workflow=hello-wtbcr
time="2024-05-30T15:08:16.327Z" level=warning msg="couldn't get boundaryTemplate through nodeName hello-wtbcr(0)" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.329Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=,name=)" tmpl="*v1alpha1.NodeStatus (p0)"
time="2024-05-30T15:08:16.329Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=,name=)" tmpl="*v1alpha1.NodeStatus (p0)"
time="2024-05-30T15:08:16.329Z" level=debug msg="Getting the template by name: p0" base="*v1alpha1.Workflow (namespace=,name=)" tmpl="*v1alpha1.NodeStatus (p0)"
time="2024-05-30T15:08:16.329Z" level=debug msg="Creating Pod: hello-wtbcr(0) (hello-wtbcr-p0-3688744399)" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.329Z" level=debug msg="Create events 201"
time="2024-05-30T15:08:16.335Z" level=debug msg="Create pods 201"
time="2024-05-30T15:08:16.335Z" level=info msg="Created pod: hello-wtbcr(0) (hello-wtbcr-p0-3688744399)" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.335Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.335Z" level=info msg=reconcileAgentPod namespace=argo workflow=hello-wtbcr
time="2024-05-30T15:08:16.335Z" level=debug msg="Log changes patch: {\"metadata\":{\"annotations\":{\"workflows.argoproj.io/pod-name-format\":\"v2\"},\"labels\":{\"workflows.argoproj.io/completed\":\"false\",\"workflows.argoproj.io/phase\":\"Running\"}},\"status\":{\"artifactGCStatus\":{\"notSpecified\":true},\"artifactRepositoryRef\":{\"artifactRepository\":{\"archiveLogs\":true,\"s3\":{\"accessKeySecret\":{\"key\":\"accesskey\",\"name\":\"my-minio-cred\"},\"bucket\":\"my-bucket\",\"endpoint\":\"minio:9000\",\"insecure\":true,\"secretKeySecret\":{\"key\":\"secretkey\",\"name\":\"my-minio-cred\"}}},\"configMap\":\"artifact-repositories\",\"key\":\"default-v1\",\"namespace\":\"argo\"},\"nodes\":{\"hello-wtbcr\":{\"children\":[\"hello-wtbcr-3688744399\"],\"displayName\":\"hello-wtbcr\",\"finishedAt\":null,\"id\":\"hello-wtbcr\",\"name\":\"hello-wtbcr\",\"phase\":\"Running\",\"startedAt\":\"2024-05-30T15:08:16Z\",\"templateName\":\"p0\",\"templateScope\":\"local/\",\"type\":\"Retry\"},\"hello-wtbcr-3688744399\":{\"displayName\":\"hello-wtbcr(0)\",\"finishedAt\":null,\"id\":\"hello-wtbcr-3688744399\",\"name\":\"hello-wtbcr(0)\",\"nodeFlag\":{\"retried\":true},\"phase\":\"Pending\",\"startedAt\":\"2024-05-30T15:08:16Z\",\"templateName\":\"p0\",\"templateScope\":\"local/\",\"type\":\"Pod\"}},\"phase\":\"Running\",\"startedAt\":\"2024-05-30T15:08:16Z\",\"storedWorkflowTemplateSpec\":{\"activeDeadlineSeconds\":300,\"arguments\":{},\"entrypoint\":\"p0\",\"podSpecPatch\":\"terminationGracePeriodSeconds: 3\\n\",\"templates\":[{\"container\":{\"command\":[\"sleep\",\"1\"],\"image\":\"alpine:3.7\",\"name\":\"\",\"resources\":{}},\"inputs\":{},\"metadata\":{},\"name\":\"p0\",\"outputs\":{},\"retryStrategy\":{\"limit\":3}},{\"container\":{\"command\":[\"sleep\",\"100000000\"],\"image\":\"alpine:3.7\",\"name\":\"\",\"resources\":{}},\"inputs\":{},\"metadata\":{},\"name\":\"p1\",\"outputs\":{},\"retryStrategy\":{\"limit\":3}}],\"workflowTemplateRef\":{\"name\":\"hello\"}}}}"
time="2024-05-30T15:08:16.336Z" level=info msg="Workflow to be dehydrated" Workflow Size=1522
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by jswxstw**
Fixes #11130
Fixes #13122

### Motivation

1. `podSpecPatch` missed keywords `null` after merging(wf/tmpl), so removing fields in map/slice by `podSpecPatch` does not work.
2. workflow-level `podSpecPatch` does not work when workflow is submitted from template by `workflowTemplateRef`.

### Modifications

1. Apply the workflow/template  `podSpecPatch` to the pod spec sequentially avoiding the merge operation.
2. Apply `podSpecPatch` in `woc.execWf.Spec` instead of `woc.wf`.

### Verification

UT and local test

### CODE REVIEW

**Comment by agilgur5** [comment]
I haven't looked at it in detail, but a quick observation that it does look like a different approach from #11222 (not necessarily good or bad)

Also DCO check is [still failing](https://github.com/argoproj/argo-workflows/pull/12476/checks?check_run_id=20219994030) as it's expecting a different/real email address

**Comment by jswxstw** [comment]
> #11222

Yes, this PR try to fix bug in pod spec patch, but #11222 try to change the merge logic of mainContainer which I think it is an incompatible change. For example, mainContainer default values in configmap may be missed after merge.
b14c2c3edf7991e3927d4f75e044b905

**Comment by agilgur5** [comment]
Ah so this allows overriding with `podSpecPatch` with `null`, which is a workaround, but does not touch `mainContainer` etc merge. Different kind of fix

File: workflow/util/util_test.go [hunk 1]
```diff
@@ -167,33 +167,6 @@ func TestReadFromSingleorMultiplePathErrorHandling(t *testing.T) {
...
 
-var yamlStr = `
-containers:
-  - name: main
-    resources:
-      limits:
-        cpu: 1000m
-`
-
-func TestPodSpecPatchMerge(t *testing.T) {
```
Comment (terrytangyuan) [inline workflow/util/util_test.go:178]: Why is this test removed?

**Review by terrytangyuan — CHANGES_REQUESTED** [review]

**Comment by jswxstw** [comment]
https://github.com/argoproj/argo-workflows/blob/7286d499a60e38e226365ac0300571963379e00c/workflow/controller/workflowpod.go#L363
There is a new bug in the original logic here: see https://github.com/argoproj/argo-workflows/discussions/12729#discussioncomment-8898332

File: workflow/controller/workflowpod_test.go [hunk 2]
```diff
@@ -1315,6 +1316,34 @@ spec:
...
+  - name: whalesay
+    podSpecPatch: '{"containers":[{"name":"main", "securityContext":{"capabilities":{"add":["ALL"],"drop":null}}}]}'
+    container:
+      image: docker/whalesay:latest
+      command: [cowsay]
+      args: ["hello world"]
+    outputs:
+      parameters:
+      - name: pod-name
+        value: "{{pod.name}}"
```
Comment (tczhao) [inline workflow/controller/workflowpod_test.go:1344]:
```suggestion
```

This seems unnecessary. Otherwise, looks good

**Review by tczhao — CHANGES_REQUESTED** [review]
looks good

File: workflow/controller/workflowpod_test.go (hunk 2 above)
Comment (jswxstw) [reply workflow/controller/workflowpod_test.go]: Yes, I removed it.

**Review by tczhao — APPROVED** [review]

**Comment by tczhao** [comment]
Hi @terrytangyuan , could you have a look at this PR again

**Review by terrytangyuan — APPROVED** [review]
