### PR TITLE
fix(ui): clarify log deletion in log-viewer. Fixes #10993

### LINKED ISSUE #10993: UI: misleading message in pod logs viewer when using Archive Logs
> Still waiting for data or an error? Try getting logs from the artifacts. Your pod GC settings will delete pods and their **logs immediately on completion**. Logs may **not appear for pods** that are deleted.

it shows this message underneath pod logs. it makes people think logs are unreachable after pod finishes but i have archived workflows setup so i can view the logs from the archived workflows ui. would be good to hide this message as it confuses new users

### PR DESCRIPTION
**Pull request by tooptoop4**
Fixes https://github.com/argoproj/argo-workflows/issues/10993

### CODE REVIEW

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 1]
```diff
@@ -289,11 +289,11 @@ export function WorkflowLogsViewer({workflow, initialNodeId, initialPodName, con
                 )}
                 {execSpec(workflow).podGC && (
                     <>
-                        <WarningIcon /> Your pod GC settings will delete pods and their logs{' '}
+                        <WarningIcon /> Your pod GC settings will delete pods{' '}
                         {execSpec(workflow).podGC.deleteDelayDuration ? `after ${execSpec(workflow).podGC.deleteDelayDuration}` : 'immediately'} on completion.
                     </>
                 )}{' '}
-                Logs may not appear for pods that are deleted.{' '}
+                Logs may not appear for pods that are deleted unless you have workflow archiving enabled.{' '}
```
Comment (agilgur5) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:296]:
```suggestion
                Logs may not appear for pods that are deleted unless you have <a href="https://argo-workflows.readthedocs.io/en/latest/configure-archive-logs/>archive logs<\> enabled.{' '}
```

Archive Logs and and Workflow Archive are separate features (that may be used together).

Also added a link. Linter may want that formatting adjusted though

**Review by agilgur5 — APPROVED** [review]
Thanks!
