### PR TITLE
fix: correct pod names for inline templates. Fixes #12895

### LINKED ISSUE #12895: Inline Workflows logs in UI always empty
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Inline Workflows always show an empty log in UI, it doesn't matter if the task succeeded or not. We are still able to read logs from the pod in the console.

Expectation: inline workflows should show correct logs in UI.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: inline-cant-show-errors
  namespace: workflows
spec:
  serviceAccountName: workflows-executor

  podGC:
    strategy: OnWorkflowSuccess

  entrypoint: pipeline
  templates:
    - name: pipeline
      dag:
        tasks:
          - name: broken-configmap
            inline:
              serviceAccountName: configmap-owner
              resource:
                action: get
                manifest: |
                  apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: non-existing-configmap
                    namespace: workflows
              outputs:
                parameters:
                  - name: value
                    valueFrom:
                      default: "default-value"
                      jqFilter: '.data["value"]'
          - name: correct-shell
            inline:
              container:
                image: alpine:3.7
                command: [sh, -c]
                args: ["echo hello"]
          - name: broken-shell
            inline:
              container:
                image: alpine:3.7
                command: [sh, -c]
                args: ["cat /tmp/non-existing-file"]
```

### Logs from the workflow controller

```text
time="2024-04-05T12:04:45.437Z" level=info msg="Processing workflow" Phase= ResourceVersion=285687282 namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.459Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=0 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.459Z" level=info msg="Updated phase  -> Running" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.463Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.463Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.463Z" level=info msg="DAG node inline-cant-show-errors-ppxjk initialized Running" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.463Z" level=warning msg="was unable to obtain the node for inline-cant-show-errors-ppxjk-1239447401, taskName broken-configmap"
time="2024-04-05T12:04:45.463Z" level=warning msg="was unable to obtain the node for inline-cant-show-errors-ppxjk-1239447401, taskName broken-configmap"
time="2024-04-05T12:04:45.463Z" level=info msg="All of node inline-cant-show-errors-ppxjk.broken-configmap dependencies [] completed" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.463Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.463Z" level=info msg="Pod node inline-cant-show-errors-ppxjk-1239447401 initialized Pending" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.510Z" level=info msg="Created pod: inline-cant-show-errors-ppxjk.broken-configmap (inline-cant-show-errors-ppxjk--1239447401)" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.510Z" level=warning msg="was unable to obtain the node for inline-cant-show-errors-ppxjk-897640899, taskName broken-shell"
time="2024-04-05T12:04:45.510Z" level=warning msg="was unable to obtain the node for inline-cant-show-errors-ppxjk-897640899, taskName broken-shell"
time="2024-04-05T12:04:45.510Z" level=info msg="All of node inline-cant-show-errors-ppxjk.broken-shell dependencies [] completed" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.510Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.510Z" level=info msg="Pod node inline-cant-show-errors-ppxjk-897640899 initialized Pending" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.559Z" level=info msg="Created pod: inline-cant-show-errors-ppxjk.broken-shell (inline-cant-show-errors-ppxjk--897640899)" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.559Z" level=warning msg="was unable to obtain the node for inline-cant-show-errors-ppxjk-109496782, taskName correct-shell"
time="2024-04-05T12:04:45.559Z" level=warning msg="was unable to obtain the node for inline-cant-show-errors-ppxjk-109496782, taskName correct-shell"
time="2024-04-05T12:04:45.560Z" level=info msg="All of node inline-cant-show-errors-ppxjk.correct-shell dependencies [] completed" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.560Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.560Z" level=info msg="Pod node inline-cant-show-errors-ppxjk-109496782 initialized Pending" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.612Z" level=info msg="Created pod: inline-cant-show-errors-ppxjk.correct-shell (inline-cant-show-errors-ppxjk--109496782)" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.612Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.612Z" level=info msg=reconcileAgentPod namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:45.625Z" level=info msg="Workflow update successful" namespace=workflows phase=Running resourceVersion=285687291 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.510Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=285687291 namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=3 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="task-result changed" namespace=workflows nodeID=inline-cant-show-errors-ppxjk-897640899 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="task-result changed" namespace=workflows nodeID=inline-cant-show-errors-ppxjk-1239447401 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="task-result changed" namespace=workflows nodeID=inline-cant-show-errors-ppxjk-109496782 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="node changed" namespace=workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=inline-cant-show-errors-ppxjk-109496782 old.message= old.phase=Pending old.progress=0/1 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="Pod failed: Error (exit code 1)" displayName=broken-configmap namespace=workflows pod=inline-cant-show-errors-ppxjk--1239447401 templateName= workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="node changed" namespace=workflows new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=inline-cant-show-errors-ppxjk-1239447401 old.message= old.phase=Pending old.progress=0/1 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="Pod failed: Error (exit code 1)" displayName=broken-shell namespace=workflows pod=inline-cant-show-errors-ppxjk--897640899 templateName= workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.511Z" level=info msg="node changed" namespace=workflows new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=inline-cant-show-errors-ppxjk-897640899 old.message= old.phase=Pending old.progress=0/1 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.512Z" level=info msg="Outbound nodes of inline-cant-show-errors-ppxjk set to [inline-cant-show-errors-ppxjk-1239447401 inline-cant-show-errors-ppxjk-897640899 inline-cant-show-errors-ppxjk-109496782]" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.512Z" level=info msg="node inline-cant-show-errors-ppxjk phase Running -> Failed" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.512Z" level=info msg="node inline-cant-show-errors-ppxjk finished: 2024-04-05 12:04:55.512049976 +0000 UTC" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.512Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.512Z" level=info msg=reconcileAgentPod namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.512Z" level=info msg="Updated phase Running -> Failed" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.518Z" level=info msg="cleaning up pod" action=deletePod key=workflows/inline-cant-show-errors-ppxjk-1340600742-agent/deletePod
time="2024-04-05T12:04:55.525Z" level=info msg="Workflow update successful" namespace=workflows phase=Failed resourceVersion=285687597 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:04:55.532Z" level=info msg="cleaning up pod" action=labelPodCompleted key=workflows/inline-cant-show-errors-ppxjk--1239447401/labelPodCompleted
time="2024-04-05T12:04:55.532Z" level=info msg="cleaning up pod" action=labelPodCompleted key=workflows/inline-cant-show-errors-ppxjk--897640899/labelPodCompleted
time="2024-04-05T12:04:55.532Z" level=info msg="cleaning up pod" action=labelPodCompleted key=workflows/inline-cant-show-errors-ppxjk--109496782/labelPodCompleted
time="2024-04-05T12:05:05.581Z" level=info msg="Processing workflow" Phase=Failed ResourceVersion=285687597 namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:05:05.583Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=3 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:05:05.583Z" level=info msg="task-result changed" namespace=workflows nodeID=inline-cant-show-errors-ppxjk-897640899 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:05:05.583Z" level=info msg="task-result changed" namespace=workflows nodeID=inline-cant-show-errors-ppxjk-1239447401 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:05:05.583Z" level=info msg="task-result changed" namespace=workflows nodeID=inline-cant-show-errors-ppxjk-109496782 workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:05:05.583Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:05:05.583Z" level=info msg=reconcileAgentPod namespace=workflows workflow=inline-cant-show-errors-ppxjk
time="2024-04-05T12:05:05.589Z" level=info msg="cleaning up pod" action=deletePod key=workflows/inline-cant-show-errors-ppxjk-1340600742-agent/deletePod
time="2024-04-05T12:05:05.597Z" level=info msg="Workflow update successful" namespace=workflows phase=Failed resourceVersion=285687597 workflow=inline-cant-show-errors-ppxjk
```

### Logs from in your workflow's wait container

```text
-
```

### LINKED ISSUE #12937: Inline templates still do not create the pod name correctly
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

It still looks like the bug from https://github.com/argoproj/argo-workflows/issues/10912 only that now with version v3.5.5 argo is not even realizing anymore that the pod is already completed.

Screenshot 2024-04-15 at 14 49 22

The pod argo wants to refer to is named `fantastic-python-2118328171` as can be seen in the UI. (for the workflow, see the example workflow further down)

It's stuck in pending mode as the pod is not found on the Kubernetes cluster, because when I look at the cluster, I see the pod called `fantastic-python--2118328171` which is either running or already done. Since argo apparently uses the wrong name to fetch the pod and its status, the workflow does not proceed. Even if it would continue, the logs would not be visible in the argo UI, see the referenced bug report for it.

You can even see in the logs of the controller that it created the pod using the double `-` and then it tries to pull the status of the pod using only one `-`. (see logs further, the first log is being returned when I search for the pod name with double `-`, the other logs, when I search for the pod name with only one `-`)

If I got your fix right for https://github.com/argoproj/argo-workflows/issues/10912 I think you tried to fix a problem with the naming of the task, but I think the issue goes deeper:

As far as I understood it, the pod name should always be something like `{workflow-name}-{workflow-id}-{step-name}-{step-id}` but when I use the `inline` option rather than the `template` option to reference another template, it simply does not add the `step-name` to the pod name.

Please have a look at it, since I need to use the `inline` option as I'm creating the workflows automatically, and using the `template` option would make everything much much harder.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: fantastic-python
  namespace: default
spec:
  entrypoint: argosay
  templates:
    - name: argosay
      dag:
        tasks:
          - name: some-task
            inline:
              container:
                name: main
                image: argoproj/argosay:v2
                command:
                  - /argosay
                args:
                  - echo
                  - 'Hello argo'
```

### Logs from the workflow controller

```text
time="2024-04-15T12:44:16.689Z" level=info msg="Created pod: fantastic-python.some-task (fantastic-python--2118328171)" namespace=default workflow=fantastic-python

time="2024-04-15T12:44:16.678Z" level=warning msg="was unable to obtain the node for fantastic-python-2118328171, taskName some-task"
time="2024-04-15T12:44:16.678Z" level=warning msg="was unable to obtain the node for fantastic-python-2118328171, taskName some-task"
time="2024-04-15T12:44:16.678Z" level=info msg="Pod node fantastic-python-2118328171 initialized Pending" namespace=default workflow=fantastic-python
time="2024-04-15T12:44:26.691Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=fantastic-python-2118328171 old.message= old.phase=Pending old.progress=0/1 workflow=fantastic-python
time="2024-04-15T12:44:36.695Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=fantastic-python-2118328171 old.message= old.phase=Pending old.progress=0/1 workflow=fantastic-python
time="2024-04-15T12:44:46.711Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=fantastic-python-2118328171 old.message= old.phase=Pending old.progress=0/1 workflow=fantastic-python
time="2024-04-15T12:44:56.714Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=fantastic-python-2118328171 old.message= old.phase=Pending old.progress=0/1 workflow=fantastic-python
time="2024-04-15T12:45:06.717Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=fantastic-python-2118328171 old.message= old.phase=Pending old.progress=0/1 workflow=fantastic-python
time="2024-04-15T12:45:16.722Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=fantastic-python-2118328171 old.message= old.phase=Pending old.progress=0/1 workflow=fantastic-python
```

### Logs from in your workflow's wait container

```text
time="2024-04-15T12:59:16.660Z" level=info msg="Starting Workflow Executor" version=v3.4.8
time="2024-04-15T12:59:16.661Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2024-04-15T12:59:16.661Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=default podName=fantastic-python--2118328171 template="{\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"main\",\"image\":\"argoproj/argosay:v2\",\"command\":[\"/argosay\"],\"args\":[\"echo\",\"Hello argo\"],\"resources\":{}}}" version="&Version{Version:v3.4.8,BuildDate:2023-05-25T22:21:53Z,GitCommit:9e27baee4b3be78bb662ffa5e3a06f8a6c28fb53,GitTag:v3.4.8,GitTreeState:clean,GoVersion:go1.20.4,Compiler:gc,Platform:linux/arm64,}"
time="2024-04-15T12:59:16.661Z" level=info msg="Starting deadline monitor"
time="2024-04-15T12:59:18.663Z" level=info msg="Main container completed" error="<nil>"
time="2024-04-15T12:59:18.663Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2024-04-15T12:59:18.663Z" level=info msg="No output parameters"
time="2024-04-15T12:59:18.663Z" level=info msg="No output artifacts"
time="2024-04-15T12:59:18.663Z" level=info msg="Alloc=9863 TotalAlloc=15937 Sys=24429 NumGC=4 Goroutines=7"

```

### PR DESCRIPTION
**Pull request by shuangkun**
Supersede #12928 and add test.

Fixes #12895
Fixes #12937

### CODE REVIEW

File: workflow/util/pod_name.go [hunk 1]
```diff
@@ -58,8 +58,8 @@ func GeneratePodName(workflowName, nodeName, templateName, nodeID string, versio
 	}
 
 	prefix := workflowName
-	if !strings.Contains(nodeName, ".inline") {
-		prefix = fmt.Sprintf("%s-%s", workflowName, templateName)
+	if !strings.Contains(nodeName, ".inline") && templateName != "" {
```
Comment (agilgur5) [inline workflow/util/pod_name.go:61]:
```suggestion
	if templateName != "" {
```

this can be simplified and would match the UI, per my previous review comment https://github.com/argoproj/argo-workflows/pull/12928#discussion_r1575035131

**Review by agilgur5 — APPROVED** [review]
Thanks for fixing this up

**Comment by agilgur5** [comment]
Some E2Es are failing due to DockerHub rate limits (for some of the images used in the E2Es)
