### PR TITLE
fix: add a special case for `item` variable during global expression replacement

### LINKED ISSUE #15008: `item` is not usable alone within a sprig expression since 3.6.7
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

For a step that uses a loop construct, e.g. `withItems`, if you use the `item` variable within a `sprig` function within an expression, _not_ with any other references to item, then the sprig function will be wiped out to an empty string.

This example will be an empty string:
```yml
    steps:
    - - name: print-message-loop
        template: print-message
        withItems:
        - example
        arguments:
          parameters:
          - name: message
            value: '{{=sprig.upper(item)}}'
```

Whereas this will actually contain the expected string `exampleEXAMPLE`:

```yml
    steps:
    - - name: print-message-loop
        template: print-message
        withItems:
        - example
        arguments:
          parameters:
          - name: message
            value: '{{=item + sprig.upper(item)}}'
```

I also tested the above on https://github.com/argoproj/argo-workflows/pull/14718 but still broken, so possibly related but not the root cause.

I found that the example works correctly on `v3.6.5`, but cherry-picking the `expr` library upgrade from this commit https://github.com/argoproj/argo-workflows/commit/9b7c0c4c4ce1ecb8e1d27df95d14ccef09cffe0f results in the broken behaviour, which comes from `expr.Run` on this line https://github.com/argoproj/argo-workflows/blob/5291e0b01f94ba864f96f795bb500f2cfc5ad799/util/template/expression_template.go#L80-L81

which with the 1.17 version of `expr` we get `result` back as an empty string, whereas `1.16.9` gets `result` as `nil`, so the check on the following line no longer works.

### Version(s)

v3.6.7, v3.7.3

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  templates:
  - name: print-message
    container:
      image: busybox
      args:
      - '{{inputs.parameters.message}}'
      command:
      - echo
    inputs:
      parameters:
      - name: message
  - name: loop-example
    steps:
    - - name: print-message-loop
        template: print-message
        withItems:
        - example
        arguments:
          parameters:
          - name: message
            value: '{{=sprig.upper(item)}}'
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep loops-jfltp
time="2025-11-07T12:00:33.355Z" level=info msg="Processing workflow" Phase= ResourceVersion=1527858 namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.386Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=loops-jfltp
time="2025-11-07T12:00:33.386Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.389Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.391Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.391Z" level=info msg="Steps node loops-jfltp initialized Running" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.391Z" level=info msg="StepGroup node loops-jfltp-2382344797 initialized Running" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.392Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.393Z" level=info msg="Pod node loops-jfltp-252820006 initialized Pending" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.462Z" level=info msg="Created pod: loops-jfltp[0].print-message-loop(0:example) (loops-jfltp-print-message-252820006)" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.463Z" level=info msg="Workflow step group node loops-jfltp-2382344797 not yet completed" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.463Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.463Z" level=info msg=reconcileAgentPod namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.464Z" level=info msg="add pod event" pod=loops-jfltp-print-message-252820006
time="2025-11-07T12:00:33.492Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1527861 workflow=loops-jfltp
time="2025-11-07T12:00:33.494Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1527861 namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.495Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=loops-jfltp
time="2025-11-07T12:00:33.497Z" level=info msg="Workflow step group node loops-jfltp-2382344797 not yet completed" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.497Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.497Z" level=info msg=reconcileAgentPod namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:33.504Z" level=info msg="update pod event" pod=loops-jfltp-print-message-252820006
time="2025-11-07T12:00:33.575Z" level=info msg="update pod event" pod=loops-jfltp-print-message-252820006
time="2025-11-07T12:00:34.807Z" level=info msg="update pod event" pod=loops-jfltp-print-message-252820006
time="2025-11-07T12:00:40.677Z" level=info msg="update pod event" pod=loops-jfltp-print-message-252820006
time="2025-11-07T12:00:43.472Z" level=info msg="update pod event" pod=loops-jfltp-print-message-252820006
time="2025-11-07T12:00:43.477Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1527861 namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:43.479Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=loops-jfltp
time="2025-11-07T12:00:43.485Z" level=info msg="Workflow step group node loops-jfltp-2382344797 not yet completed" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:43.485Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:43.485Z" level=info msg=reconcileAgentPod namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:43.510Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1527898 workflow=loops-jfltp
time="2025-11-07T12:00:43.516Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1527898 namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:43.516Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=loops-jfltp
time="2025-11-07T12:00:43.532Z" level=info msg="Workflow step group node loops-jfltp-2382344797 not yet completed" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:43.532Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:43.532Z" level=info msg=reconcileAgentPod namespace=argo workflow=loops-jfltp
time="2025-11-07T12:00:45.764Z" level=info msg="update pod event" pod=loops-jfltp-print-message-252820006
time="2025-11-07T12:00:47.335Z" level=info msg="update pod event" pod=loops-jfltp-print-message-252820006
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=loops-jfltp,workflow.argoproj.io/phase!=Succeeded
time="2025-11-07T12:00:44.347Z" level=info msg="No output parameters"
time="2025-11-07T12:00:44.347Z" level=info msg="No output artifacts"
time="2025-11-07T12:00:44.351Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: loops-jfltp/loops-jfltp-print-message-252820006/main.log"
time="2025-11-07T12:00:44.352Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2025-11-07T12:00:44.353Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=loops-jfltp/loops-jfltp-print-message-252820006/main.log path=/tmp/argo/outputs/logs/main.log
time="2025-11-07T12:00:44.448Z" level=info msg="Save artifact" artifactName=main-logs duration=95.952459ms error="<nil>" key=loops-jfltp/loops-jfltp-print-message-252820006/main.log
time="2025-11-07T12:00:44.448Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2025-11-07T12:00:44.448Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2025-11-07T12:00:44.499Z" level=info msg="Alloc=11630 TotalAlloc=17526 Sys=23637 NumGC=5 Goroutines=9"
time="2025-11-07T12:00:44.512Z" level=info msg="Deadline monitor stopped"
```

### PR DESCRIPTION
**Pull request by elliotgunton**
Fixes #15008 

### Motivation

* The root cause of the issue was from SubstituteParams, where the `globalReplacedTmplStr` would have already lost the `={{sprig.func(item)}}` expression which became an empty string. This meant the later `processItem` function had no expression to expand.
* This seems to have come from a change in sprig which in turn came from the `expr` library upgrade from 1.16 to 1.17 in 9b7c0c4

### Modifications

* We now have a special case to _not_ attempt to run the `expr` program as an unresolved `item` in a sprig string function now comes back as an empty string, instead of `nil`.
* As part of this change, refactored the `anyVarNotInEnv` to return the varname that is missing as a reference to a string, or `nil`.
* Also removed a completely unused function `hasRetries` and refactored and expanded the unit tests where it was used
* Added an e2e test using the workflow from the issue

### Verification

* e2e test added using the workflow from the issue
* Also tested manually.

### CODE REVIEW

File: util/template/expression_template.go [hunk 1]
```diff
@@ -38,17 +38,24 @@ func expressionReplace(ctx context.Context, w io.Writer, expression string, env
...
 	if err != nil && allowUnresolved {
-		log.WithError(err).Debug(ctx, "unresolved is allowed ")
+		log.WithError(err).Debug(ctx, "unresolved is allowed")
 		return fmt.Fprintf(w, "{{%s%s}}", kindExpression, expression)
 	}
 	if err != nil {
 		return 0, fmt.Errorf("failed to unmarshall JSON expression: %w", err)
 	}
 
+	if anyVarNotInEnv(unmarshalledExpression, []string{"item"}, env) && allowUnresolved {
```
Comment (Joibel) [inline util/template/expression_template.go]: We should be able to combine this and retries into one call to anyVarNotInEnv, perhaps it could return the var that is not in env for the log line.

Comment (elliotgunton) [reply util/template/expression_template.go]: Yeah was considering it's worth a refactor at this point

File: util/template/expression_template_test.go [hunk 2]
```diff
@@ -8,19 +8,22 @@ import (
...
-func Test_hasRetries(t *testing.T) {
-	t.Run("hasRetiresInExpression", func(t *testing.T) {
-		assert.True(t, hasRetries("retries"))
-		assert.True(t, hasRetries("retries + 1"))
-		assert.True(t, hasRetries("sprig(retries)"))
-		assert.True(t, hasRetries("sprig(retries + 1) * 64"))
-		assert.False(t, hasRetries("foo"))
-		assert.False(t, hasRetries("retriesCustom + 1"))
+func Test_hasVariableInExpression(t *testing.T) {
+	t.Run("hasVariableInExpression", func(t *testing.T) {
```
Comment (Joibel) [inline util/template/expression_template_test.go]: I know that it's not your line, but `t.Run` is completely unnecessary and adds confusion here and the func below.

It's so you can write one function with multiple tests nested in it, but this is one test, so it's clearer if we lose it.

File: util/template/expression_template.go [hunk 3]
```diff
@@ -23,13 +23,24 @@ func init() {
 	}
 }
 
-func anyVarNotInEnv(expression string, variables []string, env map[string]interface{}) bool {
-	for _, variable := range variables {
+var variablesToCheck = []string{
```
Comment (Joibel) [inline util/template/expression_template.go:26]: ❤️

File: test/e2e/expr_lang_test.go [hunk 4]
```diff
@@ -64,6 +64,49 @@ spec:
 		})
 }
 
-func TestExprLangSSuite(t *testing.T) {
+func (s *ExprSuite) TestRegression15008() {
```
Comment (Joibel) [inline test/e2e/expr_lang_test.go]: Would prefer a descriptive name (git blame can allow archaeology). `TestItemInSprigExpr` or something.

**Review by Joibel — COMMENTED** [review]
nits only

File: util/template/expression_template_test.go (hunk 2 above)
Comment (elliotgunton) [reply util/template/expression_template_test.go]: It did look off to me too lol

File: test/e2e/expr_lang_test.go (hunk 4 above)
Comment (elliotgunton) [reply test/e2e/expr_lang_test.go]: Yeah, changed the other one too

File: util/template/expression_template.go [hunk 5]
```diff
@@ -38,35 +49,20 @@ func expressionReplace(ctx context.Context, w io.Writer, expression string, env
...
-	// when the exit handlers complete.
-	if anyVarNotInEnv(unmarshalledExpression, []string{"workflow.status", "workflow.failures"}, env) && allowUnresolved {
-		log.WithError(err).Debug(ctx, "workflow.status or workflow.failures are present and unresolved is allowed")
+	varNameNotInEnv := anyVarNotInEnv(unmarshalledExpression, env)
+	if varNameNotInEnv != nil && allowUnresolved {
+		// this is to make sure expressions don't get resolved to nil or an empty string when certain variables
+		// don't exist in the env during the "global" replacement.
+		// See https://github.com/argoproj/argo-workflows/issues/5388, https://github.com/argoproj/argo-workflows/issues/15008,
+		// https://github.com/argoproj/argo-workflows/issues/10393, https://github.com/expr-lang/expr/issues/330
+		log.WithError(err).WithField("variable", varNameNotInEnv).Debug(ctx, "variable not in env but unresolved is allowed")
```
[the remark this answers is not in the document]
Comment (elliotgunton) [reply util/template/expression_template.go]: Valid catch

[the remark this answers is not in the document]
Comment (elliotgunton) [reply util/template/expression_template.go]: Also valid
