### PR TITLE
fix: sync cluster Workflow Template Informer before it's used

### LINKED ISSUE #8956: v3.3.5: workflow-controller panic at context.go:125 GetTemplateFromRef
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

Workflow-controller panics suddenly, and once the panic occurs, it continues.
I found other user had same panic in slack.
https://cloud-native.slack.com/archives/C01QW9QSSSK/p1652457569109429

What version are you running?
v3.3.5
This panic was not happend at v3.1.6

## Diagnostics
Note that 
- ClusterWorkflowTemplate certainly exists although it got an error.
- Controller restarts does not fix it.
```
time="2022-06-13T06:04:09.208Z" level=info msg="Get clusterworkflowtemplates 200"
time="2022-06-13T06:04:09.251Z" level=info msg="Processing workflow" namespace=ns1 workflow=wf-lx4zf
time="2022-06-13T06:04:09.251Z" level=info msg="Queueing Failed workflow ns2/wf-kzrs5 for delete in -29s due to TTL"
time="2022-06-13T06:04:09.251Z" level=info msg="Deleting garbage collected workflow 'ns2/wf-kzrs5'"
time="2022-06-13T06:04:09.258Z" level=info msg="Task-result reconciliation" namespace=ns1 numObjs=1 workflow=wf-lx4zf
time="2022-06-13T06:04:09.258Z" level=info msg="task-result changed" namespace=ns1 nodeID=wf-lx4zf-671665593 workflow=wf-lx4zf
time="2022-06-13T06:04:09.259Z" level=error msg="Mark error node" error="clusterworkflowtemplates.argoproj.io \"cluster-template-wf\" not found" namespace=ns1 nodeName="wf-lx4zf[0].wf[0].wf-main-pvc(0)" workflow=wf-lx4zf
time="2022-06-13T06:04:09.259Z" level=info msg="node wf-lx4zf-671665593 phase Running -> Error" namespace=ns1 workflow=wf-lx4zf
time="2022-06-13T06:04:09.259Z" level=info msg="node wf-lx4zf-671665593 message: clusterworkflowtemplates.argoproj.io \"cluster-template-wf\" not found" namespace=ns1 workflow=wf-lx4zf
time="2022-06-13T06:04:09.259Z" level=info msg="node wf-lx4zf-671665593 finished: 2022-06-13 06:04:09.259111158 +0000 UTC" namespace=ns1 workflow=wf-lx4zf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x19937b6]

goroutine 292 [running]:
github.com/argoproj/argo-workflows/v3/workflow/templateresolution.(*Context).GetTemplateFromRef(0x0, 0xc009b2c030)
	/go/src/github.com/argoproj/argo-workflows/workflow/templateresolution/context.go:125 +0x36
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).GetNodeTemplate(0xc007632240, 0xc00a8b4b00)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2093 +0x105
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).assessNodeStatus(0xc007632240, 0xc004a16e30, 0xc00a8b4b00)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1162 +0x9e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func1(0xc004a16e30)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:997 +0x345
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func2(0xc000b94fb8)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1037 +0x92
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1035 +0x21a"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by juliev0**
After Controller leader election we need to make sure cluster Workflow Template Informer's cache is updated first. Otherwise, we call Lister() on it before it's ready.

Signed-off-by: Julie Vogelman <julie_vogelman@intuit.com>

Fixes #8956

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1151,7 +1151,10 @@ func printPodSpecLog(pod *apiv1.Pod, wfName string) {
 // and returns the new node status if something changed
 func (woc *wfOperationCtx) assessNodeStatus(pod *apiv1.Pod, old *wfv1.NodeStatus) *wfv1.NodeStatus {
 	new := old.DeepCopy()
-	tmpl := woc.GetNodeTemplate(old)
+	tmpl, err := woc.GetNodeTemplate(old)
+	if err != nil {
+		return nil
```
Comment (tczhao) [inline workflow/controller/operator.go:1156]: should we log here? maybe hard to debug if weird things happen later

**Review by tczhao — COMMENTED** [review]
should `createClusterWorkflowTemplateInformer` gets run before the first `WaitForCache`, maybe a slightly more efficient?


https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/controller.go#L268-L280

**Comment by juliev0** [comment]
> https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/controller.go#L268-L280

sure, I could switch them

File: workflow/controller/operator.go (hunk 1 above)
Comment (juliev0) [reply workflow/controller/operator.go:1157]: added an extra log line on this level just in cas

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -1151,7 +1151,11 @@ func printPodSpecLog(pod *apiv1.Pod, wfName string) {
 // and returns the new node status if something changed
 func (woc *wfOperationCtx) assessNodeStatus(pod *apiv1.Pod, old *wfv1.NodeStatus) *wfv1.NodeStatus {
 	new := old.DeepCopy()
-	tmpl := woc.GetNodeTemplate(old)
+	tmpl, err := woc.GetNodeTemplate(old)
```
Comment (sarabala1979) [inline workflow/controller/operator.go:1154]: do we need to check the tmpl is nil or not?

Comment (juliev0) [reply workflow/controller/operator.go:1154]: was debating that one. err should be non-nil in that case, but I could add an additional check for safety. If tmpl is nil and err is non-nil, then that would be a bad unexpected situation. Would we rather crash and maybe be alerted that this case occurred through the stack trace or log an error (not sure if it will be seen?)

Comment (tczhao) [reply workflow/controller/operator.go:1154]: I say alert over the crash, don't want to be in a situation where 1 workflow crashes the controller causing all other workflows to hang

Comment (juliev0) [reply workflow/controller/operator.go:1154]: Actually, I realized (based on an e2e test) that it seems to be valid for tmpl to be nil. For safety I added a couple of checks in the switch cases below before we try to use it to make sure it's not nil.

**Review by sarabala1979 — APPROVED** [review]
LGTM
