### PR TITLE
feat: add CreatorUsername label when user is signed in via SSO. Fixes…

### LINKED ISSUE #7099: Proposal to add CreatorUsername label when user is signed in via SSO
# Summary

What change needs making?
Proposal to add `CreatorUsername` label to resources when user is signed in via SSO

# Use Cases

When would you use this?
We have a bunch of internal use cases where username of the user will help us identifying the particular user along with email and userId.

---

**Message from the maintainers**:

I will be happy to submit a PR for this, where we can keep the username in the claims of the JWE token. and then use it when we create any resource.
Cheers 🥂 

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by nityanandagohain**
closes #7099

Signed-off-by: Nityananda Gohain <nityanandagohain@gmail.com>

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Comment by nityanandagohain** [comment]
@alexec a gentle reminder for the workflow approval, thanks :)

File: server/auth/types/claims.go [hunk 1]
```diff
@@ -14,6 +14,7 @@ type Claims struct {
 	Email              string                 `json:"email,omitempty"`
 	EmailVerified      bool                   `json:"email_verified,omitempty"`
 	ServiceAccountName string                 `json:"service_account_name,omitempty"`
+	Username           string                 `json:"preferred_username,omitempty"`
```
Comment (simster7) [inline server/auth/types/claims.go:17]: Why `preferred_username` instead of `username`?

**Review by simster7 — COMMENTED** [review]
If this PR is ready for review, you should mark it as ready on Github :)

File: server/auth/types/claims.go (hunk 1 above)
Comment (nityanandagohain) [reply server/auth/types/claims.go:17]: Since `preferred_username` is a standard claim  that's why used it.

ref https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims 


do you think we should give an option to change/override it just like we do for groups i.e `customGroupClaimName`  ?

Comment (alexec) [reply server/auth/types/claims.go:17]: maybe change field name to match the JSON?

Comment (nityanandagohain) [reply server/auth/types/claims.go:17]: Yes we can do that or add to the docs that `perferred_username` claim will be used for username ?

What would you suggest ?

Comment (alexec) [reply server/auth/types/claims.go:17]: It think qualification is good

Comment (nityanandagohain) [reply server/auth/types/claims.go:17]: sorry, but I am not able comprehend what you are suggesting.

Comment (nityanandagohain) [reply server/auth/types/claims.go:17]: Hey @alexec  please help on how should I  proceed here.

Comment (alexec) [reply server/auth/types/claims.go:17]: I think field names should match JSON name, i.e. this should be

    PreferredUsername           string                 `json:"preferred_username,omitempty"`

File: workflow/common/common.go [hunk 2]
```diff
@@ -46,8 +46,9 @@ const (
 	// for the purposes of workflow segregation
 	LabelKeyControllerInstanceID = workflow.WorkflowFullName + "/controller-instanceid"
 	// Who created this workflow.
-	LabelKeyCreator      = workflow.WorkflowFullName + "/creator"
-	LabelKeyCreatorEmail = workflow.WorkflowFullName + "/creator-email"
+	LabelKeyCreator         = workflow.WorkflowFullName + "/creator"
+	LabelKeyCreatorEmail    = workflow.WorkflowFullName + "/creator-email"
+	LabelKeyCreatorUsername = workflow.WorkflowFullName + "/creator-username"
```
Comment (alexec) [inline workflow/common/common.go:51]: Should we be honest(?) here? The value is not `username` is is in fact the user preferred username

Comment (nityanandagohain) [reply workflow/common/common.go:51]: Yep, makes sense. I will make the changes.

**Review by alexec — CHANGES_REQUESTED** [review]
changes requested

File: workflow/common/common.go (hunk 2 above)
Comment (nityanandagohain) [reply workflow/common/common.go]: made the changes, but will require a workflow approval again.

**Review by alexec — APPROVED** [review]

**Comment by MarahAbu** [comment]
Hi, I'm using argo workflows version v3.2.9 and trying to use the creator username  label {{workflow.labels.workflows.argoproj.io/creator-preferred-username}} but its not working although this feature should be implemented in the version i'm using, also in the user info i don't see the preferred username I only see email

**Comment by nityanandagohain** [comment]
If the response from your IDP provider contains `preferred_username` in claims it will be added to argo JWE.

@MarahAbu can you check if you have added the correct scope in Argo config, if required by your IDP ?
