### PR TITLE
fix: use env when pod version annotation is missing. Fixes #10237

### LINKED ISSUE #10237: Inconsistent pod name with parallelization enabled
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I am noticing some inconsistent behavior for the pod names calculation when using parallelization with v1 POD_NAME spec. I have parallelization enabled to run 5 max workflows at the same time. I submit 20 workflows at the same time, the first 5 calculate pod names for all tasks without the template name(according to v1 spec), after that every workflow that was stuck in the Pending state appends template name to the pod name as well(v2 spec). Argo UI doesn't show this, but when you monitor the pods using kubectl, you can see the name of the pods being created after the initial 5 workflows will have template names appended to it(v2 spec)

### Version

3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello

  # This spec contains two templates: hello-hello-hello and whalesay
  templates:
  - name: hello-hello-hello
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: hello1            # hello1 is run before the following steps
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a           # double dash => run after previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2a"
      - name: hello2b           # single dash => run in parallel with previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2b"

  # This is the same template as from the previous example
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by isubasinghe**
Signed-off-by: Isitha Subasinghe <isitha@pipekit.io>

Fixes #10237

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [x] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

File: workflow/util/pod_name.go [hunk 1]
```diff
@@ -79,8 +79,10 @@ func ensurePodNamePrefixLength(prefix string) string {
 // given workflow
 func GetWorkflowPodNameVersion(wf *v1alpha1.Workflow) PodNameVersion {
 	annotations := wf.GetAnnotations()
-	version := annotations[common.AnnotationKeyPodNameVersion]
-
+	version, ok := annotations[common.AnnotationKeyPodNameVersion]
```
Comment (NikeNano) [inline workflow/util/pod_name.go:82]: Is the `default` in the switch case below still valid?  Otherwise this could potentially be rewritten so that `GetPodNameVersion()` is the `default` case?

Comment (isubasinghe) [reply workflow/util/pod_name.go:82]: I was tempted to implement this fix that way but that default switch case will be hit if the annotation is invalid. That is a different behaviour to the GetPodNameVersion call. 

But yeah I am on the fence on this about what the "right behaviour" is.  This is why I went with the current approach, at least it will always be consistent when the user makes a wrong annotation (default to v2).

Comment (NikeNano) [reply workflow/util/pod_name.go:82]: Ok, sounds good!

**Review by NikeNano — APPROVED** [review]
LGTM

**Review by alexec — APPROVED** [review]
