### PR TITLE
fix: use the execWf spec to determine artifactgc strategy

### LINKED ISSUE #10015: artifactGC doesn't remove artifacts if defined in WorkflowTemplate
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When running the [ArtifactGC demo workflow](https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection), it appropriately deletes the wanted artifact at workflow deletion. However, when the workflow is converted into a WorkflowTemplate, ArtifactGC no longer works, workflow finalizers are not removed, and completed workflows deriving from it can not be deleted.

I would expect ArtifactGC to work equally whether the artifact was defined in a Workflow or in a WorkflowTemplate.

Looking at controller logs (with `loglevel=DEBUG`), it seems that in the latter case, ArtifactGC cannot find any artifacts to delete, and therefore the ArtifactGC process remains incomplete. The workflow controller prints out the debug message `No Artifact Search Results returned from strategy`.

### Version

v.3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

The Workflow, for which ArtifactGC succeeds:
```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-gc-test-
spec:
  entrypoint: main
  artifactGC:
    strategy: OnWorkflowDeletion  # default Strategy set here applies to all Artifacts by default
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        command:
          - sh
          - -c
        args:
          - |
            echo "can throw this away" > /tmp/temporary-artifact.txt
            echo "keep this" > /tmp/keep-this.txt
      outputs:
        artifacts:
          - name: temporary-artifact
            path: /tmp/temporary-artifact.txt
            s3:
              key: temporary-artifact.txt
          - name: keep-this
            path: /tmp/keep-this.txt
            s3:
              key: keep-this.txt
            artifactGC:
              strategy: Never   # optional override for an Artifact
```
The WorkflowTemplate (practically the same as the workflow above), for which ArtifactGC fails both when run as an instance through Argo Server GUI and with a helper Workflow referring to the template:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: artifact-gc-test-wft
spec:
  entrypoint: main
  artifactGC:
    strategy: OnWorkflowDeletion  # default Strategy set here applies to all Artifacts by default
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        command:
          - sh
          - -c
        args:
          - |
            echo "can throw this away" > /tmp/temporary-artifact.txt
            echo "keep this" > /tmp/keep-this.txt
      outputs:
        artifacts:
          - name: temporary-artifact
            path: /tmp/temporary-artifact.txt
            s3:
              key: temporary-artifact.txt
          - name: keep-this
            path: /tmp/keep-this.txt
            s3:
              key: keep-this.txt
            artifactGC:
              strategy: Never   # optional override for an Artifact
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifactgc-test-
spec:
  entrypoint: test
  templates:
    - name: test
      steps:
        - - name: test
            templateRef:
              name: artifact-gc-test-wft
              template: main
```

### Logs from the workflow controller

When run independently:

```
2022-11-11 15:30:21	
time="2022-11-11T13:30:21.549Z" level=debug msg="Won't process Workflow since it's completed" key=argo/artifact-gc-test-9kj8h
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.542Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=17005049 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.530Z" level=debug msg="Log changes patch: {\"metadata\":{\"finalizers\":null},\"status\":{\"artifactGCStatus\":{\"podsRecouped\":{\"artifact-gc-test-9kj8h-artgc-wfdel-1685253302\":true}},\"nodes\":{\"artifact-gc-test-9kj8h-707275507\":{\"outputs\":{\"artifacts\":[{\"deleted\":true,\"name\":\"temporary-artifact\",\"path\":\"/tmp/temporary-artifact.txt\",\"s3\":{\"key\":\"temporary-artifact.txt\"}},{\"artifactGC\":{\"strategy\":\"Never\"},\"name\":\"keep-this\",\"path\":\"/tmp/keep-this.txt\",\"s3\":{\"key\":\"keep-this.txt\"}}]}}}}}"
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.530Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.530Z" level=info msg="no remaining artifacts to GC, removing artifact GC finalizer" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.520Z" level=debug msg="deleting WorkflowArtifactGCTask: artifact-gc-test-9kj8h-artgc-wfdel-1685253302-0" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.520Z" level=debug msg="processing WorkflowArtifactGCTask artifact-gc-test-9kj8h-artgc-wfdel-1685253302-0" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.515Z" level=info msg="processing completed Artifact GC Pod 'artifact-gc-test-9kj8h-artgc-wfdel-1685253302'" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.515Z" level=info msg="reconciling artifact-gc pod" message= namespace=argo phase=Succeeded pod=artifact-gc-test-9kj8h-artgc-wfdel-1685253302 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:11	
time="2022-11-11T13:30:11.514Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:01	
time="2022-11-11T13:30:01.526Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=17005049 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:01	
time="2022-11-11T13:30:01.512Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:01	
time="2022-11-11T13:30:01.493Z" level=info msg="creating pod to delete artifacts: artifact-gc-test-9kj8h-artgc-wfdel-1685253302" namespace=argo strategy=OnWorkflowDeletion workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:01	
time="2022-11-11T13:30:01.478Z" level=info msg="Creating Artifact GC Task artifact-gc-test-9kj8h-artgc-wfdel-1685253302-0" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:01	
time="2022-11-11T13:30:01.478Z" level=debug msg="list of artifacts pertaining to template main to WorkflowArtifactGCTask 'artifact-gc-test-9kj8h-artgc-wfdel-1685253302-0': map[artifact-gc-test-9kj8h-707275507:{ArchiveLocation:&ArtifactLocation{ArchiveLogs:nil,S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:s3.amazonaws.com,Bucket:CENSORED},RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,},Key:{{workflow.name}}/{{pod.name}},},Git:nil,HTTP:nil,Artifactory:nil,HDFS:nil,Raw:nil,OSS:nil,GCS:nil,Azure:nil,} Artifacts:map[temporary-artifact:{Name:temporary-artifact Path:/tmp/temporary-artifact.txt Mode:<nil> From: ArtifactLocation:{ArchiveLogs:<nil> S3:&S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,},Key:temporary-artifact.txt,} Git:nil HTTP:nil Artifactory:nil HDFS:nil Raw:nil OSS:nil GCS:nil Azure:nil} GlobalName: Archive:nil Optional:false SubPath: RecurseMode:false FromExpression: ArtifactGC:nil Deleted:false}]}]" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:01	
time="2022-11-11T13:30:01.478Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:01	
time="2022-11-11T13:30:01.478Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:30:01	
time="2022-11-11T13:30:01.476Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:46	
time="2022-11-11T13:29:46.563Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:46	
time="2022-11-11T13:29:46.562Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:36	
time="2022-11-11T13:29:36.560Z" level=info msg="Queueing Succeeded workflow argo/artifact-gc-test-9kj8h for delete in 1m50s due to TTL"
	
2022-11-11 15:29:36	
time="2022-11-11T13:29:36.560Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=17004908 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:36	
time="2022-11-11T13:29:36.547Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:36	
time="2022-11-11T13:29:36.547Z" level=debug msg="No Artifact Search Results returned from strategy OnWorkflowCompletion" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:36	
time="2022-11-11T13:29:36.547Z" level=debug msg="processing Artifact GC Strategy OnWorkflowCompletion" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:36	
time="2022-11-11T13:29:36.547Z" level=debug msg="processing Artifact GC Strategy OnWorkflowCompletion" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:36	
time="2022-11-11T13:29:36.545Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:31	
time="2022-11-11T13:29:31.559Z" level=info msg="cleaning up pod" action=deletePod key=argo/artifact-gc-test-9kj8h-main-707275507/deletePod
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.545Z" level=info msg="Queueing Succeeded workflow argo/artifact-gc-test-9kj8h for delete in 2m0s due to TTL"
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.544Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artifact-gc-test-9kj8h\", UID:\"a4a85c7c-2f17-4b79-804e-5bc5ca5944fe\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"17004838\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeSucceeded' Succeeded node artifact-gc-test-9kj8h"
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.544Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artifact-gc-test-9kj8h\", UID:\"a4a85c7c-2f17-4b79-804e-5bc5ca5944fe\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"17004838\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeSucceeded' Succeeded node artifact-gc-test-9kj8h(0)"
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.544Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=17004838 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.535Z" level=info msg="cleaning up pod" action=deletePod key=argo/artifact-gc-test-9kj8h-1340600742-agent/deletePod
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.530Z" level=debug msg="Log changes patch: {\"metadata\":{\"labels\":{\"workflows.argoproj.io/completed\":\"true\",\"workflows.argoproj.io/phase\":\"Succeeded\"}},\"status\":{\"conditions\":[{\"status\":\"False\",\"type\":\"PodRunning\"},{\"status\":\"True\",\"type\":\"Completed\"}],\"finishedAt\":\"2022-11-11T13:29:26Z\",\"nodes\":{\"artifact-gc-test-9kj8h\":{\"finishedAt\":\"2022-11-11T13:29:26Z\",\"outputs\":{\"artifacts\":[{\"name\":\"temporary-artifact\",\"path\":\"/tmp/temporary-artifact.txt\",\"s3\":{\"key\":\"temporary-artifact.txt\"}},{\"artifactGC\":{\"strategy\":\"Never\"},\"name\":\"keep-this\",\"path\":\"/tmp/keep-this.txt\",\"s3\":{\"key\":\"keep-this.txt\"}}],\"exitCode\":\"0\"},\"phase\":\"Succeeded\"},\"artifact-gc-test-9kj8h-707275507\":{\"finishedAt\":\"2022-11-11T13:29:16Z\",\"outputs\":{\"artifacts\":[{\"name\":\"temporary-artifact\",\"path\":\"/tmp/temporary-artifact.txt\",\"s3\":{\"key\":\"temporary-artifact.txt\"}},{\"artifactGC\":{\"strategy\":\"Never\"},\"name\":\"keep-this\",\"path\":\"/tmp/keep-this.txt\",\"s3\":{\"key\":\"keep-this.txt\"}}],\"exitCode\":\"0\"},\"phase\":\"Succeeded\",\"resourcesDuration\":{\"cpu\":10,\"memory\":10}}},\"phase\":\"Succeeded\"}}"
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.530Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artifact-gc-test-9kj8h\", UID:\"a4a85c7c-2f17-4b79-804e-5bc5ca5944fe\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"17004778\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowSucceeded' Workflow completed"
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="Marking workflow completed" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="node artifact-gc-test-9kj8h finished: 2022-11-11 13:29:26.529661636 +0000 UTC" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="node artifact-gc-test-9kj8h phase Running -> Succeeded" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=debug msg="Executing node artifact-gc-test-9kj8h of Retry is Running" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=debug msg="Evaluating node artifact-gc-test-9kj8h: template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=artifact-gc-test-9kj8h-707275507 old.message= old.phase=Running old.progress=0/1 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="task-result changed" namespace=argo nodeID=artifact-gc-test-9kj8h-707275507 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.529Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:26	
time="2022-11-11T13:29:26.528Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.527Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artifact-gc-test-9kj8h\", UID:\"a4a85c7c-2f17-4b79-804e-5bc5ca5944fe\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"17004778\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artifact-gc-test-9kj8h(0)"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.526Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=17004778 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.511Z" level=debug msg="Log changes patch: {\"status\":{\"conditions\":[{\"status\":\"True\",\"type\":\"PodRunning\"}],\"nodes\":{\"artifact-gc-test-9kj8h-707275507\":{\"message\":null,\"phase\":\"Running\"}}}}"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=debug msg="Skipped pod artifact-gc-test-9kj8h(0) (artifact-gc-test-9kj8h-707275507) creation: already exists" namespace=argo podPhase=Running workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=debug msg="Executing node artifact-gc-test-9kj8h(0) with container template: main\n" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=debug msg="Executing node artifact-gc-test-9kj8h of Retry is Running" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=debug msg="Evaluating node artifact-gc-test-9kj8h: template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=artifact-gc-test-9kj8h-707275507 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.510Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.509Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.509Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=17004700 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.495Z" level=debug msg="Log changes patch: {\"status\":{\"nodes\":{\"artifact-gc-test-9kj8h-707275507\":{\"hostNodeName\":\"ip-192-168-38-170.eu-central-1.compute.internal\",\"message\":\"PodInitializing\"}}}}"
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.491Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.491Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.491Z" level=debug msg="Skipped pod artifact-gc-test-9kj8h(0) (artifact-gc-test-9kj8h-707275507) creation: already exists" namespace=argo podPhase=Pending workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.491Z" level=debug msg="Executing node artifact-gc-test-9kj8h(0) with container template: main\n" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.491Z" level=debug msg="Executing node artifact-gc-test-9kj8h of Retry is Running" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.491Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.491Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.491Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.490Z" level=debug msg="Evaluating node artifact-gc-test-9kj8h: template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.490Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=artifact-gc-test-9kj8h-707275507 old.message="Unschedulable: 0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector." old.phase=Pending old.progress=0/1 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.490Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:29:06	
time="2022-11-11T13:29:06.489Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.616Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.616Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.616Z" level=debug msg="Skipped pod artifact-gc-test-9kj8h(0) (artifact-gc-test-9kj8h-707275507) creation: already exists" namespace=argo podPhase=Pending workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.616Z" level=debug msg="Executing node artifact-gc-test-9kj8h(0) with container template: main\n" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.616Z" level=debug msg="Executing node artifact-gc-test-9kj8h of Retry is Running" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.615Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.615Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.615Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.615Z" level=debug msg="Evaluating node artifact-gc-test-9kj8h: template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.615Z" level=info msg="node unchanged" namespace=argo nodeID=artifact-gc-test-9kj8h-707275507 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.615Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:14	
time="2022-11-11T13:28:14.613Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.612Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=17004220 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.595Z" level=debug msg="Log changes patch: {\"status\":{\"conditions\":[{\"status\":\"False\",\"type\":\"PodRunning\"}],\"nodes\":{\"artifact-gc-test-9kj8h-707275507\":{\"message\":\"Unschedulable: 0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector.\"}}}}"
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=debug msg="Skipped pod artifact-gc-test-9kj8h(0) (artifact-gc-test-9kj8h-707275507) creation: already exists" namespace=argo podPhase=Pending workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=debug msg="Executing node artifact-gc-test-9kj8h(0) with container template: main\n" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=debug msg="Executing node artifact-gc-test-9kj8h of Retry is Running" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.594Z" level=debug msg="Evaluating node artifact-gc-test-9kj8h: template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.593Z" level=info msg="node changed" namespace=argo new.message="Unschedulable: 0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector." new.phase=Pending new.progress=0/1 nodeID=artifact-gc-test-9kj8h-707275507 old.message= old.phase=Pending old.progress=0/1 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.593Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:28:04	
time="2022-11-11T13:28:04.592Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.647Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artifact-gc-test-9kj8h\", UID:\"a4a85c7c-2f17-4b79-804e-5bc5ca5944fe\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"17004165\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node artifact-gc-test-9kj8h"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.647Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=17004165 workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.635Z" level=debug msg="Log changes patch: {\"metadata\":{\"annotations\":{\"workflows.argoproj.io/pod-name-format\":\"v2\"},\"finalizers\":[\"workflows.argoproj.io/artifact-gc\"],\"labels\":{\"workflows.argoproj.io/phase\":\"Running\"}},\"spec\":{\"activeDeadlineSeconds\":14400,\"affinity\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"node-class\",\"operator\":\"In\",\"values\":[\"worker-node\"]}]}]}}},\"artifactGC\":{\"serviceAccountName\":\"argo-workflow\"},\"parallelism\":1000,\"podGC\":{\"strategy\":\"OnWorkflowCompletion\"},\"serviceAccountName\":\"argo-workflow\",\"templateDefaults\":{\"inputs\":{},\"metadata\":{},\"outputs\":{},\"retryStrategy\":{\"limit\":\"1\",\"retryPolicy\":\"OnTransientError\"}},\"ttlStrategy\":{\"secondsAfterCompletion\":120}},\"status\":{\"artifactGCStatus\":{},\"artifactRepositoryRef\":{\"artifactRepository\":{CENSORED},\"default\":true},\"nodes\":{\"artifact-gc-test-9kj8h\":{\"children\":[\"artifact-gc-test-9kj8h-707275507\"],\"displayName\":\"artifact-gc-test-9kj8h\",\"finishedAt\":null,\"id\":\"artifact-gc-test-9kj8h\",\"name\":\"artifact-gc-test-9kj8h\",\"phase\":\"Running\",\"startedAt\":\"2022-11-11T13:27:54Z\",\"templateName\":\"main\",\"templateScope\":\"local/artifact-gc-test-9kj8h\",\"type\":\"Retry\"},\"artifact-gc-test-9kj8h-707275507\":{\"displayName\":\"artifact-gc-test-9kj8h(0)\",\"finishedAt\":null,\"id\":\"artifact-gc-test-9kj8h-707275507\",\"name\":\"artifact-gc-test-9kj8h(0)\",\"phase\":\"Pending\",\"startedAt\":\"2022-11-11T13:27:54Z\",\"templateName\":\"main\",\"templateScope\":\"local/artifact-gc-test-9kj8h\",\"type\":\"Pod\"}},\"phase\":\"Running\",\"startedAt\":\"2022-11-11T13:27:54Z\"}}"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.635Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.635Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.635Z" level=info msg="Created pod: artifact-gc-test-9kj8h(0) (artifact-gc-test-9kj8h-main-707275507)" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.602Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"artifact-gc-test-9kj8h\", UID:\"a4a85c7c-2f17-4b79-804e-5bc5ca5944fe\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"17004161\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowRunning' Workflow Running"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.602Z" level=debug msg="Creating Pod: artifact-gc-test-9kj8h(0) (artifact-gc-test-9kj8h-main-707275507)" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug namespace=argo needLocation=true workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug msg="Executing node artifact-gc-test-9kj8h(0) with container template: main\n" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=info msg="Pod node artifact-gc-test-9kj8h-707275507 initialized Pending" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug msg="Initializing node artifact-gc-test-9kj8h(0): template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=info msg="Retry node artifact-gc-test-9kj8h initialized Running" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug msg="Initializing node artifact-gc-test-9kj8h: template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug msg="Inject a retry node for node artifact-gc-test-9kj8h" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=debug msg="Evaluating node artifact-gc-test-9kj8h: template: *v1alpha1.WorkflowStep (main), boundaryID: " namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.600Z" level=info msg="adding artifact GC finalizer" namespace=argo workflow=artifact-gc-test-9kj8h
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.594Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.594Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.594Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.593Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.592Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.592Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.592Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=artifact-gc-test-9kj8h)" depth=0 tmpl="*v1alpha1.WorkflowStep (main)"
	
2022-11-11 15:27:54	
time="2022-11-11T13:27:54.592Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-9kj8h
```

When run from a WorkflowTemplate:

```
2022-11-11 15:24:03	
time="2022-11-11T13:24:03.318Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-wft-z7txj
2022-11-11 15:24:03	
time="2022-11-11T13:24:03.318Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:53	
time="2022-11-11T13:23:53.507Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=17002758 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:53	
time="2022-11-11T13:23:53.482Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:53	
time="2022-11-11T13:23:53.482Z" level=debug msg="No Artifact Search Results returned from strategy OnWorkflowDeletion" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:53	
time="2022-11-11T13:23:53.482Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:53	
time="2022-11-11T13:23:53.482Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:53	
time="2022-11-11T13:23:53.482Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:36	
time="2022-11-11T13:23:36.875Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=17002609 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:36	
time="2022-11-11T13:23:36.864Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:36	
time="2022-11-11T13:23:36.864Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:31	
time="2022-11-11T13:23:31.877Z" level=info msg="cleaning up pod" action=deletePod key=argo/artifact-gc-test-wft-z7txj-main-648980782/deletePod
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.863Z" level=info msg="Queueing Succeeded workflow argo/artifact-gc-test-wft-z7txj for delete in 2m0s due to TTL"
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.863Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=17002511 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.856Z" level=info msg="cleaning up pod" action=deletePod key=argo/artifact-gc-test-wft-z7txj-1340600742-agent/deletePod
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.851Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.851Z" level=info msg="Marking workflow completed" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.851Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.851Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.850Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.850Z" level=info msg="node artifact-gc-test-wft-z7txj finished: 2022-11-11 13:23:26.850942378 +0000 UTC" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.850Z" level=info msg="node artifact-gc-test-wft-z7txj phase Running -> Succeeded" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.850Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=artifact-gc-test-wft-z7txj-648980782 old.message= old.phase=Running old.progress=0/1 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.850Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:26	
time="2022-11-11T13:23:26.850Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:16	
time="2022-11-11T13:23:16.849Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=17002452 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:16	
time="2022-11-11T13:23:16.835Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:16	
time="2022-11-11T13:23:16.835Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:16	
time="2022-11-11T13:23:16.834Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/1 nodeID=artifact-gc-test-wft-z7txj-648980782 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:16	
time="2022-11-11T13:23:16.834Z" level=info msg="task-result changed" namespace=argo nodeID=artifact-gc-test-wft-z7txj-648980782 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:16	
time="2022-11-11T13:23:16.834Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:16	
time="2022-11-11T13:23:16.834Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:04	
time="2022-11-11T13:23:04.432Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=17002344 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:04	
time="2022-11-11T13:23:04.419Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:04	
time="2022-11-11T13:23:04.419Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:04	
time="2022-11-11T13:23:04.419Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=artifact-gc-test-wft-z7txj-648980782 old.message="Unschedulable: 0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector." old.phase=Pending old.progress=0/1 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:04	
time="2022-11-11T13:23:04.419Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:23:04	
time="2022-11-11T13:23:04.418Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:22:02	
time="2022-11-11T13:22:02.864Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=17001860 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:22:02	
time="2022-11-11T13:22:02.854Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:22:02	
time="2022-11-11T13:22:02.854Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:22:02	
time="2022-11-11T13:22:02.853Z" level=info msg="node changed" namespace=argo new.message="Unschedulable: 0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector." new.phase=Pending new.progress=0/1 nodeID=artifact-gc-test-wft-z7txj-648980782 old.message= old.phase=Pending old.progress=0/1 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:22:02	
time="2022-11-11T13:22:02.853Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:22:02	
time="2022-11-11T13:22:02.853Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.915Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=17001804 workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.901Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.901Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.901Z" level=info msg="Created pod: artifact-gc-test-wft-z7txj(0) (artifact-gc-test-wft-z7txj-main-648980782)" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.868Z" level=info msg="Pod node artifact-gc-test-wft-z7txj-648980782 initialized Pending" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.868Z" level=info msg="Retry node artifact-gc-test-wft-z7txj initialized Running" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.867Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.867Z" level=info msg="adding artifact GC finalizer" namespace=argo workflow=artifact-gc-test-wft-z7txj
	
2022-11-11 15:21:52	
time="2022-11-11T13:21:52.853Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-gc-test-wft-z7txjSh
```

### Logs from in your workflow's wait container

Workflow version:
```
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.723Z" level=info msg="Alloc=9558 TotalAlloc=17364 Sys=23762 NumGC=5 Goroutines=11"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.723Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.723Z" level=info msg="Deadline monitor stopped"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.722Z" level=info msg="Create workflowtaskresults 201"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.708Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/keep-this.tgz"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.708Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/keep-this.tgz
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.708Z" level=info msg="Save artifact" artifactName=keep-this duration=70.155192ms error="<nil>" key=keep-this.txt
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.640Z" level=info msg="Saving file to s3" bucket=CENSORED endpoint=s3.amazonaws.com key=keep-this.txt path=/tmp/argo/outputs/artifacts/keep-this.tgz
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.638Z" level=info msg="Creating minio client using static credentials" endpoint=s3.amazonaws.com
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.638Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/keep-this.tgz, key: keep-this.txt"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.637Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/keep-this.txt.tgz -> /tmp/argo/outputs/artifacts/keep-this.tgz"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.637Z" level=info msg="Copying /tmp/keep-this.txt from container base image layer to /tmp/argo/outputs/artifacts/keep-this.tgz"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.637Z" level=info msg="Staging artifact: keep-this"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.637Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/temporary-artifact.tgz"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.637Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/temporary-artifact.tgz
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.637Z" level=info msg="Save artifact" artifactName=temporary-artifact duration=52.39008ms error="<nil>" key=temporary-artifact.txt
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.595Z" level=info msg="Saving file to s3" bucket=CENSORED endpoint=s3.amazonaws.com key=temporary-artifact.txt path=/tmp/argo/outputs/artifacts/temporary-artifact.tgz
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="Creating minio client using static credentials" endpoint=s3.amazonaws.com
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/temporary-artifact.tgz, key: temporary-artifact.txt"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/temporary-artifact.txt.tgz -> /tmp/argo/outputs/artifacts/temporary-artifact.tgz"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="Copying /tmp/temporary-artifact.txt from container base image layer to /tmp/argo/outputs/artifacts/temporary-artifact.tgz"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="Staging artifact: temporary-artifact"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="Saving output artifacts"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="No output parameters"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
	
2022-11-11 15:29:16	
time="2022-11-11T13:29:16.585Z" level=info msg="Main container completed" error="<nil>"
	
2022-11-11 15:29:07	
time="2022-11-11T13:29:07.584Z" level=info msg="Starting deadline monitor"
	
2022-11-11 15:29:07	
time="2022-11-11T13:29:07.584Z" level=info msg="Executor initialized" deadline="2022-11-11 17:27:54 +0000 UTC" includeScriptOutput=false namespace=argo podName=artifact-gc-test-9kj8h-main-707275507 template="{\"name\":\"main\",\"inputs\":{},\"outputs\":{\"artifacts\":[{\"name\":\"temporary-artifact\",\"path\":\"/tmp/temporary-artifact.txt\",\"s3\":{\"key\":\"temporary-artifact.txt\"}},{\"name\":\"keep-this\",\"path\":\"/tmp/keep-this.txt\",\"s3\":{\"key\":\"keep-this.txt\"},\"artifactGC\":{\"strategy\":\"Never\"}}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"argoproj/argosay:v2\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"can throw this away\\\" \\u003e /tmp/temporary-artifact.txt\\necho \\\"keep this\\\" \\u003e /tmp/keep-this.txt\\n\"],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":false,\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"CENSORED},\"key\":\"artifact-gc-test-9kj8h/artifact-gc-test-9kj8h-main-707275507\"}},\"retryStrategy\":{\"limit\":\"1\",\"retryPolicy\":\"OnTransientError\"}}" version="&Version{Version:v3.4.3,BuildDate:2022-10-31T05:40:15Z,GitCommit:eddb1b78407adc72c08b4ed6be8f52f2a1f1316a,GitTag:v3.4.3,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
	
2022-11-11 15:29:07	
time="2022-11-11T13:29:07.584Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
	
2022-11-11 15:29:07	
time="2022-11-11T13:29:07.581Z" level=info msg="Starting Workflow Executor" version=v3.4.3
```
WorkflowTemplate version:

```
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.112Z" level=info msg="Alloc=7403 TotalAlloc=17382 Sys=24018 NumGC=5 Goroutines=10"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.112Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.112Z" level=info msg="Deadline monitor stopped"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.111Z" level=info msg="Create workflowtaskresults 201"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.091Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/keep-this.tgz"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.091Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/keep-this.tgz
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.091Z" level=info msg="Save artifact" artifactName=keep-this duration=91.423576ms error="<nil>" key=keep-this.txt
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.003Z" level=info msg="Saving file to s3" bucket=CENSORED endpoint=s3.amazonaws.com key=keep-this.txt path=/tmp/argo/outputs/artifacts/keep-this.tgz
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.000Z" level=info msg="Creating minio client using static credentials" endpoint=s3.amazonaws.com
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.000Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/keep-this.tgz, key: keep-this.txt"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.000Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/keep-this.txt.tgz -> /tmp/argo/outputs/artifacts/keep-this.tgz"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.000Z" level=info msg="Copying /tmp/keep-this.txt from container base image layer to /tmp/argo/outputs/artifacts/keep-this.tgz"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.000Z" level=info msg="Staging artifact: keep-this"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.000Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/temporary-artifact.tgz"
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.000Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/temporary-artifact.tgz
	
2022-11-11 15:23:15	
time="2022-11-11T13:23:15.000Z" level=info msg="Save artifact" artifactName=temporary-artifact duration=67.317238ms error="<nil>" key=temporary-artifact.txt
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.940Z" level=info msg="Saving file to s3" bucket=CENSORED endpoint=s3.amazonaws.com key=temporary-artifact.txt path=/tmp/argo/outputs/artifacts/temporary-artifact.tgz
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="Creating minio client using static credentials" endpoint=s3.amazonaws.com
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/temporary-artifact.tgz, key: temporary-artifact.txt"
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/temporary-artifact.txt.tgz -> /tmp/argo/outputs/artifacts/temporary-artifact.tgz"
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="Copying /tmp/temporary-artifact.txt from container base image layer to /tmp/argo/outputs/artifacts/temporary-artifact.tgz"
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="Staging artifact: temporary-artifact"
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="Saving output artifacts"
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="No output parameters"
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
	
2022-11-11 15:23:14	
time="2022-11-11T13:23:14.932Z" level=info msg="Main container completed" error="<nil>"
	
2022-11-11 15:23:06	
time="2022-11-11T13:23:06.930Z" level=info msg="Starting deadline monitor"
	
2022-11-11 15:23:06	
time="2022-11-11T13:23:06.930Z" level=info msg="Executor initialized" deadline="2022-11-11 17:21:52 +0000 UTC" includeScriptOutput=false namespace=argo podName=artifact-gc-test-wft-z7txj-main-648980782 template="{\"name\":\"main\",\"inputs\":{},\"outputs\":{\"artifacts\":[{\"name\":\"temporary-artifact\",\"path\":\"/tmp/temporary-artifact.txt\",\"s3\":{\"key\":\"temporary-artifact.txt\"}},{\"name\":\"keep-this\",\"path\":\"/tmp/keep-this.txt\",\"s3\":{\"key\":\"keep-this.txt\"},\"artifactGC\":{\"strategy\":\"Never\"}}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"argoproj/argosay:v2\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo \\\"can throw this away\\\" \\u003e /tmp/temporary-artifact.txt\\necho \\\"keep this\\\" \\u003e /tmp/keep-this.txt\\n\"],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":false,\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"CENSORED}},\"retryStrategy\":{\"limit\":\"1\",\"retryPolicy\":\"OnTransientError\"}}" version="&Version{Version:v3.4.3,BuildDate:2022-10-31T05:40:15Z,GitCommit:eddb1b78407adc72c08b4ed6be8f52f2a1f1316a,GitTag:v3.4.3,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/amd64,}"
	
2022-11-11 15:23:06	
time="2022-11-11T13:23:06.930Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
	
2022-11-11 15:23:06	
time="2022-11-11T13:23:06.927Z" level=info msg="Starting Workflow Executor" version=v3.4.3
```

### PR DESCRIPTION
**Pull request by juliev0**
Signed-off-by: Julie Vogelmani <julie_vogelman@intuit.com>

Fixes #10015 

This fixes the case where the entire Workflow is based on a WorkflowTemplate and the ArtifactGC strategy is on the Workflow level in the WorkflowTemplate.

The issue was that when searching for artifacts we were looking at `woc.wf` rather than `woc.execWf` (which includes the merged WorkflowTemplate).

### CODE REVIEW

File: workflow/controller/artifact_gc.go [hunk 1]
```diff
@@ -538,6 +534,28 @@ func (woc *wfOperationCtx) allArtifactsDeleted() bool {
...
+			// artifact strategy is either based on overall Workflow ArtifactGC Strategy, or
+			// if it's specified on the individual artifact level that takes priority
+			artifactStrategy := woc.execWf.GetArtifactGCStrategy(&a)
+			if artifactStrategy == strategy && !a.Deleted {
+				results = append(results, wfv1.ArtifactSearchResult{Artifact: a, NodeID: n.ID})
+			}
+		}
+	}
+	return results
+}
```
Comment (juliev0) [inline workflow/controller/artifact_gc.go:557]: use `woc.execWf` to get the strategy defined in the WorkflowTemplate if there is one

File: test/e2e/testdata/artifactgc/artgc-template-2.yaml [hunk 2]
```diff
@@ -0,0 +1,52 @@
+apiVersion: argoproj.io/v1alpha1
+kind: WorkflowTemplate
+metadata:
+  name: artgc-template-2
+spec:
+  artifactGC:
+    strategy: OnWorkflowDeletion 
+  workflowMetadata:
```
Comment (juliev0) [inline test/e2e/testdata/artifactgc/artgc-template-2.yaml:8]: unlike the WorkflowTemplate test that was already in there, this one includes a strategy specified on the Workflow level

File: workflow/controller/artifact_gc.go [hunk 3]
```diff
@@ -151,16 +147,16 @@ func (woc *wfOperationCtx) processArtifactGCStrategy(ctx context.Context, strate
 		}
 		templateName := node.TemplateName
 		if templateName == "" && node.GetTemplateRef() != nil {
-			templateName = node.GetTemplateRef().Name
+			templateName = node.GetTemplateRef().Template
 		}
```
Comment (juliev0) [inline workflow/controller/artifact_gc.go:151]: was accidentally referring to the WorkflowTemplate's Name here rather than the name of the template within the WorkflowTemplate

File: workflow/controller/artifact_gc.go [hunk 4]
```diff
@@ -151,16 +147,16 @@ func (woc *wfOperationCtx) processArtifactGCStrategy(ctx context.Context, strate
...
 		if templateName == "" {
 			return fmt.Errorf("can't process Artifact GC Strategy %s: node %+v has an unnamed template", strategy, node)
 		}
 		template, found := templatesByName[templateName]
 		if !found {
-			template = woc.wf.GetTemplateByName(templateName)
+			template = woc.execWf.GetTemplateByName(templateName)
 			if template == nil {
-				return fmt.Errorf("can't process Artifact GC Strategy %s: template name %q belonging to node %+v not found??", strategy, node.TemplateName, node)
+				return fmt.Errorf("can't process Artifact GC Strategy %s: template name %q belonging to node %+v not found??", strategy, templateName, node)
```
Comment (juliev0) [inline workflow/controller/artifact_gc.go:159]: note: I confirmed that I don't see any more cases of `woc.wf` used in this file that should really be `woc.execWf`

File: workflow/controller/artifact_gc.go [hunk 5]
```diff
@@ -104,11 +104,7 @@ func (woc *wfOperationCtx) processArtifactGCStrategy(ctx context.Context, strate
 	woc.log.Debugf("processing Artifact GC Strategy %s", strategy)
 
 	// Search for artifacts
-	artifactSearchResults := woc.wf.SearchArtifacts(&wfv1.ArtifactSearchQuery{
```
Comment (alexec) [inline workflow/controller/artifact_gc.go:107]: Why not just change to wow.execWF.SearchArtifacts?

Comment (juliev0) [reply workflow/controller/artifact_gc.go:107]: Tried that at first but the execWf doesn’t seem to include the Workflow Status (for node status). Should it?

Comment (alexec) [reply workflow/controller/artifact_gc.go:107]: You're correct, you must inspect `woc.execWF.Spec` and `woc.wf.Status`. The former is what to run, the latter what to update at the end of reconciliation.

You should not query across the two.

Comment (juliev0) [reply workflow/controller/artifact_gc.go:107]: Does this look okay then? (I’m not sure if you’re saying you feel that I’m querying between the two)

Comment (sarabala1979) [reply workflow/controller/artifact_gc.go:107]: @juliev0 Make sure you include the test for workflowdefautls, workflow template

Comment (juliev0) [reply workflow/controller/artifact_gc.go:107]: @sarabala1979 I just ran a couple of tests locally to test WorkflowDefaults. In one, I just used a Workflow by itself and verified that it took the default from WorkflowDefaults. In the second, I used a WorkflowTemplate as well. As discussed, since the workflow-controller-configmap is not being dynamically reloaded, it's difficult to test this as part of the e2e test, since otherwise I need to change `test/e2e/manifests/mixins/workflow-controller-configmap.yaml`, which could have consequences for other e2e tests.

**Review by sarabala1979 — APPROVED** [review]
