### PR TITLE
fix: Fix supplied global workflow parameters, fixes 

### LINKED ISSUE #7563: workflow parameter `valueFrom: supplied: {}` fails to resolve
A workflow template fails to resolve a parameter supplied through the UI 

A workflow template using valueFrom generates an error
```yaml
  arguments:
    parameters:
      - name: name
        valueFrom:
          supplied: {}
```
Changing the parameter definition to an empty `value` works correctly however:

```yaml
  arguments:
    parameters:
      - name: name
        value: ""
```

UI screen:
Screen Shot 2022-01-14 at 11 03 34 AM

Inputs/Outputs with `valueFrom: supplied {}`
Screen Shot 2022-01-14 at 11 03 46 AM

Inputs/Outputs with `value: ""`
Screen Shot 2022-01-14 at 11 08 42 AM

## Summary
We want to force a user to enter a string in the UI for a parameter. Prior to yesterday (Jan 13) our workflowtemplates were functioning correctly. No change has been made to our argo installation (we are using the 3.2 install manifest from https://raw.githubusercontent.com/argoproj/argo-workflows/release-3.2/manifests/install.yaml), and the workflowtemplates have not been modified in weeks.

What happened/what you expected to happen?

`"{{workflow.parameters.name}}"` should resolve to `"bob"`

What version of Argo Workflows are you running?
3.2

Unfortunately the manifest defines the workflow image as `quay.io/argoproj/workflow-controller:latest`, see below for container information

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: start
  namespace: argo
spec:
  arguments:
    parameters:
      - name: name
        # does not work!
        valueFrom:
          supplied: {}
        # this does work
        # value:
        # name: ""
      - name: region
        value: us-east-1
        enum:
          - us-east-1
          - ap-southeast-2
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      steps:
        - - name: create
            arguments:
              parameters:
              - name: greeting
                value: "my name is {{workflow.parameters.name}}"
              - name: region
                value: "{{workflow.parameters.region}}"
            templateRef:
              name: create-start
              template: entrypoint
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-start
  namespace: argo
spec:
  arguments:
    parameters:
    - name: greeting
      valueFrom:
        supplied: {}
    - name: region
      valueFrom:
        supplied: {}
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    inputs:
      parameters:
      - name: greeting
      - name: region
    steps:
      - - name: print
          templateRef:
            name: greet
            template: entrypoint
          arguments:
            parameters:
              - name: greeting
                value: '{{inputs.parameters.greeting}}'
              - name: region
                value: '{{inputs.parameters.region}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: greet
  namespace: argo
spec:
  arguments:
    parameters:
    - name: greeting
      valueFrom:
        supplied: {}
    - name: region
      valueFrom:
        supplied: {}
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    inputs:
      parameters:
      - name: greeting
      - name: region
    script:
      image: ubuntu
      command:
      - bash
      source: |
        set -ex;

        # Fetch Arguments
        DESTINATION="{{inputs.parameters.greeting}}";
        CREATOR="{{inputs.parameters.region}}";
        echo "hello ${GREETING}."
        echo "i am from ${REGION}"
```

What Kubernetes provider are you using?
AWS EKS 1.19.13-eks-8df270

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

pns

Other information:
As of this morning (Jan 14) when running the workflow there are no error messages in the workflow-controller logs. We have two workflow-controller containers running right now with sha 

```workflow-controller@sha256:5027a61dd9c6b47a97b633f896f9d6489b6cd247815b4650951ea2e51333c2cb
workflow-controller@sha256:f9e048f2b4fc7b369ec7566793108137e1af6c8af34a1f3331abcf72ae646009
```

I do not have the sha of the container which was giving error logs yesterday unfortunately

One other possibly related issue: I'm 99% sure that when submitting via the ui using 
```yaml
  arguments:
    parameters:
      - name: namespace
        valueFrom:
          supplied: {}
```

If a user leaves the form blank an error message is supposed to pop up saying that a value must be supplied. This appears to no longer be the case, I can submit the above workflow without entering a `name`. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by dinever**
Signed-off-by: Peixuan Ding <dingpeixuan911@gmail.com>

Hi, this PR fixes an issue where `supplied` workflow parameters are not correctly set in the global parameters. See #7563 for more details.

For example, in the following workflow template, the parameter `name` is supplied by UI or CLI. However, it will not be set in the global parameters because both `valueFrom` and `value` exist at the runtime. The workflow controller only looks for `configMapKeyRef` when `valueFrom` is set.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  arguments:
    parameters:
      - name: name
        valueFrom:
          supplied: {}
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{workflow.parameters.name}}"
```

Fixes #7563, also relates to #7476

Thanks!

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -527,15 +527,13 @@ func (woc *wfOperationCtx) setGlobalParameters(executionParameters wfv1.Argument
...
+		if param.ValueFrom != nil && param.ValueFrom.ConfigMapKeyRef != nil {
+			cmValue, err := common.GetConfigMapValue(woc.controller.configMapInformer, woc.wf.ObjectMeta.Namespace, param.ValueFrom.ConfigMapKeyRef.Name, param.ValueFrom.ConfigMapKeyRef.Key)
+			if err != nil {
+				return fmt.Errorf("failed to set global parameter %s from configmap with name %s and key %s: %w",
+					param.Name, param.ValueFrom.ConfigMapKeyRef.Name, param.ValueFrom.ConfigMapKeyRef.Key, err)
 			}
+			woc.globalParams["workflow.parameters."+param.Name] = cmValue
 		} else {
 			woc.globalParams["workflow.parameters."+param.Name] = param.Value.String()
 		}
```
Comment (dinever) [inline workflow/controller/operator.go:539]: Changed the if/else structure from

```go
if param.ValueFrom != nil {
	if param.ValueFrom.ConfigMapKeyRef != nil {
		// ...
	}
} else {
	woc.globalParams["workflow.parameters."+param.Name] = param.Value.String()
}
```

to

```go
if param.ValueFrom != nil && param.ValueFrom.ConfigMapKeyRef != nil {
	// ...
} else {
	woc.globalParams["workflow.parameters."+param.Name] = param.Value.String()
}
```

Similar to `ProcessArgs`:

https://github.com/argoproj/argo-workflows/blob/dbb1bcfbd4de3295163900509fc624fb7d363b10/workflow/common/util.go#L141-L153

**Review by terrytangyuan — APPROVED** [review]
Thanks for the fix!
