### PR TITLE
fix: Fix the Status update for node with synchronization lock

### LINKED ISSUE #6481: Templates with synchronization behave weird when retried
## Summary 

Templates with synchronization behave weird when retried.

## Diagnostics

What Kubernetes provider are you using?: 
I see this behavior with my CI setup which uses [kind](https://github.com/kubernetes-sigs/kind).
I have also observed this issue with on-premise environment.

What version of Argo Workflows are you running? : 
v3.1.4

What executor are you running? 
k8sapi

### How to reproduce
YAML 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  template: "3"
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-workflow
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: A
        template: sleep
  - name: sleep
    retryStrategy:
      limit: 5
      retryPolicy: Always
    synchronization:
      semaphore:
        configMapKeyRef:
          name: my-config
          key: template
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["sleep 30"]

```

While running a workflow with the above setting, I delete a pod.
```console
$ kubectl delete pods my-workflowbkv6z-1912111522
pod "my-workflowbkv6z-1912111522" deleted
# wait for few seconds
$ kubectl get pods
NAME                                    READY   STATUS              RESTARTS   AGE
my-workflowbkv6z-1912111522             0/2     ContainerCreating   0          2s
$ argo get my-workflowbkv6z
Name:                my-workflowbkv6z
Namespace:           prj-primary
ServiceAccount:      default
Status:              Running
Created:             Wed Aug 04 14:26:50 +0900 (1 minute ago)
Started:             Wed Aug 04 14:26:50 +0900 (1 minute ago)
Duration:            1 minute 14 seconds
Progress:            0/1

STEP                 TEMPLATE  PODNAME                      DURATION  MESSAGE
 ● my-workflowbkv6z  entry                                              
 └─◷ A(0)            sleep     my-workflowbkv6z-1912111522  1m    
```

### Expected behavior
I was expecting a pod with a name different from the original one to be created.
Also, `argo get` should report that a retry has happened.

### Controller log

```console
$ kubectl logs -n argo deploy/workflow-controller
time="2021-08-04T05:35:14Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true
time="2021-08-04T05:35:14Z" level=info msg="cron config" cronSyncPeriod=10s
time="2021-08-04T05:35:14.342Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-08-04T05:35:14.347Z" level=info msg="Get configmaps 200"
time="2021-08-04T05:35:14.350Z" level=info msg="Configuration:\nartifactRepository: {}\ncontainerRuntimeExecutor: k8sapi\ninitialDelay: 0s\nmetricsConfig: {}\nnodeEvents: {}\npodSpecLogStrategy: {}\ntelemetryConfig: {}\n"
time="2021-08-04T05:35:14.350Z" level=info msg="Persistence configuration disabled"
time="2021-08-04T05:35:14.350Z" level=info msg="Starting Workflow Controller" version=untagged
time="2021-08-04T05:35:14.350Z" level=info msg="Workers: workflow: 32, pod: 32, pod cleanup: 4"
time="2021-08-04T05:35:14.351Z" level=info msg="List pods 200"
time="2021-08-04T05:35:14.351Z" level=info msg="List workflowtasksets 403"
time="2021-08-04T05:35:14.351Z" level=info msg="Watch configmaps 200"
time="2021-08-04T05:35:14.352Z" level=info msg="List configmaps 200"
E0804 05:35:14.353755       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:35:14.354Z" level=info msg="Watch configmaps 200"
time="2021-08-04T05:35:14.356Z" level=info msg="Watch pods 200"
time="2021-08-04T05:35:14.369Z" level=info msg="List workflows 200"
time="2021-08-04T05:35:14.370Z" level=info msg="Watch workflows 200"
time="2021-08-04T05:35:14.386Z" level=info msg="List workflowtemplates 200"
time="2021-08-04T05:35:14.387Z" level=info msg="Watch workflowtemplates 200"
time="2021-08-04T05:35:14.452Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-08-04T05:35:14.453Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-08-04T05:35:14.454Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-08-04T05:35:14.456Z" level=info msg="List workflows 200"
time="2021-08-04T05:35:14.461Z" level=info msg="Manager initialized successfully"
I0804 05:35:14.461597       1 leaderelection.go:243] attempting to acquire leader lease argo/workflow-controller...
time="2021-08-04T05:35:14.461Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2021-08-04T05:35:14.462Z" level=info msg="Get leases 404"
time="2021-08-04T05:35:14.464Z" level=info msg="Create leases 201"
I0804 05:35:14.464536       1 leaderelection.go:253] successfully acquired lease argo/workflow-controller
time="2021-08-04T05:35:14.464Z" level=info msg="new leader" id=workflow-controller-65bf8fb7bd-c95rf leader=workflow-controller-65bf8fb7bd-c95rf
time="2021-08-04T05:35:14.464Z" level=info msg="started leading" id=workflow-controller-65bf8fb7bd-c95rf
time="2021-08-04T05:35:14.464Z" level=info msg="Starting CronWorkflow controller"
time="2021-08-04T05:35:14.464Z" level=info msg="Performing periodic GC every 5m0s"
time="2021-08-04T05:35:14.464Z" level=info msg="Persistence disabled - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2021-08-04T05:35:14.464Z" level=info msg="Starting workflow TTL controller (workflowTTLWorkers 4)"
time="2021-08-04T05:35:14.465Z" level=info msg="Started workflow TTL worker"
time="2021-08-04T05:35:14.466Z" level=info msg="Create events 201"
time="2021-08-04T05:35:14.466Z" level=info msg="List workflows 200"
time="2021-08-04T05:35:14.466Z" level=info msg="List workflows 200"
time="2021-08-04T05:35:14.466Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:14.466Z" level=info msg="Watch workflows 200"
time="2021-08-04T05:35:14.466Z" level=info msg="Watch workflows 200"
time="2021-08-04T05:35:14.467Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:14.472Z" level=info msg="List clusterworkflowtemplates 200"
time="2021-08-04T05:35:14.473Z" level=info msg="Watch clusterworkflowtemplates 200"
time="2021-08-04T05:35:14.488Z" level=info msg="List cronworkflows 200"
time="2021-08-04T05:35:14.488Z" level=info msg="Watch cronworkflows 200"
time="2021-08-04T05:35:15.597Z" level=info msg="List workflowtasksets 403"
E0804 05:35:15.597652       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:35:17.926Z" level=info msg="List workflowtasksets 403"
E0804 05:35:17.926453       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:35:19.469Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:19.471Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:23.305Z" level=info msg="List workflowtasksets 403"
E0804 05:35:23.306056       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:35:24.485Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:24.494Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:29.496Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:29.498Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:33.276Z" level=info msg="List workflowtasksets 403"
E0804 05:35:33.276937       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:35:34.507Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:34.509Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:39.515Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:39.521Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:44.537Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:44.547Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:49.223Z" level=info msg="List workflowtasksets 403"
E0804 05:35:49.223594       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:35:49.550Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:49.554Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:54.558Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:54.560Z" level=info msg="Update leases 200"
time="2021-08-04T05:35:59.566Z" level=info msg="Get leases 200"
time="2021-08-04T05:35:59.573Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:04.587Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:04.598Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:09.600Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:09.602Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:14.606Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:14.608Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:16.047Z" level=info msg="List workflowtasksets 403"
E0804 05:36:16.047520       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:36:19.614Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:19.627Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:24.655Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:24.658Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:29.675Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:29.683Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:34.685Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:34.687Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:39.704Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:39.710Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:44.713Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:44.715Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:49.718Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:49.720Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:54.724Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:54.726Z" level=info msg="Update leases 200"
time="2021-08-04T05:36:56.622Z" level=info msg="List workflowtasksets 403"
E0804 05:36:56.622764       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:36:59.731Z" level=info msg="Get leases 200"
time="2021-08-04T05:36:59.733Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:04.739Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:04.741Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:08.134Z" level=info msg="Processing workflow" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.139Z" level=info msg="Get configmaps 404"
time="2021-08-04T05:37:08.139Z" level=warning msg="Non-transient error: configmaps \"artifact-repositories\" not found"
time="2021-08-04T05:37:08.139Z" level=info msg="resolved artifact repository" artifactRepositoryRef=default-artifact-repository
time="2021-08-04T05:37:08.139Z" level=info msg="Updated phase  -> Running" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.139Z" level=info msg="DAG node my-workfloww8pfq initialized Running" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.139Z" level=info msg="All of node my-workfloww8pfq.A dependencies [] completed" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.142Z" level=info msg="Get configmaps 200"
time="2021-08-04T05:37:08.144Z" level=info msg="Create events 201"
time="2021-08-04T05:37:08.145Z" level=info msg="Get configmaps 200"
time="2021-08-04T05:37:08.145Z" level=info msg="prj-primary/ConfigMap/my-config/template acquired by prj-primary/my-workfloww8pfq/my-workfloww8pfq-1725021368 " semaphore=prj-primary/ConfigMap/my-config/template
time="2021-08-04T05:37:08.145Z" level=info msg="Node my-workfloww8pfq.A acquired synchronization lock" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.145Z" level=info msg="Retry node my-workfloww8pfq-1725021368 initialized Running" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.146Z" level=info msg="Pod node my-workfloww8pfq-406076171 initialized Pending" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.161Z" level=info msg="Create pods 201"
time="2021-08-04T05:37:08.162Z" level=info msg="Created pod: my-workfloww8pfq.A(0) (my-workfloww8pfq-406076171)" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.162Z" level=info msg="TaskSet Reconciliation" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.162Z" level=info msg=reconcileAgentPod namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.184Z" level=info msg="Update workflows 200"
time="2021-08-04T05:37:08.192Z" level=info msg="Workflow update successful" namespace=prj-primary phase=Running resourceVersion=879 workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.193Z" level=info msg="Patch workflowtasksets 403"
time="2021-08-04T05:37:08.193Z" level=warning msg="error updating taskset" error="failed patching taskset: workflowtasksets.argoproj.io \"my-workfloww8pfq\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot patch resource \"workflowtasksets\" in API group \"argoproj.io\" in the namespace \"prj-primary\"" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:08.194Z" level=info msg="Create events 201"
time="2021-08-04T05:37:08.195Z" level=info msg="Create events 201"
time="2021-08-04T05:37:09.754Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:09.761Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:14.764Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:14.765Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:18.163Z" level=info msg="Processing workflow" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:18.163Z" level=info msg="Updating node my-workfloww8pfq-406076171 message: ContainerCreating" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:18.166Z" level=info msg="Get configmaps 200"
time="2021-08-04T05:37:18.166Z" level=info msg="Node my-workfloww8pfq.A acquired synchronization lock" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:18.167Z" level=info msg="TaskSet Reconciliation" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:18.167Z" level=info msg=reconcileAgentPod namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:19.775Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:19.780Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:24.783Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:24.786Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:26.258Z" level=info msg="List workflows 200"
time="2021-08-04T05:37:26.259Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=
time="2021-08-04T05:37:29.802Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:29.809Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:34.819Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:34.826Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:39.839Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:39.844Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:39.866Z" level=info msg="Processing workflow" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:39.866Z" level=info msg="Updating node my-workfloww8pfq-406076171 status Pending -> Running" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:39.872Z" level=info msg="Get configmaps 200"
time="2021-08-04T05:37:39.873Z" level=info msg="Node my-workfloww8pfq.A acquired synchronization lock" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:39.873Z" level=info msg="TaskSet Reconciliation" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:39.873Z" level=info msg=reconcileAgentPod namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:44.853Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:44.859Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:49.874Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:49.886Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:53.937Z" level=info msg="List workflowtasksets 403"
E0804 05:37:53.937384       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:37:54.895Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:54.902Z" level=info msg="Update leases 200"
time="2021-08-04T05:37:59.261Z" level=info msg="Processing workflow" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:59.262Z" level=info msg="Updating node my-workfloww8pfq-406076171 status Pending -> Running" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:59.273Z" level=info msg="Get configmaps 200"
time="2021-08-04T05:37:59.274Z" level=info msg="Node my-workfloww8pfq.A acquired synchronization lock" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:59.274Z" level=info msg="TaskSet Reconciliation" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:59.274Z" level=info msg=reconcileAgentPod namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:37:59.907Z" level=info msg="Get leases 200"
time="2021-08-04T05:37:59.911Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:04.919Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:04.925Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:09.934Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:09.940Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:14.949Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:14.956Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:19.974Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:19.976Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:24.980Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:24.982Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:25.859Z" level=info msg="List workflowtasksets 403"
E0804 05:38:25.859489       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
time="2021-08-04T05:38:26.234Z" level=info msg="List workflows 200"
time="2021-08-04T05:38:26.234Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=
time="2021-08-04T05:38:29.985Z" level=info msg="Processing workflow" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:29.985Z" level=info msg="Workflow pod is missing" namespace=prj-primary nodePhase=Pending podName="my-workfloww8pfq.A(0)" recentlyStarted=false workflow=my-workfloww8pfq
time="2021-08-04T05:38:29.988Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:29.988Z" level=info msg="Get configmaps 200"
time="2021-08-04T05:38:29.989Z" level=info msg="Node my-workfloww8pfq.A acquired synchronization lock" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:29.991Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:29.996Z" level=info msg="Create pods 201"
time="2021-08-04T05:38:29.996Z" level=info msg="Created pod: my-workfloww8pfq.A(0) (my-workfloww8pfq-406076171)" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:29.996Z" level=info msg="TaskSet Reconciliation" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:29.996Z" level=info msg=reconcileAgentPod namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:34.997Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:35.004Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:39.997Z" level=info msg="Processing workflow" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:39.998Z" level=info msg="Updating node my-workfloww8pfq-406076171 status Pending -> Running" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:40.006Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:40.006Z" level=info msg="Get configmaps 200"
time="2021-08-04T05:38:40.006Z" level=info msg="Node my-workfloww8pfq.A acquired synchronization lock" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:40.006Z" level=info msg="TaskSet Reconciliation" namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:40.006Z" level=info msg=reconcileAgentPod namespace=prj-primary workflow=my-workfloww8pfq
time="2021-08-04T05:38:40.008Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:45.015Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:45.020Z" level=info msg="Update leases 200"
time="2021-08-04T05:38:50.033Z" level=info msg="Get leases 200"
time="2021-08-04T05:38:50.044Z" level=info msg="Update leases 200"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>
closes #6481 
Tips:

* Maybe add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).
* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.
* If changes were requested, and you've made them, then dismis the review to get it looked at again.
* You can ask for help!

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1731,7 +1731,9 @@ func (woc *wfOperationCtx) executeTemplate(ctx context.Context, nodeName string,
 			}
 		}
 
-		woc.updated = wfUpdated
+		if wfUpdated {
```
Comment (sarabala1979) [inline workflow/controller/operator.go:1734]: The updated value is getting overwrite here.

Comment (alexec) [reply workflow/controller/operator.go:1734]: I assume you mean it is turned back into false? 

Minor suggestion:
```golang
woc.updated = woc.updated || wfUpdated
```

**Review by alexec — APPROVED** [review]

**Comment by sarabala1979** [comment]
yes
