### PR TITLE
fix(controller): Mark workflows wait for semaphore as pending. Fixes #6351

### LINKED ISSUE #6351: Liveness probe fails with 500 and "workflow never reconciled"
Version 3.1.1 is failing a lot for us:

```sh
$ kubectl get pod
NAME                                   READY   STATUS             RESTARTS   AGE
argo-server-895985bb9-fz2hf            1/1     Running            0          13h
workflow-controller-6c79bf6684-8xlbx   0/1     CrashLoopBackOff   83         9h

$ kubectl describe pod workflow-controller-6c79bf6684-8xlbx
[...]
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  4m54s (x251 over 9h)  kubelet  Liveness probe failed: HTTP probe failed with statuscode: 500
  Warning  BackOff    17s (x952 over 8h)    kubelet  Back-off restarting failed container

$ kubectl -n argo logs workflow-controller-6c79bf6684-8xlbx --tail=10
time="2021-07-16T06:50:23.197Z" level=info msg="Get leases 200"
time="2021-07-16T06:50:23.206Z" level=info msg="Update leases 200"
time="2021-07-16T06:50:28.211Z" level=info msg="Get leases 200"
time="2021-07-16T06:50:28.219Z" level=info msg="Update leases 200"
time="2021-07-16T06:50:33.224Z" level=info msg="Get leases 200"
time="2021-07-16T06:50:33.233Z" level=info msg="Update leases 200"
time="2021-07-16T06:50:38.238Z" level=info msg="Get leases 200"
time="2021-07-16T06:50:38.245Z" level=info msg="Update leases 200"
time="2021-07-16T06:50:42.410Z" level=info msg="List workflows 200"
time="2021-07-16T06:50:42.413Z" level=info msg=healthz age=5m0s err="workflow never reconciled: webhook-test-2h4zr" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=

$ curl -si http://localhost:6060/healthz
HTTP/1.1 500 Internal Server Error
Date: Thu, 15 Jul 2021 21:24:52 GMT
Content-Length: 45
Content-Type: text/plain; charset=utf-8

workflow never reconciled: webhook-test-2h4zr

$ kubectl -n e2e get wf webhook-test-2h4zr
NAME                 STATUS   AGE
webhook-test-2h4zr

$ kubectl -n e2e get wf webhook-test-2h4zr -oyaml
[...]
status:
  artifactRepositoryRef:
    default: true
  finishedAt: null
  message: 'Waiting for e2e/ConfigMap/semaphore/all-workflows lock. Lock status: 1/1 '
  progress: 0/0
  startedAt: null
  storedTemplates: [...]
  synchronization:
    semaphore:
      waiting:
      - semaphore: e2e/ConfigMap/semaphore/all-workflows
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>
Fixes #6351

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -230,7 +230,11 @@ func (woc *wfOperationCtx) operate(ctx context.Context) {
 		woc.updated = wfUpdate
 		if !acquired {
 			woc.log.Warn("Workflow processing has been postponed due to concurrency limit")
-			woc.wf.Status.Message = msg
+			phase := woc.wf.Status.Phase
+			if phase == wfv1.WorkflowUnknown {
```
Comment (alexec) [inline workflow/controller/operator.go:234]: @sarabala1979 Is saw strange behaviour here. The workflow had completed (`phase=Failed`) but `acquired=false`. Why did we try and acquire a lock for a completed workflow?

Comment (alexec) [reply workflow/controller/operator.go:234]: I don't understand how this could ever happen. Before operate() is invoked, we check to see if the workflows is completed and return. This should be impossible.

Comment (sarabala1979) [reply workflow/controller/operator.go:234]: it could be failed workflow retry.

**Review by sarabala1979 — APPROVED** [review]

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -229,7 +229,11 @@ func (woc *wfOperationCtx) operate(ctx context.Context) {
...
+				phase = wfv1.WorkflowPending
```
Comment (agilgur5) [inline workflow/controller/operator.go:234]: so this ends up skipping the block on line 253. in particular, `createPDBResource` is skipped in this case. see https://github.com/argoproj/argo-workflows/issues/10178#issuecomment-2068596407.

we really shouldn't be creating resources for a not started Workflow without a lock though, so I'm not sure what the optimal way of fixing this is

Comment (agilgur5) [reply workflow/controller/operator.go:234]: Filed an issue to follow-up on this as I don't have a solution off the top of my head: #12966
