### PR TITLE
fix: send periodic keepalive packets on eventstream connections

### LINKED ISSUE #5006: Recurring UI problems when watching the workflow running
## Summary 

When watching for a just started workflow, I get every 10-20 sec a UI error. This makes the product currently not usable for production because you are interrupted every x seconds in your UI browsing.

Screenshot of the UI:
2021-02-03_18h10_43

From the console:
2021-02-03_18h10_34
In text:
```
GET https://argo-dev.apps.argo-wf.acc.cloud.smals.be/api/v1/workflow-events/openshift-odc?listOptions.fieldSelector=metadata.name=node-network-loss-latest-cfmn8&listOptions.resourceVersion=0 net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
```

## Diagnostics

What Kubernetes provider are you using? 
Openshift 4.5.5 with kubernetes 1.18.3

What version of Argo Workflows are you running? 
2.12.7

Argo server is in server authentication method.

I have to add that since I use Openshift I use the PNS engine and the argo server is exposed with a **route**:
https://docs.openshift.com/container-platform/4.5/networking/routes/route-configuration.html

The error is not workflow related. I have the exact same behavior whatever workflow is in use.

Logs of argo server at the moment of the error:
```
time="2021-02-03T17:25:18.941Z" level=info msg="finished streaming call with code NotFound" error="rpc error: code = NotFound desc = workflows.argoproj.io \"node-network-loss-dev-rx9xp\" not found" grpc.code=NotFound grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-02-03T17:25:18Z" grpc.time_ms=7.023 span.kind=server system=grpc
time="2021-02-03T17:25:20.120Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-02-03T17:24:50Z" grpc.time_ms=30020.98 span.kind=server system=grpc
```

The failing request copy from the browser web console
```
fetch("https://argo-dev.apps.argo-wf.acc.<OBFUSCATED_DOMAIN>/api/v1/workflow-events/openshift-odc?listOptions.fieldSelector=metadata.name=node-network-loss-latest-cfmn8&listOptions.resourceVersion=0", {
  "headers": {
    "accept": "text/event-stream",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "no-cache",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "sec-gpc": "1"
  },
  "referrer": "https://argo-dev.apps.argo-wf.acc.<OBFUSCATED_DOMAIN>/workflows/openshift-odc/node-network-loss-latest-cfmn8?tab=workflow",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by dcherman**
When Argo is operating behind load balancers / ingress controllers that have
an idle timeout configured, it's not uncommon to get disconnected and have
an error shown in the UI if you're looking at a relatively inactive workflow
or workflow list.

In the SSE spec, `:\n` is a sequence that you can send to the client which
should be ignored by the client, so we can use that to periodically send
something in the response without affecting the code in the UI at all.

Fixes #5006

Signed-off-by: Daniel Herman <dherman@factset.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

File: server/workflow/workflow_server.go [hunk 1]
```diff
@@ -204,6 +205,15 @@ func (s *workflowServer) WatchWorkflows(req *workflowpkg.WatchWorkflowsRequest,
 	log.Debug("Piping events to channel")
 	defer log.Debug("Result channel done")
 
+	// Eagerly send the headers so that we can begin our keepalive loop if no results are received
+	// immediately.  Without this, we cannot detect a streaming response, and we can't write to the
+	// response since a subsequent write by the stream causes an error.
+	err = ws.SendHeader(metadata.MD{})
```
Comment (dcherman) [inline server/workflow/workflow_server.go:211]: Would definitely appreciate extra scrutiny on this line - I am not familiar enough with gRPC to know the potential implications of this, though I did test that it seems to continue functioning the same.

Without this, the headers that are set are not sent until the first message is received, however that message could be very delayed if you're on a relatively inactive installation of Argo.  This should force the headers to be flushed to gRPC which then results in the headers being sent to the browser, allowing us to peek at the response to confirm that it's a streaming response and begin our keepalive loop.

File: util/ticker/ticker.go [hunk 2]
```diff
@@ -0,0 +1,33 @@
+package ticker
+
+import (
+	"time"
+)
+
+type Ticker interface {
```
Comment (dcherman) [inline util/ticker/ticker.go:7]: None of the existing mock libs that I found (including the one from apimachinery that is used elsewhere) seems to properly mock the `.Reset()` method on a ticker, so I ended up implementing a small shim to let me mock that out.  If/when they support `.Reset`, we should swap to that.

File: server/apiserver/argoserver.go [hunk 3]
```diff
@@ -302,7 +303,15 @@ func (as *argoServer) newHTTPServer(ctx context.Context, port int, artifactServe
 	mustRegisterGWHandler(workflowarchivepkg.RegisterArchivedWorkflowServiceHandlerFromEndpoint, ctx, gwmux, endpoint, dialOpts)
 	mustRegisterGWHandler(clusterwftemplatepkg.RegisterClusterWorkflowTemplateServiceHandlerFromEndpoint, ctx, gwmux, endpoint, dialOpts)
 
-	mux.HandleFunc("/api/", func(w http.ResponseWriter, r *http.Request) { webhookInterceptor(w, r, gwmux) })
+	apiHandler := http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
+		webhookInterceptor(rw, r, gwmux)
+	})
+
+	if os.Getenv("ENABLE_SSE_KEEPALIVE") != "" {
```
Comment (dcherman) [inline server/apiserver/argoserver.go:310]: I figured it might be good to ship this initially behind a feature flag before releasing it generally, but would be interested to hear opinions

**Comment by dcherman** [comment]
For the lint failure, it seems like `goimports` is removing an import that's actually used (ticker) in that test file.  It does not remove it in the actual source file, so I'm confused why it's doing that here unless I'm missing something.  Even renaming the import unnecessarily to something like `argoticker` does not resolve it.

File: server/apiserver/argoserver.go (hunk 3 above)
Comment (alexec) [reply server/apiserver/argoserver.go:310]: I think on by default rather than off

File: go.mod [hunk 4]
```diff
@@ -21,6 +21,7 @@ require (
 	github.com/emicklei/go-restful v2.15.0+incompatible // indirect
 	github.com/evanphx/json-patch v4.9.0+incompatible
 	github.com/fatih/structs v1.1.0 // indirect
+	github.com/felixge/httpsnoop v1.0.1
```
Comment (alexec) [inline go.mod:24]: can we avoid this new library? if not, what licenses is in under?

File: server/apiserver/keepalive.go [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+
+type tickerFactoryFn func(time.Duration) ticker.Ticker
+
+func serverSentEventKeepaliveMiddleware(next http.Handler, keepaliveInterval time.Duration) http.HandlerFunc {
+	return serverSentEventKeepaliveMiddlewareAux(next, keepaliveInterval, nil, func(d time.Duration) ticker.Ticker {
+		return ticker.NewTicker(d)
+	})
+}
+
+func serverSentEventKeepaliveMiddlewareAux(next http.Handler, keepaliveInterval time.Duration, wg *sync.WaitGroup, tickerFactory tickerFactoryFn) http.HandlerFunc {
```
Comment (alexec) [inline server/apiserver/keepalive.go:22]: can we update StreamForwarder to have this feature instead?

https://github.com/argoproj/pkg/blob/master/grpc/http/forwarders.go#L136

File: go.mod (hunk 4 above)
Comment (dcherman) [reply go.mod:24]: httpsnoop is (at the time of that version) licensed under [the MIT license](https://github.com/felixge/httpsnoop/blob/master/LICENSE.txt)

For the rationale of why I'm using it, check out https://github.com/felixge/httpsnoop#why-this-package-exists.  Originally, I did not use an extra lib and attempted to simply wrap the ResponseWriter, but I ended up causing a slew of errors due to not implementing additional interfaces and not implementing some of the other edge cases mentioned in that link.

File: server/apiserver/keepalive.go (hunk 5 above)
Comment (dcherman) [reply server/apiserver/keepalive.go:22]: I'm open to that and it'd actually simplify the code a bit (no redundant `Content-Type` header checks needed).  The reason that I didn't in this initial implementation was that the stream forwarder is located in a shared package, and I was trying to limit the blast radius of this change to get some initial testing before potentially moving it there.  Happy to do that instead of it's preferable.

Comment (dcherman) [reply server/apiserver/keepalive.go:22]: That said, one potentially large benefit of doing it in the StreamForwarder is I would no longer need `httpsnoop` since I know exactly when data is being written to the response, so I would no longer need to wrap the ResponseWriter at all.

Comment (dcherman) [reply server/apiserver/keepalive.go:22]: https://github.com/argoproj/pkg/pull/35

**Comment by alexec** [comment]
@dcherman do you want to submit a new PR to replace this one?

**Comment by dcherman** [comment]
@alexec Yep.  Can you cut/tag 0.3.1 for `pkg`?  I'll look into making that PR tonight after work

**Comment by alexec** [comment]
> @alexec Yep. Can you cut/tag 0.3.1 for `pkg`? I'll look into making that PR tonight after work

Done. v0.4.0 though.

**Comment by dcherman** [comment]
@alexec Updated.  Any chance we can trigger the 2 e2e workflows that failed?  I think those are flaky tests versus something that I actually broke.

**Review by alexec — APPROVED** [review]
LGTM

**Comment by alexec** [comment]
you've a number of test failures related to logs:

```
    --- FAIL: TestCLISuite/TestLogs (4.80s)
        --- FAIL: TestCLISuite/TestLogs/FollowWorkflowLogs (0.08s)
        --- FAIL: TestCLISuite/TestLogs/FollowPodLogs (0.06s)
        --- FAIL: TestCLISuite/TestLogs/ContainerLogs (0.05s)
        --- FAIL: TestCLISuite/TestLogs/Since (0.05s)
        --- FAIL: TestCLISuite/TestLogs/SinceTime (0.05s)
        --- FAIL: TestCLISuite/TestLogs/TailLines (0.05s)
        --- FAIL: TestCLISuite/TestLogs/CompletedWorkflow (4.28s)
```

It is possible that the tests need updating.

**Review by alexec — CHANGES_REQUESTED** [review]
Please fix the test failures.

**Comment by dcherman** [comment]
Fixed.

File: pkg/apiclient/logs-intermediary.go [hunk 6]
```diff
@@ -25,6 +27,13 @@ func (c *logsIntermediary) Recv() (*workflowpkg.LogEntry, error) {
 	}
 }
 
+func (c *logsIntermediary) SendHeader(metadata.MD) error {
+	// We invoke `SendHeader` in order to eagerly flush headers to allow us to send period
+	// keepalives when using HTTP/1 and Server Sent Events, so we need to implement this here,
+	// though we don't use the meta for anything.
+	return nil
```
Comment (dcherman) [inline pkg/apiclient/logs-intermediary.go:34]: Like the other location, I'd appreciate extra scrutiny here since I'm not familiar enough with gRPC to know what implications this might have

Comment (alexec) [reply pkg/apiclient/logs-intermediary.go:34]: I don't think the intermediary should need do this - they're just glue. If it is needed, I think it probably is needed else where

Comment (dcherman) [reply pkg/apiclient/logs-intermediary.go:34]: This was added because the default implementation of the intermediary just panics - implementing this fixed the test failures since if I understand what they're doing correctly, the intermediaries are passed as the`ws` arg in 

https://github.com/argoproj/argo-workflows/blob/b60ab0387eb2895ccb161890c32213a3538c898d/server/workflow/workflow_server.go#L180

but I'm not going to pretend to know 100% if there is something else I should do here.  We invoke `SendHeader` in the streaming functions because otherwise the Stream Forwarders are not invoked until the first time we receive data which means keepalives won't work.

If there's an alternate suggestion to workaround that, I'm open to suggestions since I don't know much about gRPC at the moment.

**Review by alexec — APPROVED** [review]
