### PR TITLE
fix: Enable realtime metric gc after its workflow is completed. Fixes #12790

### LINKED ISSUE #12790: Real-time metrics disappear while workflow is running when metricTTL is < workflow run time.
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Workflow controller configmap is configured as follows:

```yaml
  metricsConfig: |
    metricsTTL: "3m"
```

I created a workflow that is infinitely sleeping. The workflow template has a metric that just tracks the duration as a real-time gauge metric.

Expected:

The metric is continued to be reported on until the workflow terminates. Once the workflow terminates, the metric should live for another 3 minutes before being cleaned up.

This sounds like the expected behavior based on https://github.com/argoproj/argo-workflows/issues/10503#issuecomment-1481926351

What happened instead:

The metric stopped reporting shortly after the metric TTL while the workflow is still running.

Green = Duration Metric
Yellow = some prometheus metric for the workflow pod, indicating it is not deleted

image

I tested the ttl with various different timings (10m, 20m, 1h) and confirmed the behavior scales with the TTL, though it's not always exactly the ttl time setting (i.e. when ttl is 10m, it can take up to 20m).

We cannot just turn off the metric TTL as that would affect the non-realtime metrics.

I also confirmed that our Prometheus instance was up and running, and that the Argo controller did not shut down (I did observe separately that if the controller gets shut down and a new one comes up, the metrics would not be continued either, but that is a different scenario and seems like a different bug).

### Version

v3.4.10

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sleep
  namespace: argo
spec:
  entrypoint: sleep
  templates:
    - name: sleep
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["while true; do sleep 100000; done"]
      metrics:
        prometheus:
        - name: duration_metric
          help: Duration of metric
          gauge:
            realtime: true
            value: '{{duration}}'
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

{"level":"info","msg":"Processing workflow","namespace":"argo","time":"2024-03-12T21:53:59.861Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Updated phase  -\u003e Running","namespace":"argo","time":"2024-03-12T21:53:59.965Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Pod node sleep-8ftls initialized Pending","namespace":"argo","time":"2024-03-12T21:53:59.966Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Created pod: sleep-8ftls (sleep-8ftls)","namespace":"argo","time":"2024-03-12T21:54:00.067Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"argo","time":"2024-03-12T21:54:00.067Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"reconcileAgentPod","namespace":"argo","time":"2024-03-12T21:54:00.067Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Workflow update successful","namespace":"argo","phase":"Running","resourceVersion":"398814","time":"2024-03-12T21:54:00.098Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Processing workflow","namespace":"argo","time":"2024-03-12T21:54:10.068Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Task-result reconciliation","namespace":"argo","numObjs":0,"time":"2024-03-12T21:54:10.068Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"node changed","namespace":"argo","new.message":"","new.phase":"Running","new.progress":"0/1","nodeID":"sleep-8ftls","old.message":"","old.phase":"Pending","old.progress":"0/1","time":"2024-03-12T21:54:10.069Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"argo","time":"2024-03-12T21:54:10.069Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"reconcileAgentPod","namespace":"argo","time":"2024-03-12T21:54:10.069Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Workflow update successful","namespace":"argo","phase":"Running","resourceVersion":"399005","time":"2024-03-12T21:54:10.100Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Processing workflow","namespace":"argo","time":"2024-03-12T21:54:20.101Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"Task-result reconciliation","namespace":"argo","numObjs":0,"time":"2024-03-12T21:54:20.102Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"node unchanged","namespace":"argo","nodeID":"sleep-8ftls","time":"2024-03-12T21:54:20.102Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"argo","time":"2024-03-12T21:54:20.102Z","workflow":"sleep-8ftls"}
{"level":"info","msg":"reconcileAgentPod","namespace":"argo","time":"2024-03-12T21:54:20.102Z","workflow":"sleep-8ftls"}
```

### Logs from in your workflow's wait container

```text
{"level":"info","msg":"Starting Workflow Executor","time":"2024-03-12T21:54:02.642Z","version":"untagged"}
{"Duration":1000000000,"Factor":1.6,"Jitter":0.5,"Steps":5,"level":"info","msg":"Using executor retry strategy","time":"2024-03-12T21:54:02.645Z"}
{"deadline":"0001-01-01T00:00:00Z","includeScriptOutput":false,"level":"info","msg":"Executor initialized","namespace":"argo","podName":"sleep-8ftls","template":"{\"name\":\"sleep\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"while true; do sleep 100000; done\"],\"resources\":{}},\"podSpecPatch\":\"{\\\"enableServiceLinks\\\": false}\\n\",\"metrics\":{\"prometheus\":[{\"name\":\"duration_metric\",\"help\":\"Duration of metric\",\"gauge\":{\"value\":\"{{duration}}\",\"realtime\":true}}]}}","time":"2024-03-12T21:54:02.645Z","version":"\u0026Version{Version:untagged,BuildDate:2024-03-01T06:42:25Z,GitCommit:unknown,GitTag:untagged,GitTreeState:clean,GoVersion:go1.21.7,Compiler:gc,Platform:linux/amd64,}"}
{"level":"info","msg":"Starting deadline monitor","time":"2024-03-12T21:54:02.645Z"}
{"level":"info","msg":"Alloc=6803 TotalAlloc=13592 Sys=20069 NumGC=6 Goroutines=7","time":"2024-03-12T21:59:02.646Z"}
```

### PR DESCRIPTION
**Pull request by jswxstw**
Fixes #12790 

### Motivation

Realtime metrics may be cleaned up, even if the workflow is still running.

### Modifications

Adding two boolean value: `realtime` and `complete` in metric to indicate whether the metric is realtime type and whether it is completed.
Enable realtime metric gc only after its workflow is completed.

### Verification

local test and UT

### CODE REVIEW

File: workflow/metrics/metrics.go [hunk 1]
```diff
@@ -42,6 +42,8 @@ func (s ServerConfig) SameServerAs(other ServerConfig) bool {
 type metric struct {
 	metric      prometheus.Metric
 	lastUpdated time.Time
+	realtime    bool
```
Comment (Joibel) [inline workflow/metrics/metrics.go:45]: metric.IsRealtime() does this already, I'm not sure we should be storing this.

File: workflow/metrics/metrics.go [hunk 2]
```diff
@@ -153,6 +155,23 @@ func (m *Metrics) StopRealtimeMetricsForKey(key string) {
 		return
 	}
 
+	realtimeMetrics := m.workflows[key]
+	for _, metric := range realtimeMetrics {
+		if realtimeMetric, ok := m.customMetrics[metric]; ok {
+			realtimeMetric.completed = true
```
Comment (Joibel) [inline workflow/metrics/metrics.go:161]: Should this also update `lastUpdated` so that the metric lives TTL seconds beyond the end of the workflow rather than potentially ending immediately? It feels likely this would have been set recently, but this would ensure it.

File: workflow/metrics/metrics.go [hunk 3]
```diff
@@ -153,6 +155,23 @@ func (m *Metrics) StopRealtimeMetricsForKey(key string) {
...
+			m.customMetrics[metric] = realtimeMetric
```
Comment (Joibel) [inline workflow/metrics/metrics.go:162]: What is this line doing, shouldn't it already be in this array?

File: workflow/metrics/server.go [hunk 4]
```diff
@@ -138,7 +138,11 @@ func (m *Metrics) garbageCollector(ctx context.Context) {
 			return
 		case <-ticker.C:
 			for key, metric := range m.customMetrics {
-				if time.Since(metric.lastUpdated) > m.metricsConfig.TTL {
+				if metric.realtime {
```
Comment (Joibel) [inline workflow/metrics/server.go:141]: I'd prefer this as
```
if time.Since(metric.lastUpdated) > m.metricsConfig.TTL {
  switch {
    case metric.metric.IsRealtime() && metric.completed:
        delete(m.customMetrics, key)
    case !metric.metric.IsRealtime():
        delete(m.customMetrics, key)
  }
}
```

Or perhaps read IsRealtime() just once and cache, but test TTL because it's the primary test here. The result is identical, I'm aiming for understandability.

**Review by Joibel — CHANGES_REQUESTED** [review]

File: workflow/metrics/metrics.go (hunk 1 above)
Comment (jswxstw) [reply workflow/metrics/metrics.go:45]: `IsRealtime()` is in `wfv1.Prometheus`, but metric here is `prometheus.Metric` and it does not have this function.

File: workflow/metrics/metrics.go (hunk 2 above)
Comment (jswxstw) [reply workflow/metrics/metrics.go:161]: `lastUpdated` of the metric has been updated in workflow operation, so it is no need to update it again in `persistUpdates`.

File: workflow/metrics/metrics.go (hunk 3 above)
Comment (jswxstw) [reply workflow/metrics/metrics.go:162]: The value of `customMetrics` map is `struct` type, not a pointer type, so `realtimeMetric` is actually a copy and I need to update it to the map again.

File: workflow/metrics/server.go (hunk 4 above)
Comment (jswxstw) [reply workflow/metrics/server.go:141]: I originally considered writing it like you did, but when it comes to realtime metrics that are not yet complete, there's no need to calculate whether they exceed the TTL, which can save some time.
How do you think about it?

File: workflow/metrics/metrics.go (hunk 1 above)
Comment (Joibel) [reply workflow/metrics/metrics.go:45]: Ah, yep.

File: workflow/metrics/metrics.go (hunk 3 above)
Comment (Joibel) [reply workflow/metrics/metrics.go:162]: Grr, I hate that pattern. Understood.

File: workflow/metrics/metrics.go (hunk 2 above)
Comment (Joibel) [reply workflow/metrics/metrics.go:161]: Ok.

File: workflow/metrics/server.go (hunk 4 above)
Comment (Joibel) [reply workflow/metrics/server.go:141]: I'd prefer readability and understandability over performance here. It's not performance critical nor happening very frequently.

Comment (jswxstw) [reply workflow/metrics/server.go]: Got it, done.

File: workflow/metrics/metrics_test.go [hunk 5]
```diff
@@ -112,6 +112,10 @@ func TestMetricGC(t *testing.T) {
 	if assert.NoError(t, err) {
 		assert.Len(t, m.customMetrics, 1)
 	}
+	err = m.UpsertCustomMetric("realtime_metric", "workflow-uid", newCounter("test", "test", nil), true)
```
Comment (Joibel) [inline workflow/metrics/metrics_test.go:115]: I can see what you're doing with this test, but without this diff to read this test is slightly obscure. I know overlapping the two tests in time is good for speed of the run, but I'd still prefer to do the whole test isolated from the previous test for understandability.

**Review by Joibel — CHANGES_REQUESTED** [review]

File: workflow/metrics/metrics_test.go (hunk 5 above)
Comment (jswxstw) [reply workflow/metrics/metrics_test.go]: Ok, I add a new test: `TestRealtimeMetricGC`.

**Review by Joibel — APPROVED** [review]
Thanks for your patience. LGTM
