### PR TITLE
fix(controller): Only clean-up pod when both main and wait containers have terminated. Fixes #5981

### LINKED ISSUE #5981: Workflow of Workflows example does not work on V3.1-rc5
## Summary 

Problem running workflow of workflows (https://argoproj.github.io/argo-workflows/workflow-of-workflows/).
Following the instructions, parent workflow fails with 

```
time="2021-05-24T10:47:20.969Z" level=info msg="Starting Workflow Executor" executorType=emissary version=v3.1.0-rc5
time="2021-05-24T10:47:20.973Z" level=info msg="Executor (version: v3.1.0-rc5, build_date: 2021-05-17T21:32:14Z) initialized (pod: argo/workflow-of-workflows-bf4m5-3399545254) with template:\n{\"name\":\"triggerWorkflowUsingResourceWithoutArgument\",\"inputs\":{\"parameters\":[{\"name\":\"workflowtemplate\",\"value\":\"workflow-template-submittable\"}]},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"create\",\"manifest\":\"apiVersion: argoproj.io/v1alpha1\\nkind: Workflow\\nmetadata:\\n  generateName: workflow-of-workflows-1-\\nspec:\\n  workflowTemplateRef:\\n    name: workflow-template-submittable\\n\",\"successCondition\":\"status.phase == Succeeded\",\"failureCondition\":\"status.phase in (Failed, Error)\"},\"archiveLocation\":{\"archiveLogs\":true,\"s3\":{\"endpoint\":\"minio:9000\",\"bucket\":\"my-bucket\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"my-minio-cred\",\"key\":\"accesskey\"},\"secretKeySecret\":{\"name\":\"my-minio-cred\",\"key\":\"secretkey\"},\"key\":\"workflow-of-workflows-bf4m5/workflow-of-workflows-bf4m5-3399545254\"}}}"
time="2021-05-24T10:47:20.973Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2021-05-24T10:47:20.973Z" level=info msg="kubectl create -f /tmp/manifest.yaml -o json"
time="2021-05-24T10:47:21.973Z" level=info msg="Resource: argo/Workflow.argoproj.io/workflow-of-workflows-1-wlkwg. SelfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/workflow-of-workflows-1-wlkwg"
time="2021-05-24T10:47:21.973Z" level=info msg="Starting SIGUSR2 signal monitor"
time="2021-05-24T10:47:21.973Z" level=info msg="Waiting for conditions: status.phase==Succeeded"
time="2021-05-24T10:47:21.973Z" level=info msg="Failing for conditions: status.phase in (Error,Failed)"
time="2021-05-24T10:47:21.980Z" level=info msg="Get workflows 200"
time="2021-05-24T10:47:21.980Z" level=info msg="{\"apiVersion\":\"argoproj.io/v1alpha1\",\"kind\":\"Workflow\",\"metadata\":{\"creationTimestamp\":\"2021-05-24T10:47:21Z\",\"generateName\":\"workflow-of-workflows-1-\",\"generation\":1,\"managedFields\":[{\"apiVersion\":\"argoproj.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:generateName\":{}},\"f:spec\":{\".\":{},\"f:workflowTemplateRef\":{}}},\"manager\":\"kubectl-create\",\"operation\":\"Update\",\"time\":\"2021-05-24T10:47:21Z\"}],\"name\":\"workflow-of-workflows-1-wlkwg\",\"namespace\":\"argo\",\"resourceVersion\":\"30897600\",\"selfLink\":\"/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/workflow-of-workflows-1-wlkwg\",\"uid\":\"6e03bdab-8b88-4e06-b898-d9f8bd0c4831\"},\"spec\":{\"workflowTemplateRef\":{\"name\":\"workflow-template-submittable\"}}}\n"
time="2021-05-24T10:47:21.980Z" level=info msg="failure condition '{status.phase in [Error Failed]}' evaluated false"
time="2021-05-24T10:47:21.980Z" level=info msg="success condition '{status.phase == [Succeeded]}' evaluated false"
time="2021-05-24T10:47:21.980Z" level=info msg="0/1 success conditions matched"
time="2021-05-24T10:47:21.980Z" level=info msg="Waiting for resource Workflow.argoproj.io/workflow-of-workflows-1-wlkwg in namespace argo resulted in retryable error: Neither success condition nor the failure condition has been matched. Retrying..."
time="2021-05-24T10:47:26.984Z" level=info msg="Get workflows 200"
time="2021-05-24T10:47:26.984Z" level=info msg="{\"apiVersion\":\"argoproj.io/v1alpha1\",\"kind\":\"Workflow\",\"metadata\":{\"creationTimestamp\":\"2021-05-24T10:47:21Z\",\"generateName\":\"workflow-of-workflows-1-\",\"generation\":2,\"labels\":{\"workflows.argoproj.io/phase\":\"Running\"},\"managedFields\":[{\"apiVersion\":\"argoproj.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:generateName\":{}},\"f:spec\":{\".\":{},\"f:workflowTemplateRef\":{}}},\"manager\":\"kubectl-create\",\"operation\":\"Update\",\"time\":\"2021-05-24T10:47:21Z\"},{\"apiVersion\":\"argoproj.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/phase\":{}}},\"f:spec\":{\"f:arguments\":{}},\"f:status\":{\".\":{},\"f:artifactRepositoryRef\":{},\"f:finishedAt\":{},\"f:nodes\":{},\"f:phase\":{},\"f:progress\":{},\"f:startedAt\":{},\"f:storedTemplates\":{},\"f:storedWorkflowTemplateSpec\":{}}},\"manager\":\"workflow-controller\",\"operation\":\"Update\",\"time\":\"2021-05-24T10:47:21Z\"}],\"name\":\"workflow-of-workflows-1-wlkwg\",\"namespace\":\"argo\",\"resourceVersion\":\"30897605\",\"selfLink\":\"/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/workflow-of-workflows-1-wlkwg\",\"uid\":\"6e03bdab-8b88-4e06-b898-d9f8bd0c4831\"},\"spec\":{\"arguments\":{},\"workflowTemplateRef\":{\"name\":\"workflow-template-submittable\"}},\"status\":{\"artifactRepositoryRef\":{\"configMap\":\"artifact-repositories\",\"key\":\"default-v1\",\"namespace\":\"argo\"},\"finishedAt\":null,\"nodes\":{\"workflow-of-workflows-1-wlkwg\":{\"displayName\":\"workflow-of-workflows-1-wlkwg\",\"finishedAt\":null,\"id\":\"workflow-of-workflows-1-wlkwg\",\"inputs\":{\"parameters\":[{\"name\":\"message\",\"value\":\"hello world\"}]},\"name\":\"workflow-of-workflows-1-wlkwg\",\"phase\":\"Pending\",\"progress\":\"0/1\",\"startedAt\":\"2021-05-24T10:47:21Z\",\"templateName\":\"whalesay-template\",\"templateScope\":\"local/\",\"type\":\"Pod\"}},\"phase\":\"Running\",\"progress\":\"0/1\",\"startedAt\":\"2021-05-24T10:47:21Z\",\"storedTemplates\":{\"namespaced/workflow-template-submittable/whalesay-template\":{\"container\":{\"args\":[\"{{inputs.parameters.message}}\"],\"command\":[\"cowsay\"],\"image\":\"docker/whalesay\",\"name\":\"\",\"resources\":{}},\"inputs\":{\"parameters\":[{\"name\":\"message\"}]},\"metadata\":{},\"name\":\"whalesay-template\",\"outputs\":{}}},\"storedWorkflowTemplateSpec\":{\"arguments\":{\"parameters\":[{\"name\":\"message\",\"value\":\"hello world\"}]},\"entrypoint\":\"whalesay-template\",\"templates\":[{\"container\":{\"args\":[\"{{inputs.parameters.message}}\"],\"command\":[\"cowsay\"],\"image\":\"docker/whalesay\",\"name\":\"\",\"resources\":{}},\"inputs\":{\"parameters\":[{\"name\":\"message\"}]},\"metadata\":{},\"name\":\"whalesay-template\",\"outputs\":{}}],\"workflowTemplateRef\":{\"name\":\"workflow-template-submittable\"}}}}\n"
time="2021-05-24T10:47:26.985Z" level=info msg="failure condition '{status.phase in [Error Failed]}' evaluated false"
time="2021-05-24T10:47:26.985Z" level=info msg="success condition '{status.phase == [Succeeded]}' evaluated false"
time="2021-05-24T10:47:26.985Z" level=info msg="0/1 success conditions matched"
time="2021-05-24T10:47:26.985Z" level=info msg="Waiting for resource Workflow.argoproj.io/workflow-of-workflows-1-wlkwg in namespace argo resulted in retryable error: Neither success condition nor the failure condition has been matched. Retrying..."
Error: signal: terminated
```

## Diagnostics

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 
V3.1-rc5

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Emissary

[child-wf.yaml.txt](https://github.com/argoproj/argo-workflows/files/6531776/child-wf.yaml.txt)
[parent-wf.yaml.txt](https://github.com/argoproj/argo-workflows/files/6531777/parent-wf.yaml.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by terrytangyuan**
Caught a bug while debugging issues with https://github.com/argoproj/argo-workflows/pull/6014. Also fixes #5981. 

For resource templates, main container is used as a wait container. We need to check its termination status before queue the pod for cleanup. Otherwise, when `cleanUpPod` is called during node assessment/reconciliation, the main container would have been killed by clean-up and then wf is marked as failed even though the pod is succeeded (if wf status update happens a little late than pod the cleanup, which explains why builds in https://github.com/argoproj/argo-workflows/pull/6014 only fail occasionally).

Example controller log from PNS test-executor in https://github.com/argoproj/argo-workflows/runs/2676799345:
```
 controller | time="2021-05-26T16:25:15.758Z" level=info msg="Processing workflow" namespace=argo workflow=k8s-resource-tmpl-with-wf-qvl62
 controller | time="2021-05-26T16:25:15.760Z" level=info msg="Get configmaps 200"
 controller | time="2021-05-26T16:25:15.760Z" level=info msg="Updating node k8s-resource-tmpl-with-wf-qvl62 status Pending -> Running" namespace=argo workflow=k8s-resource-tmpl-with-wf-qvl62
 controller | time="2021-05-26T16:25:15.766Z" level=info msg="cleaning up pod" action=terminateContainers key=argo/k8s-resource-tmpl-with-wf-qvl62/terminateContainers
 controller | time="2021-05-26T16:25:15.766Z" level=info msg="https://127.0.0.1:6443/api/v1/namespaces/argo/pods/k8s-resource-tmpl-with-wf-qvl62/exec?command=%2Fbin%2Fsh&command=-c&command=kill+-s15+--+-1&container=main&stderr=true&stdout=true&tty=false"
 controller | time="2021-05-26T16:25:15.770Z" level=info msg="Update workflows 200"
 controller | time="2021-05-26T16:25:15.770Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1092 workflow=k8s-resource-tmpl-with-wf-qvl62
 controller | time="2021-05-26T16:25:15.774Z" level=info msg="Create events 201"
 controller | time="2021-05-26T16:25:15.785Z" level=info msg="Create pods/exec 101"
 controller | time="2021-05-26T16:25:16.772Z" level=info msg="Processing workflow" namespace=argo workflow=k8s-resource-tmpl-with-wf-qvl62
 controller | time="2021-05-26T16:25:16.774Z" level=info msg="Get configmaps 200"
 controller | time="2021-05-26T16:25:16.774Z" level=info msg="Pod failed: Error (exit code 143)" displayName=k8s-resource-tmpl-with-wf-qvl62 namespace=argo pod=k8s-resource-tmpl-with-wf-qvl62 templateName=main workflow=k8s-resource-tmpl-with-wf-qvl62
```

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@alexec I tested that this change won't break master branch's build by https://github.com/argoproj/argo-workflows/pull/6014/commits/b9bee00326ce66d5c0bb2f95780535723ebc68ce in the other PR. Is that sufficient testing?

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1210,7 +1210,7 @@ func getExitCode(pod *apiv1.Pod) *int32 {
 
 func (woc *wfOperationCtx) cleanUpPod(pod *apiv1.Pod) {
 	for _, c := range pod.Status.ContainerStatuses {
-		if c.Name == common.WaitContainerName && c.State.Terminated == nil {
+		if (c.Name == common.WaitContainerName || c.Name == common.MainContainerName) && c.State.Terminated == nil {
```
Comment (alexec) [inline workflow/controller/operator.go:1213]: the goal of this code is to kill sidecar container, but I think checking just the name is wrong, I think you need to use `IsMainContainerName`

**Review by alexec — CHANGES_REQUESTED** [review]

File: workflow/controller/operator.go (hunk 1 above)
Comment (terrytangyuan) [reply workflow/controller/operator.go]: Updated.

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -1208,9 +1208,9 @@ func getExitCode(pod *apiv1.Pod) *int32 {
 	return nil
 }
 
-func (woc *wfOperationCtx) cleanUpPod(pod *apiv1.Pod) {
+func (woc *wfOperationCtx) cleanUpPod(pod *apiv1.Pod, tmpl wfv1.Template) {
 	for _, c := range pod.Status.ContainerStatuses {
-		if (c.Name == common.WaitContainerName || c.Name == common.MainContainerName) && c.State.Terminated == nil {
+		if (c.Name == common.WaitContainerName || tmpl.IsMainContainerName(c.Name)) && c.State.Terminated == nil {
```
Comment (alexec) [inline workflow/controller/operator.go:1213]: this logic here is confusing to me, I think we want to terminate the containers, if the main and wait containers have exited, is there a better way to formalize that?

Comment (terrytangyuan) [reply workflow/controller/operator.go]: Agree it's confusing. Also currently we are calling `woc.queuePodForCleanup` multiple times which is unnecessary. I've refactored a bit.

File: workflow/controller/operator.go [hunk 3]
```diff
@@ -1208,19 +1208,20 @@ func getExitCode(pod *apiv1.Pod) *int32 {
 	return nil
 }
 
-func (woc *wfOperationCtx) cleanUpPod(pod *apiv1.Pod) {
+func (woc *wfOperationCtx) cleanUpPod(pod *apiv1.Pod, tmpl wfv1.Template) {
+	var toCleanPod bool
```
Comment (alexec) [inline workflow/controller/operator.go:1212]: I'm not a fan of "to" or "do" variables, as they seem to greatly increase the complexity of the code and produce bugs (I'm not sure why, somewhat anecdotal, and I'd need to be a CompSci PHD to produce the analysis). 

Instead, put the logic into its own func. That can then be unit tested.

**Review by alexec — CHANGES_REQUESTED** [review]

File: workflow/controller/operator.go (hunk 3 above)
Comment (terrytangyuan) [reply workflow/controller/operator.go]: That makes sense. I just moved this to its own function and added unit tests.

File: workflow/controller/operator.go [hunk 4]
```diff
@@ -1098,7 +1098,7 @@ func (woc *wfOperationCtx) assessNodeStatus(pod *apiv1.Pod, node *wfv1.NodeStatu
 			newDaemonStatus = pointer.BoolPtr(true)
 			woc.log.Infof("Processing ready daemon pod: %v", pod.ObjectMeta.SelfLink)
 		}
-		woc.cleanUpPod(pod)
+		woc.queuePodForCleanup(pod, tmpl)
```
Comment (alexec) [inline workflow/controller/operator.go:1101]: can you leave this func's name uncnhanged, we'll want to back-port to v3.0 and this could create merge conflicts

File: workflow/controller/operator.go [hunk 5]
```diff
@@ -1208,24 +1208,22 @@ func getExitCode(pod *apiv1.Pod) *int32 {
 	return nil
 }
 
-func (woc *wfOperationCtx) cleanUpPod(pod *apiv1.Pod) {
+func cleanUpPod(pod *apiv1.Pod, tmpl wfv1.Template) bool {
```
Comment (alexec) [inline workflow/controller/operator.go:1211]: maybe call this 'podHasContainerNeedingTermination'?

File: workflow/controller/operator.go (hunk 4 above)
Comment (terrytangyuan) [reply workflow/controller/operator.go]: Done. Although the additional arg `tmpl` is needed to work with `tmpl.IsMainContainerName` in case `ContainerSet` is used. Would that be okay?

**Review by alexec — APPROVED** [review]
