### PR TITLE
fix: improve get archived workflow query performance during controller estimation. Fixes #13382

### LINKED ISSUE #13382: Slow Query Occurred in workflow-controller
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I have confirmed that the following logs frequently occur from the workflow-controller. After downgrading to version v3.4.17, the slow query issue did not occur.
I have not confirmed version 3.5.8 yet, but based on the [differences](https://github.com/argoproj/argo-workflows/compare/v3.5.7...v3.5.8), it seems likely that the same issue will occur.

- DB: Google Cloud SQL (PostgreSQL)
- Data Size:
  - argo_archived_workflows: ~1.7 million rows
  - argo_archived_workflows_labels: ~10 million rows
- workflow-controller-configmap
  - archiveTTL: 90d
```
workflow-controller 	Query:          SELECT name, namespace, uid, phase, startedat, finishedat, coalesce((workflow::json)->'metadata'->>'labels', '{}') as labels, coalesce((workflow::json)->'metadata'->>'annotations', '{}') as annotations, coalesce((workflow::json)->'status'->>'progress', '') as progress FROM "argo_archived_workflows" WHERE (("clustername" = $1 AND "instanceid" = $2) AND "namespace" = $3 AND exists (select 1 from argo_archived_workflows_labels where clustername = argo_archived_workflows.clustername and uid = argo_archived_workflows.uid and name = 'workflows.argoproj.io/cron-workflow' and value = 'uuid-my-cwf-name') AND exists (select 1 from argo_archived_workflows_labels where clustername = argo_archived_workflows.clustername and uid = argo_archived_workflows.uid and name = 'workflows.argoproj.io/phase' and value = 'Succeeded')) ORDER BY "startedat" DESC LIMIT 1
workflow-controller 	Arguments:      []interface {}{"default", "", "my-namespace"}
workflow-controller 	Stack:
workflow-controller 		fmt.(*pp).handleMethods@/usr/local/go/src/fmt/print.go:673
workflow-controller 		fmt.(*pp).printArg@/usr/local/go/src/fmt/print.go:756
workflow-controller 		fmt.(*pp).doPrint@/usr/local/go/src/fmt/print.go:1211
workflow-controller 		fmt.Append@/usr/local/go/src/fmt/print.go:289
workflow-controller 		log.(*Logger).Print.func1@/usr/local/go/src/log/log.go:261
workflow-controller 		log.(*Logger).output@/usr/local/go/src/log/log.go:238
workflow-controller 		log.(*Logger).Print@/usr/local/go/src/log/log.go:260
workflow-controller 		github.com/argoproj/argo-workflows/v3/persist/sqldb.(*workflowArchive).ListWorkflows@/go/src/github.com/argoproj/argo-workflows/persist/sqldb/workflow_archive.go:166
workflow-controller 		github.com/argoproj/argo-workflows/v3/workflow/controller/estimation.(*estimatorFactory).NewEstimator@/go/src/github.com/argoproj/argo-workflows/workflow/controller/estimation/estimator_factory.go:79
workflow-controller 		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).getEstimator@/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2401
workflow-controller 		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).estimateWorkflowDuration@/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2407
workflow-controller 		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).markWorkflowPhase@/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2347
workflow-controller 		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).markWorkflowRunning@/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2441
workflow-controller 		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate@/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:286
workflow-controller 		github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem@/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:811
workflow-controller 		github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker@/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:734
workflow-controller 		k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1@/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155
workflow-controller 		k8s.io/apimachinery/pkg/util/wait.BackoffUntil@/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156
workflow-controller 		k8s.io/apimachinery/pkg/util/wait.JitterUntil@/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133
workflow-controller 		k8s.io/apimachinery/pkg/util/wait.Until@/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90
workflow-controller 		runtime.goexit@/usr/local/go/src/runtime/asm_amd64.s:1650
workflow-controller 	Error:          upper: slow query
workflow-controller 	Time taken:     2.71444s
```

### Version(s)

v3.5.7

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Referring to the above log
```

### Logs from the workflow controller

```text
Referring to the above log
```

### Logs from in your workflow's wait container

```text
Referring to the above log
```

### PR DESCRIPTION
**Pull request by linzhengen**
Fixes #13382

### Modifications
- Added a query for during estimation
  - Avoided using SQL JSON extraction as it is slow (removed unnecessary columns)
  - Changed the filter for phase from `exists` to `phase = 'Succeeded'`

#### SQL Debug Log
```
2024/07/26 18:32:00 	Session ID:     00001
	Query:          SELECT "name", "namespace", "uid", "startedat", "finishedat" FROM "argo_archived_workflows" WHERE (("clustername" = $1 AND "namespace" = $2 AND "instanceid" = $3) AND "phase" = $4 AND "namespace" = $5 AND exists (select 1 from argo_archived_workflows_labels where clustername = argo_archived_workflows.clustername and uid = argo_archived_workflows.uid and name = 'workflows.argoproj.io/cron-workflow' and value = 'hello-world')) ORDER BY "startedat" DESC LIMIT 1
	Arguments:      []interface {}{"default", "argo", "", "Succeeded", "argo"}
	Stack:          
		fmt.(*pp).handleMethods@/Users/linzhengen/.gvm/gos/go1.22.3/src/fmt/print.go:673
		fmt.(*pp).printArg@/Users/linzhengen/.gvm/gos/go1.22.3/src/fmt/print.go:756
		fmt.(*pp).doPrint@/Users/linzhengen/.gvm/gos/go1.22.3/src/fmt/print.go:1209
		fmt.Append@/Users/linzhengen/.gvm/gos/go1.22.3/src/fmt/print.go:289
		log.(*Logger).Print.func1@/Users/linzhengen/.gvm/gos/go1.22.3/src/log/log.go:261
		log.(*Logger).output@/Users/linzhengen/.gvm/gos/go1.22.3/src/log/log.go:238
		log.(*Logger).Print@/Users/linzhengen/.gvm/gos/go1.22.3/src/log/log.go:260
		github.com/argoproj/argo-workflows/v3/persist/sqldb.(*workflowArchive).GetWorkflowForEstimator@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/persist/sqldb/workflow_archive.go:408
		github.com/argoproj/argo-workflows/v3/workflow/controller/estimation.(*estimatorFactory).NewEstimator@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/workflow/controller/estimation/estimator_factory.go:78
		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).getEstimator@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2411
		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).estimateWorkflowDuration@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2417
		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).markWorkflowPhase@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2355
		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).markWorkflowRunning@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2451
		github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:293
		github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:865
		github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:788
		k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157
		k8s.io/apimachinery/pkg/util/wait.BackoffUntil@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158
		k8s.io/apimachinery/pkg/util/wait.JitterUntil@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135
		k8s.io/apimachinery/pkg/util/wait.Until@/Users/linzhengen/.gvm/pkgsets/go1.22.3/global/src/github.com/argoproj/argo-workflows/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
		runtime.goexit@/Users/linzhengen/.gvm/gos/go1.22.3/src/runtime/asm_arm64.s:1222
	Time taken:     0.01311s
	Context:        context.Background
```

##### EXPLAIN
- Before
```sql
EXPLAIN SELECT
  name,
  namespace,
  uid,
  phase,
  startedat,
  finishedat,
  coalesce((workflow::json) -> 'metadata' ->> 'labels', '{}')      as labels,
  coalesce((workflow::json) -> 'metadata' ->> 'annotations', '{}') as annotations,
  coalesce((workflow::json) -> 'status' ->> 'progress', '')        as progress
FROM
  "argo_archived_workflows"
WHERE
  (
    (
      "clustername" = 'a'
      AND "instanceid" = 'a'
    )
    AND "namespace" = 'a'
    AND exists (
      select
        1
      from
        argo_archived_workflows_labels
      where
        clustername = argo_archived_workflows.clustername
        and uid = argo_archived_workflows.uid
        and name = 'workflows.argoproj.io/cron-workflow'
        and value = 'uuid-my-cwf-name'
    )
    AND exists (
      select
        1
      from
        argo_archived_workflows_labels
      where
        clustername = argo_archived_workflows.clustername
        and uid = argo_archived_workflows.uid
        and name = 'workflows.argoproj.io/phase'
        and value = 'Succeeded'
    )
  )
ORDER BY
  "startedat" DESC
LIMIT
  1
```
```
Limit  (cost=18.90..18.90 rows=1 width=119)
  ->  Sort  (cost=18.90..18.90 rows=1 width=119)
        Sort Key: argo_archived_workflows.startedat DESC
        ->  Nested Loop  (cost=1.55..18.89 rows=1 width=119)
              Join Filter: ((argo_archived_workflows_labels.uid)::text = (argo_archived_workflows_labels_1.uid)::text)
              ->  Nested Loop  (cost=0.99..12.54 rows=1 width=164)
                    Join Filter: ((argo_archived_workflows.uid)::text = (argo_archived_workflows_labels.uid)::text)
                    ->  Index Scan using argo_archived_workflows_labels_pkey on argo_archived_workflows_labels  (cost=0.56..6.33 rows=1 width=45)
                          Index Cond: (((clustername)::text = 'a'::text) AND ((name)::text = 'workflows.argoproj.io/cron-workflow'::text))
                          Filter: ((value)::text = 'uuid-my-cwf-name'::text)
                    ->  Index Scan using argo_archived_workflows_i2 on argo_archived_workflows  (cost=0.43..6.20 rows=1 width=127)
                          Index Cond: (((clustername)::text = 'a'::text) AND ((instanceid)::text = 'a'::text))
                          Filter: ((namespace)::text = 'a'::text)
              ->  Index Scan using argo_archived_workflows_labels_pkey on argo_archived_workflows_labels argo_archived_workflows_labels_1  (cost=0.56..6.33 rows=1 width=45)
                    Index Cond: (((clustername)::text = 'a'::text) AND ((name)::text = 'workflows.argoproj.io/phase'::text))
                    Filter: ((value)::text = 'Succeeded'::text)
```

- After
```sql
EXPLAIN SELECT
  name,
  namespace,
  uid,
  phase,
  startedat,
  finishedat
FROM
  "argo_archived_workflows"
WHERE
  (
    (
      "clustername" = 'a'
      AND "instanceid" = 'a'
    )
    AND "namespace" = 'a'
    AND "phase" = 'Succeeded'
    AND exists (
      select
        1
      from
        argo_archived_workflows_labels
      where
        clustername = argo_archived_workflows.clustername
        and uid = argo_archived_workflows.uid
        and name = 'workflows.argoproj.io/cron-workflow'
        and value = 'uuid-my-cwf-name'
    )
  )
ORDER BY
  "startedat" DESC
LIMIT
  1
```

```
Limit  (cost=12.56..12.56 rows=1 width=119)
  ->  Sort  (cost=12.56..12.56 rows=1 width=119)
        Sort Key: argo_archived_workflows.startedat DESC
        ->  Nested Loop  (cost=0.99..12.55 rows=1 width=119)
              Join Filter: ((argo_archived_workflows.uid)::text = (argo_archived_workflows_labels.uid)::text)
              ->  Index Scan using argo_archived_workflows_i2 on argo_archived_workflows  (cost=0.43..6.20 rows=1 width=127)
                    Index Cond: (((clustername)::text = 'a'::text) AND ((instanceid)::text = 'a'::text))
                    Filter: (((namespace)::text = 'a'::text) AND ((phase)::text = 'Succeeded'::text))
              ->  Index Scan using argo_archived_workflows_labels_pkey on argo_archived_workflows_labels  (cost=0.56..6.33 rows=1 width=45)
                    Index Cond: (((clustername)::text = 'a'::text) AND ((name)::text = 'workflows.argoproj.io/cron-workflow'::text))
                    Filter: ((value)::text = 'uuid-my-cwf-name'::text)
```

### CODE REVIEW

File: persist/sqldb/workflow_archive.go [hunk 1]
```diff
@@ -178,48 +187,35 @@ func (r *workflowArchive) ListWorkflows(options sutils.ListOptions) (wfv1.Workfl
...
-		labels[common.LabelKeyWorkflowArchivingStatus] = "Persisted"
-
-		annotations := make(map[string]string)
-		if err := json.Unmarshal([]byte(md.Annotations), &annotations); err != nil {
-			return nil, err
-		}
-
-		t, err := time.Parse(time.RFC3339, md.CreationTimestamp)
+		var wf workflow
+		// NOTE: Switched from SQL JSON extraction to Golang JSON parsing for better performance. #13382
```
Comment (agilgur5) [inline persist/sqldb/workflow_archive.go:191]: Did you test this? It would be good to see metrics before/after.

It was actually done in Go first and then switched to SQL because the Go variant required the entire data structure to be retrieved instead of the pieces needed (and the entire `status` can be very large) which was far too slow and unnecessary.

This is also not the solution I suggested in #13382 nor #13295

**Review by agilgur5 — CHANGES_REQUESTED** [review]
This variant is a regression to past behavior and doesn't match suggested solutions. See in-line comment for more details.

File: persist/sqldb/workflow_archive.go (hunk 1 above)
Comment (linzhengen) [reply persist/sqldb/workflow_archive.go:191]: > Did you test this? Your "Verification" section is empty.

I have tested the workflow submit and list with a small data, but not yet tested it with large data.

> Per #12912

I have reduced the size of the Go struct for `json.Unmarshal`. Benchmark results show that resource usage has decreased compared to #12912. However, while it not be directly compared to SQL, this method might still be insufficient for improvement.

Benchmark results
```
Benchmark_Unmarshal1
Benchmark_Unmarshal1-10    	   15165	     76526 ns/op	 359.04 MB/s	   70060 B/op	    1230 allocs/op
Benchmark_Unmarshal2
Benchmark_Unmarshal2-10    	   45692	     27174 ns/op	1011.11 MB/s	    4720 B/op	      81 allocs/op
PASS
```

Here is the Benchmark code
```go
package sqldb

import (
	"encoding/json"
	wfv1 "github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
	"io"
	"os"
	"testing"
)

var codeJSON []byte

func codeInit() {
	f, err := os.Open("test.json")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	data, err := io.ReadAll(f)
	if err != nil {
		panic(err)
	}

	codeJSON = data
}

func Benchmark_Unmarshal1(b *testing.B) {
	b.ReportAllocs()
	if codeJSON == nil {
		b.StopTimer()
		codeInit()
		b.StartTimer()
	}
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			var r wfv1.Workflow
			if err := json.Unmarshal(codeJSON, &r); err != nil {
				b.Fatalf("Unmarshal error: %v", err)
			}
		}
	})
	b.SetBytes(int64(len(codeJSON)))
}

func Benchmark_Unmarshal2(b *testing.B) {
	b.ReportAllocs()
	if codeJSON == nil {
		b.StopTimer()
		codeInit()
		b.StartTimer()
	}
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			var r workflow
			if err := json.Unmarshal(codeJSON, &r); err != nil {
				b.Fatalf("Unmarshal error: %v", err)
			}
		}
	})
	b.SetBytes(int64(len(codeJSON)))
}

```

Comment (agilgur5) [reply persist/sqldb/workflow_archive.go:191]: > I have reduced the size of the Go struct for `json.Unmarshal`

Yes but this method still transmits the entirety of the data over the network and still has to be parsed, even if not allocated.

For the Controller estimation scenario of your issue, I had suggested removing the unnecessary columns from the query entirely. It can use a different but similar query.

For the Server API, I had suggested a materialized view and others suggested JSONB (only Postgres compatible, so not a complete solution) and other derivations.

I think all of those methods are better than this one

Comment (linzhengen) [reply persist/sqldb/workflow_archive.go:191]: > For the Controller estimation scenario of your issue, I https://github.com/argoproj/argo-workflows/issues/13382#issuecomment-2245467582 removing the unnecessary columns from the query entirely. It can use a different but similar query.

I think this approach is good. I will revert this Pull Request to Draft.

Comment (linzhengen) [reply persist/sqldb/workflow_archive.go]: I have updated this Pull Request, rebased the previous changes and force pushed.

**Comment by linzhengen** [comment]
This CI has failed:
https://github.com/argoproj/argo-workflows/actions/runs/10118236440/job/27984839387

For `fanout(0:1)`, the message `Pod was active on the node longer than the specified deadline` is not being output.
Is this an issue with `v1.26.15+k3s1`?

```
Events:
  Type     Reason               Age   From                 Message
  ----     ------               ----  ----                 -------
  Normal   WorkflowRunning      13s   workflow-controller  Workflow Running
  Normal   WorkflowNodeRunning  13s   workflow-controller  Running node active-deadline-fanout-template-level-v2ljb[0]
  Normal   WorkflowNodeRunning  13s   workflow-controller  Running node active-deadline-fanout-template-level-v2ljb
  Normal   WorkflowNodeRunning  8s    workflow-controller  Running node active-deadline-fanout-template-level-v2ljb[0].fanout(3:4): Pod was active on the node longer than the specified deadline
  Warning  WorkflowNodeFailed   8s    workflow-controller  Failed node active-deadline-fanout-template-level-v2ljb[0].fanout(3:4): Pod was active on the node longer than the specified deadline
  Normal   WorkflowNodeRunning  8s    workflow-controller  Running node active-deadline-fanout-template-level-v2ljb[0].fanout(2:3): Pod was active on the node longer than the specified deadline
  Warning  WorkflowNodeFailed   8s    workflow-controller  Failed node active-deadline-fanout-template-level-v2ljb[0].fanout(2:3): Pod was active on the node longer than the specified deadline
  Normal   WorkflowNodeRunning  8s    workflow-controller  Running node active-deadline-fanout-template-level-v2ljb[0].fanout(1:2): Pod was active on the node longer than the specified deadline
  Warning  WorkflowNodeFailed   8s    workflow-controller  Failed node active-deadline-fanout-template-level-v2ljb[0].fanout(1:2): Pod was active on the node longer than the specified deadline
  Warning  WorkflowFailed       3s    workflow-controller  child 'active-deadline-fanout-template-level-v2ljb-1669964074' failed
  Warning  WorkflowNodeFailed   3s    workflow-controller  Failed node active-deadline-fanout-template-level-v2ljb: child 'active-deadline-fanout-template-level-v2ljb-1669964074' failed
  Warning  WorkflowNodeFailed   3s    workflow-controller  Failed node active-deadline-fanout-template-level-v2ljb[0]: child 'active-deadline-fanout-template-level-v2ljb-1669964074' failed
  Normal   WorkflowNodeRunning  3s    workflow-controller  Running node active-deadline-fanout-template-level-v2ljb[0].fanout(0:1)
  Warning  WorkflowNodeFailed   3s    workflow-controller  Failed node active-deadline-fanout-template-level-v2ljb[0].fanout(0:1)
```

**Comment by agilgur5** [comment]
Maybe a test flake (although I don't recall that one failing before 🤔), I re-ran that job

**Review by terrytangyuan — COMMENTED** [review]
@jiachengxu Could you help review this?

**Review by jiachengxu — APPROVED** [review]
The PR looks good to me! I think this is a reasonable mitigation for controller estimation, and for solving the slow archived workflows for API, JSONB migration or materialized view might improve more.

**Review by agilgur5 — COMMENTED** [review]
Have some small stylistic comments below, but otherwise this LGTM.

**Comment by linzhengen** [comment]
@agilgur5 
Thank you for the review. I agree with all points raised and fixed the code.
Please review again.

And the `Windows Unit Tests` failed. Could you re-run it?

**Comment by agilgur5** [comment]
> And the `Windows Unit Tests` failed. Could you re-run it?

These aren't required to pass (yet) so no need this time, can merge without them

**Review by agilgur5 — APPROVED** [review]

**Comment by agilgur5** [comment]
Thanks for fixing this!
