### PR TITLE
fix: Auto update workflow controller configmap

### LINKED ISSUE #10187: Config map updates are not picked up by controller without bouncing the controller
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I updated the config map parallelism setting, but the changes were not reflected until I redeployed the controller. Auto config map read was added as a feature in the past. Look at this [issue](https://github.com/argoproj/argo-workflows/issues/9123). But looks like the feature was removed as part of this refactor [commit](https://github.com/mcgrawia/argo-workflows/commit/f00ec49d695bdad108000abcdfd0f82f6af9ca6c).

 

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
        resources:
          limits:
            memory: 32Mi
            cpu: 100m
```

### Logs from the workflow controller

```text
//
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

//
```

### PR DESCRIPTION
**Pull request by sarabala1979**
Fixes #10187 

Please do not open a pull request until you have checked ALL of these:

* [ ] Create the PR as draft .
* [ ] Run `make pre-commit -B` to fix codegen and lint problems.
* [ ] Sign-off your commits (otherwise the DCO check will fail).
* [ ] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [ ] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [ ] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [ ] Github checks are green.
* [ ] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

File: workflow/controller/controller.go [hunk 1]
```diff
@@ -402,8 +402,16 @@ func (wfc *WorkflowController) runConfigMapWatcher(stopCh <-chan struct{}) {
 				continue
 			}
 			log.Debugf("received config map %s/%s update", cm.Namespace, cm.Name)
+			if cm.GetName() == wfc.configController.GetName() && wfc.namespace == cm.GetNamespace() {
+				log.Infof("Received Workflow Controller config map %s/%s update", cm.Namespace, cm.Name)
+				err := wfc.updateConfig()
+				if err != nil {
+					log.Errorf("Failed update the Workflow Controller config map. error: %v", err)
+				}
+				log.Infof("Successfully Workflow Controller config map %s/%s updated", cm.Namespace, cm.Name)
```
Comment (whynowy) [inline workflow/controller/controller.go:411]: This line will also be printed even there's an error in line 409.

**Review by whynowy — APPROVED** [review]
LGTM
