### PR TITLE
fix: remove WorkflowSpec VolumeClaimTemplates patch key

### LINKED ISSUE #11344: Cron workflow can not apply volumeClaimTemplates config from argo controller config map (workflowDefaults)
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Expected: cron workflow is started correctly
What's happening:

`map: map[metadata:map[creationTimestamp:<nil> name:pyspark-dir] spec:map[accessModes:[ReadWriteOnce] resources:map[requests:map[storage:350Gi]] storageClassName:xry-storage] status:map[]] does not contain declared merge key: name`

It works ok with non-cron type workflows.

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

Argo Controller config map (volumeClaimTemplates):
```YAML
apiVersion: v1
data:
  config: |
    instanceID: xry
    workflowDefaults:
      spec:
        podGC:
          strategy: OnWorkflowCompletion
        ttlStrategy:
          secondsAfterCompletion: 8640000
        volumeClaimGC:
          strategy: OnWorkflowCompletion
        volumeClaimTemplates:
          - metadata:
              name: pyspark-dir
              creationTimestamp: null
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 350Gi
              storageClassName: xry-storage
    nodeEvents:
      enabled: true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argo-workflows
    meta.helm.sh/release-namespace: app
  creationTimestamp: "2023-07-12T06:57:16Z"
  labels:
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-cm
    app.kubernetes.io/part-of: argo-workflows
    helm.sh/chart: argo-workflows-0.30.0
  name: argo-workflows-workflow-controller-configmap
  namespace: app
  resourceVersion: "46107870"
  uid: 5d28f4b4-037c-4d96-8c69-d2fcf93e3b68
```

And just a default cron workflow with volumeMounts:

```YAML
metadata:
  name: argo-apply-pvc-from-workflow-defaults
  namespace: app
  uid: 73c5a41c-716c-4179-ab7a-ea97c2b9fab1
  resourceVersion: '46116295'
  generation: 11
  creationTimestamp: '2023-07-12T14:18:23Z'
  labels:
    example: 'true'
    workflows.argoproj.io/controller-instanceid: xry
    workflows.argoproj.io/creator: system-serviceaccount-app-argo-workflows-server
  annotations:
    cronworkflows.argoproj.io/last-used-schedule: '* * * * *'
  managedFields:
    - manager: argo
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2023-07-12T14:20:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:example: {}
            f:workflows.argoproj.io/controller-instanceid: {}
            f:workflows.argoproj.io/creator: {}
        f:spec: {}
    - manager: workflow-controller
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2023-07-12T14:23:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:cronworkflows.argoproj.io/last-used-schedule: {}
        f:status: {}
spec:
  workflowSpec:
    templates:
      - name: argosay
        inputs:
          parameters:
            - name: message
              value: '{{workflow.parameters.message}}'
        outputs: {}
        metadata: {}
        container:
          name: main
          image: argoproj/argosay:v2
          command:
            - /argosay
          args:
            - echo
            - '{{inputs.parameters.message}}'
          resources: {}
          volumeMounts:
            - name: pyspark-dir
              mountPath: /tmp/pyspark
    entrypoint: argosay
    arguments:
      parameters:
        - name: message
          value: hello argo
    ttlStrategy:
      secondsAfterCompletion: 300
    podGC:
      strategy: OnPodCompletion
  schedule: 0 11 * * *
  workflowMetadata:
    creationTimestamp: null
    labels:
      example: 'true'
status:
  active: null
  lastScheduledTime: '2023-07-12T14:20:00Z'
  conditions: null
```


### Logs from the workflow controller

```text
│ time="2023-07-12T13:52:12.976Z" level=info msg="Get leases 200"                                                                                                                                                                                                                                                                                                  
│ time="2023-07-12T13:52:12.983Z" level=info msg="Update leases 200"                                                                                                                                                                                                                                                                                               
│ time="2023-07-12T13:52:14.727Z" level=info msg="Processing workflow" namespace=app workflow=process-frc-v2-cron-n95vq                                                                                                                                                                                                                                            
│ time="2023-07-12T13:52:14.728Z" level=info msg="Updated phase  -> Error" namespace=app workflow=process-frc-v2-cron-n95vq                                                                                                                                                                                                                                       
│ time="2023-07-12T13:52:14.728Z" level=info msg="Updated message  -> map: map[metadata:map[creationTimestamp:<nil> name:pyspark-dir] spec:map[accessModes:[ReadWriteOnce] resources:map[requests:map[storage:350Gi]] storageClassName:xry-storage] status:map[]] does not contain declared merge key: name" namespace=app workflow=process-frc-v2-cron-n95vq      │
│ time="2023-07-12T13:52:14.728Z" level=info msg="Marking workflow completed" namespace=app workflow=process-frc-v2-cron-n95vq                                                                                                                                                                                                                                     
│ time="2023-07-12T13:52:14.728Z" level=error msg="Unable to set ExecWorkflow" error="map: map[metadata:map[creationTimestamp:<nil> name:pyspark-dir] spec:map[accessModes:[ReadWriteOnce] resources:map[requests:map[storage:350Gi]] storageClassName:xry-storage] status:map[]] does not contain declared merge key: name" namespace=app workflow=process-frc-v2 │
│ time="2023-07-12T13:52:14.728Z" level=info msg="Checking daemoned children of " namespace=app workflow=process-frc-v2-cron-n95vq                                                                                                                                                                                                                                 
│ time="2023-07-12T13:52:14.728Z" level=info msg="Workflow to be dehydrated" Workflow Size=6699                                                                                                                                                                                                                                                                    
│ time="2023-07-12T13:52:14.734Z" level=info msg="cleaning up pod" action=deletePod key=app/process-frc-v2-cron-n95vq-1340600742-agent/deletePod
```


### Logs from in your workflow's wait container

```text
Containers are not started. Error comes from the controller before the containers are started.
```

### PR DESCRIPTION
**Pull request by sunyeongchoi**
Fixes #11344

### Motivation

In the workflow_type.go file, the `VolumeClaimTemplates` within the `WorkflowSpec` type was defined as follows:
```go
VolumeClaimTemplates []apiv1.PersistentVolumeClaim `json:"volumeClaimTemplates,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,6,opt,name=volumeClaimTemplates"`
```

However, upon checking the `PersistentVolumeClaim` type, the type defined under "name" doesn't exist; instead, "name" exists within the "metadata" section.

```go
type PersistentVolumeClaim struct {
	metav1.TypeMeta `json:",inline"`
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`

	// spec defines the desired characteristics of a volume requested by a pod author.
	// More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims
	// +optional
	Spec PersistentVolumeClaimSpec `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`

	// status represents the current information/status of a persistent volume claim.
	// Read-only.
	// More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims
	// +optional
	Status PersistentVolumeClaimStatus `json:"status,omitempty" protobuf:"bytes,3,opt,name=status"`
}
```

Because of this, when defining `VolumeClaimTemplates` in the controller config map (`workflowDefaults`), a continuous `does not contain declared merge key: name` occurs.

Is there a reason for defining `patchStrategy` and `patchMergeKey` in `VolumeClaimTemplates`?
In my opinion, there's no need to define `patchStrategy` and `patchMergeKey` in `VolumeClaimTemplates`, so I removed that content.
If there's a reason behind it, please provide feedback, and I'll be grateful to make changes using an alternative approach.

### Modifications

I removed `patchStrategy` and `patchMergeKey` from `VolumeClaimTemplates` in `WorkflowSpec`, as shown in the below image.

image

### CODE REVIEW

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 1]
```diff
@@ -290,9 +290,7 @@ type WorkflowSpec struct {
 	// VolumeClaimTemplates is a list of claims that containers are allowed to reference.
 	// The Workflow controller will create the claims at the beginning of the workflow
 	// and delete the claims upon completion of the workflow
-	// +patchStrategy=merge
-	// +patchMergeKey=name
-	VolumeClaimTemplates []apiv1.PersistentVolumeClaim `json:"volumeClaimTemplates,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,6,opt,name=volumeClaimTemplates"`
+	VolumeClaimTemplates []apiv1.PersistentVolumeClaim `json:"volumeClaimTemplates,omitempty" protobuf:"bytes,6,opt,name=volumeClaimTemplates"`
```
Comment (terrytangyuan) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:293]: This follows the same convention as `Volumes` above.

Comment (sunyeongchoi) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:293]: @terrytangyuan 

Hello. Thank you for the review! :)
If `VolumeClaimTemplates` are supposed to follow the same convention as `Volume`, can we proceed by removing `patchStrategy` and `patchMergeKey` from the Volume structure?
I believe that the approach of using `patchMergeKey` for `name` within `VolumeClaimTemplates` is currently not feasible.

Using `patchMergeKey` to reference a nested field structure in Kubernetes is not natively supported. `patchMergeKey` can only be applied to one of the top-level fields of an object, and it cannot be applied to nested fields.

To achieve the desired outcome of using name as `patchMergeKey`, you might need to consider altering the structure of the `PersistentVolumeClaim` type within `VolumeClaimTemplates`. This could involve actions such as moving the name field within the `VolumeClaimTemplates` array.

However, be cautious since making such structural changes to accommodate this might introduce unintended consequences. Modifying the structure of the structure might lead to other side effects, so it's essential to approach this with care.

Comment (terrytangyuan) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:293]: This might be a potential breaking change so I'd love to see more 👀 on this from others

**Comment by sunyeongchoi** [comment]
stale bot, please wait a moment

**Comment by LinuxSuRen** [comment]
Any news here? Expect this from me.

**Review by terrytangyuan — COMMENTED** [review]
Could you add some tests?

**Comment by sunyeongchoi** [comment]
> Could you add some tests?

Okay, I'll make it as fast I can.

**Comment by LinuxSuRen** [comment]
By the way, before having this feature I my temporary solution is below.

Put a workflow into a ConfigMap. Then create a cronJob which mount a that ConfigMap. Using kubectl apply -f xxx.yaml to create the workflow.

**Comment by sunyeongchoi** [comment]
I'm sorry I've been so busy these days that I've been late in writing the test code.
I plan to finish it by at least next week, so please wait a little :)

**Comment by sunyeongchoi** [comment]
I add some test code that applied `volumeClaimTemplate` to `workflowDefaults`.

**Review by terrytangyuan — APPROVED** [review]
Thanks for your patience!
