### PR TITLE
fix(ui): properly get archive logs when no node was chosen

### LINKED ISSUE #12590: Missing logs in Archived-Workflows by using the logs button
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When trying to view logs of an archived-workflow by pressing the "Logs" Button in the top action bar, the error message `Should specify a node when we get archived logs` shows up. This also occurs if a pod is selected in the drop-down menu from the log viewer or a specific node is selected before clicking the "Logs" Button. The only way to see the logs is to select a Node and use the "Logs" Button on the right pop-up menu.
screenshot

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-bash-
spec:
  entrypoint: bash-script-example
  templates:
  - name: bash-script-example
    steps:
    - - name: generate
        template: gen-random-int-bash
    - - name: print
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate.outputs.result}}"  # The result of the here-script

  - name: gen-random-int-bash
    script:
      image: debian:9.4
      command: [bash]
      source: |                                         # Contents of the here-script
        cat /dev/urandom | od -N2 -An -i | awk -v f=1 -v r=100 '{printf "%i\n", f + r * $1 / 65536}'

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.message}}"]
```

### Logs from the workflow controller

```text
time="2024-01-30T19:22:51.615Z" level=info msg="Processing workflow" Phase= ResourceVersion=16501936 namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.618Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=0 workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.618Z" level=info msg="Updated phase  -> Running" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.618Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.618Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.618Z" level=info msg="Steps node scripts-bash-bbt48 initialized Running" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.618Z" level=info msg="StepGroup node scripts-bash-bbt48-2132110377 initialized Running" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.618Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.619Z" level=info msg="Pod node scripts-bash-bbt48-2882959058 initialized Pending" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.635Z" level=info msg="Created pod: scripts-bash-bbt48[0].generate (scripts-bash-bbt48-gen-random-int-bash-2882959058)" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.635Z" level=info msg="Workflow step group node scripts-bash-bbt48-2132110377 not yet completed" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.635Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.635Z" level=info msg=reconcileAgentPod namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:22:51.643Z" level=info msg="Workflow update successful" namespace=workflows phase=Running resourceVersion=16501939 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:01.615Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=16501939 namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:01.615Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=0 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:01.616Z" level=info msg="node changed" namespace=workflows new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=scripts-bash-bbt48-2882959058 old.message= old.phase=Pending old.progress=0/1 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:01.616Z" level=info msg="Workflow step group node scripts-bash-bbt48-2132110377 not yet completed" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:01.616Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:01.616Z" level=info msg=reconcileAgentPod namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:01.691Z" level=info msg="Workflow update successful" namespace=workflows phase=Running resourceVersion=16501955 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:12.392Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=16501955 namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:12.392Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=1 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:12.392Z" level=info msg="task-result changed" namespace=workflows nodeID=scripts-bash-bbt48-2882959058 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:12.392Z" level=info msg="node changed" namespace=workflows new.message= new.phase=Running new.progress=0/1 nodeID=scripts-bash-bbt48-2882959058 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:12.392Z" level=info msg="Workflow step group node scripts-bash-bbt48-2132110377 not yet completed" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:12.392Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:12.392Z" level=info msg=reconcileAgentPod namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:12.403Z" level=info msg="Workflow update successful" namespace=workflows phase=Running resourceVersion=16501973 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.403Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=16501973 namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=1 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="task-result changed" namespace=workflows nodeID=scripts-bash-bbt48-2882959058 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="node changed" namespace=workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=scripts-bash-bbt48-2882959058 old.message= old.phase=Running old.progress=0/1 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="Step group node scripts-bash-bbt48-2132110377 successful" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="node scripts-bash-bbt48-2132110377 phase Running -> Succeeded" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="node scripts-bash-bbt48-2132110377 finished: 2024-01-30 19:23:22.404631598 +0000 UTC" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="StepGroup node scripts-bash-bbt48-3138914612 initialized Running" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="SG Outbound nodes of scripts-bash-bbt48-2882959058 are [scripts-bash-bbt48-2882959058]" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.404Z" level=info msg="Pod node scripts-bash-bbt48-3392327161 initialized Pending" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.418Z" level=info msg="Created pod: scripts-bash-bbt48[1].print (scripts-bash-bbt48-print-message-3392327161)" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.418Z" level=info msg="Workflow step group node scripts-bash-bbt48-3138914612 not yet completed" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.418Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.418Z" level=info msg=reconcileAgentPod namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.435Z" level=info msg="Workflow update successful" namespace=workflows phase=Running resourceVersion=16501985 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:22.442Z" level=info msg="cleaning up pod" action=labelPodCompleted key=workflows/scripts-bash-bbt48-gen-random-int-bash-2882959058/labelPodCompleted
time="2024-01-30T19:23:32.418Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=16501985 namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=2 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="task-result changed" namespace=workflows nodeID=scripts-bash-bbt48-2882959058 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="task-result changed" namespace=workflows nodeID=scripts-bash-bbt48-3392327161 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="node changed" namespace=workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=scripts-bash-bbt48-3392327161 old.message= old.phase=Pending old.progress=0/1 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="SG Outbound nodes of scripts-bash-bbt48-2882959058 are [scripts-bash-bbt48-2882959058]" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="Step group node scripts-bash-bbt48-3138914612 successful" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="node scripts-bash-bbt48-3138914612 phase Running -> Succeeded" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="node scripts-bash-bbt48-3138914612 finished: 2024-01-30 19:23:32.418766758 +0000 UTC" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="Outbound nodes of scripts-bash-bbt48-3392327161 is [scripts-bash-bbt48-3392327161]" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="Outbound nodes of scripts-bash-bbt48 is [scripts-bash-bbt48-3392327161]" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="node scripts-bash-bbt48 phase Running -> Succeeded" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="node scripts-bash-bbt48 finished: 2024-01-30 19:23:32.418823689 +0000 UTC" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg=reconcileAgentPod namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="Updated phase Running -> Succeeded" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="Marking workflow completed" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.418Z" level=info msg="Marking workflow as pending archiving" namespace=workflows workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.424Z" level=info msg="cleaning up pod" action=deletePod key=workflows/scripts-bash-bbt48-1340600742-agent/deletePod
time="2024-01-30T19:23:32.425Z" level=info msg="Workflow update successful" namespace=workflows phase=Succeeded resourceVersion=16502019 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.446Z" level=info msg="archiving workflow" namespace=workflows uid=1e829788-4d45-48cb-a835-381dadf33756 workflow=scripts-bash-bbt48
time="2024-01-30T19:23:32.451Z" level=info msg="cleaning up pod" action=labelPodCompleted key=workflows/scripts-bash-bbt48-print-message-3392327161/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
time="2024-01-30T19:23:10.596Z" level=info msg="No output parameters"
time="2024-01-30T19:23:10.596Z" level=info msg="No output artifacts"
time="2024-01-30T19:23:10.596Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: scripts-bash-bbt48/scripts-bash-bbt48-gen-random-int-bash-2882959058/main.log"
time="2024-01-30T19:23:10.596Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-01-30T19:23:10.596Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=scripts-bash-bbt48/scripts-bash-bbt48-gen-random-int-bash-2882959058/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-01-30T19:23:11.256Z" level=info msg="Save artifact" artifactName=main-logs duration=659.635104ms error="<nil>" key=scripts-bash-bbt48/scripts-bash-bbt48-gen-random-int-bash-2882959058/main.log
time="2024-01-30T19:23:11.256Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2024-01-30T19:23:11.256Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2024-01-30T19:23:11.266Z" level=info msg="Alloc=7910 TotalAlloc=13570 Sys=19045 NumGC=4 Goroutines=10"
time="2024-01-30T19:23:11.271Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2024-01-30T19:23:29.683Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2024-01-30T19:23:29.683Z" level=info msg="No output parameters"
time="2024-01-30T19:23:29.683Z" level=info msg="No output artifacts"
time="2024-01-30T19:23:29.683Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: scripts-bash-bbt48/scripts-bash-bbt48-print-message-3392327161/main.log"
time="2024-01-30T19:23:29.683Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-01-30T19:23:29.683Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=scripts-bash-bbt48/scripts-bash-bbt48-print-message-3392327161/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-01-30T19:23:29.698Z" level=info msg="Save artifact" artifactName=main-logs duration=14.294324ms error="<nil>" key=scripts-bash-bbt48/scripts-bash-bbt48-print-message-3392327161/main.log
time="2024-01-30T19:23:29.698Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2024-01-30T19:23:29.698Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2024-01-30T19:23:29.708Z" level=info msg="Alloc=7492 TotalAlloc=13589 Sys=19045 NumGC=4 Goroutines=10"
```

### LINKED ISSUE #12759: Workflow logs button does not fetch archived logs but node summary logs button does
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Hi!

The LOGS button on a workflow page does not load the archived logs when `archiveLogs` is set to True and workflow pods have been GCd. The LOGS buttons on the node summary does work properly, ie. loads and display logs from the archive.

Don't know if this is relevant but my artifact repository is set in the `workflow-controller-configmap` and is an AWS S3 bucket.

Screenshot 2024-03-07 at 10 42 59

**From the workflow LOGS button:**
Screenshot 2024-03-07 at 11 59 07

A GET is performed with URI `/api/v1/workflows/mwaa-data-prod/omniscient-dragon-zkc9v/log?logOptions.container=main&grep=&logOptions.follow=true&podName=omniscient-dragon-zkc9v`

**From the node summary LOGS button:**
Screenshot 2024-03-07 at 11 59 19

A GET is performed with URI `/artifact-files/mwaa-data-prod/workflows/omniscient-dragon-zkc9v/omniscient-dragon-zkc9v/outputs/main-logs` which properly fetches archived logs.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
{
  "metadata": {
    "generateName": "lovely-whale-",
    "namespace": "mwaa-data-prod"
  },
  "spec": {
    "entrypoint": "argosay",
    "archiveLogs": true,
    "serviceAccountName": "argo-executor",
    "templates": [
      {
        "name": "argosay",
        "container": {
          "name": "main",
          "image": "argoproj/argosay:v2",
          "command": [
            "/argosay"
          ],
          "args": [
            "echo",
            "This is a test"
          ]
        }
      }
    ],
    "podGC": {
      "strategy": "OnPodCompletion"
    }
  }
}
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}


time="2024-03-07T11:08:22.123Z" level=info msg="Processing workflow" Phase= ResourceVersion=399612776 namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.132Z" level=info msg="Task-result reconciliation" namespace=mwaa-data-prod numObjs=0 workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.132Z" level=info msg="Updated phase  -> Running" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.133Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.133Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.133Z" level=info msg="Pod node lovely-whale-rbdpx initialized Pending" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.186Z" level=info msg="Created pod: lovely-whale-rbdpx (lovely-whale-rbdpx)" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.186Z" level=info msg="TaskSet Reconciliation" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.186Z" level=info msg=reconcileAgentPod namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:22.200Z" level=info msg="Workflow update successful" namespace=mwaa-data-prod phase=Running resourceVersion=399612781 workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.185Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=399612781 namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.185Z" level=info msg="Task-result reconciliation" namespace=mwaa-data-prod numObjs=1 workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.185Z" level=info msg="task-result changed" namespace=mwaa-data-prod nodeID=lovely-whale-rbdpx workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.185Z" level=info msg="node changed" namespace=mwaa-data-prod new.message= new.phase=Succeeded new.progress=0/1 nodeID=lovely-whale-rbdpx old.message= old.phase=Pending old.progress=0/1 workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.185Z" level=info msg="TaskSet Reconciliation" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.185Z" level=info msg=reconcileAgentPod namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.186Z" level=info msg="Updated phase Running -> Succeeded" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.186Z" level=info msg="Marking workflow completed" namespace=mwaa-data-prod workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:32.191Z" level=info msg="cleaning up pod" action=deletePod key=mwaa-data-prod/lovely-whale-rbdpx-1340600742-agent/deletePod
time="2024-03-07T11:08:32.201Z" level=info msg="Queueing Succeeded workflow mwaa-data-prod/lovely-whale-rbdpx for delete in 48h0m0s due to TTL"
time="2024-03-07T11:08:32.202Z" level=info msg="Workflow update successful" namespace=mwaa-data-prod phase=Succeeded resourceVersion=399612901 workflow=lovely-whale-rbdpx
time="2024-03-07T11:08:37.235Z" level=info msg="cleaning up pod" action=deletePod key=mwaa-data-prod/lovely-whale-rbdpx/deletePod
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

Did a run by removing podGC.strategy and could output the following logs:

time="2024-03-07T11:19:41.293Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2024-03-07T11:19:41.293Z" level=info msg="No output parameters"
time="2024-03-07T11:19:41.293Z" level=info msg="No output artifacts"
time="2024-03-07T11:19:41.293Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: lovely-whale-dz4f7/lovely-whale-dz4f7/main.log"
time="2024-03-07T11:19:41.298Z" level=info msg="Creating minio client using IAM role"
time="2024-03-07T11:19:41.298Z" level=info msg="Saving file to s3" bucket=argo-workflows-artifacts-f617ed6 endpoint=s3.amazonaws.com key=lovely-whale-dz4f7/lovely-whale-dz4f7/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-03-07T11:19:41.370Z" level=info msg="Save artifact" artifactName=main-logs duration=76.573752ms error="<nil>" key=lovely-whale-dz4f7/lovely-whale-dz4f7/main.log
time="2024-03-07T11:19:41.370Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2024-03-07T11:19:41.370Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2024-03-07T11:19:41.409Z" level=info msg="Alloc=12094 TotalAlloc=16904 Sys=23397 NumGC=3 Goroutines=12"
```

### PR DESCRIPTION
**Pull request by agilgur5**
Fixes #12590, Fixes #12759
- Partially replaces #12591 with a root cause fix (that I wrote & pushed [myself](https://github.com/argoproj/argo-workflows/pull/12591#discussion_r1562071827) to the PR) and without an additional feature, so that this can be properly backported to 3.4.x and 3.5.x

Follow-up to #9464

### Motivation

- a node doesn't have to be clicked on in the UI to get logs, you can also click on the top-level logs button
  - in this case, there is no nodeId, but we can infer/derive one based on the Pod chosen in the drop-down

- a nodeId is required for archive logs, so this fixes archive logs when no node was chosen
  - which is a bug / regression that seems to stem from the `POD_NAMES=v2` change

### Modifications

- use the `podNamesToNodeIDs` map from #9464 to derive a `nodeId`

### Verification

Manually tested that clicking the top-level logs button and then choosing a pod name gets logs for both archive and non-archive. Screenshot below, note that the URL has no `nodeId` in it as a node was not clicked

Screenshot 2024-04-13 at 2 03 05 PM

### CODE REVIEW

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 1]
```diff
@@ -175,6 +174,8 @@ export function WorkflowLogsViewer({workflow, nodeId, initialPodName, container,
             })
     );
 
+    // default to the node id of of the pod
```
Comment (juliev0) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:177]:
```suggestion
    // default to the node id of the pod
```

**Review by juliev0 — APPROVED** [review]

**Comment by agilgur5** [comment]
Backported cleanly into `release-3.5` as 3f3ac8ea696b3a41c88d5fd5cc1bf6eeb47abbcc
- Did just miss the cut-off for `v3.5.6` though: #12956 😅
