### PR TITLE
fix(controller): Global parameter is not getting updated

### LINKED ISSUE #6226: Global output parameters cannot be changed in v3.1.0
## Summary 

In v3.1.0, if a global output parameter is set by one step and changed by another, later step, the change is reflected in `argo watch` / `argo get` but is not reflected whenever the global output parameter is referenced in the workflow. This bug does not happen in v3.0.8 or earlier versions as far as I've tried.

## Reproduction Steps

Here's an example workflow:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: change-global-parameter-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: create-output-parameter
        template: global-parameter-setting
        arguments:
          parameters:
          - name: value
            value: foo
    - - name: update-output-parameter
        template: global-parameter-setting
        arguments:
          parameters:
          - name: value
            value: bar
    - - name: consume-output-parameter
        template: global-parameter-consumption

  - name: global-parameter-setting
    inputs:
      parameters:
      - name: value
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["exit 0"]
    outputs:
      parameters:
      - name: parameter
        value: "{{inputs.parameters.value}}"
        globalName: parameter

  - name: global-parameter-consumption
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo {{workflow.outputs.parameters.parameter}}"]
```

The global parameter named `parameter` is originally set to `foo`, then changed to `bar`, then consumed. So the logs should just say `bar`, but instead, in v3.1.0, here are the logs:
```
change-global-parameter-xcvzx-3848121739: foo
```
In v3.0.8, this all works correctly:
```
change-global-parameter-mrdpf-1364986955: bar
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>
close #6226

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -3378,7 +3378,13 @@ func (woc *wfOperationCtx) mergedTemplateDefaultsInto(originalTmpl *wfv1.Templat
 }
 
 func (woc *wfOperationCtx) substituteGlobalVariables() error {
-	wfSpec, err := json.Marshal(woc.execWf.Spec)
+	execWfSpec := woc.execWf.Spec
+
+	// To Avoid the stale Global parameter value substitution to templates.
+	// Updated Global parameter values will be substituted in 'executetemplate' for templates.
+	execWfSpec.Templates = nil
```
Comment (alexec) [inline workflow/controller/operator.go:3385]: do you need to do a deep cop here?

**Review by alexec — APPROVED** [review]
one query

File: workflow/controller/operator.go (hunk 1 above)
Comment (sarabala1979) [reply workflow/controller/operator.go:3385]: no need deep copy. spec is not pointer
