### PR TITLE
fix: Terminate, rather than delete, deadlined pods. Fixes #8545

### LINKED ISSUE #8545: containers in containersets not appropriately reporting status if terminated
## Checklist
* [X] Double-checked my configuration.
* [X] Tested using the latest version.
* [X] Used the Emissary executor.

## Summary
What happened/what you expected to happen?
When terminating a workflow due to a deadline, I expect that the workflow is terminated, yet we are still waiting for containerset containers to be terminated, even though they are finished with error in k8s.

An image of the workflow after timeout termination:
Screen Shot 2022-04-29 at 7 05 21 PM

An image of the containers for shard-13 in k8s:
Screen Shot 2022-04-29 at 7 07 00 PM

What version are you running?
3.3.2

# Reproducible Workflow
[reproducible-workflow.txt](https://github.com/argoproj/argo-workflows/files/8592860/reproducible-workflow.txt)

# Logs from the workflow controller:
[controller-logs.txt](https://github.com/argoproj/argo-workflows/files/8592827/controller-logs.txt)

# The workflow's pods that are problematic:
```apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

# Logs from in your workflow's wait container:
[wait-logs.txt](https://github.com/argoproj/argo-workflows/files/8592829/wait-logs.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>

Fixes #8545

Problem: When a step hits it deadline, we delete the pod. Because we delete the pod, we loose all information about the success or failure of the pod. Instead of deleting, we must SIGTERM the pod's containers.

### CODE REVIEW

File: workflow/controller/controller.go [hunk 1]
```diff
@@ -468,24 +468,6 @@ func (wfc *WorkflowController) processNextPodCleanupItem(ctx context.Context) bo
 	err := func() error {
 		pods := wfc.kubeclientset.CoreV1().Pods(namespace)
 		switch action {
-		case shutdownPod:
```
Comment (alexec) [inline workflow/controller/controller.go:471]: this isn't needed anymore

**Review by sarabala1979 — APPROVED** [review]
LGTM, Will existing Test cover this case?
