### PR TITLE
fix: Skip missed executions if CronWorkflow schedule is changed. Fixes #7182

### LINKED ISSUE #7182: CronWorkflow gets scheduled on schedule change if new schedule is between current time and last schedule.
## Summary

I have noticed that CronWorkflows get executed even when they are not scheduled to do so. This happens if you change the schedule of the cronworkflow and put it in another time, that is after the time of the previous schedule, but before current time.

I think that the workflow controller checks the new schedule, and sees that a cronworkflow should have been executed in the meantime, triggering it.

What is more strange though is that argo cron list doesn't capture this behavior, so pods are being scheduled, but you can not find through argo.

## Diagnostics

I am using:
Argo Workflows version 3.2.0
Kubernetes version 1.21.1
Executor: PNS

To replicate. Let's say it is 13:50 and we want to schedule a CronWorkflow that executes at 14:00 each day:

Create this CronWorkflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test
spec:
  schedule: "0 14 * * *"
  suspend: false
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  timezone: CET
  workflowSpec:
    entrypoint: job
    templates:
    - name: job
      container:
        image: centos:centos7
        command: ["/bin/sh","-c"]
        args: ["/bin/echo \"hello argo\""]
        imagePullPolicy: Always
```

A Workflow will be created at 14:00 correctly. However, let's say the time now is 14:10 and we decide that for the next days, we want the schedule to be at 14:05 instead of 14:00.

Change the cronworkflow to:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test
spec:
  schedule: "5 14 * * *"
  suspend: false
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  timezone: CET
  workflowSpec:
    entrypoint: job
    templates:
    - name: job
      container:
        image: centos:centos7
        command: ["/bin/sh","-c"]
        args: ["/bin/echo \"hello argo\""]
        imagePullPolicy: Always
```
and do kubectl apply -f test.yaml

This will trigger a new workflow even though the time now is 14:10 (5 minutes after the supposed new schedule).

However using argo cron list, in the LAST RUN field we get workflow that was execute at 14:00 and not at the 14:05.

So two things here.

1. Is it the expected behavior to execute a cronworkflow outside of the schedule like this?
2. Shouldn't the LAST RUN show the correct last executed workflow?

The expected behavior for me would be to execute the CronWorkflow on the schedule.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by simster7**
Fixes https://github.com/argoproj/argo-workflows/issues/7182

Signed-off-by: Simon Behar <simbeh7@gmail.com>

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Review by alexec — COMMENTED** [review]
this seems smart, more tests?

**Comment by simster7** [comment]
@alexec enhanced tests, they should no cover all expected behaviors

File: workflow/cron/operator.go [hunk 1]
```diff
@@ -370,6 +378,17 @@ func (woc *cronWfOperationCtx) reportCronWorkflowError(conditionType v1alpha1.Co
...
 }
 
+func (woc *cronWfOperationCtx) annotateLastUsedSchedule() {
+	lastUsedSchedule, exists := woc.cronWf.Annotations[common.AnnotationKeyCronWfLastUsedSchedule]
+	// If last-used-schedule does not exist, or if it does not match the current schedule, update it
+	if !exists || lastUsedSchedule != woc.cronWf.Spec.GetScheduleString() {
+		if woc.cronWf.Annotations == nil {
+			woc.cronWf.Annotations = map[string]string{}
+		}
+		woc.cronWf.Annotations[common.AnnotationKeyCronWfLastUsedSchedule] = woc.cronWf.Spec.GetScheduleString()
```
Comment (alexec) [inline workflow/cron/operator.go:388]: minor - I feel like we spend much time getting and setting annotations, what about if we had `cronWf.SetLastUsedSchedule()` (if that is even possible

Comment (simster7) [reply workflow/cron/operator.go]: Done!

File: pkg/apis/workflow/v1alpha1/cron_workflow_types.go [hunk 2]
```diff
@@ -34,6 +36,8 @@ const (
 	ReplaceConcurrent ConcurrencyPolicy = "Replace"
 )
 
+const annotationKeyLatestSchedule = workflow.CronWorkflowFullName + "/last-used-schedule"
```
Comment (simster7) [inline pkg/apis/workflow/v1alpha1/cron_workflow_types.go:39]: Moving the label here was necessary to avoid import cycles. I believe this is okay because we have full accessor methods and the label is private... this way implementation of the "last used schedule" concept is completely abstracted.

Comment (alexec) [reply pkg/apis/workflow/v1alpha1/cron_workflow_types.go:39]: maybe `previous-schedule`?

Comment (simster7) [reply pkg/apis/workflow/v1alpha1/cron_workflow_types.go:39]: I think `last-used-schedule` is more accurate. We're interested in the schedule that was last used to execute a workflow. This may or may not be the previous schedule.

**Review by alexec — APPROVED** [review]
