### PR TITLE
fix: create task results only once. Fixes: #14617

### LINKED ISSUE #14617: Avoid frequent calls to createTaskResult in large-scale scenarios
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

In large-scale scenarios (more than 10,000 pods), we.monitorProgress causes frequent calls to create the workflowtaskresult interface, resulting in a low success rate for the entire apiserver write and a significant decrease in overall performance.

In Alibaba Cloud's log system, we can see a single workflow pod called 57 times, post workflowtaskresult requests, and the apiserver returned 409. This call is invalid, which increases the pressure on the APIserver and causes poor performance, especially when there are many pods in the cluster.

Image

### Version(s)

v3.5.13

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
any workflow
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by shuangkun**
Create taskresult only once. Avoid excessive pressure on the API server and performance degradation in large-scale scenarios.

Fixes #14617

### CODE REVIEW

File: workflow/executor/taskresult.go [hunk 1]
```diff
@@ -15,11 +15,27 @@ import (
...
+		if err != nil {
+			return err
+		}
+		we.taskResultCreated = true // Mark as created after successful creation
+	} else {
+		err := we.patchTaskResult(ctx, result)
+		if err != nil {
+			if apierr.IsNotFound(err) {
+				we.taskResultCreated = false // Reset flag since it's no longer available
+				return we.createTaskResult(ctx, result)
```
Comment (Joibel) [inline workflow/executor/taskresult.go:30]: At this point we'll create a task result and not record it as created. Not a disaster, but perhaps setting the flag true inside `createTaskResult` instead of in this function could fix that.

Comment (shuangkun) [reply workflow/executor/taskresult.go:30]: Thanks, I modified it
