### PR TITLE
fix: prevent backoff when retryStrategy.limit has been reached. Fixes #7588

### LINKED ISSUE #7588: Backoff is applied even when `retryStrategy.limit` has been reached
## Summary

What happened/what you expected to happen?

When using `retryStrategy.backoff.limit: 2` and all child nodes (0 ; 1 and 2) already failed, I am expecting the parent node to fail immediatly as no more retries are allowed. Instead, after node 2 fails, new backoff is still applied (12mn in my case) and parent node fails later than expected.

image

What version of Argo Workflows are you running?
v3.2.4

## Diagnostics

I used this ClusterWorkflowTemplate (truncated) to emulate node durations on a failing `terraform apply` step. To be close to my use case, it takes longer on the first run (21mn) that on retries (5mn).

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: bootstrap-sandbox-infrastructure
spec:
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  securityContext:
    fsGroup: 1001
  templates:
    - name: terraform-apply-infrastructure
      retryStrategy:
        limit: 2
        backoff:
          duration: 3m
          factor: 2
          maxDuration: 60m
      container:
        image: hashicorp/terraform:v1.0.9
        imagePullPolicy: IfNotPresent
        workingDir: /sources/k8s-apps-descriptors/terraform
        command:
          - sh
        args:
          - -c
          - |
            set -eo pipefail
            mkdir -p /sources/tmp

            if [[ -f /sources/tmp/duration ]]; then
              duration="$(cat /sources/tmp/duration)"
            else
              duration="21m"
            fi
            sleep "${duration}"

            echo "5m" > /sources/tmp/duration
            exit 1
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false  # terraform needs /tmp
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - name: workdir
            mountPath: /sources
```

What Kubernetes provider are you using?
GKE v1.20.11-gke.1300

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

```bash
# Logs from the workflow controller:

time="2022-01-19T15:25:24.189Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: Backoff for 3 minutes 0 seconds" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:33:56.542Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: Backoff for 6 minutes 0 seconds" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:45:28.966Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: Backoff for 12 minutes 0 seconds" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
[...]
time="2022-01-19T15:57:39.032Z" level=info msg="node has maxDuration set, setting executionDeadline to: Wed Jan 19 16:04:02 +0000 (6 minutes from now)" namespace=apps-sbx-qo-pr-4337 node="bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2[0].main.terraform-apply-infrastructure" workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: " namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="No more retries left. Failing..." namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 phase Running -> Failed" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: No more retries left" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 finished: 2022-01-19 15:57:39.032781319 +0000 UTC" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by rohankmr414**
Signed-off-by: Rohan Kumar <rohankmr414@gmail.com>

Fixes #7588

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -913,7 +913,7 @@ func (woc *wfOperationCtx) processNodeRetries(node *wfv1.NodeStatus, retryStrate
 		}
 
 		// See if we have waited past the deadline
-		if time.Now().Before(waitingDeadline) {
+		if time.Now().Before(waitingDeadline) && int32(len(node.Children)) <= retryStrategy.Limit.IntVal {
```
Comment (simster7) [inline workflow/controller/operator.go:916]: Could you elaborate a bit on the logic here? I can't see how this would fix the issue. Also, this needs tests

**Review by simster7 — CHANGES_REQUESTED** [review]

File: workflow/controller/operator.go (hunk 1 above)
Comment (alexec) [reply workflow/controller/operator.go:916]: Can you please add a test?

Comment (rohankmr414) [reply workflow/controller/operator.go:916]: @alexec I'm not quiet sure what I'm supposed to change. Do I need to change something in this function?

https://github.com/argoproj/argo-workflows/blob/6855f4c51b5bd667599f072ae5ddde48967006f1/workflow/controller/operator_test.go#L723-L774

Comment (blkperl) [reply workflow/controller/operator.go:916]: @rohankmr414, were you able to write a test to reproduce the issue?

Comment (rohankmr414) [reply workflow/controller/operator.go:916]: @blkperl I'm running this workflow and it fails when retryStrategy.limit is reached without any unnecessary backoff after the final retry. Is there a way we can get the backoff count for tests?

```yaml
metadata:
  generateName: test-backoff-
spec:
  entrypoint: main
  templates:
    - name: main
      retryStrategy:
        limit: 2
        backoff:
          duration: 2s
          factor: 2
          maxDuration: 5m
      container:
        name: main
        image: 'argoproj/argosay:v2'
        args: [ exit, "1" ]
```

Comment (alexec) [reply workflow/controller/operator.go:916]: ` retryStrategy.Limit.IntVal` can be zero, I think you need to use a func.

This PR needs to have a test added to it please.

**Review by alexec — CHANGES_REQUESTED** [review]

**Comment by rohankmr414** [comment]
@alexec I've added the missing tests for retry limit can you please review it?

File: test/e2e/retry_test.go [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+func (s *RetryTestSuite) TestRetryLimit() {
+	s.Given().
+		Workflow(`
+metadata:
+  generateName: test-backoff-
+spec:
+  entrypoint: main
+  templates:
+    - name: main
```
Comment (alexec) [inline test/e2e/retry_test.go:29]: How does this test work?

Comment (rohankmr414) [reply test/e2e/retry_test.go:29]: the workflow fails with an exit code 1 and then initiates a retry, since the `limit` in the `retryStrategy` is set to 0, the workflow fails instantly and logs `No more retries left` as message

File: workflow/controller/operator.go (hunk 1 above)
Comment (rohankmr414) [reply workflow/controller/operator.go:904]: done
